### ISSUE TITLE
GeneratedList as input of CustomTarget is broken with VS backends

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1004]
Can be seen in the `common\113 generatorcustom` test: https://ci.appveyor.com/project/jpakkane/meson/build/1.0.925/job/p69h84wd9rtvkdns

```
Traceback (most recent call last):
  File "C:\projects\meson\mesonbuild\mesonmain.py", line 279, in run
    app.generate()
  File "C:\projects\meson\mesonbuild\mesonmain.py", line 169, in generate
    g.generate(intr)
  File "C:\projects\meson\mesonbuild\backend\vs2010backend.py", line 168, in generate
    self.generate_solution(sln_filename, projlist)
  File "C:\projects\meson\mesonbuild\backend\vs2010backend.py", line 233, in generate_solution
    all_deps = self.determine_deps(p)
  File "C:\projects\meson\mesonbuild\backend\vs2010backend.py", line 203, in determine_deps
    all_deps[d.get_id()] = True
AttributeError: 'GeneratedList' object has no attribute 'get_id'
```

**Comment by nioncode** [comment]
I'm currently on vacation, but I'll have a look at it after Christmas / New Year if it is not resolved by then.

**Comment by nirbheek** [comment]
Thanks!
