### ISSUE TITLE
linuxlike 13 cmake dependency test is flaky

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#10104]
**Describe the bug**
The `linuxlike: 13 cmake dependency` test sometimes fails.

**To Reproduce**
`./run_tests.py`

**Expected behavior**
Testsuite passes consistently.

**system parameters**
* Arch Linux
* Python 3.10.2
* Meson 0.62.0rc1 (this has happened in earlier versions and is not a new regression)
* Ninja 1.10.2
* CMake 3.22.3

<details><summary><strong>Test failure log</strong></summary>

```
================================== linuxlike: 13 cmake dependency ==================================
 

Build started at 2022-03-10T10:53:34.526895
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr -Dlibdir=lib -Dbackend=ninja
Python system: Linux
The Meson build system
Version: 0.62.0.rc1
Source dir: /build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency
Build dir: /build/meson/src/meson-0.62.0rc1/b 9863013ae1
Build type: native build
Project name: external CMake dependency
Project version: undefined
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/sanitycheckc.exe
C compiler for the host machine: cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (GCC) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the build machine: cc ld.bfd 2.38
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: c++ (gcc 11.2.0 "c++ (GCC) 11.2.0")
C++ linker for the build machine: c++ ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
[Errno 21] Is a directory: '/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake'
Unusable script '/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake'
Program cmake found: YES (/usr/bin/cmake)
CMake binary for 1 is cached.

Determining dependency 'ZLIB' with CMake executable '/usr/bin/cmake'
CMake Toolchain: Calling CMake once to generate the compiler state
Calling CMake (['/usr/bin/cmake']) in /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/__CMake_compiler_info__ with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-G"
  - "Ninja"
  - "-DCMAKE_TOOLCHAIN_FILE=/build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/__CMake_compiler_info__/CMakeMesonTempToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake1;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake2;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_pref_env"
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/cmake_ZLIB with:
  - "-DNAME=ZLIB"
  - "-DARCHS="
  - "-DVERSION="
  - "-DCOMPS="
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/cmake_ZLIB/CMakeMesonToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake1;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake2;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_pref_env"
Guessed CMake target 'ZLIB::ZLIB'
CMake TARGET:
  -- name:      ZLIB::ZLIB
  -- type:      UNKNOWN
  -- imported:  True
  -- properties: {
      'INTERFACE_INCLUDE_DIRECTORIES': ['/usr/include']
      'IMPORTED_CONFIGURATIONS': ['RELEASE']
      'IMPORTED_LOCATION_RELEASE': ['/usr/lib/libz.so']
     }
  -- tline: CMake TRACE: /usr/share/cmake/Modules/FindZLIB.cmake:131 add_library(['ZLIB::ZLIB', 'UNKNOWN', 'IMPORTED'])
Include Dirs:         ['/usr/include']
Compiler Options:     []
Libraries:            ['/usr/lib/libz.so']
Run-time dependency zlib found: YES 1.2.11
CMake binary for 1 is cached.

Determining dependency 'ZLIB' with CMake executable '/usr/bin/cmake'
Try CMake generator: auto
CMake TARGET:
  -- name:      ZLIB::ZLIB
  -- type:      UNKNOWN
  -- imported:  True
  -- properties: {
      'INTERFACE_INCLUDE_DIRECTORIES': ['/usr/include']
      'IMPORTED_CONFIGURATIONS': ['RELEASE']
      'IMPORTED_LOCATION_RELEASE': ['/usr/lib/libz.so']
     }
  -- tline: CMake TRACE: /usr/share/cmake/Modules/FindZLIB.cmake:131 add_library(['ZLIB::ZLIB', 'UNKNOWN', 'IMPORTED'])
Include Dirs:         ['/usr/include']
Compiler Options:     []
Libraries:            ['/usr/lib/libz.so']
Run-time dependency zlib (modules: ZLIB::ZLIB) found: YES 1.2.11
Adding test "zlibtest"
Adding test "zlibtest2"
CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency nvakuhrabnsdfasdf found: NO (tried cmake)
CMake binary for 1 is cached.

Determining dependency 'ZLIB' with CMake executable '/usr/bin/cmake'
Try CMake generator: auto
Dependency ZLIB not found: CMake: invalid module dfggh::hgfgag for ZLIB.
Try to explicitly specify one or more targets with the "modules" property.
Valid targets are:
['ZLIB::ZLIB']
Run-time dependency zlib found: NO 
CMake binary for 1 is cached.

Determining dependency 'cmMesonTestDep' with CMake executable '/usr/bin/cmake'
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/cmake_cmMesonTestDep with:
  - "-DNAME=cmMesonTestDep"
  - "-DARCHS="
  - "-DVERSION="
  - "-DCOMPS="
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/build/meson/src/meson-0.62.0rc1/b 9863013ae1/meson-private/cmake_cmMesonTestDep/CMakeMesonToolchainFile.cmake"
  - "."
  - "-DCMAKE_PREFIX_PATH=/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake1;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_fake2;/build/meson/src/meson-0.62.0rc1/test cases/linuxlike/13 cmake dependency/cmake_pref_env"
using old-style CMake variables for dependency cmMesonTestDep
Include Dirs:         ['/usr/include']
Compiler Definitions: []
Libraries:            ['/usr/lib/libz.so']
Run-time dependency cmmesontestdep found: YES
CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency cmmesontestf1 found: NO (tried cmake)

test cases/linuxlike/13 cmake dependency/meson.build:44:0: ERROR: Dependency "cmMesonTestF1" not found, tried cmake
expected "WARNING: Could not find and exact match for the CMake dependency cmMesonTestF1." not found in stdout 

Traceback (most recent call last):
  File "/build/meson/src/meson-0.62.0rc1/run_tests.py", line 294, in run_configure_inprocess
    returncode = mesonmain.run(commandlist, get_meson_script())
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/mesonmain.py", line 260, in run
    return CommandLineParser().run(args)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/msetup.py", line 301, in run
    app.generate()
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreter/interpreter.py", line 2664, in run
    super().run()
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 567, in assignment
    value = self.evaluate_statement(node.value)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreter/interpreter.py", line 1617, in func_dependency
    d = df.lookup(kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreter/dependencyfallbacks.py", line 352, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/interpreter/dependencyfallbacks.py", line 93, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/build/meson/src/meson-0.62.0rc1/mesonbuild/dependencies/detect.py", line 160, in find_external_dependency
    raise DependencyException(f'Dependency "{name}" not found' +
mesonbuild.dependencies.base.DependencyException: Dependency "cmMesonTestF1" not found, tried cmake
```

**Comment by eli-schwartz** [comment]
@psycholance

This is your mysterious ARM-only failures from https://gitlab.alpinelinux.org/alpine/aports/-/jobs/634942

**Comment by psycholance** [comment]
yep, looks the same as ours

**Comment by eli-schwartz** [comment]
Well, the question is if you kick it does it pass on another try.

**Comment by psycholance** [comment]
yeah, rerunning them fails it on some arches and passes on others (previously failed) randomly :)

**Comment by psycholance** [comment]
i'm alright with any amount of waiting :)

**Comment by heftig** [comment]
Or patch the test to skip until the issue is resolved:

```diff
diff --git i/test cases/linuxlike/13 cmake dependency/meson.build w/test cases/linuxlike/13 cmake dependency/meson.build
index 193ad184b..e94ba68ac 100644
--- i/test cases/linuxlike/13 cmake dependency/meson.build	
+++ w/test cases/linuxlike/13 cmake dependency/meson.build	
@@ -6,6 +6,8 @@ if not find_program('cmake', required: false).found()
   error('MESON_SKIP_TEST cmake binary not available.')
 endif
 
+error('MESON_SKIP_TEST flaky, see https://github.com/mesonbuild/meson/issues/10104')
+
 # Zlib is probably on all dev machines.
 
 dep = dependency('ZLIB', version : '>=1.2', method : 'cmake')
```

**Comment by tristan957** [comment]
Is this still happening?

**Comment by heftig** [comment]
Yeah, it is, with 1.2.0.

**Comment by tristan957** [comment]
@kiwixz any chance you would want to investigate this?

**Comment by kiwixz** [comment]
Left it running in a loop all day long on my machine, could not reproduce the failure

**Comment by kiwixz** [comment]
It was on Debian.  I booted up an arch VM to try and for some reason it was easier to reproduce.

The best reproducer I could find (also works on my debian now!): `while ./run_project_tests.py --only failing-meson platform-linux; do :; done`.

The problem seems be a unexpected value in `CMakeInfo.module_paths`.  This test requires a specific CMAKE_PREFIX_PATH; but meson caches the `CMakeInfo` in a global variable and tests are run in-process.
The test runner tries to work around this problem [here](https://github.com/mesonbuild/meson/blob/d4615369ffbfc0f9a769ca1fd3566056cfa5ef81/run_project_tests.py#L546) but this is fragile at best and will break with enough concurrency.

**Comment by heftig** [comment]
I'm still seeing this fail, sometimes.
