### ISSUE TITLE
Meson wrap tool certificate expired error

### ISSUE THREAD

**Issue by Code-Marmoset** [mesonbuild/meson#10135]
**Describe the bug**
Meson's wrapdb seems to be not working. the urlopen function in urllib throws a `[SSL: CERTIFICATE_VERIFY_FAILED]` error when you use `meson wrap list` or `meson wrap install` or any other wrap function. The error seems to indicate that some certificate has expired.
The full output is as follows:
```
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 146, in run
  File "mesonbuild\wrap\wraptool.py", line 223, in run
  File "mesonbuild\wrap\wraptool.py", line 66, in list_projects
  File "mesonbuild\wrap\wraptool.py", line 62, in get_releases
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Go into command line and type `meson wrap list` or any other meson wrap function

**Expected behavior**
List all the available packages from the wrapdb

**system parameters**
Meson native build
Windows 10 21H1 (OS Build 19043.1586)
Python 3.10.3
Meson 0.61.3
Ninja 1.10.2

**Comment by eli-schwartz** [comment]
The certificate works fine here, so I suspect this has something to do with your system's certificate store being out of date.

That being said, the error message is not ideal there... and `meson subprojects` handles this better, so it should be handled the same in `meson wrap`. I submitted a PR to fix this inconsistency at #10136.

**Comment by eli-schwartz** [comment]
I am not sure of the best way to update the certificates on Windows. That being said, if you cannot fix the outdated certificates you can manually download the .wrap files from your browser by visiting https://wrapdb.mesonbuild.com/ and copy them into your `subprojects/` directory.

(If you can reach that site in your browser, it proves the certificate is valid, at least to your browser if not to your current python installation.)

**Comment by Code-Marmoset** [comment]
I managed to fix this issue by going to the Let's Encrypt website and installing the R3 certificate. Everything works fine now.
