### ISSUE TITLE
gtkdoc ignore_headers support breaks gstreamer build

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#1020]
```
Building documentation for gstreamer
Traceback (most recent call last):
  File "/path/to/meson/meson.py", line 26, in <module>
    sys.exit(main())
  File "/path/to/meson/meson.py", line 23, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/path/to/meson/mesonbuild/mesonmain.py", line 249, in run
    sys.exit(run_script_command(args[1:]))
  File "/path/to/meson/mesonbuild/mesonmain.py", line 239, in run_script_command
    return cmdfunc(cmdargs)
  File "/path/to/meson/mesonbuild/scripts/gtkdochelper.py", line 182, in run
    options.ignore_headers.split('@@') if options.ignore_headers else [])
  File "/path/to/meson/mesonbuild/scripts/gtkdochelper.py", line 96, in build_gtkdoc
    '--ignore-headers=' + ignore_headers] + scan_args
TypeError: Can't convert 'list' object to str implicitly
```

It seems that this error is caused by https://github.com/mesonbuild/meson/pull/980. When `ignore_headers` is not used in the build file, it defaults to an empty list, not an empty string.

**Comment by lantw44** [comment]
@ebassi
