### ISSUE TITLE
Python unhandled exception when trying to add dependencies to a static lib

### ISSUE THREAD

**Issue by avetiso** [mesonbuild/meson#10219]
Adding `dependencies: deps` to my call to `static_library` fails with the stack trace seen at the bottom of this issue.

I am using Meson with Conan, and am fetching my dependencies in that manner. My dependency paths are ending up correctly in `conanbuildinfo.txt`. The version is specified there, so I do not declare the versions in the `meson.build` file.

Here is how I declared my deps:

```
deps = [
'active_record',
'active_remote',
'base64',
'checkmate',
'locale',
'queue'
]
```

Here is my call to static_library():
```
libgru = static_library('gru',
                         sources: sources,
                         include_directories: inc_dir,
                         dependencies: deps,
                         install: true,
                         install_dir: install_dir)
```

**To Reproduce**
Project level `meson.build`:
```
project('gru',
        'cpp',
        version : '0.0.0',
        default_options: 'cpp_std=c++17' 
        )

deps = [
'active_record',
'active_remote',
'base64',
'checkmate',
'locale',
'queue'
]


subdir('src')
```

src/ `meson.build`:
```
inc_dir = include_directories('gru')
# List of sources
# Sources format follows order of 'tree' command
sources = [
# ton of source files I've omitted for readability
]

# We're assuming that there will be no private .h files here because we typically
# expect all models to be public facing. Add them to the persistent sources.
output = run_command('find', '_internal/generated', '-name', '*.cpp', check: true)
sources += output.stdout().strip().split('\n')

# Conan exports to a build dir, and then Meson creates its own
# additional build dir, so we have to step up one directory because
# Conan packages from the directory it created, not Meson's.
install_dir = join_paths(meson.global_build_root(), '../lib')

libgru = static_library('gru',
                         sources: sources,
                         include_directories: inc_dir,
                         dependencies: deps,
                         install: true,
                         install_dir: install_dir)

# Include the public interface of the library for use in the testing executable.
pub_inc = include_directories('.')
```

**Expected behavior**
Expected Meson to find the dependencies that conan has downloaded and populated into the conanbuildinfo.txt file.

**system parameters**
Native build, armv8.
MacOS 12.3
Python 3.9.12
Meson 0.62.0
Ninja 1.10.2

STACK TRACE:
```
gru/0.0.0@mx/stable: Calling generate()
gru/0.0.0@mx/stable: Aggregating env generators
gru/0.0.0@mx/stable: Calling build()
The Meson build system
Version: 0.62.0
Source dir: /Users/dario.avetisov/.conan/data/gru/0.0.0/mx/stable/build/343cef55aa43dc218ea7a74169ed4a6b9d605f29
Build dir: /Users/dario.avetisov/.conan/data/gru/0.0.0/mx/stable/build/343cef55aa43dc218ea7a74169ed4a6b9d605f29/build
Build type: cross build
Project name: gru
Project version: 0.0.0
C++ compiler for the host machine: clang++ (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2)")
C++ linker for the host machine: clang++ ld64 762
C++ compiler for the build machine: c++ (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2)")
C++ linker for the build machine: c++ ld64 762
Build machine cpu family: aarch64
Build machine cpu: arm64
Host machine cpu family: aarch64
Host machine cpu: arm64
Target machine cpu family: aarch64
Target machine cpu: arm64
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/msetup.py", line 301, in run
    app.generate()
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2698, in run
    super().run()
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2198, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 567, in assignment
    value = self.evaluate_statement(node.value)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1660, in func_static_lib
    return self.build_target(node, args, kwargs, build.StaticLibrary)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2940, in build_target
    target = targetclass(name, self.subdir, self.subproject, for_machine, srcs, struct, objs, self.environment, kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/build.py", line 1983, in __init__
    super().__init__(name, subdir, subproject, for_machine, sources, structured_sources, objects, environment, kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/build.py", line 776, in __init__
    self.process_kwargs(kwargs, environment)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/build.py", line 2028, in process_kwargs
    super().process_kwargs(kwargs, environment)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/build.py", line 1200, in process_kwargs
    self.add_deps(deplist)
  File "/opt/homebrew/lib/python3.9/site-packages/mesonbuild/build.py", line 1373, in add_deps
    dep_d_features = dep.d_features
AttributeError: 'str' object has no attribute 'd_features'

src/meson.build:319:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
gru/0.0.0@mx/stable: 
gru/0.0.0@mx/stable: ERROR: Package '343cef55aa43dc218ea7a74169ed4a6b9d605f29' build failed
gru/0.0.0@mx/stable: WARN: Build folder /Users/dario.avetisov/.conan/data/gru/0.0.0/mx/stable/build/343cef55aa43dc218ea7a74169ed4a6b9d605f29
ERROR: gru/0.0.0@mx/stable: Error in build() method, line 37
        meson.configure(args=cross_args, build_dir="build")
        ConanException: Error 2 while executing meson "/Users/dario.avetisov/.conan/data/gru/0.0.0/mx/stable/build/343cef55aa43dc218ea7a74169ed4a6b9d605f29" "build" --backend=ninja -Dprefix="/Users/dario.avetisov/.conan/data/gru/0.0.0/mx/stable/package/343cef55aa43dc218ea7a74169ed4a6b9d605f29" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="shared" '--cross-file' 'conan_meson_native.ini' --buildtype=release
```

**Comment by avetiso** [comment]
I have this conanbuildinfo.txt with a bunch of info about the projects dependencies. They are all built with Cmake. This is probably the most relevant part of that file with the include_dirs. How would I consume it in Meson and tell meson where to find the includes and libs for each dep?

```
[includedirs]
/Users/dario.avetisov/.conan/data/active_record/1.53.3/mx/stable/package/0025a6d31b54a7fa6690eaf4b7f07dcac703754d/include
/Users/dario.avetisov/.conan/data/active_remote/2.36.2/mx/stable/package/3c8e841d55716239a9911665d1ffd7bc43cac6de/include
/Users/dario.avetisov/.conan/data/checkmate/1.36.6/mx/stable/package/2b2a4eb93a8d80ad9fdf6c2d032a1cca001d7b2c/include
/Users/dario.avetisov/.conan/data/locale/1.39.2/mx/stable/package/a727b834c705c7da7d207a8ab5c47ea11badfedc/include
/Users/dario.avetisov/.conan/data/queue/1.32.2/mx/stable/package/98501773423965b658c32de4719df520dd175e60/include
/Users/dario.avetisov/.conan/data/common/1.34.2/mx/stable/package/41276176b6768f126e9a0f0185572e212f974cbf/include
/Users/dario.avetisov/.conan/data/sqlite3/3.26.0-6/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/include
/Users/dario.avetisov/.conan/data/curl/7.79.1-0/mx/stable/package/b46591a7948af4a09fe30c9af4096239197051f6/include
/Users/dario.avetisov/.conan/data/opencv/3.4.11-5/mx/stable/package/7a6cc83fade841338b570c6a832371feb941349d/include
/Users/dario.avetisov/.conan/data/tiny_dnn/2017.8.25-4/mx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
/Users/dario.avetisov/.conan/data/base64/1.0.0-5/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/include
/Users/dario.avetisov/.conan/data/openssl/1.1.1k-1/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/include
/Users/dario.avetisov/.conan/data/zlib/1.2.11-8/mx/stable/package/65b5071e1e8fefd56dd859ce0171993880d17623/include
/Users/dario.avetisov/.conan/data/cereal/1.2.2-2/mx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include

[libdirs]
/Users/dario.avetisov/.conan/data/active_record/1.53.3/mx/stable/package/0025a6d31b54a7fa6690eaf4b7f07dcac703754d/lib
/Users/dario.avetisov/.conan/data/active_remote/2.36.2/mx/stable/package/3c8e841d55716239a9911665d1ffd7bc43cac6de/lib
/Users/dario.avetisov/.conan/data/checkmate/1.36.6/mx/stable/package/2b2a4eb93a8d80ad9fdf6c2d032a1cca001d7b2c/lib
/Users/dario.avetisov/.conan/data/locale/1.39.2/mx/stable/package/a727b834c705c7da7d207a8ab5c47ea11badfedc/lib
/Users/dario.avetisov/.conan/data/queue/1.32.2/mx/stable/package/98501773423965b658c32de4719df520dd175e60/lib
/Users/dario.avetisov/.conan/data/common/1.34.2/mx/stable/package/41276176b6768f126e9a0f0185572e212f974cbf/lib
/Users/dario.avetisov/.conan/data/sqlite3/3.26.0-6/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/lib
/Users/dario.avetisov/.conan/data/curl/7.79.1-0/mx/stable/package/b46591a7948af4a09fe30c9af4096239197051f6/lib
/Users/dario.avetisov/.conan/data/opencv/3.4.11-5/mx/stable/package/7a6cc83fade841338b570c6a832371feb941349d/lib
/Users/dario.avetisov/.conan/data/base64/1.0.0-5/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/lib
/Users/dario.avetisov/.conan/data/openssl/1.1.1k-1/mx/stable/package/69396a1e403c24f601452a2d014779f30099e4ab/lib
/Users/dario.avetisov/.conan/data/zlib/1.2.11-8/mx/stable/package/65b5071e1e8fefd56dd859ce0171993880d17623/lib
```

**Comment by avetiso** [comment]
Think I made a simple error here, closing until I investigate further.

**Comment by eli-schwartz** [comment]
> ```
> AttributeError: 'str' object has no attribute 'd_features'
> 
> src/meson.build:319:0: ERROR: Unhandled python exception
> 
>     This is a Meson bug and should be reported!
> ```

Future versions of Meson will hopefully have better type checking for static_library, which is the main holdout for validating the types of arguments.

It will error out without a stack trace, just an "ERROR: static_library keyword argument 'dependencies' was of type array[str] but should have been array[Dependency]"

Per https://mesonbuild.com/Reference-manual_functions.html#static_library

> one or more dependency objects created with [dependency()](https://mesonbuild.com/Reference-manual_functions.html#dependency) or [compiler.find_library()](https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library) (for external deps) or [declare_dependency()](https://mesonbuild.com/Reference-manual_functions.html#declare_dependency) (for deps built by the project)

You can use `compiler.find_library()` for each of those strings to locate them as system library objects, I suppose.

**Comment by avetiso** [comment]
Just in case anyone had the same question:

Use the conan generator 'cmake_find_package' and consume said dependencies in meson like this: your_dep = dependency('lib_name', cmake_module_path: meson.source_root()).
