### ISSUE TITLE
Meson 0.6.2 configure error building libadwaita on i686 (regression from 0.61.3)

### ISSUE THREAD

**Issue by satmandu** [mesonbuild/meson#10211]
Error when building libadwaita on linux `i686` (ChromeOS/Chromebrew) **(This is a regression from 0.61.3, which works fine.)**

```
The Meson build system
Version: 0.62.0
Source dir: /usr/local/tmp/crew/libadwaita.20220330014121.dir
Build dir: /usr/local/tmp/crew/libadwaita.20220330014121.dir/builddir
Build type: native build
Project name: libadwaita
Project version: 1.0.3
C compiler for the host machine: cc (gcc 11.2.1 "cc (GCC) 11.2.1 20220305")
C linker for the host machine: cc ld.gold 2.38
Host machine cpu family: x86
Host machine cpu: i686
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wdate-time: YES 
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=missing-declarations: YES 
Compiler for C supports arguments -Werror=overflow: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=shift-count-overflow: YES 
Compiler for C supports arguments -Werror=shift-overflow=2: YES 
Compiler for C supports arguments -Werror=implicit-fallthrough=3: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmaybe-uninitialized: YES 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-strict-aliasing: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wswitch-enum: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-function: YES 
Compiler for C supports arguments -fstack-protector-strong: YES 
Program sassc found: YES (/usr/local/bin/sassc)
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/local/bin/glib-compile-resources)
Program glib-compile-resources found: YES (/usr/local/bin/glib-compile-resources)
Configuring adw-version.h using configuration
Program glib-mkenums found: YES (/usr/local/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/local/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/local/bin/glib-mkenums)
Program glib-mkenums found: YES (/usr/local/bin/glib-mkenums)
Program sed found: YES (/usr/local/bin/sed)
Program gen-public-types.sh found: YES (/bin/sh /usr/local/tmp/crew/libadwaita.20220330014121.dir/src/gen-public-types.sh)
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency gio-2.0 found: YES 2.71.3
Run-time dependency gtk4 found: YES 4.6.2
Run-time dependency glib-2.0 found: YES 2.71.3
Run-time dependency fribidi found: YES 1.0.10
Library m found: YES
Configuring config.h using configuration
Checking if "ld_supports_version_script" : links: YES 
Run-time dependency gobject-introspection-1.0 found: YES 1.70.0
Dependency gobject-introspection-1.0 found: YES 1.70.0 (cached)
Program g-ir-scanner found: YES (/usr/local/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.70.0 (cached)
Program g-ir-compiler found: YES (/usr/local/bin/g-ir-compiler)
Program vapigen found: YES (/usr/local/bin/vapigen)
Program msgfmt found: YES (/usr/local/bin/msgfmt)
Program msginit found: YES (/usr/local/bin/msginit)
Program msgmerge found: YES (/usr/local/bin/msgmerge)
Program xgettext found: YES (/usr/local/bin/xgettext)
Program desktop-file-validate found: NO
Program date found: YES (/usr/local/bin/date)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Configuring org.gnome.Adwaita1.Demo.metainfo.xml.in using configuration
Program appstream-util found: YES (/usr/local/bin/appstream-util)
Program glib-compile-resources found: YES (/usr/local/bin/glib-compile-resources)
Dependency gtk4 found: YES 4.6.2 (cached)
Dependency libadwaita-1 found: YES 1.0.3 (overridden)
Configuring run using configuration
Build targets in project: 95

libadwaita 1.0.3

  Options
    Tests        : True
    Examples     : True
    Documentation: False
    Introspection: True
    Vapi         : True

  User defined options
    buildtype    : release
    libdir       : /usr/local/lib
    mandir       : /usr/local/share/man
    prefix       : /usr/local
    strip        : true
    b_lto        : true
    b_pie        : true
    c_args       : -O2
    cpp_args     : -O2
    gtk_doc      : false
    introspection: enabled

Found ninja-1.10.2 at /usr/local/bin/ninja
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/mconf.py", line 334, in run
    c.print_conf()
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/mconf.py", line 297, in print_conf
    self.print_aligned()
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/mconf.py", line 141, in print_aligned
    desc = textwrap.wrap(line[3], four_column[3])
  File "/usr/local/lib/python3.10/textwrap.py", line 387, in wrap
    return w.wrap(text)
  File "/usr/local/lib/python3.10/textwrap.py", line 362, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/local/lib/python3.10/textwrap.py", line 256, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -4 (must be > 0)
Core properties:
  Source dir /usr/local/tmp/crew/libadwaita.20220330014121.dir
  Build dir  /usr/local/tmp/crew/libadwaita.20220330014121.dir/builddir

Main project options:
  

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Attempted to build on ChromeOS/i686 with meson 0.62.0. Docker container to replicate available on request.
[meson.build](https://github.com/mesonbuild/meson/files/8376361/libadwaita.meson.build.txt)

**Expected behavior**
The configure should succeed (as it does for other architectures.)

**system parameters**
* plain native build (for the same computer)
* `ChromeOS/Chromebrew i686 Milestone 58`
* what Python version are you using: `3.10.2`
* what `meson --version` `60.2.0`
* what `ninja --version` `1.10.2`

**Comment by eli-schwartz** [comment]
This error only comes from `meson configure`, which does nothing other than print the currently configured options for easy reading. So it should not be causing build failures.

Looking at the code, we seem to assume that the minimum width of your terminal is always at least 60.

This logic came from commit d3003ebb419ba867adfaa649bcfa3d45c03f0bf5 which has been there since 0.58.0, cc @dcbaker

**Comment by satmandu** [comment]
Ah! We are exiting when `meson configure` throws an error.

Is there a way to keep `meson configure` from breaking when it gets confused about the terminal width? We're running this from inside a ruby script. Reverting to 0.61.3 reliably fixes this, and upgrading to 0.62.0 reliably breaks it.

**Comment by dcbaker** [comment]
As a workaround, you might be able to set the COLUMNS env var in the script

**Comment by eli-schwartz** [comment]
Well, I don't get why 0.61.3 -> 0.62.0 would change anything.

**Comment by dcbaker** [comment]
Did you happen to change python versions, the minimum changed in 0.62

**Comment by satmandu** [comment]
We are using Python 3.10.3 at the moment.

**Comment by satmandu** [comment]
I think my root issue was starting a build from Termux, which defaults to a column width of less than 60.... starting from a larger console fixed the issue.
