### ISSUE TITLE
custom targets don't handle extraced objects input containing custom target generated sources

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#10394]
Hi,

When a custom target has build_tgt.extract_all_objects() as the source and the build_tgt has another custom target as the input, meson fails with a backtrace.

Repro:

```meson
project('foo', ['c'])

test2_c = custom_target(output: 'test.c', command: ['echo', 'int foo;'])

lib1 = static_library('l1', test2_c)

custom_target(
  input: lib1.extract_all_objects(recursive: false),
  output: 'test.txt',
  command: ['echo', '@INPUT@'],
  capture: true,
)
```

results in:
```
The Meson build system
Version: 0.62.99
Source dir: /tmp/repro
Build dir: /tmp/repro/build
Build type: native build
Project name: foo
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (Debian 11.3.0-1) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Traceback (most recent call last):
  File "/home/andres/src/meson/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "/home/andres/src/meson/mesonbuild/msetup.py", line 303, in run
    app.generate()
  File "/home/andres/src/meson/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/home/andres/src/meson/mesonbuild/msetup.py", line 230, in _generate
    intr.run()
  File "/home/andres/src/meson/mesonbuild/interpreter/interpreter.py", line 2766, in run
    super().run()
  File "/home/andres/src/meson/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/andres/src/meson/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/home/andres/src/meson/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/andres/src/meson/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/home/andres/src/meson/mesonbuild/interpreterbase/interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "/home/andres/src/meson/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/home/andres/src/meson/mesonbuild/interpreterbase/decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/andres/src/meson/mesonbuild/interpreter/interpreter.py", line 1914, in func_custom_target
    tg = build.CustomTarget(
  File "/home/andres/src/meson/mesonbuild/build.py", line 2436, in __init__
    get_sources_string_names(sources, backend),
  File "/home/andres/src/meson/mesonbuild/build.py", line 2838, in get_sources_string_names
    names += s.get_outputs(backend)
  File "/home/andres/src/meson/mesonbuild/build.py", line 439, in get_outputs
    return [
  File "/home/andres/src/meson/mesonbuild/build.py", line 440, in <listcomp>
    backend.object_filename_from_source(self.target, source)
  File "/home/andres/src/meson/mesonbuild/backend/backends.py", line 778, in object_filename_from_source
    assert isinstance(source, mesonlib.File)
AssertionError

meson.build:7:0: ERROR: Unhandled python exception
```

Regards,

Andres Freund

**Comment by anarazel** [comment]
For context: The reason I need this is to build a binary with dtrace probes. Which on at least freebsd and solaris requires to call dtrace -G with all the object files as input, which are modified, generating a new object file with probe symbols. To build the final executable / library the modified object files and the dtrace generated object file have to be linked.  In postgres' case that triggers this problem, because postgres contains (quite a few) generated sources.

**Comment by anarazel** [comment]
Looks to me like the problem is around
https://github.com/mesonbuild/meson/blob/b1abda2b4b9ea85551abe073b55092848285ccca/mesonbuild/build.py#L410-L412
not being helped by the fact that `object_filename_from_source()` is annotated to accept `FileOrString`, yet immediately asserts that source is a file:
https://github.com/mesonbuild/meson/blob/b1abda2b4b9ea85551abe073b55092848285ccca/mesonbuild/backend/backends.py#L777-L778

ISTM that `ExtractedObjects::get_sources()` could generate actual filenames for the generated sources, despite what the comment says? Something like `sources.append(File(True, gensrc.get_subdir(), s))` might be sufficient?

**Comment by anarazel** [comment]
Thanks @bonzini and @dcbaker!
