### ISSUE TITLE
not found: mesonbuild.dependencies.data

### ISSUE THREAD

**Issue by burgertron6** [mesonbuild/meson#10406]
**Describe the bug**
An "Unhandled python exception" when attempting to configure a build.

**To Reproduce**
Attempt to build [GLib 2.72.1](https://download.gnome.org/sources/glib/2.72/?C=M&O=D), using `meson _build`

**Expected behavior**
A successful build configuration.

**system parameters**
* Native build, aarch64
* macOS Monterey, Version 12.4 (21F79)
* Python 3.8.9
* Meson 0.62.1
* Ninja 1.10.2

```
Traceback (most recent call last):
  File "mesonbuild/mesonmain.py", line 153, in run
  File "mesonbuild/msetup.py", line 301, in run
  File "mesonbuild/msetup.py", line 185, in generate
  File "mesonbuild/msetup.py", line 229, in _generate
  File "mesonbuild/interpreter/interpreter.py", line 2700, in run
  File "mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
  File "mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
  File "mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
  File "mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
  File "mesonbuild/interpreterbase/interpreterbase.py", line 567, in assignment
  File "mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
  File "mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
  File "mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
  File "mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
  File "mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
  [Previous line repeated 5 more times]
  File "mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
  File "mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
  File "mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
  File "mesonbuild/interpreter/interpreter.py", line 1620, in func_dependency
  File "mesonbuild/interpreter/dependencyfallbacks.py", line 352, in lookup
  File "mesonbuild/interpreter/dependencyfallbacks.py", line 93, in _do_dependency
  File "mesonbuild/dependencies/detect.py", line 112, in find_external_dependency
  File "mesonbuild/dependencies/cmake.py", line 135, in __init__
  File "mesonbuild/dependencies/cmake.py", line 183, in _get_cmake_info
  File "mesonbuild/dependencies/cmake.py", line 614, in _call_cmake
  File "mesonbuild/dependencies/cmake.py", line 585, in _setup_cmake_dir
  File "importlib/resources.py", line 169, in read_text
  File "importlib/resources.py", line 126, in open_text
  File "importlib/resources.py", line 82, in _check_location
FileNotFoundError: Package has no location <module 'mesonbuild.dependencies.data' (namespace)>

meson.build:2027:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by eli-schwartz** [comment]
This is supposed to be fixed by #10230, are you absolutely sure you are using 0.62.1 and not 0.62.0 instead?

**Comment by mjakeman** [comment]
This seems to be fixed in 0.62.2.

I'm able to reproduce this on ARM Monterey (12.4) using the pkg installer for [0.62.1](https://github.com/mesonbuild/meson/releases/tag/0.62.1). If I switch to using meson 0.62.2 installed from either homebrew or pip (as there doesn't seem to be an installer available?) then I don't encounter this issue on the same codebase.

**Comment by Arkaaito** [comment]
I'm seeing the same behavior on Intel Big Sur (11.6.5) after using the 0.63.0 installer.  The stack trace is also the same modulo some tiny differences in line numbers:

    Traceback (most recent call last):
      File "mesonbuild/mesonmain.py", line 151, in run
      File "mesonbuild/msetup.py", line 303, in run
      File "mesonbuild/msetup.py", line 186, in generate
      File "mesonbuild/msetup.py", line 230, in _generate
      File "mesonbuild/interpreter/interpreter.py", line 2803, in run
      File "mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
      File "mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
      File "mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
      File "mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
      File "mesonbuild/interpreterbase/interpreterbase.py", line 462, in function_call
      File "mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
      File "mesonbuild/interpreterbase/decorators.py", line 580, in wrapper
      File "mesonbuild/interpreter/interpreter.py", line 2271, in func_subdir
      File "mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
      File "mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
      File "mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
      File "mesonbuild/interpreterbase/interpreterbase.py", line 574, in assignment
      File "mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
      File "mesonbuild/interpreterbase/interpreterbase.py", line 462, in function_call
      File "mesonbuild/interpreterbase/decorators.py", line 774, in wrapped
      File "mesonbuild/interpreterbase/decorators.py", line 774, in wrapped
      File "mesonbuild/interpreterbase/decorators.py", line 774, in wrapped
      [Previous line repeated 5 more times]
      File "mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
      File "mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
      File "mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
      File "mesonbuild/interpreter/interpreter.py", line 1670, in func_dependency
      File "mesonbuild/interpreter/dependencyfallbacks.py", line 354, in lookup
      File "mesonbuild/interpreter/dependencyfallbacks.py", line 95, in _do_dependency
      File "mesonbuild/dependencies/detect.py", line 112, in find_external_dependency
      File "mesonbuild/dependencies/cmake.py", line 137, in __init__
      File "mesonbuild/dependencies/cmake.py", line 185, in _get_cmake_info
      File "mesonbuild/dependencies/cmake.py", line 616, in _call_cmake
      File "mesonbuild/dependencies/cmake.py", line 587, in _setup_cmake_dir
      File "importlib/resources.py", line 169, in read_text
      File "importlib/resources.py", line 126, in open_text
      File "importlib/resources.py", line 82, in _check_location
    FileNotFoundError: Package has no location <module 'mesonbuild.dependencies.data' (namespace)>
    
    src/meson.build:52:0: ERROR: Unhandled python exception
    
        This is a Meson bug and should be reported!
    (base) MacBook-Pro-2:peek arkaaito$ meson --version
    0.63.0

**Comment by eli-schwartz** [comment]
I'd be pretty interested to see what the embedded contents of the pyinstaller frozen executable are, particularly with regard to `mesonbuild.dependencies`. Unfortunately, I don't have a macOS machine to experiment with.

**Comment by JamBalaya56562** [comment]
Thank you for the report. This was a packaging problem specific to the frozen (PyInstaller) macOS `.pkg` installer, where `mesonbuild/dependencies/data` wasn't bundled, so `importlib.resources` couldn't load the CMake templates. Two things resolve it:

The PyInstaller hook now explicitly collects that data package:

```python
# packaging/hook-mesonbuild.py
datas += collect_data_files('mesonbuild.dependencies.data')
...
hiddenimports += get_all_modules_from_dir('mesonbuild/dependencies')
```

And the affected artifact itself is no longer produced — the macOS `.pkg` installer was discontinued after 1.0.0; current releases ship wheels, the source tarball, and `meson.pyz`, and installing via `pip`/`pipx`/Homebrew/`meson.pyz` was already reported to work in this thread.

**Verification:** `packaging/hook-mesonbuild.py` collects `mesonbuild.dependencies.data` (added in PR #10230, commit [`7ceec99c`](https://github.com/mesonbuild/meson/commit/7ceec99c55c8534f6c0ec287e0ca7092a8c29ef5)).

Since the bundling was fixed and the frozen macOS installer that triggered this is no longer distributed, this looks safe to close. Please reopen if you can reproduce with a currently supported install method.
