### ISSUE TITLE
Run more language and framework tests on Windows

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1041]
Looking at https://www.appveyor.com/docs/installed-software/, we can run at least the following language and framework tests:

csharp
fortran (with MinGW)
frameworks/1 boost
frameworks/4 qt

We should also run our tests against MinGW.

**Comment by msink** [comment]
cross-comliner: armv7hl-unknown-linux-gnueabi-gcc from cygwin, native: mingw64 gcc
```
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7hl'
endian = 'little'

[binaries]
c = 'f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-gcc'
cpp = 'f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-g++'
ar = 'f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-ar'
strip = 'f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-strip'
pkgconfig = 'f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-config'

[properties]
root = 'f:/cygwin64/usr/armv7hl-unknown-linux-gnueabi'
```
```
project('hello', ['c'])
zlib = dependency('zlib', version: '>=1.2.3')
exe = executable('hello', sources: 'hello.c', dependencies: zlib)
```
crash:
```
The Meson build system
Version: 0.37.0.dev1
Source dir: F:\avian\hello
Build dir: F:\avian\hello\build\linux-arm32
Build type: cross build
Project name: hello
Native c compiler: gcc (gcc 4.8.1)
Cross c compiler: f:/cygwin64/bin/armv7hl-unknown-linux-gnueabi-gcc (gcc 4.8.2)
Host machine cpu family: arm
Host machine cpu: armv7hl
Target machine cpu family: arm
Target machine cpu: armv7hl
Build machine cpu family: x86_64                                                                                    12:31Build machine cpu: x86_64
Found pkg-config: f:\cygwin64\bin\pkg-config.EXE (0.29.1)
Traceback (most recent call last):
  File "F:\avian\meson\mesonbuild\mesonmain.py", line 283, in run
    app.generate()
  File "F:\avian\meson\mesonbuild\mesonmain.py", line 171, in generate
    intr.run()
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1336, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1358, in evaluate_codeblock
    raise e
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1352, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1475, in evaluate_statement
    return self.assignment(cur)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 2507, in assignment
    value = self.evaluate_statement(node.value)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1473, in evaluate_statement
    return self.function_call(cur)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "F:\avian\meson\mesonbuild\interpreter.py", line 1899, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "F:\avian\meson\mesonbuild\dependencies.py", line 1354, in find_external_dependency
    raise pkg_exc
  File "F:\avian\meson\mesonbuild\dependencies.py", line 1343, in find_external_dependency
    pkgdep = PkgConfigDependency(name, environment, kwargs)
  File "F:\avian\meson\mesonbuild\dependencies.py", line 131, in __init__
    ret, self.modversion = self._call_pkgbin(['--modversion', name])
  File "F:\avian\meson\mesonbuild\dependencies.py", line 166, in _call_pkgbin
    env=os.environ, universal_newlines=True)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

**Comment by NickeZ** [comment]
Boost now runs on windows

**Comment by nirbheek** [comment]
csharp is https://github.com/mesonbuild/meson/pull/2249, so the only things left are fortran (mingw) and qt.

**Comment by jon-turney** [comment]
After #3060, for `frameworks/4 qt` we probably only need to set some env var in the .appveyor.yml so the installed Qt can be found

**Comment by jon-turney** [comment]
A similar audit needs to be done for azure.
