### ISSUE TITLE
Unhandled exception during install with -Dstrip=true for Python extension module on Windows 10 

### ISSUE THREAD

**Issue by rkalnins** [mesonbuild/meson#10420]
**Describe the bug**
Unhandled exception occurs during `meson install` with `-Dstrip=true` for Python extension modules written in Cython on Windows 10.

**To Reproduce**

Minimal example:
https://github.com/rkalnins/meson-bug-report-windows-strip

```bash
meson setup -Dstrip=true build # install is successful without -Dstrip=true
meson compile -Cbuild
meson install -Cbuild --destdir=tmp-staging
```

```bash
C:\Users\rkalnins\dev\winbuild-test>meson install -Cbuild --destdir=tmp-staging
ninja: Entering directory `C:\Users\rkalnins\dev\winbuild-test\build'
ninja: no work to do.
Installing wintest\foo.cp38-win_amd64.pyd to C:\Users\rkalnins\dev\winbuild-test\build\tmp-staging/Lib\site-packages\wintest
Stripping target 'wintest\\foo.cp38-win_amd64.pyd'.
Traceback (most recent call last):
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\minstall.py", line 771, in run
    installer.do_install(datafilename)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\minstall.py", line 550, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\minstall.py", line 706, in install_targets
    self.do_strip(d.strip_bin, fname, outname)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\minstall.py", line 574, in do_strip
    returncode, stdo, stde = self.Popen_safe(strip_bin + [outname])
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\minstall.py", line 365, in Popen_safe
    p, o, e = Popen_safe(*args, **kwargs)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1406, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1422, in Popen_safe_legacy
    p = subprocess.Popen(args, universal_newlines=False, close_fds=False,
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\rkalnins\appdata\local\programs\python\python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

Abbreviated build directory contents
```bash
C:\USERS\RKALNINS\DEV\WINBUILD-TEST\BUILD
├───meson-info
├───meson-logs
├───meson-private
├───tmp-staging
│   └───Lib
│       └───site-packages
│           └───wintest
│                   foo.cp38-win_amd64.pyd
│
└───wintest
    │   foo.cp38-win_amd64.exp
    │   foo.cp38-win_amd64.lib
    │   foo.cp38-win_amd64.pyd
    │
    └───foo.cp38-win_amd64.pyd.p
        │   meson-generated_wintest_foo.pyx.c.obj
        │
        └───wintest
                foo.pyx.c
```

**Expected behavior**
`wintest\foo.cp38-win_amd64.pyd` should be stripped and installed correctly (see dry run below)

```
C:\Users\rkalnins\dev\winbuild-test>meson install -Cbuild --destdir=tmp-staging--dry-run
ninja: Entering directory `C:\Users\rkalnins\dev\winbuild-test\build'
ninja: no work to do.
Installing wintest\foo.cp38-win_amd64.pyd to C:\Users\rkalnins\dev\winbuild-test\build\tmp-staging/Lib\site-packages\wintest
Stripping target 'wintest\\foo.cp38-win_amd64.pyd'.
Installing wintest\foo.cp38-win_amd64.lib to C:\Users\rkalnins\dev\winbuild-test\build\tmp-staging/Lib\site-packages\wintest
Installing C:\Users\rkalnins\dev\winbuild-test\wintest\__init__.py to C:\Users\rkalnins\dev\winbuild-test\build\tmp-staging/Lib\site-packages\wintest
Installing C:\Users\rkalnins\dev\winbuild-test\wintest\test.py to C:\Users\rkalnins\dev\winbuild-test\build\tmp-staging/Lib\site-packages\wintest
```

**System parameters**
- Native build on Windows 10
- `MSVC` Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29924 for x64
- `ninja` 1.10.2.git.kitware.jobserver-1
- `Python` 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
- `Cython` 3.0.0a9
- `meson` 0.62.1

**Comment by rkalnins** [comment]
If strip is not necessary, workaround is to simply not strip but unable to change the default options (`-Dstrip=true`) set when using `meson-python` per https://github.com/FFY00/meson-python/pull/50 and https://github.com/FFY00/meson-python/issues/27

**Comment by eli-schwartz** [comment]
This is weird. We explicitly check that it is not None before trying to use it, but as far as I can tell when we generate it in the backend it is always `'strip'` and we don't actually try to find it. That being said, before b9274681375b39d4b63f8ece1ced6dcf18789a4f we still just unconditionally ran `Popen_safe(['strip', outname])` and assumed that strip will exist.

Either way, though, `-Dstrip=true` is not the default, when you explicitly opt into strip we should actually look up the strip binary and fail with a sensible error message when it's not available. This would mean the error moves to setup time rather than install time. If we want a "strip only when you can" option I would think that should be a feature option ("auto" value)...

Hmm.

**Comment by rkalnins** [comment]
Let me know if there’s anything else you need or anything you’d like to see. 

> Either way, though, `-Dstrip=true` is not the default

I understand `meson` is not stripping by default but `meson-python` (a pep517 backend) has been temporarily hard-coded to strip by default to satisfy an upcoming SciPy release requirement and not something I can change.

**Comment by xclaesse** [comment]
Note that even without `-Dstrip=true` you can still strip with `meson install --strip` since 0.62.0.
