### ISSUE TITLE
Unhandled python exception when attempting to use clang-cl

### ISSUE THREAD

**Issue by TyBalduf** [mesonbuild/meson#10439]
**Describe the bug**
I get an unhandled python exception if I try to use the `clang-cl` C compiler in a mingw64 shell. 

```
The Meson build system
Version: 0.62.99
Source dir: C:/msys64/home/balduf/xtb
Build dir: C:/msys64/home/balduf/xtb/build
Build type: native build
Project name: xtb
Project version: 6.5.0
Fortran compiler for the host machine: ifort (intel-cl 2021.5.0)
Fortran linker for the host machine: xilink.exe xilink 2021.5.0
Traceback (most recent call last):
  File "C:/msys64/home/balduf/meson/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "C:/msys64/home/balduf/meson/mesonbuild/msetup.py", line 304, in run
    app.generate()
  File "C:/msys64/home/balduf/meson/mesonbuild/msetup.py", line 187, in generate
    self._generate(env)
  File "C:/msys64/home/balduf/meson/mesonbuild/msetup.py", line 209, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreter/interpreter.py", line 320, in __init__
    self.parse_project()
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreterbase/decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreter/interpreter.py", line 1233, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreter/interpreter.py", line 1369, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "C:/msys64/home/balduf/meson/mesonbuild/interpreter/interpreter.py", line 1407, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine)
  File "C:/msys64/home/balduf/meson/mesonbuild/compilers/detect.py", line 224, in detect_compiler_for
    comp = compiler_from_language(env, lang, for_machine)
  File "C:/msys64/home/balduf/meson/mesonbuild/compilers/detect.py", line 221, in compiler_from_language
    return lang_map[lang](env, for_machine) if lang in lang_map else None
  File "C:/msys64/home/balduf/meson/mesonbuild/compilers/detect.py", line 665, in detect_c_compiler
    return _detect_c_or_cpp_compiler(env, 'c', for_machine)
  File "C:/msys64/home/balduf/meson/mesonbuild/compilers/detect.py", line 528, in _detect_c_or_cpp_compiler
    linker = guess_win_linker(env, ['lld-link'], cls, version, for_machine)
  File "C:/msys64/home/balduf/meson/mesonbuild/linkers/detect.py", line 84, in guess_win_linker
    p, o, _ = Popen_safe(compiler + check_args)
  File "C:/msys64/home/balduf/meson/mesonbuild/mesonlib/universal.py", line 1406, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "C:/msys64/home/balduf/meson/mesonbuild/mesonlib/universal.py", line 1422, in Popen_safe_legacy
    p = subprocess.Popen(args, universal_newlines=False, close_fds=False,
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

meson.build:19:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Open mingw64 shell. `export CC=clang-cl; meson setup build --buildtype=release`. This occurred while attempting to build [xtb](https://github.com/grimme-lab/xtb) though it doesn't seem to have reached anything specific to this package.

**system parameters**
* plain native build 
* Windows 10 (Mingw64 shell)
* Python 3.8
* meson version 0.62.99

**Comment by eli-schwartz** [comment]
From the context of the traceback, it looks like during linker detection Meson tried to execute the lld-link program to go with clang-cl, but could not find it, so python's subprocess error handler dumped a generic FileNotFoundError that naturally does not mention which file it could not find. ;)

Meson neglects to catch this error and tell you something a bit more... informative... like something that would actually let you know what the problem is and how to debug it. Mentioning which file could not be found is an important one.

The final bit -- "Unhandled python exception This is a Meson bug and should be reported!" is there to point out that the exception is clear as mud and we need to fix the diagnostic here.

...

All that being said, it seems your current environment isn't properly set up to *use* this compiler, so you may need some tweaks to actually make that configure successfully.

**Comment by lazka** [comment]
tbh while our (MSYS2) clang build installs a clang-cl I'm not sure if it works/is supposed to work. Maybe file an issue here instead first: https://github.com/msys2/MINGW-packages/issues

**Comment by TyBalduf** [comment]
@eli-schwartz Thank you for the quick response! I mainly just wanted to report the error since it explicitly asks to report it as a bug. I was having a separate issue (that I don't believe is due to meson) with compiling the xtb package and I was cycling through different C compilers to see if it resolved the problem. I just happened to stumble across this error message due to trying clang-cl.

**Comment by eli-schwartz** [comment]
Fair enough! :D As I said, it's a definite Meson bug with an incomprehensible error message, that's why we wrapped the error message with "please report this". So thanks for reporting it.

Analyzing what went wrong was relatively simple, so I wanted to explain what is going on in sufficient detail that you could work through it to get a resolution, if necessary...


... and also at the same time, whoever investigates actually fixing this exception has a nice pointer into what's going on ("linker detection tracebacks if the subprocess fails due to command-not-found") that saves on the effort of analyzing it.

I may get around to fixing the failure UX here after the weekend.

**Comment by andyfaff** [comment]
I'm also experiencing this issue. I'm working in a new conda environment. I have Visual Studio 2019 installed.

```
conda create -n testy
conda activate testy
conda install -c conda-forge compilers python=3.10
python -m pip install meson ninja
mkdir meson-test
cd meson-test
meson init
set CC=clang-cl
set CXX=clang-cl

:: the following line successfully compiles meson_test.exe
%CC% meson_test.c

:: now let's try a meson build
meson build
```

Unfortunately the meson build command fails.
```
The Meson build system
Version: 0.63.1
Source dir: \\filer\home\anz\programming\meson-test
Build dir: \\filer\home\anz\programming\meson-test\build
Build type: native build
Project name: meson-test
Project version: 0.1
Traceback (most recent call last):
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\msetup.py", line 303, in run
    app.generate()
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\msetup.py", line 186, in generate
    self._generate(env)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\msetup.py", line 208, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 344, in __init__
    self.parse_project()
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 580, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1257, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1393, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1431, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\compilers\detect.py", line 225, in detect_compiler_for
    comp = compiler_from_language(env, lang, for_machine)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\compilers\detect.py", line 222, in compiler_from_language
    return lang_map[lang](env, for_machine) if lang in lang_map else None
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\compilers\detect.py", line 670, in detect_c_compiler
    return _detect_c_or_cpp_compiler(env, 'c', for_machine)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\compilers\detect.py", line 533, in _detect_c_or_cpp_compiler
    linker = guess_win_linker(env, ['lld-link'], cls, version, for_machine)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\linkers\detect.py", line 85, in guess_win_linker    p, o, _ = Popen_safe(compiler + check_args)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1409, in Popen_safe    p, o, e = Popen_safe_legacy(args, write=write, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs)
  File "C:\Users\anz\Miniconda3\envs\testy\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1426, in Popen_safe_legacy
    p = subprocess.Popen(args, universal_newlines=False, close_fds=False,
  File "C:\Users\anz\Miniconda3\envs\testy\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\anz\Miniconda3\envs\testy\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR: Unhandled python exception
The system cannot find the file specified - (2, 'The system cannot find the file specified', None, 2, None)
this is probably not a Meson bug.
```

The meson-log is [here](https://gist.github.com/andyfaff/af72917637c3952ce0982a30875cc6a2)

**Comment by AndresGuzman-Ballen** [comment]
Any updates on addressing this issue?

**Comment by dcbaker** [comment]
@AndresGuzman-Ballen can you post your output? It appears that the issue is that lld-link doesn't exist or isn't in your path.

**Comment by AndresGuzman-Ballen** [comment]
@dcbaker oh I see! Let me experiment with explicitly adding that into the path and see how it goes. Thanks for the prompt reply!

**Comment by dcbaker** [comment]
We still shouldn't crash, at the very least we should give a nice error message, or continue looking for a different linker like `link.exe`
