### ISSUE TITLE
[bug report] list index out of range

### ISSUE THREAD

**Issue by sulincix** [mesonbuild/meson#10541]
```
$ ninja install
[1/1] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/minstall.py", line 771, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.10/site-packages/mesonbuild/minstall.py", line 550, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.10/site-packages/mesonbuild/minstall.py", line 724, in install_targets
    self.fix_rpath(outname, t.rpath_dirs_to_remove, install_rpath, final_path,
  File "/usr/lib/python3.10/site-packages/mesonbuild/minstall.py", line 341, in fix_rpath
    depfixer.fix_rpath(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 485, in fix_rpath
    fix_elf(fname, rpath_dirs_to_remove, new_rpath, verbose)
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 389, in fix_elf
    with Elf(fname, verbose) as e:
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 135, in __init__
    self.parse_dynamic()
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 236, in parse_dynamic
    sec = self.find_section(b'.dynamic')
  File "/usr/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 227, in find_section
    section_names = self.sections[self.e_shstrndx]
IndexError: list index out of range
Installing libinary.a to /usr/local/lib
Installing yamlget to /usr/local/bin
ERROR: Unhandled python exception
    This is a Meson bug and should be reported!
ninja: job failed: /usr/bin/meson install --no-rebuild
ninja: subcommand failed
```

Distribution: alpine linux.

meson version 0.62.1

Bug steps
1. compile source with meson using `meson build && ninja -C build`
2. use upx or remove a section from binary
3. run `ninja install -C build`

**Comment by sulincix** [comment]
Full log is https://gitlab.com/sulincix/inary-new/-/jobs/2643422078

**Comment by eli-schwartz** [comment]
Still missing information in order to determine whether this is something meson should be trying to handle. Closing as unreproducible.
