### ISSUE TITLE
python.find_installation() does not distinguish between ModuleNotFoundError and other errors

### ISSUE THREAD

**Issue by whot** [mesonbuild/meson#10589]
**Describe the bug**

This is  a bit niche but: we have a case in Fedora rawhide right now where a python module is broken - it uses `@asyncio.coroutine` which has been removed in Python 3.11. As a result, we get this:
```
$ python3 -c 'import evdev'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/evdev/__init__.py", line 5, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo, EvdevError
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  File "/usr/lib64/python3.11/site-packages/evdev/eventio_async.py", line 88, in ReadIterator
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```
So simply: the import fails, but *not* with a `ModuleNotFoundError`. Meson does not check for that though, it simply takes the nonzero return value. Where the `evdev` module is listed as a required module, we get this:
```
Program python3 (lxml, evdev, cairo, gi) found: NO modules: lxml, cairo, gi
meson.build:81:0: ERROR: python is missing modules: evdev
```
This is confusing because it looks like evdev is not available when in fact it failed to import.

**To Reproduce**

```
$  podman run --rm -it fedora:rawhide
[root@1234] # dnf install -y meson python-evdev
[root@1235] # meson --version
0.62.2
[root@1234] # cat > meson.build <<EOF
> project('test', version: '0')
> import('python').find_installation(modules: 'evdev')
> EOF
[root@1234] # meson builddir
...
meson.build:4:0: ERROR: python is missing modules: evdev
```

**Expected behavior**
Ideally, meson would print a different error message for broken modules **and** print details to the `meson-log.txt`, e.g. like this:
```
meson.build:4:0: ERROR: python unable to use failing modules: evdev
```
I reckon just distinguishing between `ModuleNotFoundError` and everything else is enough.

**system parameters**

This requires Python 3.11 for the specific test case above but can be reproduced with any broken module that fails import, on any python version.

**Comment by eli-schwartz** [comment]
It could be argued that you don't, in fact, have (a valid version of) that module. Heuristically parsing the stdout/stderr of the falling process in order to extrapolate exactly what is wrong with that module feels a bit hacky.

If instead of "is missing", it said the noncommittal "doesn't have a usable version of", would that still be an issue?

**Comment by whot** [comment]
I'm thinking an easy way to detect this would be to run
```
python -c '
try:
   import {mod}
except ModuleNotFoundError:
  import sys
  sys.exit(2)
'
```
And then distinguish between returncodes 0, 2, and other.

This is obviously a niche case which is why your message may be good enough too. Or just a "unable to import" which is also generic.
