### ISSUE TITLE
AttributeError when attempting to build Spot with meson on FreeBSD 13.1.

### ISSUE THREAD

**Issue by duncan-bayne** [mesonbuild/meson#10666]
**Describe the bug**
When running `meson build` in Spot, instead of building, meson throws `AttributeError: 'NoneType' object has no attribute 'has_header'`.

**To Reproduce**
```
git clone https://github.com/xou816/spot
cd spot
meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"
```

**Expected behavior**
spot builds, as it does on Ubuntu 22.04.

**Actual behavior**
meson throws an error, explicitly suggesting I report it.  Which is why I'm here :)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 301, in run
    app.generate()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2724, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2218, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1638, in func_dependency
    d = df.lookup(kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 352, in lookup
    dep = func(kwargs, func_args, func_kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 93, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/detect.py", line 112, in find_external_dependency
    d = c()
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/factory.py", line 105, in <lambda>
    DependencyMethods.SYSTEM:         lambda env, kwargs: system_class(name, env, kwargs),
  File "/usr/local/lib/python3.9/site-packages/mesonbuild/dependencies/misc.py", line 529, in __init__
    if not self.clib_compiler.has_header('openssl/ssl.h', '', env)[0]:
AttributeError: 'NoneType' object has no attribute 'has_header'
The Meson build system
Version: 0.62.2
Source dir: /usr/home/duncan/freebsd-setup/spot
Build dir: /usr/home/duncan/freebsd-setup/spot/target
Build type: native build
Project name: spot
Project version: 0.3.3
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program glib-compile-schemas found: YES (/usr/local/bin/glib-compile-schemas)
Program appstream-util found: NO
Program msgfmt found: YES (/usr/local/bin/msgfmt)
Program msginit found: YES (/usr/local/bin/msginit)
Program msgmerge found: YES (/usr/local/bin/msgmerge)
Program xgettext found: YES (/usr/local/bin/xgettext)
Found pkg-config: /usr/local/bin/pkg-config (1.8.0)
Run-time dependency libadwaita-1 found: YES 1.1.0
Run-time dependency gtk4 found: YES 4.6.3
Run-time dependency glib-2.0 found: YES 2.72.2

src/meson.build:6:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**system parameters**
* This is a native build.
* FreeBSD 13.1 RELEASE generic amd64
* Python 3.9.13
* meson 0.62.2
* ninja 1.10.2

**Comment by duncan-bayne** [comment]
Installing `AppStream` and `appstream-glib` addressed the `Program appstream-util found: NO` issue, but the unhandled Python exception persists.

**Comment by duncan-bayne** [comment]
If you'd like a FreeBSD development environment to look into this, I'm happy to make one available via SSH.

**Comment by eli-schwartz** [comment]
This doesn't really have anything to do with FreeBSD, except that FreeBSD happens to have openssl installed but without pkg-config files, seemingly.

Taking a look at the project you reference, it:
- has no listed languages
- builds a rust program as a custom_target via an unfortunate wrapper script that drives cargo with lots of options, then copies its fixed output to where meson expects (because rust is just difficult that way)
- looks up a couple of dependencies, but does nothing with them, presumably just to assert they exist and give a pleasant error message during configure, if they don't


And one of those dependencies is openssl, and recent versions of Meson (>= 0.62.0) include custom detection logic for openssl, even on unfortunate systems that refuse to install pkg-config files. But... that detection logic relies on running a C-like compiler.

More importantly, that detection logic assumes a C-like compiler has been added, and badly breaks if that assumption is incorrect. It should simply return not-found (because it cannot find C libraries and headers, without a C compiler), but instead it tries to treat a python `None` object as a `mesonbuild.compilers.Compiler` and tracebacks all over the screen.

This is bad, and a bug, because it is ugly and a bad error message no matter what.

That being said, even fixing this in Meson will not help you to build spot, because...

... it mandatorily depends on openssl, so returning not-found would mean that Meson errors out with "Dependency openssl is required but not found."

This could be fixed (independently of Meson fixing the "traceback instead of sensible error" bug) by:
- FreeBSD installing pkg-config files
- spot adding `add_languages('c', required : false)` to its build files in order to give it a reasonable chance to find dependencies via `cc.find_library()` and `cc.has_header()` (which is what the custom dependency lookup does under the hood)

**Comment by eli-schwartz** [comment]
BTW: there's a general ticket for the "lacking a C compiler" (no FreeBSD mention) topic at #10586

**Comment by Diegovsky** [comment]
Hey, IIRC we have a custom target because meson did not support building rust projects using cargo. Does meson now support it? I am willing to fix all aforementioned problems with our build file :)

**Comment by eli-schwartz** [comment]
I'm pretty sure we did fix the traceback issue. meson now reports that the dependency is not found "because no compiler toolchain available".

Unfortunately Meson hasn't added `cargo build` support because this is a generally hard problem and cargo itself doesn't really support that.

What you *can* do is use meson `library()` and `executable()` to build rust crates and link them to pkg-config dependencies and make executables. The main issue is that you have to write a meson.build for every crate you depend on -- there are plans to add automatic subproject support for this by parsing Cargo.toml and autogenerating a meson AST for it.

**Comment by Diegovsky** [comment]
> here are plans to add automatic subproject support for this by parsing Cargo.toml and autogenerating a meson AST for it.

I see. In that case, I'm waiting excitedly for when that is released :)

Btw, should I still make any changes to our meson.build?
