### ISSUE TITLE
AttributeError: 'PythonExternalProgram' object has no attribute 'cached_version'

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#10708]
**Describe the bug**
A PythonExternalProgram cannot execute the `version()` function if the binary is specified.
See the minimal example below.

**To Reproduce**

meson.build
```meson
project('mwe', 'c', version : '0.1')

py3_mod = import('python')
py3_inst1 = py3_mod.find_installation()
message(py3_inst1.language_version())
message(py3_inst1.version())

py3_inst2 = py3_mod.find_installation('python')
message(py3_inst2.language_version())
message(py3_inst2.version()) # this fails
```

results in:
```
The Meson build system
Version: 0.63.0
Source dir: /home/gerion/test/mwe
Build dir: /home/gerion/test/mwe/build
Build type: native build
Project name: mwe
Project version: 0.1
C compiler for the host machine: ccache cc (gcc 10.3.0 "cc (Gentoo 10.3.0 p1) 10.3.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3.10)
Message: 3.10
Message: 3.10.5
Program python found: YES (/usr/bin/python)
Message: 3.10
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 151, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 303, in run
    app.generate()
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 230, in _generate
    intr.run()
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 2803, in run
    super().run()
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 451, in function_call
    (h_posargs, h_kwargs) = self.reduce_arguments(node.args)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 533, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 533, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 184, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 490, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/baseobjects.py", line 92, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 64, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 73, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 672, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 557, in version_method
    return self.held_object.get_version(self.interpreter)
  File "/usr/lib/python3.10/site-packages/mesonbuild/programs.py", line 104, in get_version
    if not self.cached_version:
AttributeError: 'PythonExternalProgram' object has no attribute 'cached_version'

meson.build:10:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Expected behavior**
`version()` always works (since it is inherited from `external_program`).

**Additional information**
`language_version()` and `version()` behave really similar. Maybe they can be unified or maybe documented that, if you need also the last version number of the interpreter, you can use `version()` instead of `language_version()`.
This should always be the same:
```meson
project('mwe', 'c', version : '0.1')

py3_mod = import('python')
py3_inst1 = py3_mod.find_installation()
message(py3_inst1.language_version())
v = py3_inst1.version().split('.')
message('.'.join(v[0], v[1]))
```
Not sure if it is worth an own function.

#7078 is kind of related (therefore I discovered this bug).

**system parameters**
Meson 0.63 with Python 3.10 on Gentoo Linux

**Comment by JamBalaya56562** [comment]
Thank you for the minimal reproducer — this no longer crashes on current Meson.

The `AttributeError` came from `get_version()` reading `self.cached_version` on an instance where it hadn't been set. Every `ExternalProgram` now initializes it in `__init__`, so the attribute always exists:

```python
# mesonbuild/programs.py — ExternalProgram.__init__
self.cached_version: T.Optional[str] = None
```

For the Python module specifically, `PythonInstallation` stores the version up front from the interpreter's introspection (`self.version = info['version']`), which `.version()` returns directly.

**Verification:** `self.cached_version = None` is set in `ExternalProgram.__init__` (`mesonbuild/programs.py`), and `PythonInstallation.version` is populated from the introspection info in `mesonbuild/modules/python.py`.

Your example (`find_installation('python').version()`) now returns the version without the `AttributeError`, so this looks safe to close. Thanks for the report.
