### ISSUE TITLE
"TypeError: Passing coroutines is forbidden, use tasks explicitly."

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#10743]
While libfprint was being built in the CI using meson 0.62.2, one of the tests timed out and generated a lot of errors, in particular the one mentioned in the issue title.

```
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...explicitly.')>) at /usr/lib/python3.11/site-packages/mesonbuild/mtest.py:1859
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...explicitly.')>) at /usr/lib/python3.11/site-packages/mesonbuild/mtest.py:1859>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1288, in wait
    await complete_all(self.all_futures, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1200, in complete_all
    check_futures(futures)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1188, in check_futures
    raise asyncio.TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1861, in test_done
    f.result()
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1856, in run_test
    res = await test.run(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1400, in run
    await self._run_cmd(harness, cmd)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1466, in _run_cmd
    returncode, result, additional_error = await p.wait(self.runobj.timeout)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1290, in wait
    additional_error = await self._kill()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1251, in _kill
    await try_wait_one(p.wait(), timeout=0.5)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1153, in try_wait_one
    await asyncio.wait(awaitables,
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 424, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
/usr/lib/python3.11/site-packages/mesonbuild/mtest.py:1186: RuntimeWarning: coroutine 'Process.wait' was never awaited
  f.result()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1288, in wait
    await complete_all(self.all_futures, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1200, in complete_all
    check_futures(futures)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1188, in check_futures
    raise asyncio.TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 2017, in run
    return th.doit()
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1694, in doit
    self.run_tests(runners)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1833, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1930, in _run_tests
    await complete_all(futures)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1196, in complete_all
    check_futures(done)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1186, in check_futures
    f.result()
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

[ci-log.txt](https://github.com/mesonbuild/meson/files/9432150/ci-log.txt)

**Comment by QuLogic** [comment]
Looks like #10633 to me.

**Comment by eli-schwartz** [comment]
It is, AFAICT.

Also note in the traceback, you are using Python 3.11.

Python 3.11 is not a stable release, it's a fresh out of the oven rc1 testing release. That doesn't mean it isn't worth testing or reporting bugs for, but it does mean that I'd probably consider double-checking git master, because if there's an existing fix for it, it will very likely be more recent than 3 releases ago. :)

**Comment by hadess** [comment]
It's what was shipped in the Fedora rawhide CI images I use, so I have little sway over it.

**Comment by hadess** [comment]
> Looks like #10633 to me.

Thanks, that was useful.

**Comment by eli-schwartz** [comment]
Fedora rawhide is shipping Meson 0.63.1 for much the same reason they are shipping release candidates of Python 3.11 -- Rawhide is an unstable testing release of the upcoming Fedora, showcasing the latest and greatest of the ecosystem's software, and upgrading python is a lot of effort best done during release candidate testing of python itself.

So at the same time, they're bumping versions of all the other software too, so they don't need to do release candidate testing of python in combination with old versions of software that doesn't have the latest python 3.11 fixes. :p

If you're going to use rawhide for a particular CI image in order to test that it works well with very recent versions of all dependencies, that's probably also a good image to be using the system Meson in order to test that it builds with very recent versions of all ***build*** dependencies, rather than e.g. pinning Meson via `pip install`.

**Comment by hadess** [comment]
That's nice of you to explain what rawhide is to me, but I've worked for Red Hat for 20 years, so that's all a little unnecessary.

**Comment by eli-schwartz** [comment]
Following that line of thought, the third paragraph should have been unnecessary as well, but plainly it is necessary. :)
