### ISSUE TITLE
Build failure with openwrt 22.03.0 (`Input/output error: 'selinuxenabled'`)

### ISSUE THREAD

**Issue by bersbersbers** [mesonbuild/meson#10774]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/bers/openwrt/staging_dir/host/bin/meson.py/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/home/bers/openwrt/staging_dir/host/bin/meson.py/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/home/bers/openwrt/staging_dir/host/bin/meson.py/mesonbuild/minstall.py", line 593, in do_install
    self.restore_selinux_contexts(destdir)
  File "/home/bers/openwrt/staging_dir/host/bin/meson.py/mesonbuild/minstall.py", line 385, in restore_selinux_contexts
    restore_selinux_contexts()
  File "/home/bers/openwrt/staging_dir/host/bin/meson.py/mesonbuild/minstall.py", line 231, in restore_selinux_contexts
    subprocess.check_call(['selinuxenabled'])
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 5] Input/output error: 'selinuxenabled'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-install
/home/bers/openwrt/staging_dir/host/bin/python3 /home/bers/openwrt/staging_dir/host/bin/meson.py install --no-rebuild
```

See https://github.com/openwrt/openwrt/issues/10609 for more information.

**Comment by bersbersbers** [comment]
There is a patch in https://github.com/openwrt/openwrt/issues/10609#issuecomment-1237649520 that works.
