### ISSUE TITLE
(Windows 11) ERROR: Compiler cl can not compile programs

### ISSUE THREAD

**Issue by mxrch** [mesonbuild/meson#10795]
Hello !
While trying to install `scipy` on Python 3.11rc1 (Windows 11), I got this traceback : 
```python
> py -m pip install scipy --upgrade
Collecting scipy
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e
      Build dir: C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e\.mesonpy-x7d63hr0\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      Activating VS 16.11.18

      ..\..\meson.build:1:0: ERROR: Compiler cl can not compile programs.

      A full log can be found at C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e\.mesonpy-x7d63hr0\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\thher\AppData\Local\Programs\Python\Python311 C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e\.mesonpy-x7d63hr0\build
      Traceback (most recent call last):
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 923, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 902, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 547, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 463, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 494, in _configure
          self._meson(
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 477, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\thher\AppData\Local\Temp\pip-build-env-wder1mlf\overlay\Lib\site-packages\mesonpy\__init__.py", line 472, in _proc
          subprocess.check_call(list(args))
        File "C:\Users\thher\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\thher\\AppData\\Local\\Temp\\pip-install-9tovb2ma\\scipy_828fda3b17134154918e54876239f05e\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\thher\\AppData\\Local\\Programs\\Python\\Python311', 'C:\\Users\\thher\\AppData\\Local\\Temp\\pip-install-9tovb2ma\\scipy_828fda3b17134154918e54876239f05e', 'C:\\Users\\thher\\AppData\\Local\\Temp\\pip-install-9tovb2ma\\scipy_828fda3b17134154918e54876239f05e\\.mesonpy-x7d63hr0\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I searched about the error `Compiler cl can not compile programs` but I didn't find anything to fix this problem, some things about Visual Studio but I already have VS 2019..
My main concern is that I'm updating my own open-source projects to be compatible with Python 3.11 (candidate version in 1 month), and I'm afraid that Meson doesn't work out of the box on Windows.

In addition, I confirm having installed Meson using pip, and it's in PATH : 
```powershell
> meson help
usage: meson [-h]
             {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
             ...

options:
  -h, --help                                                show this help message and exit

Commands:
  If no command is specified it defaults to setup command.

  {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
    setup                                                   Configure the project
    configure                                               Change project options
    dist                                                    Generate release archive
    install                                                 Install the project
    introspect                                              Introspect project
    init                                                    Create a new project
    test                                                    Run tests
    wrap                                                    Wrap tools
    subprojects                                             Manage subprojects
    rewrite                                                 Modify the project definition
    compile                                                 Build the project
    devenv                                                  Run commands in developer environment
    env2mfile                                               Convert current environment to a cross or native file
    help                                                    Print help of a subcommand
```

**Comment by eli-schwartz** [comment]
Note that Meson is tested in CI to build C/C++ projects with cl.exe, and used quite a bit in the wild. The issue here has to be more specific, either to your environment or to SciPy or to a combination of the two. So, debugging...

```
      A full log can be found at C:\Users\thher\AppData\Local\Temp\pip-install-9tovb2ma\scipy_828fda3b17134154918e54876239f05e\.mesonpy-x7d63hr0\build\meson-logs\meson-log.txt
```

You'll want to inspect the logs to figure out exactly what went wrong, probably. However, pip tends to delete "temporary files"...

You can clone SciPy and build it directly with `meson setup builddir/`, which should give you more inspectable output.

That being said -- you need a fortran compiler too, which usually means gfortran... SciPy's official wheels are built with mingw, IIRC.
