### ISSUE TITLE
`IncompleteRead` exception on slow internet connections

### ISSUE THREAD

**Issue by Rot127** [mesonbuild/meson#10819]
**Describe the bug**

`IncompleteRead` exception is thrown on (very) slow and lagy internet connections (average around 8KiB/s).

Full exception:
```
Downloading tree-sitter source from https://github.com/tree-sitter/tree-sitter/archive/v0.20.6.tar.gz
Downloading file of unknown size.
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/client.py", line 598, in _readinto_chunked
    n = self._safe_readinto(temp_mvb)
  File "/usr/lib/python3.8/http/client.py", line 623, in _safe_readinto
    raise IncompleteRead(bytes(b[:n]), amt-n)
http.client.IncompleteRead: IncompleteRead(2169 bytes read, 3987 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreter/interpreter.py", line 2549, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 189, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 272, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreterbase/decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreter/interpreter.py", line 795, in func_subproject
    return self.do_subproject(args[0], 'meson', kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/interpreter/interpreter.py", line 836, in do_subproject
    subdir = r.resolve(subp_name, method)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/wrap/wrap.py", line 334, in resolve
    self.get_file()
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/wrap/wrap.py", line 398, in get_file
    path = self.get_file_internal('source')
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/wrap/wrap.py", line 560, in get_file_internal
    self.download(what, cache_path)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/wrap/wrap.py", line 535, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/wrap/wrap.py", line 498, in get_data
    block = resp.read(blocksize)
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 493, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.8/http/client.py", line 604, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

../meson.build:294:2: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: build.ninja 
/usr/local/bin/meson --internal regenerate /home/user/rizin /home/user/rizin/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**To Reproduce**
I could not reproduce the bug. It occurred only twice and I just assume that it is due to the slow download speed.

Project I tried to build was [Rizin](https://github.com/rizinorg/rizin).

**Expected behavior**

The exception is handled.

**system parameters**
* Is this a plain native build.
* what operating system Ubuntu 20.04.5 LTS
* what Python version: `Python 3.11.0rc1`
* what `meson --version`: `0.61.2`
* what `ninja --version`: `1.10.0.git.kitware.jobserver-1`

**Comment by eli-schwartz** [comment]
Since 0.62.0 we catch *all* exceptions and attempt an exponential backoff (about 6 times before giving up IIRC). Does that solve the problem by just avoiding the error state?

Granted that we could catch `http.client.HTTPException` and provide a better error message here, even if an incomplete read happens 6 times in a row. ;)

**Comment by Rot127** [comment]
I'm no longer in an area which has the slow internet connection and can't try it with `0.62.0` (also don't have time to analyze it further). Are you fine with closing this issue and I or someone else opens it again when stumbling into it?
