### ISSUE TITLE
Install script fails on MinGW because of encoding

### ISSUE THREAD

**Issue by sakhnik** [mesonbuild/meson#10831]
**Describe the bug**
`DESTDIR=dist ninja install` fails when there's a custom Python install script in MinGW

**To Reproduce**
On a clean MinGW64 system.
```
git clone https://github.com/sakhnik/nvim-ui
cd nvim-ui
./scripts/install-mingw.sh
./scripts/build.sh
./scripts/package-nupkg.sh
```
[meson.build](https://github.com/sakhnik/nvim-ui/blob/e5a1058f318ed211d0d9cdf81a67e931d0585209/res/meson.build#L26)

**Expected behavior**
The install scripts succeeds, so should `ninja install`.

**system parameters**
* Native build in MinGW
* Windows 10 MinGW
* Python-3.10.6
* meson-0.63.1
* ninja-1.11.1

** Output **
```
Running custom install script 'python C:/tools/msys64/home/user/nvim-ui/res/glib-compile-schemas.py C:/tools/msys64/share/glib-2.0/schemas'
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/minstall.py", line 766, in run
    installer.do_install(datafilename)
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/minstall.py", line 552, in do_install
    self.run_install_script(d, destdir, fullprefix)
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/minstall.py", line 663, in run_install_script
    rc = self.run_exe(i, env)
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/minstall.py", line 366, in run_exe
    return run_exe(*args, **kwargs)
  File "C:/tools/msys64/mingw64/lib/python3.10/site-packages/mesonbuild/scripts/meson_exe.py", line 88, in run_exe
    print(stderr.decode(encoding=encoding, errors='replace'))
  File "C:/tools/msys64/mingw64/lib/python3.10/encodings/cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 111: character maps to <undefined>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by xclaesse** [comment]
Meson assumes that the script's stdout and stderr are encoded using `locale.getpreferredencoding()`, but it seems your script does not respect that.

In mlog we do that:
```
    try:
        print(raw, end='')
    except UnicodeEncodeError:
        cleaned = raw.encode('ascii', 'replace').decode('ascii')
        print(cleaned, end='')
```

We should probably do the same here.
