### ISSUE TITLE
UnicodeEncodeError in mesonlib.do_conf_file()

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1085]
```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 283, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 171, in generate
    intr.run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1336, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1358, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1352, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1473, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 66, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2209, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1358, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1352, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1473, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2257, in func_configure_file
    mesonlib.do_conf_file(ifile_abs, ofile_abs, conf.held_object)
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonlib.py", line 292, in do_conf_file
    f.writelines(result)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 13: ordinal not in range(128)
```

**Comment by kalev** [comment]
I'm hitting this bug too with LANG=C. Workaround is export LANG=en_US.utf8

**Comment by nirbheek** [comment]
The problem is that you're trying to write a unicode character to a file when using a non-unicode encoding. We can fix this by setting the `encoding` kwarg while writing files. However, this will break in other ways, such as when using files with unicode filenames.

What's the output of:

```
python3 -c 'import locale; print(locale.getpreferredencoding())'
```

With `LANG=C` that will return `ANSI_X3.4-1968` or some similar ansi encoding. I don't think we can do anything about a broken `LANG` setting except while writing/reading files.
