### ISSUE TITLE
difficult error to debug if ninja can't be found

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1088]
I updated ninja but forgot to `chmod +x` it and got this error. At first I had no clue what was happening until I remembered I updated `ninja`.

```
python3 ./ECS/meson/meson.py --prefix=/home/gitlab-runner/builds/15268147/0/dist-ecs --buildtype=debugoptimized build
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/15268147/0/ECS/meson/mesonbuild/mesonmain.py", line 283, in run
    app.generate()
  File "/home/gitlab-runner/builds/15268147/0/ECS/meson/mesonbuild/mesonmain.py", line 173, in generate
    g.generate(intr)
  File "/home/gitlab-runner/builds/15268147/0/ECS/meson/mesonbuild/backend/ninjabackend.py", line 203, in generate
    self.generate_ending(outfile)
  File "/home/gitlab-runner/builds/15268147/0/ECS/meson/mesonbuild/backend/ninjabackend.py", line 2094, in generate_ending
    ninja_command = environment.detect_ninja()
  File "/home/gitlab-runner/builds/15268147/0/ECS/meson/mesonbuild/environment.py", line 51, in detect_ninja
    p = subprocess.Popen([n, '--version'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
  File "/usr/local/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by nirbheek** [comment]
Interesting that `subprocess.Popen` returns a `PermissionError` instead of a `FileNotFoundError` if there's a file in `PATH` with the correct name but no executable bit. Nothing else does this.

**Comment by QuLogic** [comment]
Bash does, though `which` doesn't:
```bash
$ export PATH=$PATH:.
$ touch nonexistent-program
$ which nonexistent-program
/usr/bin/which: no nonexistent-program in ($PATH:.)
$ nonexistent-program
bash: ./nonexistent-program: Permission denied
```

**Comment by nirbheek** [comment]
Fair enough!
