### ISSUE TITLE
panic in get_dep_identifier@detect.py

### ISSUE THREAD

**Issue by p01arst0rm** [mesonbuild/meson#10918]
**Describe the bug**
Unhandled Python exception in get_dep_identifier.

**To Reproduce**
execute provided dummy project

**Expected behavior**
provide meson error, or correctly return subproject target.

**system parameters**
* Is this a [cross build]: no
* what operating system Win10 21H2 19044.1741
* what Python version are you using: 3.10.7
* what `meson --version`: 0.63.2
* what `ninja --version` : N/A

[dummy.zip](https://github.com/mesonbuild/meson/files/9781303/dummy.zip)

**Comment by eli-schwartz** [comment]
Can you post the traceback? :)

**Comment by p01arst0rm** [comment]
```
PS D:\a> meson setup build
The Meson build system
Version: 0.63.2
Source dir: D:\a        
Build dir: D:\a\build   
Build type: native build
Project name: test      
Project version:        
C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
C++ linker for the host machine: c++ ld.bfd 2.28
Host machine cpu family: x86
Host machine cpu: x86
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 153, in run
  File "mesonbuild\msetup.py", line 303, in run
  File "mesonbuild\msetup.py", line 186, in generate
  File "mesonbuild\msetup.py", line 230, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 2826, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 149, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call     
  File "mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
  File "mesonbuild\interpreterbase\decorators.py", line 580, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 2294, in func_subdir
  File "mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 574, in assignment
  File "mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 774, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 774, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 774, in wrapped
  [Previous line repeated 5 more times]
  File "mesonbuild\interpreterbase\decorators.py", line 109, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1693, in func_dependency
  File "mesonbuild\interpreter\dependencyfallbacks.py", line 354, in lookup
  File "mesonbuild\interpreter\dependencyfallbacks.py", line 83, in _do_dependency_cache
  File "mesonbuild\interpreter\dependencyfallbacks.py", line 209, in _get_cached_dep
  File "mesonbuild\dependencies\detect.py", line 64, in get_dep_identifier
AssertionError

llvm\meson.build:5:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by eli-schwartz** [comment]
Aha, this is an early failure when you pass this kwarg:
```meson
method: cmake # imported cmake module
```

It is caused by insufficient typechecking to catch errors, `cmake` should be quoted as a string and this should error out with:

```
"dependency" keyword argument "method" was of type ExtensionModule but should have been str
```

Alas, we are not yet ported to typed_kwargs so this goes unnoticed until the guts of the dependency finder spew out all over the screen.

**Comment by bonzini** [comment]
Should be fixed now.
