### ISSUE TITLE
panic in relpatch@ntpath.py

### ISSUE THREAD

**Issue by p01arst0rm** [mesonbuild/meson#10920]
Describe the bug
Unhandled Python exception in relpath.

To Reproduce
execute provided dummy project

Expected behavior
provide meson error, or correctly return subproject target.

system parameters

Is this a [cross build]: no
what operating system Win10 21H2 19044.1741
what Python version are you using: 3.10.7
what meson --version: 0.63.2
what ninja --version : N/A

[dummy.zip](https://github.com/mesonbuild/meson/files/9787671/dummy.zip)

**Comment by p01arst0rm** [comment]
Traceback


```
 Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 153, in run
  File "mesonbuild\msetup.py", line 303, in run
  File "mesonbuild\msetup.py", line 186, in generate
  File "mesonbuild\msetup.py", line 248, in _generate
  File "mesonbuild\backend\vs2010backend.py", line 226, in generate
  File "mesonbuild\backend\vs2010backend.py", line 478, in generate_projects
  File "mesonbuild\backend\vs2010backend.py", line 1046, in gen_vcxproj
  File "mesonbuild\backend\backends.py", line 452, in relpath
  File "ntpath.py", line 718, in relpath
ValueError: path is on mount 'C:', start on mount 'D:'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by jpakkane** [comment]
Do you have the build dir on a separate drive from sources? That probably won't work (at least for the moment)

**Comment by p01arst0rm** [comment]
the source and build are on the same drive;  the issue only happens when trying to include a CMake subproject, not a meson project, and only specifically the project in the dummy build. though, the unhandled exception is the main reason for filing the bug report, not any weirdness to do with building
