### ISSUE TITLE
AttributeError: 'GnuCCompiler' object has no attribute 'exelist_no_ccache'

### ISSUE THREAD

**Issue by bsun0000** [mesonbuild/meson#10997]
**Describe the bug**
I was trying to recompile the mesa drivers using latest meson (0.64.0~rc2-1, debian/experimental) and got this error.

**Stack trace**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 264, in run
    return msetup.run(['--reconfigure'] + args[2:])
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 307, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 230, in _generate
    intr.run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 2895, in run
    super().run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 276, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 281, in evaluate_if
    self.evaluate_codeblock(node.elseblock)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 575, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 184, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 491, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/baseobjects.py", line 92, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 581, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/compiler.py", line 280, in run_method
    result = self.compiler.run(code, self.environment, extra_args=extra_args,
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/mixins/clike.py", line 472, in run
    with self._build_wrapper(code, env, extra_args, dependencies, mode='link', want_output=True) as p:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/compilers.py", line 1248, in _build_wrapper
    with self.compile(code, extra_args=args, mode=mode, want_output=want_output, temp_dir=env.scratch_dir) as r:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/compilers.py", line 819, in compile
    command_list = self.get_exelist(ccache=not no_ccache) + commands.to_native()
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/compilers.py", line 598, in get_exelist
    return self.exelist.copy() if ccache else self.exelist_no_ccache.copy()
AttributeError: 'GnuCCompiler' object has no attribute 'exelist_no_ccache'

../meson.build:536:4: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/blacksun/Downloads/mesa /home/blacksun/Downloads/mesa/build
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**To Reproduce**
Can be reproduced using mesa sources from git. 
meson --reconfigure build/
Fails to do the job using ccache && gcc.

**Expected behavior**
_Anything_ except this error.

**Commits to blame**
https://github.com/mesonbuild/meson/commit/2961adb8c89fa8ccfbc8e24cd9f1115bd3abeee1
https://github.com/mesonbuild/meson/commit/e68fcac919b332c7f9469672a243d2aab1bfea0a

This two commits directly related to the problem.

**system parameters**
* native build, GCC 12.2 + ccache
* Debian Bookworm with packages from _experimental_ branch
* Python 3.10
* `meson --version`: 0.64.0~rc2-1 - with this bug, 0.63.3-1 - previous version, works fine.
* `ninja --version`: 1.11.1

**Comment by xclaesse** [comment]
Is that a reconfigure of an existing builddir that was configured with a previous version of Meson? Does it work if you reconfigure from scratch, using `--wipe`?

**Comment by eli-schwartz** [comment]
Did you use an existing build directory previously generated by rc1, or by 0.63.3?

**Comment by bsun0000** [comment]
I was using an existing build directory - generated by previous meson version (0.63.x).
And i didnt have any problems doing this before..
I will test --wipe flag later if its important (already downgraded meson and start compilation, sorry..).

**Comment by eli-schwartz** [comment]
For any given version 0.X.Y, you can.upgrade to a new 0.X.(Y+1) safely. But generally not a new X+1 version. Usually Meson will emit a specific error message for mismatched versions regardless of attribute errors, and then reinvoke itself with --wipe automatically.

It's known and expected that this doesn't work for 0.X.99 versions (development versions) but I'm not sure how the release candidates play into that.

Apparently this particular change doesn't occur during unpickling of the coredata though! Otherwise we'd catch the error again and emit a message about invalid coredata.

**Comment by xclaesse** [comment]
Right, we never supported ugprading an existing builddir when updating major version or rc releases. The solution is --wipe.
