### ISSUE TITLE
custom_target() runs cross executables directly instead of using exe_wrapper

### ISSUE THREAD

**Issue by kanavin** [mesonbuild/meson#11029]
When cross compiling glib, this snippet in gio/tests/meson.build proved problematic:

```
    plugin_resources_c = custom_target('plugin-resources.c',
      input : 'test4.gresource.xml',
      output : 'plugin-resources.c',
      command : [glib_compile_resources,
                 compiler_type,
                 '--target=@OUTPUT@',
                 '--sourcedir=' + meson.current_source_dir(),
                 '--internal',
                 '--generate-source',
                 '--c-name', '_g_plugin',
                 '@INPUT@'])

```

Specifically, 'command', e,g. 'glib-compile-resources' executable in the build tree, will be executed by meson directly, even though it is is a cross-binary that has just been built, and will not run directly (and the fact is known from needs_exe_wrapper set to true, and exe wrapper pointing to qemu). Glib upstream tries to work around this by wrapping the target in 'if meson.can_run_host_binaries()', but that returns 'true' as well (because the wrapper is available), and so the target is attempted - and fails.

I've filed a quick fix for glib:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3067

 but the real issue is probably in meson.

**Comment by zboszor** [comment]
The same problem occurs with cross-compiling libfprint.

I added this patch to debug:
```
diff --git a/mesonbuild/scripts/meson_exe.py b/mesonbuild/scripts/meson_exe.py
index 33408d826..18428ad1e 100644
--- a/mesonbuild/scripts/meson_exe.py
+++ b/mesonbuild/scripts/meson_exe.py
@@ -31,6 +31,8 @@ def buildparser() -> argparse.ArgumentParser:
     return parser
 
 def run_exe(exe: ExecutableSerialisation, extra_env: T.Optional[T.Dict[str, str]] = None) -> int:
+    print("run_exe() exe: ", exe)
+    print("run_exe() extra_env: ", extra_env)
     if exe.exe_wrapper:
         if not exe.exe_wrapper.found():
             raise AssertionError('BUG: Can\'t run cross-compiled exe {!r} with not-found '
```
The result is:
```
| [122/124] /home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/bin/meson.real --internal exe --capture libfprint/70-libfprint-2.rules -- /home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/build/libfprint/fprint-list-udev-rules
| FAILED: libfprint/70-libfprint-2.rules
| /home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/bin/meson.real --internal exe --capture libfprint/70-libfprint-2.rules -- /home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/build/libfprint/fprint-list-udev-rules
| run_exe() exe:  ExecutableSerialisation(cmd_args=['/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/build/libfprint/fprint-list-udev-rules'], env=None, exe_wrapper=None, workdir=None, extra_paths=None, capture='libfprint/70-libfprint-2.rules', feed=None, tag=None, verbose=False)
| run_exe() extra_env:  None
| Traceback (most recent call last):
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/bin/meson.real", line 8, in <module>
|     sys.exit(main())
|              ^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 287, in main
|     return run(sys.argv[1:], launcher)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 275, in run
|     return run_script_command(args[1], args[2:])
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 223, in run_script_command
|     return module.run(script_args)
|            ^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/site-packages/mesonbuild/scripts/meson_exe.py", line 123, in run
|     return run_exe(exe)
|            ^^^^^^^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/site-packages/mesonbuild/scripts/meson_exe.py", line 68, in run_exe
|     p = subprocess.Popen(cmd_args, env=child_env, cwd=exe.workdir,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/subprocess.py", line 1024, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/subprocess.py", line 1789, in _execute_child
|     self._posix_spawn(args, executable, env, restore_signals,
|   File "/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/recipe-sysroot-native/usr/lib/python3.11/subprocess.py", line 1733, in _posix_spawn
|     self.pid = os.posix_spawn(executable, args, env, **kwargs)
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| FileNotFoundError: [Errno 2] No such file or directory: '/home/zozo/dtd-yocto-4.2/tmp-sicom-glibc/work/corei7-64-oe-linux/libfprint/1.94.5-r0/build/libfprint/fprint-list-udev-rules'
```
`exe_wrapper` unset for the executable.

Forcing `native: false` for the libfprint internal executables doesn't help, `exe_wrapper` is still unset when running them.

**Comment by zboszor** [comment]
@dcbaker It seems to me that the `ExecutableSerialisation` object created `mesonbuild/scripts/meson_exe.py` where `run_exe()` is defined is completely independent from `mesonbuild/backend/backends.py`'s `get_executable_serialisation()`

`mesonbuild/scripts/meson_exe.py`'s `run()` would need `exe: ExecutableSerialisation` object to get passed to it using the object as generated by `get_executable_serialisation()` (i.e. whether the `executable()` needs `exe_wrapper` or not) instead of `run()` generating the `exe` object anew without knowing anything about the executable in question, then passing the inadequate information to `run_exe()`.
