### ISSUE TITLE
'meson test' fails to run on Python 3.12

### ISSUE THREAD

**Issue by sgallagher** [mesonbuild/meson#11204]
**Describe the bug**
Meson fails to run on Python 3.12 due to reliance on the implicit instantiation of the asyncio mainloop that was deprecated in Python 3.10. It has now been removed.

Additional details in [this Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=2155490) and [this Python upstream issue](https://github.com/python/cpython/issues/93453).

**To Reproduce**

* Install python 3.12 alpha.
* Run `meson test` in any project that supports it

**Expected behavior**
Tests should run

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Experienced on Fedora Rawhide (38), but likely present on any Linux with Python 3.12
* what Python version are you using e.g. 3.8.0
  * Python 3.12
* what `meson --version`
  * Meson 0.64.1
* what `ninja --version` if it's a Ninja build
  * Ninja 1.5.8.1

**Comment by eli-schwartz** [comment]
CPython has tagged this as a release blocker for 3.10 and 3.11 stable (due to adding a deprecation warning after the initial .0 release) and is reverting the change for 3.12 since it wasn't properly deprecated. The new plan is to remove it in 3.14 instead.

This isn't to say that it would be bad to move away from that behavior, but, it's a bit less of a priority I guess.

**Comment by scivision** [comment]
Just to give specific messages with Python 3.12.0a3 (some other unrelated new warnings exist):

```
build/local/bin/python3 ../meson/run_unittests.py
/home/beef/code/meson/mesonbuild/compilers/detect.py:469: SyntaxWarning: invalid escape sequence '\d'
  arm_ver_match = re.search('version (\d+)\.(\d+) \(build number (\d+)\)', out)
/home/beef/code/meson/mesonbuild/compilers/detect.py:733: SyntaxWarning: invalid escape sequence '\d'
  arm_ver_match = re.search('version (\d+)\.(\d+) \(build number (\d+)\)', out)
Meson build system 0.61.99 Unit Tests
pytest-xdist not found, using unittest instead
..........Segmentation fault (core dumped)
```

The test that segfaults:

```
Unit test for the library search patterns used by find_library() ... Segmentation fault (core dumped)
```

**Comment by eli-schwartz** [comment]
@scivision any code that manages to *segfault* in pure python code is almost certainly a CPython bug, which really should be fixed by CPython during the alpha phase so that projects written in python don't need to solve interpreter segfaults on their end.

**Comment by scivision** [comment]
Hi Eli, my apologies I tested with an old Meson version. I'm updating my Python 3.12.0a3 results now with current Meson. So my first post I deleted was invalid.

**Comment by scivision** [comment]
I reran with Meson master branch and Python 3.12.0a3 I built myself on CentOS.

```sh
$ /local/bin/python3 run_unittests.py

Meson build system 1.0.0.rc2 Unit Tests
=========================================== test session starts
===========================================platform linux -- Python 3.12.0a3, pytest-7.2.0, pluggy-1.0.0
rootdir: /code/meson, configfile: setup.cfg
collected 479 items
```

```
========================================= short test summary info 
FAILED run_unittests.py::AllPlatformTests::test_scripts_loaded_modules - AssertionError: Lists differ: ['mesonbuild', 'mesonbuild._pathlib', 'meso[173 chars]ore'] != ['__edita...
FAILED run_unittests.py::AllPlatformTests::test_prebuilt_object - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_long_output - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_prebuilt_shared_lib_rpath - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_testsetup_default - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_force_fallback_for_nofallback - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_lto_threads - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_force_fallback_for - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_reconfigure - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_dist_git_script - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_static_library_lto - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_prebuilt_shared_lib - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_testsetup_selection - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_prebuilt_static_lib - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_forcefallback - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_suite_selection - AssertionError: 2 != 4
FAILED run_unittests.py::AllPlatformTests::test_dist_git - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_testsetups - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_testrepeat - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::CrossFileTests::test_cross_exe_passed_no_wrapper - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_pkgconfig_static - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::AllPlatformTests::test_wrap_git - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::CrossFileTests::test_needs_exe_wrapper_true_wrapper - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_freezing - AssertionError: 'Traceback' unexpectedly found in 'ninja explain: output meson-benchmark-prereq of pho...
FAILED run_unittests.py::CrossFileTests::test_needs_exe_wrapper_false - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_symlink_builddir - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::SubprojectsCommandTests::test_purge - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::CrossFileTests::test_needs_exe_wrapper_true - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::SubprojectsCommandTests::test_foreach - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::LinuxlikeTests::test_usage_external_library - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_pch_with_address_sanitizer - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_link_arg_fullname - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_static_link - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::LinuxlikeTests::test_pkgconfig_uninstalled - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
FAILED run_unittests.py::SubprojectsCommandTests::test_git_update - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::AllPlatformTests::test_verbose - subprocess.CalledProcessError: Command '['/code/cmake-python-build/build/local/bin/python3',...
FAILED run_unittests.py::LinuxlikeTests::test_wrap_with_file_url - subprocess.CalledProcessError: Command '['/ninja-1.11.1/ninja', '-w', 'dupbuild=err', '-d', ...
=================== 37 failed, 370 passed, 72 skipped, 451 warnings in 77.25s (0:01:17) ===================Total time: 77.540 seconds
```

**Comment by scivision** [comment]
Here's what I get on a trivial Meson project test:

```
ninja: no work to do.
ninja: Entering directory `/code/trivial/build'
ninja: no work to do.
Traceback (most recent call last):
  File "/code/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/meson/mesonbuild/mtest.py", line 2107, in run
    return th.doit()
           ^^^^^^^^^
  File "/code/meson/mesonbuild/mtest.py", line 1788, in doit
    self.run_tests(runners)
  File "/code/meson/mesonbuild/mtest.py", line 1926, in run_tests
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/cmake-python-build/build/local/lib/python3.12/asyncio/events.py", line 676, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by eli-schwartz** [comment]
I opened a PR that implements this.

By the way -- after testing it locally, it seems that contrary to my initial reply, and contrary to what it seems upstream CPython suggested, this particular kind of usage *did* issue a deprecation in 3.11.0. However AFAICT the entire thing is still being deferred?

It's not a big deal, we can switch in advance of python 3.14 too of course. ;)

**Comment by eli-schwartz** [comment]
(With that PR and MESON_SHOW_DEPRECATIONS=1 I can pass the entire Meson testsuite without issuing deprecations. There was another asyncio.get_event_loop case in `meson subprojects`.)

**Comment by eli-schwartz** [comment]
It breaks python 3.7 and 3.8 (I don't have python 3.9 locally installed at the moment):

```
$ ./meson.py test -C t/builddir
[...]
Traceback (most recent call last):
  File "/home/eschwartz/git/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 2112, in run
    return th.doit()
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 1788, in doit
    self.run_tests(runners)
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 1936, in run_tests
    asyncio.run(self._run_tests(runners))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 2042, in _run_tests
    await l.finish(self)
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 698, in finish
    await self.progress_task
  File "/home/eschwartz/git/meson/mesonbuild/mtest.py", line 579, in report_progress
    await self.update.wait()
  File "/usr/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
RuntimeError: Task <Task pending coro=<ConsoleLogger.start.<locals>.report_progress() running at /home/eschwartz/git/meson/mesonbuild/mtest.py:579>> got Future <Future pending> attached to a different loop
```

I don't understand why... either using `asyncio.run` or `asyncio.set_event_loop(asyncio.new_event_loop())` both fail.

**Comment by scivision** [comment]
Since there are only a couple lines changed in #11215, and these "older" Python versions in my experience had some quirks on some platforms with asyncio, maybe for stability etc. it would be worth leaving the original code `if sys.version_version < (3, 10):` or such.

**Comment by eli-schwartz** [comment]
The even simpler solution would be to defer until python 3.14 :P and to be honest, if you cannot even use the replacement APIs for several more versions, that's a good argument that it shouldn't be deprecated to begin with.

I'm honestly pretty disappointed by python, now.

**Comment by eli-schwartz** [comment]
I bisected CPython and found the problem. :D Turns out until 3.10, creating various asyncio objects would silently create a new event loop due to the whole implicit event loops flow. Explicitly instantiating your own then wreaked havoc.

So I think my PR now actually works, and dropping old API is nice.

**Comment by eli-schwartz** [comment]
Should be fixed now.
