### ISSUE TITLE
'NoneType' object has no attribute 'current_node'

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#11225]
**Describe the bug**
I was setting up a build of GIMP3 from the master branch in MSYS2/MinGW64, but I'm getting an internal error:

```
Configuring org.gimp.extension.goat-exercises.metainfo.xml.in using configuration
Traceback (most recent call last):
  File "D:/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
  File "D:/meson/mesonbuild/msetup.py", line 309, in run
    app.generate()
  File "D:/meson/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "D:/meson/mesonbuild/msetup.py", line 230, in _generate
    intr.run()
  File "D:/meson/mesonbuild/interpreter/interpreter.py", line 2886, in run
    super().run()
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "D:/meson/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "D:/meson/mesonbuild/interpreterbase/decorators.py", line 590, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "D:/meson/mesonbuild/interpreter/interpreter.py", line 2298, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 208, in evaluate_statement
    return self.evaluate_uminusstatement(cur)
  File "D:/meson/mesonbuild/interpreterbase/interpreterbase.py", line 339, in evaluate_uminusstatement
    v.current_node = cur
AttributeError: 'NoneType' object has no attribute 'current_node'

../gimp/plug-ins/meson.build:4:1: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

I am launching Meson with the following command-line:

`python /d/meson/meson.py setup ../gimp --prefix=$GIMP_PREFIX --buildtype=debug`

**To Reproduce**

* `git clone --depth=1 https://gitlab.gnome.org/GNOME/gimp.git`
* `mkdir gimp-build`
* `cd gimp-build`
* `meson setup ../gimp --buildtype=debug`

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
  `Native`
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  `Win10`
* what Python version are you using e.g. 3.8.0
  `Python 3.10.9`
* what meson --version
  `Tried both 0.64.1 and current master (1.0.99)`
* what ninja --version if it's a Ninja build
  `Ninja 1.11.1`

**Comment by lb90** [comment]
Looks like I made a mistake: instead of commenting a line:

`#subdir('file-exr')`

I wrote that:

`-subdir('file-exr')`

This confuses the parser.

**Comment by dcbaker** [comment]
This is still a legitimate bug, we should not display this exception.
