### ISSUE TITLE
Windows - meson fails to execute python script with shebang line

### ISSUE THREAD

**Issue by LunarLambda** [mesonbuild/meson#11241]
on meson 0.64.1, installed with the .msi installer. latest ninja, windows 10 22H2

This was during a much larger build, I will attempt to make a repro shortly. Just caught this random snippet in my logs:

```
"C:\Program Files\Meson\meson.exe" "--internal" "exe" "--unpickle" "C:\Users\Lambda\dev\meson-gba\build\meson-private\meson_exe_makerom_cd0a45934b5ec33a78c797e740ebe495111f2f02.dat"
Traceback (most recent call last):
  File "meson.py", line 40, in <module>
  File "mesonbuild\mesonmain.py", line 287, in main
  File "mesonbuild\mesonmain.py", line 275, in run
  File "mesonbuild\mesonmain.py", line 223, in run_script_command
  File "mesonbuild\scripts\meson_exe.py", line 120, in run
  File "mesonbuild\scripts\meson_exe.py", line 65, in run_exe
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application
[6188] Failed to execute script 'meson' due to unhandled exception!
```

python scripts do not have .py extension, but do have shebang line `#!/usr/bin/env python3` (as was told to me in https://github.com/mesonbuild/meson/discussions/10978#discussioncomment-4029863).

Seems like either meson is failing to execute itself, or it's trying to invoke the python script as a win32 application. unsure which

**Comment by dcbaker** [comment]
Is your script called meson, but chance?

**Comment by LunarLambda** [comment]
my scripts are called copy and makerom

**Comment by dcbaker** [comment]
Then that sure looks like it's something inside meson itself that's failing

**Comment by LunarLambda** [comment]
Most likely a duplicate of https://github.com/mesonbuild/meson/issues/11255

**Comment by skupr-anaconda** [comment]
I have the same issue with meson 1.3.1 on win-64 when I build gobject-introspection 1.78.1, see https://github.com/AnacondaRecipes/gobject-introspection-feedstock/pull/12#issuecomment-2249797208
