### ISSUE TITLE
Regenerate `build.ninja` fails on Windows when using MSVC

### ISSUE THREAD

**Issue by metab0t** [mesonbuild/meson#11309]
**Describe the bug**
I use the very basic setup and find weird error when using `meson setup --vsenv`

I have a folder containing two files:
- `main.cpp`
```
#include <stdio.h>

int main()
{
	printf("Hello, world!\n");
	return 0;
}
```

- `meson.build`
```meson
project('proj', 'cpp')

proj = executable('proj', 'main.cpp')
```

The steps to reproduce:

1. Setup
```cmd
❯ meson setup builddir --vsenv
The Meson build system
Version: 1.0.0
Source dir: D:\tmp\simpleproj
Build dir: D:\tmp\simpleproj\builddir
Build type: native build
Project name: proj
Project version: undefined
Activating VS 17.4.4
C++ compiler for the host machine: cl (msvc 19.34.31937 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.34.31937
��")
C++ linker for the host machine: link link 14.34.31937.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.0 at D:\mambaforge\Library\bin\ninja.EXE

Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
D:\mambaforge\Scripts\meson compile -C builddir
```

2. delete the empty line in `meson.build` and compile
```meson
project('proj', 'cpp')
proj = executable('proj', 'main.cpp')
```

```cmd
❯ meson compile -Cbuilddir
Activating VS 17.4.4
INFO: automatically activated MSVC compiler environment
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: D:\mambaforge\Library\bin\ninja.EXE -C D:/tmp/simpleproj/builddir
ninja: Entering directory `D:/tmp/simpleproj/builddir'
[0/1] Regenerating build files.The Meson build system
Version: 1.0.0
Source dir: D:\tmp\simpleproj
Build dir: D:\tmp\simpleproj\builddir
Build type: native build
Project name: proj
Project version: undefined
C++ compiler for the host machine: cl (msvc 19.34.31937 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.34.31937
��")
C++ linker for the host machine: link link 14.34.31937.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.0 at D:\mambaforge\Library\bin\ninja.EXE

[2/2] Linking target proj.exe
```

3. Add the empty line back to `meson.build` and compile
```meson
project('proj', 'cpp')

proj = executable('proj', 'main.cpp')
```

```cmd
❯ meson compile -Cbuilddir                                                                                    
INFO: autodetecting backend as ninja                                                                          
INFO: calculating backend command to run: D:\mambaforge\Library\bin\ninja.EXE -C D:/tmp/simpleproj/builddir   
ninja: Entering directory `D:/tmp/simpleproj/builddir'                                                        
[0/1] Regenerating build files.The Meson build system                                                         
Version: 1.0.0                                                                                                
Source dir: D:\tmp\simpleproj                                                                                 
Build dir: D:\tmp\simpleproj\builddir                                                                         
Build type: native build                                                                                      
Project name: proj                                                                                            
Project version: undefined                                                                                    
C++ compiler for the host machine: cl (msvc 19.34.31937 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.34.31937
��")                                                                                                          
C++ linker for the host machine: link link 14.34.31937.0                                                      
Host machine cpu family: x86_64                                                                               
Host machine cpu: x86_64                                                                                      
Build targets in project: 1                                                                                   
                                                                                                              
Found ninja-1.11.0 at D:\mambaforge\Library\bin\ninja.EXE                                                     
Traceback (most recent call last):                                                                            
  File "D:\mambaforge\lib\site-packages\mesonbuild\mesonmain.py", line 270, in run                            
    return msetup.run(['--reconfigure'] + args[2:])                                                           
  File "D:\mambaforge\lib\site-packages\mesonbuild\msetup.py", line 309, in run                               
    app.generate()                                                                                            
  File "D:\mambaforge\lib\site-packages\mesonbuild\msetup.py", line 186, in generate                          
    self._generate(env)                                                                                       
  File "D:\mambaforge\lib\site-packages\mesonbuild\msetup.py", line 250, in _generate                         
    intr.backend.generate()                                                                                   
  File "D:\mambaforge\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 607, in generate            
    with self.detect_vs_dep_prefix(tempfilename) as outfile:                                                  
  File "D:\mambaforge\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 538, in detect_vs_dep_prefix
    pc = subprocess.Popen(compiler.get_exelist() +                                                            
  File "D:\mambaforge\lib\subprocess.py", line 971, in __init__                                               
    self._execute_child(args, executable, preexec_fn, close_fds,                                              
  File "D:\mambaforge\lib\subprocess.py", line 1440, in _execute_child                                        
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                                                
FileNotFoundError: [WinError 2] 系统找不到指定的文件。                                                                   
                                                                                                              
ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.  
ninja: error: rebuilding 'build.ninja': subcommand failed                                                     
                                                                                                              
FAILED: build.ninja                                                                                           
"D:\mambaforge\Scripts\meson" "--internal" "regenerate" "D:\tmp\simpleproj" "D:\tmp\simpleproj\builddir"
```

**Expected behavior**
Meson should regenerate `build.ninja` successfully.

I tried to use gcc in msys without `--vsenv` flag and it works fine.

I tried to run meson in the VS shell with `cl` in PATH then it works fine, too

I notice that the following activation output only appears during the first compilation, but `cl` is not runnable on the command line afterwards.
```cmd
Activating VS 17.4.4
INFO: automatically activated MSVC compiler environment
```

Maybe we need to remember `need_vsenv = true` permanently if `--vsenv` is set during `setup`?

**system parameters**
* It is just a plain native build (for the same computer)
* I use Windows 10
* Python version is 3.10.8
* `meson --version` is 1.0.0
* `ninja --version` is 1.11.0

**Comment by tristan957** [comment]
Could you translate this for us?

```
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by xclaesse** [comment]
It should be fixed with https://github.com/mesonbuild/meson/pull/11312#issuecomment-1397678930

**Comment by metab0t** [comment]
> Could you translate this for us?
> 
> ```
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> ```

```
FileNotFoundError: [WinError 2] System cannot find the specified file.
```
