### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''  meson.build:1466:0: ERROR: Unhandled python exception

### ISSUE THREAD

**Issue by JackGengChen** [mesonbuild/meson#11349]
**Describe the bug**
I tried to build glib2 on MSYS2-MINGW64, but failed when running `meson build`
```
The Meson build system
Version: 1.0.0
Source dir: E:\env-setup\MSYS2\home\CG\glib-2.74.4
Build dir: E:\env-setup\MSYS2\home\CG\glib-2.74.4\build
Build type: native build
Project name: glib
Project version: 2.74.4
C compiler for the host machine: cc (gcc 12.2.0 "cc (Rev10, Built by MSYS2 project) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Rev10, Built by MSYS2 project) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.39
Compiler for C++ supports arguments -std=c++98: YES
Compiler for C++ supports arguments -std=c++03: YES
Compiler for C++ supports arguments -std=c++11: YES
Compiler for C++ supports arguments -std=c++14: YES
Compiler for C++ supports arguments -std=c++17: YES
Compiler for C++ supports arguments -std=c++20: YES
Compiler for C++ supports arguments -std=c++2b: YES
Compiler for C++ supports arguments -std=c++latest: NO
Program valgrind found: NO
Compiler for C supports arguments -fno-strict-aliasing: YES
Checking if "GNU C visibility attributes test" compiles: NO
Compiler for C supports arguments -fvisibility=hidden: YES
Message: Disabling cast checks
Has header "alloca.h" : NO
Has header "afunix.h" : YES
Has header "crt_externs.h" : NO
Has header "dirent.h" : YES
Has header "float.h" : YES
Has header "fstab.h" : NO
Has header "grp.h" : NO
Has header "inttypes.h" : YES
Has header "limits.h" : YES
Has header "locale.h" : YES
Has header "mach/mach_time.h" : NO
Has header "memory.h" : YES
Has header "mntent.h" : NO
Has header "poll.h" : NO
Has header "pwd.h" : NO
Has header "sched.h" : YES
Has header "spawn.h" : NO
Has header "stdatomic.h" : YES
Has header "stdint.h" : YES
Has header "stdlib.h" : YES
Has header "string.h" : YES
Has header "strings.h" : YES
Has header "sys/auxv.h" : NO
Has header "sys/event.h" : NO
Has header "sys/filio.h" : NO
Has header "sys/inotify.h" : NO
Has header "sys/mkdev.h" : NO
Has header "sys/mntctl.h" : NO
Has header "sys/mnttab.h" : NO
Has header "sys/mount.h" : NO
Has header "sys/param.h" : YES
Has header "sys/resource.h" : NO
Has header "sys/select.h" : NO
Has header "sys/statfs.h" : NO
Has header "sys/stat.h" : YES
Has header "sys/statvfs.h" : NO
Has header "sys/sysctl.h" : NO
Has header "sys/time.h" : YES
Has header "sys/times.h" : NO
Has header "sys/types.h" : YES
Has header "sys/uio.h" : NO
Has header "sys/vfs.h" : NO
Has header "sys/vfstab.h" : NO
Has header "sys/vmount.h" : NO
Has header "sys/wait.h" : NO
Has header "termios.h" : NO
Has header "unistd.h" : YES
Has header "values.h" : NO
Has header "wchar.h" : YES
Has header "xlocale.h" : NO
Check usable header "malloc.h" : YES
Has header "linux/netlink.h" : NO
Checking if "statx() test" compiles: NO
Header "locale.h" has symbol "LC_MESSAGES" : NO
Checking whether type "struct stat" has member "st_mtimensec" : NO
Checking whether type "struct stat" has member "st_mtim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_atimensec" : NO
Checking whether type "struct stat" has member "st_atim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_ctimensec" : NO
Checking whether type "struct stat" has member "st_ctim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_birthtime" : NO
Checking whether type "struct stat" has member "st_birthtimensec" : NO
Checking whether type "struct stat" has member "st_birthtim" : NO
Checking whether type "struct stat" has member "st_birthtim.tv_nsec" : NO
Checking whether type "struct stat" has member "st_blksize" : NO
Checking whether type "struct stat" has member "st_blocks" : NO
Checking whether type "struct statfs" has member "f_fstypename" : NO
Checking whether type "struct statfs" has member "f_bavail" : NO
Checking whether type "struct dirent" has member "d_type" : NO
Checking whether type "struct statvfs" has member "f_basetype" : NO
Checking whether type "struct statvfs" has member "f_fstypename" : NO
Checking whether type "struct tm" has member "tm_gmtoff" : NO
Checking whether type "struct tm" has member "__tm_gmtoff" : NO
Compiler for C supports arguments -Wduplicated-branches: YES
Compiler for C supports arguments -Wimplicit-fallthrough: YES
Compiler for C supports arguments -Wmisleading-indentation: YES
Compiler for C supports arguments -Wunused: YES
Compiler for C supports arguments -Wno-unused-parameter: YES
Compiler for C supports arguments -Wno-cast-function-type: YES
Compiler for C supports arguments -Wno-pedantic: YES
Compiler for C supports arguments -Wno-format-zero-length: YES
Compiler for C supports arguments -Wno-variadic-macros: YES
Compiler for C supports arguments -Werror=format=2: YES
Compiler for C supports arguments -Werror=init-self: YES
Compiler for C supports arguments -Werror=missing-include-dirs: YES
Compiler for C supports arguments -Werror=pointer-arith: YES
Compiler for C supports arguments -Werror=unused-result: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wno-bad-function-cast: YES
Compiler for C supports arguments -Werror=declaration-after-statement: YES
Compiler for C supports arguments -Werror=implicit-function-declaration: YES
Compiler for C supports arguments -Werror=missing-prototypes: YES
Compiler for C supports arguments -Werror=pointer-sign: YES
Compiler for C++ supports arguments -Wduplicated-branches: YES
Compiler for C++ supports arguments -Wimplicit-fallthrough: YES
Compiler for C++ supports arguments -Wmisleading-indentation: YES
Compiler for C++ supports arguments -Wunused: YES
Compiler for C++ supports arguments -Wno-unused-parameter: YES
Compiler for C++ supports arguments -Wno-cast-function-type: YES
Compiler for C++ supports arguments -Wno-pedantic: YES
Compiler for C++ supports arguments -Wno-format-zero-length: YES
Compiler for C++ supports arguments -Wno-variadic-macros: YES
Compiler for C++ supports arguments -Werror=format=2: YES
Compiler for C++ supports arguments -Werror=init-self: YES
Compiler for C++ supports arguments -Werror=missing-include-dirs: YES
Compiler for C++ supports arguments -Werror=pointer-arith: YES
Compiler for C++ supports arguments -Werror=unused-result: YES
Compiler for C supports link arguments -Wl,-z,nodelete: NO
Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES
Checking if "building for UWP" compiles: NO
Library iphlpapi found: YES
Checking for function "if_nametoindex" with dependency -liphlpapi: YES
Checking for function "if_indextoname" with dependency -liphlpapi: YES
Checking for function "close_range" : NO
Checking for function "endmntent" : NO
Checking for function "endservent" : NO
Checking for function "epoll_create" : NO
Checking for function "fallocate" : NO
Checking for function "fchmod" : NO
Checking for function "fchown" : NO
Checking for function "fdwalk" : NO
Checking for function "fsync" : NO
Checking for function "getauxval" : NO
Checking for function "getc_unlocked" : NO
Checking for function "getfsstat" : NO
Checking for function "getgrgid_r" : NO
Checking for function "getmntent_r" : NO
Checking for function "getpwuid_r" : NO
Checking for function "getresuid" : NO
Checking for function "getvfsstat" : NO
Checking for function "gmtime_r" : NO
Checking for function "hasmntopt" : NO
Checking for function "inotify_init1" : NO
Checking for function "issetugid" : NO
Checking for function "kevent" : NO
Checking for function "kqueue" : NO
Checking for function "lchmod" : NO
Checking for function "lchown" : NO
Checking for function "link" : NO
Checking for function "localtime_r" : NO
Checking for function "lstat" : NO
Checking for function "mbrtowc" : YES
Checking for function "memalign" : NO
Checking for function "mmap" : NO
Checking for function "newlocale" : NO
Checking for function "pipe2" : NO
Checking for function "poll" : NO
Checking for function "prlimit" : NO
Checking for function "readlink" : NO
Checking for function "recvmmsg" : NO
Checking for function "sendmmsg" : NO
Checking for function "setenv" : NO
Checking for function "setmntent" : NO
Checking for function "strerror_r" : NO
Checking for function "strnlen" : YES
Checking for function "strsignal" : NO
Checking for function "strtod_l" : NO
Checking for function "strtoll_l" : NO
Checking for function "strtoull_l" : NO
Checking for function "symlink" : NO
Checking for function "timegm" : NO
Checking for function "unsetenv" : NO
Checking for function "uselocale" : NO
Checking for function "utimes" : NO
Checking for function "utimensat" : NO
Checking for function "valloc" : NO
Checking for function "vasprintf" : YES
Checking for function "vsnprintf" : YES
Checking for function "wcrtomb" : YES
Checking for function "wcslen" : YES
Checking for function "wcsnlen" : YES
Checking for function "sysctlbyname" : NO
Checking for function "splice" : NO
Checking for function "memalign" : NO
Checking for function "_aligned_malloc" : YES
Checking for function "posix_spawn" : NO
Checking for function "snprintf" : YES
Checking for function "strcasecmp" : YES
Checking for function "strncasecmp" : YES
Header "sys/sysmacros.h" has symbol "major" : NO
Header "sys/mkdev.h" has symbol "major" : NO
Header "sys/types.h" has symbol "major" : NO
Header "dlfcn.h" has symbol "RTLD_LAZY" : NO
Header "dlfcn.h" has symbol "RTLD_NOW" : NO
Header "dlfcn.h" has symbol "RTLD_GLOBAL" : NO
Header "dlfcn.h" has symbol "RTLD_NEXT" : NO
Message: Checking whether to use statfs or statvfs .. neither
Checking if "futex(2) system call" compiles: NO
Checking if "futex(2) system call" compiles: NO
Checking if "eventfd(2) system call" : links: NO
Checking if "pidfd_open(2) system call" : links: NO
Checking if "__uint128_t available" compiles: YES
Checking if "clock_gettime" : links: YES
Checking if "dlopen() and dlsym() in system libraries" : links: NO
Checking if "dlopen() and dlsym() in libdl" : links: NO
Checking if "open() option O_DIRECTORY" compiles: NO
Checking if "fcntl() option F_FULLFSYNC" compiles: NO
Checking if "C99 vsnprintf" runs: YES
Checking if "C99 snprintf" runs: YES
Checking if "Unix98 printf positional parameters" runs: NO (1)
Checking if "nl_langinfo and CODESET" : links: NO
Checking if "nl_langinfo (PM_STR)" : links: NO
Checking if "nl_langinfo (_NL_CTYPE_OUTDIGITn_MB)" : links: NO
Checking if "nl_langinfo (ALTMON_n)" : links: NO
Checking if "nl_langinfo (_NL_ABALTMON_n)" : links: NO
Checking if "nl_langinfo and _NL_TIME_CODESET" : links: NO
Checking if "signed" compiles: YES
Header "stddef.h" has symbol "ptrdiff_t" : YES
Checking if "sig_atomic_t" : links: YES
Checking if "long long" compiles: YES
Checking if "long double" compiles: YES
Header "stddef.h" has symbol "wchar_t" : YES
Header "wchar.h" has symbol "wint_t" : YES
Checking if "uintmax_t in inttypes.h" compiles: YES
Checking if "uintmax_t in stdint.h" compiles: YES
Checking for size of "char" : 1
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "void*" : 8
Checking for size of "long" : 4
Checking for size of "long long" : 8
Checking for size of "size_t" : 8
Checking for size of "ssize_t" : 8
Checking for alignment of "char" : 1
Checking for alignment of "short" : 2
Checking for alignment of "int" : 4
Checking for alignment of "void*" : 8
Checking for alignment of "long" : 4
Checking for alignment of "long long" : 8
Checking for alignment of "size_t" : 8
Checking for size of "wchar_t" : 2
Checking if "GCC size_t typedef is long long" compiles: YES
Checking if "__va_copy check" compiles: YES
Checking if "va_copy check" compiles: YES
Checking if "va_lists can be copied as values" runs: YES
Checking if "ISO C99 varargs macros in C" compiles: YES
Checking if "ISO C99 varargs macros in C++" compiles: YES
Checking if "GNUC varargs macros" compiles: YES
Has header "alloca.h" : NO (cached)
Has header "sys/poll.h" : NO
Has header "sys/types.h" : YES (cached)
Has header "winsock2.h" : YES
Computing int of "AF_UNIX" : 1
Computing int of "AF_INET" : 2
Computing int of "AF_INET6" : 23
Traceback (most recent call last):
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\mesonmain.py", line 193, in run
    return options.run_func(options)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\msetup.py", line 309, in run
    app.generate()
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\msetup.py", line 186, in generate
    self._generate(env)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\msetup.py", line 230, in _generate
    intr.run()
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreter\interpreter.py", line 2873, in run
    super().run()
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 212, in evaluate_statement
    self.evaluate_foreach(cur)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 419, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 575, in assignment
    value = self.evaluate_statement(node.value)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 184, in evaluate_statement
    return self.method_call(cur)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 491, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\baseobjects.py", line 92, in method_call
    return method(args, kwargs)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\decorators.py", line 682, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreterbase\decorators.py", line 590, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\interpreter\compiler.py", line 403, in compute_int_method
    res = self.compiler.compute_int(expression, kwargs['low'], kwargs['high'],
  File "E:\env-setup\MSYS2\mingw64\lib\python3.10\site-packages\mesonbuild\compilers\mixins\clike.py", line 573, in compute_int
    return int(res.stdout)
ValueError: invalid literal for int() with base 10: ''

meson.build:1867:2: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

**To Reproduce**
The meson.build file:
[meson.build.txt](https://github.com/mesonbuild/meson/files/10532131/meson.build.txt)
Steps:
```bash
# get the source
wget https://download.gnome.org/sources/glib/2.74/glib-2.74.4.tar.xz -O glib-2.74.4.tar.xz
# decompress
tar -xvf glib-2.54.3.tar.xz
# 
cd /path/to/glib-2.74.4
# run the meson build
meson build --prefix=~/glib2
```

**Expected behavior**
Expected to build glib2 successfully on MSYS2 but failed to so, got the same error on PowerShell.

**system parameters**
* plain native build for the same computer
* Windows 10
* python version 3.10.9
* `meson --version` 1.0.0

**Comment by tristan957** [comment]
Are you using glib 2.74 or 2.54?

**Comment by eli-schwartz** [comment]
The contents of `build/meson-logs/meson-log.txt` could prove instructive. What it should say is that Meson tried to compile something like this:

```c
#include<stdio.h>

// used on Windows
#include <winsock2.h>
/* Used elsewhere
#include <sys/types.h>
#include <sys/socket.h>
*/

int main(void) {
    printf("%ld\\n", (long)( MSG_OOB));
    return 0;
}
```

This must:
- compile and link correctly
- be executed as a program, and return success
- print an integer

If steps 1 and 2 succeed, then Meson assumes 3 *must* be true, but according to your error report, it is instead printing nothing.
