### ISSUE TITLE
Crash on certain project type

### ISSUE THREAD

**Issue by mtribiere** [mesonbuild/meson#11512]
**Describe the bug**
Meson crashes when using the following project structure:
```
+ builddir
|
+ sub_folder
         |
         +------ Sub_sub_1
         |           |
         |           + ---- meson.build
         +------ Sub_sub_2
         |           |
         |           + ---- meson.build
         +------ meson.build 
```
It produces the following crash:

```
Traceback (most recent call last):
  File "C:\Tools\DEV\Meson_AH\mesonbuild\mesonmain.py", line 194, in run
    return options.run_func(options)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\msetup.py", line 310, in run
    app.generate()
  File "C:\Tools\DEV\Meson_AH\mesonbuild\msetup.py", line 187, in generate
    self._generate(env)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\msetup.py", line 231, in _generate
    intr.run()
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreter\interpreter.py", line 2875, in run
    super().run()
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 147, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 172, in evaluate_codeblock
    raise e
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 165, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    self.assignment(cur)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 573, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 178, in evaluate_statement
    return self.function_call(cur)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\interpreterbase.py", line 460, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreter\interpreter.py", line 1724, in func_static_lib
    return self.build_target(node, args, kwargs, build.StaticLibrary)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\interpreter\interpreter.py", line 3156, in build_target
    target = targetclass(name, self.subdir, self.subproject, for_machine, srcs, struct, objs,
  File "C:\Tools\DEV\Meson_AH\mesonbuild\build.py", line 1921, in __init__
    super().__init__(name, subdir, subproject, for_machine, sources, structured_sources, objects,
  File "C:\Tools\DEV\Meson_AH\mesonbuild\build.py", line 722, in __init__
    self.process_kwargs(kwargs)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\build.py", line 1967, in process_kwargs
    super().process_kwargs(kwargs)
  File "C:\Tools\DEV\Meson_AH\mesonbuild\build.py", line 1146, in process_kwargs
    assert isinstance(i, File)
AssertionError

meson.build:290:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Create the same project structure

**Expected behavior**
Should not crash

**System parameters**
- Cross-compilation with GCC-Like
- Windows 10
- Meson 1.0.1
- Ninja 1.11.1

**Comment by bruchar1** [comment]
I can reproduce the bug. It occurs when a target `extra_files` kwparam receives another target or a generated file.

In interpreter/interpreter.py : build_target, it calls `source_strings_to_files()`, which returns a list of `SourceOutputs` .

Then in build.py, it asserts that the list contains `File` objects.

**Comment by eli-schwartz** [comment]
https://github.com/mesonbuild/meson/pull/10714#discussion_r1128984772

Already known, in the process of being fixed.

The assertion is dumb, what we want is to report "extra_files only supports str or File", but for some bizarre reason this runtime validation code uses an assert, which is a really bad error logging format.

**Comment by bruchar1** [comment]
But documentation says: ` extra_files : str | file | custom_tgt | custom_idx`...

**Comment by eli-schwartz** [comment]
That documentation dates back to the original RefMan 2.0, which ported the entire documentation to structured yaml with included "supported types", and in many cases had to guess what the supported types were because validation is buried in the build layer instead of the interpreter layer. :D

**Comment by bruchar1** [comment]
Duplicates #10933.

**Comment by bruchar1** [comment]
Is this issue fixed?
