### ISSUE TITLE
Environment value are not flatten

### ISSUE THREAD

**Issue by Urgau** [mesonbuild/meson#11634]
**Describe the bug**
It seems like environment value are not flattened, ie array of array doesn't become a simple array leading to a crash while wanting to concat all values.

<details>

```
Found ninja-1.11.1 at /usr/bin/ninja
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 310, in run
    app.generate()
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 187, in generate
    self._generate(env)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 251, in _generate
    intr.backend.generate()
  File "/usr/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 615, in generate
    self.generate_target(t)
  File "/usr/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 802, in generate_target
    self.generate_custom_target(target)
  File "/usr/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 1108, in generate_custom_target
    cmd, reason = self.as_meson_exe_cmdline(target.command[0], cmd[1:],
  File "/usr/lib/python3.10/site-packages/mesonbuild/backend/backends.py", line 613, in as_meson_exe_cmdline
    for k, v in env.get_env({}).items():
  File "/usr/lib/python3.10/site-packages/mesonbuild/utils/core.py", line 129, in get_env
    env[name] = method(env, name, values, separator, default_value)
  File "/usr/lib/python3.10/site-packages/mesonbuild/utils/core.py", line 113, in _set
    return separator.join(values)
TypeError: sequence item 1: expected str instance, list found

ERROR: Unhandled python exception
```

</details>

**To Reproduce**
```meson
project('meson-crash', ['c'])

ct = custom_target('ct-crash',
  build_by_default: true,
  output: 'tmp',
  env: {
    'MY_KEY': ['VAL1', ['VAL2']],  # this list is not flatten
  },
  command: 'echo')
```

**Expected behavior**
I would expect my example to work.

**System parameters**
* Operating system: Archlinux
* Python version: `Python 3.10.10`
* `meson --version`: `1.0.1`

**Comment by bonzini** [comment]
Works now, I get

```
 COMMAND = env MY_KEY=VAL1:VAL2 '/home/pbonzini/work/upstream/meson/test$ cases/common/8$ install/gendir.py' dir
```

in build.ninja,
