### ISSUE TITLE
'ninja install' failure

### ISSUE THREAD

**Issue by verghiskoshi** [mesonbuild/meson#11651]
ninja install failure, details and versions below:

verghis@verghis-Latitude-E5570:~/dpdk-stable-22.11.1/build$ sudo ninja install
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-internal__install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
verghis@verghis-Latitude-E5570:~/dpdk-stable-22.11.1/build$ meson --version
1.0.1

meson 1.0.1 (latest)
Linux 5.15.0-67-generic (Mint)
Python3 3.10.6
ninja 1.10.1

**Comment by eli-schwartz** [comment]
Duplicate of #11650
