### ISSUE TITLE
meson 1.1.0 breaks pip builds under sudo

### ISSUE THREAD

**Issue by flowerysong** [mesonbuild/meson#11665]
**Describe the bug**

After #11366, meson running with EUID 0 assumes that the presence of `SUDO_USER` in the environment means that the build environment is owned by that user. If a pip installation is happening as root this results in the unprivileged build steps not being able to access the temporary build environment that pip created for root.

**To Reproduce**

```
sudo yum install dbus-devel glib2-devel python3-devel
sudo python3 -m venv /var/tmp/testvenv
sudo /var/tmp/testvenv/bin/pip install dbus-python
```

```
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 13
  ╰─> [165 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd
      Build dir: /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd/.mesonpy-bp352uvh/build
      Build type: native build
      Project name: dbus-python
      Project version: 1.3.2
      C compiler for the host machine: cc (gcc 7.3.1 "cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)")
      C linker for the host machine: cc ld.bfd 2.29.1-31
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -fno-common: YES
      Compiler for C supports arguments -Wno-missing-field-initializers: YES
      Compiler for C supports arguments -Wno-declaration-after-statement: YES
      Compiler for C supports arguments -Wno-inline: YES
      Compiler for C supports arguments -Wno-redundant-decls: YES
      Compiler for C supports arguments -Wno-switch-default: YES
      Compiler for C supports arguments -Wno-write-strings: YES
      Compiler for C supports arguments -Wcast-align: YES
      Compiler for C supports arguments -Wdouble-promotion: YES
      Compiler for C supports arguments -Wduplicated-cond: YES
      Compiler for C supports arguments -Wfloat-equal: YES
      Compiler for C supports arguments -Wformat-nonliteral: YES
      Compiler for C supports arguments -Wformat-security: YES
      Compiler for C supports arguments -Wformat=2: YES
      Compiler for C supports arguments -Winit-self: YES
      Compiler for C supports arguments -Wlogical-op: YES
      Compiler for C supports arguments -Wmissing-declarations: YES
      Compiler for C supports arguments -Wmissing-format-attribute: YES
      Compiler for C supports arguments -Wmissing-include-dirs: YES
      Compiler for C supports arguments -Wmissing-noreturn: YES
      Compiler for C supports arguments -Wnull-dereference: YES
      Compiler for C supports arguments -Wpacked: YES
      Compiler for C supports arguments -Wpointer-arith: YES
      Compiler for C supports arguments -Wshadow: YES
      Compiler for C supports arguments -Wswitch-enum: YES
      Compiler for C supports arguments -Wundef: YES
      Compiler for C supports arguments -Wunused-but-set-variable: YES
      Compiler for C supports arguments -Wjump-misses-init: YES
      Compiler for C supports arguments -Wmissing-prototypes: YES
      Compiler for C supports arguments -Wnested-externs: YES
      Compiler for C supports arguments -Wold-style-definition: YES
      Compiler for C supports arguments -Wpointer-sign: YES
      Compiler for C supports arguments -Wstrict-prototypes: YES
      Configuring _dbus-python-config.h using configuration

      Executing subproject dbus-gmain

      dbus-gmain| Project name: dbus-gmain
      dbus-gmain| Project version: undefined
      dbus-gmain| C compiler for the host machine: cc (gcc 7.3.1 "cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)")
      dbus-gmain| C linker for the host machine: cc ld.bfd 2.29.1-31
      dbus-gmain| Compiler for C supports arguments -fno-common: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wcast-align: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wdouble-promotion: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wduplicated-branches: YES
      dbus-gmain| Compiler for C supports arguments -Wduplicated-cond: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wfloat-equal: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-nonliteral: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-security: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat=2: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Winit-self: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wlogical-op: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-declarations: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-format-attribute: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-include-dirs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-noreturn: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnull-dereference: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpacked: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-arith: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wredundant-decls: YES
      dbus-gmain| Compiler for C supports arguments -Wshadow: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wswitch-default: YES
      dbus-gmain| Compiler for C supports arguments -Wswitch-enum: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wundef: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wunused-but-set-variable: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wwrite-strings: YES
      dbus-gmain| Compiler for C supports arguments -Wdeclaration-after-statement: YES
      dbus-gmain| Compiler for C supports arguments -Wjump-misses-init: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnested-externs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wold-style-definition: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-sign: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
      dbus-gmain| Found pkg-config: /bin/pkg-config (0.27.1)
      dbus-gmain| Run-time dependency dbus-1 found: YES 1.10.24
      dbus-gmain| Run-time dependency glib-2.0 found: YES 2.56.1
      dbus-gmain| Run-time dependency gthread-2.0 found: YES 2.56.1
      dbus-gmain| Program dbus-run-session found: YES (/bin/dbus-run-session)
      dbus-gmain| Build targets in project: 1
      dbus-gmain| Subproject dbus-gmain finished.

      Program python found: YES (/var/tmp/testvenv/bin/python3)
      Dependency dbus-1 found: YES 1.10.24 (cached)
      Configuring TestSuitePythonService.service using configuration
      Configuring tmp-session-bus.conf using configuration
      Program dbus-run-session found: YES (/bin/dbus-run-session)
      Build targets in project: 5

      dbus-python 1.3.2

        Subprojects
          dbus-gmain  : YES

        User defined options
          Native files: /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd/.mesonpy-native-file.ini
          debug       : false
          optimization: 2
          prefix      : /usr

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-rhr4k8x3/overlay/bin/ninja
      [1/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_bus.c.o
      [2/32] Compiling C object subprojects/dbus-gmain/libdbus-gmain.a.p/dbus-gmain.c.o
      [3/32] Linking static target subprojects/dbus-gmain/libdbus-gmain.a
      [4/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_bytes.c.o
      [5/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_abstract.c.o
      [6/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_conn.c.o
      [7/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_debug.c.o
      [8/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_exceptions.c.o
      [9/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_containers.c.o
      [10/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_float.c.o
      [11/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_conn-methods.c.o
      [12/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_generic.c.o
      [13/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_unixfd.c.o
      [14/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_libdbusconn.c.o
      [15/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_int.c.o
      [16/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_mainloop.c.o
      [17/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_message-append.c.o
      [18/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_message-get-args.c.o
      [19/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_message.c.o
      [20/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_module.c.o
      [21/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_pending-call.c.o
      [22/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_signature.c.o
      [23/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_server.c.o
      [24/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_string.c.o
      [25/32] Compiling C object _dbus_glib_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_glib_bindings_module.c.o
      [26/32] Compiling C object test/dbus_py_test.cpython-37m-x86_64-linux-gnu.so.p/dbus_py_test.c.o
      [27/32] Compiling C object _dbus_bindings.cpython-37m-x86_64-linux-gnu.so.p/dbus_bindings_validation.c.o
      [28/32] Linking target _dbus_glib_bindings.cpython-37m-x86_64-linux-gnu.so
      [29/32] Linking target test/dbus_py_test.cpython-37m-x86_64-linux-gnu.so
      [30/32] Linking target _dbus_bindings.cpython-37m-x86_64-linux-gnu.so
      [31/32] Compiling C object test/test-import-repeatedly.p/import-repeatedly.c.o
      [32/32] Linking target test/test-import-repeatedly
      INFO: autodetecting backend as ninja
      INFO: calculating backend command to run: /tmp/pip-build-env-rhr4k8x3/overlay/bin/ninja
      Traceback (most recent call last):
        File "/tmp/pip-build-env-rhr4k8x3/overlay/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 194, in run
          return options.run_func(options)
        File "/tmp/pip-build-env-rhr4k8x3/overlay/lib/python3.7/site-packages/mesonbuild/minstall.py", line 823, in run
          if not rebuild_all(opts.wd, backend):
        File "/tmp/pip-build-env-rhr4k8x3/overlay/lib/python3.7/site-packages/mesonbuild/minstall.py", line 804, in rebuild_all
          ret = subprocess.run(ninja + ['-C', wd], env=env, preexec_fn=preexec_fn).returncode
        File "/usr/lib64/python3.7/subprocess.py", line 488, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: '/tmp/pip-build-env-rhr4k8x3/overlay/bin/ninja'

      ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
      + meson setup --prefix=/usr /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd/.mesonpy-bp352uvh/build --native-file=/tmp/pip-insta
ll-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      + meson compile
      + meson install --destdir /tmp/pip-install-6mfs8xlv/dbus-python_0d3f5371cb4c472b82c44c739b92a3dd/.mesonpy-bp352uvh/install
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Expected behavior**

The build to complete without permission errors.

**system parameters**
* Amazon Linux 2
* python 3.7.18
* meson 1.1.0

**Comment by eli-schwartz** [comment]
This is generically fixable, but this can also be solved on the meson-python side. In fact, it's been solved via https://github.com/mesonbuild/meson-python/pull/383 and specifically via commit https://github.com/mesonbuild/meson-python/commit/7617ed3fdc09427acfc8b23c222a08332bd13fed

@dnicolodi @rgommers any idea when the next meson-python release is due? If nothing else, maybe the --no-rebuild improvement could be backported?

**Comment by dnicolodi** [comment]
@eli-schwartz A new meson-python release is expected very soon, there are just a couple of loose ends to tie up. The change can be backported, but I don't know if it easier to wait for the last things to be resolved and release the next version or prepare a bugfix release.

**Comment by rgommers** [comment]
Probably 0.13.0 asap rather than a 0.12.2 bug fix release. Also, it seems like we should add a `sudo pip install` test in meson-python CI. Never a shortage of more things to test.

**Comment by eli-schwartz** [comment]
On a somewhat related note if anyone has any idea of the underlying cause for https://github.com/mesonbuild/meson/issues/11662#issuecomment-1503778088 I'm quite puzzled by that.
