### ISSUE TITLE
Install target fails with foo.extract_all_objects() on debug builds due to missing pdb files

### ISSUE THREAD

**Issue by dvdhrm** [mesonbuild/meson#1169]
Hey

`ninja install` fails on linux due to missing `.pdb` files if I use `foo.extract_all_objects()`. See the following meson.build file:

```
project('foobar', 'c', default_options: [ 'buildtype=debug' ])

foo = static_library('foo', ['foo.c'], pic: true)
bar = shared_library('bar', objects: foo.extract_all_objects(), install: true)
```

The foo.c source file can be an empty file (or just some dummy). Building this works fine, but a `ninja install` fails (see the log below).

If I use a non-debug buildtype it works (i.e., `debug` and `debugoptimized` fail). Same result on git-master. I only tested on linux.

If I specify the source files in the shared-lib directly, rather than using the object-files from the static-lib, then it works.

Thanks
David

```
$ DESTDIR=foo ninja -C build/ install
ninja: Entering directory `build/'
[0/1] Installing files.
Installing libbar.pdb to foo/usr/local/lib/libbar.pdb
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 249, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 239, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 251, in run
    do_install(datafilename)
  File "/usr/lib/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 54, in do_install
    install_targets(d)
  File "/usr/lib/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 205, in install_targets
    do_copy(fname, outname)
  File "/usr/lib/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 36, in do_copy
    shutil.copyfile(from_file, to_file)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'libbar.pdb'
FAILED: install 
'/usr/bin/python3' '/usr/bin/meson' '--internal' 'install' '/home/FOOBAR/build/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
Pdb files should only be used when compiling with Visual Studio so this is strange. Are you cross compiling or is this a native Linux build?

**Comment by dvdhrm** [comment]
Native build.

**Comment by nirbheek** [comment]
This is hilarious and probably my fault. I can reproduce it. I guess object extraction has been totally broken since 0.36.

**Comment by nirbheek** [comment]
I can see what the problem is, and there's a lot of breakage in here. Working on a PR.
