### ISSUE TITLE
`install` and `install_dir` is broken

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#11748]
While working on  #11740, I found a mypy warning. Further investigation lead to finding some issues regarding the `install` and `install_dir` kwargs. We need to decide how we want to handle certain things. Once we made a decision, I can do the implementation.

1. The meson documentation claims that only strings are accepted as `install_dir`, except for custom_target which accepts strings and `false`.
The implementation however accepts strings, false and true (except for custom_target).

Should I document this undocumented feature or remove this undocumented feature?

2. Unhandled Exception

This code:
```meson
project('hello', 'c')
foo = shared_library('foo', 'foo.c', install: true, install_dir: false)
hello = shared_library('hello', 'hello.c', link_with: foo, install: true)
```
results in:
```
Traceback (most recent call last):                                                                  
  File "/home/volker/Sync/git/meson/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/home/volker/Sync/git/meson/mesonbuild/msetup.py", line 318, in run
    app.generate()
  File "/home/volker/Sync/git/meson/mesonbuild/msetup.py", line 194, in generate
    self._generate(env)
  File "/home/volker/Sync/git/meson/mesonbuild/msetup.py", line 259, in _generate
    intr.backend.generate()
  File "/home/volker/Sync/git/meson/mesonbuild/backend/ninjabackend.py", line 619, in generate
    self.generate_install()
  File "/home/volker/Sync/git/meson/mesonbuild/backend/ninjabackend.py", line 1238, in generate_install
    self.create_install_data_files()
  File "/home/volker/Sync/git/meson/mesonbuild/backend/backends.py", line 1612, in create_install_data_files
    pickle.dump(self.create_install_data(), ofile)
  File "/home/volker/Sync/git/meson/mesonbuild/backend/backends.py", line 1599, in create_install_data
    self.generate_target_install(d)
  File "/home/volker/Sync/git/meson/mesonbuild/backend/backends.py", line 1681, in generate_target_install
    mappings = t.get_link_deps_mapping(d.prefix)
  File "/home/volker/Sync/git/meson/mesonbuild/build.py", line 2112, in get_link_deps_mapping
    mappings = self.get_transitive_link_deps_mapping(prefix)
  File "/home/volker/Sync/git/meson/mesonbuild/build.py", line 1049, in get_transitive_link_deps_mapping
    mapping = i.get_link_deps_mapping(prefix)
  File "/home/volker/Sync/git/meson/mesonbuild/build.py", line 2117, in get_link_deps_mapping
    new = os.path.join(prefix, outdirs[0], fname)
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'bool'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

3. `install` and `install_dir` is bad design

Instead of having and `install` and and `install_dir` kwarg argument, we could have just one argument that accepts strings and bools (or lists thereof if there are multiple outputs), where
- `false` means it won't get installed
- `true` means it will get installed to the default location
- strings means it will get installed to this path

Having an `install` kwarg *and* an `install_dir` kwarg that accepts bools feels like duplicate information, which is bad design.

I know, I know, we cannot change that because of backwards compatibility.

4. Dependencies don't get installed
Let's say this is your project:
```meson
project('hello', 'c')
foo = shared_library('foo', 'foo.c', install: false)
hello = shared_library('hello', 'hello.c', link_with: foo, install: true)
```
Then libhello.so will get installed, but libfoo.so does not. This will (nearly) always lead to linking errors when someone installs the package and tries to run it. Should we 
- keep it as is?
- Print a warning, e.g. "Warning: 'hello' links to 'foo', but 'foo' won't get installed. This will lead to linking errors if 'hello' is used." 
- Install `libfoo.so` as well?
- Install `libfoo.so` as well, but print a warning, e.g. `Warning: 'foo' will get installed to the standard location, even though you said otherwise, because its needed as a dependency.`

Interestingly, `install_name_mappings` is `{'@rpath/libfoo.dylib': '/usr/local/lib/libfoo.so', '@rpath/libhello.dylib': '/usr/local/lib/libhello.so'}` in this case. I have not checked if this can lead to problems, but it seems bad.

**Comment by Volker-Weissmann** [comment]
> 1. This is a documented feature, but only available on https://mesonbuild.com/Vala.html -- since in that case you can have multiple outputs.

It is *documented* only for Vala and custom_target, but available for all languages.

> 3. ...

Ok, your right.

> 4. ...

Ok.

**Comment by eli-schwartz** [comment]
> It is *documented* only for Vala and custom_target, but available for all languages.

I wish that was my only problem with the vala support. :D

Nonetheless, it is not an undocumented feature and cannot be removed. Improvements to the other parts of the documentation are appropriate and welcome.

**Comment by Volker-Weissmann** [comment]
I thought about it again and I'm not totally convinced... For now, I just put an `assert isinstance(outdirs[0], str), "You hit a known issue in meson, see https://github.com/mesonbuild/meson/issues/11748"` there, to silence mypy and to provide a reference to a reader or user.

**Comment by albfan** [comment]
Maybe related with https://gitlab.gnome.org/GNOME/gitg/-/issues/412

**Comment by xclaesse** [comment]
If I understand correctly, currently `shared_library('foo', 'foo.c', install: true, install_dir: false)` crash and that's not acceptable whatever is the reason.

There are 2 ways to fix this IMHO:
- Explicitly forbid `install_dir: false`, the first item in the install_dir list must always be a string. Booleans could be allowed only for extra outputs (vala specific).
- Allow bool for 1st install_tag and it should then be respected and skip install of the 1st output. Extra vala outputs might still be installed, but that's super weird niche case...

I prefer first solution personally. Better be stricter, especially for something that was not working previously anyway.

**Comment by xclaesse** [comment]
@albfan it is somewhat related, but a bit different since this issue is a crash even when not using vala/python. I made a fix for the gitg regression: https://github.com/mesonbuild/meson/pull/12218.

**Comment by eli-schwartz** [comment]
Option 2 is only acceptable to me if it is only permitted when at least one other output *is* installed.

Does that use case currently work? If so, we have to preserve it. If not, then I still prefer option 1, the same as you, but I'd be open to hearing arguments from users about why they need to do this *before* adding support.

**Comment by xclaesse** [comment]
Actually, we have to allow `true` for first install_dir: https://gitlab.gnome.org/GNOME/gitg/-/blob/master/libgitg/meson.build?ref_type=heads#L148. But we can still forbit `false`.
