### ISSUE TITLE
Meson exception when generate Rust test from Rust library when external dependency with `link_args` is used

### ISSUE THREAD

**Issue by vanc** [mesonbuild/meson#11741]
**Describe the bug**
When `b_sanitize` is set to `address`, if use the Rust's module test method to generate a test from a Rust `rlib` target, linking would fail because of missing all symbols from the asan library.

With Cargo, I can use build.rs to inject a link command `cargo:rustc-link-lib=asan` based on an environment variable passed from meson.build. But with `rust.test`, I tried to use an external dependency with only a `link_args: '-lasan'` and got an exception.

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 271, in run
    return msetup.run(['--reconfigure'] + args[2:])
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/msetup.py", line 310, in run
    app.generate()
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/msetup.py", line 187, in generate
    self._generate(env)
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/msetup.py", line 251, in _generate
    intr.backend.generate()
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 615, in generate
    self.generate_target(t)
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 824, in generate_target
    self.generate_rust_target(target)
  File "/home/user/.local/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 1990, in generate_rust_target
    _type = 'static' if e.static else 'dylib'
AttributeError: 'InternalDependency' object has no attribute 'static'
```

**To Reproduce**
1. Create a Rust library with `rust-crate-type` as `rlib` and generate some unit tests.
2. Import `rust` module and use `rust.test()` to convert the rlib to a meson test.
3. Enable sanitizer with `meson setup builddir -Db_sanitize=address`
4. meson test would fail because of missing symbols from `asan`.

Now declare an external dependency with:
```
    dep_asan = declare_dependency(link_args: '-lasan')
```
And add the dependency to the dependency list of the test target. For example:

```
   rust = import('rust')
   rust.test('myrlib', myrlib, dependencies: [dep_asan])
```

Run meson setup again and got the backtrace.

**Expected behavior**
There should be some way to allow Rust test to link with some extra libraries.

**system parameters**
Meson version: 1.0.2
Python: 3.8

**Comment by gfxstrand** [comment]
cc @dcbaker I just hit this in Mesa

**Comment by bonzini** [comment]
This almost works for me.

meson.build:

```
project(
  'testprog',
  ['c', 'rust'],
  version : '0.1',
  meson_version : '>= 1.3.0',
  default_options : ['rust_std=2021', 'warning_level=3'],
)

rust = import('rust')
dependencies = [
  declare_dependency(link_args: '-fsanitize=address')
]

clib = static_library(
  'clib',
  'f.c',
  dependencies : dependencies,
  rust_crate_type: 'rlib',
  install : true,
)
lib = static_library(
  'testprog',
  'testprog.rs', link_with: [clib],
  dependencies : dependencies,
  rust_crate_type: 'rlib',
  install : true,
)

rust.test('testprog', lib)

# Make this library usable as a Meson subproject.
testprog_dep = declare_dependency(
  include_directories : include_directories('.'),
  dependencies : dependencies,
  link_with : lib,
)
meson.override_dependency('testprog', testprog_dep)
```

f.c:
```
extern int internal_function(void);
int internal_function() {
    return 0;
}
```

testprog.rs:
```
#![crate_name = "testprog"]

extern "C" { fn internal_function() -> i32; }

pub fn tes_func() -> i32 {
    unsafe { internal_function() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_function() {
        assert_eq!(tes_func(), 0);
    }
}
```

The problem is that sanitizer flags are not added to the rustc linking command line. But that's unrelated to `rust.test()`

**Comment by bonzini** [comment]
Closing since the problematic line of code (`_type = 'static' if e.static else 'dylib'`) does not exist anymore. The code now looks like this:

```python
        def _link_library(libname: str, static: bool, bundle: bool = False) -> None:
            orig_libname = libname
            type_ = 'static' if static else 'dylib'
            modifiers = []
```
