### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by RainbowTaro2022** [mesonbuild/meson#11770]
G:\Cone\gstreamer>meson setup build
The Meson build system
Version: 1.1.0
Source dir: G:\Cone\gstreamer
Build dir: G:\Cone\gstreamer\build
Build type: native build
Project name: gstreamer
Project version: 1.19.2
Activating VS 17.5.1
Traceback (most recent call last):
  File "G:\python310\lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
    return options.run_func(options)
  File "G:\python310\lib\site-packages\mesonbuild\msetup.py", line 318, in run
    app.generate()
  File "G:\python310\lib\site-packages\mesonbuild\msetup.py", line 194, in generate
    self._generate(env)
  File "G:\python310\lib\site-packages\mesonbuild\msetup.py", line 216, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "G:\python310\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 330, in __init__
    self.parse_project()
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 134, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "G:\python310\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "G:\python310\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1296, in func_project
    mesonlib.setup_vsenv(force_vsenv)
  File "G:\python310\lib\site-packages\mesonbuild\utils\vsenv.py", line 118, in setup_vsenv
    return _setup_vsenv(force)
  File "G:\python310\lib\site-packages\mesonbuild\utils\vsenv.py", line 95, in _setup_vsenv
    bat_output = subprocess.check_output(bat_file.name, universal_newlines=True)
  File "G:\python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "G:\python310\lib\subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "G:\python310\lib\subprocess.py", line 1141, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2372: illegal multibyte sequence

meson.build:1:0: ERROR: Unhandled python exception

**Comment by eli-schwartz** [comment]
This sounds like #10799, does updating vswhere help?

**Comment by bruchar1** [comment]
Fixed by #12088. @eli-schwartz we may close it.
