### ISSUE TITLE
cannot communicate with fpga getting issues

### ISSUE THREAD

**Issue by kmlrohin1** [mesonbuild/meson#11843]
while we type this command ( ./gsd_butterstick.py --uart-name=crossover --with-etherbone --csr-csv=csr.csv --build --load ) we getting the error as:
WARNING: Unknown CPU family riscv, please report this at https://github.com/mesonbuild/meson/issues/new
The Meson build system
Version: 0.61.5
Source dir: /home/kml/python-litex/pythondata-software-picolibc/pythondata_software_picolibc/data
Build dir: /home/kml/python-litex/litex-boards/litex_boards/targets/build/gsd_butterstick/software/libc
Build type: cross build
Project name: picolibc
Project version: 1.7.9

../../../../../../../pythondata-software-picolibc/pythondata_software_picolibc/data/meson.build:35:0: ERROR: Value "c18" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11", "gnu89", "gnu99", "gnu11".

A full log can be found at /home/kml/python-litex/litex-boards/litex_boards/targets/build/gsd_butterstick/software/libc/meson-logs/meson-log.txt
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
/home/kml/python-litex/litex/litex/soc/software/libc/Makefile:42: recipe for target '__libc.a' failed
make: *** [__libc.a] Error 1
make: Leaving directory '/home/kml/python-litex/litex-boards/litex_boards/targets/build/gsd_butterstick/software/libc'
Traceback (most recent call last):
  File "./gsd_butterstick.py", line 204, in <module>
    main()
  File "./gsd_butterstick.py", line 197, in main
    builder.build(**parser.toolchain_argdict)
  File "/home/kml/python-litex/litex/litex/soc/integration/builder.py", line 354, in build
    self._generate_rom_software(compile_bios=use_bios)
  File "/home/kml/python-litex/litex/litex/soc/integration/builder.py", line 288, in _generate_rom_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/kml/python-litex/litex-boards/litex_boards/targets/build/gsd_butterstick/software/libc', '-f', '/home/kml/python-litex/litex/litex/soc/software/libc/Makefile']' returned non-zero exit status 2.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Reference-tables.html#cpu-families

It should not be riscv, but rather riscv32 or riscv64.

c18 should also work as long as you have a GCC/clang version that actually supports that std. What is your version?
