### ISSUE TITLE
libgfortran not correctly linked when installing package

### ISSUE THREAD

**Issue by Thelxtess** [mesonbuild/meson#11878]
**Describe the bug**
When installing a Python package with Fortran module extensions, the libgfortran library is not correctly linked to the built .so (on Unix) or .pyd (on Windows) extension module files.

**To Reproduce**
Package structure:
```
meson_test/
├── meson_test/
│   ├── __init__.py
│   └── string_operations.f90
├── meson.build
└── pyproject.toml
```

The `meson.build` file and `pyproject.toml` are included as .txt.
The file `__init__.py` is empty and the extension file `string_operations.f90` is:
```
module string_operations
    implicit none

    contains

        subroutine adjust_left(str_in, str_out)
                implicit none
    
                character(len=25), intent(in) :: str_in
                character(len=25), intent(out)  :: str_out
    
                str_out = trim(adjustl(str_in))
        end subroutine adjust_left

end module string_operations
```

*Windows*
On Windows, the package is "successfully" installed using:
```
pip install --no-build-isolation -e . -U -vvv
```
The corresponding log file is attached.

Then, in a Python console, I get the following error when importing the module:
```
PS C:\Users\username\Documents\programs\Python\meson_test> python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from meson_test import string_operations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing string_operations: The specified module could not be found.
```

The error is fixed by manually adding the folder containing the libgfortran library:
```
>>> import os
>>> os.add_dll_directory("C:/msys64/mingw64/bin/")
<AddedDllDirectory('C:/msys64/mingw64/bin/')>
>>> from meson_test import string_operations
>>> string_operations.string_operations.adjust_left('   gfortran    ')
b'gfortran'
```
Note that 'C:/msys64/mingw64/bin/' was in my PATH variable environment (down with respect to my python.exe, I'm not sure if that is important).

*Linux*
On Linux, something similar happened with the same package, on a cluster where I do not have sudo rights. I installed the package in the same way, with a "successful" result.

Then, in a python console, I get a very similar error:
```
~/packages/meson_test> python3
Python 3.9.7 (default, Sep 16 2021, 13:09:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
from meson_test import string_operations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libgfortran.so.5: cannot open shared object file: No such file or directory
```

When I use `ldd build/cp39/string_operations.cpython-39-x86_64-linux-gnu.so`, I got:
```
linux-vdso.so.1 (0x00007ffe566aa000)
libgfortran.so.5 => not found
libm.so.6 => /lib64/libm.so.6 (0x0000148044d36000)
libc.so.6 => /lib64/libc.so.6 (0x0000148044941000)
/lib64/ld-linux-x86-64.so.2 (0x000014804529d000)
```

This time, I needed to add the the cluster's special path to libgfortran.so.5 to my "$LD_LIBRARY_PATH" in order to fix the issue.
Note that libgfortran.so.5 was correctly linked when I directly used `f2py` on `string_operations.f90` and checked its .so dependencies using `ldd`, which made me think that the issue is not with f2py but with meson.

**Expected behavior**
The fortran extensions should work directly when imported with no additional input required from the user. 
If the issue is not with meson but with the user's setup, inform them that something went wrong during installation instead of letting pip print that it was successful.

**system parameters**
* this is a native build
* operating system: Windows 11 22H2 and SUSE 15.3
* Python version: 3.11.3 and 3.9.7
* `meson --version`: 1.1.1 (both)
* `ninja --version`: 1.11.1.git.kitware.jobserver-1 (both)
[meson.build.txt](https://github.com/mesonbuild/meson/files/11747461/meson.build.txt)
[pyproject.toml.txt](https://github.com/mesonbuild/meson/files/11747469/pyproject.toml.txt)
[pip_install_log.txt](https://github.com/mesonbuild/meson/files/11747565/pip_install_log.txt)

**Comment by eli-schwartz** [comment]
I don't think the Windows add_dll_directory issue is solvable from meson, you need to specially handle it in your source code if I recall correctly.

On Linux you can add `-Wl,-rpath=` to your $LDFLAGS to add directories that are part of the compiler you used but not part of the `ld.so` loader that python itself uses.

Maybe f2py unconditionally adds rpath entries?

**Comment by eli-schwartz** [comment]
@rgommers

**Comment by rgommers** [comment]
Ah, yes ..... there's a number of separate things going on here:

1. everything basically looks good (a few warnings in the build log, but those can be ignored, they're not related to the problem with `libgfortran.dll` here)
2. f2py is only used as a transpiler, it emits `.c` and `.f90` files - so it does nothing related to RPATHs, that's the job of the following `py.extension_module` call in `meson.build.
3. On a standard Linux or macOS machine, this will all work out of the box. The Python extension module indeed will have an RPATH entry for wherever `libgfortran.so` is located (or it's in a standard path that the shared library loader already knows about).
4. On Windows, the problem is that there is no RPATH mechanism indeed. There are two potential solutions/workarounds for that:
    - Build a regular wheel instead of an editable one, and run [delvewheel](https://github.com/adang1345/delvewheel) over it to vendor `libgfortran.dll`. That's how you build wheels that are suitable to redistribute on PyPI; it works locally too.
    - Copy the needed DLL(s) into the source tree and/or use `os.add_dll_directory` as needed to ensure that that DLL gets found. SciPy has a hacky CLI flag to do this for local development (see [here](https://github.com/scipy/scipy/blob/9bc74cd8f4b42016cb85766524df0316d365c97f/dev.py#L428)), and it writes out a file that hooks in the needed `os.add_dll_directory` usage [here](https://github.com/scipy/scipy/blob/9bc74cd8f4b42016cb85766524df0316d365c97f/tools/openblas_support.py#L228-L264) for wheel builds.
5. The (4) above may seem very strange, but .... this is basically how Windows is designed: if you need a bunch of DLLs for your "app", you copy _all_ of them into a single directory and bundle that with your "app". A Python package is an app here.
    - There's nothing Meson can do about this.
    - Conceivably some of the hacky copying around of DLLs could be included in `meson-python`, but I'd be quite reluctant to touch that. I'd rather start with better docs to explain what is going on.
6. The Linux cluster thing I'm less sure about - that should work I believe if you use the conda compilers. The problem there may be that Python is built with one set of compilers and you are building your own package with another set - at which point a needed library path to `custom-cluster-root/libdir/` may go missing. The easiest way around it is probably to set `LD_LIBRARY_PATH` to where `libgfortran.so` is located.

**Comment by eli-schwartz** [comment]
On point 2, I seem to recall that f2py has a flag to also compile the extension using an autogenerated numpy.distutils stub?

**Comment by rgommers** [comment]
Yes it does, but you really don't want to use that when you're using Meson. And if you use `numpy.distutils`, it's preferred to use the `Configuration.add_extension` class/method that it provides directly - it understands Fortran/f2py natively, and is better than using the f2py CLI.

**Comment by eli-schwartz** [comment]
Right, but for the purposes of this discussion I'm only concerned with responding to the OP analysis of:
> I directly used `f2py` on `string_operations.f90` and checked its .so dependencies using `ldd`, which made me think that the issue is not with f2py but with meson.

**Comment by rgommers** [comment]
Ah okay, that helps. Yes, it's a little fuzzy to me what's up with that cluster setup. Does it use the same compilers etc.? Meson _should_ indeed be writing that RPATH and meson-python should preserve them.

**Comment by Thelxtess** [comment]
Thanks for your answers.

So if I understand correctly, for Windows there is no way around adding the dll directory (or using wheels). So far I fixed this in my package by adding all directories in the PATH environment variable as dll directories in the package's main `__init__.py` file (since libgfortran might be installed in different places depending on the user). I was not happy with that solution so I will gladly take inspiration from SciPy.

I am still surprised though. With `numpy.distutils` that I previously used, a Windows pip installation created extension module .dll files in a .libs directory, in addition to the .pyd files. All I had to do was to `os.add_dll_directory` that directory, without the need to copy or link to external libraries. It was quite convenient, but maybe that's not possible with meson's stricter rules?

> 3. On a standard Linux or macOS machine, this will all work out of the box.

Indeed. I also installed my package on Linux machine for which I have sudo rights and had no issue.

For your point (6) solution, this is what I did. But again I am surprised: with `numpy.distutils` I had no issue. How can I test for the difference in compilers? I can ask the cluster's administrator for more details if you want to investigate this further.
