### ISSUE TITLE
Meson fails to build a project using `zig cc` with -target

### ISSUE THREAD

**Issue by notcancername** [mesonbuild/meson#11886]
**Describe the bug**
Meson will not build a project using `zig cc` with a target.

<details>
<summary>Trace</summary>

```
The Meson build system
Version: 1.0.1
Source dir: /home/user/src/repro
Build dir: /home/user/src/repro/build
Build type: native build
Project name: repro
Project version: 0.1

meson.build:1:0: ERROR: Unable to get clang pre-processor defines:
Compiler stdout:

-----
Compiler stderr:
error: unknown target triple 'native-native-unknown-musl', please use -triple or -arch

-----


A full log can be found at /home/user/src/repro/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Traceback (most recent call last):
  File "/home/user/.local/bin/meson", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 287, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 278, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 196, in run
    return errorhandler(e, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 40, in errorhandler
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 310, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 187, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 209, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 328, in __init__
    self.parse_project()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 117, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 172, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 165, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 178, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 460, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 590, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 1245, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 1381, in add_languages
    success = self.add_languages_for(args, required, for_machine)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 1421, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/detect.py", line 115, in detect_compiler_for
    comp = compiler_from_language(env, lang, for_machine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/detect.py", line 112, in compiler_from_language
    return lang_map[lang](env, for_machine) if lang in lang_map else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/detect.py", line 577, in detect_c_compiler
    return _detect_c_or_cpp_compiler(env, 'c', for_machine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/detect.py", line 434, in _detect_c_or_cpp_compiler
    defines = _get_clang_compiler_defines(compiler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/compilers/detect.py", line 1288, in _get_clang_compiler_defines
    raise EnvironmentException('Unable to get clang pre-processor defines:\n'
mesonbuild.utils.universal.EnvironmentException: Unable to get clang pre-processor defines:
Compiler stdout:

-----
Compiler stderr:
error: unknown target triple 'native-native-unknown-musl', please use -triple or -arch

-----
```

</details>

**To Reproduce**
`export CC='zig cc -target native-native-musl'`

```meson
project('repro', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('repro', 'repro.c',
  install : true)

test('basic', exe)
```

**Expected behavior**
Meson should build the project.

**system parameters**
```
meson: 1.0.1
python: 3.11.4
zig: 0.11.0-dev.3395+1e7dcaa3a
```

**Comment by trim21** [comment]
I think we already support `zig cc` with target in some version of meson (I'm not sure).

**Comment by thesamesam** [comment]
Either 798bf519035808aa4d86e6b58d7a6b3c5e4b2988 or 2c10d77c3c7b2b9ad3464ef37bc6eb01fb34deb0.

**Comment by trim21** [comment]
> Either [798bf51](https://github.com/mesonbuild/meson/commit/798bf519035808aa4d86e6b58d7a6b3c5e4b2988) or [2c10d77](https://github.com/mesonbuild/meson/commit/2c10d77c3c7b2b9ad3464ef37bc6eb01fb34deb0).

looks like we didn't, 798bf519035808aa4d86e6b58d7a6b3c5e4b2988 support zig linker and  2c10d77c3c7b2b9ad3464ef37bc6eb01fb34deb0 change a function that is only used in CMakeToolcChain, so the meson itself still can't recognize `zig cc --target ...` or `zig c++ --target ...`

<img width="2705" height="1089" alt="Image" src="https://github.com/user-attachments/assets/b0b3e8f2-1447-4a4d-9722-ae6d0c5ac741" />

**Comment by trim21** [comment]
OK, sorry, I just test locally and we did support zig cc/c++ with target. (just not in these 2 commits)

**Comment by thesamesam** [comment]
OK..
