### ISSUE TITLE
Use array in cross file error

### ISSUE THREAD

**Issue by vbextreme** [mesonbuild/meson#11899]
**Describe the bug**
I need to use array in section [properties] in cross file, first attempt with 
```
arr = [ 'a' ]
arr += ['b']
```
but this not works
```
ERROR: Malformed variable name 'arr  +' in machine file
```

I have try with:
```
arr = [ 'a',
'b']
````
and in this case found a bug, meson tell me to report you this bug.
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 278, in run
    return msetup.run(['--reconfigure'] + args[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 318, in run
    app.generate()
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 189, in generate
    env = environment.Environment(self.source_dir, self.build_dir, self.options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/environment.py", line 519, in __init__
    config = coredata.parse_machine_files(self.coredata.cross_files)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/coredata.py", line 1013, in parse_machine_files
    parser = MachineFileParser(filenames)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/coredata.py", line 959, in __init__
    self.parser.read(filenames)
  File "/usr/lib/python3.11/site-packages/mesonbuild/coredata.py", line 947, in read
    return super().read(filenames, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/usr/lib/python3.11/configparser.py", line 1132, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/vbextreme/project/c/test/esp32/cross/esp32'
        [line 28]: "'tools/esp/sdk/esp32/xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/8.4.0/plugin/include',\n"
        [line 29]: "'tools/esp/sdk/esp32/xtensa-esp32-elf/lib/gcc/xtensa-esp32-elf/8.4.0/include-fixed']\n"

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: build.ninja
```  

**To Reproduce**
one meson.build and one crossfile with multiline array in section [properties]
```
$ meson setup --cross-file cf build
```

**Expected behavior**
Any way to create array inside a cross file

**system parameters**
crossbuild: yes
System: arch linux
Python: 3.11.3
Meson: 1.1.1
Ninja: 1.11.1

**Comment by xclaesse** [comment]
> ```
> arr = [ 'a' ]
> arr += ['b']
> ```

That's not supported syntax, try `arr = arr + ['b']`

> ```
> arr = [ 'a',
> 'b']
> ```

Line continuation must be indented, Python doc says:
>  Values can also span multiple lines, as long as they are indented deeper than the first line of the value.

> and in this case found a bug, meson tell me to report you this bug.

Indeed that's a bug, we should catch `configparser.ParsingError` exception and print a better error message.

**Comment by vbextreme** [comment]
ok with indentations works, but think we need to add to documentation.
thanks

**Comment by xclaesse** [comment]
PR welcome :)
