### ISSUE TITLE
error when using MSVC with cpp_std=c++latest

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#11900]
**Describe the bug**

Setting up the project with cpp_std=c++20 works fine! But when setting cpp_std to c++latest Im getting the following unhandled python exception:

```
Traceback (most recent call last):
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/msetup.py", line 318, in run
    app.generate()
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/msetup.py", line 194, in generate
    self._generate(env)
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/msetup.py", line 259, in _generate
    intr.backend.generate()
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 616, in generate
    self.generate_target(t)
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 979, in generate_target
    o, s = self.generate_single_compile(target, src, False, [],
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 2920, in generate_single_compile
    self.add_dependency_scanner_entries_to_element(target, compiler, element, src)
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 2927, in add_dependency_scanner_entries_to_element
    if not self.should_use_dyndeps_for_target(target):
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/backend/ninjabackend.py", line 1021, in should_use_dyndeps_for_target
    if not mesonlib.current_vs_supports_modules():
  File "C:/MSYS2/mingw64/lib/python3.10/site-packages/mesonbuild/utils/universal.py", line 803, in current_vs_supports_modules
    major = int(nums[0])
ValueError: invalid literal for int() with base 10: ''

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

I'm using MSVC build tools 17.6.4, containing cl.exe version 19.36.32535.

meson.build:
```
project('test', 'cpp', default_options: ['cpp_std=c++latest'])
executable('app', 'main.cpp')
```

main.cpp:
```
int main() {}
```

**system parameters**
* A native build.
* Windows 10, inside an MSYS2 MINGW64 environment
* python 3.10.11
* meson 1.1.1
* ninja 1.11.1

**Comment by punytroll** [comment]
Upon inspection, I guess that the function `current_vs_supports_modules()` is only called, because `c++latest` makes `should_use_dyndeps_for_target()` bail out earlier. So, that's why c++latest provokes this error.

Additionally, `current_vs_supports_modules()` uses the environment variable `VSCMD_VER` to detect the version of the MSVC executable. However, this variable is not set in my MSYS2 environment. So, I could just set that to circumvent this error. But I would need to update this value, whenever I update my MSVC build tools ... not ideal.

This makes me question, why `current_vs_supports_modules()` is implemented in terms of the Build Tools version (17.6.4) taken from some (more or less) arbitrary environment variable, instead of the actual compiler version returned by compiler.get_version(). In principle, this should be even simpler, because all of the special version handling should be unnecessary when version-comparing the build version.

Anyway, if the environment variable is not set, an error should be reported.

**Comment by punytroll** [comment]
This is still a problem in meson version 1.3.0.

`This is a Meson bug and should be reported!`

**Comment by ousttrue** [comment]
I had the same problem too.

Environment variable `VSCMD_VER` is required.

https://github.com/mesonbuild/meson/blob/master/mesonbuild/utils/universal.py#L811

```py
def current_vs_supports_modules() -> bool:
```

**Comment by punytroll** [comment]
This is still an unhandled exception in meson version 1.4.1.
I realize, that this environment variable is required, but it should not terminate with an unhandled exception in any case.
In addition to that, IMO, my point remains valid: Why is the BuildTools version (17.6.4) used and not the compiler version?

**Comment by JamBalaya56562** [comment]
Thank you for the report. The crash was in `current_vs_supports_modules()`, which used to call `int(...)` on a `VSCMD_VER` value that could be empty — e.g. in an MSYS2 environment where `VSCMD_VER` isn't set — raising `ValueError: invalid literal for int() with base 10: ''`.

On current master that function guards against an empty/unset value, so the unguarded `int()` conversion no longer exists:

```python
# mesonbuild/utils/universal.py
def current_vs_supports_modules() -> bool:
    vsver = os.environ.get('VSCMD_VER', '')
    return not vsver \
        or version_compare(vsver, '>=16.10.0') \
        or ...
```

An empty/unset `VSCMD_VER` now short-circuits to `True` instead of crashing.

**Verification:** fixed in commit [`5d590c8d`](https://github.com/mesonbuild/meson/commit/5d590c8dfc669c1bca7d53f56c706aa54a784e45) ("compilers: assume MSVC supports C++ Modules if VSCMD_VER not set").

With the crash path gone, this looks safe to close. Thanks again for reporting it.
