### ISSUE TITLE
ValueError: Invalid suffix '_pb2.py'

### ISSUE THREAD

**Issue by haata** [mesonbuild/meson#12021]
**Describe the bug**

Trying to do something simple with fs.replace_suffix.

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 278, in run
    return msetup.run(['--reconfigure'] + args[2:])
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 318, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 194, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 239, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreter.py", line 2971, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreter.py", line 2383, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreter.py", line 2383, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreter.py", line 2383, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreter.py", line 2383, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 228, in evaluate_statement
    self.evaluate_foreach(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 472, in evaluate_foreach
    self.evaluate_codeblock(node.block)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 509, in function_call
    (h_posargs, h_kwargs) = self.reduce_arguments(node.args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 593, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 593, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 792, in method_call
    ret = method(state, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 73, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/modules/fs.py", line 199, in replace_suffix
    new = original.with_suffix(args[1])
  File "/usr/lib/python3.7/pathlib.py", line 843, in with_suffix
    raise ValueError("Invalid suffix %r" % (suffix))
ValueError: Invalid suffix '_pb2.py'

../../../Prod/IDL/Protos/Extensions/meson.build:28:15: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: build.ninja
```

**To Reproduce**

```meson
protos = files(
    'APIException.proto',
    'CustomOptions.proto',
    'DaEventTypes.proto',
    'Exception.proto',
    'KeyValueTypes.proto',
    'LocalizableMessageTypes.proto',
    'ServiceInfoPersist.proto',
)
foreach f: protos
    message(fs.replace_suffix(f, '_pb2.py'))
endforeach
```

**Expected behavior**

Should print
```bash
Message APIException_pb2.py
...
```

**system parameters**

```bash
bash-4.4$ ninja --version
1.8.2
bash-4.4$ meson --version
1.1.1
bash-4.4$ python3 --version
Python 3.7.5
```

**Comment by haata** [comment]
Workaround is
```meson
    message(fs.replace_suffix(f, '') + '_pb2.py')
```
