### ISSUE TITLE
AttributeError: module 'mesonbuild.dependencies' has no attribute 'AppleFrameworks'

### ISSUE THREAD

**Issue by hasayakey** [mesonbuild/meson#12034]
**Describe the bug**
'meson setup builddir --backend=xcode' got error

**To Reproduce**
meson version 1.2.0, try 'meson setup builddir --backend=xcode'

**Expected behavior**
shoud generate xcode project

**system parameters**
* it's a cross build
* Python 3.11
* meson 1.2.0
* MacOS 14.0 Beta (23A5286i)

**Traceback**

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/msetup.py", line 253, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/backend/xcodebackend.py", line 276, in generate
    self.generate_native_frameworks_map()
  File "/opt/homebrew/lib/python3.11/site-packages/mesonbuild/backend/xcodebackend.py", line 459, in generate_native_frameworks_map
    if isinstance(dep, dependencies.AppleFrameworks):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'mesonbuild.dependencies' has no attribute 'AppleFrameworks'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

**Comment by eli-schwartz** [comment]
@jpakkane how utterly unpredictable

**Comment by jielv7758** [comment]
try to Install the specified version eg. 1.1.1

**Comment by JamBalaya56562** [comment]
Thank you for the report. This crash happened because the Xcode backend referenced `dependencies.AppleFrameworks` without that name being guaranteed to be imported at that point, raising `AttributeError: module 'mesonbuild.dependencies' has no attribute 'AppleFrameworks'`.

On current master the backend imports the class explicitly and uses it directly, so the failing attribute lookup no longer occurs:

```python
# mesonbuild/backend/xcodebackend.py
from ..dependencies.platform import AppleFrameworks
...
    if dep.found() and isinstance(dep, AppleFrameworks):
        ...
```

**Verification:** fixed in commit [`665275a7`](https://github.com/mesonbuild/meson/commit/665275a78506b68638f4e996ef8e8b8e549d5c8f) ("xcode: Check for apple framework deps by name").

Since the attribute error is gone, this looks safe to close. Thanks for the report (and for the 1.1.1 workaround note, which helped narrow it down).
