### ISSUE TITLE
pkgconf module when imported but unused breaks devenv

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#12032]
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/[mesonmain.py](http://mesonmain.py/)", line 194, in run
    return [options.run](http://options.run/)_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/[mdevenv.py](http://mdevenv.py/)", line 166, in run
    devenv, varnames = get_env(b, dump_fmt)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/[mdevenv.py](http://mdevenv.py/)", line 70, in get_env
    env = i.get_env(env, default_fmt)
          ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_env'
ERROR: Unhandled python exception
    This is a Meson bug and should be reported!
```

This happens because the pkg-config module will insert a `None` into a list that should not have `None` in it. I'm not sure why mypy/pyright don't complain about this.

**Comment by eli-schwartz** [comment]
> I'm not sure why mypy/pyright don't complain about this.

None is the black hole of anything goes. Getting the entire codebase strict-optional compliant is a tough problem.
