### ISSUE TITLE
Unhandled python exception with malformed environment variable name

### ISSUE THREAD

**Issue by ptomato** [mesonbuild/meson#12198]
**Describe the bug**

I accidentally set an environment variable with an invalid name in a test environment, and got this:
```
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...riable name')>) at /var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py:2024
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...riable name')>) at /var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py:2024>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 2026, in test_done
    f.result()
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 2018, in run_test
    res = await test.run(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1489, in run
    await self._run_cmd(harness, cmd)
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1543, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1517, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.11/asyncio/unix_events.py", line 810, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1836, in _execute_child
    raise ValueError("illegal environment variable name")
ValueError: illegal environment variable name

Ok:                 0   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/home/ptomato/workspace/chimara/_build/meson-logs/testlog.txt
Traceback (most recent call last):
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 2182, in run
    return th.doit()
           ^^^^^^^^^
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1821, in doit
    self.run_tests(runners)
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1994, in run_tests
    asyncio.run(self._run_tests(runners))
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 2095, in _run_tests
    await complete_all(futures)
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1272, in complete_all
    check_futures(done)
  File "/var/home/ptomato/.local/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1261, in check_futures
    f.result()
ValueError: illegal environment variable name

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

**meson.build**:
```meson
project('test')
test_env = environment()
test_env.set('=', '1')
t = find_program('true')
test('test', t, env: test_env)
```

**Expected behavior**

I would still expect an error, but it should not say "This is a Meson bug and should be reported".

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Fedora Silverblue 38**
* what Python version are you using e.g. 3.8.0 **3.11.3**
* what `meson --version` **1.2.1**
* what `ninja --version` if it's a Ninja build **1.11.1**

**Comment by eli-schwartz** [comment]
This is a weird special exception with the single character that's illegal in a variable name... Except of course when it is illegal but works anyways, thanks `/usr/bin/env`. 🙄

From looking at the CPython sources, I ran into some scary code. Apparently it is allowed as the first character on Windows, because something called "hidden environment variables". I think we should just catch this unconditionally though.
