### ISSUE TITLE
extract_objects on an internal dependency crashes

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#12308]
**Describe the bug**
If you call `declare_dependency(link_with:...).extract_objects(...)`, then Meson crashes.

**To Reproduce**
Add this line to the test case:
```diff
diff --git a/test cases/common/80 declare dep/meson.build b/test cases/common/80 declare dep/meson.build
index e427defaf..761a92478 100644
--- a/test cases/common/80 declare dep/meson.build
+++ b/test cases/common/80 declare dep/meson.build
@@ -6,6 +6,7 @@ exe = executable('dep_user', 'main.c',
   dependencies : entity_dep)
 test('dep', exe)

+entity_dep.extract_objects('entity1.c')
 # just to make sure [] works as a no-op dep here
 executable('dummy', 'main.c',
   dependencies : [entity_dep, []])
```
then run `meson.py setup 'test cases/common/80 declare dep' build`, which produces this exception:
```pytb
Traceback (most recent call last):
  File "/home/elliott/code/meson/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/code/meson/mesonbuild/msetup.py", line 356, in run
    app.generate()
  File "/home/elliott/code/meson/mesonbuild/msetup.py", line 179, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/code/meson/mesonbuild/msetup.py", line 224, in _generate
    intr.run()
  File "/home/elliott/code/meson/mesonbuild/interpreter/interpreter.py", line 3011, in run
    super().run()
  File "/home/elliott/code/meson/mesonbuild/interpreterbase/interpreterbase.py", line 162, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/elliott/code/meson/mesonbuild/interpreterbase/interpreterbase.py", line 188, in evaluate_codeblock
    raise e
  File "/home/elliott/code/meson/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/elliott/code/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/elliott/code/meson/mesonbuild/interpreterbase/interpreterbase.py", line 545, in method_call
    self.validate_extraction(obj.held_object)
  File "/home/elliott/code/meson/mesonbuild/interpreter/interpreter.py", line 3381, in validate_extraction
    if self.subproject != buildtarget.subproject:
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InternalDependency' object has no attribute 'subproject'

meson.build:9:27: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Expected behavior**
A clear error that this is not supported.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system Fedora 38
* what Python version are you using 3.11.4
* what `meson --version` 1.2.99 (32be9bd6de0a4769cdf6d9528496925643739918)
* what `ninja --version` if it's a Ninja build n/a

**Comment by bonzini** [comment]
Now returns

    meson.build:9:11: ERROR: Unknown method "extract_objects" in object <[DependencyHolder] holds [InternalDependency]: <InternalDependency dep196339689077002919558588058511171293846: True>> of type DependencyHolder.

A bit verbose but no exception
