### ISSUE TITLE
`not enough values to unpack` when running `meson wrap update`

### ISSUE THREAD

**Issue by pobrn** [mesonbuild/meson#12378]
**Describe the bug**

Running `meson wrap update` produces an "unhandled python exception" error with a stack trace.

```
Checking latest WrapDB version for libva...
  -> Wrap not found in wrapdb
Checking latest WrapDB version for json-glib...
  -> Could not determine current version, use --force to update any way
Checking latest WrapDB version for gl-headers...
Traceback (most recent call last):
  -> Wrap not found in wrapdb
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/wrap/wraptool.py", line 230, in run
    options.wrap_func(options)
  File "/usr/lib/python3.11/site-packages/mesonbuild/msubprojects.py", line 726, in runibwpe, ogg, libdrm, libxml2, liblc3, libpng)
    results = loop.run_until_complete(asyncio.gather(*tasks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Checking latest WrapDB version for bindinator...
  File "/usr/lib/python3.11/site-packages/mesonbuild/msubprojects.py", line 131, in run
    result = self.run_method()
             ^^^^^^^^^^^^^^^^^
  -> Wrap not found in wrapdb
  File "/usr/lib/python3.11/site-packages/mesonbuild/msubprojects.py", line 155, in update_wrapdb
    branch, revision = wrapdb_version.split('-', 1)
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)libjpeg-turbo, libwpe, ogg, libdrm, libxml2, liblc3, libpng)
Checking latest WrapDB version for avtp...
  -> Wrap not found in wrapdb
Progress: 35 / 74 (libopenjp2, sqlite3, lame, expat, glib, libjpeg-turbo, libwpe, ogg, libffi, libdrm, freetype2, libxml2, liblc3, libpng)
ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
Checking latest WrapDB version for liblc3...
  -> Wrap not found in wrapdb
Checking latest WrapDB version for libwpe...
  -> Wrap not found in wrapdb
```

**To Reproduce**

Run `meson wrap update` in the [gstreamer repository](https://gitlab.freedesktop.org/gstreamer/gstreamer/).

**system parameters**
* python 3.11.5
* meson 1.2.2 (seems to happen on `master` as well)

**Comment by tristan957** [comment]
cc @xclaesse

**Comment by xclaesse** [comment]
We should fix the crash in Meson, but the root cause seems bad manual update of some wraps in GStreamer: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/5102#note_2130137.
