### ISSUE TITLE
`gstreamer-full 1.23.0.1` via `jhbuild` fails in `_add_rust_project_entry` with `TypeError: 'str' object is not an iterator` (`Unhandled python exception`)

### ISSUE THREAD

**Issue by db-src** [mesonbuild/meson#12390]
**Describe the bug**

Building `gstreamer` via latest`jhbuild` (specifically, built from `jhbuild` `master` just now, and running`jhbuild build gtkmm`) fails with below error.

I've let `jhbuild` wipe the directory and start over from a fresh clone, but the same thing results each time.

This means I can't get past this dependency and build any GNOME modules using it :-( Help would be greatly appreciated; thanks!

```none
gstreamer-full 1.23.0.1

  Build options
    gstreamer-full library     : NO
    gstreamer-full target type : shared_library
    Tools                      : gst-inspect  gst-stats  gst-typefind  gst-launch  gst-device-monitor  gst-discoverer  gst-play
                                 gst-transcoder  gst-validate  gst-validate-media-check  gst-validate-images-check
                                 gst-validate-rtsp-server  gst-validate-transcoding  ges-launch
    Helpers                    : gst-plugin-scanner  gst-completion-helper
    Libraries                  : gst-editing-services-1.0
    Tests and examples disabled: NO

  Subprojects
    avtp                       : YES
    dv                         : YES
    fdk-aac                    : YES
    gl-headers                 : YES
    gst-devtools               : YES
    gst-editing-services       : YES
    gst-examples               : YES
    gst-integration-testsuites : YES
    gst-libav                  : YES
    gst-plugins-bad            : YES
    gst-plugins-base           : YES 1 warnings
    gst-plugins-good           : YES
    gst-plugins-rs             : NO Feature 'rs' disabled
    gst-plugins-ugly           : YES
    gst-python                 : YES
    gst-rtsp-server            : YES
    gstreamer                  : YES 1 warnings
    gstreamer-sharp            : NO Feature 'sharp' disabled
    gstreamer-vaapi            : NO Feature 'vaapi' disabled
    lame                       : YES 1 warnings
    libnice                    : YES
    libsrtp2                   : YES 1 warnings
    libva                      : YES
    openh264                   : NO Program 'nasm' not found or not executable
    orc                        : YES
    tinyalsa                   : NO Neither a subproject directory nor a tinyalsa.wrap file was found.

  User defined options
    buildtype                  : debugoptimized
    libdir                     : lib
    prefix                     : /opt/jhbuilt/gnome
    bad                        : enabled
    base                       : enabled
    good                       : enabled
    gtk_doc                    : disabled
    libav                      : enabled

Found ninja-1.11.1 at /usr/bin/ninja
Traceback (most recent call last):
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/msetup.py", line 307, in run
    app.generate()
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/msetup.py", line 248, in _generate
    intr.backend.generate()
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 612, in generate
    self.generate_target(t)
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 821, in generate_target
    self.generate_rust_target(target)
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 1960, in generate_rust_target
    self._add_rust_project_entry(target.name, main_rust_file, args, bool(target.subproject),
  File "/opt/jhbuilt/gnome/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 1776, in _add_rust_project_entry
    cfg.append(next(arg))
               ^^^^^^^^^
TypeError: 'str' object is not an iterator

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
*** Error during phase configure of gstreamer: ########## Error running meson setup --prefix /opt/jhbuilt/gnome --libdir lib -Dgtk_doc=disabled -Dbase=enabled -Dgood=enabled -Dbad=enabled -Dlibav=enabled --buildtype=debugoptimized /home/$USER/jhbuild/checkout/gnome/gstreamer *** [32/34]
```

***

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? - plain native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) - `6.5.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1 (2023-09-13) x86_64 GNU/Linux`
* what Python version are you using e.g. 3.8.0 - 3.11.6
* what `meson --version` - 1.2.1
* what `ninja --version` if it's a Ninja build - 1.11.1

**Comment by xclaesse** [comment]
According to @sdroege this is a regression only in Meson 1.2.1, 1.2.2 or 1.2.0 should be fine. Can you confirm please?

**Comment by db-src** [comment]
I've downgraded and will check. I noticed it was using `meson` scripts from `/opt/jhbuilt/gnome/lib/python3.11/site-packages`, so have deleted that, along with the rest of the JHbuild cached and installed folders. It'll take a while to rebuild the lot, but I'll update when I know if it picks up 1.2.0 and works. Thanks!

**Comment by db-src** [comment]
Yep, forcing JHbuild to download Meson 1.2.2 instead of 0.64 resolves it. I guess any remaining bug here is on GNOME's side, and I don't really expect anyone to care about JHbuild, so I guess this will have to do.

Thanks for the pointer @sdroege / @xclaesse !
