### ISSUE TITLE
Failure to create `build.dat` - unhandled python exception

### ISSUE THREAD

**Issue by mitchgrout** [mesonbuild/meson#12397]
**Describe the bug**

`meson setup ...` fails with an unhandled Python exception when setting up a particularly large project. The backtrace is:

```text
Traceback (most recent call last):
  File "C:\Python38\site-packages\mesonbuild\mesonmain.py", line 194, in run
    return options.run_func(options)
  File "C:\Python38\site-packages\mesonbuild\msetup.py", line 358, in run
    app.generate()
  File "C:\Python38\site-packages\mesonbuild\msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
  File "C:\Python38\site-packages\mesonbuild\msetup.py", line 255, in _generate
    build.save(b, dumpfile)
  File "C:\Python38\site-packages\mesonbuild\build.py", line 3118, in save
    pickle.dump(obj, f)
RecursionError: maximum recursion depth exceeded while pickling an object
```

`msetup.py:255` indicates that it is attempting to write `meson-private/build.dat` and failing while pickling.

**To Reproduce**

Currently attempting to figure out the root cause; will update when an MVP is available.

**Expected behavior**

Either the build configuration is accepted and pickled correctly, **or** an appropriate error given to explain why the configuration is rejected.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? - **Both cross and native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) - **Windows 10**
* what Python version are you using e.g. 3.8.0 - **3.8.2**
* what `meson --version` - **1.2.0**
* what `ninja --version` if it's a Ninja build - **1.11.1**

**Comment by mitchgrout** [comment]
Some extra context:

- Currently the configuration is only creating `static_library` targets; there are a total of **56** such targets
- There are 300+ source files being compiled as part of these 56 static libraries
- There is an `include_directories` object with about 80 include paths, which are provided to each static library

**Comment by mitchgrout** [comment]
So this is a bit of bad configuration from me; I wanted to avoid having a `sources` and `includes` list that I would append to, so thought instead to have an 'accumulator dependency' which I would tack sources and includes onto, e.g.

```meson
sources = declare_dependency()

# For each module we're adding...
sources = declare_dependency(sources: [...], include_directories: [...], dependencies: sources)

# Put them all together to make the final executable
executable('target', dependencies: sources)
```

My assumption being here that meson would not store the intermediate dependencies, but instead 'meld them' into the next dependency being made. It looks like this breaks a depth limit put in place by pickle, and gives meson a very unceremonious error.

This style of configuration is a bit stupid in retrospect so I'd probably encourage making it into an error, e.g. if the dependency chain length exceeds some safe number like 50, or 100, then turn that into a hard error.
