### ISSUE TITLE
ERROR: Unhandled python exception

### ISSUE THREAD

**Issue by SysWhiteDev** [mesonbuild/meson#12423]
**Describe the bug**
The bug seems to make any project unbuildable, I am no average user, i started using mason today but the problem seems to be in File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194

**To Reproduce**
1. Install meson on arch linux
2. Try to build [gnome-desktop](https://github.com/GNOME/gnome-desktop/tree/master)
3. Wait for the error

**Expected behavior**
I expected for the build to run normally

**Full log**

```
The Meson build system
Version: 1.2.3
Source dir: /home/white/gnome-desktop
Build dir: /home/white/gnome-desktop/builddir
Build type: native build
Project name: gnome-desktop
Project version: 44.0
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230801")
C linker for the host machine: cc ld.bfd 2.41.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10
Run-time dependency gtk+-3.0 found: YES 3.24.38
Run-time dependency gtk4 found: YES 4.12.3
Run-time dependency glib-2.0 found: YES 2.78.0
Run-time dependency gio-2.0 found: YES 2.78.0
Run-time dependency gio-unix-2.0 found: YES 2.78.0
Run-time dependency gsettings-desktop-schemas found: YES 45.0
Run-time dependency fontconfig found: YES 2.14.2
Run-time dependency xkeyboard-config found: YES 2.40
Run-time dependency xkbregistry found: YES 1.6.0
Run-time dependency iso-codes found: YES 4.15.0
Run-time dependency libsystemd found: YES 254
Run-time dependency libudev found: YES 254
Run-time dependency libseccomp found: YES 2.5.4
Library m found: YES
Library rt found: YES
Checking for function "clock_gettime" with dependency -lrt: YES 
Checking for function "timerfd_create" : YES 
Checking for function "openat" : YES 
Checking for function "uselocale" : YES 
Has header "xlocale.h" : NO 
Configuring config.h using configuration
Configuring gnome-desktop-version.h using configuration
Dependency gio-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/gdbus-codegen found: YES (/usr/bin/gdbus-codegen)
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Dependency gio-2.0 found: YES 2.78.0 (cached)
Program /usr/bin/gdbus-codegen found: YES (/usr/bin/gdbus-codegen)
Compiler for C supports link arguments -Wl,--version-script=/home/white/gnome-desktop/libgnome-desktop/base-symbol.map: YES 
Run-time dependency gobject-introspection-1.0 found: YES 1.78.1
Dependency gobject-introspection-1.0 found: YES 1.78.1 (cached)
Program /usr/bin/g-ir-scanner found: NO
Dependency gobject-introspection-1.0 found: YES 1.78.1 (cached)
Program /usr/bin/g-ir-compiler found: NO
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 228, in _generate
    intr.run()
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 3002, in run
    super().run()
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 196, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 521, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 2414, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 206, in evaluate_statement
    return self.evaluate_if(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 301, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 206, in evaluate_statement
    return self.evaluate_if(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 301, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
    self.assignment(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 811, in method_call
    ret = method(state, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/modules/gnome.py", line 1165, in generate_gir
    self._get_dependencies_flags(deps, state, depends, use_gir_args=True)
  File "/usr/lib/python3.11/site-packages/mesonbuild/modules/gnome.py", line 755, in _get_dependencies_flags
    cflags, internal_ldflags_raw, external_ldflags_raw, gi_includes, depends = self._get_dependencies_flags_raw(deps, state, depends, include_rpath, use_gir_args)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/modules/gnome.py", line 734, in _get_dependencies_flags_raw
    if use_gir_args and self._gir_has_option('--extra-library'):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/modules/gnome.py", line 812, in _gir_has_option
    p, o, _ = Popen_safe(exe.get_command() + ['--help'], stderr=subprocess.STDOUT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/utils/universal.py", line 1485, in Popen_safe
    p = subprocess.Popen(args, universal_newlines=True, encoding=encoding, close_fds=False,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1824, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

libgnome-desktop/meson.build:133:38: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**system parameters**
* Arch Linux
* Python 3.11.5
* meson 1.2.3

**Comment by v1993** [comment]
Possibly related to #12412?

**Comment by SysWhiteDev** [comment]
Confirmed correlation with #12412

**Comment by SysWhiteDev** [comment]
@v1993 can you please delete this issue?

**Comment by v1993** [comment]
I'm a mere contributor who has no control over this repo whatsoever... That aside, there's no real need to delete dupes, closing is good enough.
