### ISSUE TITLE
CMake subproject with dependencies to other subprojects do not work

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#12451]
**Describe the bug**
I want to use Meson to orchestrate different projects.
One of them is CMake based (the project is [InfiniTime](https://github.com/InfiniTimeOrg/InfiniTime)) which needs an external SDK as part of the build process. This SDK contains just a bunch of source files but has no build system. Within InfiniTime's CMake files the path to the SDK is given as variable and used directly in the build files ([for example](https://github.com/InfiniTimeOrg/InfiniTime/blob/main/src/CMakeLists.txt#L34)).
For my own tooling, I additionally need to patch the SDK in various ways (mainly because I want to build it with Clang instead of GCC).
I now want to setup a tooling that downloads the SDK automatically, patch it, and builds InfiniTime with it.
Therefore, I added the SDK and InfiniTime as Meson subproject/wrap and tried to tell Meson about the SDK path.
However, this does not work.

The relevant part in the `meson.build`:
```meson
cmake = import('cmake')

nrf5_sdk = subproject('nrf5-sdk')
patched_sdk = nrf5_sdk.get_variable('patched_sdk')  # points to a folder with the patched SDK within the build directory

infinitime_opts = cmake.subproject_options()
infinitime_opts.add_cmake_defines({'ARM_NONE_EABI_TOOLCHAIN_PATH': arm_fake_toolchain,

                                   'NRF5_SDK_PATH': '@0@'.format(patched_sdk),
                                   'LV_FONT_CONV': lv_font_conv.full_path()})
infinitime = cmake.subproject('InfiniTime', options: infinitime_opts)
```

This results in this error when executing `meson setup build`:
```
...
InfiniTime| CMake configuration: SUCCEEDED
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 183, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 228, in _generate
    intr.run()
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 3002, in run
    super().run()
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_statement
    self.assignment(cur)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 635, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 550, in method_call
    res = obj.method_call(method_name, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 811, in method_call
    ret = method(state, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 690, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 596, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/modules/cmake.py", line 438, in subproject
    subp = self.interpreter.do_subproject(dirname, 'cmake', kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 960, in do_subproject
    raise e
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 946, in do_subproject
    return self._do_subproject_cmake(subp_name, subdir, subdir_abs, default_options, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 1024, in _do_subproject_cmake
    cm_int.analyse()
  File "/usr/lib/python3.11/site-packages/mesonbuild/cmake/interpreter.py", line 934, in analyse
    tgt.postprocess(self.output_target_map, self.src_dir, self.subdir, self.install_prefix, self.trace)
  File "/usr/lib/python3.11/site-packages/mesonbuild/cmake/interpreter.py", line 412, in postprocess
    self.includes = list(OrderedSet([rel_path(x, True, False) for x in OrderedSet(self.includes)] + [build_dir_rel]))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/cmake/interpreter.py", line 412, in <listcomp>
    self.includes = list(OrderedSet([rel_path(x, True, False) for x in OrderedSet(self.includes)] + [build_dir_rel]))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/cmake/interpreter.py", line 405, in rel_path
    return x.relative_to(Path(self.env.get_build_dir()) / subdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/home/gerion/src/infinitime-gllvm/build/subprojects/nrf5-sdk/nrf5_sdk_patched/components/drivers_nrf/nrf_soc_nosd' is not in the subpath of '/home/gerion/src/infinitime-gllvm/build/subprojects/InfiniTime' OR one path is relative and the other is absolute.

meson.build:43:19: ERROR: Unhandled python exception
```

**To Reproduce**
The whole project is rather big. I therefore tried to build a MWE. This, however, fails with another reason. I'm not sure why.
[Here is the MWE](https://github.com/gerion0/mesoncmake) in its current form.
The build with CMake directly works without problems.
Configuration with Meson works, but building does not:
```
$ ninja subprojects/app/app
[1/2] Compiling C object subprojects/app/app.p/app.c.o
FAILED: subprojects/app/app.p/app.c.o 
ccache cc -Isubprojects/app/app.p -Isubprojects/app -I../subprojects/app -Isubprojects/app/__CMake_build -I../subprojects/app/__CMake_build -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O0 -g -MD -MQ subprojects/app/app.p/app.c.o -MF subprojects/app/app.p/app.c.o.d -o subprojects/app/app.p/app.c.o -c ../subprojects/app/app.c
../subprojects/app/app.c:1:10: fatal error: sdk.h: No such file or directory
    1 | #include "sdk.h"
      |          ^~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
The include path is missing obviously (although specified in the CMakeLists.txt). Here are the compilation commands that CMake generates for comparison:
```
[1/3] /usr/bin/cc  -I/home/gerion/test/mesoncmake/subprojects/app/build/../../sdk  -MD -MT CMakeFiles/app.dir/app.c.o -MF CMakeFiles/app.dir/app.c.o.d -o CMakeFiles/app.dir/app.c.o -c /home/gerion/test/mesoncmake/subprojects/app/app.c
[2/3] /usr/bin/cc  -I/home/gerion/test/mesoncmake/subprojects/app/build/../../sdk  -MD -MT CMakeFiles/app.dir/home/gerion/test/mesoncmake/subprojects/sdk/sdk.c.o -MF CMakeFiles/app.dir/home/gerion/test/mesoncmake/subprojects/sdk/sdk.c.o.d -o CMakeFiles/app.dir/home/gerion/test/mesoncmake/subprojects/sdk/sdk.c.o -c /home/gerion/test/mesoncmake/subprojects/sdk/sdk.c
[3/3] : && /usr/bin/cc   CMakeFiles/app.dir/app.c.o CMakeFiles/app.dir/home/gerion/test/mesoncmake/subprojects/sdk/sdk.c.o -o app   && :
```

Is this something Meson should support?
I guess the above stack trace is a bug anyway. I looked into the Meson source code and the code that fails is:
```python
if path_is_in_root(x, Path(self.env.get_build_dir())) and is_header:
    return x.relative_to(Path(self.env.get_build_dir()) / subdir)
```
So, it seems that the condition checks that `x` is in the root build directory but not within the subproject's subdirectory.

And why Meson parses the includes within the InfiniTime subproject (and fails thereby) but not in my MWE? Both tell the includes with `include_directories` as far as I can say.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

No. While the project is compiled with an ARM toolchain, this has nothing to do with Meson's cross compilation support.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Gentoo Linux

* what Python version are you using e.g. 3.8.0

3.11

* what `meson --version`

1.2.2 (this also happens with Git HEAD)

* what `ninja --version` if it's a Ninja build

1.11.2

* what CMake version

3.26.5

**Comment by f2l2pe** [comment]
Just got this too

```
SDL_image| CMake configuration: SUCCEEDED
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 193, in run
  File "mesonbuild\msetup.py", line 365, in run
  File "mesonbuild\msetup.py", line 188, in generate
  File "mesonbuild\msetup.py", line 227, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 3069, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 169, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 194, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 186, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 204, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 641, in assignment
  File "mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 556, in method_call
  File "mesonbuild\interpreter\interpreterobjects.py", line 885, in method_call
  File "mesonbuild\interpreterbase\decorators.py", line 650, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 237, in wrapper
  File "mesonbuild\interpreterbase\decorators.py", line 556, in wrapper
  File "mesonbuild\modules\cmake.py", line 435, in subproject
  File "mesonbuild\interpreter\interpreter.py", line 943, in do_subproject
  File "mesonbuild\interpreter\interpreter.py", line 931, in do_subproject
  File "mesonbuild\interpreter\interpreter.py", line 1017, in _do_subproject_cmake
  File "mesonbuild\cmake\interpreter.py", line 949, in analyse
  File "mesonbuild\cmake\interpreter.py", line 425, in postprocess
  File "mesonbuild\cmake\interpreter.py", line 421, in non_optional
  File "mesonbuild\cmake\interpreter.py", line 425, in <genexpr>
  File "mesonbuild\cmake\interpreter.py", line 415, in rel_path
  File "pathlib.py", line 682, in relative_to
ValueError: 'E:\\GameDev\\Cpp\\Game1\\buildDir\\3rdparty\\SDL\\__CMake_build\\include-revision' is not in the subpath of 'E:\\GameDev\\Cpp\\Game1\\buildDir\\3rdparty\\SDL_image'

meson.build:36:23: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

Should be related, right?
