### ISSUE TITLE
`meson dist --include-subprojects` fails on an unpromoted subproject

### ISSUE THREAD

**Issue by bgilbert** [mesonbuild/meson#12489]
**Describe the bug**
When running `meson dist` on a project with a subproject (glib) which itself has a subproject (gvdb), `meson dist --include-subprojects` fails with a `FileNotFoundError` on the promoted sub-subproject directory.  Building the project first doesn't help.

glib tarballs include both `gvdb.wrap` and a `gvdb` directory, in case that makes a difference.  Meson automatically promotes `gvdb.wrap` but not `gvdb`.

**To Reproduce**
```bash
#!/bin/bash

set -ex

cd $(mktemp -d)

python3 -m venv env
env/bin/pip install meson
meson=$(pwd)/env/bin/meson

mkdir src
cd src
cat > meson.build <<EOF
project('test')
subproject('glib')
EOF
mkdir subprojects
$meson wrap install glib

git init
git add meson.build subprojects/glib.wrap
git commit -m initial

$meson setup build
cd build
$meson dist --include-subprojects --no-tests
```

This produces:

```console
[...]
+ /tmp/tmp.o6S4xT3ZeL/env/bin/meson dist --include-subprojects --no-tests
Traceback (most recent call last):
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/mdist.py", line 371, in run
    names = project.create_dist(archives)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/mdist.py", line 209, in create_dist
    if is_git(sub_src_root):
       ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/mdist.py", line 88, in is_git
    return quiet_git(['ls-files', '--error-unmatch', 'meson.build'], src_root)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/utils/universal.py", line 210, in quiet_git
    p, o, e = git(cmd, workingdir, check)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/utils/universal.py", line 199, in git
    p, o, e = Popen_safe(cmd, cwd=workingdir, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.o6S4xT3ZeL/env/lib64/python3.11/site-packages/mesonbuild/utils/universal.py", line 1485, in Popen_safe
    p = subprocess.Popen(args, universal_newlines=True, encoding=encoding, close_fds=False,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp.o6S4xT3ZeL/src/subprojects/gvdb'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
```

**Expected behavior**
Meson produces a dist tarball.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Fedora 38
* what Python version are you using e.g. 3.8.0
3.11.6
* what `meson --version`
1.2.3
* what `ninja --version` if it's a Ninja build
1.11.1

**Comment by derekerdmannsonos** [comment]
For anyone else who hits this, one workaround is manually promoting the extracted subproject before running `meson dist`. The reproducer succeeds with this additional line above `cd build`:
```sh
$meson wrap promote subprojects/glib-2.80.3/subprojects/gvdb
```

**Comment by fatih-asici** [comment]
A sample project to reproduce this bug is also here: https://github.com/fatih-asici/meson-bug

**Comment by andy5995** [comment]
I'm running into this as well, after using `git clean`.

```
dealers-choice 0.0.13

  Subprojects
    canfigger  : YES
    deckhandler: YES
    miniaudio  : YES
    pcg        : YES (from deckhandler)
    pokeval    : YES
```

The pcg subproject is found in another subproject (correct) during the top-level meson setup, but I get an error similar to what OP posted when using `meson --include-subprojects`.

@derekerdmannsonos said:

>$meson wrap promote subprojects/glib-2.80.3/subprojects/gvdb

I couldn't remember what I did originally to put the subproject there!

Thanks!

Oh.. I should mention, the build and tests have been working even without the subproject being "promoted" (not existing at the top-level subprojects directory). I only have an error when running `meson dist --include-subprojects`.

**Comment by andy5995** [comment]
I tried adding a simple wrap in the deckhandler subprojects directory, alongside the `pcg` directory:

pcg.wrap

```
[wrap-file]

[provide]
pcg = pcg_dep
```

Then after running `meson setup...` at the top-level, a top-level subprojects/pcg.wrap file appeared.

```
[wrap-redirect]
filename = deckhandler/subprojects/pcg.wrap
```

But I get the same result when trying to include subprojects. And when using `meson subprojects update --reset` the wrap file in subprojects/deckhandler/subprojects was deleted.
