### ISSUE TITLE
 This is a Meson bug and should be reported on extract_objects()

### ISSUE THREAD

**Issue by vbextreme** [mesonbuild/meson#12519]
**Describe the bug**
Try to extract object from multiple libs to create single static lib

meson.build
```
project('sdk', 'c', version: '0.0.0')
localPath = meson.current_source_dir()
cc = meson.get_compiler('c')
libs = meson.get_external_property('NOLIBS')
libpath = meson.get_external_property('NOLIBPATH')
lobjects = []
foreach l: libs
  lib = cc.find_library(l, dirs: libpath, static: true, required: true)
  lobjects += [ lib.extract_objects() ]
endforeach

static_library(meson.project_name(), objects: lobjects)
```

meson report
```
Traceback (most recent call last):                                                                                                                                       
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run                                                                                     
    return options.run_func(options)                                                                                                                                     
           ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                     
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run                                                                                        
    app.generate()                                                                                                                                                       
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 183, in generate                                                                                   
    return self._generate(env, capture, vslite_ctx)                                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 228, in _generate                                                                                  
    intr.run()                                                                                                                                                           
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 3002, in run                                                                      
    super().run()                                                                                                                                                        
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 164, in run                                                               
    self.evaluate_codeblock(self.ast, start=1)                                                                                                                           
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock                                                
    raise e                                                                                                                                                              
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock                                                
    self.evaluate_statement(cur)                                                                                                                                         
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 228, in evaluate_statement                                                
    self.evaluate_foreach(cur)                                                                                                                                           
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 472, in evaluate_foreach                                                  
    self.evaluate_codeblock(node.block)                                                                                                                                  
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock                                                
    raise e                                                                                                                                                              
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 182, in evaluate_codeblock                                                
    self.evaluate_statement(cur)                                                                                                                                         
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 230, in evaluate_statement                                                
    self.evaluate_plusassign(cur)                                                                                                                                        
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 481, in evaluate_plusassign                                               
    addition = self.evaluate_statement(node.value)                                                                                                                       
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                       
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 212, in evaluate_statement                                                
    return self.evaluate_arraystatement(cur)                                                                                                                             
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 251, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 593, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 593, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 546, in method_call
    self.validate_extraction(obj.held_object)
  File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 3330, in validate_extraction
    if self.subproject != buildtarget.subproject:
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExternalLibrary' object has no attribute 'subproject'

meson.build:22:20: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**system parameters**
* cross build
* arch linux
* Python v3.11.5
* meson v1.2.3
* ninja v1.11.1

**Comment by xclaesse** [comment]
You cannot extract objects from an external library, that method is supposed to be allowed only on Meson targets, sush as static_library(). It is however a Meson bug that it crash rather than having a good error message.

**Comment by vbextreme** [comment]
All libs are statics, extract_objects() not works same 
```ar x lib.a```
?
Do I have another working way to merge multiple static libraries into one?

**Comment by eli-schwartz** [comment]
This is just #9218 I think.

**Comment by xclaesse** [comment]
Fixed the crash in https://github.com/mesonbuild/meson/pull/12521. As @eli-schwartz said, what you want is WIP new feature sadly. I guess you can run "ar x" in a custom_target(), at least if you don't care building on e.g. Windows.

**Comment by vbextreme** [comment]
I don't have enough expertise with Meson to understand how to use custom_target. I would need a target that is called multiple times for each input file, so I would have an array of inputs that need to be invoked in custom_target. The only thing I understand is that I can't directly pass the array because it will be expanded in the same command line.

I also don't know how to invoke custom_target without the output parameter; I don't know in advance which files will be generated. I haven't even figured out whether the command called in custom_target will be the default one or the one passed by [binaries] in the cross file.

Given:
```
lib = [bar.a, foo.a]
```
I wouldn't know how to achieve:
```
$ mkdir bar && cd bar && ./sdk/esp/bin/xtensa-ar -x bar.a && cd ..
$ mkdir foo && cd foo && $ ./sdk/esp/bin/xtensa-ar ar -x foo.a && cd ..
$ ./sdk/esp/bin/xtensa-ar ar -qc libsdk.a bar foo
```

I would be able to create it only for ar -qc.
