### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: build.ninja~

### ISSUE THREAD

**Issue by isdrk** [mesonbuild/meson#12511]
**Describe the bug**
```
[2023-11-15T14:36:23.776Z] Traceback (most recent call last):
[2023-11-15T14:36:23.776Z]   File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
[2023-11-15T14:36:23.776Z]     return options.run_func(options)
[2023-11-15T14:36:23.776Z]   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 358, in run
[2023-11-15T14:36:23.776Z]     app.generate()
[2023-11-15T14:36:23.776Z]   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 183, in generate
[2023-11-15T14:36:23.776Z]     return self._generate(env, capture, vslite_ctx)
[2023-11-15T14:36:23.776Z]   File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 253, in _generate
[2023-11-15T14:36:23.776Z]     captured_compile_args = intr.backend.generate(capture, vslite_ctx)
[2023-11-15T14:36:23.776Z]   File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 660, in generate
[2023-11-15T14:36:23.776Z]     os.replace(tempfilename, outfilename)
[2023-11-15T14:36:23.776Z] FileNotFoundError: [Errno 2] No such file or directory: '/home/build_tests/build.ninja~' -> '/home/build_tests/build.ninja'
```

This issue is random. 
It happened when I ran "meson" in parallel.
```
      meson setup build
      meson compile -C build --jobs 4
      
      meson setup -D enable-unit-tests=true build_tests
      meson test --suite CoreTestSanity -C build_tests --verbose --num-processes 4
      
      meson setup -Db_sanitize=address,undefined build_asan
      meson compile -C build_asan --jobs 4
```

After a debugging I found that file _build_tests/build.ninja~_ was missed after 
this code 
```python
            for t in ProgressBar(self.build.get_targets().values(), desc='Generating targets'):
                self.generate_target(t)
```
https://github.com/mesonbuild/meson/blob/1.2.3/mesonbuild/backend/ninjabackend.py#L631C20-L632C40

**system parameters**
ARM64
Kernel Linux 31867b4c143c 5.15.0-72-generic #79-Ubuntu SMP Tue Apr 18 16:53:43 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
Ubuntu 22.04.3 LTS (Jammy Jellyfish)
meson --version
1.2.3
ninja --version
1.11.1
python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux

**Comment by isdrk** [comment]
Looks like " meson setup " in parallel can't work. It uses a git to download files to subprojects and it fails.
