### ISSUE TITLE
rust.bindgen fails in subprojects

### ISSUE THREAD

**Issue by notpeelz** [mesonbuild/meson#12526]
**Describe the bug**
I get this error when I use `rust.bindgen()` from within a subproject:
```
subprojects/foo/meson.build:14:17: ERROR: Tried to get unknown builtin option foo:c_args
```

**To Reproduce**
```sh
git clone https://github.com/notpeelz/bug-repro-meson-subproject-bindgen
cd bug-repro-meson-subproject-bindgen
meson setup build
meson compile -C build
```

This doesn't reproduce on meson 1.2.3. I believe this bug was introduced by #12283

**system parameters**
* native build (not cross-building)
* Arch Linux (x86-64)
* `python --version`: 3.11.5
* `meson --version`: 1.3.0.rc3
* `ninja --version`: 1.11.1

**Comment by fvalette** [comment]
Hi,
I've got the exact same issue, the following fixes the issue but i am not sure it's the correct answer.
E.g setting from top level project `-D<subproject>:c_args="whatever"` does not have any effect w/ meson 1.3.0 ! Is this the expected behavior ? 

```diff
--- a/mesonbuild/modules/rust.py
+++ b/mesonbuild/modules/rust.py
@@ -241,7 +241,7 @@ class RustModule(ExtensionModule):
                     depends.append(s)
 
         # We only want include directories and defines, other things may not be valid
-        cargs = state.get_option('args', state.subproject, lang='c')
+        cargs = state.get_option('args', lang='c')
         assert isinstance(cargs, list), 'for mypy'
         for a in itertools.chain(state.global_args.get('c', []), state.project_args.get('c', []), cargs):
             if a.startswith(('-I', '/I', '-D', '/D', '-U', '/U')):
```

**Comment by Marc-Pierre-Barbier** [comment]
can confirm the issue still exist (meson 1.3.2)

**Comment by ndufresne** [comment]
I just hit that issue when trying to build mesa as a subproject, meson 1.4.1

**Comment by bonzini** [comment]
Might be fixed by the option refactoring

**Comment by ndufresne** [comment]
Which version ? or is that in main ? I can certainly test again this week to confirm.

**Comment by eli-schwartz** [comment]
It is not yet merged -- see https://github.com/mesonbuild/meson/pull/13441

**Comment by bonzini** [comment]
Merged now. Can you check if it works?

**Comment by ndufresne** [comment]
Wanted to test, but some other regression got in the way:
```
Traceback (most recent call last):
  File "/home/nicolas/Sources/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/msetup.py", line 407, in run
    app.generate()
    ~~~~~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/msetup.py", line 189, in generate
    return self._generate(env, capture, vslite_ctx)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/msetup.py", line 266, in _generate
    intr.run()
    ~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 3061, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 873, in func_subproject
    return self.do_subproject(args[0], kw)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 963, in do_subproject
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 951, in do_subproject
    return methods_map[method](subp_name, subdir, default_options, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 1001, in _do_subproject_meson
    subi.run()
    ~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 3061, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 240, in evaluate_statement
    self.evaluate_foreach(cur)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 478, in evaluate_foreach
    self.evaluate_codeblock(node.block)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 218, in evaluate_statement
    return self.evaluate_if(cur)
           ~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 308, in evaluate_if
    self.evaluate_codeblock(i.block)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    self.assignment(cur)
    ~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 641, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 873, in func_subproject
    return self.do_subproject(args[0], kw)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 963, in do_subproject
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 951, in do_subproject
    return methods_map[method](subp_name, subdir, default_options, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 1001, in _do_subproject_meson
    subi.run()
    ~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 3061, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    self.assignment(cur)
    ~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 641, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreterbase/decorators.py", line 62, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/nicolas/Sources/meson/mesonbuild/interpreter/interpreter.py", line 1083, in func_get_option
    value_object, value = self.coredata.optstore.get_option_from_meson_file(options.OptionKey(optname, self.subproject))
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/options.py", line 1101, in get_option_from_meson_file
    (value_object, value) = self.get_value_object_and_value_for(key)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nicolas/Sources/meson/mesonbuild/options.py", line 832, in get_value_object_and_value_for
    vobject = self.get_value_object_for(key)
  File "/home/nicolas/Sources/meson/mesonbuild/options.py", line 813, in get_value_object_for
    parent_option = self.options[parent_key]
                    ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: OptionKey('glib_debug', '', <MachineChoice.HOST: 1>)

subprojects/gstreamer-full/subprojects/gstreamer/meson.build:112:13: ERROR: Unhandled python exception
```

I was trying to get a single build for Weston, Mesa and GStreamer here https://gitlab.collabora.com/nicolas/mesa-weston-gst-build .

**Comment by ndufresne** [comment]
[Someone](https://github.com/mesonbuild/meson/pull/13441#issuecomment-2661154499) told me to open a new issue if there was a problem with the refactoring. Is this really what you want? The change just made it crash differently, opening a duplicate issue seems odd reaction, I was simply cross-referencing it.

**Comment by bonzini** [comment]
Can you test again with latest master?

**Comment by ndufresne** [comment]
Sure, but I might only be able to do so Monday.

**Comment by ndufresne** [comment]
Worked for me.
