### ISSUE TITLE
Crashing while quitting `meson configure` in MSYS2 console

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#12541]
**Describe the bug**

After setting up the build directory and cd'ing into it, running `meson configure` results in a hard crash with a python exception message:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:/MSYS2/mingw64/bin/meson.exe/__main__.py", line 7, in <module>
  File "C:/MSYS2/mingw64/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/MSYS2/mingw64/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 285, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/MSYS2/mingw64/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 204, in run
    mlog.shutdown()
  File "C:/MSYS2/mingw64/lib/python3.11/site-packages/mesonbuild/mlog.py", line 147, in shutdown
    self.stop_pager()
  File "C:/MSYS2/mingw64/lib/python3.11/site-packages/mesonbuild/mlog.py", line 191, in stop_pager
    self.log_pager.stdin.flush()
OSError: [Errno 22] Invalid argument
```

**To Reproduce**

Inside a MSYS2 console, a small project directory has to be set up.

`meson.build`:
```
project('crash')
subproject('tl-expected')
```

Also install the subproject 'tl-expected':
```
mkdir subprojects
meson install tl-expected
```

Then run:
```
meson setup build
cd build
meson configure
```

Immediately close the paging display by pressing `q`.

**Expected behavior**

This should crash. :)

**system parameters**
* native build
* Windows 10 Pro, inside a MSYS2 console
* Python: 3.11.6
* Meson: 1.3.0
* Ninja: 1.11.1

**Comment by xclaesse** [comment]
I cannot reproduce, at least with python 3.10 that I've got. Meson expects `BrokenPipeError` exception if `less` exits before we flush/close the file descriptor. You seems to get `OSError` which would make sense to catch as well.

**Comment by xclaesse** [comment]
@punytroll Could you please give a try to https://github.com/mesonbuild/meson/pull/12542?

**Comment by punytroll** [comment]
> @punytroll Could you please give a try to #12542?

That seems to suppress the exception nicely and doesn't seem to give rise to new problems for me.
