### ISSUE TITLE
AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_editable', meson.build:1:0: ERROR: Unable to detect linker for compiler `gfortran -Wl,--version`

### ISSUE THREAD

**Issue by pavelkomarov** [mesonbuild/meson#12569]
I'm trying to install a package called Clawpack from source, which depends on meson-python, and I keep running in to meson issues that halt the install.

I'm on macOS 13.5.2, using Python 3.9.6. I pip installed meson-python v1.3.0. I've installed gcc with `brew`, so I have `gfortran` 13.2.0, and it is symlinked in my local user bin, so it's on my path, and the terminal can find it.

If I `python3 -m pip install clawpack`, I see

```
Collecting clawpack
  Using cached clawpack-5.9.2.tar.gz (5.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      + meson setup /private/var/folders/y4/mzkq6j112wl7fg1gqfkgrdmr0000gn/T/pip-install-pcyyji2n/clawpack_525ae82d86044ef3b9e989a60061f637 /private/var/folders/y4/mzkq6j112wl7fg1gqfkgrdmr0000gn/T/pip-install-pcyyji2n/clawpack_525ae82d86044ef3b9e989a60061f637/.mesonpy-z9fzd7yf -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/y4/mzkq6j112wl7fg1gqfkgrdmr0000gn/T/pip-install-pcyyji2n/clawpack_525ae82d86044ef3b9e989a60061f637/.mesonpy-z9fzd7yf/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.0
      Source dir: /private/var/folders/y4/mzkq6j112wl7fg1gqfkgrdmr0000gn/T/pip-install-pcyyji2n/clawpack_525ae82d86044ef3b9e989a60061f637
      Build dir: /private/var/folders/y4/mzkq6j112wl7fg1gqfkgrdmr0000gn/T/pip-install-pcyyji2n/clawpack_525ae82d86044ef3b9e989a60061f637/.mesonpy-z9fzd7yf
      Build type: native build
      Program python3 found: YES (/usr/bin/python3)
      Project name: clawpack
      Project version: 5.9.2
      
      ../meson.build:1:0: ERROR: Unable to detect linker for compiler `gfortran -Wl,--version`
      stdout:
      stderr: collect2 version 13.2.0
      /usr/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/ -dynamic -arch x86_64 -platform_version macos 13.0.0 0.0 -o a.out -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13 -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc -L/usr/local/lib -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13/../../.. --version -lemutls_w -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin22/13 -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc -rpath /usr/local/lib -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current
      ld: unknown options: --version
      collect2: error: ld returned 1 exit status
```

If I take a more circuitous approach and try to install clawpack from source with 

```
cd /Users/pavel/code
git clone https://github.com/clawpack/clawpack.git 
cd clawpack
git clone --recursive https://github.com/clawpack/apps
git checkout v5.9.2  
git submodule init
git submodule update
python3 -m pip install --no-build-isolation -e .
```

then I get

```
Obtaining file:///Users/pavel/Code/clawpack
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 167, in prepare_metadata_for_build_editable
          hook = backend.prepare_metadata_for_build_editable
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_editable'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 176, in prepare_metadata_for_build_editable
          whl_basename = build_hook(metadata_directory, config_settings)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 985, in wrapper
          return func(*args, **kwargs)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 1060, in build_editable
          with _project(config_settings) as project:
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 912, in _project
          yield Project(source_dir, build_dir, meson_args, editable_verbose)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 635, in __init__
          self._meson = _get_meson_command(pyproject_config.get('meson'))
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 947, in _get_meson_command
          meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'meson'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Any ideas?

**Comment by pavelkomarov** [comment]
The result of `clawpack % gfortran -Wl,--version`

is
```
collect2 version 13.2.0
/usr/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/ -dynamic -arch x86_64 -platform_version macos 13.0.0 0.0 -o a.out -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13 -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13/../../.. --version -lemutls_w -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin22/13 -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current
ld: unknown options: --version 
collect2: error: ld returned 1 exit status`
```

But if I replace `--version` with `-v`: `gfortran -Wl,-v`

```
collect2 version 13.2.0
/usr/bin/ld -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/ -dynamic -arch x86_64 -platform_version macos 13.0.0 0.0 -o a.out -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13 -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc -L/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13/../../.. -v -lemutls_w -lgcc -lSystem -no_compact_unwind -rpath @loader_path -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin22/13 -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc -rpath /usr/local/Cellar/gcc/13.2.0/lib/gcc/current
@(#)PROGRAM:ld  PROJECT:dyld-1015.7
BUILD 18:48:43 Aug 22 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.0.12.3)
Library search paths:
	/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13
	/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc
	/usr/local/Cellar/gcc/13.2.0/bin/../lib/gcc/current/gcc/x86_64-apple-darwin22/13/../../..
Framework search paths:
```

I at least no longer get an error exit code.

**Comment by conorsleithsonos** [comment]
I hit this same issue installing scipy. I was able to work around this by `pip install git+https://github.com/mesonbuild/meson.git@master`. Looks like it's a meson bug

**Comment by pavelkomarov** [comment]
I tried installing meson from source a couple weeks ago, and it didn't solve my issue, but I can try again.

**Comment by conorsleithsonos** [comment]
Be sure to use --no-build-isolation, otherwise pip downloads and uses its own version of meson

**Comment by pavelkomarov** [comment]
Now it can't find meson in that other install. Why does it install as `meson` when I install your way, but as `meson-python` when I install the released package? Why the name change?

**Comment by conorsleithsonos** [comment]
Yeah, meson-python is the python build backend built on top of meson. What I did was install meson@master via github and meson-python through pip/pypi, and that worked

**Comment by pavelkomarov** [comment]
Okay, so I've installed both just in case. From a pip freeze:

```
meson @ git+https://github.com/mesonbuild/meson.git@e991c4d45460c09e5eaee6cb1041edb95d1e990e
meson-python @ git+https://github.com/mesonbuild/meson-python.git@9d0fa1336fe18ffcd258b31c327ff3c5a020532e
```

Then I try `python3 -m pip install --no-build-isolation clawpack `, and I get some kind of new error:

```
× Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 1019, in wrapper
          return func(*args, **kwargs)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 1072, in build_wheel
          with _project(config_settings) as project:
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 946, in _project
          yield Project(source_dir, build_dir, meson_args, editable_verbose)
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 661, in __init__
          self._meson = _get_meson_command(pyproject_config.get('meson'))
        File "/Users/pavel/Library/Python/3.9/lib/python/site-packages/mesonpy/__init__.py", line 981, in _get_meson_command
          meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'meson'
      [end of output]
```

**Comment by conorsleithsonos** [comment]
It looks like the meson executable was installed somewhere not in your PATH. Maybe in `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/`? At any rate, if you find that executable, add it to PATH or symlink it somewhere that's in PATH and you should be good to go

**Comment by pavelkomarov** [comment]
Hmm, it's not in `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/`. Where else could the meson pip install be putting it?

**Comment by pavelkomarov** [comment]
Oh! Uninstalling and reinstalling I notice this:

```
Installing collected packages: meson
  WARNING: The script meson is installed in '/Users/pavel/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Standby. I'm trying again.

**Comment by pavelkomarov** [comment]
Okay, `ln -s /Users/pavel/Library/Python/3.9/bin/meson /usr/local/bin/meson`, then `python3 -m install --no-build-isolation clawpack` yields a new error. Progress.

```
error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      
      ('\x1b[31m',)meson-python: error: Could not find ninja version 1.8.2 or newer.
      [end of output]
```

I thought ninja would be installed as a dependency automagically, but I'll try manually.

**Comment by pavelkomarov** [comment]
```
python3 -m pip install --no-build-isolation clawpack                
Defaulting to user installation because normal site-packages is not writeable
Collecting clawpack
  Using cached clawpack-5.9.2.tar.gz (5.8 MB)
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: clawpack
  Building wheel for clawpack (pyproject.toml) ... done
  Created wheel for clawpack: filename=clawpack-5.9.2-cp39-cp39-macosx_13_0_x86_64.whl size=2162949 sha256=341605d40cf3e8ccf12b79ad685359e0aef589f0e86546d7b2f945f85d9d860e
  Stored in directory: /Users/pavel/Library/Caches/pip/wheels/e6/3c/e6/9a8b2615b92e93cf2df2188630b1e6bc5b90218e890e52a633
Successfully built clawpack
Installing collected packages: clawpack
Successfully installed clawpack-5.9.2
```

Okay, that worked! Thanks for your help!
