### ISSUE TITLE
installation of pandas in pycharm error: This is a Meson bug and should be reported!

### ISSUE THREAD

**Issue by Orfeas-Karras** [mesonbuild/meson#12687]
**Describe the bug**
i am trying to install pandas in pycharm and i get the following error that says " This is a Meson bug and should be reported!"

The whole error output:

(.venv) PS C:\Users\karras\PycharmProjects\ss7Decoder> pip install pandas
Collecting pandas
  Using cached pandas-2.1.4.tar.gz (4.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [48 lines of output]
      + meson setup C:\Users\karras\AppData\Local\Temp\pip-install-0708ru_5\pandas_74da2640c4a2447a875615ae7dd675bf C:\Users\karras\AppData\Local\Temp\pip-install-0708ru_5\pandas_74da2640c4a2447a875615ae7dd675bf\.mesonpy-tqup_40y\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-
file=C:\Users\karras\AppData\Local\Temp\pip-install-0708ru_5\pandas_74da2640c4a2447a875615ae7dd675bf\.mesonpy-tqup_40y\build\meson-python-native-file.ini
      Traceback (most recent call last):
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\msetup.py", line 205, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 330, in __init__
          self.parse_project()
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 134, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1308, in func_project
          mesonlib.setup_vsenv(force_vsenv)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\utils\vsenv.py", line 118, in setup_vsenv
          return _setup_vsenv(force)
        File "C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1\overlay\Lib\site-packages\mesonbuild\utils\vsenv.py", line 57, in _setup_vsenv
          bat_json = subprocess.check_output(
        File "C:\Users\karras\AppData\Local\Programs\Python\Python310-32\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\karras\AppData\Local\Programs\Python\Python310-32\lib\subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe', '-latest', '-prerelease', '-requiresAny', '-requires', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', '-requires', 'Microsoft.VisualStudio.Workload.WDExpress', '-products', '*', '
-utf8', '-format', 'json']' returned non-zero exit status 87.
      The Meson build system
      Version: 1.2.1
      Source dir: C:\Users\karras\AppData\Local\Temp\pip-install-0708ru_5\pandas_74da2640c4a2447a875615ae7dd675bf
      Build dir: C:\Users\karras\AppData\Local\Temp\pip-install-0708ru_5\pandas_74da2640c4a2447a875615ae7dd675bf\.mesonpy-tqup_40y\build
      Build type: native build
      Project name: pandas
      Project version: 2.1.4

      ..\..\meson.build:2:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\karras\AppData\Local\Temp\pip-build-env-8m74r6n1'.
You can safely remove it manually.
 

**Expected behavior**
install pandas successfully

**system parameters**
*plain native build
* windows 10
* Python 3.10.3
* meson 1.3.1

**Comment by eli-schwartz** [comment]
```
subprocess.CalledProcessError: Command '[
    'C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe', '-latest',
    '-prerelease', '-requiresAny', '-requires', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
    '-requires', 'Microsoft.VisualStudio.Workload.WDExpress', '-products', '*', '-utf8', '-format', 'json'
    ]' returned non-zero exit status 87.
```

That's interesting, apparently vswhere exists but returns an error. Does running vswhere manually, work?

**Comment by Orf820** [comment]
![image](https://github.com/mesonbuild/meson/assets/33357128/3d4078b5-6988-4326-9c5a-d4c44c8a70d3)

i guess this is what you are asking, (i am not familiar with this kind of problems)  it seems it does not recognize the parameters "requiresAny"  and "utf8". When i run it without them it returns [ ].

**Comment by eli-schwartz** [comment]
Your vswhere.exe is from 2017, so it definitely needs to be updated.

This is still a meson bug -- we should handle an outdated vswhere.exe more gracefully.

**Comment by Orf820** [comment]
indeed the error disappeared after updating the whole Microsoft VS, but i got a new error:  ..\..\meson.build:2:0: ERROR: Could not parse vswhere.exe output

Then i choose specific version of panda (2.0.3) and i finally installed it successfully without errors

**Comment by AReshma** [comment]
> indeed the error disappeared after updating the whole Microsoft VS, but i got a new error: ....\meson.build:2:0: ERROR: Could not parse vswhere.exe output
> 
> Then i choose specific version of panda (2.0.3) and i finally installed it successfully without errors

[+] 1

same with python 3.11. All pandas versions above 2.0.3 failed with error :

_..\..\meson.build:2:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe_

**Comment by michalmainc** [comment]
I'm trying install pandas at Rpi since yesterday but I failed with latest version. I will try with another version.

```
(trzy) rpi@pv:~ $ pip install pandas
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pandas
  Downloading pandas-2.2.0.tar.gz (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 4.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      + meson setup /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a                                                                                                                                                                /.mesonpy-6111guq1/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b0                                                                                                                                                                95a60356d4bb607a/.mesonpy-6111guq1/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a
      Build dir: /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/.mesonpy-6111guq1/build
      Build type: native build
      Project name: pandas
      Project version: 2.2.0
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Cython compiler for the host machine: cython (cython 3.0.5)
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Program python found: YES (/home/rpi/Documents/Python/trzy/bin/python3.12)
      Found pkg-config: /usr/bin/pkg-config (0.29.2)
      Run-time dependency python found: YES 3.12
      Build targets in project: 53

      pandas 2.2.0

        User defined options
          Native files: /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/.mesonpy-6111guq1/build/meson-python-native-file.ini
          buildtype   : release
          vsenv       : True
          b_ndebug    : if-release
          b_vscrt     : md

      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-sus_aphj/normal/bin/ninja

      Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
      /tmp/pip-build-env-sus_aphj/overlay/bin/meson compile -C .
      + /tmp/pip-build-env-sus_aphj/normal/bin/ninja
      [1/151] Generating pandas/_libs/algos_common_helper_pxi with a custom command
      [2/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command
      [3/151] Generating pandas/_libs/hashtable_func_helper_pxi with a custom command
      [4/151] Generating pandas/_libs/algos_take_helper_pxi with a custom command
      [5/151] Generating pandas/__init__.py with a custom command
      [6/151] Generating pandas/_libs/index_class_helper_pxi with a custom command
      [7/151] Generating pandas/_libs/hashtable_class_helper_pxi with a custom command
      [8/151] Generating pandas/_libs/intervaltree_helper_pxi with a custom command
      [9/151] Generating pandas/_libs/sparse_op_helper_pxi with a custom command
      [10/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/base.pyx
      [11/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/ccalendar.pyx
      [12/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/nattype.pyx
      warning: /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/nattype.pyx:79:0: Global name __nat_unpickle match                                                                                                                                                                ed from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      warning: /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/nattype.pyx:79:0: Global name __nat_unpickle match                                                                                                                                                                ed from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
      [13/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/dtypes.pyx
      [14/151] Compiling C object pandas/_libs/tslibs/base.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_base.pyx.c.o
      [15/151] Linking target pandas/_libs/tslibs/base.cpython-312-arm-linux-gnueabihf.so
      [16/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/fields.pyx
      [17/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/conversion.pyx
      [18/151] Compiling C object pandas/_libs/tslibs/ccalendar.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_ccalendar.pyx.                                                                                                                                                                c.o
      [19/151] Linking target pandas/_libs/tslibs/ccalendar.cpython-312-arm-linux-gnueabihf.so
      [20/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/np_datetime.pyx
      [21/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/offsets.pyx
      [22/151] Compiling C object pandas/_libs/tslibs/np_datetime.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_np_datetime.                                                                                                                                                                pyx.c.o
      [23/151] Linking target pandas/_libs/tslibs/np_datetime.cpython-312-arm-linux-gnueabihf.so
      [24/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/parsing.pyx
      [25/151] Compiling C object pandas/_libs/tslibs/nattype.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_nattype.pyx.c.o
      [26/151] Linking target pandas/_libs/tslibs/nattype.cpython-312-arm-linux-gnueabihf.so
      [27/151] Compiling C object pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p/.._src_parser_tokenizer.c.o
      [28/151] Compiling C object pandas/_libs/tslibs/conversion.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_conversion.py                                                                                                                                                                x.c.o
      [29/151] Linking target pandas/_libs/tslibs/conversion.cpython-312-arm-linux-gnueabihf.so
      [30/151] Compiling C object pandas/_libs/tslibs/dtypes.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_dtypes.pyx.c.o
      [31/151] Linking target pandas/_libs/tslibs/dtypes.cpython-312-arm-linux-gnueabihf.so
      [32/151] Compiling C object pandas/_libs/tslibs/fields.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_fields.pyx.c.o
      [33/151] Linking target pandas/_libs/tslibs/fields.cpython-312-arm-linux-gnueabihf.so
      [34/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/period.pyx
      [35/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/strptime.pyx
      [36/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/timestamps.pyx
      [37/151] Compiling Cython source /tmp/pip-install-imyle0jd/pandas_e62198e3c33d44b095a60356d4bb607a/pandas/_libs/tslibs/timedeltas.pyx
      [38/151] Compiling C object pandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.o
      FAILED: pandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.o
      cc -Ipandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnueabihf.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-e                                                                                                                                                                nv-sus_aphj/overlay/lib/python3.12/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.12 -fvisibility=hidden -f                                                                                                                                                                diagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c11 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD                                                                                                                                                                 -MQ pandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.o -MF pandas/_libs/tslibs/offset                                                                                                                                                                s.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.o.d -o pandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnuea                                                                                                                                                                bihf.so.p/meson-generated_pandas__libs_tslibs_offsets.pyx.c.o -c pandas/_libs/tslibs/offsets.cpython-312-arm-linux-gnueabihf.so.p/pandas/_libs/tslibs/o                                                                                                                                                                ffsets.pyx.c
      cc: fatal error: Killed signal terminated program cc1
      compilation terminated.
      [39/151] Compiling C object pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.o
      FAILED: pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.o
      cc -Ipandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-e                                                                                                                                                                nv-sus_aphj/overlay/lib/python3.12/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.12 -fvisibility=hidden -f                                                                                                                                                                diagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c11 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD                                                                                                                                                                 -MQ pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.o -MF pandas/_libs/tslibs/parsin                                                                                                                                                                g.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.o.d -o pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnuea                                                                                                                                                                bihf.so.p/meson-generated_pandas__libs_tslibs_parsing.pyx.c.o -c pandas/_libs/tslibs/parsing.cpython-312-arm-linux-gnueabihf.so.p/pandas/_libs/tslibs/p                                                                                                                                                                arsing.pyx.c
      cc: fatal error: Killed signal terminated program cc1
      compilation terminated.
      [40/151] Compiling C object pandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_period.pyx.c.o
      FAILED: pandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_period.pyx.c.o
      cc -Ipandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.so.p -Ipandas/_libs/tslibs -I../../pandas/_libs/tslibs -I../../../../pip-build-en                                                                                                                                                                v-sus_aphj/overlay/lib/python3.12/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.12 -fvisibility=hidden -fd                                                                                                                                                                iagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -w -std=c11 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -                                                                                                                                                                MQ pandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_period.pyx.c.o -MF pandas/_libs/tslibs/period.cp                                                                                                                                                                ython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_period.pyx.c.o.d -o pandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.s                                                                                                                                                                o.p/meson-generated_pandas__libs_tslibs_period.pyx.c.o -c pandas/_libs/tslibs/period.cpython-312-arm-linux-gnueabihf.so.p/pandas/_libs/tslibs/period.py                                                                                                                                                                x.c
      cc: fatal error: Killed signal terminated program cc1
      compilation terminated.
      [41/151] Compiling C object pandas/_libs/tslibs/strptime.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_strptime.pyx.c.                                                                                                                                                                o
      [42/151] Compiling C object pandas/_libs/tslibs/timestamps.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_timestamps.py                                                                                                                                                                x.c.o
      [43/151] Compiling C object pandas/_libs/tslibs/timedeltas.cpython-312-arm-linux-gnueabihf.so.p/meson-generated_pandas__libs_tslibs_timedeltas.py                                                                                                                                                                x.c.o
      ninja: build stopped: subcommand failed.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
(trzy) rpi@pv:~ $ pip list
Package      Version
------------ -------
fastcrc      0.3.0
meson        1.3.1
pillow       10.2.0
pip          23.3.2
pymodbus     3.5.4
PyMySQL      1.1.0
pyserial     3.5
ttkbootstrap 1.10.1
(trzy) rpi@pv:~ $ python -V
```

**Comment by GearUnclear** [comment]
I cannot install VS2022 on all my users pc's.

> priyapandey26

**Comment by HydrogenDeuterium** [comment]
same error in my py3.9
