### ISSUE TITLE
meson error generate coverage report.

### ISSUE THREAD

**Issue by jianhe-fun** [mesonbuild/meson#12695]
meson version 1.3.1    
ninja version 1.10.1   
ubuntu 22. 

meson remeber the coverage report instruction, that means remove files will make coverage report generate error. now meson cannot on errror continue.

```
genhtml: ERROR: cannot read /home/jian/Desktop/pg_src/src6/postgres/contrib/bench_hash/bench_hash.c
Processing file contrib/bench_hash/bench_hash.c
Traceback (most recent call last):
  File "/home/jian/.local/bin/meson", line 8, in <module>
    sys.exit(main())
  File "/home/jian/.local/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
  File "/home/jian/.local/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 282, in run
    return run_script_command(args[1], args[2:])
  File "/home/jian/.local/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 223, in run_script_command
    return module.run(script_args)
  File "/home/jian/.local/lib/python3.10/site-packages/mesonbuild/scripts/coverage.py", line 206, in run
    return coverage(options.outputs, options.source_root,
  File "/home/jian/.local/lib/python3.10/site-packages/mesonbuild/scripts/coverage.py", line 150, in coverage
    subprocess.check_call([genhtml_exe,
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['genhtml', '--prefix', '/home/jian/postgres/buildtest6', '--prefix', '/home/jian/Desktop/pg_src/src6/postgres', '--output-directory', '/home/jian/postgres/buildtest6/meson-logs/coveragereport', '--title', 'Code coverage', '--legend', '--show-details', '--branch-coverage', '/home/jian/postgres/buildtest6/meson-logs/coverage.info']' returned non-zero exit status 2.
ninja: build stopped: subcommand failed.
```

first time, I compile, I had contrib/bench_hash/bench_hash.c and other related files. 
then I `git reset --hard origin/masrter`. 
now I have problem to generate coverage report again.

reproducer:
```
PG_PREFIX="/home/jian/postgres/regression6"
BUILD="/home/jian/postgres/buildtest6"
PGDATA="${PG_PREFIX}/data"
PGBIN="${PG_PREFIX}/bin"

: <<'already_in_bashrc'
SRC6="/home/jian/Desktop/pg_src/src6/postgres"
already_in_bashrc

cd ${SRC6}
find ${PG_PREFIX} -mindepth 1 -delete
find $BUILD6/meson-logs -mindepth 1 -delete
meson setup --reconfigure ${BUILD} -Dprefix=${PG_PREFIX}  -Dpgport=5461 

cd ${BUILD}
meson compile
meson install  > /dev/null

if [ $? -eq 0 ]
then
  printf "\n"
else
  printf "%s\n"  "meson install part is wrong. quit now"
  exit
fi
# meson test --list
meson test	--num-processes 20 --suite setup  --suite regress  --verbose
# coverage in /home/jian/postgres/buildtest6/meson-logs/coveragereport
# ninja coverage-html --verbose > /dev/null
ninja coverage-html --verbose
```

of course, totally wipe the $BUILD dir, it works fine.

**Comment by jianhe-fun** [comment]
I missed mentioned that reproducer should aslo have `-Db_coverage=true`.
