### ISSUE TITLE
Crash when regenerating (TypeError: expect bytes or str, not NoneType)

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#1277]
On Fedora 24:

- Clone https://anongit.freedesktop.org/git/gstreamer/gstreamer.git
- `mkdir build && meson build && ninja-build -C build`
- Edit any `meson.build` file and do a trivial change
- `ninja-build -C build`

```
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 292, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 177, in generate
    intr.run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2223, in run
    super().run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 124, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 150, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 371, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 47, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 2043, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 160, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 213, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 160, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 213, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 182, in evaluate_statement
    return self.evaluate_plusassign(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 333, in evaluate_plusassign
    addition = self.evaluate_statement(node.value)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 166, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 193, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 515, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 515, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 154, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 399, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 982, in method_call
    value = fn(state, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/modules/gnome.py", line 500, in generate_gir
    girdir = dep.get_pkgconfig_variable("girdir")
  File "/usr/lib/python3.5/site-packages/mesonbuild/dependencies.py", line 216, in get_pkgconfig_variable
    ret, out = self._call_pkgbin(['--variable=' + variable_name, self.name])
  File "/usr/lib/python3.5/site-packages/mesonbuild/dependencies.py", line 181, in _call_pkgbin
    p, out = Popen_safe([self.pkgbin] + args, env=os.environ)[0:2]
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonlib.py", line 396, in Popen_safe
    stderr=stderr, **kwargs)
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1474, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib64/python3.5/os.py", line 862, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not NoneType
FAILED: build.ninja 
'/usr/bin/python3' '/usr/bin/meson' --internal regenerate '/home/cassidy/tmp/gstreamer' '/home/cassidy/tmp/gstreamer/build' --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by gdesmott** [comment]
Ah, looks like it's already fixed in master with de0b02ee2d3847de9787e6b0ac32ebcb61018e15
