### ISSUE TITLE
Erroneously setting a cpp pch in a c-only target causes an internal meson error

### ISSUE THREAD

**Issue by trogke** [mesonbuild/meson#12820]
Hello,

**Describe the bug**
Setting the option **cpp_pch** for a target that only contains C sources causes an internal meson error:

>   File "mesonbuild\mesonmain.py", line 194, in run
>   File "mesonbuild\msetup.py", line 318, in run
>   File "mesonbuild\msetup.py", line 194, in generate
>   File "mesonbuild\msetup.py", line 259, in _generate
>   File "mesonbuild\backend\ninjabackend.py", line 615, in generate
>   File "mesonbuild\backend\ninjabackend.py", line 926, in generate_target
>   File "mesonbuild\backend\ninjabackend.py", line 2996, in generate_pch
> KeyError: 'cpp'

**To Reproduce**
meson.build
```
project('testme', ['c', 'cpp'])

executable('testme',
  'test.c',
  c_pch : 'pch/c_pch.h',
  # there be dragons here
  cpp_pch : 'pch/c_pch.h')
```

test.c
```
#include <stdio.h>
int main(int argc, char **argv) {
  printf("test me!\n");
  return 0;
}
```

pch/c_pch.h
```
#include <stdio.h>
```

**Expected behavior**
Meson should output a clear error message, or alternatively accept the **cpp_pch** option for c only targets.

**system parameters**
* Native build
* OS: Windows 11
* Python 3.10.11
* Meson: 1.1.0
* Ninja: 1.11.0 / Visual Studio 2022

**Comment by bonzini** [comment]
Confirmed:

```
  File "/usr/lib/python3.13/site-packages/mesonbuild/backend/ninjabackend.py", line 1006, in generate_target
    pch_objects = self.generate_pch(target, header_deps=header_deps)
  File "/usr/lib/python3.13/site-packages/mesonbuild/backend/ninjabackend.py", line 3204, in generate_pch
    compiler: Compiler = target.compilers[lang]
                         ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'cpp'

ERROR: Unhandled python exception
```

**Comment by C-512L** [comment]
I stumbled upon this or an almost identical issue. Happens if an exclusively C++ target declares `c_pch` by accident:

Here is the full output:
```
 *  Executing task: /usr/bin/meson setup --reconfigure -Dwarning_level=3 /home/c512l/Documents/p1-alg/builddir /home/c512l/Documents/p1-alg 

The Meson build system
Version: 1.10.2
Source dir: /home/c512l/Documents/p1-alg
Build dir: /home/c512l/Documents/p1-alg/builddir
Build type: native build
Project name: p1-alg
Project version: undefined
C++ compiler for the host machine: c++ (gcc 16.0.1 "c++ (GCC) 16.0.1 20260321 (Red Hat 16.0.1-0)")
C++ linker for the host machine: c++ ld.bfd 2.46-1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

p1-alg undefined

  User defined options
    warning_level: 3

Found ninja-1.13.2 at /usr/bin/ninja
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/mesonbuild/msetup.py", line 404, in run
    app.generate()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.14/site-packages/mesonbuild/msetup.py", line 196, in generate
    return self._generate(env, capture, vslite_ctx)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/mesonbuild/msetup.py", line 284, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
  File "/usr/lib/python3.14/site-packages/mesonbuild/backend/ninjabackend.py", line 660, in generate
    self.generate_target(t)
    ~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.14/site-packages/mesonbuild/backend/ninjabackend.py", line 1022, in generate_target
    pch_objects = self.generate_pch(target, header_deps=header_deps)
  File "/usr/lib/python3.14/site-packages/mesonbuild/backend/ninjabackend.py", line 3478, in generate_pch
    compiler: Compiler = target.compilers[lang]
                         ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'c'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

 *  The terminal process "/usr/bin/meson 'setup', '--reconfigure', '-Dwarning_level=3', '/home/c512l/Documents/p1-alg/builddir', '/home/c512l/Documents/p1-alg'" failed to launch (exit code: 2). 
 *  Terminal will be reused by tasks, press any key to close it. 
```
