### ISSUE TITLE
Unhandled python exception: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by RossSmyth** [mesonbuild/meson#12997]
**Describe the bug**
I have an embedded target that I was attempting to get working with Clang today (works with GCC). I setup my cross file and attempting to setup gave me this.

```
    Cross files: arm-none-eabi-clang.txt

Found ninja-1.11.1.git.kitware.jobserver-1 at c:\users\rsmyth\.local\bin\ninja.EXE
Traceback (most recent call last):
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 358, in run
    app.generate()
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 181, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 251, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 632, in generate
    self.generate_target(t)
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 1057, in generate_target
    elem = self.generate_link(target, outname, final_obj_list, linker, pch_objects, stdlib_args=stdlib_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 3385, in generate_link
    commands += self.get_link_debugfile_args(linker, target)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 2751, in get_link_debugfile_args
    return linker.get_link_debugfile_args(self.get_target_debug_filename(target))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\compilers\compilers.py", line 930, in get_link_debugfile_args
    return self.linker.get_debugfile_args(targetfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rsmyth\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\linkers\linkers.py", line 1286, in get_debugfile_args
    return self._apply_prefix(['/DEBUG', '/PDB:' + self.get_debugfile_name(targetfile)])
                                         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Sorry I cannot provide the meson files as it is company property :(

But this is on Windows if it is not clear. I have LLVM resources in a folder in my appdata folder. My cross file uses `['-target', 'thumb', '-march=armv6m']` for the c_args. The host_machine is arm cortex-m0 little endian. 

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?

Cross

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Microsoft Windows 10 Pro 10.0.19045 Build 19045

* what Python version are you using e.g. 3.8.0

3.11

* what `meson --version`

1.4.0

* what `ninja --version` if it's a Ninja build

1.11.1.git.kitware.jobserver-1

**Comment by RossSmyth** [comment]
Oh yeah, to be specific `clang.exe --version` is `clang version 17.0.6`

**Comment by eli-schwartz** [comment]
That's a very interesting error.

It indicates there is a linker class that defines get_debugfile_args to generate a link command based on the value of get_debugfile_name, but the latter returns None.

In linkers.py, we have two linkers that define get_debugfile_name. The generic DynamicLinker defines it to return None, but also defines the args to return [].

The Visual Studio mixin overrides both functions, so that the debugfile name comes, ultimately, from build.py and effectively "if Windows and using MSVC" as defined by any one of these being true:
- using C#
- using rust
- `compiler.get_linker_id() in {'link', 'lld-link', 'xilink', 'optlink'}`

... since those are roughly the conditions for build.py classes having a `create_debug_file = True` and as a result having a `self.debug_filename` that is a string instead of "None".

Somehow the self.debug_filename is, nonetheless, None when using a Visual Studio mixin type linker.

The question is why. The first few lines of the meson output would state the names of the compilers and linkers it has detected, so that could provide a lead. (In particular it would mention the linker, not just the compiler.)

**Comment by RossSmyth** [comment]
Ok I was able to replicate it with a simple test case at home where work copyright doesn't apply.

Three files:
1. `main.c`
2. `meson.build`
3. `arm-none-eabi-clang.txt`

## main.c
Just empty, doesn't matter.
```c
int main() {}
```

## meson.build
Minimal, also doesn't matter it seems.
```meson
project('test', 'c')

executable('test.elf', 'main.c')
```

## arm-none-eabi-clang.txt

```ini
[constants]
path = 'C:/Users/Ross/AppData/Roaming/llvm/bin/'
prefix = 'llvm-'

[binaries]
c = path + 'clang'
ar = path + prefix + 'ar'

[host_machine]
system = 'none'
cpu_family = 'arm'
cpu = 'cortex-m0'
endian = 'little'
```

Note:
```ps
> C:\Users\Ross\AppData\Roaming\llvm\bin\clang.exe -v
clang version 17.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\Ross\AppData\Roaming\llvm\bin
```
```ps
> C:\Users\Ross\AppData\Roaming\llvm\bin\clang.exe -print-targets

  Registered Targets:
    aarch64     - AArch64 (little endian)
    aarch64_32  - AArch64 (little endian ILP32)
    aarch64_be  - AArch64 (big endian)
    amdgcn      - AMD GCN GPUs
    arm         - ARM
    arm64       - ARM64 (little endian)
    arm64_32    - ARM64 (little endian ILP32)
    armeb       - ARM (big endian)
    avr         - Atmel AVR Microcontroller
    bpf         - BPF (host endian)
    bpfeb       - BPF (big endian)
    bpfel       - BPF (little endian)
    hexagon     - Hexagon
    lanai       - Lanai
    loongarch32 - 32-bit LoongArch
    loongarch64 - 64-bit LoongArch
    mips        - MIPS (32-bit big endian)
    mips64      - MIPS (64-bit big endian)
    mips64el    - MIPS (64-bit little endian)
    mipsel      - MIPS (32-bit little endian)
    msp430      - MSP430 [experimental]
    nvptx       - NVIDIA PTX 32-bit
    nvptx64     - NVIDIA PTX 64-bit
    ppc32       - PowerPC 32
    ppc32le     - PowerPC 32 LE
    ppc64       - PowerPC 64
    ppc64le     - PowerPC 64 LE
    r600        - AMD GPUs HD2XXX-HD6XXX
    riscv32     - 32-bit RISC-V
    riscv64     - 64-bit RISC-V
    sparc       - Sparc
    sparcel     - Sparc LE
    sparcv9     - Sparc V9
    systemz     - SystemZ
    thumb       - Thumb
    thumbeb     - Thumb (big endian)
    ve          - VE
    wasm32      - WebAssembly 32-bit
    wasm64      - WebAssembly 64-bit
    x86         - 32-bit X86: Pentium-Pro and above
    x86-64      - 64-bit X86: EM64T and AMD64
    xcore       - XCore
```

The error:

```ps
> meson setup --cross-file .\arm-eabi-none-clang.txt builddir    
The Meson build system
Version: 1.3.2
Source dir: C:\Users\Ross\Documents\test_name        
Build dir: C:\Users\Ross\Documents\test_name\builddir
Build type: cross build
Project name: test
Project version: undefined
Activating VS 17.8.3
C compiler for the host machine: C:/Users/Ross/AppData/Roaming/llvm/bin/clang (clang 17.0.6 "clang version 17.0.6")
C linker for the host machine: C:/Users/Ross/AppData/Roaming/llvm/bin/clang link 14.38.33133.0
C compiler for the build machine: cl (msvc 19.38.33133 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64")
C linker for the build machine: link link 14.38.33133.0
Build machine cpu family: x86_64
Build machine cpu: x86_64       
Host machine cpu family: arm
Host machine cpu: cortex-m0
Target machine cpu family: arm
Target machine cpu: cortex-m0
Build targets in project: 1

test undefined

  User defined options
    Cross files: .\arm-eabi-none-clang.txt

Found ninja-1.11.0 at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
Traceback (most recent call last):
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 358, in run
    app.generate()
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 181, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\msetup.py", line 251, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 632, in generate
    self.generate_target(t)
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 1057, in generate_target
    elem = self.generate_link(target, outname, final_obj_list, linker, pch_objects, stdlib_args=stdlib_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 3385, in generate_link
    commands += self.get_link_debugfile_args(linker, target)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\backend\ninjabackend.py", line 2751, in get_link_debugfile_args
    return linker.get_link_debugfile_args(self.get_target_debug_filename(target))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\compilers\compilers.py", line 930, in get_link_debugfile_args
    return self.linker.get_debugfile_args(targetfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ross\AppData\Local\pipx\pipx\venvs\meson\Lib\site-packages\mesonbuild\linkers\linkers.py", line 1286, in get_debugfile_args
    return self._apply_prefix(['/DEBUG', '/PDB:' + self.get_debugfile_name(targetfile)])
                                         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

[meson-log.txt](https://github.com/mesonbuild/meson/files/14661352/meson-log.txt)

And everything (including the builddir post-failure)
[testcase.zip](https://github.com/mesonbuild/meson/files/14661361/testcase.zip)

And at work I discovered that if I direct the bin path to the ARM LLVM clang it will not fail.

**Comment by RossSmyth** [comment]
I may be misremembering some things but this is replicated on a totally different computer, my home desktop.

**Comment by RossSmyth** [comment]
And also, if I change the cross file to:
```ini
[constants]
path = 'C:/Users/Ross/AppData/Roaming/llvm/bin/'
prefix = 'llvm-'

[binaries]
c = path + 'clang'
ar = path + prefix + 'ar'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```
AKA just using Clang to compile for Windows, what I am running, it is able to run meson setup successfully.

**Comment by RossSmyth** [comment]
And here it is with Arm's LLVM. The only thing I did was redirect to the Arm LLVM folder.

```ini
[constants]
path = 'C:/Users/Ross/AppData/Roaming/ArmLLVM/bin/'
```
and left everything else exactly the same. 

```ps
> meson setup --cross-file .\arm-eabi-none-clang.txt builddir
The Meson build system
Version: 1.3.2
Source dir: C:\Users\Ross\Documents\test_name
Build dir: C:\Users\Ross\Documents\test_name\builddir
Build type: cross build
Project name: test
Project version: undefined
Activating VS 17.8.3
C compiler for the host machine: C:/Users/Ross/AppData/Roaming/ArmLLVM/bin/clang (clang 17.0.1 "clang version 17.0.1")
C linker for the host machine: C:/Users/Ross/AppData/Roaming/ArmLLVM/bin/clang ld.lld 17.0.1
C compiler for the build machine: cl (msvc 19.38.33133 "Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64")
C linker for the build machine: link link 14.38.33133.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: cortex-m0
Target machine cpu family: arm
Target machine cpu: cortex-m0
Build targets in project: 1

test undefined

  User defined options
    Cross files: .\arm-eabi-none-clang.txt

Found ninja-1.11.0 at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
WARNING: Cross file does not specify strip binary, result will not be stripped.
WARNING: Cross file does not specify strip binary, result will not be stripped.
```

The setup succeeds.

[meson-log.txt](https://github.com/mesonbuild/meson/files/14661436/meson-log.txt)

**Comment by RossSmyth** [comment]
Oh I just realized I did not update meson on my home desktop, so this is with 1.3.2 above. I can repeat if 1.4.0 is desired.

**Comment by dcrowe777** [comment]
Hi, I am finding a similar issue with CUDA instead of cross compiling.
OS: Windows 10 22H2 (19045.4239)
Python : 3.10.11
Meson : 1.4.0
ninja : 1.11.1.git.kitware.jobserver-1
CUDA: 12.4.131

meson.build:
`project('test', ['cpp','cuda'])
executable('output', 'main.cu')`

main.cu:
`int main() { return 0;}`

stacktrace:
```
D:\git\test>meson setup build
The Meson build system
Version: 1.4.0
Source dir: D:\git\test
Build dir: D:\git\test\build
Build type: native build
Project name: test
Project version: undefined
Activating VS 17.9.6
C++ compiler for the host machine: cl (msvc 19.39.33523 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64")
C++ linker for the host machine: link link 14.39.33523.0
Cuda compiler for the host machine: nvcc (nvcc 12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0)
Cuda linker for the host machine: nvcc nvlink 12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.1.git.kitware.jobserver-1 at "C:\Program Files\Python310\Scripts\ninja.EXE"
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\mesonmain.py", line 186, in run
    return options.run_func(options)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\msetup.py", line 363, in run
    app.generate()
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\msetup.py", line 251, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 621, in generate
    self.generate_target(t)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 1046, in generate_target
    elem = self.generate_link(target, outname, final_obj_list, linker, pch_objects, stdlib_args=stdlib_args)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 3410, in generate_link
    commands += self.get_link_debugfile_args(linker, target)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\backend\ninjabackend.py", line 2756, in get_link_debugfile_args
    return linker.get_link_debugfile_args(self.get_target_debug_filename(target))
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\compilers\cuda.py", line 727, in get_link_debugfile_args
    return self._to_host_flags(self.host_compiler.get_link_debugfile_args(targetfile), _Phase.LINKER)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\compilers\compilers.py", line 853, in get_link_debugfile_args
    return self.linker.get_debugfile_args(targetfile)
  File "C:\Program Files\Python310\lib\site-packages\mesonbuild\linkers\linkers.py", line 1271, in get_debugfile_args
    return self._apply_prefix(['/DEBUG', '/PDB:' + self.get_debugfile_name(targetfile)])
TypeError: can only concatenate str (not "NoneType") to str

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
`

**Comment by dcrowe777** [comment]
Meson 1.2.3 works.  Meson 1.3.0 doesn't.

**Comment by dcbaker** [comment]
I just looked at the code, there's an obvious bug in the Ninja backend that would be caught if we had more type annotations. I'll send a PR shortly

**Comment by dcbaker** [comment]
I don't have access to a Cuda compiler, but if either @dcrowe777 or @RossSmyth could test #13108 and see if that fixes their issue

**Comment by dcbaker** [comment]
I believe this is fixed, but please re-open if you can still reproduce this with Meson's main branch

**Comment by RossSmyth** [comment]
Yup, that worked! Thanks!

**Comment by dcbaker** [comment]
Thanks for checking!
