### ISSUE TITLE
Meson tests in mingw

### ISSUE THREAD

**Issue by msink** [mesonbuild/meson#1323]
Runned from MSYS2/MinGW64 shell:

```
$ ./run_tests.py --backend=ninja
Traceback (most recent call last):
  File "F:/msys64/mingw64/lib/python3.5\multiprocessing\synchronize.py", line 29, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'sem_unlink'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_project_tests.py", line 560, in <module>
    (passing_tests, failing_tests, skipped_tests) = run_tests(all_tests, 'meson-test-run', options.extra_args)
  File "run_project_tests.py", line 406, in run_tests
    executor = conc.ProcessPoolExecutor(max_workers=num_workers)
  File "F:/msys64/mingw64/lib/python3.5\concurrent\futures\process.py", line 390, in __init__
    EXTRA_QUEUED_CALLS)
  File "F:/msys64/mingw64/lib/python3.5\multiprocessing\context.py", line 101, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "F:/msys64/mingw64/lib/python3.5\multiprocessing\queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "F:/msys64/mingw64/lib/python3.5\multiprocessing\context.py", line 65, in Lock
    from .synchronize import Lock
  File "F:/msys64/mingw64/lib/python3.5\multiprocessing\synchronize.py", line 34, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

**Comment by jpakkane** [comment]
Seems to be a limitation of Mingw's Python (AFAICR the MinGW C compiler does not have support for native Windows threads so it does not work). Meson itself does not need any of these primitives, only the test framework does.

**Comment by nirbheek** [comment]
We should fall back to single-process test invocation if importing processing returns ImportError.

**Comment by msink** [comment]
If uninstall mingw version of python, and install msys2 one:
```
 pacman -R mingw-w64-x86_64-python3
 pacman -S python3
```

-- there another error:
```
Traceback (most recent call last):
  File "/f/PycharmProjects/meson/mesonbuild/mesonmain.py", line 295, in run
    app.generate()
  File "/f/PycharmProjects/meson/mesonbuild/mesonmain.py", line 169, in generate
    intr = interpreter.Interpreter(b, g)
  File "/f/PycharmProjects/meson/mesonbuild/interpreter.py", line 1197, in __init__
    self.parse_project()
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 110, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 145, in evaluate_codeblock
    raise e
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 139, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 150, in evaluate_statement
    return self.function_call(cur)
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 371, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/f/PycharmProjects/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/f/PycharmProjects/meson/mesonbuild/interpreter.py", line 1610, in func_project
    self.add_languages(args[1:], True)
  File "/f/PycharmProjects/meson/mesonbuild/interpreter.py", line 1739, in add_languages
    self.build.add_compiler(comp)
  File "/f/PycharmProjects/meson/mesonbuild/build.py", line 106, in add_compiler
    self.static_linker = self.environment.detect_static_linker(compiler)
  File "/f/PycharmProjects/meson/mesonbuild/environment.py", line 700, in detect_static_linker
    p, out, err = Popen_safe([linker, arg])
  File "/f/PycharmProjects/meson/mesonbuild/mesonlib.py", line 395, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1659, in _communicate
    self.stdout.encoding)
  File "/usr/lib/python3.4/subprocess.py", line 888, in _translate_newlines
    data = data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 79: invalid continuation byte
```

**Comment by msink** [comment]
On Win10-64 English:

```
test cases/common/1 trivial
stdout
---
[1mThe Meson build system[0m
Version: 0.38.0.dev1
Source dir: [1m/c/Work/meson/test cases/common/1 trivial[0m
Build dir: [1m/c/Work/meson/b 4841vhu_[0m
Build type: [1mnative build[0m
Project name: [1mtrivial test[0m
Native c compiler: [1mcc[0m (gcc 6.3.0)
Build machine cpu family: [1mx86_64[0m
Build machine cpu: [1mx86_64[0m
Build targets in project: [1m1[0m
[1/2] Compiling c object trivialprog@exe/trivial.c.obj
[2/2] Linking target trivialprog.exe
1/1 runtest                                 OK       0.06 s

OK:         1
FAIL:       0
SKIP:       0
TIMEOUT:    0

Full log written to /c/Work/meson/b 4841vhu_/meson-logs/testlog.txt.
No tests defined.
[0/1] Regenerating build files
FAILED: build.ninja 
"/usr/bin/python3" "/c/Work/meson/meson.py" --internal regenerate "/c/Work/meson/test cases/common/1 trivial" "/c/Work/meson/b 4841vhu_" --backend ninja
CreateProcess failed: The system cannot find the file specified.
---
stderr
---
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by jpakkane** [comment]
This means that when you first ran Meson your Python interpreter called itself `/usr/bin/python3`. When you reinvoked it (possibly from a different shell) it no longer is called that.

**Comment by msink** [comment]
Dont know, what I did:

- Install msys2 as described in https://msys2.github.io
- In mingw64 shell:
```
pacman -S base-devel gcc VCS 
pacman -S mingw-w64-{x86_64,i686}-toolchain
pacman -S mingw-w64-{x86_64,i686}-ninja
pacman -S python3

git clone https://github.com/mesonbuild/meson.git
cd meson && ./run_tests.py --backend=ninja
```

**Comment by msink** [comment]
Reproduced on appveyor: #1346

**Comment by nirbheek** [comment]
This is not a Meson bug, it's an MSYS2 Ninja bug.

The problem is that MSYS2 pretends that there's a Linux prefix in which Python3 is installed, and MSYS2 packages/libraries do some magic to translate that to the correct paths. So, for instance, this works:

```
$ python3
Python 3.4.3 (default, Mar  4 2016, 10:23:36)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.executable)
/usr/bin/python3
>>> import subprocess; subprocess.check_output([sys.executable, '--version'])
b'Python 3.4.3\n'
>>>
```

But Ninja hasn't been patched, so it is using Windows APIs to find `/usr/bin/python3` and fails to find it.

I think it's a better option to just avoid MSYS2 for Python 3 and Ninja, and use the native Windows versions for those.

**Comment by msink** [comment]
OK, with native Ninja and Python only 3 tests failed - see updated #1346

**Comment by lazka** [comment]
fyi, the "This platform lacks a functioning sem_open implementation" error has been fixed in MSYS2 for some time now. In case the same is true for OpenBSD this workaround could be removed.
