### ISSUE TITLE
AttributeError: 'module' object has no attribute 'commonpath'

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1341]
```python
Traceback (most recent call last):
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/mesonmain.py", line 286, in run
    app.generate()
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/mesonmain.py", line 160, in generate
    intr = interpreter.Interpreter(b, g)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreter.py", line 1198, in __init__
    self.parse_project()
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 111, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreter.py", line 1581, in func_project
    self.parse_default_options(kwargs['default_options'])
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/interpreter.py", line 1549, in parse_default_options
    self.coredata.set_builtin_option(key, value)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/coredata.py", line 196, in set_builtin_option
    value = self.sanitize_dir_option_value(prefix, optname, value)
  File "/builddir/build/BUILD/meson-0.38.0/mesonbuild/coredata.py", line 161, in sanitize_dir_option_value
    if os.path.commonpath([value, prefix]) != prefix:
AttributeError: 'module' object has no attribute 'commonpath'
```

I think it happened after one of tests failed

**Comment by ignatenkobrain** [comment]
Actually, commonpath has been added in 3.5 while EL7 has 3.4....
