### ISSUE TITLE
`gnome.compile_resources()` results in unhandled python exception when `install: true` and no `install_dir` is given

### ISSUE THREAD

**Issue by RaviRahar** [mesonbuild/meson#13447]
**Describe the bug**
 `gnome.compile_resources()` errors out when 'install: true` is provided but no `install_dir` is provided.
```
The Meson build system
Version: 1.5.0
Source dir: [redacted]
Build dir: [redacted]
Build type: native build
Project name: example
Project version: 0.0.1
C compiler for the host machine: cc (gcc 14.1.1 "cc (GCC) 14.1.1 20240522")
C linker for the host machine: cc ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency gtk4 found: YES 4.14.4
Build-time dependency gio-2.0 found: YES 2.80.4
Program /usr/bin/glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Dependency gio-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring config.h using configuration
src/meson.build:35: WARNING: The variable(s) 'version' in the input file 'src/config.h.in' are not present in the given configuration data.
Dependency gio-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program gtk4-update-icon-cache found: YES (/usr/bin/gtk4-update-icon-cache)
Program update-desktop-database found: YES (/usr/bin/update-desktop-database)
Program update-mime-database found: YES (/usr/bin/update-mime-database)
Build targets in project: 3

Found ninja-1.12.1 at /usr/bin/ninja
Traceback (most recent call last):                                                                                                                              
  File "/usr/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 364, in run
    app.generate()
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 252, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/ninjabackend.py", line 654, in generate
    self.generate_install()
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/ninjabackend.py", line 1301, in generate_install
    self.create_install_data_files()
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/backends.py", line 1673, in create_install_data_files
    pickle.dump(self.create_install_data(), ofile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/backends.py", line 1660, in create_install_data
    self.generate_target_install(d)
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/backends.py", line 1822, in generate_target_install
    i = TargetInstallData(f, outdir, outdir_name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in __init__
  File "/usr/lib/python3.12/site-packages/mesonbuild/backend/backends.py", line 146, in __post_init__
    outdir_name = os.path.join('{prefix}', self.outdir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 164, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
```meson
project('example', 'c', version: '0.0.1')

gnome = import('gnome')

proname = meson.project_name()
gnome.compile_resources(
  proname,
  proname + '.gresources.xml',
  gresource_bundle: true,
  install: true,
)

sources = files('main.c')
executable(meson.project_name(), sources: sources, install: true)
```

**Expected behavior**
Either report that `install_dir` is missing and then exit gracefully or use some default location for installation.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  - Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  - Arch Linux
* what Python version are you using e.g. 3.8.0
  - 3.12.4
* what `meson --version`
  - 1.5.0
* what `ninja --version` if it's a Ninja build
  - 1.12.1

**Comment by RaviRahar** [comment]
[`install_dir`](https://github.com/mesonbuild/meson/blob/2548f921a29babe665593e5dcf401eb27aedd174/mesonbuild/modules/gnome.py#L1646) is set to default of `includedir`.

**Comment by RaviRahar** [comment]
> [`install_dir`](https://github.com/mesonbuild/meson/blob/2548f921a29babe665593e5dcf401eb27aedd174/mesonbuild/modules/gnome.py#L512) is being set to `[]` by default.
I think gresources can have no default location to install to. They are generally installed in` /usr/share/[applicationname]`.
I can add a check, if 'install` is set to true and `gresource_bundle` set to true and `install_dir` given, then only go ahead or else raise exception.
@dcbaker do you think this behaviour is okay?

**Comment by eli-schwartz** [comment]
Yes, that sounds correct and we require it for other functions as well.
