### ISSUE TITLE
1.5 branch fails in Debian

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#13476]
```
=================================== frameworks: 35 boost symlinks ==================================


Failed during: configure
Reason: Generating the build system failed.


(inprocess) $ setup --prefix /usr --libdir lib 'test cases/frameworks/35 boost symlinks' '/build/meson-1.5.1/b a257bb1ae8' --backend=ninja --native-file '/build/meson-1.5.1/b a257bb1ae8/nativefile.ini'
Included file /build/meson-1.5.1/b a257bb1ae8/meson-logs/meson-log.txt:
Build started at 2024-07-26T16:16:11.400967
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr -Dlibdir=lib -Dbackend=ninja '--native-file=/build/meson-1.5.1/b a257bb1ae8/nativefile.ini'
Python system: Linux
The Meson build system
Version: 1.5.1
Source dir: /build/meson-1.5.1/test cases/frameworks/35 boost symlinks
Build dir: /build/meson-1.5.1/b a257bb1ae8
Build type: native build
Project name: boosttestsymlinks
Project version: undefined
-----------
Detecting compiler via: `c++ --version` -> 0
stdout:
c++ (Debian 14.1.0-5) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-----------
Running command: -cpp -x c++ -E -dM -
-----
-----------
Detecting linker via: `c++ -Wl,--version -Wl,-z,relro -g -O2 -ffile-prefix-map=/build/meson-1.5.1=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2` -> 0
stdout:
GNU ld (GNU Binutils for Debian) 2.42.90.20240720
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
-----------
stderr:
collect2 version 14.1.0
/usr/bin/ld -plugin /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-linux-gnu/14/lto-wrapper -plugin-opt=-fresolution=/tmp/ccpDEvWq.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/14/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/14 -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/14/../../.. --version -z relro -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/14/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/crtn.o
-----------
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -g -O2 -ffile-prefix-map=/build/meson-1.5.1=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -Wl,-z,relro
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  '/build/meson-1.5.1/b a257bb1ae8/meson-private/sanitycheckcpp.exe'
C++ compiler for the host machine: c++ (gcc 14.1.0 "c++ (Debian 14.1.0-5) 14.1.0")
C++ linker for the host machine: c++ ld.bfd 2.42.90.20240720
-----------
Detecting archiver via: `gcc-ar --version` -> 0
stdout:
GNU ar (GNU Binutils for Debian) 2.42.90.20240720
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
-----------
-----------
Detecting compiler via: `c++ --version` -> 0
stdout:
c++ (Debian 14.1.0-5) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-----------
Running command: -cpp -x c++ -E -dM -
-----
-----------
Detecting linker via: `c++ -Wl,--version -Wl,-z,relro -g -O2 -ffile-prefix-map=/build/meson-1.5.1=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2` -> 0
stdout:
GNU ld (GNU Binutils for Debian) 2.42.90.20240720
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
-----------
stderr:
collect2 version 14.1.0
/usr/bin/ld -plugin /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-linux-gnu/14/lto-wrapper -plugin-opt=-fresolution=/tmp/ccK4lXJh.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/14/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/14 -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/14/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/14/../../.. --version -z relro -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/14/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/14/../../../x86_64-linux-gnu/crtn.o
-----------
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -g -O2 -ffile-prefix-map=/build/meson-1.5.1=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -Wl,-z,relro
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  '/build/meson-1.5.1/b a257bb1ae8/meson-private/sanitycheckcpp.exe'
C++ compiler for the build machine: c++ (gcc 14.1.0 "c++ (Debian 14.1.0-5) 14.1.0")
C++ linker for the build machine: c++ ld.bfd 2.42.90.20240720
-----------
Detecting archiver via: `gcc-ar --version` -> 0
stdout:
GNU ar (GNU Binutils for Debian) 2.42.90.20240720
Copyright (C) 2024 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
-----------
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Checking potential boost root /build/meson-1.5.1/test cases/frameworks/35 boost symlinks/boost
Run-time dependency Boost found: NO (tried system)

test cases/frameworks/35 boost symlinks/meson.build:5:0: ERROR: Assert failed: expected to find a fake version of boost




Traceback (most recent call last):
  File "/build/meson-1.5.1/run_tests.py", line 304, in run_configure_inprocess
    returncode = mesonmain.run(commandlist, get_meson_script())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/mesonmain.py", line 279, in run
    return CommandLineParser().run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/mesonmain.py", line 190, in run
    return errorhandler(e, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/mesonmain.py", line 31, in errorhandler
    raise e
  File "/build/meson-1.5.1/mesonbuild/mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/msetup.py", line 364, in run
    app.generate()
  File "/build/meson-1.5.1/mesonbuild/msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/msetup.py", line 226, in _generate
    intr.run()
  File "/build/meson-1.5.1/mesonbuild/interpreter/interpreter.py", line 3032, in run
    super().run()
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/interpreterbase/decorators.py", line 62, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/meson-1.5.1/mesonbuild/interpreter/interpreter.py", line 744, in func_assert
    raise InterpreterException('Assert failed: ' + message)
mesonbuild.interpreterbase.exceptions.InterpreterException: Assert failed: expected to find a fake version of boost



Total passed tests:  668
Total failed tests:  1
Total skipped tests: 43

All failures:
  -> frameworks: 35 boost symlinks
$ /usr/bin/python3 run_unittests.py --backend=ninja
$ /usr/bin/python3 run_project_tests.py
make[1]: Leaving directory '/build/meson-1.5.1'
```

**Comment by jpakkane** [comment]
This seems to only happen if you use ´run_tests.py`. I tried using `run_project_tests.py` as it's faster but the bug did not occur.

**Comment by jpakkane** [comment]
I rebased the whole shebang with pbuilder and the results were inconclusive. Then I ran the release again without changes and it passed. No idea what could have caused this but it's passing now so closing and releasing.
