### ISSUE TITLE
'rewrite kwargs set dependency' results in an unhandled Python exception

### ISSUE THREAD

**Issue by detly** [mesonbuild/meson#13502]
Running `meson rewrite kwargs set dependency libdetly install true` on the project below results in a Python traceback and the message *This is a Meson bug and should be reported!*

## To Reproduce

`meson.build`:  
```text
project('detly', ['c'], meson_version: '>=1.5.1')

libdetly = library('detly', files('main.c'))

libdetly_dep = declare_dependency(link_with: libdetly)
```

The file `main.c` should exist but can be empty. In an Alpine Docker image:

```text
/test # meson setup build
The Meson build system
Version: 1.5.1
Source dir: /test
Build dir: /test/build
Build type: native build
Project name: detly
Project version: undefined
C compiler for the host machine: cc (gcc 12.2.1 "cc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
C linker for the host machine: cc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.9 at /usr/bin/ninja
/test # meson rewrite kwargs set dependency libdetly install true
ERROR: Unable to find the function node
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/rewriter.py", line 1073, in run
    raise e
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/rewriter.py", line 1067, in run
    rewriter.process(i)
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/rewriter.py", line 884, in process
    self.functions[cmd['type']](cmd)
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/rewriter.py", line 91, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mesonbuild/rewriter.py", line 530, in process_kwargs
    assert isinstance(node, FunctionNode)
AssertionError

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
/test # 
```

## Expected behavior

This could be misuse of the rewriter by me, but the unhandled exception instead of a usage message appears to be a bug.

## System parameters
* Native build.
* OS: `python:3.11.5-alpine3.17` Docker image 
* Python: 3.11.5
* Meson: 1.5.1
* Ninja: actually Samurai, reports 1.9, but did not actually get as far as building

**Comment by eyalitki** [comment]
Thanks for reporting the issue, a fix will be submitted shortly.

As for the syntax at hand, the error is causes because ```libdetly``` is recognized as a "library" while ```libdetly_dep``` is recognized as a "declare_dependency", both of which aren't supported (only direct "dependency" are currently supported).
