### ISSUE TITLE
[REGRESSION] Wrong command argument when sanity checking cross compiler

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#1351]
With `0.38.1` using the following simple cross build file:

```
[binaries]
# we could set exe_wrapper = qemu-arm-static but to test the case
# when cross compiled binaries can't be run we don't do that
c = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc'
cpp = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-g++'
ar = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/ar'
strip = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/strip'
pkgconfig = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-pkg-config'

[properties]
root = '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot'
c_args = ['-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include']
cpp_args = ['-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include']

has_function_printf = true
has_function_hfkerhisadf = false

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7' # Not sure if correct.
endian = 'little'
```

I am getting the following error:
```
The Meson build system
Version: 0.38.1
Source dir: /home/thiblahute/devel/gstreamer/gst-build
Build dir: /home/thiblahute/devel/gstreamer/gst-build/odroidbuild
Build type: cross build
Project name: All GStreamer modules
Traceback (most recent call last):
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonmain.py", line 289, in run
    app.generate()
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonmain.py", line 160, in generate
    intr = interpreter.Interpreter(b, g)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1224, in __init__
    self.parse_project()
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 111, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1640, in func_project
    self.add_languages(args[1:], True)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1756, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/interpreter.py", line 1730, in detect_compilers
    cross_comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/compilers.py", line 882, in sanity_check
    return self.sanity_check_impl(work_dir, environment, 'sanitycheckc.c', code)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/compilers.py", line 858, in sanity_check_impl
    pc, stdo, stde = Popen_safe(cmdlist, cwd=work_dir)
  File "/home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/mesonlib.py", line 496, in Popen_safe
    stderr=stderr, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include'
```

Now I noticed the following:

```
ipdb> c
> /home/thiblahute/devel/gstreamer/gst-build/meson/mesonbuild/compilers.py(858)sanity_check_impl()
    857         import ipdb; ipdb.set_trace()
--> 858         pc, stdo, stde = Popen_safe(cmdlist, cwd=work_dir)
    859         mlog.debug('Sanity check compiler command line:', ' '.join(cmdlist))

ipdb> p cmdlist
['-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include', '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc', '-c', '/home/thiblahute/devel/gstreamer/gst-build/odroidbuild/meson-private/sanitycheckc.c', '-o', '/home/thiblahute/devel/gstreamer/gst-build/odroidbuild/meson-private/sanitycheckc_cross.exe']
ipdb> p self.exelist + extra_flags
['-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include', '/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc', '-c']
ipdb> p self.exelist + list(extra_flags)
['/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/arm-unknown-linux-gnueabihf-gcc', '-I/home/thiblahute/devel/odroid/x-tools7h/arm-unknown-linux-gnueabihf/bin/../arm-unknown-linux-gnueabihf/sysroot/usr/include', '-c']
```

So there is something going wrong when concatenating a `list` with a `CompilerArgs` in that case.

**Comment by nirbheek** [comment]
I know the problem. The issue is that the compiler itself is being added to the list of compiler arguments, which messes up everything. The reordering of the list is on purpose, but it can only work if you only have arguments in the list.
