### ISSUE TITLE
Passing dict for library()'s dependencies arg results in an unhandled Python exception

### ISSUE THREAD

**Issue by detly** [mesonbuild/meson#13539]
If I pass a dict to the `dependencies` argument of `library()`, I get an unhandled Python exception. Passing a dict here is an error, but the unhandled exception says it should be reported as a bug anyway.

## To Reproduce

`meson.build`:  
```meson
project('detly', ['c'], meson_version: '>=1.5.1')
deps = {'somedep' : declare_dependency(compile_args : [])}
libdetly = library('detly', files('main.c'), dependencies : deps)
```

You also need an empty `main.c` file.

Then run `meson setup build`:

```text
PS C:\Users\JasonHeeris\Code\mesontest> meson setup build
The Meson build system
Version: 1.5.1
Source dir: C:\Users\JasonHeeris\Code\mesontest
Build dir: C:\Users\JasonHeeris\Code\mesontest\build
Build type: native build
Project name: detly
Project version: undefined
Activating VS 17.10.5
C compiler for the host machine: cl (msvc 19.40.33813 "Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33813 for x64")
C linker for the host machine: link link 14.40.33813.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 188, in run
  File "mesonbuild\msetup.py", line 364, in run
  File "mesonbuild\msetup.py", line 187, in generate
  File "mesonbuild\msetup.py", line 226, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 3032, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 169, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 205, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 642, in assignment
  File "mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 116, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
  File "mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1888, in func_library
  File "mesonbuild\interpreter\interpreter.py", line 3257, in build_library
  File "mesonbuild\interpreter\interpreter.py", line 3442, in build_target
  File "mesonbuild\build.py", line 2197, in __init__
  File "mesonbuild\build.py", line 765, in __init__
  File "mesonbuild\build.py", line 2341, in process_kwargs
  File "mesonbuild\build.py", line 1142, in process_kwargs
  File "mesonbuild\build.py", line 1331, in add_deps
TypeError: unhashable type: 'dict'

meson.build:3:11: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

## System parameters

* Plain native build
* OS: Windows 11 Pro 23H2
* Python version: Not sure, it's whatever's bundled with the MSI for 1.5.1
* Meson version: 1.5.1
* Ninja version: 1.12.1

**Comment by eyalitki** [comment]
Thanks for reporting the error. With the above submitted patch, the output should now be the expected one:
```
meson.build:3:11: ERROR: Argument is of an unacceptable type 'dict'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency()).
```

**Comment by eyalitki** [comment]
I apologize, what seemed initially as a small fix blew out of proportions and is beyond my scope of understanding if implemented as requested by the project maintainers. I hope this will be handled by one of the maintainers.

**Comment by JamBalaya56562** [comment]
Thank you for the report. On current Meson this no longer produces an unhandled Python exception — passing a `dict` is now rejected with a clean, sourced error instead of a traceback.

Running your reproducer (`dependencies : {'somedep': declare_dependency(...)}`) now gives:

```
meson.build:3:11: ERROR: library keyword argument 'dependencies' was of type array[dict] but should have been array[Dependency | InternalDependency]
```

with no `Traceback (most recent call last)` / "report this as a bug" output. This is because the `dependencies` keyword is validated through `typed_kwargs`:

```python
# mesonbuild/interpreter/type_checking.py
DEPENDENCIES_KW: KwargInfo[T.List[Dependency]] = KwargInfo(
    'dependencies',
    ContainerTypeInfo(list, (Dependency, InternalDependency)),
    listify=True,
    default=[],
)
```

which is part of `_ALL_TARGET_KWS` applied to `library()` / `build_target()`.

**Verification:** the typed-kwargs definition is in `mesonbuild/interpreter/type_checking.py`, and I confirmed the clean error above by running the reproducer against current master.

Since the crash is gone (it's now a normal argument-type error pointing at the offending line), this looks safe to close. Thanks for the clear reproducer.
