### ISSUE TITLE
failing unit test case 135 for 0.38.0

### ISSUE THREAD

**Issue by anthraxx** [mesonbuild/meson#1359]
Hey, I'm trying to package the new version and encountered a unit test failure inside a clean build environment.
I'm bit confused looking at the source and the error message, maybe you have any ideas?

```
Total passed tests: 232
Total failed tests: 1
Total skipped tests: 30

Mesonlogs of failing tests

The Meson build system
Version: 0.38.0
Source dir: /build/meson/src/meson-0.38.0/test cases/common/135 generated assembly
Build dir: /build/meson/src/meson-0.38.0/b bpd2bhor
Build type: native build
Project name: generated assembly
Native c compiler: cc (gcc 6.3.1)
Appending CFLAGS from environment: '-march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong'
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro'
Appending CPPFLAGS from environment: '-D_FORTIFY_SOURCE=2'
Build machine cpu family: x86
Build machine cpu: i686
Program copy.py found: YES (/usr/bin/env python /build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py)
Build targets in project: 5
[1/12] cc  '-Isquare-gen-test@exe' '-I.' '-I../test cases/common/135 generated assembly' '-fdiagnostics-color=always' '-pipe' '-Wall' '-Winvalid-pch' '-O0' '-g' '-march=i686' '-mtune=generic' '-O2' '-fstack-protector-strong' '-D_FORTIFY_SOURCE=2' '-MMD' '-MQ' 'square-gen-test@exe/main.c.o' '-MF' 'square-gen-test@exe/main.c.o.d' -o 'square-gen-test@exe/main.c.o' -c '../test cases/common/135 generated assembly/main.c'
[2/12] cc  '-Isquare-ct-test@exe' '-I.' '-I../test cases/common/135 generated assembly' '-fdiagnostics-color=always' '-pipe' '-Wall' '-Winvalid-pch' '-O0' '-g' '-march=i686' '-mtune=generic' '-O2' '-fstack-protector-strong' '-D_FORTIFY_SOURCE=2' '-MMD' '-MQ' 'square-ct-test@exe/main.c.o' '-MF' 'square-ct-test@exe/main.c.o.d' -o 'square-ct-test@exe/main.c.o' -c '../test cases/common/135 generated assembly/main.c'
[3/12] '/usr/bin/env' 'python' '/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py' '../test cases/common/135 generated assembly/square-x86.S.in' 'square-x86.S'
FAILED: square-x86.S 
'/usr/bin/env' 'python' '/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py' '../test cases/common/135 generated assembly/square-x86.S.in' 'square-x86.S'
Traceback (most recent call last):
  File "/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py", line 4, in <module>
    import shutil
  File "/usr/lib/python3.6/shutil.py", line 13, in <module>
    import tarfile
  File "/usr/lib/python3.6/tarfile.py", line 49, in <module>
    import copy
  File "/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py", line 6, in <module>
    shutil.copyfile(sys.argv[1], sys.argv[2])
AttributeError: module 'shutil' has no attribute 'copyfile'
[4/12] '/usr/bin/env' 'python' '/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py' '../test cases/common/135 generated assembly/square-x86.S.in' 'square-gen@sha/square-x86.S'
FAILED: square-gen@sha/square-x86.S 
'/usr/bin/env' 'python' '/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py' '../test cases/common/135 generated assembly/square-x86.S.in' 'square-gen@sha/square-x86.S'
Traceback (most recent call last):
  File "/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py", line 4, in <module>
    import shutil
  File "/usr/lib/python3.6/shutil.py", line 13, in <module>
    import tarfile
  File "/usr/lib/python3.6/tarfile.py", line 49, in <module>
    import copy
  File "/build/meson/src/meson-0.38.0/test cases/common/135 generated assembly/copy.py", line 6, in <module>
    shutil.copyfile(sys.argv[1], sys.argv[2])
AttributeError: module 'shutil' has no attribute 'copyfile'
ninja: build stopped: subcommand failed.
```

however that is definitivly there:

```
> python 
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.copyfile
<function copyfile at 0x7f9d6d399378>

```

**Comment by msink** [comment]
fixed in #d2e4d59

**Comment by nirbheek** [comment]
This is a really weird Python bug, but I guess we'll work around it. @msink found the fix for it a little while ago. The fix will be in the `0.38.1` bugfix release which is happening on Monday or Tuesday.

**Comment by nirbheek** [comment]
To clarify, this is a Python bug because it should *never* look in the current directory for modules before the system paths. We will work around it, but we should also figure out why it's happening. Which distro are you packaging for?

**Comment by anthraxx** [comment]
Thanks for the fast answer, the patch indeed fixes the issue and all tests are passing.
I'm packaging for Arch Linux.

Actually I wouldn't call that a python bug, its a documented behavior/feature that it does so.
https://docs.python.org/3/library/sys.html#sys.path

**Comment by nirbheek** [comment]
`sys.path` is only searched a built-in module by that name wasn't found. It should ***never*** look for built-in modules in the current directory before looking in the built-in paths. So either the Python packaged in ArchLinux is broken to the point of being a security risk, or something else is wrong. You really should contact your Python team about this.

Also, reopening because this is not really fixed in our repository yet.

**Comment by anthraxx** [comment]
You are really deeply mistaken, its the regular way how python works, there is no issue about it and it is not distro specific and especially *not* Arch Linux specific! Also there is really absolutely no privilege boundary violated when doing so, it is the executed modules directory, you can't magically escalate privileges by doing so.

Here is how it behaves on a debian stable:
```
> python2 copy.py
<module 'copy' from '/tmp/test/copy.py'>
<module 'copy' from '/tmp/test/copy.py'>
[zsh][590]> cat copy.py
import copy
print(copy)
[zsh][591]> uname -a
Linux antbox 3.2.0-4-amd64 #1 SMP Debian 3.2.82-1 x86_64 GNU/Linux
```

You realize it does exactly the same.

**Comment by nirbheek** [comment]
Yes, I was wrong about the search path. I thought `copy` was part of the built-in modules list, but it isn't:

```
>>> sys.builtin_module_names
('_ast', '_codecs', '_collections', '_functools', '_imp', '_io', '_locale', '_operator', '_sre', '_stat', '_string', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', 'atexit', 'builtins', 'errno', 'faulthandler', 'gc', 'itertools', 'marshal', 'posix', 'pwd', 'signal', 'sys', 'xxsubtype', 'zipimport')
```

So this is not a bug, but still strange that it would prefer searching for stdlib modules in the current path. But as you say this is how Python works elsewhere too.

What's strange is that this was never caught before, which means that Python works differently on different distros. We have continuous testing on Ubuntu, Fedora, Debian, native Windows, and macOS, and the only places we've seen it reported are on Arch and MSYS2, so that's interesting to me.
