### ISSUE TITLE
IndexError in mesontest when using add_test_setup

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/meson#1371]
I'm trying to use add_test_setup() in gst-build ( https://cgit.freedesktop.org/gstreamer/gst-build/tree/meson.build ) 

```diff
diff --git a/meson.build b/meson.build
index b5283ea..6f8397b 100644
--- a/meson.build
+++ b/meson.build
@@ -1,4 +1,4 @@
-project('All GStreamer modules', 'c', version : '1.11.1.1', meson_version : '>= 0.36')
+project('All GStreamer modules', 'c', version : '1.11.1.1', meson_version : '>= 0.38')
 
 gst_version = '>= @0@'.format(meson.project_version())
 gst_branch = 'master'
@@ -101,3 +101,7 @@ update = find_program('git-update')
 run_target('git-update', command : [update])
 run_target('update', command : [update,
     '--builddir=@0@'.format(meson.current_build_dir())])
+
+env = environment()
+env.set('GST_TRACERS', 'leaks')
+add_test_setup('leaks', env: env)
```

But doing so raises an exception in `mesontest`

```
$ /home/cassidy/dev/meson/mesontest.py -C build --setup leaks
ninja: Entering directory `/home/cassidy/dev/gst/master/gst-build/build'
ninja: no work to do.
Traceback (most recent call last):
  File "/home/cassidy/dev/meson/mesontest.py", line 579, in <module>
    sys.exit(run(sys.argv[1:]))
  File "/home/cassidy/dev/meson/mesontest.py", line 575, in run
    return th.doit()
  File "/home/cassidy/dev/meson/mesontest.py", line 337, in doit
    self.run_tests(tests)
  File "/home/cassidy/dev/meson/mesontest.py", line 458, in run_tests
    (logfile, logfilename, jsonlogfile, jsonlogfilename) = self.open_log_files()
  File "/home/cassidy/dev/meson/mesontest.py", line 415, in open_log_files
    namebase = os.path.split(self.get_wrapper()[0])[1]
IndexError: list index out of range
```

**Comment by gdesmott** [comment]
The example from https://github.com/mesonbuild/meson/wiki/Release%20notes%20for%200.38.0#support-for-arbitrary-test-setups doesn't seem to work either:

```
vg = find_program('valgrind')
add_test_setup('valgrind',
  exe_wrapper : [vg, '--error-exitcode=1', '--leak-check=full'],
  timeout_multiplier : 100)
```

```
$ /home/cassidy/dev/meson/mesontest.py -C build --setup valgrind
ninja: Entering directory `/home/cassidy/dev/gst/master/gst-build/build'
ninja: no work to do.
Traceback (most recent call last):
  File "/home/cassidy/dev/meson/mesontest.py", line 579, in <module>
    sys.exit(run(sys.argv[1:]))
  File "/home/cassidy/dev/meson/mesontest.py", line 575, in run
    return th.doit()
  File "/home/cassidy/dev/meson/mesontest.py", line 337, in doit
    self.run_tests(tests)
  File "/home/cassidy/dev/meson/mesontest.py", line 485, in run_tests
    self.drain_futures(futures, logfile, jsonlogfile)
  File "/home/cassidy/dev/meson/mesontest.py", line 504, in drain_futures
    self.print_stats(numlen, tests, name, result.result(), i, logfile, jsonlogfile)
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cassidy/dev/meson/mesontest.py", line 216, in run_single_test
    child_env.update(self.options.global_env.get_env(child_env))
AttributeError: 'dict' object has no attribute 'get_env'
```

**Comment by gdesmott** [comment]
Ah, the valgrind one works if I pass a `env` as well, but not without it.

**Comment by nirbheek** [comment]
Can you try the fixes in #1402?

**Comment by gdesmott** [comment]
I still get this error when trying to use valgrind without passing it an `env`

```
$ /home/cassidy/dev/meson/mesontest.py -C build --setup valgrind
ninja: Entering directory `/home/cassidy/dev/gst/master/gst-build/build'
ninja: no work to do.
Traceback (most recent call last):
  File "/home/cassidy/dev/meson/mesontest.py", line 595, in <module>
    sys.exit(run(sys.argv[1:]))
  File "/home/cassidy/dev/meson/mesontest.py", line 591, in run
    return th.doit()
  File "/home/cassidy/dev/meson/mesontest.py", line 346, in doit
    self.run_tests(tests)
  File "/home/cassidy/dev/meson/mesontest.py", line 497, in run_tests
    self.drain_futures(futures, logfile, jsonlogfile)
  File "/home/cassidy/dev/meson/mesontest.py", line 516, in drain_futures
    self.print_stats(numlen, tests, name, result.result(), i, logfile, jsonlogfile)
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cassidy/dev/meson/mesontest.py", line 217, in run_single_test
    child_env.update(self.options.global_env.get_env(child_env))
AttributeError: 'dict' object has no attribute 'get_env'
```

**Comment by nirbheek** [comment]
You will need to wipe your builddir and try. The problem is in the setup data, so that needs to be regenerated.
