### ISSUE TITLE
1.6.0rc1 regression: boost test fails (worked with 1.5.2)

### ISSUE THREAD

**Issue by DimStar77** [mesonbuild/meson#13763]
**Describe the bug**
As meson 1.6.0rc1 was released, I've injected this into openSUSE's GNOME:Next test repository (to get a good overview if any GNOME components would fail to build newly)

The GNOME builds are fine so far, but meson fails it's own test suite:
https://build.opensuse.org/package/live_build_log/GNOME:Next/meson:test/openSUSE_Factory/x86_64

** Fail log **
```
[  376s] Checking potential boost root /home/abuild/rpmbuild/BUILD/meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost
[  376s] Run-time dependency Boost found: NO (tried system)
[  376s] 
[  376s] test cases/frameworks/35 boost symlinks/meson.build:5:0: ERROR: Assert failed: expected to find a fake version of boost
[  376s] 
[  376s] 
[  376s]  
[  376s] 
[  376s] Traceback (most recent call last):
[  376s]   File "/usr/bin/meson", line 5, in <module>
[  376s]     sys.exit(main())
[  376s]              ^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 293, in main
[  376s]     return run(sys.argv[1:], launcher)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 284, in run
[  376s]     return CommandLineParser().run(args)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 195, in run
[  376s]     return errorhandler(e, command)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 34, in errorhandler
[  376s]     raise e
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 193, in run
[  376s]     return options.run_func(options)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 365, in run
[  376s]     app.generate()
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 188, in generate
[  376s]     return self._generate(env, capture, vslite_ctx)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 227, in _generate
[  376s]     intr.run()
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 3058, in run
[  376s]     super().run()
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
[  376s]     self.evaluate_codeblock(self.ast, start=1)
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
[  376s]     raise e
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
[  376s]     self.evaluate_statement(cur)
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 201, in evaluate_statement
[  376s]     return self.function_call(cur)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 528, in function_call
[  376s]     res = func(node, func_args, kwargs)
[  376s]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
[  376s]     return f(*nargs, **wrapped_kwargs)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreterbase/decorators.py", line 62, in wrapped
[  376s]     return f(*wrapped_args, **wrapped_kwargs)
[  376s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  376s]   File "/usr/lib/python3.11/site-packages/mesonbuild/interpreter/interpreter.py", line 746, in func_assert
[  376s]     raise InterpreterException('Assert failed: ' + message)
[  376s] mesonbuild.interpreterbase.exceptions.InterpreterException: Assert failed: expected to find a fake version of boost
```
**Expected behavior**
test suite passing

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?: *no*
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): *openSUSE Tumbleweed*
* what Python version are you using e.g. 3.8.0: *Python 3.11.10*
* what `meson --version`: *meson 1.6.0rc1*
* what `ninja --version` if it's a Ninja build: *Ninja 1.12.1*

**Comment by thesamesam** [comment]
See also the mysterious https://github.com/mesonbuild/meson/issues/13476.

**Comment by eli-schwartz** [comment]
Fails everywhere: https://buildd.debian.org/status/package.php?p=meson&suite=experimental

Also in gentoo packaging but I wasn't sure why and decided to just push the rc1 for now...

I did explore a bit though!

```
$ bsdtar -tvf /var/cache/distfiles/meson-1.5.2.tar.gz | grep 'boost symlinks'
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/boost/
-rw-r--r--  0 jpakkane jpakkane     70 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/boost/version.hpp
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x32-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x64-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/libboost_regex.so.0.3.0
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x32-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x64-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/libboost_python.so.0.3.0
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:34 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/include/
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/include/boost/
-rw-r--r--  0 jpakkane jpakkane     70 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/include/boost/version.hpp
drwxrwxr-x  0 jpakkane jpakkane      0 Sep 20 14:35 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x32-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x64-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x32-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x64-0_3.lib
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/libboost_python.so.0.3.0
-rw-r--r--  0 jpakkane jpakkane      0 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/boost/lib/libboost_regex.so.0.3.0
-rw-r--r--  0 jpakkane jpakkane    243 Jul 26 15:31 meson-1.5.2/test cases/frameworks/35 boost symlinks/meson.build
-rw-r--r--  0 jpakkane jpakkane     52 May 30 13:10 meson-1.5.2/test cases/frameworks/35 boost symlinks/nativefile.ini.in
```

```
$ bsdtar -tvf /var/cache/distfiles/meson-1.6.0rc1.tar.gz | grep 'boost symlinks'
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/boost/
-rw-rw-r--  0 jpakkane jpakkane     70 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/include/boost/version.hpp
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x32-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x64-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost/0.3.0/lib/libboost_regex.so.0.3.0
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x32-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x64-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/Cellar/boost-python/0.3.0/lib/libboost_python.so.0.3.0
drwxrwxr-x  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x32-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x64-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x32-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x64-0_3.lib
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/libboost_python.so.0.3.0
-rw-rw-r--  0 jpakkane jpakkane      0 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/boost/lib/libboost_regex.so.0.3.0
-rw-rw-r--  0 jpakkane jpakkane    243 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/meson.build
-rw-rw-r--  0 jpakkane jpakkane     52 Oct  6 17:24 meson-1.6.0rc1/test cases/frameworks/35 boost symlinks/nativefile.ini.in
```

In the 1.6.0rc1 distfile, there is no file: `test cases/frameworks/35 boost symlinks/boost/include/boost/version.hpp`

(nor the containing directories)

In git, it's a symlink. In previous releases, it was a real file. We already handle symlinks for another test case by manually creating them in run_project_tests.py (???).

These symlinks are load-bearing: they were added in #7909 as part of a change to the Boost dependency to actually treat symlinks as significant.

**Comment by jpakkane** [comment]
>  We already handle symlinks for another test case by manually creating them in run_project_tests.py (???).

And now I remember why. Setup.py nukes symlinks in its packages silently. They must not be in Git.
