### ISSUE TITLE
Meson throws exception updating subprojects

### ISSUE THREAD

**Issue by TELunus** [mesonbuild/meson#13814]
**Describe the bug**
Trying to run `"C:\Program Files\Meson\meson.exe" subprojects update` throws an exception saying "This is a Meson bug and should be reported!".  Note that my project is at `Z:\Projects\ModularGameEngine`, where `Z:` is a SMB share at IP address `192.168.86.21`

**To Reproduce**
meson.build:
```
project('ModularGameEngine', 'cpp',
        version : '1.0.0',
        default_options : ['warning_level=3', 'cpp_std=c++20'])

ModularGameEngine = executable('ModularGameEngine', 'main.cpp', install : true)

test('test', ModularGameEngine)
```

output from `"C:\Program Files\Meson\meson.exe" subprojects update`
```
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 193, in run
  File "mesonbuild\msubprojects.py", line 713, in run
  File "<frozen ntpath>", line 783, in relpath
ValueError: path is on mount '\\\\192.168.86.21\\fileroot', start on mount 'Z:'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Expected behavior**
Meson should successfully update subprojects, or at least fail gracefully (and ideally in that case tell me what went wrong and how I can move toward fixing the issue)

**system parameters**
* native build
* Windows 11
* Python 3.12.3
* meson 1.6.0
* ninja 1.12.0

**Comment by gregsskyles** [comment]
FWIW, this bug still exists in 1.10.0 (the latest version for which the Windows MSI was produced).
By running Meson from Python directly, a slightly more specific traceback error is produced:
```
G:\tmp\meson-test>python \repos\meson\meson.py subprojects update
Traceback (most recent call last):
  File "\\server\share\repos\meson\mesonbuild\mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\server\share\repos\meson\mesonbuild\msubprojects.py", line 723, in run
    source_dir = os.path.relpath(os.path.realpath(options.sourcedir))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 783, in relpath
ValueError: path is on mount '\\\\server\\share', start on mount 'G:'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```
