### ISSUE TITLE
unhandled exception with meson install command

### ISSUE THREAD

**Issue by jspanchu** [mesonbuild/meson#13817]
**Describe the bug**
`meson` fails to install `mesa` sometimes. I've seen this happen only once so far. Unable to reproduce.

Error
```
Traceback (most recent call last):
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/minstall.py", line 863, in run
    installer.do_install(datafilename)
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/minstall.py", line 546, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/minstall.py", line 763, in install_targets
    self.fix_rpath(outname, t.rpath_dirs_to_remove, install_rpath, final_path,
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/minstall.py", line 335, in fix_rpath
    depfixer.fix_rpath(*args, **kwargs)
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 489, in fix_rpath
    fix_elf(fname, rpath_dirs_to_remove, new_rpath, verbose)
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 388, in fix_elf
    with Elf(fname, verbose) as e:
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 133, in __init__
    self.parse_sections()
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 213, in parse_sections
    self.sections.append(SectionHeader(self.bf, self.ptrsize, self.is_le))
  File "/builds/gitlab-kitware-sciviz-ci/build/install/lib/python3.10/site-packages/mesonbuild/scripts/depfixer.py", line 90, in __init__
    self.sh_name = struct.unpack(self.Word, ifile.read(self.WordSize))[0]
struct.error: unpack requires a buffer of 4 bytes
CMake Error at /builds/gitlab-kitware-sciviz-ci/build/superbuild/sb-osmesa-install.cmake:48 (message):
  Failed with exit code 1

ninja: Entering directory `build'
[1/6] Generating src/git_sha1.h with a custom command
[1/2] Installing files.
Installing src/mapi/shared-glapi/libglapi.so.0.0.0 to /builds/gitlab-kitware-sciviz-ci/build/install/lib
Installing src/gallium/drivers/swr/libswrAVX2.so.0.0.0 to /builds/gitlab-kitware-sciviz-ci/build/install/lib

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-internal__install 
/builds/gitlab-kitware-sciviz-ci/build/install/bin/meson-real install --no-rebuild
ninja: build stopped: subcommand failed.
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
centos7
* what Python version are you using e.g. 3.8.0
3.10.13
* what `meson --version`
1.2.1
* what `ninja --version` if it's a Ninja build
1.10.2

**Comment by dcbaker** [comment]
That's a really old commit of Mesa if it still has swr!

If you can reproduce this, especially with the artifacts, I'd be interested in seeing them. My first thought is to ask whether the binaries are corrupt, which you could probably verify with readelf.

**Comment by bonzini** [comment]
No answer and probably not reproducible, closing.
