### ISSUE TITLE
ccache isn't supported with --cross_file option

### ISSUE THREAD

**Issue by fabio-porcedda** [mesonbuild/meson#1392]
To be able to use ccache with a cross compiler I've added the 'ccache' string in the cross_file:

[binaries]
c = ['ccache', '/usr/local/bin/mips-linux-gcc']

Meson fails using the above cross_file:

The Meson build system
Version: 0.38.1
Source dir: /ssd/lte/app-2/tcommon/src/oma-dm/kt_lib
Build dir: /ssd/lte/app-2/tcommon/src/oma-dm/kt_lib/build
Build type: cross build
Project name: kt_lib
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 286, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 160, in generate
    intr = interpreter.Interpreter(b, g)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1198, in __init__
    self.parse_project()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 111, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1611, in func_project
    self.add_languages(args[1:], True)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1727, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1652, in detect_compilers
    cross_comp = self.environment.detect_c_compiler(True)
  File "/usr/lib/python3.5/site-packages/mesonbuild/environment.py", line 371, in detect_c_compiler
    basename = os.path.basename(compiler).lower()
  File "/usr/lib64/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'list' object has no attribute 'rfind'

Any idea how to fix that?

Thanks
Fabio Porcedda

**Comment by fabio-porcedda** [comment]
IMHO I've a working solution for this problem, tomorrow i will make a pull request.

**Comment by nirbheek** [comment]
The basic issue, as I said on the PR, is that we expect a string there, and we don't actually check that it's a string, and throw a traceback if it's any other object. The solution would be to check if it's a string, and use it as a string, and if it's a list, use it as a list.

**Comment by jpakkane** [comment]
The function you probably want to use is `mesonlib.stringlistify`.
