### ISSUE TITLE
AttributeError: 'GnuCCompiler' object has no attribute '_has_wpedantic_support'

### ISSUE THREAD

**Issue by anonymix007** [mesonbuild/meson#13938]
**Describe the bug**
```
Found ninja-1.12.1 at /usr/bin/ninja
Traceback (most recent call last):                                                                                                                                                                           
  File "/workspace/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/msetup.py", line 365, in run
    app.generate()
  File "/workspace/meson/mesonbuild/msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/msetup.py", line 253, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/backend/ninjabackend.py", line 657, in generate
    self.generate_target(t)
  File "/workspace/meson/mesonbuild/backend/ninjabackend.py", line 1060, in generate_target
    o, s = self.generate_single_compile(target, src, False, [],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/backend/ninjabackend.py", line 2985, in generate_single_compile
    commands += self._generate_single_compile_target_args(target, compiler)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/backend/ninjabackend.py", line 2881, in _generate_single_compile_target_args
    commands = self.generate_basic_compiler_args(target, compiler)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/backend/backends.py", line 1001, in generate_basic_compiler_args
    commands += compiler.get_warn_args(T.cast('str', target.get_option(OptionKey('warning_level'))))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/meson/mesonbuild/compilers/mixins/gnu.py", line 565, in get_warn_args
    if not self._has_wpedantic_support and '-Wpedantic' in args:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GnuCCompiler' object has no attribute '_has_wpedantic_support'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
Build gstreamer with 
```
/workspace/meson/meson.py setup /workspace/build/x86_64-w64-mingw32/gstreamer -Dauto_features=disabled --default-library=static -Dgst-full=enabled -Dgst-full-target-type=static_library --prefix=/workspace/build/x86_64-w64-mingw32/root -Dgpl=enabled -Dvpx:vp8_encoder=enabled -Dvpx:vp8_decoder=enabled -Dvpx:vp9_encoder=enabled -Dvpx:vp9_decoder=enabled -Dgst-plugins-base:app=enabled -Dgst-plugins-base:audioconvert=enabled -Dgst-plugins-base:adder=enabled -Dgst-plugins-base:videoconvertscale=enabled -Dgst-plugins-base:opus=enabled -Dgst-plugins-bad:nvcodec=enabled -Dgst-plugins-bad:svtav1=enabled -Dgst-plugins-ugly:x264=enabled -Dgst-plugins-ugly:x264_libraries=enabled -Dgst-plugins-good:vpx=enabled --reconfigure --cross-file=/workspace/meson/cross/linux-mingw-w64-64bit.txt -Dgst-plugins-good:soup=disabled -Dgst-plugins-bad:d3d11=enabled -Dgst-plugins-bad:d3d12=enabled -Dgst-full-libraries=adder,app,audioconvert,coreelements,coretracers,nvcodec,opus,svtav1,videoconvertscale,vpx,x264,d3d11,d3d12
```
`linux-mingw-w64-64bit.txt` is patched to make `sys_root = ''` as setting it breaks pkg-config

**Expected behavior**
Everything should compile

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Cross build (MinGW)
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Arch Linux
* what Python version are you using e.g. 3.8.0
3.12.7
* what `meson --version`
1.6.99 (9f3f88feed74518f406839f4935b79a45d364540)
* what `ninja --version` if it's a Ninja build
1.12.1

**Comment by eli-schwartz** [comment]
Thanks for prerelease testing!

The relevant change is in https://github.com/mesonbuild/meson/commit/1b15bd034324a0ba173d4f8109471e2a7e338a66 and I can't spot an obvious bug in it. One thing that could have caused it is if you upgrade an existing build directory as we don't guarantee binary compatible for the coredata, but we only invalidate it and force reconfiguring from scratch when changing major.minor versions. Sonin that case it's possible to end up with an internal class that was frozen using a previous commit and didn't have the right attributes expected by a new commit.

**Comment by anonymix007** [comment]
I guess this is a good explanation why this happened. Should meson store its hash in coredata to never encounter issues of this kind anymore?

**Comment by eli-schwartz** [comment]
It's only relevant when running specific commits from meson git, currently we assume this is a bit DIY. It's difficult to know when checking out a different commit should matter vs when it shouldn't matter, as not every commit changes the pickled coredata.
