### ISSUE TITLE
Can't build project with make on WSL1.

### ISSUE THREAD

**Issue by leineg** [mesonbuild/meson#14017]
**Describe the bug**
Apparently meson tells me that when I try to make a ROM, it tells me utf-8 codec can't decode byte 0xe3 in position 185: invalid continuation byte

**To Reproduce**
[meson-log.txt](https://github.com/user-attachments/files/18159167/meson-log.txt)
```
danielferreira@DESKTOP-4NNGEV1:/mnt/c/decomps/pokeplatinum$ make
mkdir -p -- build
echo "[constants]" > build/root.ini
echo "root = '$PWD'" >> build/root.ini
rm -rf tools/cw/mwrap tools/cw/build
meson setup tools/cw/build tools/cw
The Meson build system
Version: 1.6.0
Source dir: /mnt/c/decomps/pokeplatinum/tools/cw
Build dir: /mnt/c/decomps/pokeplatinum/tools/cw/build
Build type: native build
Project name: metrowerks
Project version: undefined
C compiler for the host machine: cc (gcc 13.3.0 "cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C linker for the host machine: cc ld.bfd 2.42
C++ compiler for the host machine: c++ (gcc 13.3.0 "c++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C++ linker for the host machine: c++ ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.1 at /usr/bin/ninja
meson compile -C tools/cw/build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /mnt/c/decomps/pokeplatinum/tools/cw/build
ninja: Entering directory `/mnt/c/decomps/pokeplatinum/tools/cw/build'
[100% 2/2] Linking target mwrap
install -m755 tools/cw/build/mwrap tools/cw/mwrap
rm -rf tools/cw/build
BUILD="build"; \
MWCONFIG=/mnt/c/decomps/pokeplatinum/build/.mwconfig tools/cw/mwrap -conf \
         -path_unx "$PWD" \
         -path_win "$(wslpath -w "$PWD")" \
         -path_build_unx "$BUILD" \
         -path_build_win "$(wslpath -w "$PWD")"
MWCONFIG=/mnt/c/decomps/pokeplatinum/build/.mwconfig meson setup \
         --wrap-mode=nopromote \
         --native-file=meson/native.ini \
         --native-file=build/root.ini \
         --cross-file=meson/cross_unix.ini \
         --cross-file=build/root.ini \
         -- build
The Meson build system
Version: 1.6.0
Source dir: /mnt/c/decomps/pokeplatinum
Build dir: /mnt/c/decomps/pokeplatinum/build
Build type: cross build
Project name: pokeplatinum
Project version: 1.0
Nasm compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwasmarm (mwasmarm 3.0.4)
Nasm linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
C++ compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
C++ linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
Nasm compiler for the build machine: nasm (nasm 2.16.01)
Nasm linker for the build machine: gcc ld.bfd 2.42
C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C linker for the build machine: gcc ld.bfd 2.42
C++ compiler for the build machine: g++ (gcc 13.3.0 "g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C++ linker for the build machine: g++ ld.bfd 2.42
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: arm
Host machine cpu: arm
Target machine cpu family: arm
Target machine cpu: arm
Found pkg-config: NO
Found CMake: NO
Run-time dependency nitrosdk found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency NitroSDK
Initialized empty Git repository in /mnt/c/decomps/pokeplatinum/subprojects/NitroSDK-4.2.30001/.git/
remote: Enumerating objects: 680, done.
remote: Counting objects: 100% (680/680), done.
remote: Compressing objects: 100% (575/575), done.
remote: Total 680 (delta 64), reused 667 (delta 64), pack-reused 0 (from 0)
Receiving objects: 100% (680/680), 734.62 KiB | 4.30 MiB/s, done.
Resolving deltas: 100% (64/64), done.
From https://github.com/Nomura-RH/NitroSDK
 * branch            0082ec3dd5e951a7ee7c2067595a4fa0e9496d36 -> FETCH_HEAD
HEAD is now at 0082ec3 Merge pull request #2 from PikalaxALT/patch-1

Executing subproject NitroSDK

NitroSDK| Project name: NitroSDK
NitroSDK| Project version: 4.2.30001
NitroSDK| C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
NitroSDK| C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
NitroSDK| C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
NitroSDK| C linker for the build machine: gcc ld.bfd 2.42
NitroSDK| Program gen_fx_const.py found: YES (/mnt/c/decomps/pokeplatinum/subprojects/NitroSDK-4.2.30001/gen/nitro/fx/gen_fx_const.py)
NitroSDK| Program flex found: YES (/usr/bin/flex)
NitroSDK| Program bison found: YES (/usr/bin/bison)
NitroSDK| Build targets in project: 31
NitroSDK| Subproject NitroSDK finished.

Dependency NitroSDK found: YES 4.2.30001 (overridden)
Run-time dependency nitrosystem found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency NitroSystem
Initialized empty Git repository in /mnt/c/decomps/pokeplatinum/subprojects/NitroSystem-071126.1/.git/
remote: Enumerating objects: 308, done.
remote: Counting objects: 100% (308/308), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 308 (delta 20), reused 301 (delta 20), pack-reused 0 (from 0)
Receiving objects: 100% (308/308), 275.07 KiB | 2.17 MiB/s, done.
Resolving deltas: 100% (20/20), done.
From https://github.com/Nomura-RH/NitroSystem
 * branch            507acff1585505bdac3f996551ca5123f8408073 -> FETCH_HEAD
HEAD is now at 507acff Fix mistakes in libnnsmcs source names

Executing subproject NitroSystem

NitroSystem| Project name: NitroSystem
NitroSystem| Project version: 071126.1
NitroSystem| C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
NitroSystem| C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
NitroSystem| C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
NitroSystem| C linker for the build machine: gcc ld.bfd 2.42
NitroSystem| Dependency NitroSDK found: YES 4.2.30001 (overridden)
NitroSystem| Build targets in project: 37
NitroSystem| Subproject NitroSystem finished.

Dependency NitroSystem found: YES 071126.1 (overridden)
Run-time dependency nitrowifi found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency NitroWiFi
Initialized empty Git repository in /mnt/c/decomps/pokeplatinum/subprojects/NitroWiFi-2.1.30003/.git/
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 89 (delta 3), reused 85 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (89/89), 152.90 KiB | 1.34 MiB/s, done.
From https://github.com/Nomura-RH/NitroWiFi
 * branch            0d74e5de275952680962237da9d592e80815679a -> FETCH_HEAD
HEAD is now at 0d74e5d Merge pull request #1 from mid-kid/main

Executing subproject NitroWiFi

NitroWiFi| Project name: NitroWiFi
NitroWiFi| Project version: 2.1.30003
NitroWiFi| C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
NitroWiFi| C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
NitroWiFi| C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
NitroWiFi| C linker for the build machine: gcc ld.bfd 2.42
NitroWiFi| Dependency NitroSDK found: YES 4.2.30001 (overridden)
NitroWiFi| Build targets in project: 44
NitroWiFi| Subproject NitroWiFi finished.

Dependency NitroWiFi found: YES 2.1.30003 (overridden)
Run-time dependency nitrodwc found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency NitroDWC
Initialized empty Git repository in /mnt/c/decomps/pokeplatinum/subprojects/NitroDWC-2.2.30008/.git/
remote: Enumerating objects: 226, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 226 (delta 3), reused 220 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (226/226), 1.74 MiB | 6.98 MiB/s, done.
Resolving deltas: 100% (3/3), done.
From https://github.com/Nomura-RH/NitroDWC
 * branch            8220c8bdec2e8b5252ee710cf3cc0c148228a03a -> FETCH_HEAD
HEAD is now at 8220c8b Merge pull request #2 from mid-kid/main

Executing subproject NitroDWC

NitroDWC| Project name: NitroDWC
NitroDWC| Project version: 2.2.30008
NitroDWC| C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
NitroDWC| C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
NitroDWC| C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
NitroDWC| C linker for the build machine: gcc ld.bfd 2.42
NitroDWC| Dependency NitroSDK found: YES 4.2.30001 (overridden)
NitroDWC| Dependency NitroSystem found: YES 071126.1 (overridden)
NitroDWC| Dependency NitroWiFi found: YES 2.1.30003 (overridden)
NitroDWC| Build targets in project: 64
NitroDWC| Subproject NitroDWC finished.

Dependency NitroDWC found: YES 2.2.30008 (overridden)
Run-time dependency libvct found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libvct
Initialized empty Git repository in /mnt/c/decomps/pokeplatinum/subprojects/libvct-1.3.1/.git/
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 0), reused 7 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 71.22 KiB | 828.00 KiB/s, done.
From https://github.com/Nomura-RH/libvct
 * branch            dd9f89d7c0a52e74a3c4b25552ea05cdc127a011 -> FETCH_HEAD
HEAD is now at dd9f89d Merge pull request #1 from mid-kid/main

Executing subproject libvct

libvct| Project name: libvct
libvct| Project version: 1.3.1
libvct| C compiler for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm (mwccarm 1.0.2)
libvct| C linker for the host machine: /mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwldarm mwldarm 1.0.2
libvct| C compiler for the build machine: gcc (gcc 13.3.0 "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
libvct| C linker for the build machine: gcc ld.bfd 2.42
libvct| Dependency NitroSDK found: YES 4.2.30001 (overridden)
libvct| Build targets in project: 65
libvct| Subproject libvct finished.

Dependency libvct found: YES 1.3.1 (overridden)
Traceback (most recent call last):
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/msetup.py", line 365, in run
    app.generate()
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/msetup.py", line 227, in _generate
    intr.run()
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 3063, in run
    super().run()
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 205, in evaluate_statement
    self.assignment(cur)
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 642, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 806, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 806, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 806, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 85, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 103, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 1825, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 355, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 88, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/dependencies/detect.py", line 114, in find_external_dependency
    d = c()
        ^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/dependencies/misc.py", line 440, in __init__
    if not self.clib_compiler.has_header('openssl/ssl.h', '', env)[0]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/compilers/mixins/clike.py", line 351, in has_header
    return self.compiles(code, env, extra_args=extra_args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/compilers/compilers.py", line 1304, in compiles
    with self._build_wrapper(code, env, extra_args, dependencies, mode, disable_cache=disable_cache) as p:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/compilers/compilers.py", line 1290, in _build_wrapper
    with self.cached_compile(code, env.coredata, extra_args=args, mode=mode, temp_dir=env.scratch_dir) as r:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/compilers/compilers.py", line 867, in cached_compile
    with self.compile(code, extra_args=extra_args, mode=mode, want_output=False, temp_dir=temp_dir) as p:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/compilers/compilers.py", line 838, in compile
    p, stdo, stde = Popen_safe_logged(command_list, msg='Command line', cwd=tmpdirname, env=os_env)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/utils/universal.py", line 1588, in Popen_safe_logged
    p, o, e = Popen_safe(args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danielferreira/.local/lib/python3.12/site-packages/mesonbuild/utils/universal.py", line 1546, in Popen_safe
    o, e = p.communicate(write)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 2153, in _communicate
    stdout = self._translate_newlines(stdout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1086, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 185: invalid continuation byte

meson.build:112:16: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
make: *** [Makefile:91: build/build.ninja] Error 2
```

**Expected behavior**
Should build the rom without errors... Here is the repo https://github.com/pret/pokeplatinum.git

**system parameters**
*Plain native build I think
* Windows 11 23H2 22631.4602
* Python 3.12.8
*Meson 1.6.0

**Comment by eli-schwartz** [comment]
```
Pkg-config for machine host machine not found. Giving up.
Running compile:
Working directory:  /mnt/c/decomps/pokeplatinum/build/meson-private/tmpguzpvtkg
Code:

        #ifdef __has_include
         #if !__has_include("openssl/ssl.h")
          #error "Header 'openssl/ssl.h' could not be found"
         #endif
        #else
         #include <openssl/ssl.h>
        #endif
-----------
Command line: `/mnt/c/decomps/pokeplatinum/tools/cw/mwrap mwccarm /mnt/c/decomps/pokeplatinum/build/meson-private/tmpguzpvtkg/testfile.cpp -gccinc -E -gccinc` -> 'utf-8' codec can't decode byte 0xe3 in position 185: invalid continuation byte
```

Interesting... Presumably mwccarm is emitting output for a different locale.

**Comment by leineg** [comment]
Is there a way to fix that eli?

**Comment by lhearachel** [comment]
As a thought: I wondering if this is an issue with the user's locale... our (the project's) other users have a system locale configured to `en_US`; for example, here is my `locale` output (on Arch Linux):

```shell
> locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

@leineg provided the following `locale` output in our support channels:

```shell
> locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

My understanding of locale-configuration is very limited, but I gathered from some googling that `C` should default to the user's system-configured locale. I know from other interactions that this user's PC displays directory strings in a non-English language.

**Comment by eli-schwartz** [comment]
C.UTF-8 is actually intended to be a well-defined unicode-aware enhancement to the legacy 1980s idea that only US ascii exists. It is different from simply standardizing on en_US.UTF-8 because e.g. you get portable handling of collation rules.

Its usefulness derives from the fact that it is guaranteed to be compatible with UTF-8 encoding/decoding, unlike `LC_ALL=C` which in addition to prompting applications to avoid printing gettext-localized strings for other languages, also basically ensures you're in for a really bad time if you have actual UTF-8 data to process.

Note that C.UTF-8 is actually two things, not one thing. Likewise, en_US.UTF-8 is two things, not one thing. It is a *language* (C or en_US) and an *encoding* (UTF-8, usually, and again: `LC_ALL=C` is awkward here).

Given we are still talking what is ultimately a UTF-8 locale, I see nothing wrong with having that output from `locale`. If I had to guess, though, I would guess that mccarm is printing non-ASCII output in some form that is *not* UTF-8 (C or otherwise).

> I know from other interactions that this user's PC displays directory strings in a non-English language.

A non-English language implies a language that uses more than 7-bit ASCII characters, which means that it becomes important that all programs agree on how to encode those characters. If you were to limit yourself to just 7-bit ASCII, and by extension limit yourself to English, then the compatibility story is pretty good because your average encoding makes sure that those 127 codepoints are universally compatible.

So yeah. Entirely plausible that mwccarm is actually printing those directory paths themselves, and using the wrong encoding (not respecting the configured locale).

**Comment by leineg** [comment]
```
leinadferreira@DESKTOP-4NNGEV1:~$ export LC_ALL="en_US.UTF-8"
leinadferreira@DESKTOP-4NNGEV1:~$ locale
LANG=en_US.UTF8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
I did this it still using the wrong encoding probably...

**Comment by lhearachel** [comment]
I did some digging and found that a previous user reported a similar error, but we never determined a resolution; I know that that user also operates outside of the Anglosphere, so I do think that the non-English-ness is to blame here (especially given @eli-schwartz's explanation above).

I worry that this might be down to altering the system locale. I would rather *not* ask our users to do that, but if it's something that we must mandate to make use of our compilation chain, then that may be all there is to it...

**Comment by eli-schwartz** [comment]
If there is some way to force the compiler to emit UTF-8 we could do that, I guess?

Or alternatively if we can guarantee that mwccarm always emits a very specific encoding, it is theoretically possible to update the compiler support for mwccarm so that we use the (in)correct locale instead of the system locale.

**Comment by leineg** [comment]
Woah went to the time and language>language & region, windows display language switched to English (US) and now that error does not appear.
![image](https://github.com/user-attachments/assets/1482b078-99bc-4574-b2e9-8580a83d0f0e)
