### ISSUE TITLE
`run_unittests.py` test failures on master

### ISSUE THREAD

**Issue by thesamesam** [mesonbuild/meson#14029]
**Describe the bug**

The tests run by `run_unittests.py` seem to fail on master.

**To Reproduce**

`./run_unittests.py --backend=ninja`

Seen in CI at:
* https://github.com/mesonbuild/meson/actions/runs/12422310861/job/34683756331?pr=14025
* https://github.com/mesonbuild/meson/actions/runs/12422310861/job/34683755882?pr=14025

```
Program /usr/bin/g-ir-compiler found: YES (/usr/bin/g-ir-compiler)

test cases/frameworks/7 gnome/gir/dep1/dep2/meson.build:10:16: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

Stderr:

Traceback (most recent call last):
  File "/meson/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/meson/mesonbuild/msetup.py", line 365, in run
    app.generate()
    ~~~~~~~~~~~~^^
  File "/meson/mesonbuild/msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/meson/mesonbuild/msetup.py", line 227, in _generate
    intr.run()
    ~~~~~~~~^^
  File "/meson/mesonbuild/interpreter/interpreter.py", line 3069, in run
    super().run()
    ~~~~~~~~~~~^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreter/interpreter.py", line 2482, in func_subdir
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreter/interpreter.py", line 2482, in func_subdir
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 527, in function_call
    res = func(node, func_args, kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreter/interpreter.py", line 2482, in func_subdir
    self.evaluate_codeblock(codeblock)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 194, in evaluate_codeblock
    raise e
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 186, in evaluate_codeblock
    self.evaluate_statement(cur)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    self.assignment(cur)
    ~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 641, in assignment
    value = self.evaluate_statement(node.value)
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 206, in evaluate_statement
    return self.method_call(cur)
           ~~~~~~~~~~~~~~~~^^^^^
  File "/meson/mesonbuild/interpreterbase/interpreterbase.py", line 556, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/meson/mesonbuild/interpreter/interpreterobjects.py", line 885, in method_call
    ret = method(state, args, kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 237, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/meson/mesonbuild/interpreterbase/decorators.py", line 556, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/meson/mesonbuild/modules/gnome.py", line 1218, in generate_gir
    scan_target = self._make_gir_target(
        state, girfile, scan_command, generated_files, depends,
        # We have to cast here because mypy can't figure this out
        T.cast('T.Dict[str, T.Any]', kwargs))
  File "/meson/mesonbuild/modules/gnome.py", line 981, in _make_gir_target
    run_env = PkgConfigInterface.get_env(state.environment, MachineChoice.HOST, uninstalled=True)
  File "/meson/mesonbuild/dependencies/pkgconfig.py", line 78, in get_env
    return cli._get_env(uninstalled) if cli else EnvironmentVariables()
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/meson/mesonbuild/dependencies/pkgconfig.py", line 261, in _get_env
    uninstalled_path = Path(self.env.get_build_dir(), 'meson-uninstalled').as_posix()
                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/pathlib/_local.py", line 503, in __init__
    super().__init__(*args)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib64/python3.13/pathlib/_local.py", line 132, in __init__
    raise TypeError(
    ...<2 lines>...
        f"not {type(path).__name__!r}")
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'

=============================== warnings summary ===============================
unittests/allplatformstests.py: 200 warnings
unittests/datatests.py: 6 warnings
unittests/failuretests.py: 6 warnings
unittests/internaltests.py: 20 warnings
unittests/linuxliketests.py: 59 warnings
unittests/machinefiletests.py: 68 warnings
unittests/pythontests.py: 4 warnings
unittests/rewritetests.py: 12 warnings
unittests/subprojectscommandtests.py: 3 warnings
  /meson/mesonbuild/utils/universal.py:1648: EncodingWarning: UTF-8 Mode affects locale.getpreferredencoding(). Consider locale.getencoding() instead.
    encoding = locale.getpreferredencoding()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED unittests/linuxliketests.py::LinuxlikeTests::test_old_gnome_module_codepaths - RuntimeError: Configure failed
===== 1 failed, 484 passed, 65 skipped, 378 warnings in 182.05s (0:03:02) ======
```

**Comment by thesamesam** [comment]
cc @Jan200101 @dcbaker

**Comment by thesamesam** [comment]
https://github.com/mesonbuild/meson/pull/14027 (-> https://github.com/mesonbuild/meson/actions/runs/12422952501/job/34685632877?pr=14027) shows my guess for blame was wrong.

**Comment by thesamesam** [comment]
Seems to pass now?
