### ISSUE TITLE
Unhandled python exception

### ISSUE THREAD

**Issue by gonggy** [mesonbuild/meson#14059]
**Describe the bug**

```
The Meson build system
Version: 1.0.1
Source dir: /home/zhiyu//gitsall/linux-enable-ir-emitter
Build dir: /home/zhiyu/gitsall/linux-enable-ir-emitter/build
Build type: native build
Project name: linux-enable-ir-emitter
Project version: 6.0.6-dev
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 310, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 187, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 231, in _generate
    intr.run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 2875, in run
    super().run()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 147, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 172, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 165, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 178, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 460, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 590, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 2287, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 172, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 165, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 180, in evaluate_statement
    self.assignment(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 573, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 178, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/interpreterbase.py", line 460, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 784, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 784, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 784, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 5 more times]
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 109, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase/decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/interpreter.py", line 1685, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 354, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 87, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/detect.py", line 113, in find_external_dependency
    d = c()
        ^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/pkgconfig.py", line 71, in __init__
    self._set_cargs()
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/pkgconfig.py", line 220, in _set_cargs
    ret, out, err = self._call_pkgbin(['--cflags', self.name], env=env)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/pkgconfig.py", line 174, in _call_pkgbin
    cache[(self.pkgbin, targs, fenv)] = self._call_pkgbin_real(args, env)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/dependencies/pkgconfig.py", line 124, in _call_pkgbin_real
    p, out, err = Popen_safe(cmd, env=env)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/utils/universal.py", line 1460, in Popen_safe
    o, e = p.communicate(write)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2097, in _communicate
    stdout = self._translate_newlines(stdout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1084, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 15: invalid continuation byte

src/meson.build:4:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

```
------------------------------------------------------------------------------------------------------------------------------------------

**system parameters**
* just a plain native build
* operating system:debian12  kernel:6.12.3-surface-2
* Python version:3.11
* meson --version:1.01
* ninja --version:1.11.1

**Comment by gonggy** [comment]
update by now: 
LC_ALL=C meson setup build --sysconfdir /etc --prefer-static --pkg-config-path=$(find.github -name "pkgconfig")
I solved the encoding problem with the above command，but I go into dependency hell，such as yml-cpp,gtk+-3.0,also
I almost solved them by apt installing,except "argspase",which is a defult library of python3.the pkg-config can't find it.

**Comment by gonggy** [comment]
update by now:
zhiyu@mydebian12:~/gitsall/linux-enable-ir-emitter$ LC_ALL=C meson setup build --sysconfdir /etc --prefer-static --pkg-config-path=/usr/lib/x86_64-linux-gnu/pkgconfig
The Meson build system
Version: 1.0.1
Source dir: /home/zhiyu/下载/gits/linux-enable-ir-emitter
Build dir: /home/zhiyu/下载/gits/linux-enable-ir-emitter/build
Build type: native build
Project name: linux-enable-ir-emitter
Project version: 6.0.6-dev
C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Debian 12.2.0-14) 12.2.0")
C++ linker for the host machine: c++ ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency opencv4 found: YES 4.6.0
Run-time dependency gtk+-3.0 found: YES 3.24.38
Run-time dependency yaml-cpp found: YES 0.7.0
Found CMake: /usr/bin/cmake (3.25.1)
**Run-time dependency argparse found: NO (tried pkgconfig and cmake)**

src/meson.build:7:0: ERROR: Dependency "argparse" not found, tried pkgconfig and cmake

I solved the encoding problem, but I am confused by this Dependency Hell.  it's a defult library of python3,confused.

**Comment by eli-schwartz** [comment]
> I solved the encoding problem, but I am confused by this Dependency Hell. it's a defult library of python3,confused.

You're trying to build a C++ application, which has nothing to do with python3.

python3 has an "argparse" module, but "linux-enable-ir-emitter" doesn't use it. It does use this C++ library which is *also* called "argparse": https://github.com/p-ranav/argparse

**Comment by gonggy** [comment]
> python3 has an "argparse" module, but "linux-enable-ir-emitter" doesn't use it. It does use this C++ library which is _also_ called "argparse": https://github.com/p-ranav/argparse

OH!!! I was so stupid,its cmake.thanks,very much.

**Comment by eli-schwartz** [comment]
It's also available as a meson wrap at https://wrapdb.mesonbuild.com/
