### ISSUE TITLE
Specifying own stdlib in cross file results in error

### ISSUE THREAD

**Issue by ernestask** [mesonbuild/meson#1553]
Using c_stdlib in a cross file results in an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 298, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 172, in generate
    intr = interpreter.Interpreter(b, g)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1232, in __init__
    self.parse_project()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 111, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1655, in func_project
    self.check_cross_stdlibs()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1374, in check_cross_stdlibs
    subproj = self.do_subproject(projname, {})
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1529, in do_subproject
    self.build_def_files += subi.build_def_files
AttributeError: 'Interpreter' object has no attribute 'build_def_files'
```

This is reproducible with `cross/ownstdlib.txt` from the Meson tree and a couple of trivial build definition files:
`project('foo', 'c')` - `meson.build`
`project('mylibc', 'c')` - `subprojects/mylibc/meson.build`

**Comment by denizzzka** [comment]
This issue is still here.
Maybe remove `c_stdlib` option at all?

```
Traceback (most recent call last):
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4165, in run
    super().run()
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1064, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
    return self.method_call(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 798, in method_call
    obj = self.evaluate_statement(invokable)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2538, in func_subproject
    return self.do_subproject(dirname, 'meson', kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2621, in do_subproject
    raise e
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2605, in do_subproject
    return self._do_subproject_meson(dirname, subdir, default_options, kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2632, in _do_subproject_meson
    subi.run()
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4165, in run
    super().run()
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1064, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3374, in func_library
    return self.build_library(node, args, kwargs)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4309, in build_library
    return self.build_target(node, args, kwargs, StaticLibraryHolder)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4362, in build_target
    self.add_cross_stdlib_info(target)
  File "/home/denizzz/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4402, in add_cross_stdlib_info
    target.add_deps(self.build.stdlibs.host[l])
KeyError: 'c'
```

**Comment by phillipjohnston** [comment]
I just want to confirm that I've been using this functionality successfully for a while on a number of projects. Currently using 0.56.0_rc1

```
[properties]
c_stdlib = ['libc', 'libc_dep']
```

**Comment by xclaesse** [comment]
Let's close this then. There has been changes around this in 0.56, please open a bug if there are still issues.
