### ISSUE TITLE
Fails instead of adding dependency on "non-source" file

### ISSUE THREAD

**Issue by ximion** [mesonbuild/meson#1572]
Hi!
The documentation on the `executable` target says:

> These source files can be sources, objects, libraries, or any other file. Meson will automatically categorize them based on the extension and use them accordingly. For instance, sources (.c, .cpp, .vala, .rs, etc) will be compiled, objects (.o, .obj) and libraries (.so, .dll, etc) will be linked, and all other files (headers, unknown extensions, etc) will be ignored. Meson will still create a build-time dependency on all source files, which is useful with generated files.

In practice, however, if I try to add files, Meson fails with
```Python
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 286, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 170, in generate
    g.generate(intr)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 193, in generate
    self.generate_target(t, outfile)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 431, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 1814, in generate_single_compile
    compiler = get_compiler_for_source(target.compilers.values(), src)
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 180, in get_compiler_for_source
    raise RuntimeError('No specified compiler can handle file {!s}'.format(src))
RuntimeError: No specified compiler can handle file template.dt
FAILED: build.ninja
```

Using this is nice for D's `import()` statement. I have a testcase attached, which works with the LDC compiler if you remove the `template.dt` file from the `executable` target source files (I haven't tested this with GDC, the `-J` flag should maybe be abstracted away by Meson).

Expected result: The example builds even with the "unknown" `template.dt` file being present as source.
See [mtest.tar.gz](https://github.com/mesonbuild/meson/files/900662/mtest.tar.gz)

Cheers,
    Matthias

**Comment by nirbheek** [comment]
I have a patch to fix the traceback, but to get the proper behaviour (i.e., source files that use `template.dt` get rebuilt on change), we'd need depfile support in ldc which is missing upstream.

**Comment by ximion** [comment]
> I have a patch to fix the traceback, but to get the proper behaviour (i.e., source files that use template.dt get rebuilt on change), we'd need depfile support in ldc which is missing upstream.

Jup, I know - this is reported upstream as https://github.com/ldc-developers/ldc/issues/1802 but so far nothing happened there. GDC has fixed it's depfile support though, I will submit a patch to Meson as soon as I can test it.

**Comment by bonzini** [comment]
Based on the discussion in #1573, what may be acceptable is some kind of `depend_files` added to build targets, but blindly accepting non-source files was rejected.

For D specifically, this now works with `ldc` (which has `-makedeps`) even if `template.dt` is not added to the sources but not with `gdc`. Closing as a gdc bug.
