### ISSUE TITLE
backtrace when using non-found prog in command

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1583]
```
project('meson4', 'c')

git = find_program('gita', required : false)
etags = find_program('etags', required : false)

all_files = run_command(
    git,
    ['--git-dir=@0@/.git'.format(meson.source_root()),
     'ls-files',
     ':/*.[ch]'])
all_files = files(all_files.stdout().split())

custom_target(
  'TAGS',
  output : 'TAGS',
  input : all_files,
  command : [etags, '-o', '@OUTPUT@'] + all_files)
```

```bash
$ meson build
The Meson build system
Version: 0.40.0.dev1
Source dir: /home/zbyszek/src/meson/meson4
Build dir: /home/zbyszek/src/meson/meson4/build
Build type: native build
Project name: meson4
Native c compiler: ccache cc (gcc 6.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program gita found: NO
Program etags found: YES (/usr/bin/etags)
Traceback (most recent call last):
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 298, in run
    app.generate()
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 180, in generate
    intr.run()
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreter.py", line 2529, in run
    super().run()
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 125, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 153, in evaluate_statement
    return self.assignment(cur)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreterbase.py", line 372, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreter.py", line 1493, in func_run_command
    self.subdir, in_builddir)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreter.py", line 77, in __init__
    pc, self.stdout, self.stderr = self.run_command(command_array, source_dir, build_dir, subdir, in_builddir)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/interpreter.py", line 95, in run_command
    mlog.debug('Running command:', ' '.join(command_array))
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by dcbaker** [comment]
Fixed in fdd0675661
