### ISSUE TITLE
osx test-case "2 Library version" and "common 4/6" failing for xcode-backend

### ISSUE THREAD

**Issue by kalmiya** [mesonbuild/meson#1597]
Running unittests fails in xcodebackend.py for 
                if isinstance(target, build.SharedLibrary):
                    ldargs = ['-dynamiclib', '-Wl,-headerpad_max_install_names'] + dep_libs
                    install_path = os.path.join(self.environment.get_build_dir(), target.subdir, buildtype)
                    dylib_version = target.version <=

with 
Failed test (without install) during configure: 'test cases/common/4 shared'
Reason: Generating the build system failed.
Failed test (without install) during configure: 'test cases/common/6 linkshared'
Reason: Generating the build system failed.

I'm guessing it should be target.**so**version ( or **lt**version? ) - changing that lets common 4/6 pass. 

Tried to further investigate by manually Triggering "/test cases/osx/2 library versions" using 
"python3 ~/dev/meson.git/meson.py --backend=xcode build" which is a more extensive testscenario for versioning, but it results in several issues:

Traceback (most recent call last):
  File "/Users/blackbox/dev/meson-kalmiya.git/mesonbuild/mesonmain.py", line 298, in run
    app.generate()
  File "/Users/blackbox/dev/meson-kalmiya.git/mesonbuild/mesonmain.py", line 182, in generate
    g.generate(intr)
  File "/Users/blackbox/dev/meson-kalmiya.git/mesonbuild/backend/xcodebackend.py", line 90, in generate
    self.generate_pbx_build_file()
  File "/.../mesonbuild/backend/xcodebackend.py", line 251, in generate_pbx_build_file
    fileref = self.filemap[s]
KeyError: 'exe.orig.c'

This key is not in the dictionary because in "def generate_filemap(self)" there is a check like this:

                print (' - t.sources: %s' %s)
                **if isinstance(s, mesonlib.File):**
                    s = os.path.join(s.subdir, s.fname)
                    self.filemap[s] = self.gen_id()
                _else: # let's see if this triggers
                    print (' -> not-a-file; so what is it?')_

with the following output:

generate_filemap()
- targetname: some@sha
 - t.sources: lib.c
- targetname: noversion@sha
 - t.sources: lib.c
- targetname: onlyversion@sha
 - t.sources: lib.c
- targetname: onlysoversion@sha
 - t.sources: lib.c
- targetname: library-dependency-hack@cus
 - t.sources: exe.orig.c
 -> not-a-file; so what is it?

After that, it'll fail in the same function here:
            for o in t.objects:
with
  File "/.../backend/xcodebackend.py", line 126, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'

For "t.sources:" being "exe.orig.c"

So that thing is "something else" and that fails throughout the entire system. I don't know enough of the entire system and how it's intended to work, so I can only debug this up to a certain point :(

**Comment by nacho4d** [comment]
FYI  
In recent builds: tests from `1 trivial` to `22 target arg` all pass correctly. However there are some **other** tests that still cause `AttributeError: 'CustomTarget' object has no attribute 'objects'` which is the same message as https://github.com/mesonbuild/meson/issues/1957

Perhaps this issue can be closed and future work should be in #1957 ?
(I am investigating and trying to fix various things but so far I do one or two fixes per week and there are more than 200 tests in total, this might take some time ... :p )

**Comment by bonzini** [comment]
> I'm guessing it should be target.soversion ( or ltversion? ) - changing that lets common 4/6 pass.

This was fixed in 1d0169f4e722716d2436001e1f39bd55cf04c261.

>  AttributeError: 'CustomTarget' object has no attribute 'objects'

This was fixed in fa947e6d75

Closing, though probably someone with a mac should open an issue with all the (probably many) testsuite failures.
