### ISSUE TITLE
AttributeError: 'OptionInterpreter' object has no attribute 'get_variable'

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#160]
```python
Traceback (most recent call last):
  File "/home/brain/git/mesonbuild/meson/meson.py", line 194, in run
    app.generate()
  File "/home/brain/git/mesonbuild/meson/meson.py", line 134, in generate
    intr = interpreter.Interpreter(b)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 781, in __init__
    oi.process(option_file)
  File "/home/brain/git/mesonbuild/meson/optinterpreter.py", line 124, in process
    raise e
  File "/home/brain/git/mesonbuild/meson/optinterpreter.py", line 119, in process
    self.evaluate_statement(cur)
  File "/home/brain/git/mesonbuild/meson/optinterpreter.py", line 161, in evaluate_statement
    (posargs, kwargs) = self.reduce_arguments(node.args)
  File "/home/brain/git/mesonbuild/meson/optinterpreter.py", line 152, in reduce_arguments
    reduced_kw[key] = self.reduce_single(a)
  File "/home/brain/git/mesonbuild/meson/optinterpreter.py", line 128, in reduce_single
    return self.get_variable(arg.value)
AttributeError: 'OptionInterpreter' object has no attribute 'get_variable'
```

**Comment by ignatenkobrain** [comment]
option('local_build', type : 'boolean', value : yes)

**Comment by ignatenkobrain** [comment]
Wrong error
