### ISSUE TITLE
tracebacks on installation

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#1600]
With the following simple build file:
```meson
project('meson5', 'c')

meson.add_install_script('no-such-file.sh',
                         'a',
                         'b')
```
I get
```python
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 306, in run
    do_install(datafilename)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 129, in do_install
    run_install_script(d)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 193, in run_install_script
    name = ' '.join(script + args)
TypeError: sequence item 0: expected str instance, NoneType found
```

In a different slightly more complicated case I get the following traceback:
```python
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 306, in run
    do_install(datafilename)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 129, in do_install
    run_install_script(d)
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 186, in run_install_script
    'MESONINTROSPECT': d.mesonintrospect}
AttributeError: 'InstallData' object has no attribute 'mesonintrospect'
```

**Comment by nirbheek** [comment]
You need to wipe your builddir and re-configure.

This is because you're running a git version, and we changed the format of one of Meson's internal pickles (used for storing and passing state), so Meson is expecting the new version. Normally this isn't a problem because you're required to wipe the builddir when upgrading to a new version anyway.

**Comment by nirbheek** [comment]
Actually, what's happening in your case is different. Look at the traceback:

```
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/home/zbyszek/.local/lib/python3.5/site-packages/meson-0.40.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
```

You are using `/usr/bin/meson` to run a python egg installed via `pip3 --user`? You should instead clone meson's git and directly run `meson.py` from there. You can make a symlink to it in `~/.local/bin` or something.

**Comment by keszybz** [comment]
I don't think this matters, at least for the first traceback. After a fresh git pull and with a pristine `build` dir:
```
$ git --git-dir ~/src/meson/meson.git/.git describe
0.39.1-151-g4c6f99a31a
$ ~/src/meson/meson.git/meson.py build
The Meson build system
Version: 0.40.0.dev1
Source dir: /home/zbyszek/src/meson/meson5
Build dir: /home/zbyszek/src/meson/meson5/build
Build type: native build
Project name: meson5
Native c compiler: ccache cc (gcc 6.3.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "pivot_root": YES
Checking for function "pivot_root": NO
Program no-such-file.sh found: NO
Build targets in project: 0
zbyszek@fedora ~/src/meson/meson5 % cd ubi
cd: no such file or directory: ubi
$ DESTDIR=/var/tmp/inst7 nj -C build install
[0/1] Installing files.
Traceback (most recent call last):
  File "/home/zbyszek/src/meson/meson.git/meson.py", line 37, in <module>
    sys.exit(main())
  File "/home/zbyszek/src/meson/meson.git/meson.py", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/home/zbyszek/src/meson/meson.git/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/zbyszek/src/meson/meson.git/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/zbyszek/src/meson/meson.git/mesonbuild/scripts/meson_install.py", line 306, in run
    do_install(datafilename)
  File "/home/zbyszek/src/meson/meson.git/mesonbuild/scripts/meson_install.py", line 129, in do_install
    run_install_script(d)
  File "/home/zbyszek/src/meson/meson.git/mesonbuild/scripts/meson_install.py", line 193, in run_install_script
    name = ' '.join(script + args)
TypeError: sequence item 0: expected str instance, NoneType found
FAILED: install 
'/usr/bin/python3' '/home/zbyszek/src/meson/meson.git/meson.py' '--internal' 'install' '/home/zbyszek/src/meson/meson5/build/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
Yeah, this traceback is unrelated to what I said. But it's strange that I cannot reproduce it.

**Comment by nirbheek** [comment]
Okay, I can reproduce it on Linux, but not on Windows for some reason.
