### ISSUE TITLE
zipapp throws exception

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1684]
I wanted to see what the zipapp thing was all about...

```
$ git clone https://github.com/mesonbuild/meson m
Cloning into 'm'...
remote: Counting objects: 21036, done.
remote: Total 21036 (delta 0), reused 0 (delta 0), pack-reused 21036
Receiving objects: 100% (21036/21036), 6.92 MiB | 692.00 KiB/s, done.
Resolving deltas: 100% (13980/1

$ python3 -m zipapp -p '/usr/bin/env python3' -m meson:main -o meson m
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/zipapp.py", line 201, in <module>
    main()
  File "/usr/local/lib/python3.5/zipapp.py", line 197, in main
    interpreter=args.python, main=args.main)
  File "/usr/local/lib/python3.5/zipapp.py", line 116, in create_archive
    "Cannot specify entry point if the source has __main__.py")
__main__.ZipAppError: Cannot specify entry point if the source has __main__.py

$ python3 --version
Python 3.5.2
```

Did I miss a step?

**Comment by nirbheek** [comment]
You don't need to specify the module anymore with the `-m` argument. Try this inside the git repository:

```
$ git archive --prefix meson-zipapp/ HEAD meson* __main__.py | tar -xf -
$ python3 -m zipapp -p '/usr/bin/env python3' -o meson meson-zipapp
$ rm -rf meson-zipapp/
$ ls -lh meson
```

Note however that in this mode `mesonintrospect`, `mesonconf`, etc can't work since zipapps only have one entry point.

**Comment by nirbheek** [comment]
Hmm, actually even `mesontest` won't be included, so tests won't work either. We should stop recommending this as an option in our README.
