### ISSUE TITLE
'PermissionError: [Errno 13] Permission denied' on run_target

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#1690]
You can see the relevant meson.build here - https://github.com/agauniyal/termdb/blob/master/meson.build#L24

The script is here - https://github.com/agauniyal/termdb/blob/master/scripts/extract_data.sh
```
[0/1] 'Running external command extract_data.'
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 248, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 236, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/commandrunner.py", line 52, in run
    pc = run_command(src_dir, build_dir, subdir, command, arguments)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/commandrunner.py", line 38, in run_command
    return subprocess.Popen(command_array, env=child_env, cwd=cwd)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
FAILED: extract_data 
'/usr/bin/python3' '/usr/bin/meson' '--internal' 'commandrunner' '/home/agauniyal/projects/termdb' '/home/agauniyal/projects/termdb/build2' '' '/home/agauniyal/projects/termdb/scripts/extract_data.sh'
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
Is `scripts/extract_data.sh` set to executable?

**Comment by agauniyal** [comment]
Nope, I just `chmod +x`ed it and it worked but why were earlier builds working fine?
