### ISSUE TITLE
vs2017 backend REGEN target fails to find WindowsSDKVersion

### ISSUE THREAD

**Issue by acfoltzer** [mesonbuild/meson#1847]
The vs2017 backend seems to need the `WindowsSDKVersion` environment variable in order to work. If you invoke it from the developer command line, it works, but if you invoke this target through the normal IDE, this environment variable is not set, and so it fails.

Is this environment variable something we'd expect to change, or would it make sense to bake it into the `REGEN` project so that it doesn't matter that it's not set after the initial `meson build`? Alternately, is there a way to modify the `REGEN` project to use all of the developer environment variables?

```
1>------ Build started: Project: REGEN, Configuration: debug Win32 ------
1>Checking whether solution needs to be regenerated.
1>Traceback (most recent call last):
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 298, in run
1>    app.generate()
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 165, in generate
1>    g = vs2017backend.Vs2017Backend(b)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\backend\vs2017backend.py", line 27, in __init__
1>    self.windows_target_platform_version = os.getenv('WindowsSDKVersion', None).rstrip('\\')
1>AttributeError: 'NoneType' object has no attribute 'rstrip'
1>The Meson build system
1>Version: 0.40.1
1>Source dir: C:\Users\acfoltzer\Source\Repos\OpenUxAS
1>Build dir: C:\Users\acfoltzer\Source\Repos\OpenUxAS\build
1>Build type: native build
1>Traceback (most recent call last):
1>  File "C:\Program Files\Python36\Scripts\meson.py", line 37, in <module>
1>    sys.exit(main())
1>  File "C:\Program Files\Python36\Scripts\meson.py", line 34, in main
1>    return mesonmain.run(launcher, sys.argv[1:])
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 260, in run
1>    sys.exit(run_script_command(args[1:]))
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 248, in run_script_command
1>    return cmdfunc(cmdargs)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 56, in run
1>    regen(regeninfo, mesonscript, backend)
1>  File "C:\Program Files\Python36\lib\site-packages\mesonbuild\scripts\regen_checker.py", line 42, in regen
1>    subprocess.check_call(cmd)
1>  File "C:\Program Files\Python36\lib\subprocess.py", line 291, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command '['C:\\Program Files\\Python36\\python.exe', 'C:\\Program Files\\Python36\\Scripts\\meson.py', '--internal', 'regenerate', 'C:\\Users\\acfoltzer\\Source\\Repos\\OpenUxAS\\build', 'C:\\Users\\acfoltzer\\Source\\Repos\\OpenUxAS', '--backend=vs2017']' returned non-zero exit status 1.
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "REGEN.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by nirbheek** [comment]
We should probably store the value of that environment variable and restore it on reconfigure, just like we do for `CC` and friends.

**Comment by nioncode** [comment]
The original cause was fixed by b6b3905325884c5fd2a502d09680b5a35564f0df. However, this did not fix the issue. A possible fix might arrive with #3872.

**Comment by bonzini** [comment]
Should be fixed by #4545
