### ISSUE TITLE
AttributeError on generating xcode project

### ISSUE THREAD

**Issue by Framstag** [mesonbuild/meson#1957]
I get the following error while triggering the xcode backend:

`meson --backend xcode xcode`

```
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.41.0/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 307, in run
    app.generate()
  File "/usr/local/Cellar/meson/0.41.0/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 182, in generate
    g.generate(intr)
  File "/usr/local/Cellar/meson/0.41.0/lib/python3.6/site-packages/mesonbuild/backend/xcodebackend.py", line 71, in generate
    self.generate_filemap()
  File "/usr/local/Cellar/meson/0.41.0/lib/python3.6/site-packages/mesonbuild/backend/xcodebackend.py", line 118, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'
```

Complete build files can be found at https://github.com/Framstag/libosmscout

The ninja build works without problems.

**Comment by jpakkane** [comment]
Sadly the XCode backend is a bit derelict and no-one has stepped up to maintain it. :(

**Comment by nirbheek** [comment]
Since none of the xcode backend code is run on our CI, the state of the backend is going to keep getting worse. As a first step, we need to make a list of tests that do pass on macOS and run exactly those on the CI so we at least don't regress constantly.

**Comment by drsog** [comment]
I have a fix, but I am currently looking for a CI ticket...

**Comment by nirbheek** [comment]
@drsog were you able to make progress on this?

**Comment by ylipacbio** [comment]
I am wondering if there is any progress on this bug?

**Comment by asartori86** [comment]
any improvements? I know meson itself doesn't want to depend on any dependencies, but maybe a workaround could be use something else (like the meson-cmake-wrapper) written in the documentation. Maybe (if it is not already done) we might output a suitable `json` file for a tool like this https://github.com/yonaskolb/XcodeGen. I don't have a mac but I am pushing forward to remove cmake from a project where we have many xcode users...

**Comment by gizahNL** [comment]
This bug is still present today in meson installed via pip3 on MacOS
