### ISSUE TITLE
Traceback when trying to use sparse

### ISSUE THREAD

**Issue by hughsie** [mesonbuild/meson#1989]
I tried to run `sparse` on my newly meson-ified project. A traceback was encountered which wasn't super friendly:

    $ CC=cgcc meson ../ --prefix=/home/hughsie/.root
    The Meson build system
    Version: 0.42.0.dev1
    Source dir: /home/hughsie/Code/fwupd
    Build dir: /home/hughsie/Code/fwupd/build
    Build type: native build
    Project name: fwupd
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 307, in run
        app.generate()
      File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 172, in generate
        intr = interpreter.Interpreter(b, g)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1240, in __init__
        self.parse_project()
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 111, in parse_project
        self.evaluate_codeblock(self.ast, end=1)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
        raise e
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
        self.evaluate_statement(cur)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
        return self.function_call(cur)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 361, in function_call
        return self.funcs[func_name](node, self.flatten(posargs), kwargs)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 55, in wrapped
        return f(self, node, args, kwargs)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1673, in func_project
        self.add_languages(proj_langs, True)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1789, in add_languages
        (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
      File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1712, in detect_compilers
        comp = self.environment.detect_c_compiler(False)
      File "/usr/lib/python3.6/site-packages/mesonbuild/environment.py", line 504, in detect_c_compiler
        return self._detect_c_or_cpp_compiler('c', 'CC', want_cross)
      File "/usr/lib/python3.6/site-packages/mesonbuild/environment.py", line 475, in _detect_c_or_cpp_compiler
        popen_exceptions[compiler] = 'no pre-processor defines'
    TypeError: unhashable type: 'list'

**Comment by nirbheek** [comment]
What is `cgcc` here that you are setting `CC` to?

**Comment by hughsie** [comment]
cgcc is the gcc-wrapper for the sparse utility.

**Comment by nirbheek** [comment]
I can reproduce the traceback, but even with it fixed, things won't work because `cgcc` seems to not behave like GCC at all. For instance, `cgcc -dM -E - <<<""` returns blank lines instead of a list of pre-existing compiler defines

**Comment by hughsie** [comment]
Maybe sparse could be added as a more integral part of meson if the gcc wrapper isn't very good?

**Comment by nirbheek** [comment]
That could be done, depends on what is expected of that integration.

**Comment by jpakkane** [comment]
Supporting every possible compiler wrapper tools is simply not feasible. The fact that it behaves differently from GCC is a bug and should be reported upstream as such.

**Comment by nirbheek** [comment]
Sparse is not meant to be a compiler though, it's a source code parser: https://sparse.wiki.kernel.org/index.php/Main_Page, so probably you could run it on the commands in `compile_commands.json`. The GCC wrapper exists merely to ease integration with build systems. It's a hack and isn't needed with Meson since we output all the commands we're going to run.

**Comment by nirbheek** [comment]
`compile_commands.json` is in the root build directory.
