### ISSUE TITLE
mesonconf traceback: AttributeError 'wrapped'

### ISSUE THREAD

**Issue by userwithuid** [mesonbuild/meson#2012]
Since commit https://github.com/mesonbuild/meson/commit/80ebc916f78ad736494ffee49f100134954acc2c , I get this python traceback using mesonconf:

```
Traceback (most recent call last):
  File "/usr/bin/mesonconf", line 20, in <module>
    sys.exit(mconf.run(sys.argv[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mconf.py", line 263, in run
    c = Conf(builddir)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mconf.py", line 41, in __init__
    self.build = pickle.load(f)
AttributeError: 'Interpreter' object has no attribute 'wrapped'
```

It's not for all projects, but I found at least one of your test cases can be used to trigger it:
```
cd "test cases/common/85 internal dependency"
meson . bd
mesonconf bd
```
Can you reproduce?

**Comment by trhd** [comment]
This might be related:

```
$ mesontest -C b --setup valgrind
Traceback (most recent call last):
  File "/usr/bin/mesontest", line 618, in <module>
    sys.exit(run(sys.argv[1:]))
  File "/usr/bin/mesontest", line 576, in run
    global_env = merge_suite_options(options)
  File "/usr/bin/mesontest", line 533, in merge_suite_options
    build = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.compilers.c'; 'mesonbuild.compilers' is not a package
```
