### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by zaufi** [mesonbuild/meson#2076]
Trying to build latest release of `systemd` 234 I've got an error:
~~~
 * abi_x86_32.x86: running multilib-minimal_abi_src_compile
ninja -v -j8 -l0
[1/1339] /usr/bin/python3.5 /usr/lib64/python-exec/python3.5/meson --internal exe /dev/shm/sys-apps-systemd-234/work/systemd-234-abi_x86_32.x86/meson-private/meson_exe_sed_3ab5d30c341183780e46e2d8cbdc6fdedd2ac6d2.dat
FAILED: catalog/systemd.fr.catalog 
/usr/bin/python3.5 /usr/lib64/python-exec/python3.5/meson --internal exe /dev/shm/sys-apps-systemd-234/work/systemd-234-abi_x86_32.x86/meson-private/meson_exe_sed_3ab5d30c341183780e46e2d8cbdc6fdedd2ac6d2.dat
WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
Traceback (most recent call last):
  File "/usr/lib64/python-exec/python3.5/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/lib64/python-exec/python3.5/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonmain.py", line 269, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonmain.py", line 257, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/scripts/meson_exe.py", line 76, in run
    return run_exe(exe)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/scripts/meson_exe.py", line 59, in run_exe
    p, stdout, stderr = Popen_safe(cmd + exe.cmd_args, env=child_env, cwd=exe.workdir)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonlib.py", line 512, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib64/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.5/subprocess.py", line 1485, in _communicate
    self.stdout.encoding)
  File "/usr/lib64/python3.5/subprocess.py", line 705, in _translate_newlines
    data = data.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
~~~

which is definitely wrong, cuz I have UTF-8 default locale (i.e. not an `ANSI_X3.4-1968`)

**Comment by jpakkane** [comment]
What is the output if you run the following commands in Python 3:

    import locale
    print(locale.getpreferredencoding())

**Comment by zaufi** [comment]
~~~
In [1]: import locale
   ...: print(locale.getpreferredencoding())
   ...: 
UTF-8
~~~

**Comment by jpakkane** [comment]
Are you compiling directly from that command prompt or using some other tool such as pbuilder or equivalent? Those usually set a plain ANSI locale even if the system locale is something else.

**Comment by zaufi** [comment]
I'm building using [paludis](https://paludis.exherbo.org). And yes, setting `LC_ALL=en_US.UTF-8` does help (default was `C`).

**Comment by nirbheek** [comment]
Gentoo should consider following Debian and Fedora's lead and adding a `C.UTF-8` locale.
