### ISSUE TITLE
i18n.gettext should have a install_dir

### ISSUE THREAD

**Issue by bilelmoussaoui** [mesonbuild/meson#2083]
In order to build GNOME Shell extensions using Meson build system. The locale files should be installed on the same directory as the extension. But for now we can't set an install_dir args. 
The other part of the issue is that even if i set the prefix to `--prefix=/home/username/.local/` the locale files are installed in `/usr/local/` which means that they don't use the current prefix.

For more information about the issue, and an example of the current situation see this PR https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/pull/402

**Comment by jpakkane** [comment]
Locale files (and almost anything, really) should always be installed inside the prefix. If it does not do that then it is a bug. Running `meson -h` even says its default value is `share/locale, which is relative to the prefix.

**Comment by bil-elmoussaoui** [comment]
Well, it doesn't on my machine with 0.41.1. Running ninja -C builddir install always throws a permissionError...

**Comment by TingPing** [comment]
I cannot reproduce:

`meson build --prefix=$HOME/test && ninja -C build install`

results in:
`Installing /home/tingping/Projects/gnome-shell-extensions-mediaplayer/build/po/zh_TW.gmo to /home/tingping/test/share/locale/zh_TW/LC_MESSAGES/gnome-shell-extensions-mediaplayer.mo`

**Comment by bil-elmoussaoui** [comment]
Here's why i got 
```bash
meson builddir --prefix=$HOME/.local                            

The Meson build system
Version: 0.41.1
Source dir: /home/bilal/gnome-shell-extensions-mediaplayer
Build dir: /home/bilal/gnome-shell-extensions-mediaplayer/builddir
Build type: native build
Project name: gnome-shell-extensions-mediaplayer
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring metadata.json using configuration
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/bilal/gnome-shell-extensions-mediaplayer/meson_post_install.py)
Build targets in project: 3
```
```bash
ninja -C builddir install                                        
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/dbus.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/extension.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/lib.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/manager.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/panel.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/player.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/prefs.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/settings.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/stylesheet.css to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/ui.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/util.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/widget.js to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Installing /home/bilal/gnome-shell-extensions-mediaplayer/src/org.gnome.shell.extensions.mediaplayer.gschema.xml to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info/schemas
Installing /home/bilal/gnome-shell-extensions-mediaplayer/builddir/src/metadata.json to /home/bilal/.local/share/gnome-shell/extensions/mediaplayer@patapon.info
Running custom install script '/usr/bin/python /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gnome-shell-extensions-mediaplayer'
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 269, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 257, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 115, in run
    do_install(src_sub, bld_sub, dest, options.pkgname, langs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/gettext.py", line 82, in do_install
    shutil.copyfile(srcfile, outfile)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/bilal/.local/share/locale/de/LC_MESSAGES/gnome-shell-extensions-mediaplayer.mo'
Failed to run install script '/usr/bin/python /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gnome-shell-extensions-mediaplayer'
FAILED: install 
/usr/bin/python /usr/bin/meson --internal install /home/bilal/gnome-shell-extensions-mediaplayer/builddir/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
It is installing into your home dir:

    PermissionError: [Errno 13] Permission denied: '/home/bilal/.local/share/locale/de/LC_MESSAGES/gnome-shell-extensions-mediaplayer.mo'

Maybe it fails because the directory it should write to has not been created?

**Comment by TingPing** [comment]
In my test the directory did not exist and was created.

**Comment by TingPing** [comment]
Maybe it was accidentally ran as root once?

**Comment by bil-elmoussaoui** [comment]
@TingPing I have removed the both folders and after running the script again it compiles correctly. Sorry about that. Does it makes any sense to add a install_dir to i18n.gettext or should i report that upstream instead?

**Comment by bil-elmoussaoui** [comment]
Every gnome extension out there uses that. I'm just helping people to make the move from autotools to Meson. It's up to you guys to decide whether you want to implement that or not

**Comment by TingPing** [comment]
Right so the use-case that needs to be real is a project where they install tranlsations into both `localedir` and a custom dir. I bet that usage does exist but your usage seems like `--localedir` is enough.

@bil-elmoussaoui You might be able to set `localedir` in `default_options` to make it more automatic btw: http://mesonbuild.com/Reference-manual.html#project

**Comment by bil-elmoussaoui** [comment]
I didn't knew about that ! Thanks. I can use that for now :)

**Comment by fedelibre** [comment]
I think this issue can be closed. Feature added since version 0.50 (see PR above).

**Comment by bilelmoussaoui** [comment]
@fedelibre Didn't notice it was fixed! Thanks :+1:
