### ISSUE TITLE
rpm module doesn't generate template

### ISSUE THREAD

**Issue by sgallagher** [mesonbuild/meson#2202]
When attempting to use the [RPM module](http://mesonbuild.com/RPM-module.html#rpm-module) with meson 0.41.2, it generates the following traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 307, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 180, in generate
    intr.run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2544, in run
    super().run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 125, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 151, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 361, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 47, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2261, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 146, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 140, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 155, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 389, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1060, in method_call
    value = fn(state, args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/modules/rpm.py", line 100, in generate_spec_template
    for lib in state.environment.coredata.ext_libs.values():
AttributeError: 'CoreData' object has no attribute 'ext_libs'
```

**Comment by sgallagher** [comment]
Pinging @ignatenkobrain

**Comment by nirbheek** [comment]
Igor is vacationing, so he won't be able to look into this right now. Is it blocking something urgent for you?

**Comment by nirbheek** [comment]
@ignatenkobrain poke

**Comment by nirbheek** [comment]
This broke in 2015 and no one noticed:

```
commit 06c7cef26ebe8b34658791adf4d6e7fcd02b173b
Author: Jussi Pakkanen <jpakkane@gmail.com>
Date:   Tue Nov 24 17:49:12 2015 +0200
```

I don't think the rpm module is getting any maintenance at all. I have previously also found things in it that had been broken for 1-2 years. We should consider removing it or disabling it till we have automated tests for it.

**Comment by thmo** [comment]
Bug is still present in 0.47.1.

Maybe the rpm module should be removed?
