### ISSUE TITLE
0.42.0 regression while installing pulseeffects

### ISSUE THREAD

**Issue by xircon** [mesonbuild/meson#2257]
Have already reported this on the Manjaro forum.  If I try to update pulseeffects (AUR) with v0.42.0-1 I get the following errors:
```
==> Starting package()...
[2/3] Installing files.
Installing subdir /home/steve/yaourt/yaourt-tmp-steve/aur-pulseeffects/src/pulseeffects-2.3.4/PulseEffects to /usr/lib/python3.6/site-packages
Installing subdir /home/steve/yaourt/yaourt-tmp-steve/aur-pulseeffects/src/pulseeffects-2.3.4/PulseEffectsCalibration to /usr/lib/python3.6/site-packages
Installing data/com.github.wwmm.pulseeffects.appdata.xml to /home/steve/yaourt/yaourt-tmp-steve/aur-pulseeffects/pkg/pulseeffects/usr/share/metainfo/com.github.wwmm.pulseeffects.appdata.xml
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 297, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 264, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 370, in run
    do_install(datafilename)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 190, in do_install
    install_targets(d)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 311, in install_targets
    do_copyfile(fname, outname)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 128, in do_copyfile
    restore_selinux_context(to_file)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 96, in restore_selinux_context
    subprocess.check_call(['selinuxenabled'])
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
FAILED: meson-install 
/usr/bin/python /usr/bin/meson --internal install /home/steve/yaourt/yaourt-tmp-steve/aur-pulseeffects/src/pulseeffects-2.3.4/_build/meson-private/install.dat
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build pulseeffects.
==> Restart building pulseeffects ? [y/N]
==> -------------------------------------
==> 
```

If I downgrade to v0.41.2-2 everything works as expected.

**Comment by nirbheek** [comment]
I can't reproduce this at all:

```
The Meson build system
Version: 0.42.0
Source dir: /home/nirbheek/projects/repositories/github/pulseeffects.git
Build dir: /home/nirbheek/projects/repositories/github/pulseeffects.git/build
Build type: native build
Project name: PulseEffects
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: Checking dependencies
Found pkg-config: /usr/bin/pkg-config (1.3.8)
Native dependency gtk+-3.0 found: YES 3.22.17
Native dependency pygobject-3.0 found: YES 3.24.1
Native dependency py3cairo found: YES 1.10.0
Native dependency gstreamer-1.0 found: YES 1.12.2
Native dependency gstreamer-plugins-bad-1.0 found: YES 1.12.2
Message: Getting python install path
Message: Installing PulseEffects
Message: Installing data files
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/nirbheek/projects/repositories/github/pulseeffects.git/meson_post_install.py)
Build targets in project: 5
ninja: Entering directory `build'
[2/2] Generating com.github.wwmm.pulseeffects.appdata.xml_merge with a custom command.
ninja: Entering directory `build'
[0/1] Installing files.
Installing subdir /home/nirbheek/projects/repositories/github/pulseeffects.git/PulseEffects to /usr/local/lib/python3.6/site-packages
Installing subdir /home/nirbheek/projects/repositories/github/pulseeffects.git/PulseEffectsCalibration to /usr/local/lib/python3.6/site-packages
Installing data/com.github.wwmm.pulseeffects.appdata.xml to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/metainfo/com.github.wwmm.pulseeffects.appdata.xml
Installing data/com.github.wwmm.pulseeffects.desktop to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/applications/com.github.wwmm.pulseeffects.desktop
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/pulseeffects to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/bin
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/data/com.github.wwmm.pulseeffects.gschema.xml to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/glib-2.0/schemas
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/data/com.github.wwmm.pulseeffects.sinkinputs.gschema.xml to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/glib-2.0/schemas
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/data/com.github.wwmm.pulseeffects.sourceoutputs.gschema.xml to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/glib-2.0/schemas
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/data/pulseeffects.svg to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/icons/hicolor/scalable/apps
Running custom install script '/usr/bin/python3 /home/nirbheek/projects/repositories/github/meson.git/meson.py --internal gettext install --subdir=po --localedir=share/locale --pkgname=PulseEffects'
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/build/po/cs.gmo to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/locale/cs/LC_MESSAGES/PulseEffects.mo
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/build/po/it_IT.gmo to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/locale/it_IT/LC_MESSAGES/PulseEffects.mo
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/build/po/pt_BR.gmo to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/locale/pt_BR/LC_MESSAGES/PulseEffects.mo
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/build/po/sk.gmo to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/locale/sk/LC_MESSAGES/PulseEffects.mo
Installing /home/nirbheek/projects/repositories/github/pulseeffects.git/build/po/sv.gmo to /home/nirbheek/projects/repositories/github/pulseeffects.git/install/usr/local/share/locale/sv/LC_MESSAGES/PulseEffects.mo
Running custom install script '/usr/bin/env python3 /home/nirbheek/projects/repositories/github/pulseeffects.git/meson_post_install.py'
```

**Comment by xircon** [comment]
Hmmm builds OK if I clone manually..  Will report to the package maintainer.

**Comment by nirbheek** [comment]
This error only happens when you run as a user that doesn't have permissions to run `selinuxenabled`. The fix is easy.
