### ISSUE TITLE
Boost headers on windows

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#2274]
Thanks for a great tool.

I'm trying to use two header only libraries from boost (variant and optional). And since boost isn't compiled I guess it fails to find libraries or something:

```
Dependency Boost () found: YES 1.64, c:\local\boost_1_64_0
Build targets in project: 4
Traceback (most recent call last):
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 338, in run
    app.generate()
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\mesonmain.py", line 183, in generate
    g.generate(intr)
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 182, in generate
    projlist = self.generate_projects()
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 330, in generate_projects
    self.gen_vcxproj(target, projfile, uuid)
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 917, in gen_vcxproj
    extra_link_args.extend_direct(dep.get_link_args())
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\dependencies\misc.py", line 242, in get_link_args
    return self.get_win_link_args()
  File "c:\users\niklas\appdata\local\programs\python\python36-32\lib\site-packages\mesonbuild\dependencies\misc.py", line 233, in get_win_link_args
    args.append('-L' + self.libdir)
TypeError: must be str, not NoneType
```

Also I couldn't work out how to use `BOOST_ROOT/BOOST_INCLUDEDIR` to specify where I had boost so I looked into the sources and moved it to `C:\local\boost_*`.  I had it in `C:\program files\boost\boost_*` initially.

**Comment by NickeZ** [comment]
This solved it for me. I don't know if it is the correct solution though..

```diff
diff --git a/mesonbuild/dependencies/misc.py b/mesonbuild/dependencies/misc.py
index 12e0239d..a91713a9 100644
--- a/mesonbuild/dependencies/misc.py
+++ b/mesonbuild/dependencies/misc.py
@@ -228,8 +228,8 @@ class BoostDependency(ExternalDependency):

     def get_win_link_args(self):
         args = []
-        # TODO: should this check self.libdir?
-        if self.boost_root:
+        # libdir might not be set if boost isn't compiled. (e.g. only header usage)
+        if self.boost_root and self.libdir:
             args.append('-L' + self.libdir)
         for module in self.requested_modules:
             module = BoostDependency.name2lib.get(module, module)

```

**Comment by NickeZ** [comment]
#2276
