### ISSUE TITLE
[gtk-doc] 'IncludeDirsHolder' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#231]
```python
Traceback (most recent call last):
  File "/home/brain/git/mesonbuild/meson/meson.py", line 192, in run
    app.generate()
  File "/home/brain/git/mesonbuild/meson/meson.py", line 133, in generate
    intr.run()
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 941, in run
    self.evaluate_codeblock(self.ast)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 963, in evaluate_codeblock
    raise e
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 957, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 1026, in evaluate_statement
    return self.function_call(cur)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 1728, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 59, in wrapped
    return f(self, node, args, kwargs)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 1541, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 963, in evaluate_codeblock
    raise e
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 957, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 1030, in evaluate_statement
    return self.method_call(cur)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 1828, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/home/brain/git/mesonbuild/meson/interpreter.py", line 708, in method_call
    value = fn(state, args, kwargs)
  File "/home/brain/git/mesonbuild/meson/modules/gnome.py", line 214, in gtkdoc
    os.path.normpath(os.path.join(state.subdir, src_dir)),
  File "/usr/lib64/python3.4/posixpath.py", line 79, in join
    if b.startswith(sep):
AttributeError: 'IncludeDirsHolder' object has no attribute 'startswith'
```

**Comment by ignatenkobrain** [comment]
I've used `  src_dir : incdir,`
