### ISSUE TITLE
Make output of install scripts accessible 

### ISSUE THREAD

**Issue by jtojnar** [mesonbuild/meson#2329]
When an install script fails, there is no indication as to why.

https://github.com/mesonbuild/meson/blob/c63aa0372b7acd8f6a094ca240eb39c8aab646cf/mesonbuild/scripts/meson_install.py#L263

Meson should either log the stdout/stderr of the scripts or print it on failure.

**Comment by jpakkane** [comment]
Subprocess.call does nothing to stderr or stdout. Anything printed by the run program gets printed to the terminal:

    >>> import subprocess
    >>> subprocess.call(['echo', 'hello'])
    hello
    >>>

The only thing that is lost is the text in the exception object which we probably should put in the error message.

**Comment by jtojnar** [comment]
You are right, the issue is with not printing the exception text. In this case, the issue was caused by incorrect shebang path.

**Comment by FRidh** [comment]
> You are right, the issue is with not printing the exception text. In this case, the problem was caused by incorrect shebang path.

Just had the exact same issue. This is confusing.

**Comment by eli-schwartz** [comment]
> You are right, the issue is with not printing the exception text. In this case, the problem was caused by incorrect shebang path.

The exception object will unfortunately not tell you much at all. The kernel will report "file not found", and the exception cannot tell which file could not be found.

Well, "cannot" is a big word there. Bash can: 
```bash
$ ./foo.py 
-bash: ./foo.py: /usr/bin/pyython3: bad interpreter: No such file or directory
```

```python
>>> subprocess.run(['./foo.py'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './foo.py'
```

But bash actually performs its own PATH search, tries to figure out which file the kernel attempted to open, opens that file itself, manually parses the shebang, and checks if the shebang exists.

...

Meson's own error message does distinguish between "Failed to run" (today: "could not be run") which indicates that the process could not even be started, and the case where the script ran, but exited with an error code (previously: just exit failure, today: "FAILED: install script 'XXX' exit code 123")
