### ISSUE TITLE
Failure/Traceback calling import('gnome') when gobject-introspection-1.0 is missing

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#241]
Cross compiling [gstreamer](https://github.com/jpakkane/gstreamer) with this cross compile file:

```
[binaries]
c = 'x86_64-w64-mingw32-gcc'
cpp = 'x86_64-w64-mingw32-g++'
ar = 'x86_64-w64-mingw32-ar'
strip = 'x86_64-w64-mingw32-strip'
exe_wrapper = 'wine'
pkgconfig = 'pkg-config'

[properties]
sizeof_int = 4
sizeof_wchar_t = 4
sizeof_char = 1
sizeof_void* = 4
sizeof_long = 8
sizeof_short = 2

alignment_char = 1
alignment_void* = 4
alignment_double = 4 # Don't know if this is correct...

has_function_printf = true
has_function_hfkerhisadf = false

[host_machine]
system = 'windows'
cpu = 'x86_64'
endian = 'little'
```

Leads to (when calling importing("gnome")):

```
meson build  --cross-file ubuntu-mingw.txt
The Meson build system
Version: 0.26.0-research
Source dir: /home/thiblahute/devel/misc/gstreamer
Build dir: /home/thiblahute/devel/misc/gstreamer/build
Build type: cross build
Build machine cpu: x86_64
Host machine cpu: x86_64
Target machine cpu: x86_64
Project name: gstreamer-core
Native c compiler: gcc (gcc 5.2.0)
Cross c compiler: x86_64-w64-mingw32-gcc (gcc 4.7.3)
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
Native cpp compiler: g++ (gcc 5.2.0)
Cross cpp compiler: x86_64-w64-mingw32-g++ (gcc 4.7.3)
Has header "dlfcn.h": NO
Has header "inttypes.h": YES
Has header "memory.h": YES
Has header "poll.h": NO
Has header "stdint.h": YES
Has header "stdio_ext.h": NO
Has header "strings.h": YES
Has header "string.h": YES
Has header "sys/param.h": YES
Has header "sys/poll.h": NO
Has header "sys/prctl.h": NO
Has header "sys/socket.h": NO
Has header "sys/stat.h": YES
Has header "sys/times.h": NO
Has header "sys/types.h": YES
Has header "sys/utsname.h": NO
Has header "sys/wait.h": NO
Has header "ucontext.h": NO
Has header "unistd.h": YES
Has header "valgrind/valgrind.h": NO
Has header "winsock2.h": YES
Checking for size of "char": 1
Checking for size of "int": 4
Checking for size of "long": 8
Checking for size of "short": 2
Checking for size of "void*": 4
Checking for function "gmtime_r": NO
Checking for function "localtime_r": NO
Checking for function "sigaction": NO
Checking for function "fseeko": YES
Checking for function "ftello": YES
Checking for function "fsetpos": YES
Checking for function "fgetpos": YES
Checking for function "poll": NO
Checking for function "pselect": NO
Checking for function "posix_memalign": NO
Checking for function "getpagesize": NO
Checking for type "ptrdiff_t": NO
Found pkg-config: /mnt/data/devel/cerbero_workdir/build-tools/bin/pkg-config (0.28)
Cross dependency glib-2.0 found: YES 2.44.1
Cross dependency gobject-2.0 found: YES 2.44.1
Cross dependency gmodule-2.0 found: YES 2.44.1
Cross dependency gio-2.0 found: YES 2.44.1
Library m found: NO
Program flex found: YES (/usr/bin/flex)
Program bison found: YES (/usr/bin/bison)
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Warning, glib compiled dependencies will not work until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
Library m found: NO
Program build_mkenum.py found: YES (/home/thiblahute/devel/misc/gstreamer/gst/build_mkenum.py)
Program gen_lex.py found: YES (/home/thiblahute/devel/misc/gstreamer/gst/parse/gen_lex.py)
Program gen_grammar.py found: YES (/home/thiblahute/devel/misc/gstreamer/gst/parse/gen_grammar.py)
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
Traceback (most recent call last):
  File "/usr/bin/meson", line 194, in run
    app.generate()
  File "/usr/bin/meson", line 135, in generate
    intr.run()
  File "/usr/share/meson/interpreter.py", line 953, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/share/meson/interpreter.py", line 975, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 969, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 1038, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/interpreter.py", line 1740, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/interpreter.py", line 59, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/interpreter.py", line 1558, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/share/meson/interpreter.py", line 975, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 969, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 1048, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/share/meson/interpreter.py", line 1891, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/share/meson/interpreter.py", line 975, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 969, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 1048, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/share/meson/interpreter.py", line 1891, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/share/meson/interpreter.py", line 975, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 969, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 1042, in evaluate_statement
    return self.method_call(cur)
  File "/usr/share/meson/interpreter.py", line 1840, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/usr/share/meson/interpreter.py", line 708, in method_call
    value = fn(state, args, kwargs)
  File "/usr/share/meson/modules/gnome.py", line 52, in generate_gir
    pkgstr = subprocess.check_output(['pkg-config', '--cflags', 'gobject-introspection-1.0'])
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'gobject-introspection-1.0']' returned non-zero exit status 1
```

**Comment by ignatenkobrain** [comment]
Yeah, we should use pkg-config from cross-file and print error instead of crash.

**Comment by tsaunier** [comment]
I think it should disable GI in that case, and notify the user.
