### ISSUE TITLE
Missing warnning when using an external library with link_with

### ISSUE THREAD

**Issue by bil-elmoussaoui** [mesonbuild/meson#2447]
I was trying to compile gtkimageview using meson.
And i had to link it with math lib. But i was getting this 
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 353, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 148, in generate
    self._generate(env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 196, in _generate
    intr.run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2728, in run
    super().run()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 170, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 164, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 175, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 385, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 77, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2124, in func_executable
    return self.build_target(node, args, kwargs, ExecutableHolder)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2805, in build_target
    target = targetclass(name, self.subdir, self.subproject, is_cross, sources, objs, self.environment, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/build.py", line 1127, in __init__
    super().__init__(name, subdir, subproject, is_cross, sources, objects, environment, kwargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/build.py", line 354, in __init__
    self.process_kwargs(kwargs, environment)
  File "/usr/lib/python3.6/site-packages/mesonbuild/build.py", line 693, in process_kwargs
    self.add_deps(deplist)
  File "/usr/lib/python3.6/site-packages/mesonbuild/build.py", line 824, in add_deps
    self.link(l)
  File "/usr/lib/python3.6/site-packages/mesonbuild/build.py", line 860, in link
    if not t.is_linkable_target():
AttributeError: 'ExternalLibrary' object has no attribute 'is_linkable_target'

```
Instead, i guess showing a warning/error message instead would be better :) 
Thanks!

**Comment by bil-elmoussaoui** [comment]
@jpakkane the same happens with 
```
AttributeError: 'PkgConfigDependency' object has no attribute 'is_linkable_target'
```
