### ISSUE TITLE
AttributeError: 'CustomTarget' object has no attribute 'objects'

### ISSUE THREAD

**Issue by tbodt** [mesonbuild/meson#2500]
I've got a project with a custom target in it, and this error happens when I try to generate Xcode build files:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 352, in run
    app.generate()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 147, in generate
    self._generate(env)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 197, in _generate
    g.generate(intr)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/backend/xcodebackend.py", line 71, in generate
    self.generate_filemap()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/backend/xcodebackend.py", line 118, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'
```

meson.build file: https://github.com/tbodt/ish/blob/master/meson.build

**Comment by tbodt** [comment]
Duplicate of #1957
