### ISSUE TITLE
Issue while checking meson after install using latest release

### ISSUE THREAD

**Issue by avmukilan** [mesonbuild/meson#2533]
meson --version
```python
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 4, in <module>
    __import__('pkg_resources').run_script('meson==0.43.0', 'meson')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'meson'
```

**Comment by nirbheek** [comment]
Fixed with https://github.com/mesonbuild/meson/pull/2673.
