### ISSUE TITLE
Getting no attribute 'subdir' when trying to compiler.run

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2576]
After adding the line:

cc = meson.get_compiler ('cpp')
cc.run (file = 'tests/test_gmime_version.cc', dependencies = [ notmuch, gmime ])

I get:

```
The Meson build system
Version: 0.43.0
Source dir: /home/gaute/dev/mail/notm/astroid
Build dir: /home/gaute/dev/mail/notm/astroid/adsf
Build type: native build
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 352, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 147, in generate
    self._generate(env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 187, in _generate
    intr = interpreter.Interpreter(b, g)
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1378, in __init__
    self.load_root_meson_file()
  File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 124, in load_root_meson_file
    self.ast = mparser.Parser(code, self.subdir).parse()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 443, in parse
    block = self.codeblock()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 679, in codeblock
    curline = self.line()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 673, in line
    return self.statement()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 448, in statement
    return self.e1()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 451, in e1
    left = self.e2()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 476, in e2
    left = self.e3()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 485, in e3
    left = self.e4()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 494, in e4
    left = self.e5()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 501, in e5
    return self.e5add()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 504, in e5add
    left = self.e5sub()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 510, in e5sub
    left = self.e5mod()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 516, in e5mod
    left = self.e5mul()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 522, in e5mul
    left = self.e5div()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 528, in e5div
    left = self.e6()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 538, in e6
    return self.e7()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 555, in e7
    left = self.method_call(left)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 618, in method_call
    args = self.args()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 590, in args
    a = ArgumentNode(s)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mparser.py", line 351, in __init__
    self.subdir = token.subdir
AttributeError: 'AssignmentNode' object has no attribute 'subdir'
```

**Comment by QuLogic** [comment]
Use colons, not equals (though this should be fixed).

**Comment by gauteh** [comment]
Right, thanks.

**Comment by QuLogic** [comment]
The backtrace still needs to be fixed?

**Comment by nirbheek** [comment]
I'm actually a bit tired of the whackamole we have to do with exceptions. I think the parser needs to be rewritten a bit to make it more robust to unexpected situations.
