### ISSUE TITLE
Non-numeric dependency() version parts not supported.

### ISSUE THREAD

**Issue by smokku** [mesonbuild/meson#258]
I am looking for OpenSSL with

    ssl_dep = dependency('openssl', version : '>= 1.0.1')

and meson fails with:
```
Native dependency openssl found: YES 1.0.1k

Traceback (most recent call last):
  File "/usr/bin/meson", line 188, in run
    app.generate()
  File "/usr/bin/meson", line 129, in generate
    intr.run()
  File "/usr/share/meson/interpreter.py", line 893, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/share/meson/interpreter.py", line 915, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 909, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 980, in evaluate_statement
    return self.assignment(cur)
  File "/usr/share/meson/interpreter.py", line 1686, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/share/meson/interpreter.py", line 978, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/interpreter.py", line 1667, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/interpreter.py", line 1313, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/share/meson/dependencies.py", line 1034, in find_external_dependency
    raise pkg_exc
  File "/usr/share/meson/dependencies.py", line 1023, in find_external_dependency
    pkgdep = PkgConfigDependency(name, environment, kwargs)
  File "/usr/share/meson/dependencies.py", line 119, in __init__
    self.is_found = mesonlib.version_compare(self.modversion, self.version_requirement)
  File "/usr/share/meson/mesonlib.py", line 141, in version_compare
    varr1 = [int(x) for x in vstr1.split('.')]
  File "/usr/share/meson/mesonlib.py", line 141, in <listcomp>
    varr1 = [int(x) for x in vstr1.split('.')]
ValueError: invalid literal for int() with base 10: '1k'
```

"1.0.1k" is not conforming with Semantic Versioning, but as you can see these versions exist in the wild.

One option is to convert just leading digits. Other option could be skipping version check when non semantic version number is found.

**Comment by smokku** [comment]
thx. that was quick :)
