### ISSUE TITLE
Assertion error when using libm from find_library()

### ISSUE THREAD

**Issue by ernestask** [mesonbuild/meson#2661]
Running Meson fails with Nautilus, as we do explicit linking with libm.

```
Traceback (most recent call last):
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/mesonmain.py", line 353, in run
    app.generate()
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/mesonmain.py", line 152, in generate
    self._generate(env)
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/mesonmain.py", line 209, in _generate
    g.generate(intr)
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/backend/ninjabackend.py", line 210, in generate
    self.generate_target(t, outfile)
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/backend/ninjabackend.py", line 461, in generate_target
    elem = self.generate_link(target, outfile, outname, obj_list, linker, pch_objects)
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/backend/ninjabackend.py", line 2465, in generate_link
    self.determine_rpath_dirs(target),
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/backend/backends.py", line 337, in determine_rpath_dirs
    for rp in self.rpaths_for_bundled_shared_libraries(target):
  File "/home/ernestas/Development/github.com/mesonbuild/meson/mesonbuild/backend/backends.py", line 326, in rpaths_for_bundled_shared_libraries
    assert(not os.path.isabs(rel_to_src))
AssertionError
```

The code in Meson checks if the path is a system path by looking at its prefix, but on my machine it seems to be a bit more exotic: `/usr/bin/../lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libm.so`.

**Comment by albertvaka** [comment]
Same problem here building Nautilus in Arch Linux. Did you find a solution?

**Comment by NickeZ** [comment]
I added the following lines, right before the assert.

```python
                    print(absdir)
                    print(self.environment.get_source_dir())
                    print(rel_to_src)
```

I can now see that `absdir` and `self.environment.get_source_dir()` are completely unrelated if you use:

```
find_library('foo', dirs:'C:\foo\lib')
```

`absdir` will be `c:\foo\lib' and `get_source_dir` will be something like `c:\users\niklas\git\myproj`.

The following line is therefore completely wrong. It subtracts the length of a completely unrelated path:

```python
rel_to_src = absdir[len(self.environment.get_source_dir()) + 1:]
```

I don't know what the real fix is here though..

**Comment by jpakkane** [comment]
How are you doing the linking?

    mdep = cc.find_library('m', required : false) # and then
    executable(..., dependencies : [mdep ...])

**Comment by ernestask** [comment]
```
libeel_2_deps = [
  ...
  libm,
  ...
]

libeel_2 = static_library(
  'eel-2',
  libeel_2_sources,
  dependencies: libeel_2_deps,
  include_directories: nautilus_include_dirs
)

eel_2 = declare_dependency(
  link_with: libeel_2,
  include_directories: nautilus_include_dirs,
  dependencies: libeel_2_deps
)
```

then

```
nautilus_deps = [
  eel_2,
  ...
]

libnautilus = static_library(
  'nautilus',
  libnautilus_sources,
  dependencies: nautilus_deps,
  include_directories: nautilus_include_dirs
)

libnautilus_dep = declare_dependency(
  link_with: libnautilus,
  include_directories: [
    nautilus_include_dirs,
    libnautilus_include_dirs
  ],
  dependencies: nautilus_deps
)
```

and finally

```
nautilus = executable(
  'nautilus',
  'nautilus-main.c',
  dependencies: libnautilus_dep,
  install: true
)
```
