### ISSUE TITLE
`run_unittests.py` fails when `vala` is not installed

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#2738]
You might not consider this an issue, but I would expect unsupported tests to be skipped, rather than fail.

Without `vala` installed, I got this:
```
$ ./run_unittests.py
...................Initialized empty Git repository in /home/eric/.tmp/tmpge2l1y82/.git/
[master (root-commit) 778c9b95ff2ef0e7fa5b] I am a project
 2 files changed, 9 insertions(+)
 create mode 100644 distexe.c
 create mode 100644 meson.build
......................s...cc: error trying to exec 'cc1obj': execvp: No such file or directory
..s.s.....s.................E
Stdout:
The Meson build system
Version: 0.44.0.dev1
Source dir: /home/eric/dev/scm/meson/test cases/vala/5 target glib
Build dir: /home/eric/.tmp/tmph1rt8_p7
Build type: native build
Project name: valatest
Native C compiler: ccache cc (gcc 8.0.0)

Meson encountered an error in file meson.build, line 1, column 0:
Could not execute Vala compiler "valac"

A full log can be found at /home/eric/.tmp/tmph1rt8_p7/meson-logs/meson-log.txt

Build started at 2017-12-06T11:44:37.700756
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.44.0.dev1
Source dir: /home/eric/dev/scm/meson/test cases/vala/5 target glib
Build dir: /home/eric/.tmp/tmph1rt8_p7
Build type: native build
Project name: valatest
Sanity testing C compiler: ccache cc
Is cross compiler: False.
Sanity check compiler command line: ccache cc /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.c -o /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.exe
Native C compiler: ccache cc (gcc 8.0.0)


======================================================================
ERROR: test_vala_c_warnings (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_unittests.py", line 1905, in test_vala_c_warnings
    self.init(testdir)
  File "./run_unittests.py", line 544, in init
    out = self._run(self.meson_command + args + extra_args)
  File "./run_unittests.py", line 517, in _run
    raise subprocess.CalledProcessError(p.returncode, command)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/eric/dev/scm/meson/mesonbuild/../meson.py', '--backend=ninja', '/home/eric/dev/scm/meson/./test cases/vala/5 target glib', '/home/eric/.tmp/tmph1rt8_p7', '--prefix', '/usr', '--libdir', '/usr/lib']' returned non-zero exit status 1.

Stdout:
The Meson build system
Version: 0.44.0.dev1
Source dir: /home/eric/dev/scm/meson/test cases/vala/5 target glib
Build dir: /home/eric/.tmp/tmph1rt8_p7
Build type: native build
Project name: valatest
Native C compiler: ccache cc (gcc 8.0.0)

Meson encountered an error in file meson.build, line 1, column 0:
Could not execute Vala compiler "valac"

A full log can be found at /home/eric/.tmp/tmph1rt8_p7/meson-logs/meson-log.txt

Build started at 2017-12-06T11:44:37.700756
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.44.0.dev1
Source dir: /home/eric/dev/scm/meson/test cases/vala/5 target glib
Build dir: /home/eric/.tmp/tmph1rt8_p7
Build type: native build
Project name: valatest
Sanity testing C compiler: ccache cc
Is cross compiler: False.
Sanity check compiler command line: ccache cc /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.c -o /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/eric/.tmp/tmph1rt8_p7/meson-private/sanitycheckc.exe
Native C compiler: ccache cc (gcc 8.0.0)


----------------------------------------------------------------------
Ran 74 tests in 60.655s

FAILED (errors=1, skipped=4)
```

With `vala` installed, everything passes (or is skipped):
```
$ ./run_unittests.py
...................Initialized empty Git repository in /home/eric/.tmp/tmp69f8e5d6/.git/
[master (root-commit) 96c2fd425d6fb1e01dc4] I am a project
 2 files changed, 9 insertions(+)
 create mode 100644 distexe.c
 create mode 100644 meson.build
......................s...cc: error trying to exec 'cc1obj': execvp: No such file or directory
..s.s.....s..................
----------------------------------------------------------------------
Ran 74 tests in 58.628s

OK (skipped=4)
```

I would expect the first case to result in `skipped=5` instead of `errors=1, skipped=4`, but maybe you want to force vala tests to be run?

**Comment by nirbheek** [comment]
On Linux, we generally require that various dependencies be installed because it's easy to do so. This helps us ensure a higher degree of test coverage.

We only make tests optional for frameworks that are very uncommon or have problematic dependencies.

Please install vala and other dependencies so we have increased test coverage :)
