### ISSUE TITLE
mintro: AttributeError: 'str' object has no attribute 'subdir'

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#2783]
Running this in [Mesa](/mesa3d/mesa) breaks meson:

```
$ meson -v
0.44.0

$ meson introspect --target-files egd_tables.h@cus 
Traceback (most recent call last):
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 297, in run
    return mintro.run(remaining_args)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 236, in run
    list_target_files(options.target_files, coredata, builddata)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 118, in list_target_files
    sources = [os.path.join(i.subdir, i.fname) for i in sources]
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 118, in <listcomp>
    sources = [os.path.join(i.subdir, i.fname) for i in sources]
AttributeError: 'str' object has no attribute 'subdir'
```

**Comment by jpakkane** [comment]
I tried this with the custom target tests that we have and could not reproduce. Is there possibly a simpler test case, cloning all of Mesa is a bit of a heavyweight solution ...

**Comment by 1ace** [comment]
It works for some targets (like `r600@sta`, `d3dadapter9@sha`, `wayland-egl-abi-check@exe`), but not others (like `egd_tables.h@cus`, `g_egldispatchstubs.c@cus`, `u_format_table.c@cus`).

It would look like it's broken for all `custom` targets? @dcbaker might have some insight into what Mesa might do differently, in order to get the test case in meson to catch this as well.

```
$ meson introspect --targets | jq '.[] | select(.id=="u_format_table.c@cus")'                                                                                                                                                     
{                                                                                                                                                                                                                                             
  "name": "u_format_table.c",
  "id": "u_format_table.c@cus",
  "filename": "src/gallium/auxiliary/u_format_table.c",
  "type": "custom",
  "installed": false,
  "build_by_default": false
}

$ meson introspect --target-files u_format_table.c@cus                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/usr/bin/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 297, in run
    return mintro.run(remaining_args)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 236, in run
    list_target_files(options.target_files, coredata, builddata)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 118, in list_target_files
    sources = [os.path.join(i.subdir, i.fname) for i in sources]
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 118, in <listcomp>
    sources = [os.path.join(i.subdir, i.fname) for i in sources]
AttributeError: 'str' object has no attribute 'subdir'
```

**Comment by nirbheek** [comment]
This was always broken from what I can tell, removing from stable release milestone.
