### ISSUE TITLE
wraptool error on Debian unstable

### ISSUE THREAD

**Issue by djdeath** [mesonbuild/meson#2810]
Hi,

Just running : wraptool list 
Gives me this error : 

```
$ wraptool list
Traceback (most recent call last):
  File "/usr/bin/wraptool", line 17, in <module>
    from mesonbuild.wrap import wraptool
  File "/usr/share/meson/mesonbuild/wrap/wraptool.py", line 22, in <module>
    from .wrap import API_ROOT, open_wrapdburl
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 22, in <module>
    from ..mesonlib import Popen_safe
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 60, in <module>
    meson_command = python_command + [detect_meson_py_location()]
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 51, in detect_meson_py_location
    raise RuntimeError('Could not determine how to run Meson. Please file a bug with details.')
RuntimeError: Could not determine how to run Meson. Please file a bug with details.
```
This is on Debian unstable with meson 0.44.0.

**Comment by bredelings** [comment]
Partly it is because `detect_meson_py_location` only looks for dir+`meson.py` and not also dir+`meson`.  If we change this to the following then at least we can find meson:
```
    # The only thing remaining is to try to find the bundled executable and                                                                                                  
    # pray distro packagers have not moved it.                                                                                                                               
    fname_py = os.path.join(os.path.dirname(__file__), '..', 'meson.py')
    fname = os.path.join(os.path.dirname(__file__), '..', 'meson')
    if os.path.exists(fname):
        return fname
    elif os.path.exists(fname_py):
        return fname.py
    else:
        raise RuntimeError('Could not determine how to run Meson. Please file a bug with details.')
```
