### ISSUE TITLE
wraptool install libuv failing

### ISSUE THREAD

**Issue by djdeath** [mesonbuild/meson#2812]
I may be responsible for this, as I just submitted the libuv wrap.
But when running this, I get a backtrace : 
```
$ wraptool install libuv
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wraptool", line 20, in <module>
    sys.exit(wraptool.run(sys.argv[1:]))
  File "/usr/share/meson/mesonbuild/wrap/wraptool.py", line 181, in run
    install(args[0])
  File "/usr/share/meson/mesonbuild/wrap/wraptool.py", line 90, in install
    (branch, revision) = get_latest_version(name)
  File "/usr/share/meson/mesonbuild/wrap/wraptool.py", line 74, in get_latest_version
    jd = get_result(API_ROOT + 'query/get_latest/' + name)
  File "/usr/share/meson/mesonbuild/wrap/wraptool.py", line 49, in get_result
    u = open_wrapdburl(urlstring)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 67, in open_wrapdburl
    return urllib.request.urlopen(urlstring)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by djdeath** [comment]
My bad! Left a proxy environment variable...
Sorry for the noise.
