### ISSUE TITLE
Error when trying to cross compile with SDL2 for 'objc' language

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#2908]
I cannot cross compile SDL2 for iOS because 'objc' seems to not be recognized when trying add_languages('objc'). It does not happen when compiling without cross compilation support. The error follows below.

```sh
Project name: sdl2
Native C compiler: ccache cc (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.38)")
Cross C compiler: clang (clang 9.0.0)
Library m found: YES
Library dl found: YES
Library pthread found: YES
Traceback (most recent call last):
  File "/Users/germandiago/meson/mesonbuild/mesonmain.py", line 368, in run
    app.generate()
  File "/Users/germandiago/meson/mesonbuild/mesonmain.py", line 151, in generate
    self._generate(env)
  File "/Users/germandiago/meson/mesonbuild/mesonmain.py", line 200, in _generate
    intr.run()
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 2943, in run
    super().run()
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 443, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 2618, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 210, in evaluate_statement
    return self.evaluate_if(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 263, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 202, in evaluate_statement
    return self.assignment(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 661, in assignment
    value = self.evaluate_statement(node.value)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 443, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 1710, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 1738, in do_subproject
    subi.run()
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 2943, in run
    super().run()
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 210, in evaluate_statement
    return self.evaluate_if(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 263, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 443, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 1914, in func_add_languages
    return self.add_languages(args, kwargs.get('required', True))
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 2029, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "/Users/germandiago/meson/mesonbuild/interpreter.py", line 1962, in detect_compilers
    cross_comp = self.environment.detect_objc_compiler(True)
  File "/Users/germandiago/meson/mesonbuild/environment.py", line 602, in detect_objc_compiler
    compilers, ccache, is_cross, exe_wrap = self._get_compilers('objc', 'OBJC', want_cross)
  File "/Users/germandiago/meson/mesonbuild/environment.py", line 424, in _get_compilers
    compilers = mesonlib.stringlistify(self.cross_info.config['binaries'][lang])
KeyError: 'objc'
```

My cross file is:

```sh
[binaries]
objc = 'clang'
c = 'clang'
cpp = 'clang++'
ar = 'ar'
strip = 'strip'

[properties]
root = '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer'

c_args = ['-arch', 'armv7', '-miphoneos-version-min=8.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk']
cpp_args = ['-arch', 'armv7', '-miphoneos-version-min=8.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk']
c_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk']
cpp_link_args = ['-arch', 'armv7', '-miphoneos-version-min=8.0', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk']

has_function_printf = true
has_function_hfkerhisadf = false

[host_machine]
system = 'darwin'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'
```

**Comment by germandiagogomez** [comment]
I see the problem already: self.cross_info.config['binaries'] dicitionary does not contain {'objc'} entry at all but it is the key being accessed. I suspect it should be added. Since it works in normal config (native compilation), that would fix the access.

**Comment by germandiagogomez** [comment]
My bad, I was modifying the wrong iphone.txt file. Closing...
