### ISSUE TITLE
Source only internal dependencies does not work in mixed projects

### ISSUE THREAD

**Issue by lravasz** [mesonbuild/meson#2937]
I created a mixed project with langs 'c' & 'cpp'.
The executable is pure c++ and depends on a pure c module.

```
exe = executable('projtest',
    'main.cpp',
    dependencies : dep
)
```
```
inc = include_directories('.')
dep = declare_dependency(
    sources : 'lib.c',
    include_directories : inc,
)
```
 In this setup the build process fails for the executeble because the 'c' compiler is not found for the internal dependency 'lib/lib.c'. 

```{r}
$ meson build
The Meson build system
Version: 0.44.0
Source dir: /tmp/mixed-internal-dep
Build dir: /tmp/mixed-internal-dep/build
Build type: native build
Project name: mixed internal dependency
Native C compiler: cc (gcc 4.8.4)
Native C++ compiler: c++ (gcc 4.8.4)
Build machine cpu family: x86
Build machine cpu: i686
Build targets in project: 1
Found ninja-1.8.2 at /usr/local/bin/ninja
Traceback (most recent call last):
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/mesonmain.py", line 365, in run
    app.generate()
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/mesonmain.py", line 151, in generate
    self._generate(env)
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/mesonmain.py", line 208, in _generate
    g.generate(intr)
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/backend/ninjabackend.py", line 210, in generate
    self.generate_target(t, outfile)
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/backend/ninjabackend.py", line 457, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/backend/ninjabackend.py", line 2146, in generate_single_compile
    compiler = get_compiler_for_source(target.compilers.values(), src)
  File "/home/deveushu/VEnv/all/lib/python3.6/site-packages/meson-0.44.0-py3.6.egg/mesonbuild/mesonlib.py", line 227, in get_compiler_for_source
    raise RuntimeError('No specified compiler can handle file {!s}'.format(src))
RuntimeError: No specified compiler can handle file lib/lib.c
```
 As far as i know the compilers are searched for the sources in the BuildTarget class. The dependecies are extracted with the process_kwargs(), while the compilers with the process_compilers() and process_compilers_late() methods. The process_compilers() method is called in the init before the source dependencies are extracted in the process_kwargs() method, and the process_compilers_late() method called later does not add the 'c' compiler in case of pure source code dependency.

[mixed-internal-dep.tar.gz](https://github.com/mesonbuild/meson/files/1639101/mixed-internal-dep.tar.gz)

**Comment by ldanko** [comment]
Looks that this is already solved. Tried to reproduce the issue using meson 0.47.2 and everything worked fine.

```
$ meson build
The Meson build system
Version: 0.47.2
Source dir: /home/ldanko/tmp/mixed-internal-dep
Build dir: /home/ldanko/tmp/mixed-internal-dep/build
Build type: native build
Project name: mixed internal dependency
Project version: undefined
Native C compiler: gcc (gcc 8.1.1 "gcc (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)")
Native C++ compiler: g++ (gcc 8.1.1 "g++ (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
```

**Comment by lravasz** [comment]
Hello,

 I checked it with the 0.48.0 release, and it is working. Thanks!

The Meson build system
Version: 0.48.0
Source dir: /tmp/mixed-internal-dep
Build dir: /tmp/mixed-internal-dep/build
Build type: native build
Project name: mixed internal dependency
Project version: undefined
Native C compiler: cc (gcc 4.8.4 "cc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4")
Native C++ compiler: c++ (gcc 4.8.4 "c++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4")
Build machine cpu family: x86
Build machine cpu: i686
Build targets in project: 1
