### ISSUE TITLE
rpaths_for_bundled_shared_libraries throwing

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#2974]
Hi,

I'm stumped by this. I've tested 0.43, 0.44 and this is with the latest master.

My meson.build looks like:

```
cuda_root = '/usr/local/nvidia/5.0/cuda'
cuda_lib_dir = join_paths(cuda_root, 'lib64')
cudart = cc.find_library('cudart', dirs: cuda_lib_dir)
```

And I'm getting this exception (note: I've added the warning lines as debug)

```
Found ninja-1.7.2 at /usr/local/bin/ninja
WARNING: ['/usr/local/nvidia/5.0/cuda/lib64/libcudart.so']
WARNING: /usr/local/nvidia/5.0/cuda/lib64/libcudart.so
WARNING: /builds/project/project
WARNING: /usr/local/nvidia/5.0/cuda/lib64
WARNING: /lib64
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 366, in run
    app.generate()
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 151, in generate
    self._generate(env)
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 209, in _generate
    g.generate(intr)
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 214, in generate
    self.generate_target(t, outfile)
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 465, in generate_target
    elem = self.generate_link(target, outfile, outname, obj_list, linker, pch_objects)
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 2485, in generate_link
    self.determine_rpath_dirs(target),
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/backend/backends.py", line 345, in determine_rpath_dirs
    for rp in self.rpaths_for_bundled_shared_libraries(target):
  File "/usr/local/lib/python3.5/site-packages/meson-0.45.0.dev1-py3.5.egg/mesonbuild/backend/backends.py", line 332, in rpaths_for_bundled_shared_libraries
    assert(not os.path.isabs(rel_to_src))
AssertionError
```

My slightly modified function:

```python
    def rpaths_for_bundled_shared_libraries(self, target):
        paths = []
        for dep in target.external_deps:
            if isinstance(dep, dependencies.ExternalLibrary):
                la = dep.link_args
                if len(la) == 1 and os.path.isabs(la[0]):
                    # The only link argument is an absolute path to a library file.
                    libpath = la[0]
                    if libpath.startswith(('/usr/lib', '/lib')):
                        # No point in adding system paths.
                        continue
                    if os.path.splitext(libpath)[1] not in ['.dll', '.lib', '.so']:
                        continue
                    absdir = os.path.split(libpath)[0]
                    rel_to_src = absdir[len(self.environment.get_source_dir()) + 1:]
                    mlog.warning(la)
                    mlog.warning(libpath)
                    mlog.warning(self.environment.get_source_dir())
                    mlog.warning(absdir)
                    mlog.warning(rel_to_src)
                    assert(not os.path.isabs(rel_to_src))
                    paths.append(os.path.join(self.build_to_src, rel_to_src))
        return paths
```

Is it obvious what I'm doing wrong here?

**Comment by rhd** [comment]
I've added

```python
                    if os.path.relpath(absdir, self.environment.get_source_dir())[:2] == "..":
                        continue
```

to my local copy and it seems to make it work.

Is this the logic: **If the library isn't in `/usr/lib` or `/lib` it's assumed to be part of the source tree?**

**Comment by ernestask** [comment]
Duplicate of #2726 and #2661.

**Comment by rhd** [comment]
Thanks for the heads up! Closing.
