### ISSUE TITLE
crash needs error message

### ISSUE THREAD

**Issue by stephenbarton** [mesonbuild/meson#2979]
I have spent 3 to 4 hours trying to resolve the crash.

Please help me solve the problem:
Running from cygwin or windows it is the same problem.
I am using Meson 0.44.0 and ninja 1.8.2

Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 365, in run
  File "mesonbuild\mesonmain.py", line 151, in generate
  File "mesonbuild\mesonmain.py", line 208, in _generate
  File "mesonbuild\backend\ninjabackend.py", line 210, in generate
  File "mesonbuild\backend\ninjabackend.py", line 310, in generate_target
  File "mesonbuild\backend\ninjabackend.py", line 598, in generate_run_target
  File "mesonbuild\backend\ninjabackend.py", line 1794, in replace_paths
  File "mesonbuild\backend\ninjabackend.py", line 1794, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by nirbheek** [comment]
Is this still a problem or were you able to figure it out?

**Comment by stephenbarton** [comment]
I commented out the line in the meson.build file
The generator is not protected if the file does not exist.

jlinkexe = find_program('JLinkExe', required: false)
#    jlink_run = generator(jlinkexe, arguments: '')

I found the problem by adding a lot of print statements to the meson source.

Thanks for your assistance

**Comment by stephenbarton** [comment]
'#    jlink_run = generator(jlinkexe, arguments: '')'

**Comment by stephenbarton** [comment]
the comment box interprets the hashtag sign

**Comment by bonzini** [comment]
Unclear reproduction instructions, closing.
