### ISSUE TITLE
gresources aren't rebuilt when changed

### ISSUE THREAD

**Issue by benwaffle** [mesonbuild/meson#298]
When I change a vala file it is rebuilt, but not when i change my .ui files

**Comment by jpakkane** [comment]
That is probably this bug (this is also printed as a warning when importing the Gnome module): https://bugzilla.gnome.org/show_bug.cgi?id=745754

**Comment by jpakkane** [comment]
There is a workaround I can add, I did not put it in at the time as I expecting the upstream fix to go in.

**Comment by benwaffle** [comment]
doesn't `-M` also print it out in make format?

**Comment by jpakkane** [comment]
Maybe but Ninja can only read the dep info from files and having it as a separate command means running the compiler twice on every invocation.

**Comment by benwaffle** [comment]
```Python
Traceback (most recent call last):
  File "../meson/dest/bin/meson", line 209, in run
    app.generate()
  File "../meson/dest/bin/meson", line 161, in generate
    intr.run()
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1024, in run
    self.evaluate_codeblock(self.ast)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1046, in evaluate_codeblock
    raise e
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1040, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1144, in evaluate_statement
    return self.function_call(cur)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1902, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 61, in wrapped
    return f(self, node, args, kwargs)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1720, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1046, in evaluate_codeblock
    raise e
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1040, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1146, in evaluate_statement
    return self.assignment(cur)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1921, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 1148, in evaluate_statement
    return self.method_call(cur)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 2009, in method_call
    return obj.method_call(method_name, self.flatten(args), kwargs)
  File "/home/ben/dev/meson/dest/share/meson/interpreter.py", line 775, in method_call
    value = fn(state, args, kwargs)
  File "/home/ben/dev/meson/dest/share/meson/modules/gnome.py", line 41, in compile_resources
    kwargs['depend_files'] = self.parse_gresource_xml(state, resfile)
  File "/home/ben/dev/meson/dest/share/meson/modules/gnome.py", line 50, in parse_gresource_xml
    abspath = os.path.join(state.environment.source_dir, state.subdir, fname)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'File'
```
