### ISSUE TITLE
PermissionError when running as another user (not login shell)

### ISSUE THREAD

**Issue by jaystrictor** [mesonbuild/meson#299]
```
[otheruser /]$ su jay
Password: 
[jay /]$ meson -v
Traceback (most recent call last):
  File "/usr/bin/meson", line 48, in <module>
    parser.add_argument('--libdir', default=mesonlib.default_libdir(), dest='libdir',
  File "/usr/share/meson/mesonlib.py", line 155, in default_libdir
    archpath = subprocess.check_output(['dpkg-architecture', '-qDEB_HOST_MULTIARCH']).decode().strip()
  File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
[jay /]$ exit
[otheruser /]$ su --login jay
Password: 
[jay ~]$ meson -v
0.26.0
[jay ~]$ 
```

**Comment by jpakkane** [comment]
Which platform are you running this on and what does it say if you do these commands from an otheruser prompt:

    su jay
    dpkg-architecture -qDEB_HOST_MULTIARCH

**Comment by jaystrictor** [comment]
This is Arch Linux, rolling release. Python 3.5.0
`dpkg` is not installed, as Arch Linux uses `pacman`

```
[otheruser /]$ su jay
Password: 
[jay /]$ uname -rvmpio
4.2.3-1-ARCH #1 SMP PREEMPT Sat Oct 3 18:52:50 CEST 2015 x86_64 unknown unknown GNU/Linux
[jay /]$ dpkg-architecture -qDEB_HOST_MULTIARCH
bash: dpkg-architecture: command not found
[jay /]$ 
```

**Comment by jaystrictor** [comment]
This seems to be a [bug in python](http://bugs.python.org/issue25481).
