### ISSUE TITLE
cannot use BOOST_ROOT in msys2 [crash]

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#2990]
To use boost in msys2 one have to use BOOST_ROOT because msys2 has a non standard directory layout, but it crashes:
```
$ BOOST_ROOT=/mingw64 meson builddir
The Meson build system
Version: 0.44.0
Source dir: C:/msys64/home/luca9/myproject
Build dir: C:/msys64/home/luca9/myproject/builddir
Build type: native build
Project name: myproject
Native C++ compiler: c++ (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\mesonmain.py", line 365, in run
    app.generate()
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\mesonmain.py", line 151, in generate
    self._generate(env)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\mesonmain.py", line 199, in _generate
    intr.run()
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreter.py", line 2868, in run
    super().run()
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 171, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 193, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 200, in evaluate_statement
    return self.assignment(cur)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 659, in assignment
    value = self.evaluate_statement(node.value)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 198, in evaluate_statement
    return self.function_call(cur)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 441, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreterbase.py", line 77, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\interpreter.py", line 2185, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\dependencies\base.py", line 864, in find_external_dependency
    dep = packages[lname](env, kwargs)
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\dependencies\misc.py", line 121, in __init__
    self.detect_lib_modules()
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\dependencies\misc.py", line 237, in detect_lib_modules
    return self.detect_lib_modules_win()
  File "C:/msys64/mingw64/lib/python3.6/site-packages\mesonbuild\dependencies\misc.py", line 242, in detect_lib_modules_win
    comp_ts_version = self.env.detect_cpp_compiler(self.want_cross).get_toolset_version()
AttributeError: 'GnuCPPCompiler' object has no attribute 'get_toolset_version'
```
To reproduce the issue, simply create an empty directory with this meson.build
```meson
project('myproject', ['cpp'])

boost_dep = dependency('boost', modules: [])
```
Also tried with clang and clang++ but it's the same

**Comment by bredelings** [comment]
Can you give me an example of a boost library filename for mingw64?  I'm wondering what ABI tag is used.

**Comment by lb90** [comment]
Hi! Here it is
```
mingw-w64-x86_64-boost /mingw64/
mingw-w64-x86_64-boost /mingw64/bin/
mingw-w64-x86_64-boost /mingw64/bin/libboost_atomic-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_chrono-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_container-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_context-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_coroutine-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_date_time-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_filesystem-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_graph-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_iostreams-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_locale-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_log-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_log_setup-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_c99-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_c99f-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_c99l-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_tr1-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_tr1f-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_math_tr1l-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_numpy-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_numpy3-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_prg_exec_monitor-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_program_options-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_python-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_python3-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_random-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_regex-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_serialization-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_signals-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_stacktrace_noop-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_stacktrace_windbg-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_system-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_thread-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_timer-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_type_erasure-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_unit_test_framework-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_wave-mt.dll
mingw-w64-x86_64-boost /mingw64/bin/libboost_wserialization-mt.dll
mingw-w64-x86_64-boost /mingw64/include/
mingw-w64-x86_64-boost /mingw64/include/boost/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/accumulators.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/accumulators_fwd.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulator_base.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulator_concept.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulator_set.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulators/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulators/droppable_accumulator.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulators/external_accumulator.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulators/reference_accumulator.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/accumulators/value_accumulator.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/depends_on.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/external.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/extractor.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/features.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/parameters/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/parameters/accumulator.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/parameters/sample.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/parameters/weight.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/framework/parameters/weights.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/function1.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/function2.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/function3.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/function4.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/function_n.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/detail/pod_singleton.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional/
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional/complex.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional/valarray.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional/vector.hpp
mingw-w64-x86_64-boost /mingw64/include/boost/accumulators/numeric/functional_fwd.hpp
...
mingw-w64-x86_64-boost /mingw64/lib/
mingw-w64-x86_64-boost /mingw64/lib/libboost_atomic-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_atomic-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_chrono-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_chrono-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_container-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_container-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_context-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_context-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_coroutine-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_coroutine-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_date_time-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_date_time-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_exception-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_filesystem-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_filesystem-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_graph-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_graph-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_iostreams-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_iostreams-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_locale-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_locale-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_log-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_log-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_log_setup-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_log_setup-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99f-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99f-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99l-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_c99l-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1f-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1f-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1l-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_math_tr1l-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_numpy-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_numpy-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_numpy3-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_numpy3-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_prg_exec_monitor-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_prg_exec_monitor-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_program_options-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_program_options-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_python-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_python-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_python3-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_python3-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_random-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_random-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_regex-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_regex-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_serialization-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_serialization-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_signals-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_signals-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_stacktrace_noop-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_stacktrace_noop-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_stacktrace_windbg-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_stacktrace_windbg-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_system-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_system-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_test_exec_monitor-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_thread-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_thread-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_timer-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_timer-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_type_erasure-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_type_erasure-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_unit_test_framework-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_unit_test_framework-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_wave-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_wave-mt.dll.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_wserialization-mt.a
mingw-w64-x86_64-boost /mingw64/lib/libboost_wserialization-mt.dll.a
```

**Comment by lb90** [comment]
Here you can see how the package is built
[https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-boost](url)
aside from PKGBUILD there are many patches

**Comment by bredelings** [comment]
OK, so the problem here is that boost libraries on windows sometimes have complex ABI tags, of the form `-<compiler>-mt-gd-1_66`. Currently meson assumes that this is the case, and also that the compiler is visual studio.  The crash you are seeing comes from trying to get the compiler version from gcc, where as the "toolset version" is only implemented for visual studio.

For mingw, the ABI tag is just "-mt".  I'm wondering how we are supposed to know what the ABI tag is, or if we need to try multiple forms of the ABI tag.

**Comment by bredelings** [comment]
@lb50 I think this is fixed in current master.  Can you check?  I was able to do a cross-compile with boost using the mingw-w64 compilers in Debian.

**Comment by lb90** [comment]
Thanks! I'm going to try ASAP

**Comment by lb90** [comment]
Great, it works!
Thanks a lot

**Comment by lb90** [comment]
Just a quick question: meson in MSYS2 now successfully finds boost by itself and doesn't need BOOST_ROOT envvar. So that's just fine. Anyway I tried also to run meson with BOOST_ROOT set, just to see if there could be any problem. Running
```
$ BOOST_ROOT=/mingw64 meson builddir
```
yelds a (seemingly unoffensive) warning:
```
The Meson build system
Version: 0.45.0.dev1
Source dir: C:/msys64/home/luca9/prova
Build dir: C:/msys64/home/luca9/prova/build
Build type: native build
Project name: prova
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Rev1, Built by MSYS2 project) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
WARNING: No include directory found parsing "c++ -xc++ -E -v -" output
Dependency Boost (system, filesystem) found: YES 1.66, C:/msys64/mingw64
Build targets in project: 1
Found ninja-1.8.2 at 'C:\msys64\mingw64\bin/ninja.EXE'
WARNING: No include directory found parsing "c++ -xc++ -E -v -" output
```
Anyway, ninja successfully builds the application

**Comment by lb90** [comment]
while invoking meson without BOOST_ROOT set I get a completely clean output
```
$ meson builddir2
```
```
The Meson build system
Version: 0.45.0.dev1
Source dir: C:/msys64/home/luca9/prova
Build dir: C:/msys64/home/luca9/prova/build2
Build type: native build
Project name: prova
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Rev1, Built by MSYS2 project) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency Boost (system, filesystem) found: YES 1.66
Build targets in project: 1
Found ninja-1.8.2 at 'C:\msys64\mingw64\bin/ninja.EXE'
```

**Comment by bredelings** [comment]
Can you post the meson log for the case where BOOST_ROOT is set?

**Comment by bredelings** [comment]
And also for the other one, just in case?

**Comment by lb90** [comment]
[meson-log-BOOST_ROOT.txt](https://github.com/mesonbuild/meson/files/1731654/meson-log-BOOST_ROOT.txt)
[meson-log.txt](https://github.com/mesonbuild/meson/files/1731657/meson-log.txt)
