### ISSUE TITLE
Cross-drive build is not supported on Windows

### ISSUE THREAD

**Issue by sarum9in** [mesonbuild/meson#3239]
```
Stdout:
Traceback (most recent call last):
  File "D:\dev\meson\mesonbuild\mesonmain.py", line 368, in run
    app.generate()
  File "D:\dev\meson\mesonbuild\mesonmain.py", line 150, in generate
    self._generate(env)
  File "D:\dev\meson\mesonbuild\mesonmain.py", line 168, in _generate
    g = ninjabackend.NinjaBackend(b)
  File "D:\dev\meson\mesonbuild\backend\ninjabackend.py", line 143, in __init__
    super().__init__(build)
  File "D:\dev\meson\mesonbuild\backend\backends.py", line 111, in __init__
    self.environment.get_build_dir())
  File "C:\Python36\lib\ntpath.py", line 585, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'D:', start on mount 'C:'
```

A little bit of debugging shows that this happens in `Backend.__init__()`, 
```python
self.build_to_src = os.path.relpath(self.environment.get_source_dir(), # D:\dev\meson\test cases\common\5 linkstatic
                                    self.environment.get_build_dir())  # C:\Users\$NAME\AppData\Local\Temp\tmp1iii95om
```

**Comment by jon-turney** [comment]
There are also other uses of `os.path.relpath` which also need addressing to fix this bug.
