### ISSUE TITLE
meson introspect fails when options.builddir is None

### ISSUE THREAD

**Issue by ghost** [mesonbuild/meson#3250]
In run(args)  (mesonbuild/mintro.py, line 202), options.builddir is checked to see if it is None, but cdata.load(options.builddir) is called anyway, resulting in:

```python
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 293, in run
    return mintro.run(remaining_args)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mintro.py", line 212, in run
    coredata = cdata.load(options.builddir)
  File "/usr/lib/python3.6/site-packages/mesonbuild/coredata.py", line 344, in load
    filename = os.path.join(build_dir, 'meson-private', 'coredata.dat')
```

I worked around it for now by inserting an else clause:

```python
def run(args):
    datadir = 'meson-private'
    options = parser.parse_args(args)
    if options.builddir is not None:
        datadir = os.path.join(options.builddir, datadir)
    else:
        options.builddir='./'
```

I'm using meson 0.45.0, Fedora 28 prerelease, with meson being called from gnome-builder 3.28.0.

**Comment by TingPing** [comment]
This behavior change breaks `gnome-builder`'s support

**Comment by aduskett** [comment]
Just wanted to say I ran into this problem as well.

**Comment by 1enn0** [comment]
can confirm as well, running up-to-date openSUSE Tumbleweed with meson 0.45.0 & gnome-builder 3.28.0.
