### ISSUE TITLE
executable() does not accept a script to run in test()

### ISSUE THREAD

**Issue by astavale** [mesonbuild/meson#3283]
The documentation for `executable()` states 'For instance, sources (.c, .cpp, .vala, .rs, etc) will be compiled, objects (.o, .obj) and libraries (.so, .dll, etc) will be linked, and all other files (headers, unknown extensions, etc) will be ignored'. I took 'ignored' to mean the file is accepted. This seemed like a good way of getting a test script to run. 

I'm exploring the Meson test runner interface. The test script is very simple :

```shell
#!/bin/sh
exit 1
```
and the `meson.build` file:

```meson
project( 'Failed test', 'vala', 'c' )
script_that_fails = executable( 'script_returns_fail', 'script_returns_fail' )
test( 'Script should always fail', script_that_fails )
```
With the command `meson setup builddir` I get the following traceback:
```

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mesonbuild/mesonmain.py", line 366, in run
    app.generate()
  File "/usr/lib/python3.4/site-packages/mesonbuild/mesonmain.py", line 151, in generate
    self._generate(env)
  File "/usr/lib/python3.4/site-packages/mesonbuild/mesonmain.py", line 209, in _generate
    g.generate(intr)
  File "/usr/lib/python3.4/site-packages/mesonbuild/backend/ninjabackend.py", line 215, in generate
    self.generate_target(t, outfile)
  File "/usr/lib/python3.4/site-packages/mesonbuild/backend/ninjabackend.py", line 460, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/usr/lib/python3.4/site-packages/mesonbuild/backend/ninjabackend.py", line 2164, in generate_single_compile
    compiler = get_compiler_for_source(target.compilers.values(), src)
  File "/usr/lib/python3.4/site-packages/mesonbuild/mesonlib.py", line 244, in get_compiler_for_source
    raise RuntimeError('No specified compiler can handle file {!s}'.format(src))
RuntimeError: No specified compiler can handle file script_fail

```
So is the documentation wrong and the file is not ignored? I was hoping that Meson would check the file exists and that it is executable and then ignore it because it was not compilable. Then it would be available as an executable to run through the test harness.

**Comment by jpakkane** [comment]
http://mesonbuild.com/Reference-manual.html#find_program
