### ISSUE TITLE
Error in 0.45 but no error in 0.29

### ISSUE THREAD

**Issue by lucianodato** [mesonbuild/meson#3292]
Hi, I'm having issues with a new version installed with pip3. This is my meson.build 

```
project(
    'noise-repellent',
    'c',
    default_options: 'c_std=c99'
)

#shared object name
lv2_name = 'nrepel'

#source to compile
src = 'src/nrepel.c'

#dependencies for noise repellent
nr_dep = [
    fftw_dep = dependency('fftw3f'),
    lv2_dep = dependency('lv2')
]

#compiler optimization flags
cflags = [
    '-msse',
    '-msse2',
    '-mfpmath=sse',
    '-ffast-math',
    '-fomit-frame-pointer',
    '-fno-finite-math-only'
]

#build configuration
shared_library(
    lv2_name,
    src,
    name_prefix: '',
    dependencies: nr_dep,
    c_args: cflags
)
```
This is the error output:
```
Build type: native build
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 189, in _generate
    intr = interpreter.Interpreter(b, g)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1431, in __init__
    self.load_root_meson_file()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreterbase.py", line 149, in load_root_meson_file
    self.ast = mparser.Parser(code, self.subdir).parse()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 452, in parse
    block = self.codeblock()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 688, in codeblock
    curline = self.line()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 682, in line
    return self.statement()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 457, in statement
    return self.e1()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 467, in e1
    value = self.e1()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 460, in e1
    left = self.e2()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 485, in e2
    left = self.e3()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 494, in e3
    left = self.e4()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 503, in e4
    left = self.e5()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 510, in e5
    return self.e5add()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 513, in e5add
    left = self.e5sub()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 519, in e5sub
    left = self.e5mod()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 525, in e5mod
    left = self.e5mul()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 531, in e5mul
    left = self.e5div()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 537, in e5div
    left = self.e6()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 547, in e6
    return self.e7()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 550, in e7
    left = self.e8()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 577, in e8
    args = self.args()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 599, in args
    a = ArgumentNode(s)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mparser.py", line 359, in __init__
    self.subdir = token.subdir
AttributeError: 'AssignmentNode' object has no attribute 'subdir'
```
I can't figure out what is happening. I'm sorry if this was an obvious error from my part, I'm learning this great build system. I'm forcing to update meson since I need to use name_prefix: '' and wasn't working with the older version. Thanks in advance!

**Comment by jpakkane** [comment]
```meson
nr_dep = [
    fftw_dep = dependency('fftw3f'),
    lv2_dep = dependency('lv2')
]
```

In Meson, assignment does not return the thing that was assigned. If you don't need the named variables, then do:

```meson
nr_dep = [
    fftw_dep = dependency('fftw3f'),
    lv2_dep = dependency('lv2')
]
```

If you do need them then you need to do it in two phases:

```meson
ftw_dep = dependency('fftw3f'),
lv2_dep = dependency('lv2')

nr_dep = [
    fftw_dep,
    lv2_dep,
]
```

**Comment by lucianodato** [comment]
That was it! Sorry for the inconvenience.Thanks!
