### ISSUE TITLE
Crash when using a file generated by configure_file as a content_file for gnome.gtkdoc

### ISSUE THREAD

**Issue by abderrahim** [mesonbuild/meson#3317]
The following `meson.build` reproduces the issue
```
project('bug', 'c')
gnome = import('gnome')

cdata = configuration_data()

cfile = configure_file(input: 'conffile.in',
  output: 'conffile',
  configuration: cdata)

gnome.gtkdoc('bug',
  src_dir: 'src',
  content_files: [cfile])
```
By running the following
```
$ touch conffile.in
$ meson.py build
$ ninja -C build bug-doc
```
I get
```
ninja: Entering directory `build'
[0/1] Running external command bug-doc.
Building documentation for bug
Traceback (most recent call last):
  File "/home/abderrahim/.local/bin/meson.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/abderrahim/meson/meson.py", line 26, in <module>
    sys.exit(main())
  File "/home/abderrahim/meson/meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/home/abderrahim/meson/mesonbuild/mesonmain.py", line 326, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/abderrahim/meson/mesonbuild/mesonmain.py", line 275, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/abderrahim/meson/mesonbuild/scripts/gtkdochelper.py", line 231, in run
    options.mode)
  File "/home/abderrahim/meson/mesonbuild/scripts/gtkdochelper.py", line 96, in build_gtkdoc
    abs_out, os.path.basename(f_abs)))
  File "/usr/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/abderrahim/meson-bug/conffile'
FAILED: meson-bug-doc 
```
obviously, the file should be `~/meson-bug/build/conffile` instead of `~/meson-bug/conffile`.

**Comment by bilboed** [comment]
Looks like it was introduced by this commit https://github.com/mesonbuild/meson/commit/f92d117becb21111d2c7f0f1f17e47d87c1184a1#diff-f0b2f77396eac67139fe2f2ed20db161

**Comment by inigomartinez** [comment]
I've pushed a [PR](https://github.com/mesonbuild/meson/pull/3360) that should fix half of the problem. However, as said in the [attached comment](https://github.com/mesonbuild/meson/pull/3360#issue-179171731), this issue still isn't solved due to another issue with `gtkdochelper` copying files.

**Comment by bilboed** [comment]
That pull request does fix this particular issue (at least for gstreamer). There are then other issues for which I'll file other bugs.
