### ISSUE TITLE
Traceback when installing GNOME Control Center using GNOME Builder

### ISSUE THREAD

**Issue by GeorgesStavracas** [mesonbuild/meson#3329]
When I open GNOME Control Center (git master) using GNOME Builder (git master) and click on the "Run" button, Meson 0.45.1 fails with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 211, in do_install
    install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 220, in install_subdirs
    for (src_dir, dst_dir, mode, exclude) in d.install_subdirs:
ValueError: too many values to unpack (expected 4)
FAILED: meson-install 
/usr/bin/python /usr/bin/meson --internal install /home/feaneron/.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-control-center/builds/default-host-gbsneto-object-storage/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

This does not happen on Meson 0.44.1.

**Comment by TingPing** [comment]
Can you test 0.45.1 just to ensure it wasn't fixed?

**Comment by GeorgesStavracas** [comment]
I actually tested with both 0.45.0 and 0.45.1, both are equally failing. Edited the original description to reflect that.

**Comment by eli-schwartz** [comment]
I cannot duplicate this with old versions of Meson and gnome-control-center. The code looks like it should have exactly the right number of values to unpack.

Anyway, the code is very different these days
