### ISSUE TITLE
windows: shared_library without exports caused stack trace on install

### ISSUE THREAD

**Issue by textshell** [mesonbuild/meson#3332]
When building a shared library on windows with a build file like this:
```
project('lib1', ['c'])

a = library('test-lib', 'lib.c', install: true)
```

But with 'lib.c' missing the `__declspec(dllexport)` the build step succeeds but when installing meson errors out with an exception. Throwing an exception here is quite unhelpful and lets the user suspect a problem with meson when in reality the error is in an incorrect project setup(i.e. missing defines or missing porting to windows)

```
[1/2] Compiling C object test-lib@sha/lib.c.obj.
[2/2] Linking target test-lib.dll.
ninja explain: deps for 'test-lib@sha/lib.c.obj' are missing
ninja explain: test-lib@sha/lib.c.obj is dirty
ninja explain: test-lib.dll is dirty

[0/1] Installing files.
Installing test-lib.dll to C:\Users\appveyor\AppData\Local\Temp\1\tmpet63x0r2\install/usr\bin\test-lib.dll
Installing pdb file test-lib.pdb to C:\Users\appveyor\AppData\Local\Temp\1\tmpet63x0r2\install/usr\bin\test-lib.pdb
Traceback (most recent call last):
  File "C:\\projects\\meson\\meson.py", line 26, in <module>
    sys.exit(main())
  File "C:\\projects\\meson\\meson.py", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "C:\projects\meson\mesonbuild\mesonmain.py", line 326, in run
    sys.exit(run_script_command(args[1:]))
  File "C:\projects\meson\mesonbuild\mesonmain.py", line 275, in run_script_command
    return cmdfunc(cmdargs)
  File "C:\projects\meson\mesonbuild\scripts\meson_install.py", line 397, in run
    do_install(datafilename)
  File "C:\projects\meson\mesonbuild\scripts\meson_install.py", line 216, in do_install
    install_targets(d)
  File "C:\projects\meson\mesonbuild\scripts\meson_install.py", line 327, in install_targets
    fname = check_for_stampfile(t[0])
  File "C:\projects\meson\mesonbuild\scripts\meson_install.py", line 315, in check_for_stampfile
    if os.stat(fname).st_size == 0:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'test-lib.lib'
FAILED: meson-install 
"C:\\python35\\python.exe" "C:\\projects\\meson\\meson.py" "--internal" "install" "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpet63x0r2\\meson-private\\install.dat"
ninja: build stopped: subcommand failed.
ninja explain: output PHONY of phony edge with no inputs doesn't exist
ninja explain: PHONY is dirty
ninja explain: meson-install is dirty
```

[This bug report was reconstructed from a CI build log, so it might have some inconsistencies]

**Comment by sarum9in** [comment]
Related: #3187

**Comment by cenomla** [comment]
Is there any progress on this issue? I am running into a case where I'm building dll files with no corresponding lib files and meson just crashes trying to install in that case.
