### ISSUE TITLE
Broken tests become spinning zombies

### ISSUE THREAD

**Issue by mikkelfj** [mesonbuild/meson#3348]
Running ninja -C build test on a test suite that has an infinite loop just hangs on OS-X, meson 0.45.1
Pressing ctrl+C dumps a trace but does not exit, a second ctrl+C exits. But one or more broken test processes remains active. After a few test runs all cores max out - assuming the tests are looping - just a basic C main() program.

```
^CTraceback (most recent call last):
  File "/usr/local/Cellar/meson/0.45.1/libexec/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/meson/0.45.1/libexec/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 288, in run
    return mtest.run(remaining_args)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 644, in run
    return th.doit()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 419, in doit
    self.run_tests(tests)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 554, in run_tests
    self.drain_futures(futures)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 570, in drain_futures
    self.print_stats(numlen, tests, name, result.result(), i)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 427, in result
    self._condition.wait(timeout)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
ninja: build stopped: interrupted by user.
```

**Comment by ssssam** [comment]
I think there's a more general issue here. I'm finding that hitting CTRL+C during `meson test` doesn't actually stop the test processes, instead it produces the backtrace shown above.

The issue is only really noticeable if your tests produce debug output and you are running with `meson test --verbose`, because the tests continue to write debug output to the console after `meson test` has exited and the shell prompt is back.

**Comment by psychon** [comment]
The following example reproduces the problem:
```python
#!/usr/bin/python

import subprocess
import concurrent.futures as conc

def do_it():
    p = subprocess.Popen(["/bin/sleep", "60"])
    try:
        p.communicate()
    except KeyboardInterrupt:
        print("Got CTRL-C (1) [This is where meson kills processes")

do_it()

executor = conc.ThreadPoolExecutor(max_workers = 42)
f = executor.submit(do_it)
try:
    f.result()
except KeyboardInterrupt:
    print("Got CTRL-C (2)")
```
Run this and press ctrl-C twice. The first press runs the exception handler in `do_it`, the second one does not. For meson this means that `_run_cmd` in `mtest.py` tries to catch `KeyboardInterrupt` to kill the started child process, but this code does not actually ever run. Thus, the child is not killed.

No idea how to fix this without lots of uglyness, since the use of a thread pool basically has to go (right?).

If you want to work around this: Add `is_parallel: false` to your test so that meson does not use a thread pool.

[Loosely related side note: Why does meson use `setsid()` instead of `setpgid(0, 0)`? The latter is enough to get a process into its own process group. Keeping the process in the session means that `SIGHUP` is also delivered to it when, well, a hang up happens. Shall I open a separate issue for that?]
[`setsid` comes from fixing #377, but that does not need a session]

**Comment by nirbheek** [comment]
> No idea how to fix this without lots of uglyness, since the use of a thread pool basically has to go (right?).

Getting rid of thread pool will likely also speed up the testing since it has a lot of overhead. We should probably just use `subprocess.Popen` and asynchronously handle process exits.

**Comment by bonzini** [comment]
Fixed by #7836 and more subsequent PRs.
