### ISSUE TITLE
test-suite failures with python 3.5

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#3478]
Version: 0.45.1

Trying to build meson for stretch results in the test-suite failing:
```
======================================================================
ERROR: test_vala_generated_source_buildir_inside_source_tree (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 2659, in test_vala_generated_source_buildir_inside_source_tree
    self.init(testdir)
  File "run_unittests.py", line 548, in init
    out = self._run(self.meson_command + args + extra_args)
  File "run_unittests.py", line 514, in _run
    raise subprocess.CalledProcessError(p.returncode, command)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/<<PKGBUILDDIR>>/meson.py', '--backend=ninja', '/tmp/tmpd1_rvorz/srctree', '/tmp/tmpd1_rvorz/srctree/subdir/_build', '--prefix', '/usr', '--libdir', '/usr/lib']' returned non-zero exit status 2

Stdout:
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 207, in _generate
    g.generate(intr)
  File "/<<PKGBUILDDIR>>/mesonbuild/backend/ninjabackend.py", line 219, in generate
    self.generate_target(t, outfile)
  File "/<<PKGBUILDDIR>>/mesonbuild/backend/ninjabackend.py", line 356, in generate_target
    vala_generated_sources = self.generate_vala_compile(target, outfile)
  File "/<<PKGBUILDDIR>>/mesonbuild/backend/ninjabackend.py", line 1171, in generate_vala_compile
    vala_c_file = os.path.join(vala_c_subdir, vala_c_file)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PurePosixPath'
```
The full build log is at
https://buildd.debian.org/status/fetch.php?pkg=meson&arch=all&ver=0.45.1-2~bpo9%2B1&stamp=1524726415&raw=0

This change was added in b2007217e0163fb42ef0e4452d44ae3392bccf55.
Stretch ships Python 3.5.3

**Comment by mbiebl** [comment]
I tried with 0.46.0 and it passed the test-suite. Any idea which commit fixed the issue?

**Comment by mbiebl** [comment]
it's apparently 942e34241f9b7430c56b9936c1309665662816bb
Sorry for the noise
