### ISSUE TITLE
Docker container ubuntu 18.04 from Mac: wrapdb fails with connection refused.

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#3492]
Hello.

This is working from my Mac in a native environment, but failing when using a Docker container for building. Not sure whether it is a Docker config problem but the fact is that I am downloading submodules and cloning a repo in previous steps and it does work, ssh included. The problem seems to be inside a wrap file I use for json library.

Meson version: 0.47.0dev1 (cloned from git) and 0.45 (installed from ubuntu). Both fail the same way.
Docker version: Docker version 17.12.0-ce, build c97c6d6
Mac OS High Sierra

```
Downloading json from https://github.com/nlohmann/json/archive/v2.1.1/json-2.1.1.tar.gz
Download size: 108615607
Downloading: ..........
Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/json/2.1.1/1/get_zip
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 197, in _generate
    intr.run()
  File "/usr/share/meson/mesonbuild/interpreter.py", line 2991, in run
    super().run()
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 202, in evaluate_statement
    return self.assignment(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 674, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 456, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 55, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1742, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1764, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 145, in resolve
    self.download(p, packagename)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 335, in download
    phash, tmpfile = self.get_data(purl)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 269, in get_data
    resp = open_wrapdburl(url)
  File "/usr/share/meson/mesonbuild/wrap/wrap.py", line 67, in open_wrapdburl
    return urllib.request.urlopen(urlstring)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/json/2.1.1/1/get_zip
SSL connection failed. Falling back to unencrypted connections.
The command '/bin/sh -c /home/tpi-service/meson/meson.py --prefix=/home/tpi-service/tpii-app /home/tpi-service/tpii /home/tpi-service/build' returned a non-zero code: 2
```

**Comment by jeandet** [comment]
@germandiagogomez did you try a simple `wget https://wrapdb.mesonbuild.com/v1/projects/json/2.1.1/1/get_zip`  from your container?

**Comment by germandiagogomez** [comment]
> @germandiagogomez did you try a simple wget https://wrapdb.mesonbuild.com/v1/projects/json/2.1.1/1/get_zip from your container?

Same problem. Seems to be a certificates installation problem. I installed ca-certificates but I think python and wget either do not find them or the certificate are not present in the package... Any idea? Does not seem to be a meson problem after all I think.

**Comment by jeandet** [comment]
@germandiagogomez , in fact https://wrapdb.mesonbuild.com isn't accessible, looks like wrapdb is down.

**Comment by germandiagogomez** [comment]
@jeandet any news on this front? Still not working I think :/

**Comment by jeandet** [comment]
@germandiagogomez , @ignatenkobrain is the guy who manage this server. From what I know there was an issue in the server room(in Russia), he is working on restoring the service. In the near future we should have wrapdb mirrors.

**Comment by germandiagogomez** [comment]
@jeandet thanks for the info! It is working now. I close this.
