### ISSUE TITLE
cannot connect to meson wrap

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/meson#3497]
I don't know what is wrong but meson wrap doesn't work

```
$ meson wrap list
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib64/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib64/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alberto/opt/lib/meson/bin/meson", line 4, in <module>
    __import__('pkg_resources').run_script('meson==0.47.0.dev1', 'meson')
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/EGG-INFO/scripts/meson", line 26, in <module>
    sys.exit(main())
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/EGG-INFO/scripts/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 293, in run
    return wraptool.run(remaining_args)
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/wrap/wraptool.py", line 204, in run
    list_projects()
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/wrap/wraptool.py", line 67, in list_projects
    projects = get_projectlist()
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/wrap/wraptool.py", line 62, in get_projectlist
    jd = get_result(API_ROOT + 'projects')
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/wrap/wraptool.py", line 52, in get_result
    u = open_wrapdburl(urlstring)
  File "/home/alberto/opt/lib/meson/lib64/python3.5/site-packages/meson-0.47.0.dev1-py3.5.egg/mesonbuild/wrap/wrap.py", line 67, in open_wrapdburl
    return urllib.request.urlopen(urlstring)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>
```

the same issue happens when trying to download a subproject, or install a `.wrap` file

**Comment by jeandet** [comment]
@asartori86 , wrapweb seems down, it should be back soon.

**Comment by germandiagogomez** [comment]
It is still down and affecting my work :(

**Comment by asartori86** [comment]
wrapweb is back

**Comment by CyberShadow** [comment]
Down again today.

**Comment by RafaGago** [comment]
Still down
