### ISSUE TITLE
Newline in target name breaks build dir permanently (ninja backend)

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#3522]
Minimal test case:

```bash
# Set up a minimal temporary project
cd "$(mktemp -d)"
mkdir mesontest && cd mesontest
meson init

# Important: let it generate a working build dir first.
meson builddir

# Intentionally break meson.build by introducing a newline to the target name.
sed -i "s/'mesontest'/'mesontest\\\\n'/" meson.build

# Try to build, this fails as it should.
# ERROR: Ninja does not support newlines in rules
ninja -C builddir

# Now undo the change to meson.build so that it's valid again.
sed -i "s/'mesontest\\\\n'/'mesontest'/" meson.build

# Try to build again, this time it'll fail even though meson.build is good.
ninja -C builddir
```

```
ninja: Entering directory `builddir'
[0/1] Regenerating build files.
Error during basic setup:

Something went terribly wrong. Please file a bug.
FAILED: build.ninja
/usr/bin/python3 /usr/bin/meson --internal regenerate /tmp/tmp.sWjjdMkrcp/mesontest /tmp/tmp.sWjjdMkrcp/mesontest/builddir --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

I encountered this bug because some of my target names depend on output from an external script, where I accidentally introduced a newline character to the output. It might be also worth investigating other instances where the build rules might fail to generate because of backend limitations to see if similar behavior occurs in those cases.

**Comment by Akaricchi** [comment]
This may be related to #3511

**Comment by nirbheek** [comment]
This is the backtrace:

```python
Traceback (most recent call last):
  File "/home/nirbheek/.bin/meson", line 26, in <module>
    sys.exit(main())
  File "/home/nirbheek/.bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/mesonmain.py", line 135, in generate
    self._generate(env)
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/mesonmain.py", line 201, in _generate
    g.generate(intr)
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 220, in generate
    self.generate_target(t, outfile)
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 468, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 2280, in generate_single_compile
    element.write(outfile)
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 96, in write
    line = 'build %s: %s %s' % (' '.join([ninja_quote(i, True) for i in self.outfilenames]),
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 96, in <listcomp>
    line = 'build %s: %s %s' % (' '.join([ninja_quote(i, True) for i in self.outfilenames]),
  File "/home/nirbheek/projects/meson/meson.git/mesonbuild/backend/ninjabackend.py", line 56, in ninja_quote
    raise MesonException(errmsg)
mesonbuild.mesonlib.MesonException: Ninja does not support newlines in rules. The content was:
```

So, basically any exception while generating the build file while doing a regen will leave the builddir unusable. It is the same as #3511.
