### ISSUE TITLE
Docker wrap fmt getting decode error under ubuntu 18.04 base image

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#3532]
Hello everyone,

I am trying to put a project under Docker, it uses meson to download. The thing is that when using without Docker in my Mac everything works ok. But this is the error I get under a dockerized image for Ubuntu 18.04. I have no clue of how I could fix this, maybe avoiding wrap directly, but I leave here the report just in case:

```
Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/fmt/4.1.0/1/get_zip
Download size: 1075
Downloading: ..........Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 197, in _generate
    intr.run()
  File "/usr/share/meson/mesonbuild/interpreter.py", line 2991, in run
    super().run()
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 173, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 456, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 79, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 2658, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 189, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 202, in evaluate_statement
    return self.assignment(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 674, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 200, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 456, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 47, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1673, in func_run_command
    return self.run_command_impl(node, args, kwargs)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1727, in run_command_impl
    self.environment.get_build_command() + ['introspect'], in_builddir)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 87, in __init__
    pc, self.stdout, self.stderr = self.run_command(cmd, args, source_dir, build_dir, subdir, mesonintrospect, in_builddir)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 109, in run_command
    p, o, e = Popen_safe(command_array, env=child_env, cwd=cwd)
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 722, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1558, in _communicate
    self.stderr.errors)
  File "/usr/lib/python3.6/subprocess.py", line 740, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 48: ordinal not in range(128)
```

**Comment by jpakkane** [comment]
Try setting `LANG=C.UTF-8`.

**Comment by germandiagogomez** [comment]
@jpakkane Yes I fixed it and indeed the problem was the locale. I used a utf-8 locale and everything worked. I think it would be a good idea to document this since Docker is a common deployment and compilation environment.

If you could tell me how to proceed I can add the documentation myself. I close the issue.
