### ISSUE TITLE
'Executable' object has no attribute 'vala_vapi' when using shared_module

### ISSUE THREAD

**Issue by Exalm** [mesonbuild/meson#3538]
See example repo: https://github.com/Exalm/meson_issue3538_demo

Current result: C program builds and runs fine:
```bash
> meson _build
The Meson build system
Version: 0.45.1
Source dir: /host/var/home/exalm/aa/c
Build dir: /host/var/home/exalm/aa/c/_build
Build type: native build
Project name: test
Native C compiler: cc (gcc 8.0.1 "cc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /bin/pkg-config (1.4.2)
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gmodule-2.0 found: YES 2.56.1
Build targets in project: 2
Found ninja-1.8.2 at /bin/ninja

> cd _build

> ninja
[4/4] Linking target libapp_module.so.
>LD_LIBRARY_PATH=. ./app
42
```

And Vala program crashes Meson:
```bash
> meson _build
The Meson build system
Version: 0.45.1
Source dir: /host/var/home/exalm/aa/vala
Build dir: /host/var/home/exalm/aa/vala/_build
Build type: native build
Project name: test
Native C compiler: cc (gcc 8.0.1 "cc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)")
Native Vala compiler: valac (valac 0.40.4)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /bin/pkg-config (1.4.2)
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gmodule-2.0 found: YES 2.56.1
Build targets in project: 2
Found ninja-1.8.2 at /bin/ninja
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 361, in run
    app.generate()
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 150, in generate
    self._generate(env)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 207, in _generate
    g.generate(intr)
  File "/usr/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 219, in generate
    self.generate_target(t, outfile)
  File "/usr/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 356, in generate_target
    vala_generated_sources = self.generate_vala_compile(target, outfile)
  File "/usr/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 1238, in generate_vala_compile
    dependency_vapis = self.determine_dep_vapis(target)
  File "/usr/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 1072, in determine_dep_vapis
    vapiname = dep.vala_vapi
AttributeError: 'Executable' object has no attribute 'vala_vapi'
```

Expected result: both programs behave the same way and output "42"

Steps to reproduce: clone the repo and run `reproduce.sh` script

Fedora 28, meson 0.45.1.

**Comment by nirbheek** [comment]
How do you tell valac that an executable will be `--export-dynamic` and that it should generate a vapi (and possibly a header) for it, and not warn about unused functions?

**Comment by nirbheek** [comment]
Well, even after fixing the issue you reported, I get this:

```meson
$ ninja -C _build/
ninja: Entering directory `_build/'
[1/6] Compiling Vala source ../app.vala.
../app.vala:5.1-5.12: warning: method `app_func' never used
int app_func () {
^^^^^^^^^^^^
Compilation succeeded - 1 warning(s)
[3/6] Compiling Vala source ../module.vala app.vapi.
FAILED: app_module@sha/module.c app_module.h app_module.vapi 
valac -C --debug --color=always --directory app_module@sha --basedir ../ --library app_module --header app_module.h --vapi ../app_module.vapi ../module.vala app.vapi
../module.vala:3.10-3.17: error: The name `app_func' does not exist in the context of `module_func'
  return app_func() + 1;
         ^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
[4/6] Linking target app.
ninja: build stopped: subcommand failed.
```

It looks like `app.vapi` and `app.h` don't actually contain any definitions, so `app_module` doesn't know what to link against. Can you tell me where that GNOME games meson port is? It's not in the upstream repo.

**Comment by nirbheek** [comment]
This is the branch in case you want to do some testing: https://github.com/mesonbuild/meson/tree/nirbheek/vala-shared-module-link

**Comment by Exalm** [comment]
Hmm, ok. It's quite possible there was some mistake in my `meson.build` as well, since I couldn't test it. :)
The GNOME Games port is here: https://gitlab.gnome.org/GNOME/gnome-games/merge_requests/26
There's currently a hack to make it build somehow, so the problem isn't there currently. I'll make another branch without a workaround now.

**Comment by Exalm** [comment]
Wait, it's actually `public int app_func () {` in the code, so I'm not sure where the error is from...

**Comment by nirbheek** [comment]
I fixed the `app_func()` prototype, and now I get:

```console
[3/6] Compiling Vala source ../module.vala app.vapi.
FAILED: app_module@sha/module.c app_module.h app_module.vapi 
valac -C --debug --color=always --directory app_module@sha --basedir ../ --library app_module --header app_module.h --vapi ../app_module.vapi ../module.vala app.vapi
../module.vala:2.1-2.15: warning: method `module_func' never used
int module_func () {
^^^^^^^^^^^^^^^
../module.vala:2.1-2.15: error: [ModuleInit] requires a parameter of type `GLib.TypeModule'
int module_func () {
^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 1 warning(s)
[4/6] Linking target app.
```

**Comment by Exalm** [comment]
There's no `[ModuleInit]` there. I know what happened, I fixed these 2 mistakes (and maybe a bit more, I don't remember) and did `git commit --amend`, and you have the old version.

**Comment by nirbheek** [comment]
Yep that fixes everything. Filed https://github.com/mesonbuild/meson/pull/3560, will be in the 0.46.1 stable release. Thanks for reporting and helping!

**Comment by Exalm** [comment]
Yay!
