### ISSUE TITLE
Cross GLEW Fail.

### ISSUE THREAD

**Issue by jsapparts** [mesonbuild/meson#355]
1 - When making cross-compiling I need to cross-compiling the libraries to? Or just compile and put in the pkg-config of mingw32?

2- When just compiling and added to pkg-config all others dependencies are found. but now glew has been found but produce a error that stops meson.

```
The Meson build system
Version: 0.27.0
Source dir: /home/carlos/Desktop/erathorn-game-client
Build dir: /home/carlos/Desktop/erathorn-game-client/build
Build type: cross build
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: Erathorn Client
Native cpp compiler: c++ (gcc 4.9.2-10)
Cross cpp compiler: /usr/bin/i586-mingw32msvc-g++ (gcc 4.9.1)
Dependency Boost (chrono, filesystem, system, thread, timer) found: YES (1.55)
Found pkg-config: /usr/bin/pkg-config (0.28)
Cross dependency lua5.1 found: YES 5.1.5
Cross dependency vorbis found: YES 1.3.5
Cross dependency physfs found: YES 2.0.3-2
Cross dependency libssl found: YES 1.1.0-pre2
Cross dependency glew found: YES 1.13.0
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 208, in run
    app.generate()
  File "/usr/local/bin/meson", line 160, in generate
    intr.run()
  File "/personaldata/opt/meson/interpreter.py", line 1029, in run
    self.evaluate_codeblock(self.ast)
  File "/personaldata/opt/meson/interpreter.py", line 1051, in evaluate_codeblock
    raise e
  File "/personaldata/opt/meson/interpreter.py", line 1045, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/personaldata/opt/meson/interpreter.py", line 1163, in evaluate_statement
    return self.assignment(cur)
  File "/personaldata/opt/meson/interpreter.py", line 1967, in assignment
    value = self.evaluate_statement(node.value)
  File "/personaldata/opt/meson/interpreter.py", line 1177, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/personaldata/opt/meson/interpreter.py", line 2244, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/personaldata/opt/meson/interpreter.py", line 1978, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/personaldata/opt/meson/interpreter.py", line 1978, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/personaldata/opt/meson/interpreter.py", line 1163, in evaluate_statement
    return self.assignment(cur)
  File "/personaldata/opt/meson/interpreter.py", line 1967, in assignment
    value = self.evaluate_statement(node.value)
  File "/personaldata/opt/meson/interpreter.py", line 1161, in evaluate_statement
    return self.function_call(cur)
  File "/personaldata/opt/meson/interpreter.py", line 1948, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/personaldata/opt/meson/interpreter.py", line 1566, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/personaldata/opt/meson/dependencies.py", line 1093, in find_external_dependency
    raise pkg_exc
  File "/personaldata/opt/meson/dependencies.py", line 1082, in find_external_dependency
    pkgdep = PkgConfigDependency(name, environment, kwargs)
  File "/personaldata/opt/meson/dependencies.py", line 132, in __init__
    raise RuntimeError('Could not generate cargs for %s.' % name)
RuntimeError: Could not generate cargs for glew.

```

**Comment by jpakkane** [comment]
If you mean dependencies you build yourself, then build and install them into the place where your pkg-config finds them.

For the latter, I committed a patch with some more logging which should help debugging the issue.

**Comment by jsapparts** [comment]
I mean like : I want to compile a software to Windows 7 32bits using Linux Debian 8.0 x86_64. I need to cross-compile them in someway to make it work, or compiling it on my arch would be ok to i586-mingw32  work with it?

And very thank you for your patch. I cloned git repository and try again. The error continues but now it only show the following output: 
```
...
......
Native cpp compiler: c++ (gcc 4.9.2-10)
Cross cpp compiler: /usr/bin/i586-mingw32msvc-g++ (gcc 4.9.1)
Dependency Boost (chrono, filesystem, system, thread, timer) found: YES (1.55)
Found pkg-config: /usr/bin/pkg-config (0.28)
Cross dependency lua5.1 found: YES 5.1.5
Cross dependency vorbis found: YES 1.3.5
Cross dependency physfs found: YES 2.0.3-2
Cross dependency libssl found: YES 1.1.0-pre2
Cross dependency glew found: YES 1.13.0

Meson encountered an error in file meson.build, line 39, column 0:
Could not generate cargs for glew:



```

And yes the output is just 2 clean lines. Also can someone say to me why meson found suitable to use boost that are in x86_64-linux-gnu libs folder but not found lua5.1 or lua 5.2 even using diferentes pkgconfig files that work good for native compilation?

**Comment by jsapparts** [comment]
Sorry. that's totally my error. When looking in dependencies.py I realize that the error is on --cflags and when I tried to reproduce the pkg-config output that it needs the glu.pc. I make a copy of glew.pc and edit to glu. it works great.
