### ISSUE TITLE
PermissionError when a test times out in OpenBSD

### ISSUE THREAD

**Issue by kernigh** [mesonbuild/meson#3569]
I run OpenBSD/amd64 6.3. This issue happened with OpenBSD's package of meson 0.45.0 and still happens with meson 0.47.0.dev1 from commit 8a9f7cf.

When a test times out, Meson shows a PermissionError, then gets stuck until the test finishes, then exits. Meson doesn't kill the test, doesn't give the name of the timed-out test, and doesn't run any more tests. While Meson is stuck, it ignores ^C SIGINT, but I can still use ^Z SIGTSTP to get a shell prompt. If the test doesn't finish, I need SIGTERM to kill Meson.

To reproduce, write a test that times out, as in this *meson.build* file:

```
project('example')
sleep = find_program('sleep')
test('siesta', sleep, args: '2', timeout: 1)
```

Then try to run it:

```
$ meson build
The Meson build system
Version: 0.47.0.dev1
Source dir: /home/kernigh/park/example
Build dir: /home/kernigh/park/example/build
Build type: native build
Project name: example
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program sleep found: YES (/bin/sleep)
Build targets in project: 0
Found ninja-1.8.2 at /usr/local/bin/ninja
$ ninja -C build test
ninja: Entering directory `build'                                              
[0/1] Running all tests.
Traceback (most recent call last):
  File "/home/kernigh/bin/meson", line 26, in <module>                         
    sys.exit(main())                                                           
  File "/home/kernigh/bin/meson", line 23, in main                             
    return mesonmain.run(sys.argv[1:], launcher)                               
  File "/home/kernigh/park/meson/mesonbuild/mesonmain.py", line 290, in run    
    return mtest.run(remaining_args)                                           
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 712, in run        
    return th.doit()                                                           
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 463, in doit       
    self.run_tests(tests)                                                      
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 621, in run_tests  
    self.drain_futures(futures)
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 637, in drain_future
s                        
    self.process_test_result(result.result())                                  
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in resu
lt                                                                             
    return self.__get_result() 
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __ge
t_result                
    raise self._exception         
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)                                
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 232, in run        
    return self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_arg
s)                                                                             
  File "/home/kernigh/park/meson/mesonbuild/mtest.py", line 307, in _run_cmd   
    os.killpg(os.getpgid(p.pid), signal.SIGKILL)                               
PermissionError: [Errno 1] Operation not permitted                             
FAILED: meson-test                                                             
/usr/local/bin/python3 -u /home/kernigh/bin/meson test --no-rebuild --print-erro
rlogs                                                                          
ninja: build stopped: subcommand failed.
```

The traceback suggests that getpgid(2) or killpg(3) failed. I trace the system calls with `ktrace -i ninja -C build test` and `kdump`. The trace shows that getpgid(2) failed:

```
 24750 python3.6 CALL  fork()
 24750 python3.6 RET   fork 58015/0xe29f
 58015 python3.6 RET   fork 0
...
 58015 python3.6 CALL  setsid()
 58015 python3.6 RET   setsid 58015/0xe29f
...
 58015 python3.6 CALL  execve(0x1ee0c4ca3630,0x1ee0c4c7bfd8,0x1ee0f7c09158)
 58015 python3.6 NAMI  "/bin/sleep"
 58015 python3.6 ARGS  
        [0] = "/bin/sleep"
        [1] = "2"
 58015 sleep    RET   execve 0
...
 24750 python3.6 CALL  getpgid(58015)
 24750 python3.6 RET   getpgid -1 errno 1 Operation not permitted
```

OpenBSD's manual for [getpgid(2)](https://man.openbsd.org/getpgid) says,

```
     [EPERM]            The current process and the process pid are not in the
                        same session.
```

The child had called setsid(2) before it executed /bin/sleep, so the parent and child were not in the same session. Therefore, the parent's call to getpgid(2) failed.

**Comment by kernigh** [comment]
I'm attaching the output of `./run_tests.py | tee testlog.txt` in OpenBSD. There are several failures, but I don't see this PermissionError among them.

[testlog.txt](https://github.com/mesonbuild/meson/files/2006442/testlog.txt)

After I made the testlog.txt, I made this change to meson:

```
diff --git a/mesonbuild/mtest.py b/mesonbuild/mtest.py
index 110a94e8..b4f9f402 100644
--- a/mesonbuild/mtest.py
+++ b/mesonbuild/mtest.py
@@ -304,7 +304,7 @@ class SingleTestRunner:
                 subprocess.call(['taskkill', '/F', '/T', '/PID', str(p.pid)])
             else:
                 try:
-                    os.killpg(os.getpgid(p.pid), signal.SIGKILL)
+                    os.killpg(p.pid, signal.SIGKILL)
                 except ProcessLookupError:
                     # Sometimes (e.g. with Wine) this happens.
                     # There's nothing we can do (maybe the process
```

This change fixes my time-out example. I believe that setsid(2) in BSD, [Linux](http://man7.org/linux/man-pages/man2/setsid.2.html), and [illumos](https://illumos.org/man/setsid) sets the process group ID to be equal to the process ID; therefore, `p.pid` is also the process group ID.

What if the test moves `p.pid` to a different process group? Then `killpg(p.pid, signal.SIGKILL)` wouldn't kill the test, but `killpg(os.getpgid(p.pid), signal.SIGKILL)` might kill other processes that aren't part of the test. I can only expect killpg() to work if the test stays in its own process group.

My fix does have one problem. The output from `ninja -C build test` is now too long, so I need to scroll up to learn that my test timed out.

```
$ ninja -C build test                                                
ninja: Entering directory `build'                                              
[0/1] Running all tests.                                                       
1/1 siesta                                  TIMEOUT  1.02 s                    
                                                                               
OK:         0                                                                  
FAIL:       1                                                                  
SKIP:       0                                                                  
TIMEOUT:    1                                                                  
                                                                               
                                                                               
The output from the failed tests:

1/1 siesta                                  TIMEOUT  1.02 s                    
                                                                               
--- command ---
LOGNAME='kernigh' XDG_RUNTIME_DIR='/var/run/user/1000' WINDOWID='25165827' HOME=
'/home/kernigh' XDG_DATA_DIRS='/usr/local/share:/usr/share' ACKDIR='/home/kernig
h/park/ack-build/staging' XDG_SESSION_COOKIE='pehcehwahn-1526397199.483714-94047
9227' EDITOR='mg' XDG_CONFIG_DIRS='/etc/xdg' MANPATH='/home/kernigh/prefix/share
/man:/home/kernigh/park/ack-build/staging/share/man::/usr/local/jdk-1.8.0/man' T
MUX='/tmp/tmux-1000/default,81435,0' SSH_AUTH_SOCK='/tmp/ssh-jbIRdGCcrMRP/agent.
75645' SHELL='/bin/ksh' COLORTERM='truecolor' TERM='screen' DBUS_SESSION_BUS_ADD
RESS='unix:path=/tmp/dbus-r5CBrIoygo,guid=d137af4dd30eb7243e3353a15afaf911' XDG_
MENU_PREFIX='xfce-' WINDOWPATH='ttyC4' PWD='/home/kernigh/park/example/build' GL
ADE_MODULE_PATH=':' LC_CTYPE='en_US.UTF-8' DISPLAY=':0.0' SSH_AGENT_PID='36355'
SESSION_MANAGER='local/pehcehwahn:/tmp/.ICE-unix/84383' XDG_CURRENT_DESKTOP='XFC
E' _='/usr/local/bin/ninja' GLADE_CATALOG_PATH=':' XFCE4_SESSION_WITH_CK='1' ENV
='/.//home/kernigh/.kshrc' PATH='/home/kernigh/bin:/home/kernigh/prefix/bin:/hom
e/kernigh/park/ack-build/staging/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bi
n:/usr/local/bin:/usr/local/sbin:/usr/games:/usr/local/jdk-1.8.0/bin' TMUX_PANE=
'%0' VTE_VERSION='5002' GLADE_PIXMAP_PATH=':' DESKTOP_SESSION='xfce' USER='kerni
gh' /bin/sleep 2                 
-------
                                                                               
Full log written to /home/kernigh/park/example/build/meson-logs/testlog.txt    
FAILED: meson-test
/usr/local/bin/python3 -u /home/kernigh/bin/meson test --no-rebuild --print-errorlogs                                                                           
ninja: build stopped: subcommand failed.                                        
```

**Comment by kernigh** [comment]
QEMU might or might not run BSD; FreeBSD/i386 in qemu-system-i386 worked for me, but NetBSD/macppc in qemu-system-ppc didn't work.

[rust-lang/libc runs FreeBSD and OpenBSD in QEMU in Travis](https://github.com/rust-lang/libc/tree/master/ci), but the project says, "the emulation is super slow." I suspect that QEMU is about 5 times slower than real hardware. [Meson on Travis](https://travis-ci.org/mesonbuild/meson) takes about 15 minutes; Meson on QEMU on Travis might take more than an hour, if Travis allows that much time. I'm guessing that Meson on QEMU on Travis would be too slow.

This benchmark *fib.bc* uses the slow recursive algorithm for Fibonacci numbers.

```
define f(n) {
    if (n < 2) return (n)
    return (f(n - 2) + f(n - 1))
}
f(30)
```

This is the benchmark with real hardware: PowerPC G4 (MPC7447A) at 1.33 GHz running Mac OS X 10.4.11. It takes about 20 seconds.

```
$ bc --version
bc 1.06
Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.
$ time bc </tmp/fib.bc
832040

real	0m22.211s
user	0m22.054s
sys	0m0.048s
```

This is the benchmark with qemu-system-ppc running Debian 8 (Linux 3.16.0); the host is AMD Phenom II X2 560 at 3.30 GHz running OpenBSD 6.3. It takes about 100 seconds.

```
$ bc --version
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
$ time bc </tmp/fib.bc
832040

real    1m40.410s
user    1m39.780s
sys     0m0.492s
```

**Comment by nirbheek** [comment]
... also our appveyor tests take upwards of an hour, so this still won't be the bottleneck.

**Comment by kernigh** [comment]
Meson has a test for this time-out bug in [manual tests/8 timeout](https://github.com/mesonbuild/meson/tree/master/manual%20tests/8%20timeout), but it is a manual test, so I guess the CI doesn't run it?

**Comment by kernigh** [comment]
I'm having trouble with Meson's tests. Both `./run_unittests.py` and `./run_project_tests.py` make too much output if more than a few tests are failing. That's why I use `./run_tests.py | tee testlog.txt`.

`./run_project_tests.py` starts by writing only 1 or 2 lines for each test, but at the end, it suddenly dumps a huge log to my terminal. This log is too big for my tmux, so I can't scroll back to the list of tests, so I can't identify the failing tests. There also isn't a summary that counts the failing tests or lists only the failing tests.

`./run_unittests.py` dumps a log whenever a test fails, so it is difficult to see more than the last few failures.
