### ISSUE TITLE
Vala cross compilation attempt crashes meson

### ISSUE THREAD

**Issue by zesterer** [mesonbuild/meson#370]
The title explains it all.

```
$ meson .. --cross-file ../cross-compile/win32.txt

The Meson build system
Version: 0.27.0
Source dir: /media/master-storage/Documents/Projects/opplyse
Build dir: /media/master-storage/Documents/Projects/opplyse/build-win32
Build type: cross build
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: opplyse
Native vala compiler: valac (unknown 0.30.0)
Cross vala compiler: valac (unknown 0.30.0)
Traceback (most recent call last):
  File "/usr/bin/meson", line 208, in run
    app.generate()
  File "/usr/bin/meson", line 160, in generate
    intr.run()
  File "/usr/share/meson/interpreter.py", line 1029, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/share/meson/interpreter.py", line 1051, in evaluate_codeblock
    raise e
  File "/usr/share/meson/interpreter.py", line 1045, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/share/meson/interpreter.py", line 1161, in evaluate_statement
    return self.function_call(cur)
  File "/usr/share/meson/interpreter.py", line 1948, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/share/meson/interpreter.py", line 69, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/share/meson/interpreter.py", line 1393, in func_project
    self.add_languages(node, args[1:])
  File "/usr/share/meson/interpreter.py", line 1502, in add_languages
    self.build.add_cross_compiler(cross_comp)
  File "/usr/share/meson/build.py", line 96, in add_cross_compiler
    self.static_cross_linker = self.environment.detect_static_linker(compiler)
  File "/usr/share/meson/environment.py", line 461, in detect_static_linker
    if compiler.is_cross:
AttributeError: 'ValaCompiler' object has no attribute 'is_cross'
```

**Comment by jpakkane** [comment]
Do you know if cross compiling Vala requires any special flags or binaries or is all the cross part delegated to the generated C files?

**Comment by zesterer** [comment]
I believe it is up to C to compile cross-platform things. Vala is just a translator program providing a conversion from one portable language (Vala) to another portable language (C).

**Comment by zesterer** [comment]
By the way... I know this isn't the place to say it, but thank your for building meson. In my (admittedly limited) experience, it kicks the ass of alternatives like autotools, CMake and make. I'm gradually migrating all of my C, C++ and Vala projects over to it.

**Comment by SkyzohKey** [comment]
Hey, bumping this issue.
First, thanks for this awesome build system !

I have the same issue than @zesterer when trying to compile my app for Windows. :/
Here's the (same?) backtrace:
```
→ meson . win_build --cross-file cross_win.txt                        [d6b32ec]
The Meson build system
Version: 0.26.0
Source dir: /home/skyzohkey/Dev/Vala/ValaTox/Ricin
Build dir: /home/skyzohkey/Dev/Vala/ValaTox/Ricin/win_build
Build type: cross build
Build machine cpu: x86_64
Host machine cpu: i686
Target machine cpu: i686
Project name: Ricin
Native vala compiler: valac (unknown 0.30.0)
Cross vala compiler: valac (unknown 0.30.0)
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 208, in run
    app.generate()
  File "/usr/local/bin/meson", line 149, in generate
    intr.run()
  File "/usr/local/share/meson/interpreter.py", line 954, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/share/meson/interpreter.py", line 976, in evaluate_codeblock
    raise e
  File "/usr/local/share/meson/interpreter.py", line 970, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/share/meson/interpreter.py", line 1039, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/share/meson/interpreter.py", line 1747, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/local/share/meson/interpreter.py", line 67, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/local/share/meson/interpreter.py", line 1231, in func_project
    self.add_languages(node, args[1:])
  File "/usr/local/share/meson/interpreter.py", line 1328, in add_languages
    self.build.add_cross_compiler(cross_comp)
  File "/usr/local/share/meson/build.py", line 96, in add_cross_compiler
    self.static_cross_linker = self.environment.detect_static_linker(compiler)
  File "/usr/local/share/meson/environment.py", line 460, in detect_static_linker
    if compiler.is_cross:
AttributeError: 'ValaCompiler' object has no attribute 'is_cross'
```

**Comment by jpakkane** [comment]
I've been busy but I'll try to get this fixed at some point.
