### ISSUE TITLE
wrapdb.mesonbuild.com SSL certificate expired

### ISSUE THREAD

**Issue by vramana** [mesonbuild/meson#3722]
![image](https://user-images.githubusercontent.com/3112509/41189118-50389b18-6be6-11e8-9285-6712083f29e0.png)

I could not find the url on anywhere in meson documentation or by googling. I had to look through wrapweb source files and then I found it. I spent atleast 40 mins on this bug since the `meson wrap list` emits a very unhelful error message. It just says SSL certificate verification failed. I would be nicer to print out the url host it's trying to connect.

<details>
 <summary>meson wrap list error message</summary>

```
meson wrap list                     
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ramana/.local/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/home/ramana/.local/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 305, in run
    return wraptool.run(remaining_args)
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 204, in run
    list_projects()
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 67, in list_projects
    projects = get_projectlist()
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 62, in get_projectlist
    jd = get_result(API_ROOT + 'projects')
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 52, in get_result
    u = open_wrapdburl(urlstring)
  File "/home/ramana/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 67, in open_wrapdburl
    return urllib.request.urlopen(urlstring)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

```
</details>

----

Anyway thanks for making meson.

**Comment by vramana** [comment]
It seems the certificate got renewed.

**Comment by sandraiser** [comment]
it expired again :(
