### ISSUE TITLE
gtkdoc error: missing include paths

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#3772]
It seems that the current master branch of meson misses some -I flags when passing --cflags to gtkdoc-scangobj. I found it affects atk and clutter-gtk.

```
Running custom install script '/usr/local/bin/python3 /usr/home/lantw44/gnome/devinstall/bin/meson --internal gtkdoc --sourcedir=/usr/home/lantw44/gnome/source/atk --builddir=/usr/home/lantw44/gnome/build/atk --subdir=docs --headerdirs=/usr/home/lantw44/gnome/source/atk/atk@@/usr/home/lantw44/gnome/build/atk/atk --mainfile=atk-docs.xml --modulename=atk --mode=auto --scanargs=--rebuild-types@@--deprecated-guards=ATK_DISABLE_DEPRECATED@@--ignore-decorators=_ATK_EXTERN@@--ignore-headers=atkmarshal.h atkintl.h --gobjects-types-file=/usr/home/lantw44/gnome/source/atk/docs/atk.types --fixxrefargs=--html-dir=/home/lantw44/gnome/devinstall/share/gtk-doc/html@@--extra-dir=/home/lantw44/gnome/devinstall/share/gtk-doc/html/glib@@--extra-dir=/home/lantw44/gnome/devinstall/share/gtk-doc/html/gobject --mkdbargs=--output-format=xml --content-files= --cflags=-I/usr/home/lantw44/gnome/build/atk/atk/. -I/usr/home/lantw44/gnome/source/atk/atk/. -I/home/lantw44/gnome/devinstall/include/glib-2.0 -I/home/lantw44/gnome/devinstall/lib/glib-2.0/include -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -Og --ldflags=-L/usr/home/lantw44/gnome/build/atk/atk -Wl,-rpath,/usr/home/lantw44/gnome/build/atk/atk -latk-1.0 -L/home/lantw44/gnome/devinstall/lib /home/lantw44/gnome/devinstall/lib/libgobject-2.0.so /home/lantw44/gnome/devinstall/lib/libglib-2.0.so -lintl -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -Og -L/usr/local/lib --cc=clang --ld=clang'
Building documentation for atk
ERROR: 
Error in gtkdoc helper script:

ERROR: 'gtkdoc-scangobj' failed with status 1
atk-scan.c:7:10: fatal error: 'atk/atk.h' file not found
#include <atk/atk.h>
         ^~~~~~~~~~~
1 error generated.
2018-06-21 00:04:36,696:scangobj.py:execute_command:1196:WARNING:Compiling scanner failed: 1, command: clang -I/usr/home/lantw44/gnome/build/atk/atk/. -I/usr/home/lantw44/gnome/source/atk/atk/. -I/home/lantw44/gnome/devinstall/include/glib-2.0 -I/home/lantw44/gnome/devinstall/lib/glib-2.0/include -march=corei7 -B/home/lantw44/.local/bin -pipe -g3 -Og -c -o atk-scan.o atk-scan.c

FAILED: meson-install 
/usr/local/bin/python3 /usr/home/lantw44/gnome/devinstall/bin/meson --internal install /usr/home/lantw44/gnome/build/atk/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

**Comment by xclaesse** [comment]
Could it be that PR #3746 already fixed this?

**Comment by lantw44** [comment]
No, this test was done on the master branch which already includes #3746.

**Comment by xclaesse** [comment]
Tried to build atk doc but I get this:
```
Building documentation for atk
ERROR: 
Error in gtkdoc helper script:

ERROR: 'gtkdoc-scan' failed with status 1
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-scan", line 59, in <module>
    scan.Run(options)
  File "/usr/share/gtk-doc/python/gtkdoc/scan.py", line 78, in Run
    ScanHeaders(dir, section_list, decl_list, get_types, options)
  File "/usr/share/gtk-doc/python/gtkdoc/scan.py", line 140, in ScanHeaders
    ScanHeader(fullname, section_list, decl_list, get_types, options)
  File "/usr/share/gtk-doc/python/gtkdoc/scan.py", line 229, in ScanHeader
    for line in common.open_text(input_file):
  File "/usr/lib/python2.7/codecs.py", line 701, in next
    return self.reader.next()
  File "/usr/lib/python2.7/codecs.py", line 632, in next
    line = self.readline()
  File "/usr/lib/python2.7/codecs.py", line 547, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python2.7/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 0: invalid continuation byte
```

**Comment by xclaesse** [comment]
Hm, I don't know what happened, it was for atk/atkversion.h which is a generated header, and rebuilding fixed that problem.

This bug is actually fixed as a totally unexpected side effect of PR #3775, atk.types in source tree had `#include <atk/atk.h>` but not the one generated in build dir.

**Comment by xclaesse** [comment]
Note that the reason why `atk/atk.h` was not found is because CFLAGS contains `-I../atk/.` relative to top build dir, so it should have been `#include <atk.h>` instead. And that's not meson issue because atk/meson.build defines libatk_dep with `include_directories('.')`.

**Comment by lantw44** [comment]
> atk.types in source tree had #include <atk/atk.h> but not the one generated in build dir.

You are right. The same thing also happens in clutter-gtk. I am doing a build test now, and I will close this issue if no similar issue is found.

**Comment by xclaesse** [comment]
Those .types files should probably be removed from git since gtkdoc regenerate them anyway, no?

**Comment by lantw44** [comment]
Yes, they should be removed and it is not a problem of meson. I just want to make sure I cannot find similar issues before closing it.
