### ISSUE TITLE
Weird error message upon executing meson build command

### ISSUE THREAD

**Issue by stefanos82** [mesonbuild/meson#3804]
Specs:
```txt
Meson: 0.46.1
OS: GNU / Linux Debian testing, 64-bit
```
I initialized an existing project, then edited my `meson.build` file with the following syntax:
```py
project(
    'shuffle',
    'c',
    version : '0.1',
    default_options : [
        c_std='c89',
        'warning_level=3'
    ]
)

sources = ['src/main.c']
inc = include_directories('include')

executable(
    'shuffle',
    sources,
    include_directories : inc,
    install : true
)

```
Then I run `meson --buildtype debug builddebug`.

This is what it threw at my terminal:
```sh
meson --buildtype debug builddebug
The Meson build system
Version: 0.46.1
Source dir: /home/stefanos/tmp/c_projects/shuffle
Build dir: /home/stefanos/tmp/c_projects/shuffle/builddebug
Build type: native build
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 135, in generate
    self._generate(env)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 174, in _generate
    intr = interpreter.Interpreter(b, g)
  File "/usr/share/meson/mesonbuild/interpreter.py", line 1603, in __init__
    self.load_root_meson_file()
  File "/usr/share/meson/mesonbuild/interpreterbase.py", line 191, in load_root_meson_file
    self.ast = mparser.Parser(code, self.subdir).parse()
  File "/usr/share/meson/mesonbuild/mparser.py", line 476, in parse
    block = self.codeblock()
  File "/usr/share/meson/mesonbuild/mparser.py", line 712, in codeblock
    curline = self.line()
  File "/usr/share/meson/mesonbuild/mparser.py", line 706, in line
    return self.statement()
  File "/usr/share/meson/mesonbuild/mparser.py", line 481, in statement
    return self.e1()
  File "/usr/share/meson/mesonbuild/mparser.py", line 484, in e1
    left = self.e2()
  File "/usr/share/meson/mesonbuild/mparser.py", line 509, in e2
    left = self.e3()
  File "/usr/share/meson/mesonbuild/mparser.py", line 518, in e3
    left = self.e4()
  File "/usr/share/meson/mesonbuild/mparser.py", line 527, in e4
    left = self.e5()
  File "/usr/share/meson/mesonbuild/mparser.py", line 534, in e5
    return self.e5add()
  File "/usr/share/meson/mesonbuild/mparser.py", line 537, in e5add
    left = self.e5sub()
  File "/usr/share/meson/mesonbuild/mparser.py", line 543, in e5sub
    left = self.e5mod()
  File "/usr/share/meson/mesonbuild/mparser.py", line 549, in e5mod
    left = self.e5mul()
  File "/usr/share/meson/mesonbuild/mparser.py", line 555, in e5mul
    left = self.e5div()
  File "/usr/share/meson/mesonbuild/mparser.py", line 561, in e5div
    left = self.e6()
  File "/usr/share/meson/mesonbuild/mparser.py", line 571, in e6
    return self.e7()
  File "/usr/share/meson/mesonbuild/mparser.py", line 577, in e7
    args = self.args()
  File "/usr/share/meson/mesonbuild/mparser.py", line 634, in args
    a.set_kwarg(s.value, self.statement())
  File "/usr/share/meson/mesonbuild/mparser.py", line 481, in statement
    return self.e1()
  File "/usr/share/meson/mesonbuild/mparser.py", line 484, in e1
    left = self.e2()
  File "/usr/share/meson/mesonbuild/mparser.py", line 509, in e2
    left = self.e3()
  File "/usr/share/meson/mesonbuild/mparser.py", line 518, in e3
    left = self.e4()
  File "/usr/share/meson/mesonbuild/mparser.py", line 527, in e4
    left = self.e5()
  File "/usr/share/meson/mesonbuild/mparser.py", line 534, in e5
    return self.e5add()
  File "/usr/share/meson/mesonbuild/mparser.py", line 537, in e5add
    left = self.e5sub()
  File "/usr/share/meson/mesonbuild/mparser.py", line 543, in e5sub
    left = self.e5mod()
  File "/usr/share/meson/mesonbuild/mparser.py", line 549, in e5mod
    left = self.e5mul()
  File "/usr/share/meson/mesonbuild/mparser.py", line 555, in e5mul
    left = self.e5div()
  File "/usr/share/meson/mesonbuild/mparser.py", line 561, in e5div
    left = self.e6()
  File "/usr/share/meson/mesonbuild/mparser.py", line 571, in e6
    return self.e7()
  File "/usr/share/meson/mesonbuild/mparser.py", line 574, in e7
    left = self.e8()
  File "/usr/share/meson/mesonbuild/mparser.py", line 601, in e8
    args = self.args()
  File "/usr/share/meson/mesonbuild/mparser.py", line 623, in args
    a = ArgumentNode(s)
  File "/usr/share/meson/mesonbuild/mparser.py", line 383, in __init__
    self.subdir = token.subdir
AttributeError: 'AssignmentNode' object has no attribute 'subdir'
```
Is it something I did wrong by mistake?

Please advice, thank you.

**Comment by stefanos82** [comment]
False alarm everyone, my bad.

My issue was with `c_std='c89'`; it should have been `'c_std=c99'`.

Again, my apologies.

Mistakes happen :man_shrugging:
