### ISSUE TITLE
Unhandled exception when passing a program object that wasn't found to run_target

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#3817]
```meson
project('bad_run_target', 'c')

bad_program = find_program('xxxdoesnotexistxxx', required : false)
run_target('bad target', command : [bad_program])
```

```
The Meson build system
Version: 0.47.0.dev1
Source dir: /tmp/mesontest/bad_run_target
Build dir: /tmp/mesontest/bad_run_target/builddir
Build type: native build
Project name: bad_run_target
Project version: undefined
Native C compiler: ccache cc (gcc 8.1.1 "cc (SUSE Linux) 8.1.1 20180523 [gcc-8-branch revision 260570]")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program xxxdoesnotexistxxx found: NO
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 339, in run
    app.generate()
  File "/data/git/meson/mesonbuild/mesonmain.py", line 114, in generate
    self._generate(env)
  File "/data/git/meson/mesonbuild/mesonmain.py", line 163, in _generate
    intr.backend.generate(intr)
  File "/data/git/meson/mesonbuild/backend/ninjabackend.py", line 220, in generate
    self.generate_target(t, outfile)
  File "/data/git/meson/mesonbuild/backend/ninjabackend.py", line 323, in generate_target
    self.generate_run_target(target, outfile)
  File "/data/git/meson/mesonbuild/backend/ninjabackend.py", line 616, in generate_run_target
    cmd = self.replace_paths(target, cmd)
  File "/data/git/meson/mesonbuild/backend/ninjabackend.py", line 1880, in replace_paths
    for x in args]
  File "/data/git/meson/mesonbuild/backend/ninjabackend.py", line 1880, in <listcomp>
    for x in args]
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by eli-schwartz** [comment]
This was fixed in #3818 but with a self-referential bug reference that accidentally did not point here.
