### ISSUE TITLE
Meson/Ninja Build Failure

### ISSUE THREAD

**Issue by Partha1b** [mesonbuild/meson#4052]
Using the provided 64-bit MSI installer. Installed on `D:\Msys-Platform\Meson`
Running under msys shell. I'm building `gdk-pixbuf-2.37.0`. My command-line is:
`meson builddir --prefix=/opt --buildtype=release && cd builddir`
Then Error message is:
```
$ ninja
[8/155] Generating gdk-pixbuf-enum-types.h with a meson_exe.py custom command.
FAILED: gdk-pixbuf/gdk-pixbuf-enum-types.h
"D:/Msys-Platform/Meson/meson.exe" "--internal" "exe" "Z:/src/builds/gdk-pixbuf-2.37.0/builddir/meson-private/meson_exe_python_de4a50035d4ec34c7435137fb6450d5e23a25119.dat"
Traceback (most recent call last):
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meson.py", line 29, in <module>
  File "mesonbuild\mesonmain.py", line 379, in main
  File "mesonbuild\mesonmain.py", line 316, in run
  File "mesonbuild\mesonmain.py", line 232, in run_script_command
  File "mesonbuild\scripts\meson_exe.py", line 91, in run
  File "mesonbuild\scripts\meson_exe.py", line 73, in run_exe
  File "C:\python\lib\subprocess.py", line 709, in __init__
  File "C:\python\lib\subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[17/155] Generating pixbuf-scale.test with a custom command.
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment]
Are you using MSYS or MSYS2? If MSYS2, please install meson using `pacman` and not the MSI installer. The MSI installer uses Windows-native Python which cannot understand MSYS2 paths.

**Comment by stefan0xC** [comment]
You can find packages with `pacman -Ss` and install them with `pacman -S`. `pacman -U` is for installing a package file directly. To install meson with msys2 you should probably use `pacman -S meson`
See https://github.com/msys2/msys2/wiki/Using-packages

**Comment by nirbheek** [comment]
Meson is an arch-specific package:

```console
$ pacman -Ss meson
mingw32/mingw-w64-i686-meson 0.44.1-1 [installed]
    High-productivity build system (mingw-w64)
mingw64/mingw-w64-x86_64-meson 0.44.1-1 [installed]
    High-productivity build system (mingw-w64)
```

One would install one of those two depending on whether one wants 32-bit or 64-bit.

For instance: `pacman -S mingw64/mingw-w64-x86_64-meson`

(my pacman db is out of date, those are not the latest versions packaged for MSYS2)

**Comment by frozenpandaman** [comment]
Any updates?

**Comment by bonzini** [comment]
Closing as it's more of a support request. Use discussions if still relevant.
