### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#4059]
While running the test suite for git master, I got the following error message:
```
Traceback (most recent call last):
  File "/tmp/meson/mesonbuild/mesonmain.py", line 353, in run
    app.generate()
  File "/tmp/meson/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/tmp/meson/mesonbuild/mesonmain.py", line 146, in _generate
    intr.run()
  File "/tmp/meson/mesonbuild/interpreter.py", line 3719, in run
    super().run()
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 411, in evaluate_statement
    return self.assignment(cur)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 946, in assignment
    value = self.evaluate_statement(node.value)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/meson/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/meson/mesonbuild/interpreter.py", line 2908, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/tmp/meson/mesonbuild/dependencies/base.py", line 1311, in find_external_dependency
    mlog.log(type_text, mlog.bold(display_name), details + 'found:', mlog.green('YES'), d.version + info)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
 ```
This is in a Debian stretch build chroot with Python 3.5.
I didn't see such an error with 0.47.1

**Comment by mbiebl** [comment]
Small correction: This is git master + PR #3981

**Comment by mbiebl** [comment]
This makes ```test cases/frameworks/18 vulkan``` fail fwiw

**Comment by GoaLitiuM** [comment]
Is this an issue in master or my PR? I moved the fix for your previous issue to #4058 so try that one instead.

**Comment by mbiebl** [comment]
Full build log attached: 
[meson-git-log.txt](https://github.com/mesonbuild/meson/files/2300926/meson-git-log.txt)

**Comment by mbiebl** [comment]
I will have to test with a pristine git master to see if it's caused by #3981.

**Comment by mbiebl** [comment]
This will have to wait until tomorrow

**Comment by mbiebl** [comment]
Ok, happens with git master (4a30f729) i.e. without the PRS as well

**Comment by eli-schwartz** [comment]
Was this ever properly investigated? Is it still an issue? If it is still an issue, how can one actually expose the issue given it is plainly not occurring in CI?

**Comment by dcbaker** [comment]
Do we have mypy type checking in dependencies yet? mypy would catch this

**Comment by mensinda** [comment]
This old code path is gone now (or will be soon with #9299) anyway with the recent primitive holder refactorings.

**Comment by eli-schwartz** [comment]
Good enough for me.

Seizing the opportunity to close this old bug and unreproducible bug.
