### ISSUE TITLE
Decoding issue. 

### ISSUE THREAD

**Issue by pavlosun** [mesonbuild/meson#4074]
Hi,
I am working on project [libgda](https://gitlab.gnome.org/GNOME/libgda). By building documentation for the project i reproducible get the following error. I use meson 0.47.1. I am not sure what information you need, but let me know and I will try to provide it. 
Thanks.

`Traceback (most recent call last):
  File "/home/pavlo/jhbuild/install/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 316, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 243, in run
    options.mode)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 185, in build_gtkdoc
    gtkdoc_run_check(mkhtml_cmd, os.path.join(abs_out, 'html'))
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 55, in gtkdoc_run_check
    p, out = Popen_safe(cmd, cwd=cwd, env=env, stderr=subprocess.STDOUT)[0:2]
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 842, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.6/subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 8688-8689: invalid continuation byte
FAILED: meson-libgda-6.0-doc 
`

**Comment by bonzini** [comment]
Probably gtkdoc should use `errors='replace'`, because otherwise warnings/errors that refer to invalid UTF-8 are not visible at all.
