### ISSUE TITLE
Issue while trying to `meson . build`

### ISSUE THREAD

**Issue by SkyzohKey** [mesonbuild/meson#421]
A friend tried to compile Ricin but ended up with the following issue:
I know he is running Ubuntu 15.04. 

```
$ meson . build
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 17, in <module>
    from mesonbuild import mesonmain
  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/mesonmain.py", line 20, in <module>
    from . import environment, interpreter, mesonlib
  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/environment.py", line 17, in <module>
    from .compilers import *
  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/compilers.py", line 18, in <module>
    from . import mlog
  File "/usr/local/lib/python2.7/dist-packages/mesonbuild/mlog.py", line 73
    print(*arr, file=log_file, **kwargs) # Log file never gets ANSI codes.
          ^
SyntaxError: invalid syntax
```

**Comment by jpakkane** [comment]
According to this:

    File "/usr/local/lib/python2.7/dist-packages/mesonbuild/mlog.py", line 73

He is running it under Python 2. This most likely means that the installation has been done incorrectly.

**Comment by SkyzohKey** [comment]
Ah! I see... Thanks for the fast reply!
