### ISSUE TITLE
i18n generates .gmo files at install time, breaking rebuilds by the user

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#4217]
When I run `nina -C build && sudo ninja -C build install` I end up with a bunch of files owned by root. This seems bad because:
- the build phase is not complete, I would expect install to just copy stuff around, not to generate new things.
- if I subsequently run `ninja install` as non-root, it will fail (for example `DESTDIR=/var/tmp/inst ninja -C build install`)

I get the following traceback:
```console
$ DESTDIR=/var/tmp/inst2 ninja -C build install
...
Running custom install script '/usr/bin/python3 /usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=systemd'
msgfmt: error while opening "/home/zbyszek/src/systemd-work2/build/po/be.gmo" for writing: Permission denied
Traceback (most recent call last):
  File "/usr/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 316, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/gettext.py", line 118, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/gettext.py", line 66, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "/usr/lib64/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', '/home/zbyszek/src/systemd-work2/po/be.po', '-o', '/home/zbyszek/src/systemd-work2/build/po/be.gmo']' returned non-zero exit status 1.
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by QuLogic** [comment]
While I don't like this either, running `ninja install` should invoke `pkcon` to get permissions, so you don't need to run with `sudo`.

**Comment by keszybz** [comment]
Well, I think using `pkcon` to get privs would be an interesting approach, it's really not relevant to the problem here. This bug is about missing dependencies on the `gmo` files from the "all" target.

**Comment by Hi-Angel** [comment]
Indeed, the `.gmo` files not being regenerated by `ninja -C build`, IOW being outdated, just costed me 4-5 hours of debugging *(that wasn't only reason, but if it worked, I wouldn't have to do a bunch of other stuff)*.
