### ISSUE TITLE
Regression finding external dependencies for Fortran

### ISSUE THREAD

**Issue by richli** [mesonbuild/meson#4223]
I have a Fortran project that uses an external dependency. It seems that this no longer works. Here is a minimal example `meson.build` that fails:

```meson
project('hello', 'fortran')
executable('hello', dependencies : dependency('netcdf'))
```

Here are the outputs of `meson . build` with two versions of meson:

```
The Meson build system
Version: 0.46.1
Source dir: /home/richli/test
Build dir: /home/richli/test/build
Build type: native build
Project name: hello
Native Fortran compiler: gfortran (gcc 8.2.1 "GNU Fortran (GCC) 8.2.1 20180831")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.5.3)
Native dependency netcdf found: YES 4.6.1
Build targets in project: 1
Found ninja-1.8.2 at /home/richli/.local/miniconda3/envs/meson/bin/ninja
```

```
The Meson build system
Version: 0.47.2
Source dir: /home/richli/test
Build dir: /home/richli/test/build
Build type: native build
Project name: hello
Project version: undefined
Native Fortran compiler: gfortran (gcc 8.2.1 "GNU Fortran (GCC) 8.2.1 20180831")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.5.3)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 351, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 146, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3699, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 691, in function_call
    (posargs, kwargs) = self.reduce_arguments(node.args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 928, in reduce_arguments
    reduced_kw[key] = self.evaluate_statement(a)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 699, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2897, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 1162, in find_external_dependency                                                                                                 
    raise pkg_exc
  File "/usr/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 1149, in find_external_dependency                                                                                                 
    pkgdep = PkgConfigDependency(name, env, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 505, in __init__
    self._set_libs()
  File "/usr/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 719, in _set_libs
    self.link_args, self.raw_link_args = self._search_libs(out, out_raw)
  File "/usr/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 648, in _search_libs
    libpaths, libtype)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/fortran.py", line 198, in find_library
    return self.find_library_impl(libname, env, extra_dirs, code, libtype)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/fortran.py", line 192, in find_library_impl                                                                                                         
    return CCompiler.find_library_impl(self, *args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/c.py", line 975, in find_library_impl
    value = self.find_library_real(libname, env, extra_dirs, code, libtype)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/fortran.py", line 189, in find_library_real                                                                                                         
    return CCompiler.find_library_real(self, *args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/c.py", line 955, in find_library_real
    trial = self._get_trials_from_pattern(p, d, libname)
AttributeError: 'GnuFortranCompiler' object has no attribute '_get_trials_from_pattern'
```
Changing the language to C works (i.e., `project('hello', 'c')`).

**Comment by QuLogic** [comment]
Bisect says this came from 8cfb8fd02c86e1667ded9a7841d77204f96a4a6d; cc @nirbheek.

**Comment by martin-schlipf** [comment]
I ran into the same issue today, when trying to link a Fortran program to Atlas-BLAS with meson 0.49.0.

**Comment by zephyr111** [comment]
I also ran into the same issue with meson 0.49.0 on a Fortran library, but the error occurs only when PKG_CONFIG_PATH is set...

**Comment by scivision** [comment]
This does not happen for me with v0.50. Maybe not an issue anymore?

**Comment by richli** [comment]
This also doesn't happen for me with v0.50. (I changed the dependency from `netcdf` to `sqlite3` to avoid invoking the custom dependency on NetCDF introduced in v0.50.)

**Comment by scivision** [comment]
This is a script that reliably reproduces this issue for Meson < 0.50.0:
```meson
project('hello', 'fortran')
executable('hello', dependencies : dependency('zlib'))
```
There was a substantial overhaul to Fortran in Meson 0.50.0, when this issue was fixed (manually verified now).
