### ISSUE TITLE
KeyError: 'b_vscrt' when building with the vs2017 backend

### ISSUE THREAD

**Issue by rzumer** [mesonbuild/meson#4273]
On Meson 0.48, running `meson build --backend vs2017` on the [dav1d](https://code.videolan.org/videolan/dav1d) project results in the following output:

```
The Meson build system
Version: 0.48.0
Source dir: C:\Users\rzumer\Projects\dav1d
Build dir: C:\Users\rzumer\Projects\dav1d\build
Build type: native build
Project name: dav1d
Project version: 0.0.1
Native C compiler: gcc (gcc 7.1.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 7.1.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Check usable header "stdatomic.h": YES
Compiler for C supports arguments -mpreferred-stack-boundary=5: NO
Compiler for C supports arguments -mpreferred-stack-boundary=4: YES
Compiler for C supports arguments -fvisibility=hidden: YES
Checking for function "posix_memalign" : NO
Checking for function "_aligned_malloc" : YES
Compiler for C supports arguments -Wundef: YES
Compiler for C supports arguments -Wvla: YES
Configuring config.h using configuration
Build targets in project: 6
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\mesonmain.py", line 364, in run
    app.generate()
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\mesonmain.py", line 136, in generate
    self._generate(env)
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\mesonmain.py", line 185, in _generate
    intr.backend.generate(intr)
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 165, in generate
    projlist = self.generate_projects()
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 374, in generate_projects
    self.gen_vcxproj(target, str(projfile_path), proj_uuid)
  File "c:\program files (x86)\python37-32\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 688, in gen_vcxproj
    vscrt_type = self.environment.coredata.base_options['b_vscrt']
KeyError: 'b_vscrt'
```

The same result was observed with Visual Studio 2017 15.7.6 and 15.8.5.

**Comment by rzumer** [comment]
Using the Developer Command Prompt for VS 2017, I have managed to build correctly.

**Comment by XVilka** [comment]
I think this was fixed already? Can you please recheck
