### ISSUE TITLE
Meson crashes trying to generate a project when using wraps.

### ISSUE THREAD

**Issue by cenomla** [mesonbuild/meson#4284]
I tried to add two libraries to my project using wrap files that. These two libraries are both git repos.
Error message:
```
colemanpc% meson . build
The Meson build system
Version: 0.48.0
Source dir: /home/cenomla/data/workspace/cpp/shooter
Build dir: /home/cenomla/data/workspace/cpp/shooter/build
Build type: native build
Project name: shooter
Project version: undefined
Native C compiler: cc (gcc 8.2.1 "cc (GCC) 8.2.1 20180831")
Native C++ compiler: c++ (gcc 8.2.1 "c++ (GCC) 8.2.1 20180831")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 136, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 165, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3836, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 411, in evaluate_statement
    return self.assignment(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 946, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 133, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2278, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2317, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 146, in resolve
    self.download(p, packagename)
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 322, in download
    ofname = os.path.join(self.cachedir, p.get('source_filename'))
  File "/usr/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 97, in get
    return self.values[key]
KeyError: 'source_filename'
```

Both wrap files look like this (The directory and url change):
```
[wrap-file]
directory = oak_util
url=https://oakcc@bitbucket.org/oakcc/oak_util.git
revision=head
```

**Comment by jpakkane** [comment]
You should not use `[wrap-file]` but `[wrap-git]` instead. [See the documentation](https://mesonbuild.com/Wrap-dependency-system-manual.html#branching-subprojects-directly-from-git).
