### ISSUE TITLE
If Meson fails to find boost, it crashes with error "TypeError: get_library_dirs() takes 0 positional arguments but 1 was given"

### ISSUE THREAD

**Issue by ilmola** [mesonbuild/meson#4407]
Tested with meson 0.48.1

Full stack trace

```
Traceback (most recent call last):
  File "mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "mesonbuild/mesonmain.py", line 136, in generate
    self._generate(env)
  File "mesonbuild/mesonmain.py", line 165, in _generate
    intr.run()
  File "mesonbuild/interpreter.py", line 3836, in run
    super().run()
  File "mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "mesonbuild/interpreterbase.py", line 411, in evaluate_statement
    return self.assignment(cur)
  File "mesonbuild/interpreterbase.py", line 946, in assignment
    value = self.evaluate_statement(node.value)
  File "mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "mesonbuild/interpreter.py", line 2998, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "mesonbuild/dependencies/base.py", line 1455, in find_external_dependency
    raise pkg_exc
  File "mesonbuild/dependencies/base.py", line 1409, in find_external_dependency
    d = c()
  File "mesonbuild/dependencies/boost.py", line 145, in __init__
    self.detect_lib_modules()
  File "mesonbuild/dependencies/boost.py", line 271, in detect_lib_modules
    self.detect_lib_modules_nix()
  File "mesonbuild/dependencies/boost.py", line 446, in detect_lib_modules_nix
    libdirs = mesonlib.get_library_dirs(self.env)
TypeError: get_library_dirs() takes 0 positional arguments but 1 was given
```

**Comment by jpakkane** [comment]
Can you test if the linked PR fixes this for you?

**Comment by ilmola** [comment]
The crash seems to fixed and if boost is not found, it now gives the correct(?) error message "Dependency "boost" not found, tried".
