### ISSUE TITLE
Meson uses install_name_tool on incompatible binaries

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#4417]
When cross compiling on macOS, meson tries to use `install_name_tool` on cross-compiled binaries that `install_name_tool` can not handle:

```
Traceback (most recent call last):
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/mesonmain.py", line 109, in run
    return options.run_func(options)
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/minstall.py", line 506, in run
    installer.do_install(datafilename)
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/minstall.py", line 343, in do_install
    self.install_targets(d)
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/minstall.py", line 484, in install_targets
    install_name_mappings, verbose=False)
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/scripts/depfixer.py", line 447, in fix_rpath
    fix_darwin(fname, new_rpath, final_path, install_name_mappings)
  File "/Users/epirat/Projects/Misc/meson/mesonbuild/scripts/depfixer.py", line 415, in fix_darwin
    stderr=subprocess.DEVNULL)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install_name_tool', '/Users/epirat/Projects/VideoLAN/VLC/contrib/x86_64-w64-mingw32/bin/libplacebo-6.dll', '-change', '@rpath/libplacebo.6.dylib', '/Users/epirat/Projects/VideoLAN/VLC/contrib/x86_64-w64-mingw32/bin/libplacebo-6.dll']' returned non-zero exit status 1.
FAILED: meson-install 
```

**Comment by alexandre-janniaux** [comment]
Also related to https://github.com/mesonbuild/meson/issues/8027 ?
