### ISSUE TITLE
OpenMP detection with the Intel C++ Compiler 

### ISSUE THREAD

**Issue by zephyr111** [mesonbuild/meson#4491]
Hi,
Meson fail during the detection of OpenMP for the Intel C++ compiler (2018).

Here is the meson.build file:

```
project('vlp4d', 'cpp', default_options: ['cpp_std=c++14'])
executable('vlp4d', ['main.cpp'], dependencies: [dependency('openmp')])
```

Here is the error:

```
$ CC=icc CXX=icpc meson build2
The Meson build system
Version: 0.48.1
Source dir: /panfs/panasas/cnt0041/cvt1605/jrichard/WORKDIR/git-vlp4d/src
Build dir: /panfs/panasas/cnt0041/cvt1605/jrichard/WORKDIR/git-vlp4d/src/build2
Build type: native build
Project name: vlp4d
Project version: undefined
Native C++ compiler: icpc (intel 18.0.1 "icpc (ICC) 18.0.1 20171018")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.27.1)
Dependency fftw3 found: YES 3.3.8
Dependency OpenMP found: NO 
Traceback (most recent call last):
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 136, in generate
    self._generate(env)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 165, in _generate
    intr.run()
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3836, in run
    super().run()
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.evaluate_plusassign(cur)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 641, in evaluate_plusassign
    addition = self.evaluate_statement(node.value)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 705, in function_call
    return func(node, posargs, kwargs)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2998, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/dependencies/base.py", line 1455, in find_external_dependency
    raise pkg_exc
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/dependencies/base.py", line 1409, in find_external_dependency
    d = c()
  File "/panfs/panasas/cnt0041/cvt1605/jrichard/spack/opt/spack/linux-rhel7-x86_64/gcc-8.1.0/python-3.6.5-5b5kw7wkotmpgamwyai4ymcgxa5rs5lm/lib/python3.6/site-packages/mesonbuild/dependencies/misc.py", line 258, in __init__
    self.version = self.VERSIONS[openmp_date]
KeyError: '201611'
```

thanks.

**Comment by dcbaker** [comment]
I have a patch that fixes this, but it's in a larger series that needs to be rebased, I'll split it out and send it.
