### ISSUE TITLE
meson install with --only-changed fails if the target binary is running

### ISSUE THREAD

**Issue by mteyssier** [mesonbuild/meson#4496]
I got some issue while trying to install a binary which is already running.
Somewhat looks like #578

```
$ /install/bin/sample &
$ meson install --only-changed
ninja: Entering directory `.'
ninja: no work to do.
Preserving existing file /install/bin/sample.
Traceback (most recent call last):
  File "/usr/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 284, in run
    return minstall.run(remaining_args)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 346, in do_install
    self.install_targets(d)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 490, in install_targets
    install_name_mappings, verbose=False)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 404, in fix_rpath
    fix_elf(fname, new_rpath, verbose)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 342, in fix_elf
    with Elf(fname, verbose) as e:
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 117, in __init__
    self.bf = open(bfile, 'r+b')
OSError: [Errno 26] Text file busy: '/install/bin/sample'
Exception ignored in: <bound method Elf.__del__ of <mesonbuild.scripts.depfixer.Elf object at 0x7f36fa0737f0>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/depfixer.py", line 132, in __del__
    if self.bf:
AttributeError: 'Elf' object has no attribute 'bf'
```

Running `meson install` without `--only-changed` works fine.

If I understand correctly, in `install_targets` from `minstall.py`:
- `do_copyfile` is called, the file didn't change so it is preserved (not removed, not copied, no issue yet).
- however `depfixer.fix_rpath` is still called and tries to open the file with write access which fails because the binary is running.

Is this use case supported?
If the file is to be preserved, should the "fix rpath" step be skipped?

**Comment by nirbheek** [comment]
This will be fixed with https://github.com/mesonbuild/meson/pull/6612.
