### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 7191-7192: invalid continuation byte

### ISSUE THREAD

**Issue by pavlosun** [mesonbuild/meson#4519]
Hi, 

I am working on libgda project https://gitlab.gnome.org/GNOME/libgda. Specifically, I am trying to compile the gtk-doc documentation. I receive the following error with traceback:
```
Traceback (most recent call last):
  File "/home/pavlo/jhbuild/install/bin/meson", line 11, in <module>
    load_entry_point('meson==0.48.0', 'console_scripts', 'meson')()
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 392, in main
    return run(sys.argv[1:], launcher)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 344, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 254, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 253, in run
    options.mode)
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 194, in build_gtkdoc
    gtkdoc_run_check(mkhtml_cmd, os.path.join(abs_out, 'html'))
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/scripts/gtkdochelper.py", line 66, in gtkdoc_run_check
    p, out = Popen_safe(cmd, cwd=cwd, env=env, stderr=subprocess.STDOUT)[0:2]
  File "/home/pavlo/jhbuild/install/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 829, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.6/subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 7191-7192: invalid continuation byte
FAILED: meson-libgda-6.0-doc 
/home/pavlo/jhbuild/install/bin/meson --internal commandrunner /home/pavlo/jhbuild/checkout/libgda /home/pavlo/jhbuild/checkout/libgda/build doc/C/libgda /home/pavlo/jhbuild/install/bin/meson /home/pavlo/jhbuild/install/bin/meson --internal gtkdoc --sourcedir=/home/pavlo/jhbuild/checkout/libgda --builddir=/home/pavlo/jhbuild/checkout/libgda/build --subdir=doc/C/libgda --headerdirs=/home/pavlo/jhbuild/checkout/libgda/libgda@@/home/pavlo/jhbuild/checkout/libgda/build/libgda --mainfile=libgda-6.0-docs.xml --modulename=libgda-6.0 --mode=none '--scanargs=--deprecated-guards="GDA_DISABLE_DEPRECATED"@@--rebuild-types@@--ignore-headers=gda-marshal.h gda-custom-marshal.h gda-enum-types.h sqlite3.h csv.h md5.h jni-wrapper.h gda-jdbc-recordset.h gda-jdbc-blob-op.h gda-jdbc-provider.h gda-jdbc-pstmt.h dummy-object.h gda-data-model-bdb.h' --mkdbargs=--xml-mode@@--output-format=xml@@--name-space=gda --html-assets=/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/DataModels.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/architecture.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/parts.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-unknown.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-select.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-insert1.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-insert2.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-update.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/stmt-compound.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/information_schema.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/MetaStore1.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/MetaStore2.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/i_s_data_types.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/writable_data_model.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/GdaDataModelIter.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_validation_holder.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_validation_proxy.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_validation_set.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_proxy1.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_proxy2.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_proxy3.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_proxy4.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/data_proxy5.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/gda-sql-graph.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/howto-exec.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/GdaStatement.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/parser_gen.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/parser_prov.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/tree-overview.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/tree-overview2.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/SqlIdentifiers.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/thread-wrapper.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-basic-form.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-combo.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-data-entry.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-login.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-cloud.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-provider-selector.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-raw-grid.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-info.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-filter.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-server-op.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/vi-rte.png@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/connection-status.png --content-files=/home/pavlo/jhbuild/checkout/libgda/build/doc/C/libgda/version.xml@@/home/pavlo/jhbuild/checkout/libgda/build/doc/C/libgda/builddate.xml@@/home/pavlo/jhbuild/checkout/libgda/doc/C/libgda/fdl-appendix.sgml --ignore-headers=gda-data-model-bdb.h --cc=cc --ld=cc '--cflags=-I/home/pavlo/jhbuild/install/include/glib-2.0 -I/home/pavlo/jhbuild/install/lib/glib-2.0/include -pthread -I/usr/include/libxml2 -I/home/pavlo/jhbuild/install/include/libsoup-2.4 -Wall -g -O0' '--ldflags=-L/home/pavlo/jhbuild/checkout/libgda/build/libgda -L/home/pavlo/jhbuild/install/lib -Wl,-rpath,/home/pavlo/jhbuild/install/lib -Wl,-rpath,/home/pavlo/jhbuild/checkout/libgda/build/libgda -lgda-6.0 -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgmodule-2.0 -pthread -lxml2 -lsoup-2.4 -lsqlite3 -Wall -g -O0'
ninja: build stopped: subcommand failed.
```
I am not expert with meson and checked some other projects for documentation organization, e.g. glib. My meson.build file is:
```
libgda_typesdoc = configure_file( input: 'libgda.types.in',
		output : 'libgda.types',
		configuration : conf)

gda_html_images = files([
	'DataModels.png',
	'architecture.png',
	'parts.png',
	'stmt-unknown.png',
	'stmt-select.png',
	'stmt-insert1.png',
	'stmt-insert2.png',
	'stmt-update.png',
	'stmt-compound.png',
	'information_schema.png',
	'MetaStore1.png',
	'MetaStore2.png',
	'i_s_data_types.png',
	'writable_data_model.png',
	'GdaDataModelIter.png',
	'data_validation_holder.png',
	'data_validation_proxy.png',
	'data_validation_set.png',
	'data_proxy1.png',
	'data_proxy2.png',
	'data_proxy3.png',
	'data_proxy4.png',
	'data_proxy5.png',
	'gda-sql-graph.png',
	'howto-exec.png',
	'GdaStatement.png',
	'parser_gen.png',
	'parser_prov.png',
	'tree-overview.png',
	'tree-overview2.png',
	'SqlIdentifiers.png',
	'thread-wrapper.png',
	'vi-basic-form.png',
	'vi-combo.png',
	'vi-data-entry.png',
	'vi-login.png',
	'vi-cloud.png',
	'vi-provider-selector.png',
	'vi-raw-grid.png',
	'vi-info.png',
	'vi-filter.png',
	'vi-server-op.png',
	'vi-rte.png',
	'connection-status.png'
	])

doc_conf = configuration_data()
doc_conf.set('GDA_VERSION', project_version)
doc_conf.set('GDA_BUILDDATE', dates.stdout())

doc_version = configure_file(
	input: 'version.xml.in',
	output: 'version.xml',
	configuration: doc_conf
	)
doc_builddate= configure_file(
	input: 'builddate.xml.in',
	output: 'builddate.xml',
	configuration: doc_conf
	)
contentf = [
	doc_version,
	doc_builddate
	]
contentf += files([
	'fdl-appendix.sgml'
	])

ignore_headers = [
        'gda-marshal.h',
        'gda-custom-marshal.h',
        'gda-enum-types.h',
        'sqlite3.h',
        'csv.h',
        'md5.h',
        'jni-wrapper.h',
        'gda-jdbc-recordset.h',
        'gda-jdbc-blob-op.h',
        'gda-jdbc-provider.h',
        'gda-jdbc-pstmt.h',
        'dummy-object.h'
]

ignore_bdb = []
ignore_bdb += ['gda-data-model-bdb.h']

ignore_headers += ignore_bdb

gnome_module.gtkdoc(project_package,
        main_xml : project_package+'-docs.xml',
        src_dir: [
                join_paths(meson.source_root(),'libgda'),
                join_paths(meson.build_root(),'libgda'),
        ],
        mode: 'none',
        dependencies: total_dep, 
        ignore_headers: ignore_bdb,
        scan_args: [
                '--deprecated-guards="GDA_DISABLE_DEPRECATED"',
                '--rebuild-types',
                '--ignore-headers=' + ' '.join(ignore_headers),
                 ],
        mkdb_args: [
                '--xml-mode',
                '--output-format=xml',
                '--name-space=gda'
                ],
        html_assets: gda_html_images,
        content_files: contentf,
        install: true
        )
```
Is it problem with my file, meson or python? 
I am using meson 0.48.0 (jhbuild)

Any help or suggestions would be appreciated.

Thanks.
-Pavlo.

**Comment by krader1961** [comment]
This should probably be closed since it is a question that is 14 months old (thus the O.P. almost certainly no longer cares) and the problem is clearly a character encoding problem. That is, meson seems to be running in a locale using UTF-8 encoding and the text being read is not UTF-8 encoded (probably a ISO 8859 or other non-ASCII compatible encoding).

**Comment by pavlosun** [comment]
I agree with @krader1961 . We can close this bug. If we see the same problem again, we will open a new one to work. Thanks.
