### ISSUE TITLE
wrap without ssh: is that possible?

### ISSUE THREAD

**Issue by pgallir** [mesonbuild/meson#4520]
my settings: 
conda environment with python 3.7.0 
meson 0.47.2

my problem: 
my company network blocks ssh to outside by design. because of this I have problems in using the wrap dependency strategy. it seems meson uses ssh to download the dependencies (even though the repo location is addressed using https). 

```
(py37) developer@XUbuntu-16-VirtualBox:(master)$ meson build
...
Using gtest from cache.
Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 351, in run
    app.generate()
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 146, in _generate
    intr.run()
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3699, in run
    super().run()
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 380, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 699, in function_call
    return func(node, posargs, kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3313, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 411, in evaluate_statement
    return self.assignment(cur)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 940, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 699, in function_call
    return func(node, posargs, kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 273, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 133, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2209, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2233, in do_subproject
    resolved = r.resolve(dirname)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 145, in resolve
    self.download(p, packagename)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 335, in download
    phash, tmpfile = self.get_data(purl)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 269, in get_data
    resp = open_wrapdburl(url)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 67, in open_wrapdburl
    return urllib.request.urlopen(urlstring)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/developer/miniconda3/envs/py37/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)>
```

the log ends with... 
`Downloading patch from https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip`
...and no other info are provided. 

hereafter follows my gtest.wrap, which I did not expect to use ssh (as the repo location is addressed using https), should it? 
```
[wrap-file]
directory = gtest #googletest-release-1.8.0

source_url = https://github.com/google/googletest/archive/release-1.8.0.zip
source_filename = gtest-1.8.0.zip
source_hash = f3ed3b58511efd272eb074a3a6d6fb79d7c2e6a0e374323d1e6bcbcc1ef141bf

patch_url = https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
patch_filename = gtest-1.8.0-5-wrap.zip
patch_hash = 7eeaede4aa2610a403313b74e04baf91ccfbaef03203d8f56312e22df1834ec5
```
I wonder whether it would be possible to address those dependencies without SSL, i.e. providing the credentials interactively in the shell after the call. 

many thanks in advance for any help.

**Comment by pgallir** [comment]
meanwhile, I will try a different approach as suggested [here](https://github.com/mesonbuild/meson/issues/642#issuecomment-232784687) by @jpakkane : 

> create a tarball with upstream + build and put it somewhere Meson uses urllib so you can use file:// urls to get to it

**Comment by pgallir** [comment]
This issue is surely connected to #4510
