### ISSUE TITLE
Cannot access version in default_options

### ISSUE THREAD

**Issue by jtojnar** [mesonbuild/meson#4577]
When I try the following

```meson
project(
	'telepathy-idle',
	'c',
	version: '0.2.0.1',
	default_options: [
		'c_std=c99',
		'werror=@0@'.format((meson.project_version().split('.')[3] == '0').to_string()), # development version
	],
)
```

meson crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 351, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 117, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 134, in _generate
    intr = interpreter.Interpreter(b)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 1877, in __init__
    self.parse_project()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 365, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 404, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 398, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 409, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 691, in function_call
    (posargs, kwargs) = self.reduce_arguments(node.args)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 928, in reduce_arguments
    reduced_kw[key] = self.evaluate_statement(a)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 454, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 922, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 922, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 413, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 713, in method_call
    return self.string_method_call(obj, method_name, args)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 798, in string_method_call
    (posargs, kwargs) = self.reduce_arguments(args)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 922, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 922, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 413, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 709, in method_call
    obj = self.evaluate_statement(invokable)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 423, in evaluate_statement
    return self.evaluate_comparison(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 491, in evaluate_comparison
    val1 = self.evaluate_statement(node.left)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
    return self.evaluate_indexing(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 666, in evaluate_indexing
    iobject = self.evaluate_statement(node.iobject)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 413, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 709, in method_call
    obj = self.evaluate_statement(invokable)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 413, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 735, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 304, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 162, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 1754, in project_version_method
    return self.build.dep_manifest[self.interpreter.active_projectname]['version']
AttributeError: 'Interpreter' object has no attribute 'active_projectname'
```

While it makes sense, as `project` call has not finalized yet, the following does not work due to the meson limitation either:

```meson
idle_major_version = '0'
idle_minor_version = '2'
idle_micro_version = '0'
idle_nano_version = '1'

version = '@0@.@1@.@2@.@3@'.format(
	idle_major_version,
	idle_minor_version,
	idle_micro_version,
	idle_nano_version,
)
 
project(
	'telepathy-idle',
	'c',
	version: '0.2.0.1',
	default_options: [
		'c_std=c99',
		'werror=@0@'.format((idle_nano_version == '0').to_string()), # development version
	],
)

```

**Comment by bruce-richardson** [comment]
interestingly, while you can't access the project_version inside the project statement itself, you can have "run_command()" inside it e.g. this works: 
     "project('test_project', 'c', version: run_command('uname','-r').stdout().strip())"

Maybe as a hack, you can use grep etc. on your meson.build file to parse the version number, or alternatively, pull that info from a separate file.

**Comment by jpakkane** [comment]
You might want to consider a conceptual change here. Whether to use `-Werror` is not _really_ a property of the build system or the version, but of the _usage circumstances_. If your project has CI and/or gating, the choice of `-Werror` should be made there. This way you can enforce that your trunk is always werror clean but it is not forced on everyone else.

Downstream people such as packagers **hate** projects that enable werror with a passion. The reason for this is that every new compiler version adds new warnings and things that were working just fine start breaking for no good reason.

**Comment by jtojnar** [comment]
I agree with this, we probably still want a better error message.
