### ISSUE TITLE
`meson test` crashes with "UnicodeEncodeError: 'ascii' codec can't encode character '\u2192' in position 2: ordinal not in range(128)"

### ISSUE THREAD

**Issue by evverx** [mesonbuild/meson#4600]
A real-world example can be found at the end of https://travis-ci.org/systemd/systemd/jobs/464904604. Below is an artificial reproducer where `PYTHONIOENCODING=ascii` is used to set `sys.stdout.encoding` to `ascii`:
```
$ cat meson.build
# SPDX-License-Identifier: LGPL-2.1+

project('systemd', 'c',
        version : '239',
        license : 'LGPLv2+',
        meson_version : '>= 0.46',
       )

print_arrow = find_program('print-arrow.sh')
test('print arrow', print_arrow)

$ cat print-arrow.sh
#!/bin/bash

printf 'a \u2192 b'
exit 1

$ meson --version
0.48.2

$ meson ./build/
...

$ PYTHONIOENCODING=ascii ninja -v -C ./build/ test
1/1 print arrow                             FAIL     0.01 s (exit status 1)

OK:         0
FAIL:       1
SKIP:       0
TIMEOUT:    0


The output from the failed tests:

1/1 print arrow                             FAIL     0.01 s (exit status 1)

--- command ---
/home/vagrant/TEST/print-arrow.sh
--- stdout ---
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 11, in <module>
    load_entry_point('meson==0.48.2', 'console_scripts', 'meson')()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 392, in main
    return run(sys.argv[1:], launcher)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 302, in run
    return mtest.run(remaining_args)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 778, in run
    return th.doit()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 526, in doit
    self.run_tests(tests)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 688, in run_tests
    self.print_collected_logs()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mtest.py", line 517, in print_collected_logs
    print(line)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2192' in position 2: ordinal not in range(128)
FAILED: meson-test
/usr/local/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes it for you?

Why are you using a plain ASCII locale in this case? It is not recommended and Python is going to default to UTF-8 in the next release (or possibly it already does in the current one).

**Comment by evverx** [comment]
Thank you! The issue is gone in the sense that `ninja` is no longer crashes but `python` changes the arrow to a question mark:
```
$ PYTHONIOENCODING=ascii ninja -C ./build/ test | grep '^a.*b' | hexdump -C
00000000  61 20 3f 20 62 0a                                 |a ? b.|
00000006
```
Given that in general tests can print binary gibberish would it be possible to print data as is without encoding and decoding, that is with `sys.stdout.buffer.write(b"some binary data")` or something like that?

Regarding the locale, that most likely happens because the locales package isn't shipped by default in debian docker images (which saves a lot of space I suppose).

**Comment by jpakkane** [comment]
What gets printed to the terminal is only informational. The original data can be found in the log files.

**Comment by evverx** [comment]
Got it. I have no problem with that :-) Thank you!

**Comment by mbiebl** [comment]
Fwiw, it should be possible to use ```LC_ALL=C.UTF8``` This is what the debian package does.
