### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 223: ordinal not in range(128)

### ISSUE THREAD

**Issue by SkyzohKey** [mesonbuild/meson#467]
Hey guys,
An issue with meson got reported on the Ricin's repository, so I copy/paste it here.
For more informations → @ovalseven8

## Summary
* **Operating System:** Manjaro Linux
* **Ricin's version:** https://github.com/RicinApp/Ricin/commit/a5480df646f86a26763b38368ea6b0757b9ac646
* **Reproducible:** Always

## Steps to reproduce:
1.  `git clone --recursive https://github.com/RicinApp/Ricin.git && cd Ricin`
2.  `make autogen`

Result:
```
git clone --recursive https://github.com/RicinApp/Ricin.git
Cloning into 'Ricin'...
remote: Counting objects: 2565, done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 2565 (delta 88), reused 0 (delta 0), pack-reused 2423
Receiving objects: 100% (2565/2565), 1.35 MiB | 546.00 KiB/s, done.
Resolving deltas: 100% (1848/1848), done.
Checking connectivity... done.
Submodule 'tox-vapi' (https://github.com/RicinApp/tox-vapi.git) registered for path 'tox-vapi'
Cloning into 'tox-vapi'...
remote: Counting objects: 465, done.
remote: Total 465 (delta 0), reused 0 (delta 0), pack-reused 465
Receiving objects: 100% (465/465), 221.97 KiB | 0 bytes/s, done.
Resolving deltas: 100% (233/233), done.
Checking connectivity... done.
Submodule path 'tox-vapi': checked out 'b53518c054ed455d66ca3b95638efbcbbb660829'

cd Ricin

make autogen
rm -rf ./build
mkdir -p ./build
meson . ./build
The Meson build system
Version: 0.29.0
Source dir: /home/test/Ricin
Build dir: /home/test/Ricin/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: Ricin
Native vala compiler: valac (unknown 0.30.1)
Native c compiler: cc (gcc 5.3.0)
Warning, glib compiled dependencies will not work until this upstream issue is fixed: https://bugzilla.gnome.org/show_bug.cgi?id=745754
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency glib-2.0 found: YES 2.46.2
Native dependency gio-2.0 found: YES 2.46.2
Native dependency gobject-2.0 found: YES 2.46.2
Native dependency gmodule-2.0 found: YES 2.46.2
Native dependency gtk+-3.0 found: YES 3.18.8
Native dependency libsoup-2.4 found: YES 2.52.2
Native dependency json-glib-1.0 found: YES 1.0.4
Native dependency libnotify found: YES 0.7.6
Native dependency libtoxcore found: YES 0.0.0
Native dependency libconfig found: YES 1.5
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 250, in run
    app.generate()
  File "/usr/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 160, in generate
    intr.run()
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1028, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1050, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1044, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1160, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1957, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 62, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/lib/python3.5/site-packages/mesonbuild/interpreter.py", line 1766, in func_subdir
    code = open(absname).read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 223: ordinal not in range(128)
Makefile:14: recipe for target 'autogen' failed
make: *** [autogen] Error 1
```

**Comment by jpakkane** [comment]
This machine seems to have broken locales and only supports ASCII. On Debian based systems you can fix this with `dpkg-reconfigure locales` and selecting an utf8 locale as the default.

That being said we probably should open all files explicitly in utf8.

**Comment by nanonyme** [comment]
Wouldn't it be better to trust locale except that if it's ascii, promote to utf-8 since utf-8 is a direct superset of ascii?

**Comment by nirbheek** [comment]
We already do that. This bug is about code that has already changed. Please open a new issue for your problem.
