### ISSUE TITLE
ninja coverage-html throws exception and doesn't provide coverage report

### ISSUE THREAD

**Issue by Ox0000** [mesonbuild/meson#4679]
## Summary
When I run `ninja coverage-html`; instead of getting a coverage report, ninja fails with error code 255

## Repro Steps
```
$ ninja # build succeeds
$ ninja test # all tests pass
$ ninja coverage-html
```

### Expected Outcome:
I get an html coverage report that I can inspect.

### Actual Outcome:
Ninja fails with error code 255. The following output is generated and I do **not** get an HTML Coverage Report (I have replaced relevant paths with variables).

```
[1/1] /usr/bin/meson --internal coverage --html ${PROJECT_ROOT} ${PROJECT_ROOT}/subprojects ${PROJECT_ROOT}/builddir_debug ${PROJECT_ROOT}/builddir_debug/meson-logs
FAILED: meson-coverage-html 
/usr/bin/meson --internal coverage --html ${PROJECT_ROOT} ${PROJECT_ROOT}/subprojects ${PROJECT_ROOT}/builddir_debug ${PROJECT_ROOT}/builddir_debug/meson-logs
Capturing coverage data from ${PROJECT_ROOT}/builddir_debug
Found gcov version: 8.2.1
Scanning ${PROJECT_ROOT}/builddir_debug for .gcno files ...
Found 238 graph files in ${PROJECT_ROOT}/builddir_debug

#
# listing of all source files from all projects goes here
# 

Finished .info-file creation
Capturing coverage data from ${PROJECT_ROOT}/builddir_debug
Found gcov version: 8.2.1
Scanning ${PROJECT_ROOT}/builddir_debug for .gcda files ...
Found 175 data files in ${PROJECT_ROOT}/builddir_debug
```
Note that in the block above, there is reference to a path `${PROJECT_ROOT}/subprojects` (in the command `/usr/bin/meson --internal coverage --html ${PROJECT_ROOT} ${PROJECT_ROOT}/subprojects ${PROJECT_ROOT}/builddir_debug ${PROJECT_ROOT}/builddir_debug/meson-logs`) and I have no idea where that comes from nor does this path exist in my repository. This is also not a mistake in my path obfuscation for the purpose of logging this issue.

Then, for each .gcda file I see the following:
```
Processing ${PATH_TO_SUBPROJECT}/${FILE_RELATIVE_PATH}.cxx.gcda
${PROJECT_ROOT}/builddir_debug/${PATH_TO_SUBPROJECT}/${FILE_RELATIVE_PATH}.cxx.gcno:version '402*', prefer 'A82*'
${PROJECT_ROOT}/builddir_debug/${PATH_TO_SUBPROJECT}/${FILE_RELATIVE_PATH}.cxx.gcno:no functions found
${PROJECT_ROOT}/builddir_debug/${PATH_TO_SUBPROJECT}/${FILE_RELATIVE_PATH}.cxx.gcda:version '402*', prefer version 'A82*'
geninfo: WARNING: gcov did not create any files for ${PROJECT_ROOT}/builddir_debug/${PATH_TO_SUBPROJECT}/${FILE_RELATIVE_PATH}.cxx.gcda!
```

Finally:
```
Finished .info-file creation
lcov: ERROR: no valid records found in tracefile ${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.run
Combining tracefiles.
Reading tracefile ${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.initial
Reading tracefile ${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.run
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.49.0', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 192, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 181, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 145, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 149, in run
    options.log_dir)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/coverage.py", line 81, in coverage
    '-o', raw_tracefile])
  File "/usr/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lcov', '-a', '${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.initial', '-a', '${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.run', '--rc', 'lcov_branch_coverage=1', '-o', '${PROJECT_ROOT}/builddir_debug/meson-logs/coverage.info.raw']' returned non-zero exit status 255.
ninja: build stopped: subcommand failed.
```

## Environment
- Meson: 0.49.0
- Ninja: 1.8.2
- LCov:  1.13
- Linux 4.19.12 (in case that is relevant)

The configuration of my build (generated into a directory named `builddir_debug` - see output below)
- Build type: native build
- Native C++ compiler: clang++ (clang 7.0.1 "clang version 7.0.1 (tags/RELEASE_701/final)")
- Build machine cpu family: x86_64
- Build machine cpu: x86_64
Settings:
- werror = true
- b_lundef = false
- buildtype = debug
- debug = true
- optimization = 0
- b_coverage = true
- b_ndebug = false

## Illustrative source code lay out
My repository consists of a total of 59 projects organized roughly as following:
- product
    - liblibrary
    - product_bin_a_depending_on_liblibrary
    - product_bin_b_depending_on_liblibrary
    - product_bin_c_depending_on_liblibrary
    - _...etc..._
- test
    - libtesthelpers
    - testsuite_a_depending_on_liblibrary_and_libtesthelpers
    - testsuite_b_depending_on_liblibrary_and_libtesthelpers
    - testsuite_c_depending_on_liblibrary_and_libtesthelpers
    - testsuite_d_depending_on_liblibrary_and_libtesthelpers
    - testsuite_e_depending_on_liblibrary_and_libtesthelpers
    - _...etc..._
- tools
    - tool_a_freestanding
    - tool_b_depending_on_liblibrary
    - _...etc..._

**Comment by msekletar** [comment]
I've hit the same problem but I don't think it is a meson issue. lcov failure is due to, 

https://bugzilla.redhat.com/show_bug.cgi?id=1668843

I was able to workaround the issue on my end by manually building newer lcov (v1.14) and after updating lcov ```ninja coverage-html``` started to work again.
