### ISSUE TITLE
Interrupting msgmerge results in an empty .po file

### ISSUE THREAD

**Issue by nomis** [mesonbuild/meson#4683]
Interrupting execution of `msgmerge` results in an empty .po file:
```
ninja -C build/release/ dtee-update-po
ninja: Entering directory `build/release/'
[1/1] Running external command dtee-update-po.
^CTraceback (most recent call last):
  File "/home/simon/.local/bin/meson", line 11, in <module>
    sys.exit(main())
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 392, in main
Traceback (most recent call last):
  File "/home/simon/.local/bin/meson", line 11, in <module>
    return run(sys.argv[1:], launcher)
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 344, in run
    sys.exit(main())
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 392, in main
    sys.exit(run_script_command(args[1:]))
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 254, in run_script_command
    return run(sys.argv[1:], launcher)
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 344, in run
    return cmdfunc(cmdargs)
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/scripts/commandrunner.py", line 70, in run
    pc.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    sys.exit(run_script_command(args[1:]))
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/mesonmain.py", line 254, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/scripts/gettext.py", line 113, in run
    return update_po(src_sub, options.pkgname, langs)
  File "/home/simon/.local/lib/python3.5/site-packages/mesonbuild/scripts/gettext.py", line 74, in update_po
    subprocess.check_call(['msgmerge', '-q', '-o', pofile, pofile, potfile])
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 559, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
ninja: build stopped: interrupted by user.
GNUmakefile:98: recipe for target 'po' failed
make: *** [po] Error 2
```

The `fr.po` file is now empty:
```
-rw-rw-r-- 1 simon simon 4698 Dec 28 17:44 en.po
-rw-rw-r-- 1 simon simon    0 Dec 28 17:44 fr.po
```

The output file should be created with a different name and renamed into place so that this doesn't happen.

**Comment by nomis** [comment]
```
$ meson --version
0.48.0
$ ninja --version
1.5.1
$ msgmerge --version
msgmerge (GNU gettext-tools) 0.19.7
```

**Comment by jpakkane** [comment]
FWICT this is a bug in `msgmerge` since it does not write its output files atomically.

**Comment by nomis** [comment]
That doesn't prevent Meson from copying the file to the build directory to run `msgmerge` on it and then move it back.

**Comment by eli-schwartz** [comment]
Why is it meson's job to painfully include logic to work around a msgmerge bug? The correct solution is to report an upstream bug to the msgmerge developer and have it fixed for everyone.

**Comment by nomis** [comment]
Because meson is explicitly instructing `msgmerge` to output to the same file as the input. The default is to output to standard output.

**Comment by eli-schwartz** [comment]
```
gettext, gnome: use meson_exe to invoke msgmerge

meson is instructing msgmerge to output to the same file
as the input, but this means that interrupting the
execution of msgmerge results in an empty .po file.

Instead, go through scripts.meson_exe and make msgmerge
print to stdout.  This is more effective because it also
skips the update if the contents did not change.
```

I'd assume the -U mode already does "skip the update", but also I don't see how it matters, it is a run_target so only triggered manually.


And I still don't see where the gettext developer was asked to fix this (correctly). We didn't fix anything but that's fine, since the fix is in gettext itself we can leave this ticket closed either way.
