### ISSUE TITLE
`ninja scan-build` errors out when running g-ir-scanner

### ISSUE THREAD

**Issue by sgallagher** [mesonbuild/meson#4709]
When running `ninja scan-build` against my project [libmodulemd](https://github.com/fedora-modularity/libmodulemd/), the scan terminates with an error when `g-ir-scanner` is invoked.

This is on Fedora 29 with:

* meson-0.49.0-1.fc29.noarch
* ninja-build-1.8.2-5.fc29.x86_64
* gobject-introspection-1.58.3-1.fc29.x86_64
* clang-7.0.0-2.fc29.x86_64
* clang-analyzer-7.0.0-2.fc29.noarch

```
[sgallagh@sgallaghp50:api2 (scan-build)]$ ninja scan-build
[0/1] /usr/bin/meson --internal scanbuild /home/sgallagh/workspace/libmodulemd /home/sgallagh/workspace/libmodulemd/api2 /usr/bin/meson -Dbuild_api_v1=false -Dbuild_api_v2=true -Ddeveloper_build=true -Dtest_dirty_git=false -Dtest_installed_lib=false
scan-build: Using '/usr/bin/clang-7' for static analysis
The Meson build system
Version: 0.49.0
Source dir: /home/sgallagh/workspace/libmodulemd
Build dir: /home/sgallagh/workspace/libmodulemd/api2/meson-private/tmpl32f8w7w
Build type: native build
Project name: modulemd
Project version: 2.0.0
Native C compiler: /usr/bin/../libexec/ccc-analyzer (gcc 8.2.1 "gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Werror=missing-declarations: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wuninitialized: YES
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES
Compiler for C supports arguments -Werror=implicit: YES
Compiler for C supports arguments -Werror=init-self: YES
Compiler for C supports arguments -Werror=main: YES
Compiler for C supports arguments -Werror=missing-braces: YES
Compiler for C supports arguments -Werror=return-type: YES
Compiler for C supports arguments -Werror=array-bounds: YES
Compiler for C supports arguments -Werror=write-strings: YES
Compiler for C supports arguments -DG_LOG_USE_STRUCTURED: YES
Compiler for C supports arguments -DG_LOG_DOMAIN="libmodulemd": YES
DEPRECATION: Project targetting '>=0.44.0' but tried to use feature deprecated since '0.48.0': python3 module
Found pkg-config: /usr/bin/pkg-config (1.5.3)
Dependency gobject-2.0 found: YES 2.58.2
Dependency yaml-0.1 found: YES 0.2.1
Dependency gtk-doc found: YES 1.29
Program sh found: YES (/usr/bin/sh)
Program sed found: YES (/usr/bin/sed)
Program spec_tmpl.sh found: YES (/home/sgallagh/workspace/libmodulemd/spec_tmpl.sh)
Program mkdir found: YES (/usr/bin/mkdir)
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring make_srpm.sh using configuration
Configuring make_rpms.sh using configuration
Program clang-format found: YES (/usr/bin/clang-format)
Program python3-autopep8 found: YES (/usr/bin/python3-autopep8)
Program valgrind found: YES (/usr/bin/valgrind)
Configuring config.h using configuration
Configuring version.xml using configuration
Program common/tests/test-import-headers.sh found: YES (/home/sgallagh/workspace/libmodulemd/modulemd/common/tests/test-import-headers.sh)
Build targets in project: 24
WARNING: Deprecated features used:
 * 0.48.0: {'python3 module'}
Option b_asneeded is: True [default: true]
Found ninja-1.8.2 at /usr/bin/ninja
scan-build: Removing directory '/tmp/scan-build-2019-01-03-145250-31673-1' because it contains no reports.
scan-build: No bugs found.
scan-build: Using '/usr/bin/clang-7' for static analysis
ninja: Entering directory `/home/sgallagh/workspace/libmodulemd/api2/meson-private/tmpl32f8w7w'
[20/63] Compiling C object 'modulemd/v2/370d462@@modulemd@sha/modulemd-dependencies.c.o'.
../../../modulemd/v2/modulemd-dependencies.c:433:21: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
                    nested_error->message);
                    ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:183:57: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, NULL, __VA_ARGS__)
                                                        ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
../../../modulemd/v2/modulemd-dependencies.c:447:21: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
                    nested_error->message);
                    ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:183:57: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, NULL, __VA_ARGS__)
                                                        ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
2 warnings generated.
[30/63] Compiling C object 'modulemd/v2/370d462@@modulemd@sha/modulemd-translation-entry.c.o'.
../../../modulemd/v2/modulemd-translation-entry.c:455:46: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
                                             nested_error->message);
                                             ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:183:57: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, NULL, __VA_ARGS__)
                                                        ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
1 warning generated.
[31/63] Compiling C object 'modulemd/v2/370d462@@modulemd@sha/modulemd-translation.c.o'.
../../../modulemd/v2/modulemd-translation.c:566:19: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
                  nested_error->message);
                  ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:183:57: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, NULL, __VA_ARGS__)
                                                        ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
1 warning generated.
[36/63] Compiling C object 'modulemd/v2/370d462@@modulemd@sha/modulemd-defaults-v1.c.o'.
../../../modulemd/v2/modulemd-defaults-v1.c:670:15: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
              nested_error->message);
              ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:186:58: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_BOOL'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, FALSE, __VA_ARGS__)
                                                         ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
../../../modulemd/v2/modulemd-defaults-v1.c:758:17: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'nested_error')
                nested_error->message);
                ^~~~~~~~~~~~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:186:58: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_BOOL'
  MMD_YAML_ERROR_EVENT_EXIT_FULL (_error, _event, FALSE, __VA_ARGS__)
                                                         ^~~~~~~~~~~
../../../modulemd/v2/include/modulemd-2.0/private/modulemd-yaml.h:166:54: note: expanded from macro 'MMD_YAML_ERROR_EVENT_EXIT_FULL'
      g_autofree gchar *formatted = g_strdup_printf (__VA_ARGS__);            \
                                                     ^~~~~~~~~~~
2 warnings generated.
[38/63] Compiling C object 'modulemd/v2/370d462@@translation_v2@exe/tests_test-modulemd-translation.c.o'.
../../../modulemd/v2/tests/test-modulemd-translation.c:193:3: warning: Value stored to 't' is never read
  t = modulemd_translation_new (1, "testmodule", "teststream", 5);
  ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[62/63] Generating Modulemd-2.0.gir with a custom command.
FAILED: modulemd/v2/Modulemd-2.0.gir 
/usr/bin/g-ir-scanner -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread --no-libtool --namespace=Modulemd --nsversion=2.0 --warn-all --output modulemd/v2/Modulemd-2.0.gir -I/home/sgallagh/workspace/libmodulemd/modulemd/v2 -I/home/sgallagh/workspace/libmodulemd/api2/meson-private/tmpl32f8w7w/modulemd/v2 -I./modulemd/v2/include/modulemd-2.0 -I../../../modulemd/v2/include/modulemd-2.0 --filelist=/home/sgallagh/workspace/libmodulemd/api2/meson-private/tmpl32f8w7w/modulemd/v2/370d462@@modulemd@sha/Modulemd_2.0_gir_filelist --include=GObject-2.0 --symbol-prefix=modulemd_ --identifier-prefix=Modulemd --cflags-begin -Wpointer-arith -Werror=missing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wuninitialized -Werror=format-security -Werror=format=2 -Werror=implicit -Werror=init-self -Werror=main -Werror=missing-braces -Werror=return-type -Werror=array-bounds -Werror=write-strings -DG_LOG_USE_STRUCTURED '-DG_LOG_DOMAIN="libmodulemd"' -I./modulemd/v2/include/modulemd-2.0 -I../../../modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include --cflags-end --library modulemd -L/home/sgallagh/workspace/libmodulemd/api2/meson-private/tmpl32f8w7w/modulemd/v2 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=yaml
could not find clang line
Traceback (most recent call last):
  File "/usr/lib64/python3.7/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command '/usr/bin/../libexec/ccc-analyzer' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 96, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 547, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 418, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 294, in compile_introspection_binary
    return dc.run()
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 168, in run
    introspection_obj = self._compile(c_path)
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 197, in _compile
    self._options.init_sections)
  File "/usr/lib64/gobject-introspection/giscanner/ccompiler.py", line 250, in compile
    output_dir=os.path.abspath(os.sep))
  File "/usr/lib64/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.7/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/../libexec/ccc-analyzer' failed with exit status 1
ninja: build stopped: subcommand failed.
scan-build: 7 bugs found.
scan-build: Run 'scan-view /home/sgallagh/workspace/libmodulemd/api2/meson-logs/scanbuild/2019-01-03-145253-31875-1' to examine bug reports.
FAILED: meson-scan-build 
/usr/bin/meson --internal scanbuild /home/sgallagh/workspace/libmodulemd /home/sgallagh/workspace/libmodulemd/api2 /usr/bin/meson -Dbuild_api_v1=false -Dbuild_api_v2=true -Ddeveloper_build=true -Dtest_dirty_git=false -Dtest_installed_lib=false
ninja: build stopped: subcommand failed.
```

**Comment by ignatenkobrain** [comment]
I think this is the error: `could not find clang line`

**Comment by sgallagher** [comment]
That tells us that it can't find the clang executable, but why would it have problems only during the GIR generation? It works fine for the rest of the compilation.

**Comment by ignatenkobrain** [comment]
No, I think it tells that it outputs something unexpected.

**Comment by ignatenkobrain** [comment]
```
FAILED: modulemd/v2/Modulemd-2.0.gir 
/usr/bin/g-ir-scanner -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -v --no-libtool --namespace=Modulemd --nsversion=2.0 --warn-all --output modulemd/v2/Modulemd-2.0.gir -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2 -I./modulemd/v2/include/modulemd-2.0 -I../../../modulemd/v2/include/modulemd-2.0 --filelist=/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2/370d462@@modulemd@sha/Modulemd_2.0_gir_filelist --include=GObject-2.0 --symbol-prefix=modulemd_ --identifier-prefix=Modulemd --cflags-begin -Wpointer-arith -Werror=missing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wuninitialized -Werror=format-security -Werror=format=2 -Werror=implicit -Werror=init-self -Werror=main -Werror=missing-braces -Werror=return-type -Werror=array-bounds -Werror=write-strings -DG_LOG_USE_STRUCTURED '-DG_LOG_DOMAIN="libmodulemd"' -I./modulemd/v2/include/modulemd-2.0 -I../../../modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include --cflags-end --library modulemd -L/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=yaml
/usr/bin/../libexec/ccc-analyzer -E -DG_LOG_USE_STRUCTURED -DG_LOG_DOMAIN="libmodulemd" -I. -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2/include/modulemd-2.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gobject-introspection-1.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2 -o g-ir-cpp-yw605w89.i -C -Wpointer-arith -Werror=missing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wuninitialized -Werror=format-security -Werror=format=2 -Werror=implicit -Werror=init-self -Werror=main -Werror=missing-braces -Werror=return-type -Werror=array-bounds -Werror=write-strings /home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/g-ir-cpp-yw605w89.c
/usr/bin/../libexec/ccc-analyzer -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -fPIC -DG_LOG_USE_STRUCTURED -DG_LOG_DOMAIN="libmodulemd" -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2/include/modulemd-2.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/modulemd/v2/include/modulemd-2.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -c /home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/tmp-introspectyjmnv8hb/Modulemd-2.0.c -o /home/brain/Projects/upstream/libmodulemd/build/meson-private/tmpcz_nvs66/tmp-introspectyjmnv8hb/Modulemd-2.0.o -Wno-deprecated-declarations -pthread -Wpointer-arith -Werror=missing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wuninitialized -Werror=format-security -Werror=format=2 -Werror=implicit -Werror=init-self -Werror=main -Werror=missing-braces -Werror=return-type -Werror=array-bounds -Werror=write-strings
could not find clang line
```

Seems that this is coming directly from clang-analyzer.

**Comment by ignatenkobrain** [comment]
```
⋊> ~/P/u/libmodulemd on master ⨯ /usr/bin/../libexec/ccc-analyzer -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -fPIC -DG_LOG_USE_STRUCTURED -DG_LOG_DOMAIN='"libmodulemd"' -I/usr/include/gobject-introspection-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmplinqfu2t/modulemd/v2 -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmplinqfu2t/modulemd/v2/include/modulemd-2.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/home/brain/Projects/upstream/libmodulemd/build/meson-private/tmplinqfu2t/modulemd/v2/include/modulemd-2.0 -I/home/brain/Projects/upstream/libmodulemd/modulemd/v2/include/modulemd-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -c /home/brain/Projects/upstream/libmodulemd/build/meson-private/tmplinqfu2t/tmp-introspect2q9br2ci/Modulemd-2.0.c -o /home/brain/Projects/upstream/libmodulemd/build/meson-private/tmplinqfu2t/tmp-introspect2q9br2ci/Modulemd-2.0.o -Wno-deprecated-declarations -pthread -Wpointer-arith -Werror=missing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wuninitialized -Werror=format-security -Werror=format=2 -Werror=implicit -Werror=init-self -Werror=main -Werror=missing-braces -Werror=return-type -Werror=array-bounds -Werror=write-strings
could not find clang line
```

**Comment by ignatenkobrain** [comment]
```
read(5, "clang-7: error: unknown argument"..., 8192) = 513
```

**Comment by ignatenkobrain** [comment]
```
read(5, "clang-7: error: unknown argument: '-fstack-clash-protection'\nclang-7: error: unknown argument: '-fstack-clash-protection'\nclang-7
: error: unknown argument: '-flto-partition=none'\nclang version 7.0.1 (Fedora 7.0.1-2.fc30)\nTarget: x86_64-unknown-linux-gnu\nThread model
: posix\nInstalledDir: /usr/bin\nclang-7: warning: optimization flag '-fuse-linker-plugin' is not supported [-Wignored-optimization-argument
]\nclang-7: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]\n", 8192) = 513
```

**Comment by ignatenkobrain** [comment]
@sgallagher so:

* clang-analyzer uses Python's distutils to compile code (or something like this)
* distutils uses Python's embedded CFLAGS which on fedora include those flags which Clang doesn't support
* Then clang-analyzer simply fails.

So this is not a bug in Meson, but rather in clang which uses Python's CFLAGS.
