### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get_path' on git master

### ISSUE THREAD

**Issue by z3ntu** [mesonbuild/meson#4728]
```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\mesonbuild\mesonmain.py", line 111, in run
    return options.run_func(options)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 230, in run
    app.generate()
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 161, in generate
    self._generate(env)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 190, in _generate
    intr.run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 3880, in run
    super().run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 408, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 432, in evaluate_codeblock
    raise e
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 426, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 447, in evaluate_statement
    return self.evaluate_if(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 515, in evaluate_if
    self.evaluate_codeblock(node.elseblock)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 432, in evaluate_codeblock
    raise e
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 426, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 439, in evaluate_statement
    return self.assignment(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 437, in evaluate_statement
    return self.function_call(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 763, in function_call
    return func(node, posargs, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 153, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 181, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2963, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 3015, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 2095, in find_external_dependency
    raise pkg_exc[0]
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 2049, in find_external_dependency
    d = c()
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 551, in __init__
    '{!r}'.format(name, self.pkgbin.get_path()))
AttributeError: 'bool' object has no attribute 'get_path'
```

Git master from yesterday 13:00 GMT+1 still worked.

Complete build log: https://ci.appveyor.com/project/z3ntu/razer-test-pnxsa/builds/21415050/job/5p7gj4d3aw4neui0

EDIT: My Linux & macOS CI don't report any issue so this might be Windows-only / systems without pkg-config?

**Comment by z3ntu** [comment]
This should be added to the 0.49.1 milestone

**Comment by dcbaker** [comment]
I ran into this on FreeBSD because pkg-config wasn't installed. Not windows specific.

**Comment by nirbheek** [comment]
This doesn't happen with 0.49, only with git master. Removing milestone.

**Comment by nirbheek** [comment]
This was fixed in https://github.com/mesonbuild/meson/pull/4757.

**Comment by z3ntu** [comment]
Now there's another issue that looks very related:
```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\mesonbuild\mesonmain.py", line 114, in run
    return options.run_func(options)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 163, in generate
    self._generate(env)
  File "c:\python37\lib\site-packages\mesonbuild\msetup.py", line 193, in _generate
    intr.run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 3790, in run
    super().run()
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2919, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\interpreter.py", line 2966, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 2132, in find_external_dependency
    raise pkg_exc[0]
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 2086, in find_external_dependency
    d = c()
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\ui.py", line 513, in __init__
    QtBaseDependency.__init__(self, 'qt5', env, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\ui.py", line 219, in __init__
    self._pkgconfig_detect(mods, kwargs)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\ui.py", line 282, in _pkgconfig_detect
    kwargs, language=self.language)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 543, in __init__
    version_if_ok = self.check_pkgconfig(potential_pkgbin)
  File "c:\python37\lib\site-packages\mesonbuild\dependencies\base.py", line 831, in check_pkgconfig
    ''.format(' '.join(pkgbin.get_command())))
TypeError: sequence item 0: expected str instance, NoneType found
```
(full log: https://ci.appveyor.com/project/z3ntu/razer-test-pnxsa/builds/21996193/job/kar1h74ydtwovs63)

**Comment by z3ntu** [comment]
CC @Ericson2314

**Comment by nirbheek** [comment]
I have a fix for that + a test in https://github.com/mesonbuild/meson/pull/4846. Can you try that?
