### ISSUE TITLE
test-suite fails with python 3.5

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#4759]
Version: 0.49.0

Hi,

when trying to build meson on Debian stable I run into problems when running the test-suite.
Python is version 3.5.

```
test_python_module (__main__.NativeFileTests) ... ERROR
...
======================================================================
ERROR: test_python_module (__main__.NativeFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 4754, in test_python_module
    self._simple_test('python', 'python')
  File "run_unittests.py", line 4734, in _simple_test
    self.init(self.testcase, extra_args=['--native-file', config, '-Dcase={}'.format(case)])
  File "run_unittests.py", line 1084, in init
    out = self._run(self.setup_command + args + extra_args)
  File "run_unittests.py", line 1046, in _run
    raise subprocess.CalledProcessError(p.returncode, command, output=p.stdout)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/build/meson-0.49.0/meson.py', '--backend=ninja', '/build/meson-0.49.0/test cases/unit/46 native file binary', '/tmp/tmp8cza7xo7', '--prefix', '/usr', '--libdir', 'lib', '--native-file', '/tmp/tmp8cza7xo7/generated0.config', '-Dcase=python']' returned non-zero exit status 1

Stdout:
The Meson build system
Version: 0.49.0
Source dir: /build/meson-0.49.0/test cases/unit/46 native file binary
Build dir: /tmp/tmp8cza7xo7
Build type: native build
Project name: test project
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:18:2: ERROR:  <ExternalProgram '/tmp/tmp8cza7xo7/binary_wrapper0.py' -> ['/tmp/tmp8cza7xo7/binary_wrapper0.py']> is not a valid python

A full log can be found at /tmp/tmp8cza7xo7/meson-logs/meson-log.txt

Build started at 2019-01-10T18:37:06.483040
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.0
Source dir: /build/meson-0.49.0/test cases/unit/46 native file binary
Build dir: /tmp/tmp8cza7xo7
Build type: native build
Project name: test project
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:18:2: ERROR:  <ExternalProgram '/tmp/tmp8cza7xo7/binary_wrapper0.py' -> ['/tmp/tmp8cza7xo7/binary_wrapper0.py']> is not a valid python


----------------------------------------------------------------------
Ran 171 tests in 171.010s

FAILED (errors=1, skipped=21)
```
Full build log attached.
[build-stretch-llvm4.log](https://github.com/mesonbuild/meson/files/2746669/build-stretch-llvm4.log)

**Comment by dcbaker** [comment]
That's my bad apparently, I'll look at it.

**Comment by smcv** [comment]
For those interested in Python 3.5, #4797 might also be relevant (I don't *think* this is the same failure mode, but I could be wrong).

**Comment by eli-schwartz** [comment]
I'm not sure how to duplicate this problem. It doesn't seem to manifest in newer python versions, and trying to sanity check against python 3.5 / meson 0.49.0 failed since that seems to just crash a lot somewhere in ctypes (???).

Python 3.5 is looooong out of support upstream and our minimum required version is now 3.7, so unless this can be reproduced there I think this issue is no longer relevant.
