### ISSUE TITLE
AttributeError: 'PkgConfigDependency' object has no attribute 'cargs'

### ISSUE THREAD

**Issue by inizan-yannick** [mesonbuild/meson#477]
today I've errors when I configure directory : 
```
Traceback (most recent call last):
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 250, in run
    app.generate()
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 161, in generate
    g.generate(intr)
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 174, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 174, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 307, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, True, [], header_deps))
  File "/usr/share/meson/mesonbuild/backend/ninjabackend.py", line 1449, in generate_single_compile
    commands = self.generate_basic_compiler_args(target, compiler)
  File "/usr/share/meson/mesonbuild/backend/backends.py", line 248, in generate_basic_compiler_args
    commands += dep.get_compile_args()
  File "/usr/share/meson/mesonbuild/dependencies.py", line 177, in get_compile_args
    return self.cargs
AttributeError: 'PkgConfigDependency' object has no attribute 'cargs'
```

with this meson.build : 
```
project('taglib-glib', 'vala', 'cpp', 'c')

deps = [
    dependency('taglib', version: '>= 1.11', required: false),
    dependency('gio-2.0'),
    dependency('gee-0.8')
]

subdir('src')

shared_library('taglib-glib',
	sources: src,
	dependencies: deps,
	vala_args: [
		'-H', 'taglib-glib.h',
		'--vapidir', 'vapi'
	],
	install: true
)

maybe an error in meson Python files ?

**Comment by inizan-yannick** [comment]
well.. error due to package version
