### ISSUE TITLE
failing test_install_umask on new platform (=SunOS)

### ISSUE THREAD

**Issue by chincheta0815** [mesonbuild/meson#4869]
Can anyone help me with resolving the following issue with the "test_install_umask"?
I get the message:

```
======================================================================
ERROR: test_install_umask (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./run_unittests.py", line 4353, in test_install_umask
    self.install()
  File "./run_unittests.py", line 1161, in install
    self._run(self.install_command, workdir=self.builddir)
  File "./run_unittests.py", line 1092, in _run
    raise subprocess.CalledProcessError(p.returncode, command, output=p.stdout)
subprocess.CalledProcessError: Command '['ninja', '-w', 'dupbuild=err', '-d', 'explain', 'install']' returned non-zero exit status 1

Stdout:
The Meson build system
Version: 0.49.999
Source dir: /tmp/tmpjtgodnmf/26 install umask
Build dir: /tmp/tmpwcjz70k0
Build type: native build
Project name: install umask
Project version: undefined
Native C compiler: gcc (gcc 6.4.0 "gcc (OpenIndiana 6.4.0-OI-3) 6.4.0")
Build machine cpu family: x86
Build machine cpu: i686
Program myinstall.py found: YES (/tmp/tmpjtgodnmf/26 install umask/myinstall.py)
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja

ninja explain: deps for 'prog@exe/prog.c.o' are missing
ninja explain: prog@exe/prog.c.o is dirty
ninja explain: prog is dirty
[1/2] Compiling C object 'prog@exe/prog.c.o'.
[2/2] Linking target prog.

ninja explain: output PHONY of phony edge with no inputs doesn't exist
ninja explain: PHONY is dirty
ninja explain: meson-install is dirty
[0/1] Installing files.
/usr/bin/python3: can't open file '['/tmp/tmpjtgodnmf/26 install umask/myinstall.py']': [Errno 2] No such file or directory
Installing subdir /tmp/tmpjtgodnmf/26 install umask/subdir to /tmp/tmpwcjz70k0/install/usr/share/subdir
Installing /tmp/tmpjtgodnmf/26 install umask/subdir/datafile.dog to /tmp/tmpwcjz70k0/install/usr/share/subdir
Installing /tmp/tmpjtgodnmf/26 install umask/subdir/sayhello to /tmp/tmpwcjz70k0/install/usr/share/subdir
Installing prog to /tmp/tmpwcjz70k0/install/usr/bin
Installing /tmp/tmpjtgodnmf/26 install umask/sample.h to /tmp/tmpwcjz70k0/install/usr/include
Installing /tmp/tmpjtgodnmf/26 install umask/prog.1 to /tmp/tmpwcjz70k0/install/usr/share/man/man1
Installing /tmp/tmpjtgodnmf/26 install umask/datafile.cat to /tmp/tmpwcjz70k0/install/usr/share
Running custom install script '/tmp/tmpjtgodnmf/26 install umask/myinstall.py share file.dat'
FAILED: meson-install
/usr/bin/python3 /export/home/github.com/meson.git/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by chincheta0815** [comment]
Additionl info:
Run manually the test works.
