### ISSUE TITLE
tests fail with permission denied.

### ISSUE THREAD

**Issue by chincheta0815** [mesonbuild/meson#4871]
all tests running scripts from within the test folders fail with "permission denied".
They will run when the folder "test cases" and thus all the scripts needed have the execute bit (e.g. chmod 755) set.

Is that on purpose and if not how would I get that fixed?

**Comment by jpakkane** [comment]
Some of those scripts do not have execute bits set, but we should detect shebangs automatically and use it to run the scripts. Which platform is this on, which scripts fail and how?

**Comment by chincheta0815** [comment]
Well, if it would be some ;o), the feeling says hardly all ;o)

All .py-scripts in the "test cases" fail, by a "Permission denied" error.
These pop up in on eof the subpocess Popens invoked by .build() and .install() in the tests, e.g. test_configure_file_warnings:

```
test_configure_file_warnings (__main__.AllPlatformTests) ... ERROR

Stdout:
Traceback (most recent call last):
  File "/export/home/github.com/meson.git/mesonbuild/mesonmain.py", line 114, in run
    return options.run_func(options)
  File "/export/home/github.com/meson.git/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/export/home/github.com/meson.git/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/export/home/github.com/meson.git/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/export/home/github.com/meson.git/mesonbuild/interpreter.py", line 3797, in run
    super().run()
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/interpreter.py", line 2271, in func_run_command
    return self.run_command_impl(node, args, kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/interpreter.py", line 2339, in run_command_impl
    in_builddir=in_builddir, check=check, capture=capture)
  File "/export/home/github.com/meson.git/mesonbuild/interpreter.py", line 151, in __init__
    pc, self.stdout, self.stderr = self.run_command(cmd, args, env, source_dir, build_dir, subdir, mesonintrospect, in_builddir, check)
  File "/export/home/github.com/meson.git/mesonbuild/interpreter.py", line 175, in run_command
    p, o, e = Popen_safe(command_array, stdout=stdout, env=child_env, cwd=cwd)
  File "/export/home/github.com/meson.git/mesonbuild/mesonlib.py", line 949, in Popen_safe
    return Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "/export/home/github.com/meson.git/mesonbuild/mesonlib.py", line 957, in Popen_safe_legacy
    stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```




Another one that could be handled by adding "[sys.executable]" was in the test_install_umask (see https://github.com/chincheta0815/meson/blob/aaaf1914f84b7fd67667db7a3d31b479cc6139aa/mesonbuild/minstall.py#L420). This might just be a workaround here, so if you have a better idea...

The platform is Sunos. I am right now adding support for it.
see https://github.com/chincheta0815/meson/tree/add.SunOS

**Comment by bonzini** [comment]
From #5008:

> I reverted this change and I don't see any other tests failing
