### ISSUE TITLE
List index out of range when using dependency(method: 'system')

### ISSUE THREAD

**Issue by Qix-** [mesonbuild/meson#4882]
```meson
terra = dependency('terra', method: 'system')
```

`libterra.a` is in `/usr/local/lib`, I think it's worth mentioning.

Here's the full stack trace:

```
Dependency terra found: NO
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 112, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 230, in run
    app.generate()
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 190, in _generate
    intr.run()
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3874, in run
    super().run()
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 408, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 432, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 426, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 439, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 437, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 763, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 292, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 153, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 181, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3022, in func_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 2074, in find_external_dependency
    if pkg_exc[0]:
IndexError: list index out of range
FAILED: build.ninja
/usr/local/Cellar/meson/0.49.1/libexec/bin/meson --internal regenerate /src/tidemmo/terrac /src/tidemmo/terrac/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by Qix-** [comment]
Looks like this was fixed on master: https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/base.py#L2192
