### ISSUE TITLE
Can't use meson configure to change boolean option

### ISSUE THREAD

**Issue by copelnug** [mesonbuild/meson#4888]
# Problems
It's currently impossible to a binary option without using "-D". Furthermore, it is not obvious that using "-D" would solve the problem.

# Current behaviour
`meson configure --werror`
> Namespace(builddir='.', clearcache=False, projectoptions=[], run_func=<function run at 0x7f2c731d4ea0>, werror=True)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 112, in run
>     return options.run_func(options)
>   File "/usr/local/lib/python3.6/site-packages/mesonbuild/mconf.py", line 156, in run
>     coredata.update_cmd_line_file(builddir, options)
>   File "/usr/local/lib/python3.6/site-packages/mesonbuild/coredata.py", line 587, in update_cmd_line_file
>     config['options'].update(options.cmd_line_options)
>   File "/usr/local/lib/python3.6/_collections_abc.py", line 841, in update
>     self[key] = other[key]
>   File "/usr/local/lib/python3.6/configparser.py", line 1237, in __setitem__
>     self._parser._validate_value_types(option=key, value=value)
>   File "/usr/local/lib/python3.6/configparser.py", line 1177, in _validate_value_types
>     raise TypeError("option values must be strings")
> TypeError: option values must be strings

`meson configure --werror=True`
`meson configure --werror=true`

> usage: meson configure [-h]
> [--buildtype {plain,debug,debugoptimized,release,minsize,custom}]
>                        [--strip] [--unity {on,off,subprojects}]
>                        [--prefix PREFIX] [--libdir LIBDIR]
>                        [--libexecdir LIBEXECDIR] [--bindir BINDIR]
>                        [--sbindir SBINDIR] [--includedir INCLUDEDIR]
>                        [--datadir DATADIR] [--mandir MANDIR]
>                        [--infodir INFODIR] [--localedir LOCALEDIR]
>                        [--sysconfdir SYSCONFDIR]
>                        [--localstatedir LOCALSTATEDIR]
>                        [--sharedstatedir SHAREDSTATEDIR] [--werror]
>                        [--warnlevel {1,2,3}] [--layout {mirror,flat}]
>                        [--default-library {shared,static,both}]
>                        [--backend {ninja,vs,vs2010,vs2015,vs2017,xcode}]
>                        [--stdsplit] [--errorlogs]
>                        [--install-umask INSTALL_UMASK]
>                        [--auto-features {enabled,disabled,auto}]
>                        [--optimization {0,g,1,2,3,s}] [--debug]
>                        [--wrap-mode {default,nofallback,nodownload,forcefallback}]
>                        [-D option] [--clearcache]
>                        [builddir]
> meson configure: error: argument --werror: ignored explicit argument 'True'

# Proposed solutions
It would be great to accept those command lines.
At a minimum, they one should give a better error message (maybe with an indication of what to use instead).

**Comment by keszybz** [comment]
See also #5467.

**Comment by ThatNerdUKnow** [comment]
I'm experiencing this problem as well
```
The Meson build system
  Version: 0.64.0
  Source dir: /home/brandon/repos/libvmaf-sys/vmaf/libvmaf
  Build dir: /home/brandon/repos/libvmaf-sys/target/debug/build/libvmaf-sys-fe10f7bf47038abe/out/build
  Build type: native build

  meson.build:1:0: ERROR: Value 'true'  is not boolean (true or false).

  A full log can be found at /home/brandon/repos/libvmaf-sys/target/debug/build/libvmaf-sys-fe10f7bf47038abe/out/build/meson-logs/meson-log.txt
```
and the error file
```
Build started at 2022-12-20T22:42:22.349303
Main binary: /usr/bin/python3
Build Options: '-Denable_float=true ' -Dbuildtype=debug
Python system: Linux
The Meson build system
Version: 0.64.0
Source dir: /home/brandon/repos/libvmaf-sys/vmaf/libvmaf
Build dir: /home/brandon/repos/libvmaf-sys/target/debug/build/libvmaf-sys-fe10f7bf47038abe/out/build
Build type: native build

meson.build:1:0: ERROR: Value true  is not boolean (true or false).

```

**Comment by bonzini** [comment]
The error is now slightly better:

```
meson setup: error: argument --werror: ignored explicit argument 'true'
```

The message comes from argparse, so it's not really possible to improve it further.

It is documented that -D can be used:

> All these can be set by passing `-Doption=value` to `meson` (aka `meson setup`), or by setting them inside default_options of [`project()`](https://mesonbuild.com/Reference-manual_functions.html#project) in your `meson.build`. Some options can also be set by `--option=value`, or `--option value` -- a list is shown by running `meson setup --help`.

So I'm closing this.
