### ISSUE TITLE
install_data(vcs_tag) fails

### ISSUE THREAD

**Issue by F-i-f** [mesonbuild/meson#4893]
This is using Meson 0.49.1.
Problem also occurs with latest master (8a4a75cc59e7c1951deb58a5918ebe1b67a81881)

Given the simple meson.build:
```
project('test',
	 license: 'GPL3' )

tag = vcs_tag(command:  ['git', 'rev-parse', 'HEAD'],
	     input:    files('in'),
	     output:   'out',
	     fallback: 'unknown')
install_data(tag)
```
and with the file "in" set to:
```
@VCS_TAG@
```
Meson fails with:
```
% meson build
The Meson build system
Version: 0.49.999
Source dir: /home/phil/mux
Build dir: /home/phil/mux/build
Build type: native build
Project name: test
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Traceback (most recent call last):
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/mesonmain.py", line 114, in run
    return options.run_func(options)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreter.py", line 3804, in run
    super().run()
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/interpreter.py", line 3394, in func_install_data
    data = DataHolder(build.Data(sources, install_dir, install_mode, rename))
  File "/home/phil/meson/BUILD/lib/python3.7/site-packages/meson-0.49.999-py3.7.egg/mesonbuild/build.py", line 2257, in __init__
    assert(isinstance(s, File))
AssertionError
[1]    16306 exit 2     meson build
```

**Comment by jpakkane** [comment]
The error message is bad, but basically you can only install existing files with `install_data`, not anything that you build or create. Nobody has thus far needed to install the output of `vcs_tag` so functionality to do that has not been added.

**Comment by F-i-f** [comment]
What would it take to get that feature added?
I'm trying to use meson to build gnome shell extensions and embed the VCS tag in a json file (metadata.json).
