### ISSUE TITLE
No such file or directory: '/usr/bin/meson'

### ISSUE THREAD

**Issue by SkyzohKey** [mesonbuild/meson#497]
**OS:** Ubuntu 12.04.2 precise amd64 (Drone.io)

```
$ sudo python3 install_meson.py --prefix=/usr
Installing xcodebackend.py to /usr/share/meson.
Installing environment.py to /usr/share/meson.
Installing meson.py to /usr/share/meson.
Installing vcstagger.py to /usr/share/meson.
Installing ninjabackend.py to /usr/share/meson.
Installing depfixer.py to /usr/share/meson.
Installing compilers.py to /usr/share/meson.
Installing wrap.py to /usr/share/meson.
Installing meson_test.py to /usr/share/meson.
Installing backends.py to /usr/share/meson.
Installing gtkdochelper.py to /usr/share/meson.
Installing vs2010backend.py to /usr/share/meson.
Installing optinterpreter.py to /usr/share/meson.
Installing build.py to /usr/share/meson.
Installing mlog.py to /usr/share/meson.
Installing delwithsuffix.py to /usr/share/meson.
Installing dependencies.py to /usr/share/meson.
Installing symbolextractor.py to /usr/share/meson.
Installing wraptool.py to /usr/share/meson.
Installing rustrunner.py to /usr/share/meson.
Installing mesonlib.py to /usr/share/meson.
Installing meson_install.py to /usr/share/meson.
Installing mesonintrospect.py to /usr/share/meson.
Installing mesonconf.py to /usr/share/meson.
Installing interpreter.py to /usr/share/meson.
Installing mparser.py to /usr/share/meson.
Installing commandrunner.py to /usr/share/meson.
Installing mesongui.py to /usr/share/meson.
Installing coredata.py to /usr/share/meson.
Installing mesonstart.ui to /usr/share/meson.
Installing mesonmain.ui to /usr/share/meson.
Installing mesonrunner.ui to /usr/share/meson.
Creating symlinks.
Traceback (most recent call last):
  File "install_meson.py", line 95, in <module>
    os.unlink(bin_name)
OSError: [Errno 2] No such file or directory: '/usr/bin/meson'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install_meson.py", line 96, in <module>
    except FileNotFoundError:
NameError: name 'FileNotFoundError' is not defined
```

**Comment by jpakkane** [comment]
That is an old version, Meson has installed with standard distutils/setuptools for quite a while now. Please upgrade.
