### ISSUE TITLE
Ternary operator inside method call crashes the parser

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5003]
```meson
project('mesonfail')
foo = 'FOO=@0@'.format(get_option('foo') == 'bar' ? 0 : 1)
```

```
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 115, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/data/git/meson/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/data/git/meson/mesonbuild/msetup.py", line 180, in _generate
    intr = interpreter.Interpreter(b)
  File "/data/git/meson/mesonbuild/interpreter.py", line 2018, in __init__
    self.load_root_meson_file()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 379, in load_root_meson_file
    self.ast = mparser.Parser(code, self.subdir).parse()
  File "/data/git/meson/mesonbuild/mparser.py", line 514, in parse
    block = self.codeblock()
  File "/data/git/meson/mesonbuild/mparser.py", line 792, in codeblock
    curline = self.line()
  File "/data/git/meson/mesonbuild/mparser.py", line 786, in line
    return self.statement()
  File "/data/git/meson/mesonbuild/mparser.py", line 519, in statement
    return self.e1()
  File "/data/git/meson/mesonbuild/mparser.py", line 529, in e1
    value = self.e1()
  File "/data/git/meson/mesonbuild/mparser.py", line 522, in e1
    left = self.e2()
  File "/data/git/meson/mesonbuild/mparser.py", line 547, in e2
    left = self.e3()
  File "/data/git/meson/mesonbuild/mparser.py", line 556, in e3
    left = self.e4()
  File "/data/git/meson/mesonbuild/mparser.py", line 565, in e4
    left = self.e5()
  File "/data/git/meson/mesonbuild/mparser.py", line 574, in e5
    return self.e5add()
  File "/data/git/meson/mesonbuild/mparser.py", line 577, in e5add
    left = self.e5sub()
  File "/data/git/meson/mesonbuild/mparser.py", line 583, in e5sub
    left = self.e5mod()
  File "/data/git/meson/mesonbuild/mparser.py", line 589, in e5mod
    left = self.e5mul()
  File "/data/git/meson/mesonbuild/mparser.py", line 595, in e5mul
    left = self.e5div()
  File "/data/git/meson/mesonbuild/mparser.py", line 601, in e5div
    left = self.e6()
  File "/data/git/meson/mesonbuild/mparser.py", line 611, in e6
    return self.e7()
  File "/data/git/meson/mesonbuild/mparser.py", line 628, in e7
    left = self.method_call(left)
  File "/data/git/meson/mesonbuild/mparser.py", line 720, in method_call
    args = self.args()
  File "/data/git/meson/mesonbuild/mparser.py", line 692, in args
    a = ArgumentNode(s)
  File "/data/git/meson/mesonbuild/mparser.py", line 419, in __init__
    self.subdir = token.subdir
AttributeError: 'TernaryNode' object has no attribute 'subdir'
The Meson build system
Version: 0.49.999
Source dir: /tmp/mesonfail
Build dir: /tmp/mesonfail/build
Build type: native build
```

**Comment by Akaricchi** [comment]
It looks like this bug is actually quite old; see #2404 #3690

**Comment by dcbaker** [comment]
Yup, I've run into this a few times myself.

**Comment by dcbaker** [comment]
I'm interested, I extended the test case, now let me see if I can fix the actual bug :)
