### ISSUE TITLE
gstreamer-sharp tests don't have MONO_PATH set correctly sometimes (to be investigated further)

### ISSUE THREAD

**Issue by alatiera** [mesonbuild/meson#5087]
[Gstreamer Sharp](https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp) test suite started failing once we tried to bump the version of meson from 0.49.2 to 0.50.0. Tested the same exact trees with both meson versions so the change is not in our end.

```
$ meson test -C build --suite gstreamer-sharp --print-errorlogs
The output from the failed tests:

1/3 gstreamer-sharp / gstreamer_sharp_abi   FAIL     0.28 s (exit status 1)

--- command ---
MONO_PATH='/root/gst-build/build/subprojects/gstreamer-sharp/Tests/NUnit/3.10.1/lib/net45/nunit.framework.dll/..' LD_LIBRARY_PATH='//root/gst-build/build/subprojects/gst-editing-services/ges' /root/gst-build/subprojects/gstreamer-sharp/Tests/test_abi.py /root/gst-build/build/subprojects/gstreamer-sharp/sources/gst_sharp_c_abi /root/gst-build/build/subprojects/gstreamer-sharp/sources/gst_sharp_cs_abi.exe
--- stderr ---

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
Traceback (most recent call last):
  File "/root/gst-build/subprojects/gstreamer-sharp/Tests/test_abi.py", line 12, in <module>
    csharp_abi = subprocess.check_output(launcher + [sys.argv[2]]).decode().split("\n")
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mono', '--debug', '/root/gst-build/build/subprojects/gstreamer-sharp/sources/gst_sharp_cs_abi.exe']' returned non-zero exit status 1.
-------

2/3 gstreamer-sharp / gst-editing-servicesabi  FAIL     0.29 s (exit status 1)

--- command ---
MONO_PATH='/root/gst-build/build/subprojects/gstreamer-sharp/Tests/NUnit/3.10.1/lib/net45/nunit.framework.dll/..' LD_LIBRARY_PATH='//root/gst-build/build/subprojects/gst-editing-services/ges' /root/gst-build/subprojects/gstreamer-sharp/Tests/test_abi.py /root/gst-build/build/subprojects/gstreamer-sharp/ges/gst-editing-services_c_abi /root/gst-build/build/subprojects/gstreamer-sharp/ges/gst-editing-services_cs_abi.exe
--- stderr ---

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' or one of its dependencies.
File name: 'glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
Traceback (most recent call last):
  File "/root/gst-build/subprojects/gstreamer-sharp/Tests/test_abi.py", line 12, in <module>
    csharp_abi = subprocess.check_output(launcher + [sys.argv[2]]).decode().split("\n")
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['mono', '--debug', '/root/gst-build/build/subprojects/gstreamer-sharp/ges/gst-editing-services_cs_abi.exe']' returned non-zero exit status 1.
-------
```

looking at the introspection there's a suspicious path set.
`            "MONO_PATH": "/root/gst-build/build/subprojects/gstreamer-sharp/Tests/NUnit/3.10.1/lib/net45/nunit.framework.dll/..",`

[full introspection here](https://gist.github.com/alatiera/0024c1b631d4ff78ae171f432d400568)

cc @thiblahute

**Comment by jpakkane** [comment]
Can you bisect the commit that broke this?

**Comment by dcbaker** [comment]
I not only can't bisect this, I can reproduce this exact bug with 0.49.2. After hacking up the MONO_PATH to be correct (including both the nunit plugin and $builddir/sources, I still can't get the tests to pass. I'm not sure what's going on here and without help from upstream I'm not sure we can resolve this, @alatiera, @nirbheek

**Comment by nirbheek** [comment]
CCing @thiblahute who wrote the C# support.

**Comment by nirbheek** [comment]
This is not a regression in 0.50, the same behaviour also happens on 0.49.2 in specific conditions. Something to do with how `env.prepend()` works. Removing milestone.

**Comment by alatiera** [comment]
Indeed, sorry for the misleading title. We thought it happened after updating meson but that wasn't the case.

I've looked at it with nirbeek the other day and looks like that might be even considered a bug on gstreamer-sharp side. This error occurs if you have installed `nunit3`. Either just `nunit3` or alongside `nunit2`. With just `nunit2` everything works as expected.

**Comment by nirbheek** [comment]
This is not a Meson bug. The build files are assuming that `prepend()` stacks with previous calls such as `set()`.
