### ISSUE TITLE
vcs_tag() errors with --backend=xcode

### ISSUE THREAD

**Issue by fzwoch** [mesonbuild/meson#5104]
```meson
project('vcs_tag_test', 'c',
    version : '0.0.0'
)

vcs = vcs_tag(
    command : meson.project_version(),
    input : 'version.h.in',
    output : 'version.h',
)

library('vcs_tag_test', vcs)
```

`version.h.in` Only has `@VCS_TAG@` as content.

This works fine with ninja backend but fails with xcode backend with the following error:

```
The Meson build system
Version: 0.50.0
Source dir: /home/fzwoch/code/x
Build dir: /home/fzwoch/code/x/xcode
Build type: native build
Project name: vcs_tag_test
Project version: 0.0.0
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-2) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
Traceback (most recent call last):
  File "/home/fzwoch/code/meson/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/home/fzwoch/code/meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/fzwoch/code/meson/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/home/fzwoch/code/meson/mesonbuild/msetup.py", line 216, in _generate
    intr.backend.generate(intr)
  File "/home/fzwoch/code/meson/mesonbuild/backend/xcodebackend.py", line 80, in generate
    self.generate_filemap()
  File "/home/fzwoch/code/meson/mesonbuild/backend/xcodebackend.py", line 131, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'
```

**Comment by erick2red** [comment]
Any updates on this?

I have the same issue on a different project.
