### ISSUE TITLE
${LANG}_pch hates file objects, throws exception

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5129]
```meson
# meson.build in some subdir:

glslang_pch = [files('pch.h'), files('pch.cpp')]

.........

# meson.build outside the subdir:

libglslang = library('glslang',
    glslang_src,
    cpp_pch : glslang_pch,
    link_with : [libspirv, liboglcompiler],
    dependencies : threads_dep,
    build_by_default : not meson.is_subproject(),
)
```

```
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/data/git/meson/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/data/git/meson/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/data/git/meson/mesonbuild/interpreter.py", line 3828, in run
    super().run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3375, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3088, in func_library
    return self.build_library(node, args, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3966, in build_library
    return self.build_target(node, args, kwargs, SharedLibraryHolder)
  File "/data/git/meson/mesonbuild/interpreter.py", line 4025, in build_target
    target = targetclass(name, self.subdir, self.subproject, is_cross, sources, objs, self.environment, kwargs)
  File "/data/git/meson/mesonbuild/build.py", line 1544, in __init__
    super().__init__(name, subdir, subproject, is_cross, sources, objects, environment, kwargs)
  File "/data/git/meson/mesonbuild/build.py", line 474, in __init__
    self.process_kwargs(kwargs, environment)
  File "/data/git/meson/mesonbuild/build.py", line 1713, in process_kwargs
    super().process_kwargs(kwargs, environment)
  File "/data/git/meson/mesonbuild/build.py", line 809, in process_kwargs
    self.add_pch('cpp', cpp_pchlist)
  File "/data/git/meson/mesonbuild/build.py", line 1097, in add_pch
    if (os.path.dirname(pchlist[0]) != os.path.dirname(pchlist[1])):
  File "/usr/lib64/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not File
```

**Comment by eli-schwartz** [comment]
This was fixed by #5132 but never linked, so this issue never got closed.
