### ISSUE TITLE
Python error on introspect on meson.build file

### ISSUE THREAD

**Issue by ocrete** [mesonbuild/meson#5177]
Some introspect methods work on unconfigured builds, but for the other I gets a Python exception.
```
$ meson introspect --dependencies meson.build 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mintro.py", line 405, in run
    return print_results(options, results, indent)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mintro.py", line 374, in print_results
    print(json.dumps(results[0][1], indent=indent))
  File "/usr/lib64/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib64/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type FunctionNode is not JSON serializable
```

**Comment by mensinda** [comment]
Do you have the `meson.build` publically available? Unfortunately, the stack trace alone isn't enough to find the underlying bug in this case.

**Comment by mensinda** [comment]
Could you test if #5197 fixes this issue for your use case?
