### ISSUE TITLE
`benchmark`s don't build executables they depend on, unlike `test`s

### ISSUE THREAD

**Issue by jmesmon** [mesonbuild/meson#5239]
Example:

```
# meson.build
project('bench-fail', 'c')

t1 = executable('t1', 't.c',
  build_by_default: false)
benchmark('t1', t1)


t2 = executable('t2', 't.c',
  build_by_default: false)
test('t2', t2)
```

```
/* t.c */
```
int main(void)
{
	return 0;
}
```

This makes it difficult (process-wise) to mark benchmarks as not needed by default.

**Comment by michaelcadilhac** [comment]
Note that: 1. `t2` is built even if `--benchmark` is provided, 2. `t1` is not built, but it seems that the code expect it to be, since it fails with `FileNotFoundError`:

```
$ meson test --benchmark
ninja: Entering directory `/tmp/ms/build'
[1/1] Linking target t2
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1261, in run
    return th.doit()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 995, in doit
    self.run_tests(tests)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1158, in run_tests
    res = single_test.run()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 648, in run
    return self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_args)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 705, in _run_cmd
    p = subprocess.Popen(cmd + extra_cmd,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ms/build/t1'
```

**Comment by bonzini** [comment]
`meson test --benchmark` works these days with the provided test:

```
ninja: Entering directory `/home/pbonzini/work/upstream/meson/ff/build'
[2/2] Linking target t1
1/1 bench-fail:t1        OK              0.01s

Ok:                1   
Fail:              0   

Full log written to /home/pbonzini/work/upstream/meson/ff/build/meson-logs/testlog.txt
```
