### ISSUE TITLE
Running "meson configure" in source directory raises an exception (again)

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5256]
Sorry for the lack of an isolated test-case. Apparently [the Taisei repo](https://github.com/taisei-project/taisei/) can serve as a decent integration test for this feature in general.

Ping @mensinda 

```
[0] [akari@navi] [?master ← /home/akari/git/taisei]
 % meson configure
Unable to evaluate subdir([]) in AstInterpreter --> Skipping
Unable to evaluate subdir([]) in AstInterpreter --> Skipping
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/mconf.py", line 200, in run
    c = Conf(builddir)
  File "/data/git/meson/mesonbuild/mconf.py", line 56, in __init__
    intr.analyze()
  File "/data/git/meson/mesonbuild/ast/introspection.py", line 274, in analyze
    self.run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "/data/git/meson/mesonbuild/ast/interpreter.py", line 149, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "/data/git/meson/mesonbuild/ast/interpreter.py", line 216, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 470, in evaluate_statement
    return self.evaluate_plusassign(cur)
  File "/data/git/meson/mesonbuild/ast/interpreter.py", line 177, in evaluate_plusassign
    self.assign_vals[node.var_name] += [self.evaluate_statement(node.value)]
KeyError: 'em_bundle_misc_packer_args'

[2] [akari@navi] [?master ← /home/akari/git/taisei]
 % git describe
v1.2-366-g387d16d6
```

**Comment by Akaricchi** [comment]
I think the cause for this is access to the `em_bundle_misc_packer_args` variable, [which is declared dynamically via a call to `set_variable`, and never statically](https://github.com/taisei-project/taisei/blob/master/resources/meson.build). Assuming the introspection interpreter doesn't evaluate any function calls, this seems like a difficult problem. If there's no feasible solution, this limitation should be documented, and perhaps setting of undefined variables via `set_variable` should be deprecated.

**Comment by mensinda** [comment]
Yeah, there are a lot of edge cases to think about.

Should be fixed with #5259

**Comment by Akaricchi** [comment]
@mensinda Indeed that fixed it, thanks. I've tried to break it again with a silly contrived case, and I think I accidentally found another related but distinct issue. This snippet:
```meson
set_variable(run_command('echo', 'insanity').stdout.strip(), [])
```

Causes `meson configure` to silently exit with status code 1, without printing anything (other than the usual `subdir()` warnings). Same behavior with and without the patch.

**Comment by mensinda** [comment]
That line is evil... But I will also try to fix that insanity :D

**Comment by mensinda** [comment]
Wait a minute:

```
The Meson build system
Version: 0.50.999
Source dir: /home/daniel/projects/meson/test cases/unit/55 introspection
Build dir: /home/daniel/projects/meson/tmp
Build type: native build

meson.build:15:51: ERROR: Expecting lparen got dot.
set_variable(run_command('echo', 'insanity').stdout.strip(), [])
                                                   ^

A full log can be found at /home/daniel/projects/meson/tmp/meson-logs/meson-log.txt
```

Are you sure that
```meson
set_variable(run_command('echo', 'insanity').stdout.strip(), [])
```
is valid meson? The above error was generated with a normal meson setup.

**Comment by Akaricchi** [comment]
Yeah sorry, I messed that up. Already realized that and started typing a response... It would be nice if the introspection interpreter reported syntax errors instead of swallowing them silently, though.

**Comment by mensinda** [comment]
The problem with printing errors is that I have to disable the entire output of the interpreter and parser so that the output JSON format doesn't get messed up. Although, this might not be necessary with `meson configure`
