### ISSUE TITLE
meson setup with Boost deps fails after upgrade to 0.50.1

### ISSUE THREAD

**Issue by mtrenkmann** [mesonbuild/meson#5285]
`meson build` cannot detect Boost dependencies anymore after updating from `0.49.2` to `0.50.1`.

This `meson.build` file with a Boost dependency worked with `0.49.2` **but not with** `0.50.1`:

```meson
project('tutorial', 'cpp')
boost = dependency('boost', modules : ['program_options'])
executable('demo', 'main.cc', dependencies : [ boost ])
```

Console output:

```sh
~/projects/test$ meson build
The Meson build system
Version: 0.50.1
Source dir: /home/martin/projects/test
Build dir: /home/martin/projects/test/build
Build type: native build
Project name: tutorial
Project version: undefined
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 246, in run
    app.generate()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 3817, in run
    super().run()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 1019, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2934, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2981, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/dependencies/base.py", line 2350, in find_external_dependency
    d = c()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/dependencies/boost.py", line 145, in __init__
    self.detect_lib_modules()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/dependencies/boost.py", line 271, in detect_lib_modules
    self.detect_lib_modules_nix()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/dependencies/boost.py", line 446, in detect_lib_modules_nix
    libdirs = mesonlib.get_library_dirs()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonlib.py", line 692, in get_library_dirs
    unixdirs += [str(x) for x in (Path('/usr/lib/') / plat).iterdir() if x.is_dir()]
UnboundLocalError: local variable 'plat' referenced before assignment
```

**Comment by XVilka** [comment]
Looks like a target for https://github.com/mesonbuild/meson/milestone/38

**Comment by lazka** [comment]
Introduced in 907af96193b3 afaics @scivision

**Comment by lazka** [comment]
Hm, what's the difference between `mesonlib.get_library_dirs()` and `self.clib_compiler.get_library_dirs(self.env)`?

**Comment by scivision** [comment]
Making fix now, just a typo. `plat` => `machine`

**Comment by jpakkane** [comment]
Can you test if the linked MR fixes it for you?

**Comment by scivision** [comment]
meson.build:
```meson
project('tutorial', 'cpp')
boost = dependency('boost', modules : ['program_options'])
```

results in:
```
The Meson build system
Version: 0.50.999
...
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency Boost (program_options) found: YES 1.65.1
...
```

**Comment by mtrenkmann** [comment]
I can confirm that the linked MR fixes the problem.

Console output is:

```
The Meson build system
Version: 0.50.999
Source dir: /home/martin/projects/test
Build dir: /home/martin/projects/test/build
Build type: native build
Project name: tutorial
Project version: undefined
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency Boost (program_options) found: YES 1.65.1
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
```

**Comment by lazka** [comment]
I guess this can be closed?
