### ISSUE TITLE
Unit test fails on ubuntu disco & bionic (test_build_rpath | test_rpath_uses_ORIGIN)

### ISSUE THREAD

**Issue by SolarLiner** [mesonbuild/meson#5366]
2 unit tests are failing on Ubuntu Disco (19.04) and Bionic (18.04), as well as in the `python:3.7.3` and `python:3.6.5` Docker images. Tested off of master (d31db565) on all 4.
<details>
<summary>Logs</summary>

```
======================================================================
FAIL: test_build_rpath (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 4775, in test_build_rpath
    self.assertEqual(build_rpath, '$ORIGIN/sub:/foo/bar')
AssertionError: None != '$ORIGIN/sub:/foo/bar'

Stdout:
The Meson build system
Version: 0.50.999
Source dir: /home/solarliner/Documents/Projets/Externe/meson-upstream/meson/test cases/unit/10 build_rpath
Build dir: /tmp/tmpxtv95i7b
Build type: native build
Project name: build rpath
Project version: undefined
Native C compiler: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Native C++ compiler: c++ (gcc 8.3.0 "c++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 3
Found ninja-1.8.2 at /usr/bin/ninja

ninja explain: deps for 'sub/ddc6e2b@@stuff@sha/stuff.c.o' are missing
ninja explain: sub/ddc6e2b@@stuff@sha/stuff.c.o is dirty
ninja explain: sub/libstuff.so is dirty
ninja explain: deps for 'prog@exe/prog.c.o' are missing
ninja explain: prog@exe/prog.c.o is dirty
ninja explain: sub/libstuff.so is dirty
ninja explain: sub/ddc6e2b@@stuff@sha/libstuff.so.symbols is dirty
ninja explain: prog is dirty
ninja explain: deps for 'progcxx@exe/prog.cc.o' are missing
ninja explain: progcxx@exe/prog.cc.o is dirty
ninja explain: sub/ddc6e2b@@stuff@sha/libstuff.so.symbols is dirty
ninja explain: progcxx is dirty
[1/7] Compiling C object 'sub/ddc6e2b@@stuff@sha/stuff.c.o'.
[2/7] Linking target sub/libstuff.so.
[3/7] Compiling C object 'prog@exe/prog.c.o'.
[4/7] Generating symbol file 'sub/ddc6e2b@@stuff@sha/libstuff.so.symbols'.
[5/7] Linking target prog.
[6/7] Compiling C++ object 'progcxx@exe/prog.cc.o'.
[7/7] Linking target progcxx.
```

```
=====================================================================
FAIL: test_rpath_uses_ORIGIN (__main__.AllPlatformTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 2298, in test_rpath_uses_ORIGIN
    self.assertTrue(rpath, 'Rpath could not be determined for {}.'.format(each))
AssertionError: None is not true : Rpath could not be determined for prog.

Stdout:
The Meson build system
Version: 0.50.999
Source dir: /home/solarliner/Documents/Projets/Externe/meson-upstream/meson/test cases/common/43 library chain
Build dir: /tmp/tmps8yk7r4m
Build type: native build
Project name: libchain
Project version: undefined
Native C compiler: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 4
Found ninja-1.8.2 at /usr/bin/ninja

ninja explain: deps for 'subdir/subdir2/8e36f39@@lib2@sha/lib2.c.o' are missing
ninja explain: subdir/subdir2/8e36f39@@lib2@sha/lib2.c.o is dirty
ninja explain: subdir/subdir2/liblib2.so is dirty
ninja explain: deps for 'subdir/subdir3/2079cfb@@lib3@sha/lib3.c.o' are missing
ninja explain: subdir/subdir3/2079cfb@@lib3@sha/lib3.c.o is dirty
ninja explain: subdir/subdir3/liblib3.so is dirty
ninja explain: deps for 'subdir/bdf6c15@@lib1@sha/lib1.c.o' are missing
ninja explain: subdir/bdf6c15@@lib1@sha/lib1.c.o is dirty
ninja explain: subdir/subdir2/liblib2.so is dirty
ninja explain: subdir/subdir2/8e36f39@@lib2@sha/liblib2.so.symbols is dirty
ninja explain: subdir/subdir3/liblib3.so is dirty
ninja explain: subdir/subdir3/2079cfb@@lib3@sha/liblib3.so.symbols is dirty
ninja explain: subdir/liblib1.so is dirty
ninja explain: deps for 'prog@exe/main.c.o' are missing
ninja explain: prog@exe/main.c.o is dirty
ninja explain: subdir/liblib1.so is dirty
ninja explain: subdir/bdf6c15@@lib1@sha/liblib1.so.symbols is dirty
ninja explain: prog is dirty
[1/11] Compiling C object 'subdir/subdir2/8e36f39@@lib2@sha/lib2.c.o'.
[2/11] Compiling C object 'subdir/subdir3/2079cfb@@lib3@sha/lib3.c.o'.
[3/11] Compiling C object 'prog@exe/main.c.o'.
[4/11] Compiling C object 'subdir/bdf6c15@@lib1@sha/lib1.c.o'.
[5/11] Linking target subdir/subdir3/liblib3.so.
[6/11] Linking target subdir/subdir2/liblib2.so.
[7/11] Generating symbol file 'subdir/subdir2/8e36f39@@lib2@sha/liblib2.so.symbols'.
[8/11] Generating symbol file 'subdir/subdir3/2079cfb@@lib3@sha/liblib3.so.symbols'.
[9/11] Linking target subdir/liblib1.so.
[10/11] Generating symbol file 'subdir/bdf6c15@@lib1@sha/liblib1.so.symbols'.
[11/11] Linking target prog.
```
</details>

**Comment by jpakkane** [comment]
[Is this using eatmydata and/or overlayfs?](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917501)

**Comment by SolarLiner** [comment]
Neither of them are installed on my machine, nor on the Docker images. So I'd guess not.

**Comment by jpakkane** [comment]
Docker uses overlayfs internally IIRC.

**Comment by bonzini** [comment]
Python
