### ISSUE TITLE
setup --wipe crashes when the build directory has a symlink pointing to the outside

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#5545]
```
Traceback (most recent call last):
  File "/home/lantw44/gnome/source/meson/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/home/lantw44/gnome/source/meson/mesonbuild/msetup.py", line 240, in run
    app = MesonApp(options)
  File "/home/lantw44/gnome/source/meson/mesonbuild/msetup.py", line 89, in __init__
    mesonlib.windows_proof_rmtree(l)
  File "/home/lantw44/gnome/source/meson/mesonbuild/mesonlib.py", line 1168, in windows_proof_rmtree
    shutil.rmtree(f)
  File "/usr/local/lib/python3.6/shutil.py", line 496, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/local/lib/python3.6/shutil.py", line 494, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```

This happens when using `meson setup --wipe` in the shell opened by JHBuild on build failure. When JHBuild opens a debug shell, it puts a symlink called `.jhbuild-srcdir` under the build directory to allow the user to access the source directory with the link.
https://gitlab.gnome.org/GNOME/jhbuild/commit/3f5e90d152ab39627503dfcf91169fd5b81bd76e

If the user run `meson setup --wipe` without deleting the symlink created by JHBuild, meson crashes with the above message.

**Comment by pinchartl** [comment]
This should be fixed now that https://github.com/mesonbuild/meson/pull/7055 has been merged.

**Comment by lantw44** [comment]
I confirmed that meson no longer crashes on the current master branch.
