### ISSUE TITLE
running meson fails on latest release 0.51.0

### ISSUE THREAD

**Issue by cxleb** [mesonbuild/meson#5550]
i installed meson 0.51.0 64 using the msi installer and when running "meson" as a test i produces this stack trace:
Traceback (most recent call last):

```
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meson.py", line 22, in <module>
  File "C:\python\lib\pathlib.py", line 1109, in resolve
  File "C:\python\lib\pathlib.py", line 186, in resolve
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'meson'
```

i rolled back to version 0.50.1 which worked correctly

**Comment by jpakkane** [comment]
The attached PR should fix this. I made a test MSI package and put it [here](https://www.dropbox.com/s/0iwlily4bs7vtz2/meson-0.51.999-64.msi?dl=0). Can you test if that works for you?

**Comment by cxleb** [comment]
this has fixed the issue, thank you.
