### ISSUE TITLE
Meson crashes on cross compilation with Vala

### ISSUE THREAD

**Issue by nahuelwexd** [mesonbuild/meson#5580]
```
$ meson build-win32 --cross-file win32
The Meson build system
Version: 0.51.0
Source dir: /home/nahuelwexd/Proyectos/Proyectos Personales/SyncVideo
Build dir: /home/nahuelwexd/Proyectos/Proyectos Personales/SyncVideo/build-win32
Build type: cross build
Project name: syncvideo
Project version: 0.1.0
C compiler for the build machine: cc (gcc 9.1.0 "cc (GCC) 9.1.0")
Vala compiler for the build machine: valac (valac 0.44.5)
C compiler for the host machine: /usr/bin/x86_64-w64-mingw32-gcc (gcc 9.1.0 "x86_64-w64-mingw32-gcc (GCC) 9.1.0")
Vala compiler for the host machine: valac (valac 0.44.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/x86_64-w64-mingw32-pkg-config (1.6.1)
Run-time dependency gtk+-3.0 found: YES 3.24.9
Build targets in project: 1
Found ninja-1.9.0 at /usr/bin/ninja
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 240, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 158, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 210, in _generate
    intr.backend.generate(intr)
  File "/usr/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 295, in generate
    self.generate_target(t)
  File "/usr/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 498, in generate_target
    vala_generated_sources = self.generate_vala_compile(target)
  File "/usr/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 1256, in generate_vala_compile
    self.add_build(element)
  File "/usr/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 888, in add_build
    self.ruledict[build.rule].refcount += 1
KeyError: 'vala_COMPILER'
```

**Comment by jpakkane** [comment]
Can you try the latest trunk? I think we fixed some of these.

**Comment by nahuelwexd** [comment]
Yeah, it's fixed. Then I close this issue
