### ISSUE TITLE
0.51.0: Working Project Fails to Build after Update

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/meson#5587]
I get a big long traceback message when I try to build a project after updating to 0.51.0:

Tips on figuring out the offending build code?

```
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 240, in run
    app.generate()
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 158, in generate
    self._generate(env)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 187, in _generate
    intr.run()
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3917, in run
    super().run()
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1048, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3145, in func_executable
    return self.build_target(node, args, kwargs, ExecutableHolder)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4108, in build_target
    target = targetclass(name, self.subdir, self.subproject, for_machine, sources, objs, self.environment, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 1425, in __init__
    super().__init__(name, subdir, subproject, for_machine, sources, objects, environment, kwargs)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 469, in __init__
    self.process_kwargs(kwargs, environment)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 854, in process_kwargs
    self.add_deps(deplist)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 1029, in add_deps
    self.add_deps(dep.ext_deps)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 1029, in add_deps
    self.add_deps(dep.ext_deps)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 1017, in add_deps
    self.link(l)
  File "/usr/local/Cellar/meson/0.51.0/lib/python3.7/site-packages/mesonbuild/build.py", line 1065, in link
    msg = 'Tried to mix libraries for machines {1} and {2} in target {!r}'.format(self.name, self.for_machine, t.for_machine)
ValueError: cannot switch from manual field specification to automatic field numbering
make: *** [groundwork] Error 2
```

**Comment by phillipjohnston** [comment]
Logs:

[meson-log.txt](https://github.com/mesonbuild/meson/files/3347601/meson-log.txt)
[console-output.txt](https://github.com/mesonbuild/meson/files/3347602/console-output.txt)

**Comment by dcbaker** [comment]
Do you happen to have a a library with `native : true` and one with `native : false` that you're trying to link together? That's what the assertion is meant to handle, I think. the assertion itself is broken as well.

**Comment by phillipjohnston** [comment]
I'm working through the libraries to confirm, but not that I'm aware of. This project has been generally well-behaved with native/cross libraries, and I've seen that assertion before when I messed it up. The only change from the previously working build was upgrading meson.

**Comment by dcbaker** [comment]
It's possible that has been fixed, there were several regression around cross compiling in 0.51, if you could try with master it might already be fixed for 0.51.1

**Comment by phillipjohnston** [comment]
Thanks for the pointer. With top of tree the assertion is fixed, and I can see the problematic targets:

```
WARNING: Tried to mix libraries for machines MachineChoice.HOST and MachineChoice.BUILD in target 'fwdemo_x86' This will fail in cross build.
WARNING: Tried to mix libraries for machines MachineChoice.HOST and MachineChoice.BUILD in target 'blinky_x86' This will fail in cross build.
```

Checking the references to see if there's a real mismatch, but I'm pretty good about separating them:

```
	blinky_simulator_app = executable('blinky_native',
		sources: ['blinky.cpp'],
		dependencies: [
			framework_native_dep,
			blinky_sim_platform_dep
		],
		native: true
	)

	# We want to build a demo app to test cross compilation on x86_64 with mainline clang
	if target_architecture == 'x86_64'
		blinky_simulator_app_x86 = executable('blinky_x86',
			sources: [
				'blinky.cpp',
			],
			dependencies: [
				framework_dep,
				blinky_sim_x86_platform_dep
			],
		)
	endif
```

**Comment by phillipjohnston** [comment]
Well, it did reveal a long-standing issue that just happened to work out in the past. I think this can be closed too.

**Comment by phillipjohnston** [comment]
Thanks for your great help @dcbaker. I appreciate it.
