### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by tsnoam** [mesonbuild/meson#563]
I encountered the following error with the master branch (rev. 1a0938cc) while trying to run a cross compilation build (with tag 0.31.0 there is no problem).

[crosscompile.bugreport.meson.txt](https://github.com/mesonbuild/meson/files/283468/crosscompile.bugreport.meson.txt)

```
The Meson build system
Version: 0.32.0.dev1
Source dir: SRC_DIR
Build dir: BUILD_DIR
Build type: cross build
Host machine cpu family: x86
Host machine cpu: x86_64
Target machine cpu family: mips
Target machine cpu: mips
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: PROJECT_NAME
Traceback (most recent call last):
  File "/home/nm/sources/meson/mesonbuild/mesonmain.py", line 260, in run
    app.generate()
  File "/home/nm/sources/meson/mesonbuild/mesonmain.py", line 156, in generate
    intr.run()
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1081, in run
    self.evaluate_codeblock(self.ast)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1103, in evaluate_codeblock
    raise e
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1097, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1215, in evaluate_statement
    return self.function_call(cur)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 2010, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 71, in wrapped
    return f(self, node, args, kwargs)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1417, in func_project
    self.add_languages(node, args[1:], True)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1527, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "/home/nm/sources/meson/mesonbuild/interpreter.py", line 1501, in detect_compilers
    cross_comp.sanity_check(self.environment.get_scratch_dir())
  File "/home/nm/sources/meson/mesonbuild/compilers.py", line 460, in sanity_check
    pe = subprocess.Popen(cmdlist)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by tsnoam** [comment]
By manually checking various revisions I found that the problem was introduced in rev. c0765b0e

**Comment by tsnoam** [comment]
Well... if I dare dive into some1 else's code (without understanding all the internal logic), I suspect that the problem lies within `mesonbuild/environment.py`, func `need_exe_wrapper()`.

I think that this function neglects to check if the target is defined, different than the host system and that their both are not x86 flavours.

**Comment by tsnoam** [comment]
closing for my own ignorance :-(
I confused between the meaning of host, build & target machines.
I fixed the properties file to contain only `host_machine` (attached here) and now it just works...
[crosscompile.bugreport.meson.txt](https://github.com/mesonbuild/meson/files/283483/crosscompile.bugreport.meson.txt)
