### ISSUE TITLE
DESTDIR dont work while install at Windows

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#567]
`binpac_lib = static_library('libbinpac', binpac_lib_srcs, cpp_args:  [cpp_args], install : install_arg , install_dir : 'lib')` are worked as expect at windows.

 But when i try configure with DESTDIR as absolute path install is failed.
`env DESTDIR=c:\x ninja install` 
(i use env from gnuwin32 package)

```
Installing lib\libbinpac.lib to c:\xc:/lib\libbinpac.lib
Traceback (most recent call last):
  File "F:\\devel\\meson\\meson.git\\meson.py", line 24, in <module>
    sys.exit(mesonmain.run(thisfile, sys.argv[1:]))
  File "F:\devel\meson\meson.git\mesonbuild\mesonmain.py", line 220, in run
    sys.exit(run_script_command(args[1:]))
  File "F:\devel\meson\meson.git\mesonbuild\mesonmain.py", line 210, in run_scri
pt_command
    return cmdfunc(cmdargs)
  File "F:\devel\meson\meson.git\mesonbuild\scripts\meson_install.py", line 207,
 in run
    do_install(datafilename)
  File "F:\devel\meson\meson.git\mesonbuild\scripts\meson_install.py", line 32,
in do_install
    install_targets(d)
  File "F:\devel\meson\meson.git\mesonbuild\scripts\meson_install.py", line 167,
 in install_targets
    os.makedirs(outdir, exist_ok=True)
  File "F:\lang\Python35-64\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "F:\lang\Python35-64\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или мет
ке тома: 'c:\\xc:'
FAILED: install
```

**Comment by LRN** [comment]
I'm using meson from MSYS, and it works if i do this:
```
meson --prefix=//mingw
DESTDIR=/foo/bar/baz ninja install
```
Note the two slashes for the prefix (leaving only one slash will make MSYS mangle the name, as meson is being interpreted by a Windows version of Python).
