### ISSUE TITLE
Trying to download dependencies from WrapDB.

### ISSUE THREAD

**Issue by squidfarts** [mesonbuild/meson#5672]
From Meson version 0.49.999 to Meson version 0.51.1 I get this error after trying to search, list, download and use anything from WrapDB.  Am I missing something?

```console
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/wrap/wraptool.py", line 216, in run
    options.wrap_func(options)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/wrap/wraptool.py", line 72, in list_projects
    projects = get_projectlist()
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/wrap/wraptool.py", line 67, in get_projectlist
    jd = get_result(API_ROOT + 'projects')
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/wrap/wraptool.py", line 57, in get_result
    u = open_wrapdburl(urlstring)
  File "/Users/shnitzel/Library/Python/3.7/lib/python/site-packages/meson-0.51.1-py3.7.egg/mesonbuild/wrap/wrap.py", line 71, in open_wrapdburl
    return urllib.request.urlopen(urlstring, timeout=req_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
Michaels-MacBook-Pro:ham-radio shnitzel$ 
```

**Comment by jpakkane** [comment]
Are you encountering [this issue](https://superuser.com/questions/1400928/certificate-issue-with-python3-on-osx).

**Comment by squidfarts** [comment]
Sorry I guess i'm also a part of the I overlooked important detail regarding OpenSSL certificate club. 🙂
