### ISSUE TITLE
ninja install build gtk-doc as root

### ISSUE THREAD

**Issue by grimmy** [mesonbuild/meson#5793]
While working on many of my meson projects, if I run `ninja -C build install` on a tree thats using a default prefix (`/usr/local`) I'll get prompted by policykit for the root password once the build is completed.  However, since `gtk-doc` targets aren't run until after the policykit prompt, and thus privilege escalation, they get built as root.  This then makes it impossible to `ninja -C build foo-doc` as a user because the files are owned by root.

I'm running meson 0.51.1 on debian unstable.  I can provide repos for reference or an asciinema as well, but making a small test case is kind of involved so I haven't done that yet.

**Comment by QuLogic** [comment]
You can reproduce with one of the test cases:
```
$ ./meson.py test cases/frameworks/10\ gtk-doc/ work\ area/
$ ninja -C work\ area/ install
$ ls -l work\ area/doc/*
```
and verify that all these files are owned by `root:root`, and then things fail if you try to build the docs yourself:
```
$ touch test\ cases/frameworks/10\ gtk-doc/doc/foobar1/foobar-docs.sgml 
 
$ ninja -C work\ area/ foobar-doc
ninja: Entering directory `work area/'
[1/1] Generating foobar-doc with a custom command.
FAILED: doc/foobar1/foobar-decl.txt 
/usr/bin/python3 /home/elliott/code/meson/meson.py --internal gtkdoc '--sourcedir=/home/elliott/code/meson/test cases/frameworks/10 gtk-doc' '--builddir=/home/elliott/code/meson/work area' --subdir=doc/foobar1 '--headerdirs=/home/elliott/code/meson/test cases/frameworks/10 gtk-doc/include@@/home/elliott/code/meson/work area/include' --mainfile=foobar-docs.sgml --modulename=foobar --moduleversion= --mode=auto --gtkdoc-scan=/usr/bin/gtkdoc-scan --gtkdoc-scangobj=/usr/bin/gtkdoc-scangobj --gtkdoc-mkdb=/usr/bin/gtkdoc-mkdb --gtkdoc-mkhtml=/usr/bin/gtkdoc-mkhtml --gtkdoc-fixxref=/usr/bin/gtkdoc-fixxref '--content-files=/home/elliott/code/meson/work area/include/bar.xml@@/home/elliott/code/meson/work area/doc/version.xml' '--cc=ccache cc' '--ld=ccache cc'
Building documentation for foobar
Traceback (most recent call last):
  File "/home/elliott/code/meson/meson.py", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/home/elliott/code/meson/mesonbuild/mesonmain.py", line 226, in main
    return run(sys.argv[1:], launcher)
  File "/home/elliott/code/meson/mesonbuild/mesonmain.py", line 215, in run
    return run_script_command(args[1], args[2:])
  File "/home/elliott/code/meson/mesonbuild/mesonmain.py", line 163, in run_script_command
    return module.run(script_args)
  File "/home/elliott/code/meson/mesonbuild/scripts/gtkdochelper.py", line 264, in run
    options)
  File "/home/elliott/code/meson/mesonbuild/scripts/gtkdochelper.py", line 116, in build_gtkdoc
    shutil.copyfile(f, os.path.join(abs_out, os.path.basename(f)))
  File "/usr/lib64/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/elliott/code/meson/work area/doc/foobar1/foobar-docs.sgml'
ninja: build stopped: subcommand failed.
```

**Comment by xclaesse** [comment]
This should be fixed by my WIP rewrite of gtkdoc:
https://github.com/mesonbuild/meson/pull/5735
