### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#5843]
A recent change in meson(?) seems to have started to cause evince to fail to build which I tried to work around in https://gitlab.gnome.org/GNOME/evince/merge_requests/185
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/builds/GNOME/evince/_build/help/reference/libdocument/html/libevdocument.devhelp2' -> '/builds/GNOME/evince/_build/help/reference/libdocument/html/libevdocument-3.0.devhelp2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.51.1', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 224, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 213, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 161, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/gtkdochelper.py", line 259, in run
    options.mode)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/gtkdochelper.py", line 205, in build_gtkdoc
    os.path.join(htmldir, '{}-{}.devhelp2'.format(module, module_version)))
  File "/usr/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/builds/GNOME/evince/_build/help/reference/libdocument/html/libevdocument.devhelp2'
```

Full log at:
https://gitlab.gnome.org/GNOME/evince/-/jobs/403965

I unfortunately could not replicate the problem locally on Fedora 30.

**Comment by Cogitri** [comment]
It appears this happens in numerous packages, e.g. libsecret and gucharmap too.

**Comment by hadess** [comment]
> It appears this happens in numerous packages, e.g. libsecret and gucharmap too.

Did you find a way to reproduce the problem? Because I couldn't, and I haven't hit the problem since.

**Comment by Cogitri** [comment]
It happens for me in 100% of cases when building libsecret or gucharmap with gtk-doc enabled with meson 0.53.2

**Comment by mtelka** [comment]
I'm facing this issue too when building `gucharmap` on OpenIndiana.
@Cogitri, did you manage to solve this issue?  Thank you.

**Comment by acid-bong** [comment]
> building `gucharmap`

samesies, i'm bumping Gucharmap version in Guix (https://codeberg.org/guix/guix/pulls/5783) and having the same problems

**Comment by mtelka** [comment]
This seems to be a bug in `gtk-doc`: https://gitlab.gnome.org/GNOME/gtk-doc/-/issues/162
