### ISSUE TITLE
Cannot use output of generator for custom_target?

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#587]
Hello,

I am not sure if I am doing something wrong.

I have something like this:

              gen = generator(make_resource_header,
              output: '@BASENAME@.h',
              arguments : ['@INPUT@', '@OUTPUT@'])

              gen_src = card_gen.process(
              'images/res1.jpg',
              'images/res2.jpg')

I want gen_src to be able to be fed into a custom_target so that I can cat all the results,
but it seems that I cannot get the results of the generated files in a custom_target.
Seems reasonable to me:

    all_headers_in_one = custom_target('all_headers',
        input : gen_src, <--------------------------------------------- This as input will fail
        output : all_resources.hpp',
        command : ['python3', cat_files, '@INPUT@',
                   '@OUTPUT@'])

After this I would like to include `all_headers_in_one` in my executable as a dependency (source file). 

The error is below:

```
 File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 265, in run
    app.generate()
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 160, in generate
    g.generate(intr)
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 179, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 179, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 224, in generate_target
    self.generate_custom_target(target, outfile)
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/backend/ninjabackend.py", line 344, in generate_custom_target
    (srcs, ofilenames, cmd) = self.eval_custom_target_command(target)
  File "/usr/local/lib/python3.5/site-packages/meson-0.33.0.dev1-py3.5.egg/mesonbuild/backend/backends.py", line 480, in eval_custom_target_command
    fname = i.rel_to_builddir(self.build_to_src)
AttributeError: 'GeneratedList' object has no attribute 'rel_to_builddir'
```

**Comment by jpakkane** [comment]
Can you test if MR #592 works for you? Thanks.

**Comment by germandiagogomez** [comment]
> Can you test if MR #592 works for you? Thanks.

I think that the weekend. Sorry, quite busy now. Maybe if I find time before I will, but no guarantees though.

**Comment by germandiagogomez** [comment]
Just refreshed in a linux box

This is the relevant simplified part of my meson.build file:

res_gen_src = res_gen.process(
'images/reverso_carta' + file_ext,
'images/sota_de_oros' + file_ext)


all_res = custom_target('cards_deck_res', input : res_gen_src,
                              output : 'cards_deck.res.hpp',
                              command : [cat_files, '@INPUT@', '>', '@OUTPUT@'])
                              

libguinyote = static_library('guinyote',
                [sources...],
                 all_res,
                ...)
```

And the error:

```
Traceback (most recent call last):
  File "/home/german/git/git-internet-modules/meson/mesonbuild/mesonmain.py", line 265, in run
    app.generate()
  File "/home/german/git/git-internet-modules/meson/mesonbuild/mesonmain.py", line 160, in generate
    g.generate(intr)
  File "/home/german/git/git-internet-modules/meson/mesonbuild/backend/ninjabackend.py", line 179, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/german/git/git-internet-modules/meson/mesonbuild/backend/ninjabackend.py", line 179, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/german/git/git-internet-modules/meson/mesonbuild/backend/ninjabackend.py", line 224, in generate_target
    self.generate_custom_target(target, outfile)
  File "/home/german/git/git-internet-modules/meson/mesonbuild/backend/ninjabackend.py", line 344, in generate_custom_target
    (srcs, ofilenames, cmd) = self.eval_custom_target_command(target)
  File "/home/german/git/git-internet-modules/meson/mesonbuild/backend/backends.py", line 480, in eval_custom_target_command
    fname = i.rel_to_builddir(self.build_to_src)
AttributeError: 'GeneratedList' object has no attribute 'rel_to_builddir'
```
