### ISSUE TITLE
Emscripten: AttributeError: 'NoneType' object has no attribute 'get_allow_undefined_args'

### ISSUE THREAD

**Issue by Akaricchi** [mesonbuild/meson#5900]
Looks like there is no linker detected for emcc, which could be the issue.

```
$ meson --wipe ~/git/taisei
The Meson build system
Version: 0.51.999
Source dir: /data/git/taisei
Build dir: /data/webshit/ports/taisei
Build type: cross build
Project name: taisei
Project version: v1.4-dev
C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
C linker for the build machine: lld 8.0.1
C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: wasm32
Host machine cpu: wasm32
Target machine cpu family: wasm32
Target machine cpu: wasm32
DEPRECATION: Project targetting '>=0.45.0' but tried to use feature deprecated since '0.48.0': python3 module
Program thunk.py found: YES (/data/git/taisei/scripts/thunk.py)
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wpedantic: YES 
Compiler for C supports arguments -Werror=assume: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Wabsolute-value: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wcast-align=strict: NO 
Compiler for C supports arguments -Wcast-function-type: NO 
Compiler for C supports arguments -Wclobbered: NO 
Compiler for C supports arguments -Wduplicated-branches: NO 
Compiler for C supports arguments -Wduplicated-cond: NO 
Compiler for C supports arguments -Wfloat-overflow-conversion: YES 
Compiler for C supports arguments -Wfloat-zero-conversion: YES 
Compiler for C supports arguments -Wfor-loop-analysis: YES 
Compiler for C supports arguments -Wformat-pedantic: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wgcc-compat: YES 
Compiler for C supports arguments -Wgnu: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wlogical-op: NO 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wno-long-long: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-typedef-redefinition: YES 
Compiler for C supports arguments -Wnull-dereference: YES 
Compiler for C supports arguments -Wparentheses: YES 
Compiler for C supports arguments -Wshadow=compatible-local: NO 
Compiler for C supports arguments -Wsometimes-uninitialized: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wunneeded-internal-declaration: YES 
Compiler for C supports arguments -Wunreachable-code: YES 
Compiler for C supports arguments -Wunreachable-code-loop-increment: YES 
Compiler for C supports arguments -fexcess-precision=standard: YES 
Compiler for C supports arguments -fmerge-all-constants: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-signaling-nans: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -msse -mfpmath=sse: NO 
Looking for a fallback subproject for the dependency freetype2 because:
Use of fallback dependencies is forced.

|Executing subproject freetype method meson 
|
|Project name: freetype2
|Project version: 2.10.1
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|Compiler for C supports arguments -Wcast-function-type: NO (cached)
|Header <unistd.h> has symbol "_POSIX_VERSION" : YES 
|Has header "unistd.h" : YES 
|Has header "fcntl.h" : YES 
|Has header "stdint.h" : YES 
|Looking for a fallback subproject for the dependency zlib because:
|Use of fallback dependencies is forced.
|
||Executing subproject zlib method meson 
||
||Project name: zlib
||Project version: 1.2.11
||C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
||C linker for the build machine: lld 8.0.1
||C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
||Compiler for C supports arguments -Wno-implicit-fallthrough: YES 
||Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
||Build targets in project: 2
||Subproject zlib finished.
|
|Dependency zlib from subproject subprojects/zlib found: YES
|Configuring ftconfig.h using configuration
|Configuring ftoption.h using configuration
|Build targets in project: 3
|Subproject freetype finished.

Dependency freetype2 from subproject subprojects/freetype found: YES
Looking for a fallback subproject for the dependency opusfile because:
Use of fallback dependencies is forced.

|Executing subproject opusfile method meson 
|
|Project name: opusfile
|Project version: 0.11
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|
|subprojects/opusfile/meson.build:3:0: Exception: 'NoneType' object has no attribute 'get_allow_undefined_args'

Subproject opusfile is buildable: NO (disabling)
Dependency opusfile from subproject subprojects/opusfile found: NO
Looking for a fallback subproject for the dependency libpng because:
Use of fallback dependencies is forced.

|Executing subproject libpng method meson 
|
|Project name: libpng
|Project version: 1.6.37
|C compiler for the build machine: ccache /usr/bin/clang (clang 8.0.1 "clang version 8.0.1 (tags/RELEASE_801/final 366581)")
|C linker for the build machine: lld 8.0.1
|C compiler for the host machine: ccache /data/webshit/emroot/emcc (emscripten 1.38.43 "emcc (Emscripten gcc/clang-like replacement) 1.38.43 (commit efc64876db1473312587a3f346be000a733bc16d)")
|Dependency zlib from subproject subprojects/zlib found: YES
Traceback (most recent call last):
  File "/data/git/meson/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/data/git/meson/mesonbuild/msetup.py", line 244, in run
    app.generate()
  File "/data/git/meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/data/git/meson/mesonbuild/msetup.py", line 191, in _generate
    intr.run()
  File "/data/git/meson/mesonbuild/interpreter.py", line 3992, in run
    super().run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1053, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 778, in function_call
    return func(node, posargs, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3082, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3142, in dependency_impl
    return self.dependency_fallback(display_name, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 3193, in dependency_fallback
    self.do_subproject(dirname, 'meson', sp_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 2524, in do_subproject
    raise e
  File "/data/git/meson/mesonbuild/interpreter.py", line 2508, in do_subproject
    return self._do_subproject_meson(dirname, subdir, default_options, required, kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 2535, in _do_subproject_meson
    subi.run()
  File "/data/git/meson/mesonbuild/interpreter.py", line 3992, in run
    super().run()
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1053, in assignment
    value = self.evaluate_statement(node.value)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 457, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 490, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1020, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 1020, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
    return self.method_call(cur)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 815, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 325, in method_call
    return method(args, kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/data/git/meson/mesonbuild/interpreter.py", line 1564, in find_library_method
    linkargs = self.compiler.find_library(libname, self.environment, search_dirs, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 997, in find_library
    return self.find_library_impl(libname, env, extra_dirs, code, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 987, in find_library_impl
    value = self.find_library_real(libname, env, extra_dirs, code, libtype)
  File "/data/git/meson/mesonbuild/compilers/mixins/clike.py", line 946, in find_library_real
    largs = self.get_allow_undefined_link_args()
  File "/data/git/meson/mesonbuild/compilers/compilers.py", line 1044, in get_allow_undefined_link_args
    return self.linker.get_allow_undefined_args()
AttributeError: 'NoneType' object has no attribute 'get_allow_undefined_args'
```

**Comment by dcbaker** [comment]
0.54 changes emcc to use wasm-ld instead of pretending it doesn't have a linker. Is this still present with current master?

**Comment by Akaricchi** [comment]
This issue actually got fixed in #6040. And it still seems to work. However, there are new warnings, presumably related to the 0.54 change:

```
shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning
shared:WARNING: ignoring unsupported linker flag: `-rpath`
shared:WARNING: ignoring unsupported linker flag: `$ORIGIN/../subprojects/cglm:$ORIGIN/../subprojects/freetype:$ORIGIN/../subprojects/zlib:$ORIGIN/../subprojects/koishi/src:$ORIGIN/../subprojects/libpng:$ORIGIN/../subprojects/sdl2:$ORIGIN/../subprojects/libwebp/src:$ORIGIN/../subprojects/sdl2_mixer:$ORIGIN/../subprojects/opusfile/src:$ORIGIN/../subprojects/ogg/src:$ORIGIN/../subprojects/opus/src:$ORIGIN/../subprojects/opus/silk:$ORIGIN/../subprojects/opus/celt`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/cglm`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/freetype`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/zlib`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/koishi/src`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/libpng`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/sdl2`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/libwebp/src`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/sdl2_mixer`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/opusfile/src`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/ogg/src`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/opus/src`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/opus/silk`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/data/webshit/ports/taisei/subprojects/opus/celt`
```

We shouldn't pass rpath-related stuff to emscripten.

**Comment by bonzini** [comment]
Please try to reproduce and open a new issue; since the exception was fixed, I'm closing this one.
