### ISSUE TITLE
cross compilation does not work with D

### ISSUE THREAD

**Issue by qwertzui11** [mesonbuild/meson#5931]
### system
- OS: ubuntu 18.04
- meson: v0.51.2

### compiler: gdc 8
```bash
apt install gdc-8-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf
```
### toolchainfile
```
[binaries]
d = '/usr/bin/arm-linux-gnueabihf-gdc-8'
ar = '/usr/bin/arm-linux-gnueabihf-ar'
strip = '/usr/bin/arm-linux-gnueabihf-strip'
pkgconfig = '/usr/bin/arm-linux-gnueabihf-pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7hf'
endian = 'little'
```
### meson.build
```
project('cross_d', 'd', meson_version : '>=0.51.0')
executable('cross',  'cross.d')
```
### create build
```bash
meson builddir . --cross-file=toolchain
```
### the output
```
The Meson build system
Version: 0.51.2
Source dir: /home/user/Development/projects/meson_fun/cross
Build dir: /home/user/Development/projects/meson_fun/cross/builddir
Build type: cross build
Project name: cross_d
Project version: undefined
D compiler for the build machine: dmd (dmd 2.088.0 "DMD64 D Compiler v2.088.0")
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 241, in run
    app.generate()
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 175, in _generate
    intr = interpreter.Interpreter(b)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2074, in __init__
    self.parse_project()
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 778, in function_call
    return func(node, posargs, kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2722, in func_project
    self.add_languages(proj_langs, True)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2782, in add_languages
    success &= self.add_languages_for(args, required, MachineChoice.HOST)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2800, in add_languages_for
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "/home/user/.local/lib/python3.6/site-packages/mesonbuild/compilers/d.py", line 91, in sanity_check
    if subprocess.call(output_name) != 0:
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/user/Development/projects/meson_fun/cross/builddir/meson-private/dtest'
```
the file `/home/user/Development/projects/meson_fun/cross/builddir/meson-private/dtest` that throws the error `Exec format error` is of type `arm` and can't be executed. Which makes sense.
```
file /home/user/Development/projects/meson_fun/cross/builddir/meson-private/dtest
/home/user/Development/projects/meson_fun/cross/builddir/meson-private/dtest: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.2.0, BuildID[sha1]=d2
728fa7fc4883524d285ec9d30388d54acf3996, not stripped
```
### what i tried so far
- if I change the d-compiler in the `toolchain` file to `/usr/bin/gdc-8` everything works fine. But, of course it doesn't cross compile to arm.
- I tried the same with `C++` and it worked without a problem.

Any information about what I could be doing wrong, would be greatly appreciated. However I believe it's a bug.

**Comment by qwertzui11** [comment]
I found the pull request which addresses the issue https://github.com/mesonbuild/meson/pull/5804
It seems to be stuck for a month

**Comment by denizzzka** [comment]
This issue is fixed?

**Comment by dcbaker** [comment]
I think it should be, but I don't have a D cross compiler to check with and don't really want to build one.

**Comment by denizzzka** [comment]
This issue is gdc-specific? Otherwise, I found easiest way to get D cross compiler for me - ldc2 snap package.

**Comment by dcbaker** [comment]
Well, I rebuilt ldc (gentoo user) with i686 support, and I've tested gdc with i686 support (which I already had, I was just not thinking), and was able to correctly compile both of those. Of course, I can run i686 natively on my machine. I'm building a true cross toolchain with D support to see if that works.

**Comment by dcbaker** [comment]
I built an aarch64 cross toolchain with gdc and this works fine, so I'm closing it.
