### ISSUE TITLE
LZMA dependency introduced in the latest release

### ISSUE THREAD

**Issue by rzumer** [mesonbuild/meson#6012]
I run the latest release of `meson` at all times (installed via `pip3`), and starting this week I can no longer run `meson` without hitting the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 11, in <module>
    load_entry_point('meson==0.52.0', 'console_scripts', 'meson')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 25, in <module>
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mdist.py", line 16, in <module>
    import lzma
  File "/usr/local/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

I see that the `lzma` import has been there for a while, but as of last week I could still run `meson` without a problem.

Please consider removing the dependency for default usage if possible, or at least documenting it in the README and any other relevant documents.

**Comment by jpakkane** [comment]
[According to Python documentation](https://docs.python.org/3/library/lzma.html), LZMA has been available since 3.3 and in `shutil` [at least since 3.5](https://docs.python.org/3/library/shutil.html). If it is missing from your Python install it seems to be more of a case that your Python distribution provider has chosen to not build or install it.

Meson requires that the Python standard library is installed in its entirety.

**Comment by scivision** [comment]
I have seen this same error before with Pandas due to improperly configured system Python on HPC system.

Is this a system where you could install Miniconda Python (70 MBytes) or other non-system Python that has the stdlib available?

**Comment by scivision** [comment]
I believe the place to note that the full Python 3 install is required (not just python3-minimal or other stripped-down Python) would be at:

https://mesonbuild.com/Quick-guide.html
