### ISSUE TITLE
Meson wrap tool still down?

### ISSUE THREAD

**Issue by sandervalstar** [mesonbuild/meson#6039]
Hi,
Two days ago there were issues with the SSL certificate of the meson wrap tool. This was supposedly fixed: https://github.com/mesonbuild/meson/issues/6034

However, today I got the following error (different error than two days ago, but seemingly related). And my build still cannot download subproject patches from the meson wrapdb (for gtest in my case).
My meson version is 0.51.2

```
meson wrap list
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 216, in run
    options.wrap_func(options)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 72, in list_projects
    projects = get_projectlist()
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 67, in get_projectlist
    jd = get_result(API_ROOT + 'projects')
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/wrap/wraptool.py", line 57, in get_result
    u = open_wrapdburl(urlstring)
  File "/usr/local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 71, in open_wrapdburl
    return urllib.request.urlopen(urlstring, timeout=req_timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by jpakkane** [comment]
That seems more like a transient connectivity error. You can test by opening [WrapDB](https://wrapdb.mesonbuild.com) with a browser on the same machine.

**Comment by sandervalstar** [comment]
Thank you. Meson wrap list suddenly works again. No idea why it gave this error for me yesterday...
