### ISSUE TITLE
FAILED: subprojects/glib/gio/tests/test.gresource

### ISSUE THREAD

**Issue by mczarnek** [mesonbuild/meson#6134]
Hello, I'm trying to build gstreamer using meson in Windows. It seems like ninja is having an issue compiling gio within glib and is blaming it on meson.  Given the glib version is specifically specified within the build script, seems like this is a meson or ninja issue, not gstreamer.  I've tried updating to the latest version of glib, still getting this error every time I try to compile.

I've tried looking at the .dat file and tests and I'm not seeing anything useful.

Help? Thanks!

[1248/6193] Generating test.gresource with a meson_exe.py custom command.
FAILED: subprojects/glib/gio/tests/test.gresource
"C:/Users/Edge360/AppData/Local/Programs/Python/Python38-32/Scripts/meson" "--internal" "exe" "--unpickle" "C:/gstreamer/gst-build/build/meson-private/meson_exe_glib-compile-resources_50a4cc01736d47442e1f6abe4f7838e9bb4edf72.dat"
[1257/6193] Linking target subprojects/glib/gio/tests/gdbus-example-server.exe.
ninja: build stopped: subcommand failed.

**Comment by mczarnek** [comment]
Seems related to this one given just before it fails it has an error about "library machine type 'x64' conflicts with target machine type 'x86'"?
https://github.com/mesonbuild/meson/issues/5189

[1145/6193] Linking target subprojects/glib/gio/gio-2.0-0.dll.
   Creating library subprojects\\glib\\gio\\gio-2.0.lib and object subprojects\\glib\\gio\\gio-2.0.exp
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflate referenced in function _g_zlib_compressor_convert
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflateEnd referenced in function _g_zlib_compressor_finalize
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflateReset referenced in function _g_zlib_compressor_reset
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflateSetHeader referenced in function _g_zlib_compressor_set_gzheader
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflateInit_ referenced in function _g_zlib_compressor_constructed
gzlibcompressor.c.obj : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function _g_zlib_compressor_constructed
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflate referenced in function _g_zlib_decompressor_convert
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflateEnd referenced in function _g_zlib_decompressor_finalize
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflateReset referenced in function _g_zlib_decompressor_reset
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflateGetHeader referenced in function _g_zlib_decompressor_set_gzheader
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflateInit_ referenced in function _g_zlib_decompressor_constructed
gzlibdecompressor.c.obj : error LNK2019: unresolved external symbol _inflateInit2_ referenced in function _g_zlib_decompressor_constructed
C:\gstreamer\1.0\x86_64\lib\z.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
subprojects\glib\gio\gio-2.0-0.dll : warning LNK4088: image being generated due to /FORCE option; image may not run
[1148/6193] Linking target subprojects/gstreamer/libs/gst/check/gstcheck-1.0-0.dll.
   Creating library subprojects\\gstreamer\\libs\\gst\\check\\gstcheck-1.0.lib and object subprojects\\gstreamer\\libs\\gst\\check\\gstcheck-1.0.exp
[1248/6193] Generating test.gresource with a meson_exe.py custom command.
FAILED: subprojects/glib/gio/tests/test.gresource
"C:/Users/Edge360/AppData/Local/Programs/Python/Python38-32/Scripts/meson" "--internal" "exe" "--unpickle" "C:/gstreamer/gst-build/build/meson-private/meson_exe_glib-compile-resources_50a4cc01736d47442e1f6abe4f7838e9bb4edf72.dat"
[1257/6193] Linking target subprojects/glib/gio/tests/gdbus-example-server.exe.
ninja: build stopped: subcommand failed.

**Comment by mczarnek** [comment]
Thanks scivision

I type 'python' into cmd and recieve:
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32

Using python -c "import sys; print(sys.maxsize > 2**32)", I get an output of True

I'm using Visual Studio 2019 and running this within the Developer Command Prompt for 2019. Think I've tried in 2017 too and got same issue.

So, I forced gstreamer's meson.build file to choose "wine64". Same issue, didn't fix gstreamer ninja compile error :(

**Comment by mczarnek** [comment]
using either this:
 project('All GStreamer modules', 'c',
   version : '1.17.0.1',
   meson_version : '>= 0.48.0',
   default_options : ['buildtype=debugoptimized'])
or:
  project('foo','c')

meson build
The Meson build system
Version: 0.52.0
Source dir: C:\mesontest
Build dir: C:\mesontest\build
Build type: native build
Project name: All GStreamer modules
Project version: 1.17.0.1
C compiler for the host machine: cl (msvc 19.23.28106.4)
C linker for the host machine: link 19.23.28106.4
Host machine cpu family: x86
Host machine cpu: x86
Build targets in project: 0
Found ninja.EXE-1.8.2 at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"

**Comment by scivision** [comment]
OK using VS2019 v16.3.8 x64 command prompt for meson.build `project('foo', 'c')` I get:

```
The Meson build system
Version: 0.52.999
Source dir: c:\temp
Build dir: c:\temp\19
Build type: native build
Project name: foo
Project version: undefined
C compiler for the host machine: cl (msvc 19.23.28106.4)
C linker for the host machine: link 19.23.28106.4
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0
Found ninja.EXE-1.9.0 at C:\msys64\mingw64\bin\ninja.EXE
```

and 

```
The Meson build system
Version: 0.52.0
Source dir: c:\temp
Build dir: c:\temp\191
Build type: native build
Project name: foo
Project version: undefined
C compiler for the host machine: cl (msvc 19.23.28106.4)
C linker for the host machine: link 19.23.28106.4
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0
Found ninja.EXE-1.9.0 at C:\msys64\mingw64\bin\ninja.EXE
```

**Comment by mczarnek** [comment]
Can try forcing it to use mingw64 version of ninja to see if that helps but install only that one

Host machine cpu family showing wrong version definitely seems like a problem.

Can I try changing an environmental variable to get meson to realize I'm on x64?

Which variable and to what?

**Comment by scivision** [comment]
Here's what I think we have in command (my and your PC)

* Visual Studio 2019, latest version
* Python 64-bit
* Meson 0.52.0 (or git master)

What's different

* I'm using Ninja 1.9.0, you're using Ninja 1.8.2 ("should" be unrelated to issue)
* I am using Windows 10 1903 (what are you using)

**Comment by scivision** [comment]
@mczarnek that's exactly the issue--I'm not sure, from what you've written I don't immediately see the issue. The way I would approach this is using the trivial meson.build and VS2019 x64 command prompt, insert `breakpoint()` into the appropriate functions in `mesonbuild/environment.py` and step through using PDB to see which exact line picks `x86`.

(breakpoint() is a Python 3.7+ feature)

**Comment by mczarnek** [comment]
I have tried with 1.9.0 too, I decided to try the cygwin version and uninstalled all other versions. But I was previously getting the same error using 1.9.0.  Let me try newest mingw64 version.

I'm using Windows 10 1809 (OS Build 17763.805)

**Comment by scivision** [comment]
I think Ninja is unlikely to be the issue, it's more likely just a glitch in environment.py. Thankfully this is a bit easier to deal with in Python.

**Comment by mczarnek** [comment]
Do you know where this environment.py script is typically located?

**Comment by scivision** [comment]
mesonbuild/environment.py

**Comment by mczarnek** [comment]
I see, I needed to use the python version of meson instead of the .exe I was running

Looks like it does look for  os.environ.get('PROCESSOR_ARCHITEW6432', '').lower()

Which is not set, can you tell me what it is set to for you?

**Comment by mczarnek** [comment]
```
-> if mesonlib.is_windows():
(Pdb) step
--Call--
> c:\tools\meson\mesonbuild\mesonlib.py(451)is_windows()
-> def is_windows() -> bool:
(Pdb) step
> c:\tools\meson\mesonbuild\mesonlib.py(452)is_windows()
-> platname = platform.system().lower()
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(884)system()
-> def system():
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(891)system()
-> return uname().system
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(746)uname()
-> def uname():
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(759)uname()
-> no_os_uname = 0
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(761)uname()
-> if _uname_cache is not None:
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(762)uname()
-> return _uname_cache
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(762)uname()->uname_result(...GenuineIntel')
-> return _uname_cache
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(891)system()->'Windows'
-> return uname().system
(Pdb) step
> c:\tools\meson\mesonbuild\mesonlib.py(453)is_windows()
-> return platname == 'windows' or 'mingw' in platname
(Pdb) step
--Return--
> c:\tools\meson\mesonbuild\mesonlib.py(453)is_windows()->True
-> return platname == 'windows' or 'mingw' in platname
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(320)detect_cpu_family()
-> trial = detect_windows_arch(compilers)
(Pdb) step
--Call--
> c:\tools\meson\mesonbuild\environment.py(261)detect_windows_arch()
-> def detect_windows_arch(compilers: CompilersDict) -> str:
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(285)detect_windows_arch()
-> os_arch = detect_native_windows_arch()
(Pdb) step
--Call--
> c:\tools\meson\mesonbuild\environment.py(245)detect_native_windows_arch()
-> def detect_native_windows_arch():
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(252)detect_native_windows_arch()
-> arch = os.environ.get('PROCESSOR_ARCHITEW6432', '').lower()
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\_collections_abc.py(657)get()
-> def get(self, key, default=None):
(Pdb) runeval(arch)
*** NameError: name 'runeval' is not defined
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\_collections_abc.py(659)get()
-> try:
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\_collections_abc.py(660)get()
-> return self[key]
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(668)__getitem__()
-> def __getitem__(self, key):
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(669)__getitem__()
-> try:
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(670)__getitem__()
-> value = self._data[self.encodekey(key)]
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(738)encodekey()
-> def encodekey(key):
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(739)encodekey()
-> return encode(key).upper()
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(732)check_str()
-> def check_str(value):
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(733)check_str()
-> if not isinstance(value, str):
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(735)check_str()
-> return value
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(735)check_str()->'PROCESSOR_ARCHITEW6432'
-> return value
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(739)encodekey()->'PROCESSOR_ARCHITEW6432'
-> return encode(key).upper()
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(674)__getitem__()
-> return self.decodevalue(value)
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\os.py(674)__getitem__()->'AMD64'
-> return self.decodevalue(value)
(Pdb) runeval(value)
*** NameError: name 'runeval' is not defined
(Pdb) runeval(value)
*** NameError: name 'runeval' is not defined
(Pdb) runeval(arch)
*** NameError: name 'runeval' is not defined
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\_collections_abc.py(660)get()->'AMD64'
-> return self[key]
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(253)detect_native_windows_arch()
-> if not arch:
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(259)detect_native_windows_arch()
-> return arch
(Pdb) step
--Return--
> c:\tools\meson\mesonbuild\environment.py(259)detect_native_windows_arch()->'amd64'
-> return arch
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(286)detect_windows_arch()
-> if os_arch == 'x86':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(292)detect_windows_arch()
-> for compiler in compilers.values():
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(293)detect_windows_arch()
-> if compiler.id == 'msvc' and (compiler.target == 'x86' or compiler.target == '80x86'):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(294)detect_windows_arch()
-> return 'x86'
(Pdb) step
--Return--
> c:\tools\meson\mesonbuild\environment.py(294)detect_windows_arch()->'x86'
-> return 'x86'
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(325)detect_cpu_family()
-> if trial.startswith('i') and trial.endswith('86'):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(327)detect_cpu_family()
-> elif trial == 'bepc':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(329)detect_cpu_family()
-> elif trial.startswith('arm') or trial.startswith('earm'):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(331)detect_cpu_family()
-> elif trial.startswith(('powerpc64', 'ppc64')):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(333)detect_cpu_family()
-> elif trial.startswith(('powerpc', 'ppc')):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(335)detect_cpu_family()
-> elif trial == 'macppc':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(337)detect_cpu_family()
-> elif trial in ('amd64', 'x64', 'i86pc'):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(339)detect_cpu_family()
-> elif trial in {'sun4u', 'sun4v'}:
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(345)detect_cpu_family()
-> if trial == 'x86_64':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(348)detect_cpu_family()
-> elif trial == 'aarch64':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(353)detect_cpu_family()
-> elif trial == 'parisc64':
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(358)detect_cpu_family()
-> if trial not in known_cpu_families:
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(363)detect_cpu_family()
-> return trial
(Pdb) step
--Return--
> c:\tools\meson\mesonbuild\environment.py(363)detect_cpu_family()->'x86'
-> return trial
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(413)detect_machine_info()
-> detect_cpu(compilers) if compilers is not None else None,
(Pdb) step
--Call--
> c:\tools\meson\mesonbuild\environment.py(365)detect_cpu()
-> def detect_cpu(compilers: CompilersDict):
(Pdb) step
> c:\tools\meson\mesonbuild\environment.py(366)detect_cpu()
-> if mesonlib.is_windows():
(Pdb) step
--Call--
> c:\tools\meson\mesonbuild\mesonlib.py(451)is_windows()
-> def is_windows() -> bool:
(Pdb) step
> c:\tools\meson\mesonbuild\mesonlib.py(452)is_windows()
-> platname = platform.system().lower()
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(884)system()
-> def system():
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(891)system()
-> return uname().system
(Pdb) step
--Call--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(746)uname()
-> def uname():
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(759)uname()
-> no_os_uname = 0
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(761)uname()
-> if _uname_cache is not None:
(Pdb) step
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(762)uname()
-> return _uname_cache
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(762)uname()->uname_result(...GenuineIntel')
-> return _uname_cache
(Pdb) step
--Return--
> c:\users\edge360\appdata\local\programs\python\python38-32\lib\platform.py(891)system()->'Windows'
-> return uname().system
(Pdb)

```

**Comment by scivision** [comment]
PROCESSOR_ARCHITEW6432 is *not* set in my VS2019 x64 command prompt (where Meson works correctly)

**Comment by mczarnek** [comment]
So it appears that environment.py get an architecture of 'amd64', which is does not recognize as x64

**Comment by scivision** [comment]
This comment https://github.com/mesonbuild/meson/issues/6128#issuecomment-550463558
notes that it's the VS target that's `x86` 
I am not sure if this is VS sending "bad" information or if Meson should realize not to do that?
I think a more experienced Meson dev with VS than me would have a better idea?

**Comment by scivision** [comment]
In 6128 I asked nirbheek for insight.

**Comment by mczarnek** [comment]
This is interesting, it lands on line 294 in environment.py where it determines that this is x86:
if compiler.id == 'msvc' and (compiler.target == 'x86' or compiler.target == '80x86'):
            return 'x86'

Trying to figure out if MSCV developer command prompt does indeed have the target set to x86

**Comment by scivision** [comment]
In 6128 sz-CHEN noted that their VS2017 command prompt included:

```
[vcvarsall.bat] Environment initialized for: 'x64'
```

but maybe there's something in the VS project that's saying build for x86 anyway?

**Comment by mczarnek** [comment]
I used cd to get to 'VC\Auxiliary\Build'

I wasn't able to check the environment, but yes, I ran "vcvarsall.bat amd64" and it returned:
[vcvarsall.bat] Environment initialized for: 'x64'

And now it is detecting the correct version for windows.. will try to set it more permanently but at least that does it. Of course this is leading to new errors for ninja and not even getting as far as I was before in compilation...  but at least it's not this one. lol

Thank you again scivision.

**Comment by scivision** [comment]
Is this https://github.com/mesonbuild/meson/issues/6128#issuecomment-550491362 the same issue?

**Comment by mczarnek** [comment]
Checking.. do you happen to know how I can pull that commit? Seeing 'Tree a107eab294' as the branch.. not sure how to switch Trees?

**Comment by mczarnek** [comment]
Downloaded and tried that whole branch using the zip file version.

No, still detects that I'm using x86 unless I specifically switch for command line using something like:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

And throws an error at the very end of the script:
Traceback (most recent call last):
  File "C:\Tools\mesonNewTree\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "C:\Tools\mesonNewTree\mesonbuild\msetup.py", line 244, in run
    app.generate()
  File "C:\Tools\mesonNewTree\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "C:\Tools\mesonNewTree\mesonbuild\msetup.py", line 214, in _generate
    intr.backend.generate(intr)
  File "C:\Tools\mesonNewTree\mesonbuild\backend\ninjabackend.py", line 301, in generate
    with self.detect_vs_dep_prefix(tempfilename) as outfile:
  File "C:\Tools\mesonNewTree\mesonbuild\backend\ninjabackend.py", line 251, in detect_vs_dep_prefix
    pc = subprocess.Popen([compiler.get_exelist(),
  File "C:\Users\Edge360\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Edge360\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Edge360\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Edge360\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 816, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by scivision** [comment]
is your computer set to English language locale? That seemed to be an issue for #6128

**Comment by scivision** [comment]
If it's non-English locale, this worked over for lb90 in 6128:

```
set VSLANG=1033
```
then wipe the Meson build directory and try again

**Comment by mczarnek** [comment]
No, that didn't do it. But actually I've fixed that more permanently.

For future people having this issue, go into the Properties for "Developer Command Prompt for VS 2019":
![image](https://user-images.githubusercontent.com/23365232/68342607-fbff0c80-00b8-11ea-8ed9-a5e28e0bb8b7.png)

And in the properties window change Target from:
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\VsDevCmd.bat"

To:
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"

Now it'll run Visual Studio's Developer Command Prompt in 64 bit mode.  In theory it'll fix this whole issue.. of course my build is now crashing before it ever gets there but at least it fixes the x64 thing.

Will open other tickets for a couple other issues I'm having.

**Comment by scivision** [comment]
Maybe `glib` upstream should have this in their docs?

**Comment by mczarnek** [comment]
Great idea, submitted a pull for glib.
