### ISSUE TITLE
meson wrongly tries to parse % sign in command line options

### ISSUE THREAD

**Issue by ptsneves** [mesonbuild/meson#6157]
Hello all,
I recently a weird situation started to happen where my command line option causes meson to fail.
Specifically when I have an invocation of the type meson -Dmyoption='something with %' I get the following stack trace:

```
Traceback (most recent call last):
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 112, in run
|     return options.run_func(options)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 232, in run
|     app.generate()
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 163, in generate
|     self._generate(env)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 217, in _generate
|     coredata.write_cmd_line_file(self.build_dir, self.options)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/mesonbuild/coredata.py", line 548, in write_cmd_line_file
|     config['options'] = options.cmd_line_options
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/configparser.py", line 971, in __setitem__
|     self.read_dict({key: value})
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/configparser.py", line 753, in read_dict
|     self.set(section, key, value)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/configparser.py", line 1198, in set
|     super().set(section, option, value)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/configparser.py", line 893, in set
|     value)
|   File "/opt/builds/tmp/work/armv5e-poky-linux-gnueabi/drotagx/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/configparser.py", line 402, in before_set
|     "position %d" % (value, tmp_value.find('%')))
| ValueError: invalid interpolation syntax in 'socat tcp:192.168.3.123:5760 PTY,link=%s,cfmakeraw,ispeed=b115200,ospeed=b115200' at position 38
```

**Comment by ptsneves** [comment]
Just a hint, I was able to fix this by setting in coredata.py. I can submit a patch if this is an acceptable solution.

```
- super().__init__(delimiters=['='])
+ super().__init__(delimiters=['='], interpolation=None)
```

**Comment by scivision** [comment]
I don't see anything in the `meson setup` docs that specify a need to interpolate the command line. In this type of use case, an alternative would be to use Meson `run_command()`.

I am not immediately thinking of any cases where Meson would need to interpolate this input. It would seem to make `meson setup` more robust even without this specific application.

I would thus be for this patch.
