### ISSUE TITLE
Fails with FileNotFoundError on compiler executable

### ISSUE THREAD

**Issue by hypothermic** [mesonbuild/meson#6158]
Cross-compiling GLib 2.62.2 on Ubuntu 18.04 fails with the following error:

```meson
me@workstation:~/AndroidStudioProjects/ValaAndroid/app/src/main/cpp/glib/build$ /usr/local/bin/meson android-arm-build --cross-file android.txt 
The Meson build system
Version: 0.52.0
Source dir: /home/me/AndroidStudioProjects/ValaAndroid/app/src/main/cpp/glib/build
Build dir: /home/me/AndroidStudioProjects/ValaAndroid/app/src/main/cpp/glib/build/android-arm-build
Build type: cross build
Project name: glib
Project version: 2.62.2
C compiler for the build machine: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C linker for the build machine: GNU ld.bfd 2.30
C++ compiler for the build machine: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C++ linker for the build machine: GNU ld.bfd 2.30
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2106, in __init__
    self.parse_project()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 778, in function_call
    return func(node, posargs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2753, in func_project
    self.add_languages(proj_langs, True)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2814, in add_languages
    success &= self.add_languages_for(args, required, MachineChoice.HOST)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/interpreter.py", line 2832, in add_languages_for
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/compilers/c.py", line 60, in sanity_check
    return self.sanity_check_impl(work_dir, environment, 'sanitycheckc.c', code)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/compilers/mixins/clike.py", line 234, in sanity_check_impl
    pc, stdo, stde = mesonlib.Popen_safe(cmdlist, cwd=work_dir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonlib.py", line 1063, in Popen_safe
    stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './toolchain/bin/arm-linux-androideabi-gcc': './toolchain/bin/arm-linux-androideabi-gcc'
```
Here's `android.txt`:
```
[binaries]
c = './toolchain/bin/arm-linux-androideabi-gcc'
cpp = './toolchain/bin/arm-linux-androideabi-g++'
ar = './toolchain/bin/arm-linux-androideabi-ar'
ld = './toolchain/bin/arm-linux-androideabi-ld'
strip = './toolchain/bin/arm-linux-androideabi-strip'

[properties]
root = './toolchain/'

[host_machine]
system = 'android-arm'
cpu_family = 'arm'
cpu = 'armv7a'
endian = 'little'
```

Any ideas?

**Comment by hypothermic** [comment]
Changing the paths in `android.txt` to absolute worked.
