### ISSUE TITLE
Infinite recursion on cmake subproject configuration under Windows 10

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#6202]
I am facing an infinite recursion problem when using Capnproto 0.7 subproject under Windows 10.

Meson version: 0.51.1 (because 0.52.0 detects boost 32-bit in Windows so I sticked to this)

How to reproduce: Just set  a cmake subproject with capnproto 0.7 that can be found here: https://capnproto.org/capnproto-c++-win32-0.7.0.zip
```
-- Build files have been written to: C:/GitProjects/xxxx/build/subprojects/capnproto-c++-0.7.0/__CMake_build
|
|CMake configuration: SUCCEEDED
|CMake server handshake: SUCCEEDED
|CMake server configure: SUCCEEDED
|Generating build system files: SUCCEEDED
|Querying build system files: SUCCEEDED
|Querying the CMake code model: SUCCEEDED
|CMake project Cap'n Proto has 12 build targets.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\mesonmain.py", line 127, in run
    return options.run_func(options)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 240, in run
    app.generate()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 158, in generate
    self._generate(env)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 187, in _generate
    intr.run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3917, in run
    super().run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1048, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 440, in evaluate_statement
    return self.method_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 810, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 1705, in method_call
    value = fn(self.interpreter, state, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 231, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\modules\cmake.py", line 277, in subproject
    return CMakeSubprojectHolder(interpreter.do_subproject(dirname, 'cmake', kwargs), dirname)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2493, in do_subproject
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2479, in do_subproject
    return self._do_subproject_cmake(dirname, subdir, subdir_abs, default_options, required, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2536, in _do_subproject_cmake
    ast = cm_int.pretend_to_be_meson()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 555, in pretend_to_be_meson
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  [Previous line repeated 962 more times]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 494, in process_target
    link_with += [id_node(processed[i.name]['tgt'])]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 435, in id_node
    return IdNode(token(val=value))
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 429, in token
    return Token(tid, self.subdir, 0, 0, 0, None, val)
RecursionError: maximum recursion depth exceeded|-- Build files have been written to: C:/GitProjects/xxxxx/build/subprojects/capnproto-c++-0.7.0/__CMake_build
|
|CMake configuration: SUCCEEDED
|CMake server handshake: SUCCEEDED
|CMake server configure: SUCCEEDED
|Generating build system files: SUCCEEDED
|Querying build system files: SUCCEEDED
|Querying the CMake code model: SUCCEEDED
|CMake project Cap'n Proto has 12 build targets.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\mesonmain.py", line 127, in run
    return options.run_func(options)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 240, in run
    app.generate()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 158, in generate
    self._generate(env)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 187, in _generate
    intr.run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3917, in run
    super().run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1048, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 440, in evaluate_statement
    return self.method_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 810, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 1705, in method_call
    value = fn(self.interpreter, state, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 231, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\modules\cmake.py", line 277, in subproject
    return CMakeSubprojectHolder(interpreter.do_subproject(dirname, 'cmake', kwargs), dirname)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2493, in do_subproject
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2479, in do_subproject
    return self._do_subproject_cmake(dirname, subdir, subdir_abs, default_options, required, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2536, in _do_subproject_cmake
    ast = cm_int.pretend_to_be_meson()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 555, in pretend_to_be_meson
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  [Previous line repeated 962 more times]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 494, in process_target
    link_with += [id_node(processed[i.name]['tgt'])]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 435, in id_node
    return IdNode(token(val=value))
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 429, in token
    return Token(tid, self.subdir, 0, 0, 0, None, val)
RecursionError: maximum recursion depth exceededse a cmake subproject

```
|-- Build files have been written to: C:/GitProjects/xxxx/build/subprojects/capnproto-c++-0.7.0/__CMake_build
|
|CMake configuration: SUCCEEDED
|CMake server handshake: SUCCEEDED
|CMake server configure: SUCCEEDED
|Generating build system files: SUCCEEDED
|Querying build system files: SUCCEEDED
|Querying the CMake code model: SUCCEEDED
|CMake project Cap'n Proto has 12 build targets.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\mesonmain.py", line 127, in run
    return options.run_func(options)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 240, in run
    app.generate()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 158, in generate
    self._generate(env)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\msetup.py", line 187, in _generate
    intr.run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3917, in run
    super().run()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 773, in function_call
    return func(node, posargs, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 3458, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 1048, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 440, in evaluate_statement
    return self.method_call(cur)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 810, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 1705, in method_call
    value = fn(self.interpreter, state, args, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 231, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\modules\cmake.py", line 277, in subproject
    return CMakeSubprojectHolder(interpreter.do_subproject(dirname, 'cmake', kwargs), dirname)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2493, in do_subproject
    raise e
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2479, in do_subproject
    return self._do_subproject_cmake(dirname, subdir, subdir_abs, default_options, required, kwargs)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\interpreter.py", line 2536, in _do_subproject_cmake
    ast = cm_int.pretend_to_be_meson()
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 555, in pretend_to_be_meson
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 493, in process_target
    process_target(i)
  [Previous line repeated 962 more times]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 494, in process_target
    link_with += [id_node(processed[i.name]['tgt'])]
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 435, in id_node
    return IdNode(token(val=value))
  File "C:\Program Files\Python37\lib\site-packages\mesonbuild\cmake\interpreter.py", line 429, in token
    return Token(tid, self.subdir, 0, 0, 0, None, val)
RecursionError: maximum recursion depth exceeded
```

**Comment by mensinda** [comment]
Could you please try to reproduce this with the current meson master (in a small test project to avoid the boost issue)? I currently lack a windows VM to test this project and there are major changes in the CMake support between the 0.51 and the master branch.

**Comment by germandiagogomez** [comment]
Not happening anymore
