### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not ExternalProgramHolder

### ISSUE THREAD

**Issue by jtojnar** [mesonbuild/meson#6217]
**Describe the bug**
When trying to make GIMP build system more robust (https://gitlab.gnome.org/GNOME/gimp/merge_requests/181) I encountered the following crash:

```python
Traceback (most recent call last):
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4020, in run
    super().run()
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 451, in evaluate_statement
    return self.evaluate_if(cur)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 516, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1053, in assignment
    value = self.evaluate_statement(node.value)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 778, in function_call
    return func(node, posargs, kwargs)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/nix/store/g90890h0d4xrzb8h6k6cqxdn1wdh5xcq-meson-0.52.0/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3276, in func_vcs_tag
    vcs_cmd[0] = shutil.which(vcs_cmd[0]) or os.path.join(source_dir, vcs_cmd[0])
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/shutil.py", line 1138, in which
    if os.path.dirname(cmd):
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not ExternalProgramHolder
```

I can also use `git.path()` but then I get:

```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**
Here is MVE:

```meson
project('gimp')

git = find_program('git', required: false, disabler: false)
# git = find_program('nongit', required: false, disabler: false)
# git = find_program('git', required: false, disabler: true)
# git = find_program('nongit', required: false, disabler: true)

gitversion_h1 = vcs_tag(
  input : 'git-version.h.in',
  output: 'git-version.h',
  command: [ git ],
  # command: [ git.path() ],
  replace_string: '@GIMP_GIT_LAST_COMMIT_YEAR@',
  fallback: 'unknown (unsupported)',
)
```

See this table for all the variants I have tried:

| disabler | `.path()` | git present |                 result                 |
|----------|-----------|-------------|----------------------------------------|
| false    | no        | yes, no     | :no: TypeError (ExternalProgramHolder) |
| false    | yes       | yes         | :yes:                                  |
| false    | yes       | no          | :no: TypeError (NoneType)              |
| true     | no        | yes         | :no: TypeError (ExternalProgramHolder) |
| true     | no        | no          | :yes:                                  |
| true     | yes       | yes         | :yes:                                  |
| true     | yes       | no          | :no: Unknown method "path" in object.  |

Perhaps this should really be two issues:

* `vcs_tag` should not crash Meson when object is passed to `command` list
* `disabler().path()` should return disabler.

**Expected behavior**
Meson should stop with a clean error, not a traceback.

**system parameters**
* build: native
* OS: NixOS unstable
* Python: 3.7.5
* Meson: 0.52.0

**Comment by jtojnar** [comment]
Apparently, `vcs_tag(command: [ disabler() ], fallback: 'foo')` returns `disabler()` instead of producing header with the fallback substituted in. That makes sense for a short-circuiting object, event though it is less useful.

I guess this issue should focus on just improving the error messages.

**Comment by jameshilliard** [comment]
> Apparently, `vcs_tag(command: [ disabler() ], fallback: 'foo')` returns `disabler()` instead of producing header with the fallback substituted in.

Yeah, you can work around this by checking if the command is a disabler before passing it to `vss_tag` using `is_disabler()`. I guess we should probably see if it makes sense to rework the disabler logic when fallbacks are present.

**Comment by dcbaker** [comment]
Oops, wrong tab.

**Comment by jameshilliard** [comment]
@jtojnar I've reworked the way `vcs_tag` interacts with disablers in #7065, see if that fixes all the issues here for you.

**Comment by bonzini** [comment]
No exceptions anymore. Some tests for the PR in #7065 fails because there is no special handling of disablers, but that is probably out of scope because at least it's consistent with how disablers work in general.
