### ISSUE TITLE
A % in a config string causes scan-build to fail

### ISSUE THREAD

**Issue by geissonator** [mesonbuild/meson#6323]
**Describe the bug**
A % in a config string causes scan-build to fail

**To Reproduce**
Add a meson_options.txt option that has a % within it. For example:
```
option(
    'host-running-file', type: 'string',
    value: '/run/openbmc/host@%d-on',
    description: 'File to create if host is running.',
)
```
Run a scan build and you'll get something like this:
```
ninja: Entering directory `build'
[0/1] /usr/local/bin/meson --internal scanbuild /Users/andrewg@us.ibm.com/Code/phosphor-state-manager /...tedHostTransition -Dpoh-counter-persist-path=/var/lib/phosphor-state-manager/POHCounter -Dtests=enable
scan-build: Using '/usr/lib/llvm-8/bin/clang' for static analysis
The Meson build system
Version: 0.52.0
Source dir: /Users/andrewg@us.ibm.com/Code/phosphor-state-manager
Build dir: /Users/andrewg@us.ibm.com/Code/phosphor-state-manager/build/meson-private/tmpu854oc_4
Build type: native build
Project name: phosphor-state-manager
Project version: 0.1
C++ compiler for the host machine: /usr/share/clang/scan-build-8/bin/../libexec/c++-analyzer (gcc 9.2.1 "g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
C++ linker for the host machine: GNU ld.bfd 2.33
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency sdbusplus found: YES 1.0
Run-time dependency sdeventplus found: YES 0.1
Run-time dependency phosphor-logging found: YES 1.0
Run-time dependency phosphor-dbus-interfaces found: YES 1.0
Library stdc++fs found: YES
Run-time dependency GTest found: YES 1.9.0
Build targets in project: 8
Found ninja-1.9.0 at /usr/bin/ninja
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 218, in _generate
    coredata.write_cmd_line_file(self.build_dir, self.options)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/coredata.py", line 816, in write_cmd_line_file
    config['options'] = options.cmd_line_options
  File "/usr/lib/python3.7/configparser.py", line 971, in __setitem__
    self.read_dict({key: value})
  File "/usr/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/usr/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/usr/lib/python3.7/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '/run/openbmc/host@%d-on' at position 18
scan-build: Removing directory '/tmp/scan-build-2019-12-09-205852-245-1' because it contains no reports.
scan-build: No bugs found.
FAILED: meson-scan-build 
```

I think this may be more of a python issue. I've seen some projects do workarounds like the one documented in https://github.com/distributed-system-analysis/pbench/issues/1329

**Expected behavior**
For the scan-build to complete without failure.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Native build within a docker container

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
MacOS executing a docker container based on Ubuntu 19.10

* what Python version are you using e.g. 3.8.0
3.7.5rc1

* what `meson --version`
0.52.0

* what `ninja --version` if it's a Ninja build
1.9.0

**Comment by scivision** [comment]
#6170 may have solved this problem, could you try this with the latest Git master?
e.g.

```sh
https://github.com/mesonbuild/meson

pip install -e meson
```

and then retry the failing situation

**Comment by geissonator** [comment]
Thanks, confirmed "Version: 0.52.999" (master as of today) does fix my issue.
