### ISSUE TITLE
regression: compilers: intel, intel-cl, pgi, cuda

### ISSUE THREAD

**Issue by scivision** [mesonbuild/meson#6332]
ef9aeb188ea2bc7353e59916c18901cde90fa2b3 is the first bad commit

Intel compiler on Linux does *not* appear to be affected.

* ifort (intel-cl 19.0.5.281)
* xilink 19.0.5.281
* icl (intel-cl 19.0.5.281)
* Python 3.7.5
* Windows 10

```sh
$ meson build
```

leads to traceback
```
The Meson build system
Version: 0.52.999
Build type: native build
Traceback (most recent call last):
  File "meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "meson\mesonbuild\msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "meson\mesonbuild\interpreter.py", line 2111, in __init__
    self.parse_project()
  File "meson\mesonbuild\interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "meson\mesonbuild\interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson\mesonbuild\interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson\mesonbuild\interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson\mesonbuild\interpreterbase.py", line 785, in function_call
    return func(node, posargs, kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson\mesonbuild\interpreter.py", line 2777, in func_project
    self.add_languages(proj_langs, True)
  File "meson\mesonbuild\interpreter.py", line 2837, in add_languages
    success = self.add_languages_for(args, required, MachineChoice.BUILD)
  File "meson\mesonbuild\interpreter.py", line 2853, in add_languages_for
    comp = self.environment.detect_compiler_for(lang, for_machine)
  File "meson\mesonbuild\environment.py", line 1527, in detect_compiler_for
    comp = self.compiler_from_language(lang, for_machine)
  File "meson\mesonbuild\environment.py", line 1499, in compiler_from_language
    comp = self.detect_c_compiler(for_machine)
  File "meson\mesonbuild\environment.py", line 1068, in detect_c_compiler
    return self._detect_c_or_cpp_compiler('c', for_machine)
  File "meson\mesonbuild\environment.py", line 1009, in _detect_c_or_cpp_compiler
    linker = XilinkDynamicLinker(for_machine, version=version)
TypeError: __init__() missing 1 required positional argument: 'always_args'
```

**Comment by scivision** [comment]
@dcbaker

**Comment by scivision** [comment]
for `pgi` 19.10 on Windows:

```
Traceback (most recent call last):
  File "\meson\mesonbuild\mesonmain.py", line 129, in run
    return options.run_func(options)
  File "\meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "\meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "\meson\mesonbuild\msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "\meson\mesonbuild\interpreter.py", line 2120, in __init__
    self.parse_project()
  File "\meson\mesonbuild\interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "\meson\mesonbuild\interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "\meson\mesonbuild\interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "\meson\mesonbuild\interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "\meson\mesonbuild\interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "\meson\mesonbuild\interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "\meson\mesonbuild\interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "\meson\mesonbuild\interpreter.py", line 2796, in func_project
    self.add_languages(proj_langs, True)
  File "\meson\mesonbuild\interpreter.py", line 2856, in add_languages
    success = self.add_languages_for(args, required, MachineChoice.BUILD)
  File "\meson\mesonbuild\interpreter.py", line 2872, in add_languages_for
    comp = self.environment.detect_compiler_for(lang, for_machine)
  File "\meson\mesonbuild\environment.py", line 1541, in detect_compiler_for
    comp = self.compiler_from_language(lang, for_machine)
  File "\meson\mesonbuild\environment.py", line 1533, in compiler_from_language
    comp = self.detect_fortran_compiler(for_machine)
  File "\meson\mesonbuild\environment.py", line 1191, in detect_fortran_compiler
    PGIFortranCompiler.LINKER_PREFIX, version=version)
TypeError: __init__() missing 1 required positional argument: 'always_args'
```

**Comment by scivision** [comment]
PGI on Linux:

```
Traceback (most recent call last):
  File "meson/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "meson/mesonbuild/msetup.py", line 176, in _generate
    intr = interpreter.Interpreter(b)
  File "meson/mesonbuild/interpreter.py", line 2114, in __init__
    self.parse_project()
  File "meson/mesonbuild/interpreterbase.py", line 397, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreter.py", line 2790, in func_project
    self.add_languages(proj_langs, True)
  File "meson/mesonbuild/interpreter.py", line 2850, in add_languages
    success = self.add_languages_for(args, required, MachineChoice.BUILD)
  File "meson/mesonbuild/interpreter.py", line 2866, in add_languages_for
    comp = self.environment.detect_compiler_for(lang, for_machine)
  File "meson/mesonbuild/environment.py", line 1541, in detect_compiler_for
    comp = self.compiler_from_language(lang, for_machine)
  File "meson/mesonbuild/environment.py", line 1533, in compiler_from_language
    comp = self.detect_fortran_compiler(for_machine)
  File "meson/mesonbuild/environment.py", line 1191, in detect_fortran_compiler
    PGIFortranCompiler.LINKER_PREFIX, version=version)
TypeError: __init__() missing 1 required positional argument: 'always_args'
```

**Comment by scivision** [comment]
cuda on Windows 10

$ python run_project_tests.py

```
Traceback (most recent call last):
  File ".\run_project_tests.py", line 959, in <module>
    detect_system_compiler()
  File ".\run_project_tests.py", line 899, in detect_system_compiler
    comp = env.compiler_from_language(lang, MachineChoice.HOST)
  File "meson\mesonbuild\environment.py", line 1519, in compiler_from_language
    comp = self.detect_cuda_compiler(for_machine)
  File "meson\mesonbuild\environment.py", line 1108, in detect_cuda_compiler
    linker = CudaLinker(compiler, for_machine, 'nvlink', CudaCompiler.LINKER_PREFIX, version=CudaLinker.parse_version())TypeError: __init__() missing 1 required positional argument: 'always_args'
```

**Comment by jpakkane** [comment]
Can you test if the linker MR fixes this for you?
