### ISSUE TITLE
rpm module doesn't generate template - new cause

### ISSUE THREAD

**Issue by laolux** [mesonbuild/meson#6384]
**Describe the bug**
The meson RPM module does not produce a rpm spec file template but crashes the entire meson instead.
Old and similar issue is #2202, which was fixed in #4740.

**To Reproduce**
Make a tiny c++ project (single source) and use meson to generate a rpm spec file template. Whenever I run 'meson build' meson just crashes with

    The Meson build system
    Version: 0.52.0
    Source dir: /path/mesonhello
    Build dir: /path/mesonhello/build
    Build type: native build
    Project name: mesonhello
    Project version: undefined
    C++ compiler for the host machine: c++ (gcc 9.2.1 "c++ (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)")
    C++ linker for the host machine: GNU ld.bfd 2.32-30
    Host machine cpu family: x86_64
    Host machine cpu: x86_64
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
        return options.run_func(options)
      File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
        app.generate()
      File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
        self._generate(env)
      File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 192, in _generate
        intr.run()
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4020, in run
        super().run()
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 412, in run
        self.evaluate_codeblock(self.ast, start=1)
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
        raise e
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
        self.evaluate_statement(cur)
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 445, in evaluate_statement
        return self.method_call(cur)
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 815, in method_call
        return obj.method_call(method_name, args, kwargs)
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 1741, in method_call
        value = fn(state, args, kwargs)
      File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 134, in wrapped
        return f(*wrapped_args, **wrapped_kwargs)
      File "/usr/lib/python3.7/site-packages/mesonbuild/modules/rpm.py", line 34, in generate_spec_template
        required_compilers = self.__get_required_compilers()
      File "/usr/lib/python3.7/site-packages/mesonbuild/modules/rpm.py", line 154, in __get_required_compilers
        for compiler in self.coredata.compilers.values():
    AttributeError: 'ModuleState' object has no attribute 'compilers'

The c++ file used (main.cpp):

    #include <iostream>

    int main(){
            std::cout << "meson example project, packaged with rpm." << std::endl;
            return 0;
    }

The `meson.build`:

    project('mesonhello', 'cpp')
    executable('mesonhelloexec', 'main.cpp', install : true)
    rpm = import('rpm')
    rpm.generate_spec_template()

**Expected behavior**
I get a great rpm spec file template which hardly needs any changes before using productively.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
This is a plain build for the same computer.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
OS: Fedora 31
* what Python version are you using e.g. 3.8.0
Python 3.7.6
* what `meson --version`
meson version 0.52.0
* what `ninja --version` if it's a Ninja build
I do not even get to use ninja...

**Comment by eli-schwartz** [comment]
This got mysteriously fixed by one of a couple tagalong commits in #6238 and currently the example works.

> I get a great rpm spec file template which hardly needs any changes before using productively.

I dispute the notion that rpm spec files are "great", or can be used productively, though. :p

And in this case, this module is unmaintained abandonware... it periodically breaks for 3+ years and no one notices...
