### ISSUE TITLE
wrap db is down

### ISSUE THREAD

**Issue by RafaGago** [mesonbuild/meson#6454]
Can reproduce both on Github and locally

On Github:
https://github.com/RafaGago/base_library/runs/386762100

Locally
```
$ meson build
The Meson build system
Version: 0.52.1
Source dir: /home/rafa/base_library
Build dir: /home/rafa/base_library/build
Build type: native build
Project name: base_library
Project version: 0.1.0
C compiler for the host machine: cc (gcc 8.3.0 "cc (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0")
C linker for the host machine: GNU ld.bfd 2.30
C++ compiler for the host machine: c++ (gcc 8.3.0 "c++ (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0")
C++ linker for the host machine: GNU ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Downloading cmocka source from https://cmocka.org/files/1.1/cmocka-1.1.2.tar.xz
Download size: 82300
Downloading: ..........
Downloading cmocka patch from https://wrapdb.mesonbuild.com/v1/projects/cmocka/1.1.2/1/get_zip
SSL connection failed. Falling back to unencrypted connections.
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 4024, in run
    super().run()
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 451, in evaluate_statement
    return self.evaluate_if(cur)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 1054, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 776, in function_call
    return func(node, posargs, kwargs)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2454, in func_subproject
    return self.do_subproject(dirname, 'meson', kwargs)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2493, in do_subproject
    resolved = r.resolve(dirname, method)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 151, in resolve
    self.get_file()
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 226, in get_file
    self.apply_patch()
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 369, in apply_patch
    path = self.get_file_internal('patch')
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 365, in get_file_internal
    self.download(what, cache_path)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 347, in download
    dhash, tmpfile = self.get_data(srcurl)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 302, in get_data
    resp = open_wrapdburl(url)
  File "/home/rafa/.local/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 72, in open_wrapdburl
    return urllib.request.urlopen(urlstring, timeout=req_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>
```

**Comment by RafaGago** [comment]
Duplicated. 2 days without being able to build fresh.

https://github.com/mesonbuild/meson/issues/6446
