### ISSUE TITLE
Meson test fails with relative path to program

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#6467]
Meson versions : 0.52.1 **AND** git HEAD.

I've been using `find_program('../my_external_tool')`, and Meson configure did not complain about any relative path (it finds the program).

But when comes to Meson test, that's another story :
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1045, in run
    return th.doit()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 802, in doit
    self.run_tests(tests)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 954, in run_tests
    self.drain_futures(futures)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 970, in drain_futures
    self.process_test_result(result.result())
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 486, in run
    cmd = self._get_cmd()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 466, in _get_cmd
    if self.test.fname[0].endswith('.jar'):
AttributeError: 'NoneType' object has no attribute 'endswith'
ninja: job failed: /usr/bin/meson test --no-rebuild --print-errorlogs
ninja: subcommand failed
```

Using an absolute path (but not finite, meaning there are still unresolved `../` inside) resolves the issue.

**Comment by xclaesse** [comment]
How are you using the program it found? Can you provide a minimal test case?

**Comment by bonzini** [comment]
Tried `test('test', find_program('../f.sh'))` and it works, closing.
