### ISSUE TITLE
Compatibility broken with Python 3.5

### ISSUE THREAD

**Issue by Finii** [mesonbuild/meson#6496]
When Python is only on version 3.5 meson can not be invoked anymore.

Culprit are these two commits
* 875ef354 compilers: Rework the CompilerArgs to be less awful
* e88b3c80 build: Fix type signature of rich comparison dunders

by @dcbaker 

This is the Python version used (on Ubuntu 16.04):
```
~/git/meson$ python3 --version
Python 3.5.2

~/git/meson$ which python3
/usr/bin/python3

~/git/meson$ apt-file search -F `which python3`
python3-minimal: /usr/bin/python3

~/git/meson$ dpkg -l python3-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  python3-minimal                                 3.5.1-3                      amd64                        minimal subset of the Python language (default python3 version)

~/git/meson$
```

Here a sample output that shows the issue:
```
~/git/meson$ git checkout 0.53.0
[...] HEAD is now at 8d576eb... Prepare new release.
~/git/meson$ ./meson.py --version
Traceback (most recent call last):
  File "./meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/ujastrow/git/meson/mesonbuild/mesonmain.py", line 25, in <module>
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata
  File "/home/ujastrow/git/meson/mesonbuild/mconf.py", line 16, in <module>
    from . import coredata, environment, mesonlib, build, mintro, mlog
  File "/home/ujastrow/git/meson/mesonbuild/environment.py", line 32, in <module>
    from . import compilers
  File "/home/ujastrow/git/meson/mesonbuild/compilers/__init__.py", line 102, in <module>
    from .compilers import (
  File "/home/ujastrow/git/meson/mesonbuild/compilers/compilers.py", line 389, in <module>
    class CompilerArgs(typing.MutableSequence[str]):
  File "/home/ujastrow/git/meson/mesonbuild/compilers/compilers.py", line 658, in CompilerArgs
    def __eq__(self, other: typing.Any) -> typing.Union[bool, 'NotImplemented']:
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 178, in _eval_type
    "Forward references must evaluate to types.")
  File "/usr/lib/python3.5/typing.py", line 312, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Forward references must evaluate to types. Got NotImplemented.
~/git/meson$ 
```

Reverting the two aforementioned commits restores full functionality, at least for me. So I guess they have to be revisited.

Thank you!

**Comment by Finii** [comment]
Sorry, duplicate of issue #6427
