### ISSUE TITLE
possible 0.53.1 git wrap checkout regression

### ISSUE THREAD

**Issue by scivision** [mesonbuild/meson#6505]
I haven't had the time to segment this, but with  but fails only with **Meson 0.53.1**. Other software versions: Git 2.24.1, Ubuntu 18.04, Python 3.7.5.

Meson 0.53.0 or Git master Meson this works without error as expected.

It is probably not peculiar to this repo, I just didn't take the time to make a standalone example, If it isn't a weird quirk from me, then others might start experiencing this soon.

wrap file:
```ini
[wrap-git]
directory = glow
url = https://github.com/gemini3d/glow.git
revision = 915592c
```

traceback on invoking meson.build `subproject()`
```
fatal: couldn't find remote ref 915592c
Traceback (most recent call last):
  File "meson/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "meson/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "meson/mesonbuild/interpreter.py", line 4165, in run
    super().run()
  File "meson/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreter.py", line 3687, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson/mesonbuild/interpreterbase.py", line 451, in evaluate_statement
    return self.evaluate_if(cur)
  File "meson/mesonbuild/interpreterbase.py", line 530, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "meson/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "meson/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "meson/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "meson/mesonbuild/interpreterbase.py", line 1064, in assignment
    value = self.evaluate_statement(node.value)
  File "meson/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "meson/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreterbase.py", line 143, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "meson/mesonbuild/interpreter.py", line 2538, in func_subproject
    return self.do_subproject(dirname, 'meson', kwargs)
  File "meson/mesonbuild/interpreter.py", line 2580, in do_subproject
    resolved = r.resolve(dirname, method)
  File "meson/mesonbuild/wrap/wrap.py", line 187, in resolve
    self.get_git()
  File "meson/mesonbuild/wrap/wrap.py", line 285, in get_git
    verbose_git(['fetch', self.wrap.get('url'), revno], self.dirname, check=True)
  File "meson/mesonbuild/wrap/wrap.py", line 62, in verbose_git
    return git(cmd, workingdir, check=check).returncode == 0
  File "meson/mesonbuild/mesonlib.py", line 64, in git
    stdin=subprocess.DEVNULL, **kwargs)
  File "/home/box/miniconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/git', '-C', '/mnt/c/code/gemini/subprojects/glow', 'fetch', 'https://github.com/gemini3d/glow.git', '915592c']' returned non-zero exit status 128.
```

**Comment by xclaesse** [comment]
`fatal: Couldn't find remote ref 915592c`, can you double check that commit id exists?

**Comment by xclaesse** [comment]
Oh I see, regression caused by @nirbheek and that I didn't catch when reviewing.

**Comment by scivision** [comment]
sorry for the incomplete report. Glad it wasn't just me.
