### ISSUE TITLE
KeyError: 'b_vscrt' with Visual Studio 2019 (meson)

### ISSUE THREAD

**Issue by neishka998** [mesonbuild/meson#6607]
It is showing me key error when i am running **meson  buildvs --backend=vs2019**

Version: 0.53.0
Source dir: /Users/neishkasrivastava/harfbuzz
Build dir: /Users/neishkasrivastava/harfbuzz/buildvs
Build type: native build
Project name: harfbuzz
Project version: undefined
C++ compiler for the host machine: c++ (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.17)")
C++ linker for the host machine: c++ APPLE ld 530
Host machine cpu family: x86_64
Host machine cpu: x86_64
Library m found: YES
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.62.4
Run-time dependency cairo found: YES 1.16.0
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -pedantic: YES 
Compiler for C++ supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C++ supports arguments -Werror=vla: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Configuring hb-version.h using configuration
Build targets in project: 2

Traceback (most recent call last):
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate(intr)
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/vs2010backend.py", line 181, in generate
    projlist = self.generate_projects()
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/vs2010backend.py", line 415, in generate_projects
    self.gen_vcxproj(target, str(projfile_path), proj_uuid)
  File "/Users/neishkasrivastava/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/vs2010backend.py", line 777, in gen_vcxproj
    vscrt_type = self.environment.coredata.base_options['b_vscrt']

KeyError: 'b_vscrt'

**Comment by mrobertseidowsky-gpsw** [comment]
Hello, I've exactly the same issue, is anyone has an idea of solution?

**Comment by jpakkane** [comment]
You can not mix clang with the VS backend. You can only use the Ninja one. If you want to use VS then you also have to use the VS compiler.

**Comment by dcbaker** [comment]
You can use clang-cl with the be backend though
