### ISSUE TITLE
summary(): IndexError: list index out of range when empty list is printed

### ISSUE THREAD

**Issue by nh2** [mesonbuild/meson#6645]
**Describe the bug**

But in the new `summary()` function:

```meson
summary({
  'somelist': [],
})
```

Result:

```
Traceback (most recent call last):
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 4172, in run
    self._print_summary()
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2929, in _print_summary
    main_summary.dump()
  File "/nix/store/xcar77agh5khbzcr1npmac56qbk1wgxy-meson-0.53.1/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1796, in dump
    mlog.log(' ' * indent, k + ':', v[0])
IndexError: list index out of range
```

`v[0]` is accessed, which cannot work for the empty list.

That is this line https://github.com/mesonbuild/meson/commit/6e865a233099a00e9ea08f6a2f911ede3c7b4215#diff-e3100e45aaf56f9ead204d2bdcc3b774R1781

CC @xclaesse 

**Expected behavior**

Prints the empty list without crashing.

**Comment by nh2** [comment]
Workaround I'm using for now:

```meson
summary({'somelist': '@0@'.format( mylist )})
```

**Comment by xclaesse** [comment]
Already fixed: https://github.com/mesonbuild/meson/pull/6563.

**Comment by nh2** [comment]
That's great, thanks!
