### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'thread_flags' when cross-compiling with v 0.53.1

### ISSUE THREAD

**Issue by daemoohn** [mesonbuild/meson#6684]
Setup:
-meson 0.53.1 with python 3.7
-debian 10
-emscripten 1.39.8

I'm trying to cross-compile a C library, dav1d.
Here's the build script:
`
CFLAGS=-pthread \
LDFLAGS=-pthread \
meson ../../../dav1d \
	--cross-file=../../../build-dav1d-cross-compile.txt \
	-Dbitdepths='["8"]' \
	-Denable_asm=true \
	-Denable_tools=false \
	-Denable_examples=false \
	-Denable_tests=false \
	-Dlogging=false \
	-Ddefault_library=static \
    --buildtype release
`
Here's the cross-compilation file:
`
[binaries]
c = 'emcc'
ar = 'emar'
install_name_tool = 'echo'
exe_wrapper = 'echo'

[properties]
c_args = ['-s', 'WASM=1', '-s', 'SIMD=1', '-s', 'WASM_OBJECT_FILES=0', '-s', 'USE_PTHREADS=1']
c_link_args = ['-s', 'WASM=1', '-s', 'SIMD=1', '-s', 'WASM_OBJECT_FILES=0', '-s', 'USE_PTHREADS=1']
needs_exe_wrapper = true

[host_machine]
system = 'linux'
cpu_family = 'wasm32'
cpu = 'wasm32'
endian = 'little'
`
Here's the output:
`
The Meson build system
Version: 0.53.1
Source dir: /home/daemoohn/work/mercury/dav1d
Build dir: /home/daemoohn/work/mercury/build/temp/dav1d
Build type: cross build
Project name: dav1d
Project version: 0.5.2
Appending CFLAGS from environment: '-pthread'
Appending LDFLAGS from environment: ['-pthread']
C compiler for the build machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
C linker for the build machine: cc GNU ld.bfd 2.31.1
/home/daemoohn/work/mercury/build/temp/dav1d/meson-private/sanitycheckc_cross.exe
C compiler for the host machine: emcc (emscripten 1.39.8 "emcc (Emscripten gcc/clang-like replacement) 1.39.8 (commit 1458145cf4f3db0fb548343e6acab267eef8e4ef)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: wasm32
Host machine cpu: wasm32
Target machine cpu family: wasm32
Target machine cpu: wasm32
Traceback (most recent call last):
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 4165, in run
    super().run()
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 412, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 451, in evaluate_statement
    return self.evaluate_if(cur)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 533, in evaluate_if
    self.evaluate_codeblock(node.elseblock)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_codeblock
    raise e
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 430, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 443, in evaluate_statement
    return self.assignment(cur)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 1064, in assignment
    value = self.evaluate_statement(node.value)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 441, in evaluate_statement
    return self.function_call(cur)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 788, in function_call
    return func(node, posargs, kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 2 more times]
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 155, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3234, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3281, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/dependencies/base.py", line 2230, in find_external_dependency
    d = c()
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/dependencies/misc.py", line 141, in __init__
    self.link_args = self.clib_compiler.thread_link_flags(environment)
  File "/home/daemoohn/.local/lib/python3.7/site-packages/mesonbuild/compilers/mixins/clike.py", line 1071, in thread_link_flags
    return self.linker.thread_flags(env)
AttributeError: 'NoneType' object has no attribute 'thread_flags'
`

**Comment by daemoohn** [comment]
Thank you for support!
