### ISSUE TITLE
Defiantly a problem with buildsystem_files.json for Windows host

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6921]
**Describe the bug**
Most of this issue has been explained in #6895, here I confirm that it does present an issue
for users that wish to use custom IDE backends on Windows host operating systems.

**To Reproduce**

```
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\view\setup_activity.py", line 60, in <lambda>
    self.control_push_do_setup.clicked.connect(lambda: self.exec_do_setup())
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\view\setup_activity.py", line 104, in exec_do_setup
    self._cache_sender(meson_args=meson_args)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\view\setup_activity.py", line 126, in _cache_sender
    ide = backend_factory(self.combo_backend.currentText(), self.meson_api)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\mesonuilib\backend.py", line 24, in backend_factory
    }[backend](meson_api)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\mesonuilib\backends\kdevelop.py", line 23, in __init__
    self.project_name = re.sub(r'[^a-z0-9]', '_', self.projectinfo['descriptive_name'])
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\mesonuilib\backends\backendimpl.py", line 18, in projectinfo
    return self.meson_api.get_object(group='projectinfo', extract_method='loader')
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\repository\mesonapi.py", line 37, in get_object
    return self._builddir_loader.extract_from(group=group)
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\repository\dataloader.py", line 44, in extract_from
    return self._scan(group=f'intro-{group}.json')
  File "C:\Users\Mike\AppData\Roaming\Python\Python37\site-packages\mesonui\repository\dataloader.py", line 26, in _scan
    with open(join(self._builddir, subdir, group)) as loaded_json:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Mike/Desktop/cpp-program\\builddir\\meson-info\\intro-projectinfo.json'

C:\Users\Mike>
```

**Expected behavior**
Also same as #6895.

**system parameters**
* Is this just a plain native build with custom backend
* Windows 10
* python 3.8.2
* `meson 0.54.0`
* `ninja 1.9.0`

**Comment by michaelbadcrumble** [comment]
Ping
