### ISSUE TITLE
`b_sanitize=memory` failures get interpreted as skipped tests by `meson test`

### ISSUE THREAD

**Issue by haasn** [mesonbuild/meson#6978]
**Describe the bug**
When compiling a project with `-Db_sanitize=memory` and running `meson test` afterwards, memory sanitizer failures are interpreted as skipped tests, because the [default exit code for msan is `77`](https://github.com/llvm-mirror/compiler-rt/blob/master/lib/msan/msan.cpp#L150), the same as the GNU test exit code for "skip this test".

This is [arguably an upstream bug](https://github.com/google/sanitizers/issues/1225), but I think we're in a position to work around it, because this clash in default behaviour is quite confusing for users, especially given upstream's lack of good documentation. At the very least, **it should be documented somewhere in meson** that users are recommended to set `MSAN_OPTIONS` in combination with `-Db_sanitize=memory` to avoid this particular exitcode issue.

**To Reproduce**
`demo.c`:
```c
int main()
{
    int x;
    return x;
}
```

`meson.build`:
```meson
project('demo', 'c')
e = executable('demo', 'demo.c')
test('undefined behavior', e)
```

Reproduction steps:
```shell
$ CC=clang meson build -Db_sanitize=memory -Db_lundef=false
The Meson build system
Version: 0.53.1
...

$ meson test -Cbuild --verbose
ninja: Entering directory `/mem/build'
[1/2] Compiling C object 'demo@exe/demo.c.o'.
...
[2/2] Linking target demo.
==3090204==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x49339c in main /mem/build/../demo.c:4:5
    #1 0x7ff9ef30ce3a in __libc_start_main /usr/src/debug/sys-libs/glibc-2.30-r8/glibc-2.30/csu/../csu/libc-start.c:308:16
    #2 0x41c269 in _start (/mem/build/demo+0x41c269)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /mem/build/../demo.c:4:5 in main
Exiting
1/1 undefined behavior                      SKIP     0.12 s 

Ok:                    0
Expected Fail:         0
Fail:                  0
Unexpected Pass:       0
Skipped:               1
Timeout:               0
```

**Expected behavior**
Unless the user explicitly overrides this already, meson should automatically export some variant of `MSAN_OPTIONS=exitcode=N` when running tests defined with `b_sanitize=memory`, where N is some exit code that is not 77.

**system parameters**
* `uname -a`: `Linux xor 5.6.3-gentoo #1 SMP PREEMPT Sat Apr 11 03:15:51 CEST 2020 x86_64 AMD Ryzen Threadripper 1950X 16-Core Processor AuthenticAMD Linux`
* `python --version`: `Python 3.7.7`
* `meson --version`: `0.51.1`
* `ninja --version`: `1.10.0`
* `clang --version`: `10.0.0`
* compiler-rt-sanitizers version: 10.0.0

**Comment by Flowdalic** [comment]
Related LLVM change request https://reviews.llvm.org/D92490

**Comment by dcbaker** [comment]
Thanks for fixing that upstream.

**Comment by bonzini** [comment]
Fixed in LLVM.

**Comment by thesamesam** [comment]
https://github.com/mesonbuild/meson/commit/8ba0ea68017b489b0a461abbd375f319dc7a48f3 and https://github.com/mesonbuild/meson/commit/8480f3e795395edeb9b8c25ae5fae4afb05559c7 too
