### ISSUE TITLE
meson build ends with "Build targets in project: 1722"

### ISSUE THREAD

**Issue by knifegunaxe** [mesonbuild/meson#6996]
meson don't build efl-1.23.3 on trisquel 8
last output message is:

Build targets in project: 1722

after hit ctrl-c it shows:
```python
^CTraceback (most recent call last):
  File "../meson-0.54.0/meson.py", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/mesonmain.py", line 228, in main
    return run(sys.argv[1:], launcher)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/mesonmain.py", line 219, in run
    return CommandLineParser().run(args)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/backend/ninjabackend.py", line 295, in generate
    ninja = environment.detect_ninja_command_and_version(log=True)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/environment.py", line 158, in detect_ninja_command_and_version
    p, found = Popen_safe([n, '--version'])[0:2]
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/mesonlib.py", line 1151, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "/home/johannes/Downloads/meson-0.54.0/mesonbuild/mesonlib.py", line 1172, in Popen_safe_legacy
    o, e = p.communicate(input_)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

this happens with meson-0.52.0 and meson-0.54.0 ninja version 0.1.3 Python 2.7.12

**Comment by knifegunaxe** [comment]
I did it with trisquel 9. Its working

**Comment by jpakkane** [comment]
It seems to be stuck trying to detect Ninja. Are you sure it is installed and working? At least on some platforms there are other programs with the name `ninja` and trying to run them by accident may cause these kinds of failures.

**Comment by stephen-mw** [comment]
This happens when you `apt install ninja` instead of `apt install ninja-build`. It will invoke `ninja` on $PATH and hang forever since that binary executes in the foreground.

**Comment by bonzini** [comment]
Spring cleaning of old needs-info issues.
