### ISSUE TITLE
Does not seem to be a way to give unquoted link arguments to emcc

### ISSUE THREAD

**Issue by curiousdannii** [mesonbuild/meson#7038]
Hi, I'm trying to port my emscripten project to using Meson. https://github.com/curiousdannii/emglken/tree/meson

I have the following in my meson.build, where I'm specifying several `link_args`

```
glulxe_link_args = [
    '--js-library emglken/library.js',
    '-s EMTERPRETIFY=1',
    '-s EMTERPRETIFY_ASYNC=1',
    '-s EMTERPRETIFY_WHITELIST=\'"@whitelist.json"\'',
    '-s EXPORTED_FUNCTIONS=\'["_emautosave","_emglulxeen"]\'',
    '-s MODULARIZE=1',
    '-s WASM=0',
]
executable('glulxe-core', glulxe_srcs,
    include_directories: emglken_inc,
    link_args: glulxe_link_args,
    link_with: emglken,
)
```

When I run it I get the following:

```
emcc  -o glulxe-core.js 'glulxe-core@exe/glulxe_accel.c.o' 'glulxe-core@exe/glulxe_debugger.c.o' 'glulxe-core@exe/glulxe_emglulxeen.c.o' 'glulxe-core@exe/glulxe_exec.c.o' 'glulxe-core@exe/glulxe_files.c.o' 'glulxe-core@exe/glulxe_float.c.o' 'glulxe-core@exe/glulxe_funcs.c.o' 'glulxe-core@exe/glulxe_gestalt.c.o' 'glulxe-core@exe/glulxe_glkop.c.o' 'glulxe-core@exe/glulxe_heap.c.o' 'glulxe-core@exe/glulxe_main.c.o' 'glulxe-core@exe/glulxe_operand.c.o' 'glulxe-core@exe/glulxe_osdepend.c.o' 'glulxe-core@exe/glulxe_profile.c.o' 'glulxe-core@exe/glulxe_search.c.o' 'glulxe-core@exe/glulxe_serial.c.o' 'glulxe-core@exe/glulxe_string.c.o' 'glulxe-core@exe/glulxe_vm.c.o' -s ERROR_ON_UNDEFINED_SYMBOLS=1 -Wl,-O1 -Wl,--start-group libemglken.a -Wl,--end-group '--js-library emglken/library.js' '-s EMTERPRETIFY=1' '-s EMTERPRETIFY_ASYNC=1' '-s EMTERPRETIFY_WHITELIST='"'"'"@whitelist.json"'"'"'' '-s EXPORTED_FUNCTIONS='"'"'["_emautosave","_emglulxeen"]'"'"'' '-s MODULARIZE=1' '-s WASM=0' '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/src/build/
shared:WARNING: ignoring unsupported linker flag: `-O1`
shared:WARNING: ignoring unsupported linker flag: `-rpath`
shared:WARNING: ignoring unsupported linker flag: `$ORIGIN/`
shared:WARNING: ignoring unsupported linker flag: `-rpath-link`
shared:WARNING: ignoring unsupported linker flag: `/src/build/`
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "Error: ENOENT: no such file or directory, open '/src/build/-s EMTERPRETIFY=1'" | Error: ENOENT: no such file or directory, open '/src/build/-s EMTERPRETIFY=1'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:350:35)
    at read (/emsdk_portable/fastcomp/emscripten/src/compiler.js:62:34)
    at Object.load (eval at globalEval (/emsdk_portable/fastcomp/emscripten/src/compiler.js:110:8), <anonymous>:171:17)
    at JSify (eval at globalEval (/emsdk_portable/fastcomp/emscripten/src/compiler.js:110:8), <anonymous>:76:20)
    at Object.<anonymous> (/emsdk_portable/fastcomp/emscripten/src/compiler.js:226:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
shared:ERROR: '/emsdk_portable/node/12.9.1_64bit/bin/node /emsdk_portable/fastcomp/emscripten/src/compiler.js /tmp/tmpVjJFBv.txt' failed (1)
ninja: build stopped: subcommand failed.
```

The problem seems to be that because it's adding single quotes around the `-s` options, emcc thinks it's specifying source files, rather than settings, and of course it can't find `'/src/build/-s EMTERPRETIFY=1'` etc.

Is there any way to just pass raw values to the linker?

**Comment by jpakkane** [comment]
You need to pass them as individual arguments, just like all the others. Meaning like this:

```
  '-s', 'EMTERPRETIFY=1',
```

and not like this:

```
  '-s EMTERPRETIFY=1',
```

**Comment by curiousdannii** [comment]
Thank you! That does appear to be working for the simpler settings.

But for the settings with quotes in them, it's still outputting quotes. I've tried both of these:

```
'-s', 'EXPORTED_FUNCTIONS=\'["_emautosave","_emglulxeen"]\'',
'-s', '''EXPORTED_FUNCTIONS='["_emautosave","_emglulxeen"]' ''',
```

Which result in the following, respectively:

```
-s 'EXPORTED_FUNCTIONS='"'"'["_emautosave","_emglulxeen"]'"'"''
-s ''"'"'EXPORTED_FUNCTIONS='"'"'["_emautosave","_emglulxeen"]'"'"' '
```
