### ISSUE TITLE
g-ir-scanner invocation in mesonbuild/modules/gnome.py is broken on Visual Studio

### ISSUE THREAD

**Issue by fanc999** [mesonbuild/meson#7051]
Hi,

**Describe the bug**

It seems that in recent commits that Meson no longer prepends the python executable before the g-ir-scanner command, which broke introspection builds on Windows with Visual Studio, since the underlying cmd.exe console does not support shebang lines, which caused the ```ninja: fatal: %1 is not a valid Win32 command``` error to show up, because Ninja called the g-ir-scanner Python script directly.

Could have been a regression caused by commits:
f66b04b0996eae5cd7b0ad007435d5a51f28b691
6ba034c37d8004a72d392f37f66e709c593d8983

**To Reproduce**
Using any Visual Studio with Meson 0.54.1, and attempt to build any package (e.g. ATK, for simplicity reasons) that builds introspection files with g-ir-scanner using the introspection functions in the gnome.py Meson module.

**Expected behavior**
Introspection files are built normally.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 10
* what Python version are you using e.g. 3.8.0 Python 3.7.6
* what `meson --version` 0.54.1
* what `ninja --version` if it's a Ninja build 1.8.2, 1.10.0

With blessings, thank you!

**Comment by xclaesse** [comment]
Should be fixed by https://github.com/mesonbuild/meson/pull/7020, would be appreciated if you can confirm.

**Comment by fanc999** [comment]
Hi @xclaesse,

Unfortunately, now I could not even get through the configure stage...

``
Program g_ir_scanner found: YES (c:/vs14.0/X64/bin/g-ir-scanner)
Program g_ir_compiler found: YES (c:/vs14.0/X64/bin/g-ir-compiler.exe)
Traceback (most recent call last):
  File "c:\python37.x64\lib\site-packages\mesonbuild\mesonmain.py", line 131, in run
    return options.run_func(options)
  File "c:\python37.x64\lib\site-packages\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "c:\python37.x64\lib\site-packages\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "c:\python37.x64\lib\site-packages\mesonbuild\msetup.py", line 192, in _generate
    intr.run()
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreter.py", line 4388, in run
    super().run()
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 441, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 472, in evaluate_statement
    return self.function_call(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 829, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 326, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 212, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreter.py", line 3910, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 482, in evaluate_statement
    return self.evaluate_if(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 563, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 474, in evaluate_statement
    self.assignment(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 1127, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 476, in evaluate_statement
    return self.method_call(cur)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 871, in method_call
    return obj.method_call(method_name, args, self.kwargs_string_keys(kwargs))
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreter.py", line 1813, in method_call
    value = fn(state, args, kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 326, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\interpreterbase.py", line 212, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\modules\gnome.py", line 753, in generate_gir
    self._get_dependencies_flags(deps, state, depends, use_gir_args=True)
  File "c:\python37.x64\lib\site-packages\mesonbuild\modules\gnome.py", line 371, in _get_dependencies_flags
    if use_gir_args and self._gir_has_option('--extra-library'):
  File "c:\python37.x64\lib\site-packages\mesonbuild\modules\gnome.py", line 426, in _gir_has_option
    p, o, e = Popen_safe(exe.get_command() + ['--help'], stderr=subprocess.STDOUT)
  File "c:\python37.x64\lib\site-packages\mesonbuild\mesonlib.py", line 1189, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "c:\python37.x64\lib\site-packages\mesonbuild\mesonlib.py", line 1206, in Popen_safe_legacy
    stdout=stdout, stderr=stderr, **kwargs)
  File "c:\python37.x64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\python37.x64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 不是有效的 Win32 應用程式。
``

``` [WinError 193] %1 不是有效的 Win32 應用程式。``` translates to [WinError 193] %1 is not a valid Win32 Application```

I think in the meanwhile I will roll back to Meson 0.53.0

With blessings, thank you!

**Comment by fanc999** [comment]
Hi,

I tried to look a bit further into this... It seems like we are trying to do the same thing (call ```g-ir-scanner``` directly) when we found GObject-Introspection via pkg-config (lines 409-414 in ```gnome.py```) during the check for the options supported by g-ir-scanner (line 426).  If I put that into a ```try:``` block and if I get an OSError, I try again by replacing exe with self.interpreter.find_program_impl('g-ir-scanner')``` and do ```Popen_safe()``` again with the new ```exe.get_command()```, then the check passes but the generated build.ninja still does not prepend the needed Python interpreter before the ```g-ir-scanner``` command line.

With blessings, thank you!

**Comment by xclaesse** [comment]
Ok, reading the code in ExternalProgram class, I think this is my fault. I modified your patch to pass name and command args to the constructor, but in that case it won't read the shebang and prepend python intrepreter. Giving the proper name gives nicer log messages so I'll see if I can fix ExternalProgram class instead.

**Comment by xclaesse** [comment]
@fanc999 Should be fixed by https://github.com/mesonbuild/meson/pull/7059, can you confirm please?

**Comment by fanc999** [comment]
Hi @xclaesse,

#7059 does indeed fix the issue... I tried using latest master + #7059 and managed to build the latest gtk master on Visual Studio.

With blessings, thank you!
