### ISSUE TITLE
Crash in gnome module when using -Dlayout=flat

### ISSUE THREAD

**Issue by ocrete** [mesonbuild/meson#7133]
It seems that -Dlayout=flat doesn't work with the gnome module.

```
$ meson  build -Dlayout=flat
The Meson build system
Version: 0.54.0
Source dir: /home/tester/collabora/libnice
Build dir: /home/tester/collabora/libnice/build
Build type: native build
Project name: libnice
Project version: 0.1.16.1
C compiler for the host machine: ccache cc (gcc 10.1.1 "cc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)")
C linker for the host machine: cc ld.bfd 2.34-2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "clock_gettime" : YES 
Has header "arpa/inet.h" : YES 
Has header "net/in.h" : NO 
Has header "netdb.h" : YES 
Has header "ifaddrs.h" : YES 
Has header "unistd.h" : YES 
Checking for function "poll" : YES 
Checking for function "getifaddrs" : YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Message: warning level: 1
Message: werror enabled: false
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency gio-2.0 found: YES 2.64.2
Run-time dependency gthread-2.0 found: YES 2.64.2
Message: Crypto librar requested: auto
Run-time dependency gnutls found: YES 3.6.13
Run-time dependency gstreamer-base-1.0 found: YES 1.16.2
Run-time dependency gupnp-igd-1.0 found: YES 0.2.5
Library m found: YES
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Program gen-def.py found: YES (/usr/bin/python3 /home/tester/collabora/libnice/nice/gen-def.py)
Program gen-map.py found: YES (/usr/bin/python3 /home/tester/collabora/libnice/nice/gen-map.py)
Compiler for C supports link arguments -Wl,--version-script,/home/tester/collabora/libnice/nice/libnice.ver: YES 
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 4359, in run
    super().run()
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 441, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 472, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 829, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 326, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 212, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 3881, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 482, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 563, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 466, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 459, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 506, in evaluate_statement
    self.evaluate_plusassign(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 760, in evaluate_plusassign
    addition = self.evaluate_statement(node.value)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 488, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 522, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 1082, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]  # type: T.List[TYPE_nvar]
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 1082, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]  # type: T.List[TYPE_nvar]
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 476, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 871, in method_call
    return obj.method_call(method_name, args, self.kwargs_string_keys(kwargs))
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 1788, in method_call
    value = fn(state, args, kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 326, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/interpreterbase.py", line 212, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/modules/gnome.py", line 790, in generate_gir
    scan_command += ['--filelist=' + self._make_gir_filelist(state, srcdir, ns, nsversion, girtargets, libsources)]
  File "/usr/lib/python3.8/site-packages/mesonbuild/modules/gnome.py", line 608, in _make_gir_filelist
    os.mkdir(gir_filelist_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tester/collabora/libnice/build/meson-out/e186022@@nice@sha'
```

**Comment by dcbaker** [comment]
@jpakkane, flat layout doesn't work in a ton of cases and no one seems to be working on it, can we delete it?

**Comment by jpakkane** [comment]
The main reason it was added was to make Windows development work out of the box because you can't really do rpath on Windows. If nobody is doing that, then we can delete it. But it's hard to know if that is the case.

Maybe deprecate it for one release with warning messages and if nobody complains, then delete it?

**Comment by ocrete** [comment]
I guess if you want to keep it, then you need to add some mode to the unit tests to run everything with it and fix everything...

**Comment by nirbheek** [comment]
> The main reason it was added was to make Windows development work out of the box because you can't really do rpath on Windows

I actually [tried your hack](https://nibblestew.blogspot.com/2019/05/emulating-rpath-on-windows-via-binary.html) a few weeks ago and it worked pretty well. I think we can implement that in Meson and it will work properly.

Alternatively, we could implement a `meson run` subcommand.

**Comment by anonyno** [comment]
a layout=flat bug that is v annoying is #1521.

**Comment by eli-schwartz** [comment]
> The main reason it was added was to make Windows development work out of the box because you can't really do rpath on Windows. If nobody is doing that, then we can delete it. But it's hard to know if that is the case.

We have `meson devenv` now, is that a reasonable alternative to layout=flat? Maybe it is time to drop it?

**Comment by nirbheek** [comment]
Yes, I would support that. It's not even tested on the CI, so it's probably very broken already.

**Comment by xclaesse** [comment]
One possible issue with `meson devenv` is the PATH env variable could easily exceed the max length. The work around that I was envisaging is to copy all libs/exe in a temporary directory while running `meson devenv`. That could even be done by running install with a destdir inside builddir. It would have a startup time penalty, but could be an easy way out.

**Comment by xclaesse** [comment]
In any case, flat layout is not tested and clearly doesn't have enough users to justify the work needed to fix/maintain it. +1 for deprecating/removing it.
