### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#721]
I'm trying to build my project using some CI services, surprisingly meson works on my local system, however fails on the CI. Here's the full log - 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 283, in run
    app.generate()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 166, in generate
    intr.run()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1154, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1176, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1170, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1301, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2402, in evaluate_if
    self.evaluate_codeblock(node.elseblock)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1176, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1170, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1293, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2208, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1291, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2189, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 73, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1374, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1400, in do_subproject
    subi.run()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1154, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1176, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1170, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1291, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2189, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 73, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1497, in func_project
    mlog.log('Project name: ', mlog.bold(args[0]), sep='')
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mlog.py", line 79, in log
    print(*arr, file=log_file, **kwargs) # Log file never gets ANSI codes.
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 0: ordinal not in range(128)
```

Here's the code that fails - https://github.com/agauniyal/isaac-core/tree/feature/uwebsockets

**Comment by agauniyal** [comment]
Both instances of meson (mine and CI's) are same version. Only difference is, mine is installed via pacman while CI one is being installed via python pip3.

**Comment by nirbheek** [comment]
You are most likely hitting locale issues on your CI. If you could investigate that, we can figure out if there's something we can do about it in Meson or if the CI needs to be fixed.

**Comment by agauniyal** [comment]
Okay I'll report back.

**Comment by agauniyal** [comment]
When explicitly setting LC_ALL
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by agauniyal** [comment]
It's definitely an issue with CI, hence I'm closing this issue here.
