### ISSUE TITLE
Cuda depedency (mixed case) failed to parse default_options

### ISSUE THREAD

**Issue by Lagrang3** [mesonbuild/meson#7237]
**Describe the bug**
I have found that meson fails to parse the project files 
for a mixed c++ and cuda compiler project after
I set `default_options` in the `project` function.

**To Reproduce**
The bug is activated with the test case
https://github.com/mesonbuild/meson/tree/master/test%20cases/cuda/12%20cuda%20dependency%20(mixed)
if `default_options: ['optimization=3']` is introduced in the `project` function.

Here's `the meson.build` file:
```
project('cuda dependency', 'cpp', 'cuda',default_options: ['optimization=3'])
exe = executable(
    'prog', 'prog.cpp', 'kernel.cu', 
    dependencies: dependency('cuda', modules: ['cublas']))
test('cudatest', exe)
```

Meson then prints this on screen:
```
The Meson build system
Version: 0.54.2
Source dir: /home/lagrange/CODEBOX/meson/cuda/dependency-mixed
Build dir: /home/lagrange/CODEBOX/meson/cuda/dependency-mixed/build
Build type: native build
Project name: cuda dependency
Project version: undefined
C++ compiler for the host machine: c++ (gcc 8.3.0 "c++ (Debian 8.3.0-6) 8.3.0")
C++ linker for the host machine: c++ ld.bfd 2.31.1
Cuda compiler for the host machine: nvcc (nvcc 9.2.148)
Cuda linker for the host machine: nvcc nvlink 9.2.148
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency CUDA (modules: cudart, cublas) found: YES 9.2 (/usr/local/cuda)
Build targets in project: 1

Found ninja-1.9.0 at /opt/anaconda3/bin/ninja
Traceback (most recent call last):                                                                  
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 322, in generate
    self.generate_target(t)
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 636, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 2131, in generate_single_compile
    commands = self._generate_single_compile(target, compiler, is_generated)
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/ninjabackend.py", line 2065, in _generate_single_compile
    commands += self.generate_basic_compiler_args(target, compiler, no_warn_args)
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/backend/backends.py", line 607, in generate_basic_compiler_args
    commands += compiler.get_buildtype_args(self.get_option_for_target('buildtype', target))
  File "/opt/anaconda3/lib/python3.7/site-packages/mesonbuild/compilers/cuda.py", line 247, in get_buildtype_args
    return cuda_buildtype_args[buildtype] + self._to_host_flags(host_args)
KeyError: 'custom'
```

**Expected behavior**
No error thrown by meson.

**system parameters**
* Is this a [cross build]: no
* what operating system: Debian 10
* what Python version are you using: 3.7.6
* what `meson --version`: 0.54.2
* what `ninja --version`: 1.9.0

**Comment by bonzini** [comment]
Closing as `cuda_buildtype_args` is no more.
