### ISSUE TITLE
Test suite fails with setuptools 49

### ISSUE THREAD

**Issue by heftig** [mesonbuild/meson#7452]
Recently, the test suite started failing on Arch Linux. I've bisected it to the upgrade of python-setuptools from 48.0.0 to 49.0.0.

I suspect https://github.com/pypa/setuptools/issues/2165 is the cause of the failure. The temporary prefix `test_meson_installed` installs to is no longer set up to load site packages.

```
test_meson_installed (__main__.CommandTests) ... zip_safe flag not set; analyzing archive contents...
mesonbuild.__pycache__.environment.cpython-38: module references __file__
mesonbuild.__pycache__.minstall.cpython-38: module references __file__
mesonbuild.cmake.__pycache__.executor.cpython-38: module references __file__
Traceback (most recent call last):
  File "/tmp/tmpl306alxl/prefix/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.55.0', 'console_scripts', 'meson')())
  File "/tmp/tmpl306alxl/prefix/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: meson
```

[:page_with_curl: More log output](https://github.com/mesonbuild/meson/files/4912262/log.txt)

**Comment by heftig** [comment]
Well, this made it pass. Don't know if it would work on any other platform, though.

```diff
diff --git i/mesonbuild/mesonlib.py w/mesonbuild/mesonlib.py
index a43d4c4da..3e7400e22 100644
--- i/mesonbuild/mesonlib.py
+++ w/mesonbuild/mesonlib.py
@@ -1390,7 +1390,7 @@ def _make_tree_writable(topdir: str) -> None:
         os.chmod(d, os.stat(d).st_mode | stat.S_IWRITE | stat.S_IREAD)
         for fname in files:
             fpath = os.path.join(d, fname)
-            if os.path.isfile(fpath):
+            if os.path.isfile(fpath) and not os.path.islink(fpath):
                 os.chmod(fpath, os.stat(fpath).st_mode | stat.S_IWRITE | stat.S_IREAD)
 
 
diff --git i/run_meson_command_tests.py w/run_meson_command_tests.py
index 6ed3d8f8d..0c2cd9699 100755
--- i/run_meson_command_tests.py
+++ w/run_meson_command_tests.py
@@ -124,11 +124,10 @@ class CommandTests(unittest.TestCase):
         pylibdir = prefix / get_pypath()
         bindir = prefix / get_pybindir()
         pylibdir.mkdir(parents=True)
-        # XXX: join with empty name so it always ends with os.sep otherwise
-        # distutils complains that prefix isn't contained in PYTHONPATH
-        os.environ['PYTHONPATH'] = os.path.join(str(pylibdir), '')
+        self._run(python_command + ['-m', 'venv', '--system-site-packages', str(prefix)])
         os.environ['PATH'] = str(bindir) + os.pathsep + os.environ['PATH']
-        self._run(python_command + ['setup.py', 'install', '--prefix', str(prefix)])
+        venv_python = str(bindir / ('Python.exe' if is_windows() else 'python'))
+        self._run([venv_python, 'setup.py', 'install'])
         # Check that all the files were installed correctly
         self.assertTrue(bindir.is_dir())
         self.assertTrue(pylibdir.is_dir())
@@ -162,10 +161,10 @@ class CommandTests(unittest.TestCase):
         stdo = self._run(meson_command + [self.testdir, builddir])
         self.assertMesonCommandIs(stdo.split('\n')[0], resolved_meson_command)
         # Run `python3 -m mesonbuild.mesonmain`
-        resolved_meson_command = python_command + ['-m', 'mesonbuild.mesonmain']
+        resolved_meson_command = [venv_python, '-m', 'mesonbuild.mesonmain']
         builddir = str(self.tmpdir / 'build3')
-        meson_setup = ['-m', 'mesonbuild.mesonmain', 'setup']
-        meson_command = python_command + meson_setup + self.meson_args
+        meson_setup = [venv_python, '-m', 'mesonbuild.mesonmain', 'setup']
+        meson_command = meson_setup + self.meson_args
         stdo = self._run(meson_command + [self.testdir, builddir])
         self.assertMesonCommandIs(stdo.split('\n')[0], resolved_meson_command)
         if is_windows():
```
