### ISSUE TITLE
symbolextractor fails with "permission denied" when linking library to executable (MSYS2)

### ISSUE THREAD

**Issue by jcorks** [mesonbuild/meson#7605]
**Issue**

When specifying both `library` and `executable` targets where the executable target uses `link_with` to link the library target to the executable, the process consistently fails with a python stacktrace similar to the following:
```
[1/2] Generating symbol file 'mylib@sha/libmylib.dll.symbols'
FAILED: mylib@sha/libmylib.dll.symbols
"/usr/bin/meson" --internal symbolextractor "/home/username/mesontest/build" libmylib.dll "libmylib.dll.a" 'mylib@sha/libmylib.dll.symbols'
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.54.3', 'console_scripts', 'meson')()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 219, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 208, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 165, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/symbolextractor.py", line 271, in run
    gen_symbols(libfile, impfile, outfile, options.cross_host)
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/symbolextractor.py", line 239, in gen_symbols
    windows_syms(impfilename, outfilename)
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/symbolextractor.py", line 213, in windows_syms
    result, e = _get_implib_dllname(impfilename)
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/symbolextractor.py", line 170, in _get_implib_dllname
    output, e = call_tool_nowarn(lib + ['-list', impfilename])
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/symbolextractor.py", line 90, in call_tool_nowarn
    p, output, e = Popen_safe(tool, **kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonlib.py", line 1193, in Popen_safe
    p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'lib'
ninja: build stopped: subcommand failed.

```

This seems to only occur if the `link_with` is specified.

This is on Windows with an MSYS2 environment using the latest distributed version of Meson under MSYS2

**To Reproduce**

Here's a small toy example:

Here are 2 C source files, one intended for the library (library.c with library.h declaring an extern function) and one intended for the program containing `main()` (main.c). All sources are contained in the same directory.

library.c:
```
#include <stdio.h>
#include "library.h"

int call_me() {
	printf("Called me!\n");
	return 1;
}
```
library.h:
```
#ifndef H_LIBRARY__INCLUDED
#define H_LIBRARY__INCLUDED

extern int call_me();

#endif
```

main.c:
```
#include "library.h"

int main(int argc, char ** argv) {
	call_me();
	return 0;
}
```

The meson.build file in the same directory looks very similar to what's currently recommended on `mesonbuild.com/Build-targets.html`

meson.build:
```
project(
    'TestProject', 
    'c'
)

lib = library(
    'mylib',
    'library.c'
)

executable(
    'program',
    'main.c',
    link_with : lib
)
```

With all of these within the same directory, running:
```
meson build
cd ./build
meson compile
```
Produces the stack trace first mentioned consistently. Building only the library or only the executable with the library source added to the source list both result in no errors. It only seems to error out from the extra logic related to `link_with`.

**Expected behavior**
To get an output DLL and executable corresponding to the targets specified.

**system parameters**
* Native build under MSYS2 (on and for x86_64, CC is gcc 10.2.0)
* Windows 10
* Python 3.8.5
* Meson --version: 0.54.3
* ninja --version: 1.10.0

**Comment by nirbheek** [comment]
I can't reproduce this. What does `which lib` output for you?
