### ISSUE TITLE
Crash when using meson on existing build generated by older version

### ISSUE THREAD

**Issue by DaanDeMeyer** [mesonbuild/meson#7613]
**Describe the bug**

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1220, in run
    return th.doit()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 975, in doit
    self.run_tests(tests)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1130, in run_tests
    self.drain_futures(futures)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 1146, in drain_futures
    self.process_test_result(result.result())
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 628, in run
    cmd = self._get_cmd()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mtest.py", line 612, in _get_cmd
    elif self.test.cmd_is_built and self.test.needs_exe_wrapper:
AttributeError: 'TestSerialisation' object has no attribute 'cmd_is_built'
```

**To Reproduce**

The issue occurred when running the latest version of meson on an already built version of systemd. After removing the build directory I cannot reproduce the issue anymore. Maybe some issue where the new version of meson can't handle serialized data from older versions?

**Expected behavior**

No crash

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 

Not a cross build

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

Python: 3.8.5
Arch Linux

* what `meson --version`

meson: 0.55.1

* what `ninja --version` if it's a Ninja build

ninja: 1.10.0

**Comment by xclaesse** [comment]
Meson uses python's pickle to store data, so a build dir cannot be reused after meson update. That being said, meson usually detect it's a build from an older version and print an error message saying to reconfigure. Looks like "meson test" subcommand is missing that check.
