### ISSUE TITLE
OSError: [WinError 123] at meson.py execution

### ISSUE THREAD

**Issue by davidowens1998** [mesonbuild/meson#7656]
**Describe the bug**

I execute the command:

`"C:\Users\David Owens\AppData\Local\Programs\Python\Python37\python.exe" meson.py build`

And get the error:

```
git command not found. Using fall-back method to init submodules
The Meson build system
Version: 0.54.999
Source dir: C:\Program Files\SU2-master
Build dir: C:\Program Files\SU2-master\build
Build type: native build
Project name: SU2
Project version: 7.0.6 "Blackbird"
C compiler for the host machine: gcc (gcc 8.1.0 "gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0")
C linker for the host machine: gcc ld.bfd 2.30
C++ compiler for the host machine: c++ (gcc 8.1.0 "c++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (C:\Users\David Owens\AppData\Local\Programs\Python\Python37\python.exe)
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
mpicc found: NO
Run-time dependency MPI for c found: YES
mpic++ found: NO
Run-time dependency MPI for cpp found: NO (tried pkgconfig and config-tool)
Message: Extracting boost ...
Message: -------------------------------------------------------------------------
         |    ___ _   _ ___                                                      |
         |   / __| | | |_  )   Release 7.0.6 "Blackbird"                         |
         |   \__ \ |_| |/ /                                                      |
         |   |___/\___//___|   Meson Configuration Summary                       |
         |                                                                       |
         -------------------------------------------------------------------------

         Option          Value
         ---------------------
         TecIO:          true
         CGNS:           true
         AD (reverse):   false
         AD (forward):   false
         Python Wrapper: false
         Intel-MKL:      false
         OpenBlas:       false
         PaStiX:         false
         Mixed Float:    false

         Please be sure to add the $SU2_HOME and $SU2_RUN environment variables,
         and update your $PATH (and $PYTHONPATH if applicable) with $SU2_RUN

         Based on the input to this configuration, add these lines to your .bashrc file:

         export SU2_RUN=c://bin
         export SU2_HOME=C:\Program Files\SU2-master
         export PATH=$PATH:$SU2_RUN
         export PYTHONPATH=$PYTHONPATH:$SU2_RUN

         Use './ninja -C C:\Program Files\SU2-master\build install' to compile and install SU2

Build targets in project: 12

Found ninja.exe-1.9.0 at "C:\Program Files\SU2-master\ninja.exe"
Traceback (most recent call last):
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\mesonmain.py", line 131, in run
    return options.run_func(options)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\msetup.py", line 215, in _generate
    intr.backend.generate()
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\backend\ninjabackend.py", line 321, in generate
    self.generate_target(t)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\backend\ninjabackend.py", line 641, in generate_target
    elem = self.generate_link(target, outname, obj_list, linker, pch_objects, stdlib_args=stdlib_args)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\backend\ninjabackend.py", line 2571, in generate_link
    dep_targets.extend(self.guess_external_link_dependencies(linker, target, commands, internal))
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\backend\ninjabackend.py", line 2454, in guess_external_link_dependencies
    search_dirs, static_patterns)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\backend\ninjabackend.py", line 2395, in guess_library_absolute_path
    trial = CCompiler._get_file_from_list(self.environment, trial)
  File "C:\Program Files\SU2-master\externals\meson\mesonbuild\compilers\mixins\clike.py", line 922, in _get_file_from_list
    if f.is_file():
  File "C:\Users\David Owens\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1387, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Users\David Owens\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\..\\lib\\gcc\\x86_64-w64-mingw32\\8.1.0\\libC:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x64\\msmpi.a
```
Tried poking around in some of the python scripts files mentioned in the error, but to no avail. It just appears like there's a bug in the processing of the path, but I cannot locate it.

**To Reproduce**

meson.build:

```
project('SU2', 'c', 'cpp',
        version: '7.0.6 "Blackbird"',
        license: 'LGPL2',
        default_options: ['buildtype=release',
                          'warning_level=0',
                          'cpp_std=c++11'])


pymod = import('python')
python = pymod.find_installation()

su2_cpp_args = []
su2_deps     = [declare_dependency(include_directories: 'externals/CLI11')]

if build_machine.system() == 'windows'
  default_warning_flags = []
else
  default_warning_flags = ['-Wno-unused-parameter',
                           '-Wno-empty-body',
                           '-Wno-format-security',
                           '-Wno-deprecated-declarations',
                           '-Wno-non-virtual-dtor']
endif

# meson script path
script_path = meson.source_root() / 'meson_scripts'

# mpi flag
mpi = false

# If custom mpi mode is enabled, include and library pathes for MPI have to be set manually to env variables
if get_option('custom-mpi')
  mpi_dep = []
  mpi = true
# Otherwise they are automatically determined
else
  mpi_dep = [dependency('mpi', language:'c', required : get_option('with-mpi')),
             dependency('mpi', language:'cpp', required : get_option('with-mpi'))]
  if mpi_dep[0].found() or mpi_dep[1].found()
    mpi = true
  endif
endif

# OpenMP
omp = get_option('with-omp')

if omp
  omp_dep = dependency('openmp', language:'cpp')
endif

if get_option('enable-autodiff') or get_option('enable-directdiff')
  codi_dep = [declare_dependency(include_directories: 'externals/codi/include')]
  codi_rev_args = '-DCODI_REVERSE_TYPE'
  codi_for_args = '-DCODI_FORWARD_TYPE'
endif

# add cgns library
if get_option('enable-cgns')
  subdir('externals/cgns')
  su2_deps     += cgns_dep
  su2_cpp_args += '-DHAVE_CGNS'
endif

# check for non-debug build
if get_option('buildtype')!='debug'
  su2_cpp_args += '-DNDEBUG'
endif

# check for mixed precision floating point arithmetic
if get_option('enable-mixedprec')
  su2_cpp_args += '-DUSE_MIXED_PRECISION'
endif

# check if MPI dependencies are found and add them
if mpi

  # add MPI dependency
  su2_deps += mpi_dep
  su2_cpp_args += '-DHAVE_MPI'

  # compile metis
  subdir('externals/metis')

  # add metis dependency
  su2_deps     += metis_dep
  su2_cpp_args += '-DHAVE_METIS'

  # compile parmetis
  subdir('externals/parmetis')

  # add parmetis dependency
  su2_deps     += parmetis_dep
  su2_cpp_args += '-DHAVE_PARMETIS'

  # add medi dependency
  if get_option('enable-autodiff') or get_option('enable-directdiff')
    codi_dep += declare_dependency(include_directories: ['externals/medi/include', 'externals/medi/src'])
  endif
endif

if omp
  # add OpenMP dependency
  su2_deps += omp_dep
endif

if get_option('enable-tecio')
  subdir('externals/tecio')
endif

# PaStiX
if get_option('enable-pastix')
  assert(mpi,
         'PaStiX support requires MPI')
  assert(get_option('enable-mkl') or get_option('enable-openblas'),
         'PaStiX support requires either mkl or openblas')

  su2_cpp_args += '-DHAVE_PASTIX'

  pastix_dep = dependency('pastix', required: false)

  if not pastix_dep.found()
    pastix_root = get_option('pastix_root')+'/install'
    scotch_root = get_option('scotch_root')+'/lib'
    pastix_dep  = declare_dependency(include_directories: pastix_root,
                                    link_args: [ '-L../'+pastix_root, '-L../'+scotch_root,
                                    '-lpastix', '-lscotch', '-lptscotch', '-lptscotcherr',
                                    '-lm', '-lrt', '-lpthread'])
  endif
  su2_deps += pastix_dep
endif

# blas-type dependencies
if get_option('enable-mkl')

  su2_cpp_args += '-DHAVE_MKL'

  # the following mkl name matches the linked libs in manual dependency
  # see https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-and-pkg-config-tool
  # should probably switch to iomp if Intel OpenMP is used
  mkl_dep = dependency('mkl-static-lp64-seq', required: false)

  if not mkl_dep.found()
    mkl_root = get_option('mkl_root')
    mkl_dep = declare_dependency(include_directories: mkl_root+'/include', compile_args: '-m64',
      link_args: ['-L'+mkl_root+'/lib/intel64','-lmkl_intel_lp64','-lmkl_sequential','-lmkl_core','-lpthread','-lm','-ldl'])
  endif
  su2_deps += mkl_dep

elif get_option('enable-openblas')

  su2_cpp_args += '-DHAVE_BLAS'
  su2_cpp_args += '-DHAVE_LAPACK'
  blas_dep = dependency(get_option('blas-name'))
  su2_deps += blas_dep

endif

catch2_dep = declare_dependency(include_directories: 'externals/catch2/')

# compile common library
subdir('Common/src')
# compile SU2_CFD executable
subdir('SU2_CFD/src')
# compile SU2_DOT executable
subdir('SU2_DOT/src')
# compile SU2_DEF executable
subdir('SU2_DEF/src')
# compile SU2_GEO executable
subdir('SU2_GEO/src')
# compile SU2_MSH executable
subdir('SU2_MSH/src')
# compile SU2_SOL executable
subdir('SU2_SOL/src')
# install python scripts
subdir('SU2_PY')
# unit tests
subdir('UnitTests')

if get_option('enable-pywrapper')
  subdir('SU2_PY/pySU2')
endif

message('''-------------------------------------------------------------------------
         |    ___ _   _ ___                                                      |
         |   / __| | | |_  )   Release 7.0.6 "Blackbird"                         |
         |   \__ \ |_| |/ /                                                      |
         |   |___/\___//___|   Meson Configuration Summary                       |
         |                                                                       |
         -------------------------------------------------------------------------
         
         Option          Value
         ---------------------
         TecIO:          @2@
         CGNS:           @3@
         AD (reverse):   @4@
         AD (forward):   @5@
         Python Wrapper: @6@
         Intel-MKL:      @7@
         OpenBlas:       @8@
         PaStiX:         @9@
         Mixed Float:    @10@

         Please be sure to add the $SU2_HOME and $SU2_RUN environment variables,
         and update your $PATH (and $PYTHONPATH if applicable) with $SU2_RUN

         Based on the input to this configuration, add these lines to your .bashrc file:

         export SU2_RUN=@0@
         export SU2_HOME=@1@
         export PATH=$PATH:$SU2_RUN
         export PYTHONPATH=$PYTHONPATH:$SU2_RUN

         Use './ninja -C @11@ install' to compile and install SU2
'''.format(get_option('prefix')+'/bin', meson.source_root(), get_option('enable-tecio'), get_option('enable-cgns'),
           get_option('enable-autodiff'), get_option('enable-directdiff'), get_option('enable-pywrapper'), get_option('enable-mkl'),
           get_option('enable-openblas'), get_option('enable-pastix'), get_option('enable-mixedprec'), meson.build_root().split('/')[-1]))


```

**Expected behavior**
Expect it to successfully execute.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
Native

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10

* what Python version are you using e.g. 3.8.0
3.7.9

* what `meson --version`
7.0.6 "Blackbird"

* what `ninja --version` if it's a Ninja build
1.9.0

**Comment by davidowens1998** [comment]
In ninjabackend.py, line 471 is being run, and the comment suggests this is a known error. Any help/fix appreciated.

![Capture](https://user-images.githubusercontent.com/70112976/91506370-d81bea00-e8c9-11ea-9d9e-41ea56881d66.PNG)

**Comment by nirbheek** [comment]
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\..\\lib\\gcc\\x86_64-w64-mingw32\\8.1.0\\libC:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x64\\msmpi.a

This suggests to me that something somewhere is concatenating the paths instead of using `join_paths()` because it is assuming UNIX-like paths. Most likely it's a bug in the MSMPI dependency detection in `mesonbuild/dependencies/mpi.py:MSMPIDependency`. I think you can try to poke around in there? The link args is what you want to look at.

I would look at what the value of `self.link_args` is, then look at what the value of the `mpi_dep` variable is, then look at how it gets added to the target that consumes `mpi_dep`.

**Comment by davidowens1998** [comment]
So, in that class, this is part of the code, I added the print statement: 

```
incdir = os.environ.get('MSMPI_INC')
        arch = detect_cpu_family(self.env.coredata.compilers.host)
        libdir = None
        if arch == 'x86':
            libdir = os.environ.get('MSMPI_LIB32')
            post = 'x86'
        elif arch == 'x86_64':
            libdir = os.environ.get('MSMPI_LIB64')
            post = 'x64'

        if libdir is None or incdir is None:
            self.is_found = False
            return

        self.is_found = True
        self.link_args = ['-l' + os.path.join(libdir, 'msmpi')]
        self.compile_args = ['-I' + incdir, '-I' + os.path.join(incdir, post)]
        if self.language == 'fortran':
            self.link_args.append('-l' + os.path.join(libdir, 'msmpifec'))
            
        print("self.link_args: ", flush=True)
        print(self.link_args[:], flush=True)
```

When the meson.build is rerun, I get this from my print statement:

```
self.link_args:
['-lC:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x64\\msmpi']
```

which looks bizarre. Can't see any `msi_dep` variable - I understood you as meaning an environment variable, but there was neither that nor a variable in the mentioned class by that name.

**Comment by Adwaitkm** [comment]
https://github.com/mesonbuild/meson/issues/7656#issue-687595698

I'm having the same issue as well. I want to use the adjoint function of SU2 and I'm obtaining the same errors as you are when I try to build SU2 from source. Any fixes found? Or is there an alternate method to build SU2 on windows?
Thanks!

**Comment by davidowens1998** [comment]
No Windows solutions yet. I'm now sorting myself out with a Linux virtual machine and using SU2 through that. I'll let you know if the build works in that.

**Comment by Adwaitkm** [comment]
Tried on Linux as well, didn't seem to work. However, the error message was different on the Linux machine.

**Comment by davidowens1998** [comment]
What was your error? I got a invalid python or missing setuptools, so I installed pip and made sure setuptools was updated. Reran meson and ninja and it worked fine.

**Comment by Adwaitkm** [comment]
I got the same python error but wasn't able to debug that. Linux is kind of new to me. Thanks for your update, I'll try that out and let you know!

**Comment by Adwaitkm** [comment]
I was able to build successfully. Ran a test case with SU2_CFD and it worked fine. However, while trying to run the shape optimization command from tutorial case - 'https://su2code.github.io/tutorials/Inviscid_3D_Constrained_ONERAM6/' I'm getting ' ImportError: No module named numpy'. I know its a pretty common bug but I'm clueless since Linux is completely new to me.
Here's what I've done so far -
-Installed python3 using sudo apt
-Installed MPICH using sudo apt
-Installed pip.'
-Installed numpy and scipy using pip

Apparently linux systems have python inbuilt already? I checked for the version and it had an old one (2.8.x). Hence I updated the system's default python to be the latest version that I installed initially (3.8.2)
I did that by adding the line ' alias python='/usr/bin/python3.8' to my /.bashrc file.

Since my goal is to use SU2 for its shape optimization feature, I'm finding it hard to get my simulation running. Any suggestions?

**Comment by Adwaitkm** [comment]
Fixed the numpy issue by using using the entire path of the shape_optimization.py script. Also specified the python version I wanted to use.

The command -
python3.8 /home/adwait/SU2/SU2_PY/shape_optimization.py -g DISCRETE_ADJOINT -f inv_ONERAM6_adv.cfg 

However, I get a new error now - SU2_PROCESS returned error '1'.

I also tried to run the constrained shape design of 2D Airfoil tutorial ( https://su2code.github.io/tutorials/Turbulent_2D_Constrained_RAE2822/ ), but ran into another error - ' EXCEPTION: unrecognized gradient method' . 

I built and compiled the source code with AD support so I'm not quite sure where I'm going wrong.

**Comment by davidowens1998** [comment]
Yh you'll get those package errors if you have multiple python versions, you have gotta be quite specific sometimes!

As for these new errors, they seem interesting, I'll see if i can replicate them. 

Also quite interested to talk about what you're using SU2's shape optimization tool for - the same reason I'm using SU2, for my masters research project. Perhaps not on here, I set myself up a temp email - send me a message at cohakok956@mailvxin.net and I'll reply from my actual personal email.

**Comment by pwnorbitals** [comment]
(Triage : @davidowens1998, can you still replicate the issue ?)
