### ISSUE TITLE
Crash with CMake subproject containing fortran sources

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/meson#7687]
**Describe the bug**
While configuring a Meson project with a CMake subproject I get this:
```
Build targets in project: 255

PHARE 0.0.1

  Subprojects
    SAMRAI: YES

Found ninja-1.10.1 at /usr/bin/ninja
Traceback (most recent call last):                                                                  
  File "/home/jeandet/Documents/prog/meson/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/home/jeandet/Documents/prog/meson/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/jeandet/Documents/prog/meson/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/jeandet/Documents/prog/meson/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 514, in generate
    self.generate_target(t)
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 832, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 2390, in generate_single_compile
    extra_deps += self.get_fortran_deps(compiler, abs_src, target)
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 2092, in get_fortran_deps
    mod_files = _scan_fortran_file_deps(src, srcdir, dirname, tdeps, compiler)
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 3046, in _scan_fortran_file_deps
    mod_files.extend(_scan_fortran_file_deps(incfile, srcdir, dirname, tdeps, compiler))
  File "/home/jeandet/Documents/prog/meson/mesonbuild/backend/ninjabackend.py", line 3039, in _scan_fortran_file_deps
    with src.open(encoding='ascii', errors='ignore') as f:
  File "/usr/lib64/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jeandet/Documents/prog/PHARE/bc_common.f'
```
Where top project PHARE has no Fortran sources, so this might have leaked form SAMRAI subproject, maybe missing subproject path?

**To Reproduce**

```
git clone -b meson-is-cool https://github.com/jeandet/PHARE
meson PHARE build
```

**system parameters**
* Native build
* Fedora 32
* Python  3.8.5
* Meson 0.55.1 and master
* Ninja 1.10.1

**Comment by scivision** [comment]
Note: SAMRAI has further issues at the m4 generation step. The problem stems from SAMRAI/cmake/SetupM4.cmake I think. This is a separate issue.

```
$ meson compile -C build
Found runner: /usr/bin/ninja
ninja: Entering directory `build'
[1/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen2d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen2d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen2d.f.o -c subprojects/SAMRAI/geom_cartcoarsen2d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[2/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen3d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen3d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen3d.f.o -c subprojects/SAMRAI/geom_cartcoarsen3d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[3/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen1d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen1d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen1d.f.o -c subprojects/SAMRAI/geom_cartcoarsen1d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[4/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen4d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen4d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartcoarsen4d.f.o -c subprojects/SAMRAI/geom_cartcoarsen4d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[5/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine1d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine1d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine1d.f.o -c subprojects/SAMRAI/geom_cartrefine1d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[6/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine2d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine2d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine2d.f.o -c subprojects/SAMRAI/geom_cartrefine2d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[7/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine3d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine3d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_geom.a.p -o subprojects/SAMRAI/libcm_SAMRAI_geom.a.p/meson-generated_.._geom_cartrefine3d.f.o -c subprojects/SAMRAI/geom_cartrefine3d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[8/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen1d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen1d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -o subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen1d.f.o -c subprojects/SAMRAI/pdat_concoarsen1d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[9/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen2d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen2d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -o subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen2d.f.o -c subprojects/SAMRAI/pdat_concoarsen2d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
[10/45] Compiling Fortran object subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen3d.f.o
FAILED: subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen3d.f.o
gfortran -Isubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -Isubprojects/SAMRAI -I../subprojects/SAMRAI -Isubprojects/SAMRAI/__CMake_build/include -I../subprojects/SAMRAI/__CMake_build/include -Isubprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/__CMake_build/lib/fortran -I../subprojects/SAMRAI/source -I../../subprojects/SAMRAI -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -g -fPIC -Jlib/fortran -fPIC -Jsubprojects/SAMRAI/libcm_SAMRAI_pdat.a.p -o subprojects/SAMRAI/libcm_SAMRAI_pdat.a.p/meson-generated_.._pdat_concoarsen3d.f.o -c subprojects/SAMRAI/pdat_concoarsen3d.f
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/include’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../subprojects/SAMRAI/__CMake_build/lib/fortran’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘../../subprojects/SAMRAI’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘lib/fortran’ [-Wmissing-include-dirs]
f951: Fatal Error: gfortran: Only one ‘-J’ option allowed
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by jeandet** [comment]
@scivision yes, your PR seems to fix the config step or at least it doesn't crash anymore. Then I get the same errors during build step. Thank you for your help.
