### ISSUE TITLE
FileNotFoundError when installing mesa

### ISSUE THREAD

**Issue by lrusak** [mesonbuild/meson#7691]
**Describe the bug**

When installing mesa 20.1.7 I get the following error.

EDIT: full log here https://jenkins.kodi.tv/job/LINUX-arm-GBM/5/console

```
08:17:32 [1/2] /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/meson install --no-rebuild
08:17:33 Traceback (most recent call last):
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/site-packages/meson-0.55.1-py3.8.egg/mesonbuild/mesonmain.py", line 131, in run
08:17:33     return options.run_func(options)
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/site-packages/meson-0.55.1-py3.8.egg/mesonbuild/minstall.py", line 542, in run
08:17:33     installer.do_install(datafilename)
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/site-packages/meson-0.55.1-py3.8.egg/mesonbuild/minstall.py", line 365, in do_install
08:17:33     self.install_data(d)
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/site-packages/meson-0.55.1-py3.8.egg/mesonbuild/minstall.py", line 396, in install_data
08:17:33     if self.do_copyfile(fullfilename, outfilename, makedirs=(d.dirmaker, outdir)):
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/site-packages/meson-0.55.1-py3.8.egg/mesonbuild/minstall.py", line 276, in do_copyfile
08:17:33     shutil.copyfile(from_file, to_file)
08:17:33   File "/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python3.8/shutil.py", line 261, in copyfile
08:17:33     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
08:17:33 FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/pkgconfig/egl.pc'
08:17:33 Installing src/mapi/shared-glapi/libglapi.so.0.0.0 to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib
08:17:33 Installing src/mapi/es2api/libGLESv2.so.2.0.0 to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib
08:17:33 Installing src/gbm/libgbm.so.1.0.0 to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib
08:17:33 Installing src/egl/libEGL.so.1.0.0 to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib
08:17:33 Installing src/gallium/targets/dri/libgallium_dri.so to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/dri
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/KHR/khrplatform.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/KHR
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES2/gl2.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES2
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES2/gl2ext.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES2
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES2/gl2platform.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES2
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES3/gl3.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES3
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES3/gl31.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES3
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES3/gl32.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES3
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES3/gl3ext.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES3
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GLES3/gl3platform.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GLES3
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GL/gl.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GL/glcorearb.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GL/glext.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/EGL/egl.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/EGL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/EGL/eglext.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/EGL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/EGL/eglplatform.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/EGL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/EGL/eglmesaext.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/EGL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/EGL/eglextchromium.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/EGL
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/include/GL/internal/dri_interface.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include/GL/internal
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/src/gbm/main/gbm.h to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/include
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/src/util/00-mesa-defaults.conf to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/share/drirc.d
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/build/meson-private/glesv2.pc to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/pkgconfig
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/build/meson-private/dri.pc to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/pkgconfig
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/build/meson-private/gbm.pc to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/pkgconfig
08:17:33 Installing /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/target/mesa/arm-linux-gnueabihf-debug/build/meson-private/egl.pc to /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/arm-linux-gnueabihf-debug/lib/pkgconfig
08:17:33 FAILED: meson-install 
08:17:33 /home/jenkins/workspace/LINUX-arm-GBM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/bin/meson install --no-rebuild
08:17:33 ninja: build stopped: subcommand failed.
```

**system parameters**

This is a cross build. Ubuntu 18.04 cross compiling for arm-linux-gnueabihf
```
$ ./arm-depends/x86_64-linux-gnu-native/bin/python3 --version
Python 3.8.5
```

```
$ ./arm-depends/x86_64-linux-gnu-native/bin/meson --version
0.55.1
```

```
$ ./arm-depends/x86_64-linux-gnu-native/bin/ninja --version
1.9.0
```

CC @dcbaker

**Comment by lrusak** [comment]
I've figured out what's happening and I don't think it's a bug. It's a problem on our end although the error message is a little misleading.

There was a symlink in place for the `egl.pc` that gets created before mesa is built. I guess meson doesn't like this symlink and bails out instead.

```
$ ls -lh arm-depends/arm-linux-gnueabihf-debug/lib/pkgconfig/egl.pc 
lrwxrwxrwx 1 ubuntu ubuntu 45 Sep  3 19:44 arm-depends/arm-linux-gnueabihf-debug/lib/pkgconfig/egl.pc -> /usr/lib/arm-linux-gnueabihf/pkgconfig/egl.pc
```
