### ISSUE TITLE
Issue with "-DVAR=\"STRING\"" compiler flags

### ISSUE THREAD

**Issue by brechtsanders** [mesonbuild/meson#7728]
I have encountered the following issue when compiling several packages with MinGW-w64 on Windows using meson and ninja:
When a string define is passed via command line to the C/C++ compiler with the `-D` flag and the value is in quotes, the flag isn't quoted properly or the quotes are not escaped properly somewhere in Ninja.

My current reproducible case is https://ftp.gnome.org/pub/GNOME/sources/tepl/5.0/tepl-5.0.0.tar.xz

In `meson.build` the following definition is present:
```
add_project_arguments(
  '-DG_LOG_DOMAIN="@0@"'.format(meson.project_name()),
  language: 'c'
)
```

In the generated `build.ninja` this is escaped as follows: `"-DG_LOG_DOMAIN=\"tepl\""`

However in the generated `meson-private/meson_exe_python.exe_a81b490ef1cd2b6c9445bff7fd2f45c28a8a6bfc.dat` this isn't properly escaped: `-DG_LOG_DOMAIN="tepl"`

This results in the following Ninja build output:
```
ninja: Entering directory `build_both'
[59/84] Generating Tepl-5.gir with a meson_exe.py custom command
FAILED: tepl/Tepl-5.gir
"D:/Prog/Python/WinPython64-3.7.4.1Zero/python-3.7.4.amd64/python.exe" "D:/Prog/winlibs64-9.2.0/custombuilt/bin/meson.py" "--internal" "exe" "--unpickle" "R:/winlibs64-9.2.0/tepl-5.0.0/build_both/meson-private/meson_exe_python.exe_a81b490ef1cd2b6c9445bff7fd2f45c28a8a6bfc.dat"
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/gobject/gobject.h: In function 'g_assert_finalize_object':
<command-line>: error: 'tepl' undeclared (first use in this function)
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/glib/gtestutils.h:140:69: note: in expansion of macro 'G_LOG_DOMAIN'
  140 |                                                g_assertion_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, \
      |                                                                     ^~~~~~~~~~~~
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/gobject/gobject.h:786:3: note: in expansion of macro 'g_assert_true'
  786 |   g_assert_true (G_IS_OBJECT (weak_pointer));
      |   ^~~~~~~~~~~~~
<command-line>: note: each undeclared identifier is reported only once for each
function it appears in
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/glib/gtestutils.h:140:69: note: in expansion of macro 'G_LOG_DOMAIN'
  140 |                                                g_assertion_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, \
      |                                                                     ^~~~~~~~~~~~
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/gobject/gobject.h:786:3: note: in expansion of macro 'g_assert_true'
  786 |   g_assert_true (G_IS_OBJECT (weak_pointer));
      |   ^~~~~~~~~~~~~
R:\winlibs64-9.2.0\tepl-5.0.0\build_both\tmp-introspecthy_d3ac_\Tepl-5.c: In function 'escaped_printf':
<command-line>: error: 'tepl' undeclared (first use in this function)
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/glib/gmessages.h:335:32: note: in expansion of macro 'G_LOG_DOMAIN'
  335 | #define g_critical(...) g_log (G_LOG_DOMAIN,         \
      |                                ^~~~~~~~~~~~
R:\winlibs64-9.2.0\tepl-5.0.0\build_both\tmp-introspecthy_d3ac_\Tepl-5.c:61:7: note: in expansion of macro 'g_critical'
   61 |       g_critical ("failed to write to iochannel: %s", error->message);
      |       ^~~~~~~~~~
R:\winlibs64-9.2.0\tepl-5.0.0\build_both\tmp-introspecthy_d3ac_\Tepl-5.c: In function 'goutput_write':
<command-line>: error: 'tepl' undeclared (first use in this function)
D:\Prog\winlibs64-9.2.0\custombuilt\include\glib-2.0/glib/gmessages.h:335:32: note: in expansion of macro 'G_LOG_DOMAIN'
  335 | #define g_critical(...) g_log (G_LOG_DOMAIN,         \
      |                                ^~~~~~~~~~~~
R:\winlibs64-9.2.0\tepl-5.0.0\build_both\tmp-introspecthy_d3ac_\Tepl-5.c:76:7: note: in expansion of macro 'g_critical'
   76 |       g_critical ("failed to write to iochannel: %s", error->message);
      |       ^~~~~~~~~~
Traceback (most recent call last):
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\cygwinccompiler.py", line 170, in _compile
    extra_postargs)
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\ccompiler.py", line 909,
in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'D:\\Prog\\winlibs64-9.2.0\\mingw64\\bin\\gcc.exe' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Prog/winlibs64-9.2.0/custombuilt/bin/g-ir-scanner", line 104, in <module>
    sys.exit(scanner_main(sys.argv))
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\scannermain.py", line 599, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\scannermain.py", line 426, in create_binary
    gdump_parser.get_error_quark_functions())
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\dumper.py", line 290, in compile_introspection_binary
    return dc.run()
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\dumper.py", line 159, in run
    introspection_obj = self._compile(c_path)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\dumper.py", line 188, in _compile
    self._options.init_sections)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\gobject-introspection\giscanner\ccompiler.py", line 315, in compile
    output_dir=os.path.abspath(os.sep))
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\ccompiler.py", line 574,
in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "R:\winlibs64-9.2.0\tepl-5.0.0\winfix\distutils\cygwinccompiler.py", line 172, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'D:\\Prog\\winlibs64-9.2.0\\mingw64\\bin\\gcc.exe' failed with exit status 1
ninja: build stopped: subcommand failed.
```

The compiler error is caused by the compiler define not being quoted.

So I believe there is a bug in the code that generates `meson-private/meson_exe_python.exe_a81b490ef1cd2b6c9445bff7fd2f45c28a8a6bfc.dat` that causes the quotes not to be scaped.

**Comment by brechtsanders** [comment]
Any news on this issue?
If `ninja.build` contains something like `ARGS = "-DG_LOG_DOMAIN=\"tepl\""`, what should it be changed to to make it work? The goal is that the C compiler sees `G_LOG_DOMAIN` as a quoted string.

**Comment by brechtsanders** [comment]
I found a workaround:
```
patch -ulbf meson.build << EOF
@@ -72,5 +72,5 @@
 add_project_arguments(
-  '-DG_LOG_DOMAIN="@0@"'.format(meson.project_name()),
   language: 'c'
 )
+cargs = ['-DG_LOG_DOMAIN="@0@"'.format(meson.project_name())]

EOF
```
What is the reason this workaround works?
