### ISSUE TITLE
Windows ninja install cannot find .lib file

### ISSUE THREAD

**Issue by mgautierfr** [mesonbuild/meson#7838]
**Describe the bug**
On a Windows, building shared library, `ninja install` fails because meson cannot find `.lib` file.
```
C:\Users\mgautier\pugibuild>ninja install
[0/1] Installing files.
Installing pugixml.dll to C:\Users\mgautier\FOO\bin
Traceback (most recent call last):
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\mesonmain.py", line 140, in run
    return options.run_func(options)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 544, in run
    installer.do_install(datafilename)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 362, in do_install
    self.install_targets(d)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 458, in install_targets
    raise RuntimeError('File {!r} could not be found'.format(t.fname))
RuntimeError: File 'pugixml.lib' could not be found
FAILED: meson-install
"C:\Users\mgautier\.virtualenvs\kbuild\Scripts\meson" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```

**To Reproduce**
I'm try to build pugixml library with meson on Windows.
The pugixml sources are taken from here : http://github.com/zeux/pugixml/releases/download/v1.10/pugixml-1.10.tar.gz
And the meson.build file is simply :

```
project('pugixml', 'cpp')

install_headers(['src/pugixml.hpp', 'src/pugiconfig.hpp'])
pugixml = library('pugixml',
                  ['src/pugixml.cpp'],
                  install:true)

pkg_mod = import('pkgconfig')
pkg_mod.generate(libraries : pugixml,
                 version : '1.10',
                 name : 'libpugixml',
                 description : 'pugixml',
                 filebase : 'pugixml')
```

I've install Visual Studio Community 2019 and load the environment (launched C:/Program File (x86)/Microsoft visual Studio/2019/Community/VC/Auxilary/Build/vcvars64.bat).
Also installed ninja using chocolatey.

Then:
```
C:\Users\mgautier>meson --prefix C:\Users\mgautier\FOO pugixml-1.10 pugibuild
The Meson build system
Version: 0.55.3
Source dir: C:\Users\mgautier\WORKING_DIR\SOURCE\pugixml-1.2
Build dir: C:\Users\mgautier\pugibuild
Build type: native build
Project name: pugixml
Project version: undefined
C++ compiler for the host machine: cl (msvc 19.27.29112)
C++ linker for the host machine: link link 14.27.29112.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.1 at C:\ProgramData\chocolatey\bin\ninja.EXE

C:\Users\mgautier>cd pugibuild

C:\Users\mgautier\pugibuild>ninja
[2/2] Linking target pugixml.dll

C:\Users\mgautier\pugibuild>ninja install
[0/1] Installing files.
Installing pugixml.dll to C:\Users\mgautier\FOO\bin
Traceback (most recent call last):
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\mesonmain.py", line 140, in run
    return options.run_func(options)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 544, in run
    installer.do_install(datafilename)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 362, in do_install
    self.install_targets(d)
  File "c:\users\mgautier\.virtualenvs\kbuild\lib\site-packages\mesonbuild\minstall.py", line 458, in install_targets
    raise RuntimeError('File {!r} could not be found'.format(t.fname))
RuntimeError: File 'pugixml.lib' could not be found
FAILED: meson-install
"C:\Users\mgautier\.virtualenvs\kbuild\Scripts\meson" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.

C:\Users\mgautier\pugibuild>
```

**Expected behavior**
Install target should work.
Either not trying to install `.lib` file or either having compilation step generate it.

**system parameters**
* Plain native build.
* Windows 10
* Python 3.9.0
* what `meson --version`  : 0.55.3
* what `ninja --version` : 1.10.1

**Comment by mgautierfr** [comment]
A small up :)

Do you have a idea of what is going wrong here ?

**Comment by mateus558** [comment]
I'm also having the same problem, does someone have any idea if it's a bug?

**Comment by dcbaker** [comment]
It certainly looks like a bug.

**Comment by dcbaker** [comment]
Does the .lib file that Meson is expecting exist?

**Comment by mateus558** [comment]
I've found what's causing this. I could generate the .lib file adding this to the beginning of my header definition:

```cpp
#pragma once
#if defined _WIN32 || defined __CYGWIN__
  #ifdef BUILDING_LIBSAMPLE
    #define LIBSAMPLE_PUBLIC __declspec(dllexport)
  #else
    #define LIBSAMPLE_PUBLIC __declspec(dllimport)
  #endif
#else
  #ifdef BUILDING_LIBSAMPLE
      #define LIBSAMPLE_PUBLIC __attribute__ ((visibility ("default")))
  #else
      #define LIBSAMPLE_PUBLIC
  #endif
#endif
```
Defining my class like that:
```cpp
class LIBSAMPLE_PUBLIC Libsample {

public:
  ...
private:
...
};
```

And defining my library target like that:
```cpp
lib_args = ['-DBUILDING_LIBSAMPLE']

shlib = shared_library('libsample', 'libsample.cpp',
  install : true,
  cpp_args : lib_args,
  gnu_symbol_visibility : 'hidden',
)
```

Just like the library template that Meson provides. But I still have a doubt, why is all this necessary to generate the .lib file? 

There isn't a better way to do that on windows without writing more code to my library's headers?

I'm trying to adapt a library I'm programming to windows, but this is cumbersome. :cry:

**Comment by dcbaker** [comment]
That's not Meson's doing, that's MSVC. Windows is completely the opposite on Unix, all symbols are hidden unless marked otherwise, basically assume that MSVC works like adding `-fvisibility=hidden` by default. Your other option is to add a `.def` file to declare the public functions from your library.

**Comment by mateus558** [comment]
Thanks, I'll try to do that.

**Comment by kelson42** [comment]
@mateus558 Any news?

**Comment by randydu** [comment]
You have to export something (function, class, variable, etc.) from a *.DLL otherwise the *.Lib file won't be created by the compiler. Export nothing from a windows DLL does not make sense because the internal apis implemented in the DLL are invisible and cannot be accessed from outside.

To export a function "void my_api()":

```c
void
#ifdef _WIN32
__declspec(dllexport)
#endif 
my_api()
{
}
```

You can also create a *.DEF file in your project and pass it to the MSVC linker via "/DEF" link_args.

**Comment by mgautierfr** [comment]
It seems it is not a bug in meson but it our code.

Except a potential better error message (or a warning from meson) I think you can close this issue.

**Comment by doraeric** [comment]
Just encounter this issue. I think it's related to #2132 .
