### ISSUE TITLE
can't install meson no matter: Exception error

### ISSUE THREAD

**Issue by littleIdiotperson** [mesonbuild/meson#7885]
Already have ninja and python updated but no matter what I do this error appeared

 python3 -m pip install mesonCollecting meson
  Using cached meson-0.55.3.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 160, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/pip-build-env-llwu2xp9/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/tmp/pip-build-env-llwu2xp9/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 32, in <module>
    from setuptools import windows_support
  File "/tmp/pip-build-env-llwu2xp9/overlay/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

uninstalled meson and reinstalled didn't help

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
I don't know what that mean
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Linux Mint 19.3 32 bit version x86
* what Python version are you using e.g. 3.8.0
python3 : 3.9.0
* what `meson --version`
0.45.1 trying to update to get scrcpy to work
* what `ninja --version` if it's a Ninja build
1.10.0.git.kitware.jobserver-1

**Comment by dcbaker** [comment]
A little googling suggests that `apt install libffi-dev` might fix the problem

**Comment by littleIdiotperson** [comment]
> A little googling suggests that `apt install libffi-dev` might fix the problem

already tried it before posting but still didn't work.. ,
 apt install libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-8).
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-48-generic linux-hwe-5.4-headers-5.4.0-48
  linux-image-5.4.0-48-generic linux-modules-5.4.0-48-generic
  linux-modules-extra-5.4.0-48-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by littleIdiotperson** [comment]
STILL NO ANSWER???

**Comment by dcbaker** [comment]
It's not a problem with meson per se, is something about your setup. Did you build python from source?

**Comment by littleIdiotperson** [comment]
> It's not a problem with meson per se, is something about your setup. Did you build python from source? If your did, did you have ffi-dev when you compiled python? The next guess would be that you're python doesn't have ffi support.
> 
> Also, please chill. We're all volunteers here, answering questions on our own time, not paid professional support.

First. Excuse me for yelling. I actually don't know if I have compiled python without "ffi-dev" I'm pretty sure I used the original one from python site to build Python3. but I have also python (not 3 here ) with version 2.7.17 can that be a problem by any means ? also. I'm clueless since  only started using Linux a week ago. Thank You

**Comment by eli-schwartz** [comment]
> I'm pretty sure I used the original one from python site to build Python3.

I would recommend you install the python3 package from your distro directly rather than compiling it yourself as the latter can be very complicated to do while ensuring all features are actually enabled.

e.g. on Debian, `apt install python3 python3-pip`

This works fine in the general sense as long as python itself is correctly built.
