### ISSUE TITLE
dependency('xyzzy', required: false, include_type: 'system') crashes meson 0.56.0, python 3.6

### ISSUE THREAD

**Issue by borg323** [mesonbuild/meson#7920]
**Describe the bug**
`xyzzy = dependency('xyzzy', required: false, include_type: 'system')` crashes meson.

**To Reproduce**
```
project('foo', 'cpp')

xyzzy = dependency('xyzzy', required: false, include_type: 'system')
```

**Expected behavior**
Clean exit

**system parameters**
* plain native build (for the same computer)
* Ubuntu 16.04, but also reported on other linux versions and windows
* Python version 3.5.1 but also reported with 3.6
* meson 0.56.0

**Comment by borg323** [comment]
An example on windows: <https://ci.appveyor.com/project/LeelaChessZero/lc0/builds/36058219/job/8hmig6upn7dx3g5d#L109>

**Comment by eli-schwartz** [comment]
Not reproducible for me on Arch Linux + meson 0.56.2

**Comment by drmoose** [comment]
@eli-schwartz Arch's Python is too new (3.9.1 at time of writing). You need <= 3.6

**Comment by eli-schwartz** [comment]
That information could be better highlighted in the description...

**Comment by drmoose** [comment]
If it helps, here's a Dockerfile that reproduces the issue:

```Dockerfile
FROM ubuntu:bionic

RUN set -xe ;\
    apt-get update ;\
    apt-get install -yqq python3-pip pkg-config curl ;\
    rm -rf /var/lib/apt/lists ;\
    pip3 install ninja meson ;\
    mkdir -p /src/subprojects ; cd /src ;\
    echo "project('foo', 'cpp')" > meson.build ;\
    echo >> meson.build ;\
    echo "dependency('spdlog', required: false, include_type: 'system')" >> meson.build ;\
    curl -o subprojects/spdlog.wrap https://wrapdb.mesonbuild.com/v1/projects/spdlog/1.8.2/1/get_wrap

WORKDIR /src

CMD ["bash", "-c", "meson $(mktemp -d)"]
```

**Comment by jpakkane** [comment]
I did the same with debootstrap rather than Docker and it worked:

```
Version: 0.56.99
Source dir: /home/jpakkane/meson/deptest
Build dir: /home/jpakkane/meson/build
Build type: native build
Project name: foo
Project version: undefined
C++ compiler for the host machine: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xyzzy found: NO (tried pkgconfig and cmake)
Build targets in project: 0

Found ninja-1.8.2 at /usr/bin/ninja
jpakkane@jonnebox:~/meson$ python3 --version
Python 3.6.5
jpakkane@jonnebox:~/meson$ cat deptest/meson.build 
project('foo', 'cpp')

xyzzy = dependency('xyzzy', required: false, include_type: 'system')
```

Is the error message the same for you as the one listed above?

**Comment by drmoose** [comment]
The crash only occurs if the dependency is found.

The error that appears in the Dockerfile I supplied, in the OP @borg323's AppVeyor report and in the linked issue #7971 is `TypeError: cannot deepcopy this pattern object`.

It's not reproducing for @jpakkane above because `Run-time dependency xyzzy found: NO`. I don't have a `xyzzy` package either, which is why my Dockerfile uses "spdlog" from wrapdb instead.

**Comment by jpakkane** [comment]
With that I got it reproduced. However the following change _fixes the issue_.

```
diff --git a/mesonbuild/dependencies/base.py b/mesonbuild/dependencies/base.py
index 3a5f5f810..35021cc03 100644
--- a/mesonbuild/dependencies/base.py
+++ b/mesonbuild/dependencies/base.py
@@ -232,6 +232,7 @@ class Dependency:
         raise DependencyException('No default provided for dependency {!r}, which is not pkg-config, cmake, or config-tool based.'.format(self))
 
     def generate_system_dependency(self, include_type: str) -> T.Type['Dependency']:
+        print(self)
         new_dep = copy.deepcopy(self)
         new_dep.include_type = self._process_include_type_kw({'include_type': include_type})
         return new_dep
```

Can someone else verify? This does not make any sense.

**Comment by borg323** [comment]
In my case it triggered when the dependency was **NOT** found, both locally (with ancient python) and on appveyor with python 3.6, and it does not trigger when the dependency is found (at least locally).

**Comment by jpakkane** [comment]
@borg323 can you test my patch from above?

**Comment by drmoose** [comment]
That `print` patch does not solve the problem in my docker environment. It prints `<NotFoundDependency not-found: False>`. And it gets even more confusing: if I change the `dependency()` call back to `xyzzy` it _still_ reproduces in my Python 3.6 docker environment.

[Heisenbug?](https://en.wikipedia.org/wiki/Heisenbug)

**Comment by drmoose** [comment]
The trigger seems to be _having any valid wrap file in `subprojects`_

Using @borg323's exact `meson.build` file:

```
$ meson $(mktemp -d)
The Meson build system
Version: 0.56.99
Source dir: /tmp/src
Build dir: /tmp/tmp.YRkIe2nC4G
Build type: native build
Project name: foo
Project version: undefined
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xyzzy found: NO (tried pkgconfig and cmake)
<class 'mesonbuild.dependencies.base.NotFoundDependency'> <NotFoundDependency not-found: False>
Build targets in project: 0

Found ninja-1.10.0.git.kitware.jobserver-1 at /usr/local/bin/ninja
$ curl -o subprojects/spdlog.wrap https://wrapdb.mesonbuild.com/v1/projects/spdlog/1.8.2/1/get_wrap
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   444  100   444    0     0    891      0 --:--:-- --:--:-- --:--:--   893
$ meson $(mktemp -d)
Traceback (most recent call last):
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 132, in run
    return options.run_func(options)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 275, in run
    app.generate()
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 183, in generate
    self._generate(env)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 222, in _generate
    intr.run()
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 4764, in run
    super().run()
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 519, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 544, in evaluate_codeblock
    raise e
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 537, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 550, in evaluate_statement
    return self.function_call(cur)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 909, in function_call
    return func(node, func_args, kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 393, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 393, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 393, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 4 more times]
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 209, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3752, in func_dependency
    d = d.as_system_method([wanted], {})
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 301, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 527, in as_system_method
    new_dep = self.held_object.generate_system_dependency(new_is_system)
  File "/tmp/home/.local/lib/python3.6/site-packages/mesonbuild/dependencies/base.py", line 238, in generate_system_dependency
    new_dep = copy.deepcopy(self)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
The Meson build system
Version: 0.56.99
Source dir: /tmp/src
Build dir: /tmp/tmp.IcvrQkbYgD
Build type: native build
Project name: foo
Project version: undefined
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xyzzy found: NO (tried pkgconfig and cmake)
<class 'mesonbuild.dependencies.base.NotFoundDependency'> <NotFoundDependency not-found: False>
```

**Comment by drmoose** [comment]
Investigating further, I wrote a hacky little patch to figure out where the pattern object that can't be deep-copied lives:

```diff
diff --git a/mesonbuild/dependencies/base.py b/mesonbuild/dependencies/base.py
index e72f34693..d50efb6c1 100644
--- a/mesonbuild/dependencies/base.py
+++ b/mesonbuild/dependencies/base.py
@@ -28,6 +28,7 @@ import platform
 import typing as T
 from enum import Enum
 from pathlib import Path, PurePath
+from pprint import pprint
 
 from .. import mlog
 from .. import mesonlib
@@ -234,10 +235,25 @@ class Dependency:
         raise DependencyException('No default provided for dependency {!r}, which is not pkg-config, cmake, or config-tool based.'.format(self))
 
     def generate_system_dependency(self, include_type: str) -> T.Type['Dependency']:
+        can_deepcopy(self, set())
         new_dep = copy.deepcopy(self)
         new_dep.include_type = self._process_include_type_kw({'include_type': include_type})
         return new_dep
 
+def can_deepcopy(thing, closed):
+    if id(thing) in closed:
+        return True
+    closed.add(id(thing))
+    try:
+        copy.deepcopy(thing)
+        return True
+    except:
+        pprint({k: v
+               for k, v in getattr(thing, '__dict__', thing).items()
+               if isinstance(v, type(re.compile(''))) or \
+                  not can_deepcopy(v, closed)})
+        return False
+
 class InternalDependency(Dependency):
     def __init__(self, version, incdirs, compile_args, link_args, libraries,
                  whole_libraries, sources, ext_deps, variables: T.Dict[str, T.Any]):

```

and the answer seems to be in Python 3.6's `ConfigParser` implementation:

```python
{'_converters': <configparser.ConverterMapping object at 0x7f43544a5780>,
 '_optcre': re.compile('\n        (?P<option>.*?)                    # very permissive!\n        \\s*(?P<vi>=|:)\\s*              # any number of space/tab,\n                                           # followed by any of t, re.VERBOSE),
 '_proxies': OrderedDict([('DEFAULT', <Section: DEFAULT>),
                          ('wrap-file', <Section: wrap-file>),
                          ('provide', <Section: provide>)])}
{'config': <configparser.ConfigParser object at 0x7f43544a5518>}
{'spdlog': <mesonbuild.wrap.wrap.PackageDefinition object at 0x7f43544a54e0>}
{}
{'provided_deps': {'spdlog': <mesonbuild.wrap.wrap.PackageDefinition object at 0x7f43544a54e0>},
 'wraps': {'spdlog': <mesonbuild.wrap.wrap.PackageDefinition object at 0x7f43544a54e0>}}
{'wrap_resolver': <mesonbuild.wrap.wrap.Resolver object at 0x7f43544a5160>}
{'env': <mesonbuild.environment.Environment object at 0x7f43544a5c88>}
```

**Comment by jpakkane** [comment]
I also looked it up and it resides in the `env` variable. The following makes the problem go away:

```
diff --git a/mesonbuild/dependencies/base.py b/mesonbuild/dependencies/base.py
index 3a5f5f810..f4437b0e5 100644
--- a/mesonbuild/dependencies/base.py
+++ b/mesonbuild/dependencies/base.py
@@ -232,7 +232,11 @@ class Dependency:
         raise DependencyException('No default provided for dependency {!r}, which is not pkg-config, cmake, or config-tool based.'.format(self))
 
     def generate_system_dependency(self, include_type: str) -> T.Type['Dependency']:
+        e = self.env
+        self.env = None
         new_dep = copy.deepcopy(self)
+        new_dep.env = e
+        self.env = e
         new_dep.include_type = self._process_include_type_kw({'include_type': include_type})
         return new_dep
```

But it does not seem like a proper fix.

**Comment by drmoose** [comment]
Additional sidenote: the reason this problem is limited to pythons 3.6 and below is that in the 3.7 release notes [Python made `re` objects copyable](https://docs.python.org/3/whatsnew/3.7.html#re)

**Comment by drmoose** [comment]
I could be wrong, but it looks like the [`PackageDefinition.config`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/wrap/wrap.py#L117), the member variable causing the problem, doesn't need to be a member variable.  It seems to only ever be consumed by `parse_wrap_section` and `parse_provide_section` on the same class, which in turn are only ever called by `parse_wrap` itself.

This patch, then, solves the problem in this ticket, but I'm nowhere near confident enough to suggest it won't break anything else:

```diff
diff --git a/mesonbuild/wrap/wrap.py b/mesonbuild/wrap/wrap.py
index bb153c55c..fb02b7096 100644
--- a/mesonbuild/wrap/wrap.py
+++ b/mesonbuild/wrap/wrap.py
@@ -114,11 +114,11 @@ class PackageDefinition:
 
     def parse_wrap(self) -> None:
         try:
-            self.config = configparser.ConfigParser(interpolation=None)
-            self.config.read(self.filename)
+            config = configparser.ConfigParser(interpolation=None)
+            config.read(self.filename)
         except configparser.Error as e:
             raise WrapException('Failed to parse {}: {}'.format(self.basename, str(e)))
-        self.parse_wrap_section()
+        self._parse_wrap_section(config)
         if self.type == 'redirect':
             # [wrap-redirect] have a `filename` value pointing to the real wrap
             # file we should parse instead. It must be relative to the current
@@ -140,21 +140,21 @@ class PackageDefinition:
             self.filename = str(fname)
             self.parse_wrap()
             return
-        self.parse_provide_section()
+        self._parse_provide_section(config)
 
-    def parse_wrap_section(self) -> None:
-        if len(self.config.sections()) < 1:
+    def _parse_wrap_section(self, config: configparser.ConfigParser) -> None:
+        if len(config.sections()) < 1:
             raise WrapException('Missing sections in {}'.format(self.basename))
-        self.wrap_section = self.config.sections()[0]
+        self.wrap_section = config.sections()[0]
         if not self.wrap_section.startswith('wrap-'):
             m = '{!r} is not a valid first section in {}'
             raise WrapException(m.format(self.wrap_section, self.basename))
         self.type = self.wrap_section[5:]
-        self.values = dict(self.config[self.wrap_section])
+        self.values = dict(config[self.wrap_section])
 
-    def parse_provide_section(self) -> None:
-        if self.config.has_section('provide'):
-            for k, v in self.config['provide'].items():
+    def _parse_provide_section(self, config: configparser.ConfigParser) -> None:
+        if config.has_section('provide'):
+            for k, v in config['provide'].items():
                 if k == 'dependency_names':
                     # A comma separated list of dependency names that does not
                     # need a variable name

```
