### ISSUE TITLE
Detailed coverage is broken with Vala

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#799]
It seems like `gcov` cannot locate generated C sources correctly.

```
[1/1] Generating HTML coverage report.
FAILED: coverage-html 
'gcovr' '--html' '--html-details' '-r' '/home/guillaume/Projets/valum' '-o' '/home/guillaume/Projets/valum/build/meson-logs/coverage.html'
Traceback (most recent call last):
  File "/home/guillaume/.local/bin/gcovr", line 1970, in <module>
    print_html_report(covdata, options.html_details)
  File "/home/guillaume/.local/bin/gcovr", line 1473, in print_html_report
    INPUT = open(data['FILENAME'], 'r')
IOError: [Errno 2] No such file or directory: 'build/auth-test.c'
ninja: build stopped: subcommand failed.
```

**Comment by lcallarec** [comment]
Same issue for me. As shown in this [example repo](https://github.com/lcallarec/vala-meson-flatpak-example), `ninja coverage-text` can't bind generated c files with vala sources. 

I'll be happy to dig into meson sources to fix this issue, any help will be appreciated to support me in that task...

**Comment by mdegans** [comment]
Same issue here.
```text
 $ meson .. -Db_coverage=true
The Meson build system
Version: 0.55.0
Source dir: /home/anzu/Projects/columbia
Build dir: /home/anzu/Projects/columbia/builddir
Build type: native build
Project name: Columbia
Project version: 0.1.0
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
Vala compiler for the host machine: valac (valac 0.48.6)
Host machine cpu family: aarch64
Host machine cpu: aarch64
Library posix found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gstreamer-1.0 found: YES 1.14.5
Run-time dependency libosinfo-1.0 found: YES 1.1.0
Run-time dependency gio-unix-2.0 found: YES 2.56.4
Run-time dependency gio-2.0 found: YES 2.56.4
Configuring config.vala using configuration
Program g-ir-compiler found: YES
Build targets in project: 7

Found ninja-1.8.2 at /usr/bin/ninja
Traceback (most recent call last):
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 518, in generate
    self.generate_coverage_rules()
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 991, in generate_coverage_rules
    self.generate_coverage_command(e, [])
  File "/home/anzu/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 975, in generate_coverage_command
    for compiler in target.compilers.values():
AttributeError: 'CustomTarget' object has no attribute 'compilers'
````

If I comment out the custom target, it builds:

```meson
g_ir_compiler = find_program('g-ir-compiler', required: false)
if g_ir_compiler.found()
# the meson docs are incorrect on this
# https://github.com/mesonbuild/meson/issues/2296#issuecomment-328882589
  custom_target('libcolumbia typelib',
    command: [
      g_ir_compiler,
      '--output', '@OUTPUT@',
      meson.current_build_dir() / libcolumbia_gir
    ],
    depends: libcolumbia,
    output: libcolumbia_typelib,
    install: true,
    install_dir: get_option('libdir') / 'girepository-1.0',
  )
else
  message('not building typelib language bindings')
endif
```

Before I upgraded, with meson 0.54.0 (i _think_), it was generating coverage, but only for one of the .c files generated by valac.

**Comment by cxw42** [comment]
> Also the generated files don't point to the actual .vala source, but to the .c code (while .c files includes #line directives properly).

If you run `valac -g`, you will get `#line` directives pointing into the vala source, for generated lines that directly map to `.vala` lines.  The coverage data will be a mix of `.vala` and `.c` files, but it works reasonably well in my experience.
