### ISSUE TITLE
Release a new version, could be based on patch

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#802]
My CI builds are breaking again too many times for the same error - `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`. I reckon you had fixed that error somehow but there hasn't been a new release since. Could you possibly release a new version on pip(that's where we install meson from) with a patch upgrade `0.34.1` if you're not thinking of releasing a major version soon.

```
export WERCKER_STEP_ROOT="/pipeline/script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f"
export WERCKER_STEP_ID="script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f/artifacts"
source "/pipeline/script-64f7cee4-ebc9-4f4e-8f38-ab334c909e1f/run.sh" < /dev/null
Cloning into 'uWebSockets'...
The Meson build system
Version: 0.34.0
Source dir: /pipeline/source
Build dir: /pipeline/source/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: isaac-core
Native cpp compiler: c++ (clang 3.8.0-2ubuntu4)
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)

Executing subproject uWS.

Project name: uWebSockets
Native cpp compiler: c++ (clang 3.8.0-2ubuntu4)
Native dependency zlib found: YES 1.2.8
Native dependency openssl found: YES 1.0.2g
Native dependency libuv found: YES 1.8.0
Build targets in project: 3

Subproject uWS finished.
Found a fallback subproject subprojects/uWS for uWS
Dowloading json from https://github.com/nlohmann/json/archive/v2.0.3.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 282, in run
    app.generate()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/mesonmain.py", line 167, in generate
    intr.run()
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1186, in run
    self.evaluate_codeblock(self.ast)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1208, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1202, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1325, in evaluate_statement
    return self.assignment(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2253, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1323, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 2240, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 73, in wrapped
    return f(self, node, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1408, in func_subproject
    return self.do_subproject(dirname, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/interpreter.py", line 1422, in do_subproject
    resolved = r.resolve(dirname)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/wrap/wrap.py", line 104, in resolve
    self.download(p, packagename)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/wrap/wrap.py", line 176, in download
    srcdata = self.get_data(srcurl)
  File "/usr/local/lib/python3.5/dist-packages/mesonbuild/wrap/wrap.py", line 142, in get_data
    dlsize = int(resp.info()['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by jpakkane** [comment]
We do releases roughly once a month so the next one should come soon.
