### ISSUE TITLE
Cannot pass a configure_file() in a custom_target() command

### ISSUE THREAD

**Issue by spanezz** [mesonbuild/meson#8039]
**Describe the bug**

When I try to pass a `configure_file()` object as a `command:` element on a `custom_target()`, I get an exception.

**To Reproduce**

If I do something like this:
```
help2man = find_program('help2man')
run_local = configure_file(output: 'run-local', input: 'run-local.in', configuration: {…})
custom_target('script.1', input: [script], output: script + '.1',
                  command: [run_local, help2man, '@INPUT0@'],
                  capture: true,
                  install: true,
                  install_dir: get_option('mandir') / 'man1')
```

I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate(intr)
  File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 314, in generate
    self.generate_target(t)
  File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 476, in generate_target
    self.generate_custom_target(target)
  File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 695, in generate_custom_target
    cmd = self.replace_paths(target, cmd)
  File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 1746, in replace_paths
    for x in args]
  File "/usr/lib/python3/dist-packages/mesonbuild/backend/ninjabackend.py", line 1746, in <listcomp>
    for x in args]
AttributeError: 'File' object has no attribute 'replace'
```

**Expected behavior**

I would have expected the configure_file output to expand with its full path in the command array.

**Workaround**

I can work around this issue by wrapping the `configure_file()` with `find_program()`. This would work:

```
help2man = find_program('help2man')
run_local_cfg = configure_file(output: 'run-local', input: 'run-local.in', configuration: {…})
run_local = find_program(run_local_cfg)
custom_target('script.1', input: [script], output: script + '.1',
                  command: [run_local, help2man, '@INPUT0@'],
                  capture: true,
                  install: true,
                  install_dir: get_option('mandir') / 'man1')
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? **Plain native**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) **Debian buster + backports**
* what Python version are you using e.g. 3.8.0 **Python 3.7.3**
* what `meson --version` **0.52.1**
* what `ninja --version` if it's a Ninja build **1.8.2**

**Comment by bonzini** [comment]
Fixed by commit f63e168685c22a749502161355a7ea98a6c5344a
