### ISSUE TITLE
Failure when using CustomTarget with a Rust executable

### ISSUE THREAD

**Issue by cmarcelo** [mesonbuild/meson#8157]
**Describe the bug**

Using a CustomTarget as the only source of a Rust executable makes meson fail.

**To Reproduce**

The self-contained `meson.build` is:

```
project('proj', 'rust')

main_rs = custom_target(
  'main_rs',
  output: 'main.rs',
  capture: true,
  command: ['echo',
            'fn main() { println!("hi") }'
	   ],
)

executable('main', [main_rs])
```

Then fails at `meson build` with the following stack trace:

```
Found ninja-1.10.2 at /usr/bin/ninja
Traceback (most recent call last):                                                                  
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 223, in _generate
    intr.backend.generate()
  File "/usr/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 519, in generate
    self.generate_target(t)
  File "/usr/lib/python3.8/site-packages/mesonbuild/backend/ninjabackend.py", line 842, in generate_target
    linker, stdlib_args = self.determine_linker_and_stdlib_args(target)
  File "/usr/lib/python3.8/site-packages/mesonbuild/backend/backends.py", line 465, in determine_linker_and_stdlib_args
    l, stdlib_args = target.get_clink_dynamic_linker_and_stdlibs()
  File "/usr/lib/python3.8/site-packages/mesonbuild/build.py", line 1325, in get_clink_dynamic_linker_and_stdlibs
    raise AssertionError(m.format(self.name))
AssertionError: Could not get a dynamic linker for build target 'main'
```

**Expected behavior**

Expected success, and when executing `ninja -C build` an executable called `main` would be created.

**Notes**

After digging a bit it seems that generated sources are not taken into account by neither `is_rust_target` nor `generate_rust_target` in the ninjabackend. Failing to identify this as a rust target seems to be the main problem here.

**System parameters**

* Linux
* Meson 0.56.0
* Ninja 1.10.2

**Comment by dcbaker** [comment]
Just be aware generating rust sources doesn't really work in general, because rust expects a unified build and source tree (because that's how cargo works). You need to copy all of your sources into the builddir by hand to make this work. Likely we'll eventually do that for you since upstream doesn't seem interested in fixing it.
