### ISSUE TITLE
meson 0.55.3 Xcode backend fails -- AttributeError: 'CustomTarget' object has no attribute 'objects'

### ISSUE THREAD

**Issue by jeremyhu** [mesonbuild/meson#8210]
**Describe the bug**

I wanted to try out the Xcode backend to meson to see if it could help as a workaround for #8206, but alas it results in an error.

**To Reproduce**

```
[1149] ~/src/freedesktop/github/XQuartz/src/mesa/mesa (20.3) $ meson build --backend xcode
The Meson build system
Version: 0.55.3
Source dir: /Users/jeremy/src/freedesktop/github/XQuartz/src/mesa/mesa
Build dir: /Users/jeremy/src/freedesktop/github/XQuartz/src/mesa/mesa/build
Build type: native build
Program python found: YES
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Project name: mesa
Project version: 20.3.3
C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.14.8)")
C linker for the host machine: cc ld64 650.1
C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.14.8)")
C++ linker for the host machine: c++ ld64 650.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/opt/local/bin/python3)
Fetching value of define "ETIME" : 101 
Checking for function "bswap32" : YES 
Checking for function "bswap64" : YES 
Checking for function "clz" : YES 
Checking for function "clzll" : YES 
Checking for function "ctz" : YES 
Checking for function "expect" : YES 
Checking for function "ffs" : YES 
Checking for function "ffsll" : YES 
Checking for function "popcount" : YES 
Checking for function "popcountll" : YES 
Checking for function "unreachable" : YES 
Compiler for C supports function attribute const: YES 
Compiler for C supports function attribute flatten: YES 
Compiler for C supports function attribute malloc: YES 
Compiler for C supports function attribute pure: YES 
Compiler for C supports function attribute unused: YES 
Compiler for C supports function attribute warn_unused_result: YES 
Compiler for C supports function attribute weak: YES 
Compiler for C supports function attribute format: YES 
Compiler for C supports function attribute packed: YES 
Compiler for C supports function attribute returns_nonnull: YES 
Compiler for C supports function attribute alias: NO 
Compiler for C supports function attribute noreturn: YES 
Compiler for C supports function attribute visibility:hidden: YES 
Checking if "__uint128_t" compiles: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=empty-body: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=int-conversion: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-format-truncation: NO 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -Qunused-arguments: YES 
Compiler for C supports arguments -fno-common: YES 
Compiler for C supports arguments -Werror=format: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C++ supports arguments -Werror=return-type: YES 
Compiler for C++ supports arguments -Werror=empty-body: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-format-truncation: NO 
Compiler for C++ supports arguments -fno-math-errno: YES 
Compiler for C++ supports arguments -fno-trapping-math: YES 
Compiler for C++ supports arguments -Qunused-arguments: YES 
Compiler for C++ supports arguments -flifetime-dse=1: NO 
Compiler for C++ supports arguments -Werror=format: YES 
Compiler for C++ supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wno-override-init: YES 
Compiler for C supports arguments -Wno-initializer-overrides: YES 
Compiler for C supports arguments -Werror=pointer-arith: YES 
Compiler for C++ supports arguments -Werror=pointer-arith: YES 
Compiler for C supports arguments -Werror=vla: YES 
Compiler for C++ supports arguments -Werror=vla: YES 
Compiler for C supports arguments -Werror=gnu-empty-initializer: YES 
Compiler for C++ supports arguments -Werror=gnu-empty-initializer: YES 
Compiler for C supports arguments -Wmicrosoft-enum-value: YES 
Checking if "GCC atomic builtins" compiles: YES 
Checking if "GCC atomic builtins required -latomic" links: YES 
Checking if "GCC 64bit atomics" with dependency not-found links: YES 
Library ws2_32 found: NO
Header <sys/sysmacros.h> has symbol "major" : NO 
Header <sys/mkdev.h> has symbol "major" : NO 
Check usable header "sys/sysctl.h" : YES 
Check usable header "xlocale.h" : YES 
Check usable header "linux/futex.h" : NO 
Check usable header "endian.h" : NO 
Check usable header "dlfcn.h" : YES 
Check usable header "execinfo.h" : YES 
Check usable header "sys/shm.h" : YES 
Check usable header "cet.h" : YES 
Check usable header "pthread_np.h" : NO 
Checking for function "strtof" : YES 
Checking for function "mkostemp" : YES 
Checking for function "timespec_get" : YES 
Checking for function "memfd_create" : NO 
Checking for function "random_r" : NO 
Checking for function "flock" : YES 
Checking for function "strtok_r" : YES 
Checking for function "getrandom" : NO 
Header <errno.h> has symbol "program_invocation_name" : NO 
Checking for function "posix_memalign" : YES 
Checking whether type "struct dirent" has member "d_type" : YES 
Checking if "strtod has locale support" links: YES 
Checking if "Bsymbolic" links: NO 
Checking if "gc-sections" links: NO 
Checking if "version-script" links: NO 
Checking if "dynamic-list" links: NO 
Compiler for C supports link arguments -Wl,--build-id=sha1: NO 
Checking for function "dlopen" : YES 
Checking for function "dladdr" with dependency not-found: YES 
Checking for function "dl_iterate_phdr" : NO 
Checking for function "clock_gettime" : YES 
Found pkg-config: /opt/local/bin/pkg-config (0.29.2)
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency zlib found: YES 1.2.11
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency libzstd found: YES 1.4.8
Run-time dependency threads found: YES
Checking for function "pthread_setaffinity_np" with dependency threads: NO 
Library expat found: YES
Library m found: YES
Found CMake: /opt/local/bin/cmake (3.19.3)
Run-time dependency libdrm found: NO (tried pkgconfig, framework and cmake)
WARNING: Ignoring LLVM CMake dependency because dynamic was requested
llvm-config found: NO found '3.2' but need '>= 3.9.0'
Run-time dependency LLVM found: NO (tried cmake and config-tool)
Looking for a fallback subproject for the dependency llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine)
Subproject directory not found and llvm.wrap file not found
Subproject  subprojects/llvm is buildable: NO (disabling)
Dependency llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine) from subproject subprojects/llvm found: NO
Run-time dependency valgrind found: NO (tried pkgconfig)
Program bison found: YES
Program bison found: YES 3.7.4
Program flex found: YES
Library System found: YES
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency x11 found: YES 1.7.0
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xext found: YES 1.3.4
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xdamage found: YES 1.1.5
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xfixes found: YES 5.0.3
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xcb-glx found: YES 1.14
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xcb-shm found: YES 1.14
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency xcb found: YES 1.14
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency x11-xcb found: YES 1.7.0
Using 'PKG_CONFIG_PATH' from environment with value: '/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig:'
Run-time dependency glproto found: YES 1.4.17
Library sensors found: NO
Compiler for C supports link arguments -Wl,--gc-sections: NO 
Program nm found: YES
Program symbols-check.py found: YES
Program install_megadrivers.py found: YES
WARNING: Library target 'GLESv1_CM' has 'name_prefix' set. Compilers may not find it from its '-lGLESv1_CM' linker flag in the 'glesv1_cm.pc' pkg-config file.
WARNING: Library target 'GLESv1_CM' has 'name_prefix' set. Compilers may not find it from its '-lGLESv1_CM' linker flag in the 'glesv1_cm-uninstalled.pc' pkg-config file.
WARNING: Library target 'GLESv2' has 'name_prefix' set. Compilers may not find it from its '-lGLESv2' linker flag in the 'glesv2.pc' pkg-config file.
WARNING: Library target 'GLESv2' has 'name_prefix' set. Compilers may not find it from its '-lGLESv2' linker flag in the 'glesv2-uninstalled.pc' pkg-config file.
Library Xplugin found: YES
Program /Users/jeremy/src/freedesktop/github/XQuartz/src/mesa/mesa/bin/install_megadrivers.py found: YES (/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Users/jeremy/src/freedesktop/github/XQuartz/src/mesa/mesa/bin/install_megadrivers.py)
Message: Configuration summary:
        
        prefix:          /usr/local
        libdir:          lib
        includedir:      include
        
        OpenGL:          yes (ES1: yes ES2: yes)
        OSMesa:          no
        
        DRI platform:    apple
        DRI drivers:     no
        DRI driver dir:  /usr/local/lib/dri
        
        GLX:             DRI-based
        
        EGL:             no
        GBM:             no
        
        Vulkan drivers:  no
        
        llvm:            no
        
        Gallium drivers: swrast
        Gallium st:      mesa
        HUD lmsensors:   no
        
        Shared-glapi:    yes

Build targets in project: 101

mesa 20.3.3

  Subprojects
    llvm: NO Subproject directory not found and llvm.wrap file not found

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/msetup.py", line 215, in _generate
    intr.backend.generate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/backend/xcodebackend.py", line 81, in generate
    self.generate_filemap()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mesonbuild/backend/xcodebackend.py", line 132, in generate_filemap
    for o in t.objects:
AttributeError: 'CustomTarget' object has no attribute 'objects'

```

**Expected behavior**

**system parameters**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)

macOS 10.11 with recent meson, python38, etc from MacPorts

Python 3.8.7

**Comment by dcbaker** [comment]
The XCode backend is in pretty rough shape, and really could use some love from someone who knows more about Apple platforms that most of us do. Maybe you know someone would be interested in doing that kind of work? :)

If we could get it in good enough shape to turn on in CI we could probably keep it going ourselves.

**Comment by eli-schwartz** [comment]
This seems to be the same bug as #8210 but the author of the other ticket submitted a fix. More generally, the xcode backend should be in much better shape these days -- can you confirm?
