### ISSUE TITLE
Errors with tap test and gdb

### ISSUE THREAD

**Issue by Szunti** [mesonbuild/meson#8265]
## Describe the bug
Using  a recent checkout, meson test --gdb gives errors after leaving gdb. Maybe a different thing, but even after I change the test protocol to exitcode, these errors remain until I create a fresh build directory.

## To Reproduce
**meson.build**
```
project('failing_test', 'c')
e = executable('failing', 'test_failing.c')
test('failing', e, protocol:'tap')
```
**test_failing.c**
```
#include <stdio.h>

int main() {
  puts("1..1");
  puts("not ok 1");
  return 1;
}
```
Configuring meson:
**/repos/meson/meson.py build**
```
The Meson build system
Version: 0.56.99
Source dir: /tmp/meson_gdb
Build dir: /tmp/meson_gdb/build
Build type: native build
Project name: failing_test
Project version: undefined
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
```
Running test under gdb:
**/repos/meson/meson.py test -C build --gdb**
```
ninja: Entering directory `/tmp/meson_gdb/build'
ninja: no work to do.
Reading symbols from /tmp/meson_gdb/build/failing...
```
Run command of gdb:
```
(gdb) run
Starting program: /tmp/meson_gdb/build/failing
1..1
not ok 1
[Inferior 1 (process 135336) exited normally]
```
Leaving gdb:
```
quit)
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...valid state')>) at /repos/meson/mesonbuild/mtest.py:1649
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...valid state')>) at /repos/meson/mesonbuild/mtest.py:1649>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/repos/meson/mesonbuild/mtest.py", line 1651, in test_done
    f.result()
  File "/repos/meson/mesonbuild/mtest.py", line 1646, in run_test
    res = await test.run()
  File "/repos/meson/mesonbuild/mtest.py", line 1214, in run
    await self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_args)
  File "/repos/meson/mesonbuild/mtest.py", line 1303, in _run_cmd
    res, error = await parse_task
  File "/repos/meson/mesonbuild/mtest.py", line 916, in parse
    async for i in TAPParser().parse_async(lines):
  File "/repos/meson/mesonbuild/mtest.py", line 310, in parse_async
    async for line in lines:
  File "/repos/meson/mesonbuild/mtest.py", line 1006, in read_decode_lines
    f.set_result(''.join(stdo_lines))
asyncio.exceptions.InvalidStateError: invalid state


Ok:                 0
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Traceback (most recent call last):
  File "/repos/meson/mesonbuild/mesonmain.py", line 132, in run
    return options.run_func(options)
  File "/repos/meson/mesonbuild/mtest.py", line 1798, in run
    return th.doit(options)
  File "/repos/meson/mesonbuild/mtest.py", line 1483, in doit
    self.run_tests(runners)
  File "/repos/meson/mesonbuild/mtest.py", line 1629, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/repos/meson/mesonbuild/mtest.py", line 1716, in _run_tests
    await complete(future)
  File "/repos/meson/mesonbuild/mtest.py", line 1051, in complete
    await future
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/repos/meson/mesonbuild/mtest.py", line 1651, in test_done
    f.result()
  File "/repos/meson/mesonbuild/mtest.py", line 1646, in run_test
    res = await test.run()
  File "/repos/meson/mesonbuild/mtest.py", line 1214, in run
    await self._run_cmd(wrap + cmd + self.test.cmd_args + self.options.test_args)
  File "/repos/meson/mesonbuild/mtest.py", line 1303, in _run_cmd
    res, error = await parse_task
  File "/repos/meson/mesonbuild/mtest.py", line 916, in parse
    async for i in TAPParser().parse_async(lines):
  File "/repos/meson/mesonbuild/mtest.py", line 310, in parse_async
    async for line in lines:
  File "/repos/meson/mesonbuild/mtest.py", line 1006, in read_decode_lines
    f.set_result(''.join(stdo_lines))
asyncio.exceptions.InvalidStateError: invalid state
Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'at_eof'")>
Traceback (most recent call last):
  File "/repos/meson/mesonbuild/mtest.py", line 997, in read_decode_lines
    while not reader.at_eof():
AttributeError: 'NoneType' object has no attribute 'at_eof'
```
The line that set's reader to None is [here](https://github.com/mesonbuild/meson/blob/9eb8b6be2874b343ffa1819a3afc2d4ed355b050/mesonbuild/mtest.py#L1274)

### Change to exitcode protocol
Modify meson.build:
**sed -i "s/'tap'/'exitcode'/"  meson.build**

Run test:
**/repos/meson/meson.py test -C build --gdb**
```
ninja: Entering directory `/tmp/meson_gdb/build'
[0/1] Regenerating build files.
The Meson build system
Version: 0.56.99
Source dir: /tmp/meson_gdb
Build dir: /tmp/meson_gdb/build
Build type: native build
Project name: failing_test
Project version: undefined
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
ninja: no work to do.
Reading symbols from /tmp/meson_gdb/build/failing...
(gdb) run
Starting program: /tmp/meson_gdb/build/failing
1..1
not ok 1
[Inferior 1 (process 135527) exited normally]
quit)
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...valid state')>) at /repos/meson/mesonbuild/mtest.py:1649
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...valid state')>) at /repos/meson/mesonbuild/mtest.py:1649>
Traceback (most recent call last):
```
Stacktrace was truncated, exactly the same as above.

### With fresh build directory
No errors, test reported as ok, but that's probably known limitation:
**rm -r build**
**/repos/meson/meson.py build**
```
The Meson build system
Version: 0.56.99
Source dir: /tmp/meson_gdb
Build dir: /tmp/meson_gdb/build
Build type: native build
Project name: failing_test
Project version: undefined
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
```

**/repos/meson/meson.py test -C build --gdb**
```
ninja: Entering directory `/tmp/meson_gdb/build'
[2/2] Linking target failing
Reading symbols from /tmp/meson_gdb/build/failing...
quit)
1/1 failing OK              1.63s


Ok:                 1
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

```
## System parameters
* plain native build
* Arch Linux
* python 3.9
* meson 0.56.99 commit f808c955e
* ninja 1.10.2

**Comment by bonzini** [comment]
Related to #13980
