### ISSUE TITLE
compilers.py: cuda_buildtype_args is missing 'custom' entry, leading to KeyError

### ISSUE THREAD

**Issue by andrzejc** [mesonbuild/meson#8336]
Following the advice in https://github.com/mesonbuild/meson/issues/8334 to use built-in cuda support in meson I attempted to do debug build with optimizations and I got the exception below:

```
  Traceback (most recent call last):                                                                  
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/msetup.py", line 223, in _generate
    intr.backend.generate()
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 519, in generate
    self.generate_target(t)
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 837, in generate_target
    obj_list.append(self.generate_single_compile(target, src, False, [], header_deps))
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 2350, in generate_single_compile
    commands = self._generate_single_compile(target, compiler, is_generated)
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 2284, in _generate_single_compile
    commands += self.generate_basic_compiler_args(target, compiler, no_warn_args)
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/backend/backends.py", line 704, in generate_basic_compiler_args
    commands += compiler.get_buildtype_args(self.get_option_for_target('buildtype', target))
  File "/home/aciarkowski/.local/lib/python3.6/site-packages/mesonbuild/compilers/cuda.py", line 268, in get_buildtype_args
    return cuda_buildtype_args[buildtype] + self._to_host_flags(host_args)
  KeyError: 'custom'
```

Which leads to the definition of cuda_buildtype_args:

https://github.com/mesonbuild/meson/blob/5f697358f0e4249c103f4325424e5ca725ee5261/mesonbuild/compilers/compilers.py#L177

**Comment by dcbaker** [comment]
@jpakkane this should be pretty easy to fix, so we should probably fix it before the release. I'll see if i can get a chance to look at it before Sunday, but someone else could easily beat me to it.
