### ISSUE TITLE
UnicodeDecodeError after "Running custom install script..."

### ISSUE THREAD

**Issue by amezin** [mesonbuild/meson#8480]
**Describe the bug**
On Windows, with non-English locale:

```
> git clone https://gitlab.gnome.org/GNOME/gtk/
> cd gtk
> mkdir build
> cd build
> meson
> ninja
> ninja install
...
Running custom install script 'c:\\users\\aleksandr\\appdata\\local\\programs\\python\\python39\\python.exe C:\\Users\\Aleksandr\\gtk\\build-aux/meson/post-install.py 4.0 4.0.0 C:/Users/Aleksandr/gtk/build/install/lib C:/Users/Aleksandr/gtk/build/install/share C:/Users/Aleksandr/gtk/build/install/bin'
--- stdout ---
Compiling GSettings schemas...

--- stderr ---
Traceback (most recent call last):
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\minstall.py", line 702, in run
    installer.do_install(datafilename)
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\minstall.py", line 508, in do_install
    self.run_install_script(d, destdir, fullprefix)
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\minstall.py", line 580, in run_install_script
    rc = self.run_exe(i, env)
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\minstall.py", line 352, in run_exe
    return run_exe(*args, **kwargs)
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\scripts\meson_exe.py", line 77, in run_exe
    print(stderr.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 914: invalid continuation byte
FAILED: meson-install
"C:\Users\Aleksandr\AppData\Local\Programs\Python\Python39\Scripts\meson" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```

**Expected behavior**

I expected to see output of the failed script, not stack trace from Meson itself

```
Running custom install script 'c:\\users\\aleksandr\\appdata\\local\\programs\\python\\python39\\python.exe C:\\Users\\Aleksandr\\gtk\\build-aux/meson/post-install.py 4.0 4.0.0 C:/Users/Aleksandr/gtk/build/install/lib C:/Users/Aleksandr/gtk/build/install/share C:/Users/Aleksandr/gtk/build/install/bin'
--- stdout ---
Compiling GSettings schemas...

--- stderr ---
Traceback (most recent call last):
  File "C:\Users\Aleksandr\gtk\build-aux\meson\post-install.py", line 19, in <module>
    glib_compile_schemas = subprocess.check_output(['pkg-config',
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\aleksandr\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

FAILED: install script 'c:\users\aleksandr\appdata\local\programs\python\python39\python.exe C:\Users\Aleksandr\gtk\build-aux/meson/post-install.py 4.0 4.0.0 C:/Users/Aleksandr/gtk/build/install/lib C:/Users/Aleksandr/gtk/build/install/share C:/Users/Aleksandr/gtk/build/install/bin' exit code 1, stopped
```

**system parameters**
* Plain native build
* Windows 10
* Pre-built Python 3.9.2 from python.org
* meson 0.57.1
* ninja 1.8.2

**Comment by amezin** [comment]
I guess Meson shouldn't use `errors='strict'` when decoding stdout/stderr https://docs.python.org/3/library/stdtypes.html#bytes.decode

Also not sure if 'utf-8' is the correct choice on Windows (probably not)
