### ISSUE TITLE
crash when running tests with `--repeat 10`

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#8486]
**Describe the bug**
the following command causes a crash on my system:
```
meson test -C build --repeat 10 audio_marker_track
```
output:
```
ninja: Entering directory `/home/alex/Documents/git/zrythm/build'
[1/314] Generating config.h with a custom command
fatal: No annotated tags can describe '9f7e7016d18d1ce2cb1754c7b08fbb2db17fc02e'.
However, there were unannotated tags: try --tags.
[2/310] Generating zrythm-config.h with a custom command
1/1 zrythm:audio / audio_marker_track        OK               5.87s
1/1 zrythm:audio / audio_marker_track        OK               0.02s
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1809, in test_done
    f.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1805, in run_test
    self.process_test_result(res)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1558, in process_test_result
    l.log(self, result)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 657, in log
    self.running_tests.remove(result)
  File "/usr/lib/python3.9/_collections_abc.py", line 684, in remove
    raise KeyError(value)
KeyError: <mesonbuild.mtest.TestRunExitCode object at 0x7f9541d8c130>
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1809, in test_done
    f.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1805, in run_test
    self.process_test_result(res)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1558, in process_test_result
    l.log(self, result)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 657, in log
    self.running_tests.remove(result)
  File "/usr/lib/python3.9/_collections_abc.py", line 684, in remove
    raise KeyError(value)
KeyError: <mesonbuild.mtest.TestRunExitCode object at 0x7f9541d8c130>
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1809, in test_done
    f.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1805, in run_test
    self.process_test_result(res)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1558, in process_test_result
    l.log(self, result)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 657, in log
    self.running_tests.remove(result)
  File "/usr/lib/python3.9/_collections_abc.py", line 684, in remove
    raise KeyError(value)
KeyError: <mesonbuild.mtest.TestRunExitCode object at 0x7f9541d8c130>
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...f9541d8c130>)>) at /usr/lib/python3.9/site-packages/mesonbuild/mtest.py:1807>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1809, in test_done
    f.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1805, in run_test
    self.process_test_result(res)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1558, in process_test_result
    l.log(self, result)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 657, in log
    self.running_tests.remove(result)
  File "/usr/lib/python3.9/_collections_abc.py", line 684, in remove
    raise KeyError(value)
KeyError: <mesonbuild.mtest.TestRunExitCode object at 0x7f9541d8c130>


Ok:                 6   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/alex/Documents/git/zrythm/build/meson-logs/testlog.txt
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 132, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1960, in run
    return th.doit()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1642, in doit
    self.run_tests(runners)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1781, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1876, in _run_tests
    await complete_all(futures)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1160, in complete_all
    f.result()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1809, in test_done
    f.result()
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1805, in run_test
    self.process_test_result(res)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1558, in process_test_result
    l.log(self, result)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mtest.py", line 657, in log
    self.running_tests.remove(result)
  File "/usr/lib/python3.9/_collections_abc.py", line 684, in remove
    raise KeyError(value)
KeyError: <mesonbuild.mtest.TestRunExitCode object at 0x7f9541d8c130>
```

**To Reproduce**
TODO

**Expected behavior**
no crash

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Parabola with systemd
* what Python version are you using: 3.9
* what `meson --version`: 0.57.1 provided by Arch Linux
* what `ninja --version` if it's a Ninja build: 1.10.2

**Comment by tristan957** [comment]
Fixed in latest master. We really need a meson 0.57.2 release. Would be nice if there were generally more point releases. Lots of fixes are always getting in.

**Comment by anarazel** [comment]
This appears to be fixed - I don't have the rights to close the bug though...

**Comment by tristan957** [comment]
@dcbaker can you close this?
