### ISSUE TITLE
Use user-friendly error when defining multiple targets with same name

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#8519]
**Describe the bug**
When adding a target with the same name as another target, you get this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 132, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 275, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 183, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 222, in _generate
    intr.run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 4798, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 641, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 666, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 659, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 682, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 764, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 666, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 659, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 672, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 1031, in function_call
    return func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 229, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 4090, in func_run_target
    assert(full_name not in self.build.run_target_names)
AssertionError
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/alex/Documents/git/zrythm /home/alex/Documents/git/zrythm/build --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**To Reproduce**
Create multiple targets with same name

**Expected behavior**
A user friendly error message: "A target with the name  `name` already exists"

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Arch Linux
* what Python version are you using: 3.9.2
* what `meson --version` 0.57.1
* what `ninja --version` if it's a Ninja build: 1.10.2

**Comment by alex-tee** [comment]
this is probably very low priority

**Comment by eli-schwartz** [comment]
It's tripping over an assert statement. Those are "this is completely impossible to occur, but if they do let's yell at the developer" concepts, get optimized out when running with python -O and indicate that actual program logic somewhere is lacking robustness.

Is this unique to run_target()?

**Comment by behlec** [comment]
Can you provide a simple example?

**Comment by alex-tee** [comment]
hmm I can't seem to reproduce it with a simple example and I'm still on the same meson version. I get proper error messages with a simple example:

`meson.build:12:0: ERROR: Tried to create target "mytarget", but a target of that name already exists.`
`ERROR: Multiple producers for Ninja target "mytarget". Please rename your targets.`

**Comment by behlec** [comment]
Same here, a quick glance at the source code does not give me an idea either.

**Comment by JamBalaya56562** [comment]
Thank you for the report. Defining two targets with the same name no longer produces a bare `AssertionError` traceback — it now raises a clear, user-facing error that points at the problem:

```
ERROR: Tried to create target "<name>", but a target of that name already exists.
```

The target functions go through `add_target()`, which validates the name rather than asserting on it:

```python
# mesonbuild/interpreter/interpreter.py (add_target)
raise InvalidCode(f'Tried to create target "{name}", but a target of that name already exists.')
```

**Verification:** `add_target()` in `mesonbuild/interpreter/interpreter.py` raises `InvalidCode` (a normal, sourced Meson error) on a duplicate target id, instead of the old `assert` that produced a traceback.

Since duplicate names now give a friendly error, this looks safe to close. Thanks for the report.
