### ISSUE TITLE
AttributeError: 'Interpreter' object has no attribute 'builtin'

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#857]
I just updated to the latest master and got this stackdump.

```python
mkdir build
python3 ./ECS/MDP1/meson/meson.py --buildtype=debugoptimized build
The Meson build system
Version: 0.36.0.dev1
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Traceback (most recent call last):
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/mesonmain.py", line 282, in run
    app.generate()
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/mesonmain.py", line 159, in generate
    intr = interpreter.Interpreter(b, g)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1129, in __init__
    self.sanity_check_ast()
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1258, in sanity_check_ast
    args = self.reduce_arguments(first.args)[0]
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2387, in reduce_arguments
    reduced_kw[key] = self.evaluate_statement(a)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1435, in evaluate_statement
    return self.evaluate_arraystatement(cur)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2744, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2381, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2381, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1423, in evaluate_statement
    return self.method_call(cur)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2515, in method_call
    return self.string_method_call(obj, method_name, args)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2434, in string_method_call
    (posargs, _) = self.reduce_arguments(args)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2381, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2381, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1423, in evaluate_statement
    return self.method_call(cur)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 2505, in method_call
    obj = self.get_variable(object_name)
  File "/tmp/foo/ECS/MDP1/meson/mesonbuild/interpreter.py", line 1308, in get_variable
    if varname in self.builtin:
AttributeError: 'Interpreter' object has no attribute 'builtin'
```

**Comment by rhd** [comment]
Hi jussi, I just updated to today's master (e2b3752f8757) and I'm still seeing this error. I'm stuck. Can you help me figure out what's going on?

**Comment by jpakkane** [comment]
Can you test #887?

**Comment by rhd** [comment]
sure. I get this now.

```
mkdir build
python3 ./ECS/MDP1/meson/meson.py --buildtype=debugoptimized build
The Meson build system
Version: 0.36.0.dev1
Source dir: /tmpwork/MDP1
Build dir: /tmp/work/MDP1/build
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Unknown variable "meson".
make: *** [build] Error 1
```

```
10:34 $ head meson.build
project('ECS', ['cpp', 'c'],
    default_options : ['buildtype=debugoptimized',
                       'cpp_std=c++11',
                       'errorlogs=true',
                       'prefix=@0@/dist'.format(meson.current_source_dir())]
)

cc = meson.get_compiler('cpp')
```

**Comment by jpakkane** [comment]
How about now?

**Comment by rhd** [comment]
Yes, it's working now. :+1:
