### ISSUE TITLE
Does not work on python 3.9

### ISSUE THREAD

**Issue by protonesso** [mesonbuild/meson#8728]
**Describe the bug**
This bug occurs on meson 0.58.0 and python 3.9.5:
```
# meson
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.58.0', 'console_scripts', 'meson')())
  File "/usr/bin/meson", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 25, in <module>
    from . import mconf, mdist, minit, minstall, mintro, msetup, mtest, rewriter, msubprojects, munstable_coredata, mcompile
  File "/usr/lib/python3.9/site-packages/mesonbuild/mconf.py", line 16, in <module>
    from . import coredata, environment, mesonlib, build, mintro, mlog
  File "/usr/lib/python3.9/site-packages/mesonbuild/mintro.py", line 30, in <module>
    from .interpreter import Interpreter
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/__init__.py", line 19, in <module>
    from .interpreter import Interpreter, permitted_test_kwargs, permitted_dependency_kwargs
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 33, in <module>
    from ..interpreterbase import ObjectHolder, RangeHolder
ImportError: cannot import name 'RangeHolder' from 'mesonbuild.interpreterbase' (/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py)
```

**To Reproduce**
Update python to 3.9.5 and install latest stable meson (in our case this is 0.58.0)

**Expected behavior**
Working meson script with latest python 3

**system parameters**
* This is native build
* Custom built Linux distribution, other python programs seem to work
* Python version is 3.9.5
* meson version is 0.58.0
* ninja version is 1.9

**Comment by protonesso** [comment]
meson 0.57.2 seems to work though

**Comment by eli-schwartz** [comment]
What does this have to do with python 3.9?

Also interpreterbase.py does define this class.

**Comment by protonesso** [comment]
I don't know what went wrong but ig you may test on your own

**Comment by xclaesse** [comment]
My guess is it mix meson 0.57 and 0.58 py or pyc files. Try uninstall and install again, clear pycache?

**Comment by protonesso** [comment]
Okay I'll try

ср, 5 мая 2021 г., 17:40 Xavier Claessens ***@***.***>:

**Comment by eli-schwartz** [comment]
So, what ended up happening?

**Comment by protonesso** [comment]
Okay still the same

**Comment by tristan957** [comment]
I have seen errors like this happen before and something is just getting cached poorly on the system. I don't how to fix it other than blowing away my virtual environment.

**Comment by eli-schwartz** [comment]
So... meson works here on my end and elsewhere. On your system it doesn't work. This indicates it is not a meson bug, but a problem with your python environment.

You are using:
- a "custom built linux distribution". As a distribution builder, you should know how to put together distros and debug their problems (I hope) or have contact info for someone who is involved in this custom distro and can handle that work.
- A meson installed to /usr/lib/python3.9/site-packages, which falls into the domain of said distro environment

I'm closing this ticket because there's no information here to help us help you, and we've given all the suggestions we can.

But mostly, because this isn't a meson issue, it's a python issue, and this isn't an issue tracker dedicated to python environments or PyPA user experiences or anything of that sort. So keeping this ticket in the "open, needs attention" queue is incorrect.

Feel free to report back about your experiences, and if this turns out to be something we can fix on our end, we can of course re-open the ticket.
