### ISSUE TITLE
Reconfiguring project with option `--backend=vs` added raises a KeyError of `backend_startup_project`.

### ISSUE THREAD

**Issue by BugenZhao** [mesonbuild/meson#8738]
**Describe the bug**
Reconfiguring project with option `--backend=vs` added raises a KeyError of `backend_startup_project`.

```
Traceback (most recent call last): 
  File "c:\python39\lib\site-packages\mesonbuild\mesonmain.py", line 132, in run 
    return options.run_func(options) 
  File "c:\python39\lib\site-packages\mesonbuild\msetup.py", line 279, in run 
    app.generate() 
  File "c:\python39\lib\site-packages\mesonbuild\msetup.py", line 183, in generate 
    self._generate(env) 
  File "c:\python39\lib\site-packages\mesonbuild\msetup.py", line 245, in _generate 
    intr.backend.generate() 
  File "c:\python39\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 192, in generate 
    projlist = self.generate_projects() 
  File "c:\python39\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 409, in generate_projects 
    startup_project = self.environment.coredata.options[OptionKey('backend_startup_project')].value 
KeyError: OptionKey('backend_startup_project', '', <MachineChoice.HOST: 1>, None)
```

**To Reproduce**
- Clone `https://gitlab.freedesktop.org/mesa/mesa` to local.
- Configure project as usual: `meson`.
- Reconfigure with: `meson --backend=vs --reconfigure`.

**Expected behavior**
Generate a Visual Studio Solution `sln` file.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10
* what Python version are you using e.g. 3.8.0
3.9.4
* what `meson --version`
0.57.2
* what `ninja --version` if it's a Ninja build
1.10.2

**Comment by dcbaker** [comment]
Are you switching from the ninja backend to the vs one? I'm not sure if we support that without a full wipe to be honest.

**Comment by bonzini** [comment]
Fixed:

```
ERROR: Tried to modify read only option "backend"
```
