### ISSUE TITLE
Regression building Mesa on Windows

### ISSUE THREAD

**Issue by kusma** [mesonbuild/meson#8916]
We are using Meson to build Mesa on Windows, but when upgrading from 0.57.2 to 0.58.1, Meson starts crashing while scanning dependencies.

You can observe this from a CI log here:
https://gitlab.freedesktop.org/kusma/mesa/-/jobs/11095506#L368

The actual error is this:
```
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\meson.exe\__main__.py", line 7, in <module>
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 231, in main
    return run(sys.argv[1:], launcher)
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 220, in run
    return run_script_command(args[1], args[2:])
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 168, in run_script_command
    return module.run(script_args)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 201, in run
    return scanner.scan()
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 152, in scan
    self.scan_file(s)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 53, in scan_file
    self.scan_cpp_file(fname)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 111, in scan_cpp_file
    for line in fpath.read_text().split('\n'):
  File "c:\python3\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "c:\python3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 11367: character maps to <undefined>
```

To reproduce this locally, one should be able to to build Mesa on Windows, including the RADV driver (`-Dvulkan-drivers=amd`). This requires a build of LLVM in order to complete, which is time-consuming to build, and doesn't work with any prebuilt packages to my knowledge. But it's likely that someone who knows the dependency scanning code can reduce this to something smaller.

I have not tried versions between 0.57.2 and 0.58.1 (0.58.0 plus release-candidates) to narrow this down, because the CI build takes several hours to prepare the dependencies (mostly due to LLVM), and I don't have the local setup to debug this locally at the moment.

**Comment by kusma** [comment]
This seems similar to #8263, except for working until recently. So it might not be exactly the same, but related or something?

**Comment by kusma** [comment]
Actually, it seems like this is just #8263 in disguise, and the upgrading Meson was just an illusion.

It's really unclear what's going on thought, because it passes on our main-branch with the current source code. But some recent changes did include UTF-8 symbols in the area of the code where this fails, but I only see this fail if I also upgrade dependencies in our docker image first. Rolling back Meson doesn't help, so perhaps there were a change in Python here?

In either case, it seems the right thing to do is to pass in an UTF-8 encoding object to `read_text()`, because the current locale is almost certainly not what we want to use to read source files.

**Comment by kusma** [comment]
OK, I found out what this is; it's [this](https://github.com/python/cpython/commit/4827483f47906fecee6b5d9097df2a69a293a85c#diff-bcdfa9cbb0764d7959cda48f9084d79785f87c5ad7460f27ba2678b0bda76e38) python change.

**Comment by kusma** [comment]
Just to be clear; this doesn't seem to be due to a python-change at all, but rather our CI builders upgrading Visual Studio to a version that triggered a latent bug.
