### ISSUE TITLE
Allow custom_target outputs to be directories

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#893]
Currently we allow this, but that directory can then not be installed: 

```
Traceback (most recent call last):
  File "/home/nirbheek/projects/repositories/github/meson.git/meson.py", line 25, in <module>
    sys.exit(mesonmain.run(launcher, sys.argv[1:]))
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/mesonmain.py", line 242, in run
    sys.exit(run_script_command(args[1:]))
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 251, in run
    do_install(datafilename)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 54, in do_install
    install_targets(d)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 205, in install_targets
    do_copy(fname, outname)
  File "/home/nirbheek/projects/repositories/github/meson.git/mesonbuild/scripts/meson_install.py", line 36, in do_copy
    shutil.copyfile(from_file, to_file)
  File "/usr/lib64/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: 'devhelp'
FAILED: install 
```

I can't think of a reason to not allow this.

Found while investigating #890

**Comment by grindhold** [comment]
wait. that's not all. as i wrote, valadoc will not only output the folder devhelp, but it will output ```<outputdir>/<modulename>/<modulename>/```  the deepest folder in the tree is the folder that then has to be installed to e.g. ```/usr/local/share/devhelp/books/```, so it looks like ```/usr/local/share/devhelp/books/<modulename>``` in order to work. 

so it's not only that folders must be allowed, it would be nice to be able to pick a specific subfolder to be installed.

**Comment by nirbheek** [comment]
For the specific case of valadoc, ideally we'd like to get native support for it (#894).
