### ISSUE TITLE
smatch + meson does not work

### ISSUE THREAD

**Issue by phomes** [mesonbuild/meson#9055]
Smatch is a static analysis tool. It is primarily written for the kernel but I have found it useful on many other C based projects in the past.

Smatch contains a script "cgcc" that you use instead of gcc. I have never gotten this to work with meson.

To reproduce:
1. git clone https://repo.or.cz/w/smatch.git
2. run make
3. export the path
4. CC=cgcc meson build (in the project you want to run the analyzer on)

meson crashes with:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3/dist-packages/mesonbuild/msetup.py", line 178, in _generate
    intr = interpreter.Interpreter(b)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 2436, in __init__
    self.parse_project()
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 504, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 544, in evaluate_codeblock
    raise e
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 537, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 550, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 909, in function_call
    return func(node, func_args, kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 197, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3213, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3337, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/interpreter.py", line 3369, in add_languages_for
    comp = self.environment.detect_compiler_for(lang, for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/environment.py", line 1885, in detect_compiler_for
    comp = self.compiler_from_language(lang, for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/environment.py", line 1857, in compiler_from_language
    comp = self.detect_c_compiler(for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/environment.py", line 1345, in detect_c_compiler
    return self._detect_c_or_cpp_compiler('c', for_machine)
  File "/usr/lib/python3/dist-packages/mesonbuild/environment.py", line 1145, in _detect_c_or_cpp_compiler
    defines = self.get_gnu_compiler_defines(compiler)
  File "/usr/lib/python3/dist-packages/mesonbuild/environment.py", line 831, in get_gnu_compiler_defines
    defines[rest] = True
TypeError: unhashable type: 'list'

```

**Comment by eli-schwartz** [comment]
This works for me. Your traceback isn't representative of current versions of meson, does this work if you install the latest meson?

**Comment by phomes** [comment]
Apologies. It does indeed work with 0.59
