### ISSUE TITLE
bash completion errors outside of builddir

### ISSUE THREAD

**Issue by st3r4g** [mesonbuild/meson#9077]
**Describe the bug**
The bash completion doesn't handle directories that are not meson build directories well.

**To Reproduce**
Outside of a meson builddir, type `meson test` and then `Tab` twice:
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Expected behavior**
No errors are shown

**system parameters**
* Native build
* Voidlinux
* Python 3.9.6
* meson 0.58.2

**Comment by tristan957** [comment]
@eli-schwartz looks like https://github.com/mesonbuild/meson/pull/11422 will fix this one.
