### ISSUE TITLE
GLib configure fails: AttributeError: 'ModuleState' object has no attribute 'node'

### ISSUE THREAD

**Issue by amezin** [mesonbuild/meson#9081]
**Describe the bug**
I can't build [current GLib main branch - commit `2700a22f02c67adc3d135b8bba5a76195ec7ce9d`](https://gitlab.gnome.org/GNOME/glib/-/commit/2700a22f02c67adc3d135b8bba5a76195ec7ce9d) with [Meson from master branch - `5c87167a34c6ed703444af180fffd8a45a7928ee`](https://github.com/mesonbuild/meson/commit/5c87167a34c6ed703444af180fffd8a45a7928ee)

```
The Meson build system
Version: 0.59.99
Source dir: /home/amezin/glib
Build dir: /home/amezin/glib/build
Build type: native build
Project name: glib
Project version: 2.69.1
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
C++ compiler for the host machine: ccache c++ (gcc 11.1.0 "c++ (GCC) 11.1.0")
C++ linker for the host machine: c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fno-strict-aliasing: YES 
Checking if "GNU C visibility attributes test" compiles: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Message: Enabling various debug infrastructure
Has header "alloca.h" : YES 
Has header "crt_externs.h" : NO 
Has header "dirent.h" : YES 
Has header "float.h" : YES 
Has header "fstab.h" : YES 
Has header "grp.h" : YES 
Has header "inttypes.h" : YES 
Has header "limits.h" : YES 
Has header "linux/magic.h" : YES 
Has header "locale.h" : YES 
Has header "mach/mach_time.h" : NO 
Has header "memory.h" : YES 
Has header "mntent.h" : YES 
Has header "poll.h" : YES 
Has header "pwd.h" : YES 
Has header "sched.h" : YES 
Has header "spawn.h" : YES 
Has header "stdatomic.h" : YES 
Has header "stdint.h" : YES 
Has header "stdlib.h" : YES 
Has header "string.h" : YES 
Has header "strings.h" : YES 
Has header "sys/auxv.h" : YES 
Has header "sys/event.h" : NO 
Has header "sys/filio.h" : NO 
Has header "sys/inotify.h" : YES 
Has header "sys/mkdev.h" : NO 
Has header "sys/mntctl.h" : NO 
Has header "sys/mnttab.h" : NO 
Has header "sys/mount.h" : YES 
Has header "sys/param.h" : YES 
Has header "sys/resource.h" : YES 
Has header "sys/select.h" : YES 
Has header "sys/statfs.h" : YES 
Has header "sys/stat.h" : YES 
Has header "sys/statvfs.h" : YES 
Has header "sys/sysctl.h" : NO 
Has header "sys/time.h" : YES 
Has header "sys/times.h" : YES 
Has header "sys/types.h" : YES 
Has header "sys/uio.h" : YES 
Has header "sys/vfs.h" : YES 
Has header "sys/vfstab.h" : NO 
Has header "sys/vmount.h" : NO 
Has header "sys/wait.h" : YES 
Has header "termios.h" : YES 
Has header "unistd.h" : YES 
Has header "values.h" : YES 
Has header "wchar.h" : YES 
Has header "xlocale.h" : NO 
Checking if "malloc.h" compiles: YES 
Has header "linux/netlink.h" : YES 
Checking if "statx() test" compiles: YES 
Header <locale.h> has symbol "LC_MESSAGES" : YES 
Checking whether type "struct stat" has member "st_mtimensec" : NO 
Checking whether type "struct stat" has member "st_mtim.tv_nsec" : YES 
Checking whether type "struct stat" has member "st_atimensec" : NO 
Checking whether type "struct stat" has member "st_atim.tv_nsec" : YES 
Checking whether type "struct stat" has member "st_ctimensec" : NO 
Checking whether type "struct stat" has member "st_ctim.tv_nsec" : YES 
Checking whether type "struct stat" has member "st_birthtime" : NO 
Checking whether type "struct stat" has member "st_birthtimensec" : NO 
Checking whether type "struct stat" has member "st_birthtim" : NO 
Checking whether type "struct stat" has member "st_birthtim.tv_nsec" : NO 
Checking whether type "struct stat" has member "st_blksize" : YES 
Checking whether type "struct stat" has member "st_blocks" : YES 
Checking whether type "struct statfs" has member "f_fstypename" : NO 
Checking whether type "struct statfs" has member "f_bavail" : YES 
Checking whether type "struct dirent" has member "d_type" : YES 
Checking whether type "struct statvfs" has member "f_basetype" : NO 
Checking whether type "struct statvfs" has member "f_fstypename" : NO 
Checking whether type "struct tm" has member "tm_gmtoff" : YES 
Checking whether type "struct tm" has member "__tm_gmtoff" : NO 
Compiler for C supports arguments -Wduplicated-branches: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wmisleading-indentation: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-bad-function-cast: YES 
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wno-pedantic: YES 
Compiler for C supports arguments -Wno-format-zero-length: YES 
Compiler for C supports arguments -Werror=declaration-after-statement: YES 
Compiler for C supports arguments -Werror=format=2: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=missing-include-dirs: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Werror=pointer-arith: YES 
Compiler for C supports link arguments -Wl,-z,nodelete: YES 
Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
Checking for function "close_range" : NO 
Checking for function "endmntent" : YES 
Checking for function "endservent" : YES 
Checking for function "epoll_create" : YES 
Checking for function "fallocate" : YES 
Checking for function "fchmod" : YES 
Checking for function "fchown" : YES 
Checking for function "fdwalk" : NO 
Checking for function "fsync" : YES 
Checking for function "getauxval" : YES 
Checking for function "getc_unlocked" : YES 
Checking for function "getfsstat" : NO 
Checking for function "getgrgid_r" : YES 
Checking for function "getmntent_r" : YES 
Checking for function "getpwuid_r" : YES 
Checking for function "getresuid" : YES 
Checking for function "getvfsstat" : NO 
Checking for function "gmtime_r" : YES 
Checking for function "hasmntopt" : YES 
Checking for function "inotify_init1" : YES 
Checking for function "issetugid" : NO 
Checking for function "kevent" : NO 
Checking for function "kqueue" : NO 
Checking for function "lchmod" : YES 
Checking for function "lchown" : YES 
Checking for function "link" : YES 
Checking for function "localtime_r" : YES 
Checking for function "lstat" : YES 
Checking for function "mbrtowc" : YES 
Checking for function "memalign" : YES 
Checking for function "mmap" : YES 
Checking for function "newlocale" : YES 
Checking for function "pipe2" : YES 
Checking for function "poll" : YES 
Checking for function "prlimit" : YES 
Checking for function "readlink" : YES 
Checking for function "recvmmsg" : YES 
Checking for function "sendmmsg" : YES 
Checking for function "setenv" : YES 
Checking for function "setmntent" : YES 
Checking for function "strerror_r" : YES 
Checking for function "strnlen" : YES 
Checking for function "strsignal" : YES 
Checking for function "strtod_l" : YES 
Checking for function "strtoll_l" : YES 
Checking for function "strtoull_l" : YES 
Checking for function "symlink" : YES 
Checking for function "timegm" : YES 
Checking for function "unsetenv" : YES 
Checking for function "uselocale" : YES 
Checking for function "utimes" : YES 
Checking for function "valloc" : YES 
Checking for function "vasprintf" : YES 
Checking for function "vsnprintf" : YES 
Checking for function "wcrtomb" : YES 
Checking for function "wcslen" : YES 
Checking for function "wcsnlen" : YES 
Checking for function "sysctlbyname" : NO 
Checking for function "statvfs" : YES 
Checking for function "statfs" : YES 
Checking for function "if_indextoname" : YES 
Checking for function "if_nametoindex" : YES 
Checking for function "splice" : YES 
Checking for function "stpcpy" : YES 
Checking for function "posix_memalign" : YES 
Checking for function "posix_spawn" : YES 
Checking if "strerror_r() returns char *" compiles: YES 
Checking for function "snprintf" : YES 
Checking for function "strcasecmp" : YES 
Checking for function "strncasecmp" : YES 
Header <sys/sysmacros.h> has symbol "major" : YES 
Header <dlfcn.h> has symbol "RTLD_LAZY" : YES 
Header <dlfcn.h> has symbol "RTLD_NOW" : YES 
Header <dlfcn.h> has symbol "RTLD_GLOBAL" : YES 
Header <dlfcn.h> has symbol "RTLD_NEXT" : YES 
Message: Checking whether to use statfs or statvfs .. statfs
Checking for function "mkostemp" : YES 
Checking if "futex(2) system call" links: YES 
Checking if "eventfd(2) system call" links: YES 
Checking if "__uint128_t available" compiles: YES 
Checking if "clock_gettime" links: YES 
Checking if "dlopen() and dlsym() in system libraries" links: NO 
Checking if "dlopen() and dlsym() in libdl" links: YES 
Library dl found: YES
Checking if "number of arguments to statfs() (n=2)" compiles: YES 
Checking if "open() option O_DIRECTORY" compiles: YES 
Checking if "fcntl() option F_FULLFSYNC" compiles: NO 
Checking if "C99 vsnprintf" runs: YES
Checking if "C99 snprintf" runs: YES
Checking if "Unix98 printf positional parameters" runs: YES
Checking if "nl_langinfo and CODESET" links: YES 
Checking if "nl_langinfo (PM_STR)" links: YES 
Checking if "nl_langinfo (_NL_CTYPE_OUTDIGITn_MB)" links: YES 
Checking if "nl_langinfo (ALTMON_n)" links: YES 
Checking if "nl_langinfo (_NL_ABALTMON_n)" links: YES 
Checking if "nl_langinfo and _NL_TIME_CODESET" links: YES 
Checking if "signed" compiles: YES 
Header <stddef.h> has symbol "ptrdiff_t" : YES 
Checking if "sig_atomic_t" links: YES 
Checking if "long long" compiles: YES 
Checking if "long double" compiles: YES 
Header <stddef.h> has symbol "wchar_t" : YES 
Header <wchar.h> has symbol "wint_t" : YES 
Checking if "uintmax_t in inttypes.h" compiles: YES 
Checking if "uintmax_t in stdint.h" compiles: YES 
Checking for size of "char" : 1
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "void*" : 8
Checking for size of "long" : 8
Checking for size of "long long" : 8
Checking for size of "size_t" : 8
Checking for size of "ssize_t" : 8
Checking if "int64_t is long" compiles: YES 
Checking for alignment of "char" : 1
Checking for alignment of "short" : 2
Checking for alignment of "int" : 4
Checking for alignment of "void*" : 8
Checking for alignment of "long" : 8
Checking for alignment of "long long" : 8
Checking for alignment of "size_t" : 8
Checking for size of "wchar_t" : 4
Checking if "GCC size_t typedef is long" compiles: YES 
Checking if "GCC size_t typedef is long long" compiles: NO 
Checking if "__va_copy check" compiles: YES 
Checking if "va_copy check" compiles: YES 
Checking if "va_lists can be copied as values" runs: DID NOT COMPILE
Checking if "ISO C99 varargs macros in C" compiles: YES 
Checking if "ISO C99 varargs macros in C++" compiles: YES 
Checking if "GNUC varargs macros" compiles: YES 
Has header "alloca.h" : YES (cached)
Has header "sys/poll.h" : YES 
Has header "sys/types.h" : YES (cached)
Has header "winsock2.h" : NO 
Computing int of "POLLIN" : 1
Computing int of "POLLOUT" : 4
Computing int of "POLLPRI" : 2
Computing int of "POLLERR" : 8
Computing int of "POLLHUP" : 16
Computing int of "POLLNVAL" : 32
Computing int of "AF_UNIX" : 1
Computing int of "AF_INET" : 2
Computing int of "AF_INET6" : 10
Computing int of "MSG_OOB" : 1
Computing int of "MSG_PEEK" : 2
Computing int of "MSG_DONTROUTE" : 4
Checking for type "struct in6_addr" : YES 
Checking if "atomic ops" links: YES 
Checking if "atomic ops define" compiles: YES 
Run-time dependency threads found: YES
Header <pthread.h> has symbol "pthread_attr_setstacksize" : YES 
Header <pthread.h> has symbol "pthread_attr_setinheritsched" : YES 
Header <pthread.h> has symbol "pthread_condattr_setclock" : YES 
Header <pthread.h> has symbol "pthread_cond_timedwait_relative_np" : NO 
Header <pthread.h> has symbol "pthread_getname_np" : YES 
Header <sys/syscall.h> has symbol "SYS_sched_getattr" : YES 
Checking if "pthread_setname_np(const char*)" with dependency threads links: NO 
Checking if "pthread_setname_np(pthread_t, const char*)" with dependency threads links: YES 
Checking if "stack grows check" runs: NO (1)
Checking for function "iconv_open" : YES 
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency libpcre found: YES 8.45
Library m found: YES
Run-time dependency libffi found: YES 3.3
Run-time dependency zlib found: YES 1.2.11
Checking for function "ngettext" : YES 
Checking for function "bind_textdomain_codeset" : YES 
Run-time dependency mount found: YES 2.37.1
Found CMake: /usr/bin/cmake (3.21.1)
Run-time dependency libselinux found: NO (tried pkgconfig and cmake)
Checking for function "getxattr" : YES 
Has header "sys/xattr.h" : YES 
Checking if "XATTR_NOFOLLOW" compiles: NO 
Checking for function "strlcpy" : NO 
Checking if "/proc/self/cmdline" runs: YES
Program python3 found: YES (/usr/bin/python3)
Program bash found: YES (/usr/bin/bash)
Run-time dependency bash-completion found: YES 2.11
Program sh found: YES (/usr/bin/sh)
Program env found: YES (/usr/bin/env)
Configuring glibconfig.h using configuration
Dependency sysprof-capture-4 skipped: feature sysprof disabled
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Configuring gtester-report using configuration
Configuring libglib-2.0.so.0.6901.0-gdb.py using configuration
Program xmllint found: YES (/usr/bin/xmllint)
Configuring glib-genmarshal using configuration
Program glib-genmarshal found: YES (/home/amezin/glib/build/gobject/glib-genmarshal)
Configuring glib-mkenums using configuration
Program glib-mkenums found: YES (/home/amezin/glib/build/gobject/glib-mkenums)
Configuring libgobject-2.0.so.0.6901.0-gdb.py using configuration
Checking if "dlsym() preceding underscores" with dependency -ldl runs: NO (1)
Checking for function "dlerror" with dependency -ldl: YES 
Configuring gmoduleconf.h using configuration
Checking if "C_IN in public headers (no arpa/nameser_compat.h needed)" compiles: YES 
Checking if "res_query()" links: NO 
Checking if "res_query() in -lresolv" links: YES 
Library resolv found: YES
Checking if "socket()" links: YES 
Checking if "res_init()" links: YES 
Checking if "res_nclose()" links: YES 
Checking if "res_ndestroy()" links: NO 
Checking if "res_ninit()" links: YES 
Checking if "res_nquery()" links: YES 
Checking for type "struct ip_mreqn" : YES 
Checking if "ioctl with request SIOCGIFADDR" compiles: YES 
Configuring gnetworking.h using configuration
Configuring gdbus-codegen using configuration
Program gdbus-codegen found: YES (/home/amezin/glib/build/gio/gdbus-2.0/codegen/gdbus-codegen)
Configuring config.py using configuration
WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

WARNING: extract_all_objects called without setting recursive
keyword argument. Meson currently defaults to
non-recursive to maintain backward compatibility but
the default will be changed in the future.

Run-time dependency libelf found: YES 0.185
Message: Found libutil as libutil.so.1
Program gengiotypefuncs.py found: YES (/usr/bin/python /home/amezin/glib/gio/tests/gengiotypefuncs.py)
Run-time dependency dbus-1 found: YES 1.12.20
Program dbus-daemon found: YES (/usr/bin/dbus-daemon)
Program msgfmt found: YES (/usr/bin/msgfmt)
Configuring appinfo-test-gnome.desktop using configuration
Configuring appinfo-test-notgnome.desktop using configuration
Configuring appinfo-test.desktop using configuration
Configuring appinfo-test2.desktop using configuration
Program objcopy found: YES (/usr/bin/objcopy)
Program ld found: YES (/usr/bin/ld)
Configuring org.freedesktop.portal.Documents.service using configuration
Configuring org.gtk.GDBus.FakeService.service using configuration
Compiler for C supports arguments -Werror=unused-function: YES 
Library FuzzingEngine skipped: feature oss_fuzz disabled
Program xgettext found: YES (/usr/bin/xgettext)
Configuring glib-gettextize using configuration
Configuring config.h using configuration
Run-time dependency gtk-doc found: YES 1.33.1
Program gtkdoc-scan found: YES (/usr/bin/gtkdoc-scan)
Program gtkdoc-scangobj found: YES (/usr/bin/gtkdoc-scangobj)
Program gtkdoc-mkdb found: YES (/usr/bin/gtkdoc-mkdb)
Program gtkdoc-mkhtml found: YES (/usr/bin/gtkdoc-mkhtml)
Program gtkdoc-fixxref found: YES (/usr/bin/gtkdoc-fixxref)
Configuring gtkdocentities.ent using configuration
Configuring version.xml using configuration
Program concat-files-helper.py found: YES (/usr/bin/python /home/amezin/glib/docs/reference/gio/concat-files-helper.py)
Configuring gio-sections.txt with command
WARNING: Project targeting '>= 0.49.2' but tried to use feature introduced in '0.52.0': check arg in gnome.gtkdoc.
Program gtkdoc-scan found: YES (/usr/bin/gtkdoc-scan)
Program gtkdoc-scangobj found: YES (/usr/bin/gtkdoc-scangobj)
Program gtkdoc-mkdb found: YES (/usr/bin/gtkdoc-mkdb)
Program gtkdoc-mkhtml found: YES (/usr/bin/gtkdoc-mkhtml)
Program gtkdoc-fixxref found: YES (/usr/bin/gtkdoc-fixxref)
Program gtkdoc-check found: YES (/usr/bin/gtkdoc-check)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 184, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 223, in _generate
    intr.run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2366, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 132, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 554, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 645, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 224, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1877, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 554, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 645, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 224, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1877, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 257, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 598, in method_call
    return self._holderify(obj.method_call(method_name, args, kwargs))
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 766, in method_call
    ret = method(state, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 645, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 645, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 645, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/modules/gnome.py", line 1140, in gtkdoc
    state.test(check_args, env=check_env, workdir=check_workdir, depends=custom_target)
  File "/usr/lib/python3.9/site-packages/mesonbuild/modules/__init__.py", line 104, in test
    self._interpreter.func_test(self.node, args, kwargs)
AttributeError: 'ModuleState' object has no attribute 'node'
```

**system parameters**
* plain native build
* Arch Linux
* Python 3.9.6
* meson 0.59.99 (commit 5c87167a34c6ed703444af180fffd8a45a7928ee)

**Comment by xclaesse** [comment]
Thanks for testing master, it helps reducing our number of regressions :D

Should be fixed by https://github.com/mesonbuild/meson/pull/9082.
