### ISSUE TITLE
Incorrect handling of -l:LIB.a in pkg-config file

### ISSUE THREAD

**Issue by PlushBeaver** [mesonbuild/meson#9091]
**Describe the bug**
If a .pc file Lib.private contains a flags of the form `-l:libfoo.a`, meson fails to configure.

**To Reproduce**
File tree:
```
repro/
  meson.build
  lib/
    pkgconfig/
      libfoo.pc
  foo.c
  bar.c
```
foo.c: empty
bar.c: `int main() {}`
libfoo.pc:
```
prefix=c:/
libdir=${prefix}/lib
includedir=${prefix}/include
Name: libfoo
Version: 0.1
Description: example
Libs.private: -l:libfoo.a
```
meson.build:
```
project('repro', 'C')
foo = dependency('libfoo', method: 'pkg-config', static: true)
executable('bar', sources: files('bar.c'), dependencies: foo)
```
1. Build libfoo: `clang -c foo.c -o foo.o && llvm-ar rcs lib\libfoo.a foo.o`
2. Try to configure: `meson build`
```
The Meson build system
Version: 0.57.2
Source dir: C:\Users\Administrator\Desktop\test\repro
Build dir: C:\Users\Administrator\Desktop\test\repro\build
Build type: native build
Project name: repro
Project version: undefined
C compiler for the host machine: clang (clang 10.0.0 "clang version 10.0.0 ")
C linker for the host machine: clang link 14.24.28316.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: C:\ProgramData\chocolatey\bin\pkg-config.EXE (0.28)
Traceback (most recent call last):
  File "c:\python\lib\site-packages\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "c:\python\lib\site-packages\mesonbuild\msetup.py", line 279, in run
    app.generate()
  File "c:\python\lib\site-packages\mesonbuild\msetup.py", line 183, in generate
    self._generate(env)
  File "c:\python\lib\site-packages\mesonbuild\msetup.py", line 222, in _generate
    intr.run()
  File "c:\python\lib\site-packages\mesonbuild\interpreter.py", line 4809, in run
    super().run()
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 641, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 666, in evaluate_codeblock
    raise e
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 659, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 674, in evaluate_statement
    self.assignment(cur)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 1341, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 672, in evaluate_statement
    return self.function_call(cur)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 1031, in function_call
    return func(node, func_args, kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 4 more times]
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 210, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreterbase.py", line 229, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreter.py", line 3774, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "c:\python\lib\site-packages\mesonbuild\interpreter.py", line 3868, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "c:\python\lib\site-packages\mesonbuild\dependencies\base.py", line 2432, in find_external_dependency
    d = c()
  File "c:\python\lib\site-packages\mesonbuild\dependencies\base.py", line 645, in __init__
    self._set_libs()
  File "c:\python\lib\site-packages\mesonbuild\dependencies\base.py", line 906, in _set_libs
    self.link_args, self.raw_link_args = self._search_libs(out, out_raw)
  File "c:\python\lib\site-packages\mesonbuild\dependencies\base.py", line 830, in _search_libs
    args = self.clib_compiler.find_library(lib[2:], self.env,
  File "c:\python\lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 1139, in find_library
    return self._find_library_impl(libname, env, extra_dirs, code, libtype)
  File "c:\python\lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 1128, in _find_library_impl
    value = self._find_library_real(libname, env, extra_dirs, code, libtype)
  File "c:\python\lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 1113, in _find_library_real
    trial = self._get_file_from_list(env, trials)
  File "c:\python\lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 1056, in _get_file_from_list
    if p.is_file():
  File "c:\python\lib\pathlib.py", line 1417, in is_file
    return S_ISREG(self.stat().st_mode)
  File "c:\python\lib\pathlib.py", line 1191, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Program Files\\LLVM\\lib\\clang\\10.0.0\\:libfoo.a.a'
```
It looks like meson considers everything after `-l` as a library name without extension, which is wrong.
Also I noticed that with this example path prefix is compiler dir, while in real case it is a proper libdir.
Real .pc file with this form of `-l` is generated with meson 0.57.2 (in a different project).

**Expected behavior**
Meson configuration succeeds.

**System parameters**
* Native build
* Windows 10
* Python 3.8.1
* meson 0.57.2 or 0.59.0
* ninja 1.10.2

**Comment by eli-schwartz** [comment]
Seems like this is a duplicate of #9000 which got a fix merged just yesterday.

Please check if running the git master version of meson succeeds, hopefully the answer is "yes". :)

**Comment by PlushBeaver** [comment]
Sorry for the duplicate. It configures, but the link command is still wrong:
```
PS C:\Users\Administrator\Desktop\test\repro> meson build
The Meson build system
Version: 0.59.99
Source dir: C:\Users\Administrator\Desktop\test\repro
Build dir: C:\Users\Administrator\Desktop\test\repro\build
Build type: native build
Project name: repro
Project version: undefined
C compiler for the host machine: clang (clang 10.0.0 "clang version 10.0.0 ")
C linker for the host machine: clang link 14.24.28316.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: C:\ProgramData\chocolatey\bin\pkg-config.EXE (0.28)
WARNING: Library 'libfoo.a' not found for dependency 'libfoo', may not be successfully linked
Run-time dependency libfoo found: YES 0.1
Build targets in project: 1

Found ninja-1.10.2 at "C:\Program Files\Meson\ninja.EXE"
PS C:\Users\Administrator\Desktop\test\repro> ninja -Cbuild
ninja: Entering directory `build'
[2/2] Linking target bar.exe
FAILED: bar.exe bar.pdb
"clang"  -Wl,/MACHINE:X64 -Wl,/OUT:bar.exe bar.exe.p/bar.c.obj "-Wl,/nologo" "-Wl,/release" "-Wl,/nologo" "-Wl,/DEBUG" "-Wl,/PDB:bar.pdb" "-l:libfoo.a" "-Wl,/SUBSYSTEM:CONSOLE" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32"
LINK : fatal error LNK1181: cannot open input file ':libfoo.a.lib'
clang: error: linker command failed with exit code 1181 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by PlushBeaver** [comment]
I should have read the warning. Seems like an issue with the example, the real project (same as in #9000) configures OK.

**Comment by eli-schwartz** [comment]
Excellent, thanks for confirming the fix allows you to successfully build your project on windows too. ;)
