### ISSUE TITLE
meson traceback with RuntimeError("generator didn't yield")

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#9093]
Déjà vu, #2689. 

```console
$ ninja -C build-clang
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 200, in _generate
    intr.run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 4715, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 519, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 544, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 537, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 554, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 922, in method_call
    (args, kwargs) = self.reduce_arguments(node.args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 1183, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]  # type: T.List[TYPE_nvar]
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 1183, in <listcomp>
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]  # type: T.List[TYPE_nvar]
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 554, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 951, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 56, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase.py", line 228, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter.py", line 1431, in sizeof_method
    esize = self.compiler.sizeof(element, prefix, self.environment,
  File "/usr/lib/python3.9/site-packages/mesonbuild/compilers/mixins/clike.py", line 610, in sizeof
    res = self.run(t.format(**fargs), env, extra_args=extra_args,
  File "/usr/lib/python3.9/site-packages/mesonbuild/compilers/mixins/clike.py", line 472, in run
    with self._build_wrapper(code, env, extra_args, dependencies, mode='link', want_output=True) as p:
  File "/usr/lib64/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/site-packages/mesonbuild/compilers/compilers.py", line 1180, in _build_wrapper
    with self.compile(code, extra_args=args, mode=mode, want_output=want_output, temp_dir=env.scratch_dir) as r:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
FAILED: build.ninja 
/usr/bin/meson --internal regenerate /home/zbyszek/src/systemd /home/zbyszek/src/systemd/build-clang --backend ninja
ninja: error: rebuilding 'build.ninja': subcommand failed
```

meson-0.56.2-2.fc34.noarch
python3-3.9.6-2.fc34.x86_64

I'll keep the builddir around, in case more info is needed.

**Comment by bonzini** [comment]
In 0.56.2 this could happen due to

```
-        except OSError:
-            # On Windows antivirus programs and the like hold on to files so
-            # they can't be deleted. There's not much to do in this case. Also,
-            # catch OSError because the directory is then no longer empty.
-            return
```

Fixed in 0.57.0 by abc7e6af01714206100a752898c325282436501f
