### ISSUE TITLE
GTK4 build setup fails on Windows 10 due to erroneous path

### ISSUE THREAD

**Issue by lempamo** [mesonbuild/meson#9127]
**Describe the bug**
I have Python 3.9, Meson 0.5.9, MSYS2, and the latest versions of the packages necessary for installation, yet it fails because of an invalid path that I found inside of 'sanitycheckc.exe'. The path in question is "D:\\a\\_temp\\msys\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\x86_64-w64-mingw32\\10.3.0". Invalid because D: is my disc drive, which was empty at the time I attempted installation. I was told this was a bug with meson rather than anything in the GTK repo, so I'm posting this here.

Console log: https://gist.github.com/lempamo/acdef79225973caf6f7e6bd7537ff37b

**To Reproduce**
Simply clone the GTK repository and run 'meson setup build'.

**Expected behavior**
Build setup should complete without error.

**Comment by eli-schwartz** [comment]
This is produced by compilers/mixins/gnu.py _get_search_dirs() returning this directory somehow in the output of:

```
gcc --print-search-dirs
```

It seems strange that a non-existing directory is reported here, can you confirm the output?

**Comment by lempamo** [comment]
```
install: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/
programs: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/x86_64-w64-mingw32/10.3.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/
libraries: =C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/;C:/msys64/mingw64/bin/../lib/gcc/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/x86_64-w64-mingw32/10.3.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../x86_64-w64-mingw32/10.3.0/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../lib/;D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/lib/x86_64-w64-mingw32/10.3.0/;D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/lib/../lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/;C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../;D:/a/_temp/msys/msys64/mingw64/x86_64-w64-mingw32/lib/
```

it's in there. the question is why?

**Comment by eli-schwartz** [comment]
The MSYS2 people would probably know best.

**Comment by pineapplemachine** [comment]
I am experiencing this issue, too. It is definitely in part due to msys putting nonsense paths into gcc's search directories.

**However,** I was able to get meson working for me on my system by making it a little more resilient in the face of awkward results when asking for gcc's search directories. I would like to suggest making this or a similar change to meson:

Replace this line in `mesonbuild\compilers\mixins\gnu.py`:

``` python
if pobj.exists():
```

With these lines:

``` python
exists = False
try:
    exists = pobj.exists()
except:
    pass 
if exists:
```

Curiously, it seems like even checking whether a path exists can produce an exception on Windows in some situations, when one might have expected the function to just return False.

@eli-schwartz

**Comment by eli-schwartz** [comment]
Well, the exception makes sense. You can get a similar exception on Linux:

```python
>>> import pathlib
>>> pathlib.Path('\0').stat()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
ValueError: embedded null byte
```

It should be noted in `pathlib._IGNORED_WINERRORS`, 87 (The parameter is incorrect) is not listed as something to ignore (`.stat()` does not ignore errors, but `.exists()` will... sometimes). I wonder why -- maybe the Python developers would be interested in considering this?

I would still like to know if the MSYS team is going to fix their compiler's leaky build environment paths though...

**Comment by judemille** [comment]
This error still exists -- it has been two years, now. I don't know what the best solution is, but I would like to get this fixed.

**Comment by gregsskyles** [comment]
As noted above, it's an MSYS2 bug, so you are asking in the wrong place. It should probably be closed here as WONT_FIX.
