### ISSUE TITLE
vs backend doesn't handle alias targets

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#9247]
Hi,

Using meson 0.59.0-318-g214d03568 I tried to build my WIP postgres-meson branch with visual studio. Despites lots of other issues that failed because of the presence of an alias_target().

A simple repro follows:

meson.build:
```
project('repro', ['c'],
	version : '0.1',
	meson_version: '>=0.59.99')

sometarget = custom_target('bleat', command: ['cmd', '/s', '/c', 'echo', 'foo'], capture: true, output: ['bleat'])
alias_target('noisy', [sometarget])
```

invocation and failure:
```
C:\Users\anfreund\src\meson-vs-repro>python C:\Users\anfreund\src\meson\meson.py setup --backend vs2019 --wipe build-x64
The Meson build system
Version: 0.59.99
Source dir: C:\Users\anfreund\src\meson-vs-repro
Build dir: C:\Users\anfreund\src\meson-vs-repro\build-x64
Build type: native build
Project name: repro
Project version: 0.1
C compiler for the host machine: cl (msvc 19.29.30133 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64")
C linker for the host machine: link link 14.29.30133.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program cmd found: YES (C:\Windows\system32\cmd.EXE)
Build targets in project: 2

repro 0.1

  User defined options
    backend: vs2019

Traceback (most recent call last):
  File "C:\Users\anfreund\src\meson\mesonbuild\mesonmain.py", line 228, in run
    return options.run_func(options)
  File "C:\Users\anfreund\src\meson\mesonbuild\msetup.py", line 290, in run
    app.generate()
  File "C:\Users\anfreund\src\meson\mesonbuild\msetup.py", line 181, in generate
    self._generate(env)
  File "C:\Users\anfreund\src\meson\mesonbuild\msetup.py", line 243, in _generate
    intr.backend.generate()
  File "C:\Users\anfreund\src\meson\mesonbuild\backend\vs2010backend.py", line 212, in generate
    projlist = self.generate_projects()
  File "C:\Users\anfreund\src\meson\mesonbuild\backend\vs2010backend.py", line 447, in generate_projects
    self.gen_vcxproj(target, str(projfile_path), proj_uuid)
  File "C:\Users\anfreund\src\meson\mesonbuild\backend\vs2010backend.py", line 788, in gen_vcxproj
    return self.gen_run_target_vcxproj(target, ofname, guid)
  File "C:\Users\anfreund\src\meson\mesonbuild\backend\vs2010backend.py", line 561, in gen_run_target_vcxproj
    wrapper_cmd, _ = self.as_meson_exe_cmdline(target.command[0], cmd_raw[1:],
IndexError: list index out of range
```

This problem didn't use to exist. I bisected it down to 71784e1002fe7a5507111273d78ddc8ed654e8de (CC @jpakkane).

The problem is that the
``` 
        if not target.command:
            # FIXME: This is an alias target that doesn't run any command, there
            # is probably a better way than running a this dummy command.
            cmd_raw = python_command + ['-c', 'exit']
```
hack doesn't do the trick anymore because target.command[0] is explicitly referenced:
```
        wrapper_cmd, _ = self.as_meson_exe_cmdline(target.command[0], cmd_raw[1:],
                                                   force_serialize=True, env=target_env,
                                                   verbose=True)
```

Regards,

Andres

**Comment by anarazel** [comment]
Oh, the fix may be trivial: Need to use `cmd[0]` as the first argument to `as_meson_exe_cmdline()`. I guess I need to figure out how to get a regression test on windows running to test that (I'm not a windows person by any stretch).

**Comment by xclaesse** [comment]
It's a bit more complicated than that. The reason we pass `target.command[0]` here is because we need the actual object for the executable instead of the path string that cmd_raw[0] contains.

**Comment by anarazel** [comment]
@xclaesse That's relevant for run targets and not alias targets, right? I was thinking of a change like
```
nd.py
index 13cd546db..bc9143d69 100644
--- a/mesonbuild/backend/vs2010backend.py
+++ b/mesonbuild/backend/vs2010backend.py
@@ -554,11 +554,15 @@ class Vs2010Backend(backends.Backend):
             # FIXME: This is an alias target that doesn't run any command, there
             # is probably a better way than running a this dummy command.
             cmd_raw = python_command + ['-c', 'exit']
+            exe = cmd_raw[0]
+            args = cmd_raw[1:]
         else:
             _, _, cmd_raw = self.eval_custom_target_command(target)
+            exe = target.command[0]
+            args = cmd_raw[1:]
         depend_files = self.get_custom_target_depend_files(target)
         target_env = self.get_run_target_env(target)
-        wrapper_cmd, _ = self.as_meson_exe_cmdline(target.command[0], cmd_raw[1:],
+        wrapper_cmd, _ = self.as_meson_exe_cmdline(exe, args,
                                                    force_serialize=True, env=target_env,
                                                    verbose=True)
         self.add_custom_build(root, 'run_target', ' '.join(self.quote_arguments(wrapper_cmd)),
```
which seems to work for both alias and run targets.

But perhaps the better fix would be to just implement alias targets differently from run targets? I don't know much about msbuild, nor about meson's vs backend, but it seems like it works to just not emit the CustomBuild. As far as I understand meson's vs backend it doesn't use dependencies between targets and dependencies between target names, but instead just has different projects that are referenced. As long as the alias target emits the project references, they're going to be built afaict.

**Comment by xclaesse** [comment]
@anarazel that looks good if you can open a PR. If you found a way to not run a dummy command that would be even better.
