### ISSUE TITLE
Parallel 'meson build' run failed

### ISSUE THREAD

**Issue by skartashev** [mesonbuild/meson#9403]
**Describe the bug**
When I run 2 'meson build' processes in parallel on CI server, one process crashes on 'Activating VS' stage:

```
> meson build
Traceback (most recent call last):
	File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
		return _run_code(code, main_globals, None,
	File "C:\Python39\lib\runpy.py", line 87, in _run_code
		exec(code, run_globals)
	File "C:\Python39\Scripts\meson.exe\__main__.py", line 7, in <module>
	File "C:\Python39\lib\site-packages\mesonbuild\mesonmain.py", line 319, in main
		setup_vsenv()
	File "C:\Python39\lib\site-packages\mesonbuild\mesonmain.py", line 108, in setup_vsenv
		bat_file.unlink()
	File "C:\Python39\lib\pathlib.py", line 1354, in unlink
		self._accessor.unlink(self)
	FileNotFoundError: [WinError 2] The system cannot find the file specified: '...\\vsdetect.bat'

```

**To Reproduce**
`meson builddir1 | meson builddir2`

**Expected behavior**
'meson builddir' works well in parallel

**system parameters**
* Windows 10
* Python 3.9
* meson 0.59.2

**Comment by JamBalaya56562** [comment]
Thank you for the report. The VS-environment activation no longer uses a fixed `vsdetect.bat` filename — it now creates a unique temporary `.bat` (and env file) per invocation and removes them afterwards, so concurrent `meson setup` runs no longer race on a shared file.

```python
# mesonbuild/utils/vsenv.py — _setup_vsenv()
with tempfile.NamedTemporaryFile(delete=False) as env_file:
    ...
with tempfile.NamedTemporaryFile('w', suffix='.bat', encoding='utf-8', delete=False) as bat_file:
    ...
finally:
    windows_proof_rm(env_file.name)
    windows_proof_rm(bat_file.name)
```

**Verification:** `_setup_vsenv()` in `mesonbuild/utils/vsenv.py` uses per-invocation `tempfile.NamedTemporaryFile(...)` and cleans up with `windows_proof_rm`; the maintainer noted this was fixed in 0.60.0-rc1.

The fixed-name `vsdetect.bat` that caused the parallel `FileNotFoundError` is gone, so this looks safe to close. Thanks for reporting it.
