### ISSUE TITLE
REGRESSION: GES GIR build broke with d9473095f234df54a9a531a859cb745bc349c5c2

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#947]
Since d9473095f234df54a9a531a859cb745bc349c5c2 GES GIR can't build because g-ir-scanner is not building against gstreamer-1.0:

```
[2014/2261] 'Generating GES-1.0.gir with a custom command.'
FAILED: subprojects/gst-editing-services/ges/GES-1.0.gir 
'g-ir-scanner' '../subprojects/gst-editing-services/ges/ges.c' '../subprojects/gst-editing-services/ges/ges-enums.c' '../subprojects/gst-editing-services/ges/ges-meta-container.c' '../subprojects/gst-editing-services/ges/ges-timeline.c' '../subprojects/gst-editing-services/ges/ges-layer.c' '../subprojects/gst-editing-services/ges/ges-clip.c' '../subprojects/gst-editing-services/ges/ges-pipeline.c' '../subprojects/gst-editing-services/ges/ges-source-clip.c' '../subprojects/gst-editing-services/ges/ges-base-effect-clip.c' '../subprojects/gst-editing-services/ges/ges-effect-clip.c' '../subprojects/gst-editing-services/ges/ges-uri-clip.c' '../subprojects/gst-editing-services/ges/ges-operation-clip.c' '../subprojects/gst-editing-services/ges/ges-base-transition-clip.c' '../subprojects/gst-editing-services/ges/ges-transition-clip.c' '../subprojects/gst-editing-services/ges/ges-test-clip.c' '../subprojects/gst-editing-services/ges/ges-title-clip.c' '../subprojects/gst-editing-services/ges/ges-overlay-clip.c' '../subprojects/gst-editing-services/ges/ges-text-overlay-clip.c' '../subprojects/gst-editing-services/ges/ges-track.c' '../subprojects/gst-editing-services/ges/ges-audio-track.c' '../subprojects/gst-editing-services/ges/ges-video-track.c' '../subprojects/gst-editing-services/ges/ges-track-element.c' '../subprojects/gst-editing-services/ges/ges-source.c' '../subprojects/gst-editing-services/ges/ges-operation.c' '../subprojects/gst-editing-services/ges/ges-video-source.c' '../subprojects/gst-editing-services/ges/ges-audio-source.c' '../subprojects/gst-editing-services/ges/ges-video-uri-source.c' '../subprojects/gst-editing-services/ges/ges-audio-uri-source.c' '../subprojects/gst-editing-services/ges/ges-image-source.c' '../subprojects/gst-editing-services/ges/ges-multi-file-source.c' '../subprojects/gst-editing-services/ges/ges-transition.c' '../subprojects/gst-editing-services/ges/ges-audio-transition.c' '../subprojects/gst-editing-services/ges/ges-video-transition.c' '../subprojects/gst-editing-services/ges/ges-video-test-source.c' '../subprojects/gst-editing-services/ges/ges-audio-test-source.c' '../subprojects/gst-editing-services/ges/ges-title-source.c' '../subprojects/gst-editing-services/ges/ges-text-overlay.c' '../subprojects/gst-editing-services/ges/ges-base-effect.c' '../subprojects/gst-editing-services/ges/ges-effect.c' '../subprojects/gst-editing-services/ges/ges-screenshot.c' '../subprojects/gst-editing-services/ges/ges-formatter.c' '../subprojects/gst-editing-services/ges/ges-pitivi-formatter.c' '../subprojects/gst-editing-services/ges/ges-asset.c' '../subprojects/gst-editing-services/ges/ges-uri-asset.c' '../subprojects/gst-editing-services/ges/ges-clip-asset.c' '../subprojects/gst-editing-services/ges/ges-track-element-asset.c' '../subprojects/gst-editing-services/ges/ges-extractable.c' '../subprojects/gst-editing-services/ges/ges-project.c' '../subprojects/gst-editing-services/ges/ges-base-xml-formatter.c' '../subprojects/gst-editing-services/ges/ges-xml-formatter.c' '../subprojects/gst-editing-services/ges/ges-command-line-formatter.c' '../subprojects/gst-editing-services/ges/ges-auto-transition.c' '../subprojects/gst-editing-services/ges/ges-timeline-element.c' '../subprojects/gst-editing-services/ges/ges-container.c' '../subprojects/gst-editing-services/ges/ges-effect-asset.c' '../subprojects/gst-editing-services/ges/ges-smart-adder.c' '../subprojects/gst-editing-services/ges/ges-smart-video-mixer.c' '../subprojects/gst-editing-services/ges/ges-utils.c' '../subprojects/gst-editing-services/ges/ges-group.c' '../subprojects/gst-editing-services/ges/ges-validate.c' '../subprojects/gst-editing-services/ges/ges-structured-interface.c' '../subprojects/gst-editing-services/ges/ges-structure-parser.c' '../subprojects/gst-editing-services/ges/gstframepositioner.c' '../subprojects/gst-editing-services/ges/ges-types.h' '../subprojects/gst-editing-services/ges/ges.h' '../subprojects/gst-editing-services/ges/ges-enums.h' '../subprojects/gst-editing-services/ges/ges-gerror.h' '../subprojects/gst-editing-services/ges/ges-meta-container.h' '../subprojects/gst-editing-services/ges/ges-timeline.h' '../subprojects/gst-editing-services/ges/ges-layer.h' '../subprojects/gst-editing-services/ges/ges-clip.h' '../subprojects/gst-editing-services/ges/ges-pipeline.h' '../subprojects/gst-editing-services/ges/ges-source-clip.h' '../subprojects/gst-editing-services/ges/ges-uri-clip.h' '../subprojects/gst-editing-services/ges/ges-base-effect-clip.h' '../subprojects/gst-editing-services/ges/ges-effect-clip.h' '../subprojects/gst-editing-services/ges/ges-operation-clip.h' '../subprojects/gst-editing-services/ges/ges-base-transition-clip.h' '../subprojects/gst-editing-services/ges/ges-transition-clip.h' '../subprojects/gst-editing-services/ges/ges-test-clip.h' '../subprojects/gst-editing-services/ges/ges-title-clip.h' '../subprojects/gst-editing-services/ges/ges-overlay-clip.h' '../subprojects/gst-editing-services/ges/ges-text-overlay-clip.h' '../subprojects/gst-editing-services/ges/ges-base-effect.h' '../subprojects/gst-editing-services/ges/ges-effect.h' '../subprojects/gst-editing-services/ges/ges-track.h' '../subprojects/gst-editing-services/ges/ges-audio-track.h' '../subprojects/gst-editing-services/ges/ges-video-track.h' '../subprojects/gst-editing-services/ges/ges-track-element.h' '../subprojects/gst-editing-services/ges/ges-source.h' '../subprojects/gst-editing-services/ges/ges-operation.h' '../subprojects/gst-editing-services/ges/ges-video-source.h' '../subprojects/gst-editing-services/ges/ges-audio-source.h' '../subprojects/gst-editing-services/ges/ges-video-uri-source.h' '../subprojects/gst-editing-services/ges/ges-audio-uri-source.h' '../subprojects/gst-editing-services/ges/ges-image-source.h' '../subprojects/gst-editing-services/ges/ges-multi-file-source.h' '../subprojects/gst-editing-services/ges/ges-transition.h' '../subprojects/gst-editing-services/ges/ges-audio-transition.h' '../subprojects/gst-editing-services/ges/ges-video-transition.h' '../subprojects/gst-editing-services/ges/ges-video-test-source.h' '../subprojects/gst-editing-services/ges/ges-audio-test-source.h' '../subprojects/gst-editing-services/ges/ges-title-source.h' '../subprojects/gst-editing-services/ges/ges-text-overlay.h' '../subprojects/gst-editing-services/ges/ges-screenshot.h' '../subprojects/gst-editing-services/ges/ges-formatter.h' '../subprojects/gst-editing-services/ges/ges-pitivi-formatter.h' '../subprojects/gst-editing-services/ges/ges-asset.h' '../subprojects/gst-editing-services/ges/ges-uri-asset.h' '../subprojects/gst-editing-services/ges/ges-clip-asset.h' '../subprojects/gst-editing-services/ges/ges-track-element-asset.h' '../subprojects/gst-editing-services/ges/ges-extractable.h' '../subprojects/gst-editing-services/ges/ges-project.h' '../subprojects/gst-editing-services/ges/ges-base-xml-formatter.h' '../subprojects/gst-editing-services/ges/ges-xml-formatter.h' '../subprojects/gst-editing-services/ges/ges-command-line-formatter.h' '../subprojects/gst-editing-services/ges/ges-timeline-element.h' '../subprojects/gst-editing-services/ges/ges-container.h' '../subprojects/gst-editing-services/ges/ges-effect-asset.h' '../subprojects/gst-editing-services/ges/ges-smart-adder.h' '../subprojects/gst-editing-services/ges/ges-utils.h' '../subprojects/gst-editing-services/ges/ges-group.h' '-pthread' '-I/usr/include/gobject-introspection-1.0' '-I/usr/lib/libffi-3.2.1/include' '-I/usr/include/glib-2.0' '-I/usr/lib/glib-2.0/include' '--no-libtool' '--namespace=GES' '--nsversion=1.0' '--warn-all' '--output' 'subprojects/gst-editing-services/ges/GES-1.0.gir' '--add-init-section=extern void gst_init(gint*,gchar**); gst_init(NULL,NULL);' '--c-include=ges/ges.h' '--cflags-begin' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-editing-services/ges/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-editing-services/ges/..' '--cflags-end' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-editing-services/ges' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-editing-services/ges' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-editing-services/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-editing-services/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-devtools/validate/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-devtools/validate/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '--include=Gst-1.0' '--include=GstPbutils-1.0' '--include=GstVideo-1.0' '--include=Gio-2.0' '--symbol-prefix=ges' '--identifier-prefix=GES' '--pkg-export=ges-1.0' 'gst-libs' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/libs' '-I/usr/include/orc-0.4' '.' '/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-plugins-base/gst-libs' '-pthread' '-I/usr/include/libxml2' '-I/usr/include/glib-2.0' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-plugins-base/gst-libs' '-I/usr/include/json-glib-1.0' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/libs' 'libs' '-I/usr/lib/glib-2.0/include' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gst-devtools/validate/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-devtools/validate/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/subprojects/gstreamer/.' '-I/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/..' 'parse' '--add-include-path=/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst' '--add-include-path=/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-devtools/validate/gst/validate' '-L/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gst-editing-services/ges' '--library' 'ges-1.0'
/usr/sbin/ld: tmp-introspectpkze6qtk/var/lib/jenkins/workspace/GStreamer-master-meson/build/tmp-introspectpkze6qtk/GES-1.0.o: undefined reference to symbol 'gst_init'
/var/lib/jenkins/workspace/GStreamer-master-meson/build/subprojects/gstreamer/gst/libgstreamer-1.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 196, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

Full build log: https://ci.gstreamer.net/job/GStreamer-master-meson/307/console

**Comment by nirbheek** [comment]
Didn't we fix this already with 3c48bd2d88e94db2c9f6e714b7b320889a5dcb38?

**Comment by thiblahute** [comment]
Yeah 'fixed' :) we should follow up to fix the issue properly though.

**Comment by TingPing** [comment]
Closing this as the regression was reverted and an issue over the core problem was opened.
