### ISSUE TITLE
[Bug] meson failed to compile with ubuntu 18.04 on launchpad build

### ISSUE THREAD

**Issue by souravdas142** [mesonbuild/meson#9505]
**Describe the bug**

I was trying to build meson with ubuntu 18.04 on launchpad . But it is continuously failing to  build. Always test error. For more details see the [launchpad build log](https://launchpad.net/~pipewire-debian/+archive/ubuntu/bionic-qt5125/+build/22357414/+files/buildlog_ubuntu-bionic-amd64.meson_0.60.0.r15.gc9e6afc-1~ubuntu18.04_BUILDING.txt.gz)

I'd tried to build from release and from the latest branch 0.60 both are failing. I can successfully build the same with ubuntu >= 20.04

**Expected behavior**

Test is failing. I think you can understand seeing the above mentioned launchpad build log properly.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) ubuntu 18.04
* what Python version are you using e.g. 3.6.9
* what `meson --version` 0.58
* what `ninja --version` if it's a Ninja build 1.10.2

**Comment by eli-schwartz** [comment]
> Test is failing. I think you can understand seeing the above mentioned launchpad build log properly.

Can you not assume that and just report the part of that log that is failing? There are 85k lines there and I can't even grep for the word "failed" because that appears over a hundred times and none of the succeeding tests are collapsing/hiding their logs.

**Comment by souravdas142** [comment]
Sorry for that.  [This log](https://launchpadlibrarian.net/566488331/buildlog_ubuntu-bionic-amd64.meson_0.60.0.r15.gc9e6afc-6~ubuntu18.04_BUILDING.txt.gz) is more cleaner and shorter version of build log. I think you can understand. There are lots of error. I don't understand which one should i mention Can you please try to reproduce the same for ubuntu 18.04 ?. You can also see the [launchpad ubuntu daily build of meson](https://launchpad.net/~ubuntu-support-team/+archive/ubuntu/meson/+packages) also can't build and so that they didn't published.

**Comment by eli-schwartz** [comment]
I don't use operating systems that are produced by the company known as Canonical. However, meson's own CI runners test every commit on Ubuntu Bionic, Ubuntu Latest, Fedora, openSUSE, and Arch Linux. The tests pass. So your test failures are more specific than just "can you try to run the tests on Ubuntu 18.04 and see if they fail" -- maybe a question of the tools you have installed, maybe a question of your unique environment, I don't know.

I will try to look at your log later today. But really, it would be very helpful if you followed standard bug reporting procedures and distilled relevant details, then posted relevant excerpts, directly to the ticket you are reporting -- this both ensures that transient attachments from third-party hosting don't disappear from the record, and allows the project maintainers to get a much more focused look at what your problem is.

**Comment by souravdas142** [comment]
> I don't use operating systems that are produced by the company known as Canonical

me too. :wink:  using arch personally. making packages for ubuntu thats another story and out of context. In short you know ubuntu family are very slow in updating packages and thats why I am trying to fill the gap since last april. My only focus on "PipeWire for ubuntu" thats it.

At the time of reporting there  few depencies were missing and providing them still its failed actually I take the official recipie from [daily build of meson on launchpad](https://launchpad.net/~ubuntu-support-team/+archive/ubuntu/meson/+packages) and was trying to build on ubuntu 18.04. So if CI is not failing then I should look at [bionic CI](https://github.com/mesonbuild/meson/blob/master/ci/ciimage/bionic/install.sh) this may fix the problem. OKK I will report you back  if thing goes well. 

Still sorry for everything and Its my utmost respect to devs to build this all. Thank you.

**Comment by eli-schwartz** [comment]
Alright, thanks. The new build log (only 8k lines) is a lot clearer. The relevant bits look like this:

```
/usr/bin/python3 /<<PKGBUILDDIR>>/meson.py --internal coverage '/<<PKGBUILDDIR>>/test cases/common/105 generatorcustom' '/<<PKGBUILDDIR>>/test cases/common/105 generatorcustom/subprojects' /<<PKGBUILDDIR>>/tmpomhzrkbl /<<PKGBUILDDIR>>/tmpomhzrkbl/meson-logs
LLVM (http://llvm.org/):
  LLVM version 6.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: bdver1
lcov: LCOV version 1.13
genhtml: LCOV version 1.13
Usage: gcovr [options]

gcovr: error: no such option: --sonarqube
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/meson.py", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 235, in main
    return run(sys.argv[1:], launcher)
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 224, in run
    return run_script_command(args[1], args[2:])
  File "/<<PKGBUILDDIR>>/mesonbuild/mesonmain.py", line 172, in run_script_command
    return module.run(script_args)
  File "/<<PKGBUILDDIR>>/mesonbuild/scripts/coverage.py", line 184, in run
    options.log_dir, options.use_llvm_cov)
  File "/<<PKGBUILDDIR>>/mesonbuild/scripts/coverage.py", line 55, in coverage
    ] + gcov_exe_args)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcovr', '-r', '/<<PKGBUILDDIR>>/tmpomhzrkbl', '--sonarqube', '-o', '/<<PKGBUILDDIR>>/tmpomhzrkbl/meson-logs/sonarqube.xml', '-e', '\\/build\\/meson\\-isi7wc\\/meson\\-0\\.60\\.0\\.r15\\.gc9e6afc\\/test\\ cases\\/common\\/105\\ generatorcustom\\/subprojects']' returned non-zero exit status 2.
ninja: build stopped: subcommand failed.
```

The version of `gcovr` installed in this build VM does not support --sonarqube, added in https://github.com/gcovr/gcovr/commit/702aa38edb52d7f03d1063db3b0de003af741e83 back in mid-2019 in gcovr 4.2 and added to meson 0.60 in commit 2e30b5a1e2ca21555bb3aa50f91e87f4d2821bb6.

The funny thing is that the tool claims it will only attempt to generate coverage reports for output formats which your gcovr version supports. However, this is FALSE. It unconditionally adds all of them, and the only version check is to find out whether it needs syntax changes to point to the builddir.

That's definitely a bug, albeit one which could be solved by upgrading gcovr.

**Comment by eli-schwartz** [comment]
Can you test my linked PR?

**Comment by souravdas142** [comment]
> Can you test my linked PR?

Yeah everything is fine and build successfully thanks.

**Comment by eli-schwartz** [comment]
Yay!
