### ISSUE TITLE
meson test: UnicodeEncodeError in non-unicode locale

### ISSUE THREAD

**Issue by anarazel** [mesonbuild/meson#9538]
Hi,

When meson test reports progress interactively, and a non-unicode locale is in use, a UnicodeEncodeError is encountered / shown. I originally encountered this while trying to see if postgres builds with meson on AIX, but it repros on linux as well.

**To Reproduce**
```
$ cat ../meson.build 
project('repro', ['c'])

test('echo', find_program('echo'), args: 'foo')

$ LANG=en_US ~/src/meson/meson.py test
ninja: Entering directory `/tmp/repro-meson-src/build'
ninja: no work to do.
1/1 echo        OK              0.00s
Traceback (most recent call last):
  File "/home/andres/src/meson/mesonbuild/mesonmain.py", line 139, in run
    return options.run_func(options)
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 2006, in run
    return th.doit()
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 1686, in doit
    self.run_tests(runners)
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 1825, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 1928, in _run_tests
    await l.finish(self)
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 684, in finish
    await self.progress_task
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 589, in report_progress
    self.emit_progress(harness)
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 559, in emit_progress
    self.print_progress(line)
  File "/home/andres/src/meson/mesonbuild/mtest.py", line 523, in print_progress
    print(self.should_erase_line, line, sep='', end='\r')
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f311' in position 6: ordinal not in range(256)

$ LANG=en_US.UTF-8 ~/src/meson/meson.py test
ninja: Entering directory `/tmp/repro-meson-src/build'
ninja: no work to do.
1/1 echo        OK              0.00s


Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /tmp/repro-meson-src/build/meson-logs/testlog.txt
```

**Expected behavior**
meson test should work in non-unicode locales, or at least produce a more helpful error message.

**system parameters**
* plain
* debian sid, x64
* python 3.9
* recent git checkout 5af556e2b

**Comment by eli-schwartz** [comment]
@bonzini
