### ISSUE TITLE
Missing _bootlocale in Windows MSI in meson 0.60.1

### ISSUE THREAD

**Issue by peterh** [mesonbuild/meson#9548]
When trying to configure any project with meson 0.60.1 on Windows installed from the provided Release MSI, I receive the following error:

```
The Meson build system
Version: 0.60.1
Source dir: C:\src\etx\src
Build dir: C:\src\etx\vbuild2
Build type: native build
Project name: project
Project version: undefined
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 138, in run
  File "mesonbuild\msetup.py", line 294, in run
  File "mesonbuild\msetup.py", line 185, in generate
  File "mesonbuild\msetup.py", line 207, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 297, in __init__
  File "mesonbuild\interpreterbase\interpreterbase.py", line 118, in parse_project
  File "mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 179, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 454, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 276, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1130, in func_project
  File "mesonbuild\interpreter\interpreter.py", line 1257, in add_languages
  File "mesonbuild\interpreter\interpreter.py", line 1295, in add_languages_for
  File "mesonbuild\compilers\detect.py", line 215, in detect_compiler_for
  File "mesonbuild\compilers\detect.py", line 212, in compiler_from_language
  File "mesonbuild\compilers\detect.py", line 623, in detect_c_compiler
  File "mesonbuild\compilers\detect.py", line 403, in _detect_c_or_cpp_compiler
  File "mesonbuild\mesonlib\universal.py", line 1385, in Popen_safe
  File "locale.py", line 628, in getpreferredencoding
ModuleNotFoundError: No module named '_bootlocale'
```

This happens both with and without --backend=vs. Discovered while testing vs2022, but I don't think the VS version matters as meson does not reach that part of the configuration (and vs2022 works fine with ninja in 0.60.0).

This is a regression from the 0.60.0 Release MSI.

**Comment by jortbmd** [comment]
Same for me:
When trying out the basic example found on the meson tutorial page, when running the meson builddir command. I get the following error: ModuleNotFoundError: No module named '_bootlocale'.

The output:

The Meson build system
Version: 0.60.1
Source dir: C:\LEFTOUT\meson_local_target_test_build
Build dir: C:\LEFTOUT\meson_local_target_test_build\builddir
Build type: native build
Project name: meson_local_target_test
Project version: 1.0
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 138, in run
  File "mesonbuild\msetup.py", line 294, in run
  File "mesonbuild\msetup.py", line 185, in generate
  File "mesonbuild\msetup.py", line 207, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 297, in __init__
  File "mesonbuild\interpreterbase\interpreterbase.py", line 118, in parse_project
  File "mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 179, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 454, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
  File "mesonbuild\interpreterbase\decorators.py", line 276, in wrapper
  File "mesonbuild\interpreter\interpreter.py", line 1130, in func_project
  File "mesonbuild\interpreter\interpreter.py", line 1257, in add_languages
  File "mesonbuild\interpreter\interpreter.py", line 1295, in add_languages_for
  File "mesonbuild\compilers\detect.py", line 215, in detect_compiler_for
  File "mesonbuild\compilers\detect.py", line 212, in compiler_from_language
  File "mesonbuild\compilers\detect.py", line 623, in detect_c_compiler
  File "mesonbuild\compilers\detect.py", line 403, in _detect_c_or_cpp_compiler
  File "mesonbuild\mesonlib\universal.py", line 1385, in Popen_safe
  File "locale.py", line 628, in getpreferredencoding
ModuleNotFoundError: No module named '_bootlocale'
Python version: Python 3.10.0
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.19041 N/A Build 19041

**Comment by Bxaa** [comment]
+

**Comment by jpakkane** [comment]
I created a test version with a fix. Could someone try if [this](https://www.dropbox.com/s/ptghny2cjzgyzru/meson-0.60.1.1-64.msi?dl=0) works for them?

**Comment by jortbmd** [comment]
Thanks for creating a fix!
I am fine with testing, however I am uncomfortable with downloading an .exe from a dropbox link. If you create a pull request and point me to it I am happy to test it from there.

**Comment by TheIronWolfModding** [comment]
@jpakkane - _bootlocale issue fixed for me, thank you!

**Comment by jpakkane** [comment]
The  linked PR has the fix, the release page has been updated with a new installer. It's the same as the dropbox one so if you already installed it you don't have to do anything.

**Comment by peterh** [comment]
The new installer on the release page fixes the issue for me (although "Windows Defender" detects it as "Trojan:Win32/Wacatac.B!ml", presumably a false positive?)

Thanks for the quick fix.

**Comment by lygstate** [comment]
So is me.
