### ISSUE TITLE
"TypeError: sequence item 0: expected str instance, File found"

### ISSUE THREAD

**Issue by nnamua** [mesonbuild/meson#9651]
**Describe the bug**

Generated automatically. Please see #9646 for a detailed description.
A minimal working example can be found below. ..

```
Traceback (most recent call last):
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\mesonmain.py", line 138, in run
    return options.run_func(options)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 294, in run
    app.generate()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 229, in _generate
    intr.run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2484, in run
    super().run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 183, in evaluate_statement
    return self.method_call(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 482, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\baseobjects.py", line 90, in method_call
    return method(args, kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 546, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\mesonmain.py", line 155, in add_install_script_method
    script = self._find_source_script(args[0], script_args)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\mesonmain.py", line 89, in _find_source_script
    found = self.interpreter.func_find_program({}, prog, {})
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 96, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1483, in func_find_program
    return self.find_program_impl(args, for_machine, required=required,
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1398, in find_program_impl
    progobj = self.notfound_program(args)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1386, in notfound_program
    return NonExistingExternalProgram(' '.join(args))
TypeError: sequence item 0: expected str instance, File found
```
**To Reproduce**
```meson
project('generated', ['c', 'java'])

obj = files('foo.c')[0]
RXHYNUBcku = [obj]
sPbHlahqKm = meson
KZSpUstqmQ = true
sPbHlahqKm.add_install_script(obj,obj,skip_if_destdir : KZSpUstqmQ)
UvoCRPdgBX = meson
QvZbaUcxvS = 'String'
EfQbPWutuv = true
UvoCRPdgBX.add_install_script(obj,QvZbaUcxvS,skip_if_destdir : EfQbPWutuv)
UfMSLlffvt = meson
PJoZjgBwPR = 'script.py'
LbBMDEaWMY = true
UfMSLlffvt.add_install_script(PJoZjgBwPR,obj,skip_if_destdir : LbBMDEaWMY)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')
```
**Expected behaviour**

No crash.

**System parameters**
```
The Meson build system
Version: 0.60.1
Build type: native build
C compiler for the host machine: gcc (gcc 8.3.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
C linker for the host machine: gcc ld.bfd 2.32
Java compiler for the host machine: javac (unknown 17.0.1)
Host machine cpu family: x86_64
Host machine cpu: x86_64
```

**Comment by nnamua** [comment]
The following buildfile results in the same last trace line:

```meson
project('generated', ['c', 'java'])

obj = files('foo.c')[0]
oBKrmfFVOk = [obj]
EsheKnbyRb = meson
EsheKnbyRb.add_postconf_script(obj,obj)
wjHHDQXxGv = meson
JEBzXXRaVH = 'String'
wjHHDQXxGv.add_postconf_script(obj,JEBzXXRaVH)
VHhXiLQKyv = meson
IIMxWjdByh = 'script.py'
VHhXiLQKyv.add_postconf_script(IIMxWjdByh,obj)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')

```

**Comment by nnamua** [comment]
The following buildfile results in the same last trace line:

```meson
project('generated', ['c', 'java'])

obj = files('foo.c')[0]
UGybyXKPMP = [obj]
pDmnINyDJN = meson
pDmnINyDJN.add_dist_script(obj,obj)
JvYVTwWOKK = meson
ZZTUYaZapw = 'String'
JvYVTwWOKK.add_dist_script(obj,ZZTUYaZapw)
CSAtBFdvgh = meson
xKiVIbQxZK = 'script.py'
CSAtBFdvgh.add_dist_script(xKiVIbQxZK,obj)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')

```

**Comment by nnamua** [comment]
The following buildfile results in the same last trace line:

```meson
project('generated', ['c', 'java'])

obj = configure_file(input : 'config.h.in', output: 'config.h', configuration: configuration_data())
YMfwnXVWug = [obj]
qiBEPhTVYq = meson
qiBEPhTVYq.add_postconf_script(obj,obj)
gRaIiEzalW = meson
aGmJDQqjuF = 'String'
gRaIiEzalW.add_postconf_script(obj,aGmJDQqjuF)
wJPSAdeojW = meson
SBVeonRDwn = 'script.py'
wJPSAdeojW.add_postconf_script(SBVeonRDwn,obj)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')

```

**Comment by nnamua** [comment]
The following buildfile results in the same last trace line:

```meson
project('generated', ['c', 'java'])

obj = configure_file(input : 'config.h.in', output: 'config.h', configuration: configuration_data())
YBMmdKXITp = [obj]
PAgWWQKpmh = meson
dujytWRwOw = true
PAgWWQKpmh.add_install_script(obj,obj,skip_if_destdir : dujytWRwOw)
FgIjelcnmJ = meson
OgnAGxsCRd = 'String'
GyzHhBavzg = true
FgIjelcnmJ.add_install_script(obj,OgnAGxsCRd,skip_if_destdir : GyzHhBavzg)
QNaTOmpqPT = meson
ZMfgXNyeVF = 'script.py'
slSJsJnDUW = true
QNaTOmpqPT.add_install_script(ZMfgXNyeVF,obj,skip_if_destdir : slSJsJnDUW)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')

```

**Comment by nnamua** [comment]
The following buildfile results in the same last trace line:

```meson
project('generated', ['c', 'java'])

obj = configure_file(input : 'config.h.in', output: 'config.h', configuration: configuration_data())
EQuMEblWXh = [obj]
uQCwFQznSk = meson
uQCwFQznSk.add_dist_script(obj,obj)
ufFVsfWMkH = meson
XRoCOwBfwC = 'String'
ufFVsfWMkH.add_dist_script(obj,XRoCOwBfwC)
omlwQBtgTE = meson
JGXIZqvQmF = 'script.py'
omlwQBtgTE.add_dist_script(JGXIZqvQmF,obj)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')

```

**Comment by eli-schwartz** [comment]
In the latest version of Meson, this now errors out with e.g.

```
meson.build:3:0: ERROR: File foo.c does not exist.
```

or

```
meson.build:3:0: ERROR: File config.h.in does not exist.
```
