### ISSUE TITLE
"TypeError: argument of type 'CustomTargetIndex' is not iterable"

### ISSUE THREAD

**Issue by nnamua** [mesonbuild/meson#9657]
**Describe the bug**

Generated automatically. Please see #9646 for a detailed description.
A minimal working example can be found below. ..

```
Traceback (most recent call last):
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\mesonmain.py", line 138, in run
    return options.run_func(options)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 294, in run
    app.generate()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 229, in _generate
    intr.run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2484, in run
    super().run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 51, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1647, in func_vcs_tag
    return self._func_custom_target_impl(node, [kwargs['output']], kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1731, in _func_custom_target_impl
    tg = build.CustomTarget(name, self.subdir, self.subproject, kwargs, backend=self.backend)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\build.py", line 2325, in __init__
    super().__init__(name, subdir, subproject, False, MachineChoice.HOST)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\build.py", line 511, in __init__
    if has_path_sep(name):
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1012, in has_path_sep
    if each in name:
TypeError: argument of type 'CustomTargetIndex' is not iterable
```
**To Reproduce**
```meson
project('generated', ['c', 'java'])

obj = custom_target('MvmAYYIGxK', output : 'bar.c', input : 'bar.txt', command : [ find_program('script.py'), '@INPUT@', '@OUTPUT@'])[0]
XAZaNcKVPj = [obj]
UbtGYVCaAe = 'String'
jvyHpnasWt = 'String'
ZuWUjUbzxP = 'String'
vcs_tag(command : UbtGYVCaAe,fallback : jvyHpnasWt,input : obj,output : obj,replace_string : ZuWUjUbzxP)
IYTrkEmyxX = find_program('python3')
fhkmwiLwwE = 'String'
ieMdVLFbzX = 'String'
vcs_tag(command : IYTrkEmyxX,fallback : fhkmwiLwwE,input : obj,output : obj,replace_string : ieMdVLFbzX)
JpMGxfycYE = 'String'
aPdAJdSziV = 'String'
vcs_tag(command : XAZaNcKVPj,fallback : JpMGxfycYE,input : obj,output : obj,replace_string : aPdAJdSziV)
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')
```
**Expected behaviour**

No crash.

**System parameters**
```
The Meson build system
Version: 0.60.1
Build type: native build
C compiler for the host machine: gcc (gcc 8.3.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
C linker for the host machine: gcc ld.bfd 2.32
Java compiler for the host machine: javac (unknown 17.0.1)
Host machine cpu family: x86_64
Host machine cpu: x86_64
```

**Comment by eli-schwartz** [comment]
In the latest version of Meson this errors out with e.g.

```
meson.build:8:0: ERROR: vcs_tag keyword argument 'output' was of type array[CustomTargetIndex] but should have been array[str] that cannot be empty
```
