### ISSUE TITLE
"TypeError: expected str, bytes or os.PathLike object, not File"

### ISSUE THREAD

**Issue by nnamua** [mesonbuild/meson#9663]
**Describe the bug**

Generated automatically. Please see #9646 for a detailed description.
A minimal working example can be found below. ..

```
Traceback (most recent call last):
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\mesonmain.py", line 138, in run
    return options.run_func(options)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 294, in run
    app.generate()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\msetup.py", line 229, in _generate
    intr.run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2484, in run
    super().run()
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 713, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 51, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1626, in func_vcs_tag
    vcs_cmd[0] = shutil.which(vcs_cmd[0]) or os.path.join(source_dir, vcs_cmd[0])
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\shutil.py", line 1390, in which
    if os.path.dirname(cmd):
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "c:\users\paulo\appdata\local\programs\python\python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not File
```
**To Reproduce**
```meson
project('generated', ['c', 'java'])

qiGBSyfzwh = files('foo.c', 'bar.c')
lpqogzfoPa = 'String'
PiubmfgWhR = files('foo.c')[0]
tZLANJnVzR = files('foo.c')[0]
QkDkgiGIqm = 'String'
oCRymWOkPv = vcs_tag(command : qiGBSyfzwh,fallback : lpqogzfoPa,input : PiubmfgWhR,output : tZLANJnVzR,replace_string : QkDkgiGIqm)
PvJjiiqaCa = 0
oCRymWOkPv[PvJjiiqaCa]
oCRymWOkPv.full_path()
oCRymWOkPv.to_list()
error('This error is produced to speed up checks and can be ignored ($IGNORE$)')
```
**Expected behaviour**

No crash.

**System parameters**
```
The Meson build system
Version: 0.60.1
Build type: native build
C compiler for the host machine: gcc (gcc 8.3.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
C linker for the host machine: gcc ld.bfd 2.32
Java compiler for the host machine: javac (unknown 17.0.1)
Host machine cpu family: x86_64
Host machine cpu: x86_64
```

**Comment by eli-schwartz** [comment]
In the latest version of Meson, this now errors out with:

```
meson.build:3:0: ERROR: File foo.c does not exist.
```
