### ISSUE TITLE
AssertionError: In funcion qt.compile_resources default value of name is not a valid type

### ISSUE THREAD

**Issue by deepbluev7** [mesonbuild/meson#9698]
**Describe the bug**
When using `qt5.compile_resources` without a name, I get an assertion error (with a typo).

**To Reproduce**

Use qt5.compile_resources without the name argument, i.e. like so:

```
project(
  'nheko',
  'cpp',
        default_options : ['cpp_std=c++17', 'b_pie=true', 'default_library=static']
)

qt5 = import('qt5')
qt5_dep = dependency('qt5', modules: ['Core', 'Qml', 'Quick', 'DBus', 'Multimedia', 'Svg'], include_type: 'system')
inc = include_directories('src')

deps = [
        qt5_dep,
]

sources = [
        'src/main.cpp',
    ]

resources = qt5.compile_resources(sources: 'resources/res.qrc')

executable('nheko',
        sources, resources,
        include_directories: inc,
        dependencies : deps,
        install: true)
```

This prints the following assertion:

```
Run-time dependency qt5 (modules: Core) found: YES 5.15.2 (pkg-config)
Program /usr/lib64/qt5/bin/moc found: YES 5.15.2 (/usr/lib64/qt5/bin/moc)
Program /usr/lib64/qt5/bin/uic found: YES 5.15.2 (/usr/lib64/qt5/bin/uic)
Program /usr/lib64/qt5/bin/rcc found: YES 5.15.2 (/usr/lib64/qt5/bin/rcc)
Program /usr/lib64/qt5/bin/lrelease found: YES 5.15.2 (/usr/lib64/qt5/bin/lrelease)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 138, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2485, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 183, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 482, in method_call
    res = obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 754, in method_call
    ret = method(state, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 621, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 51, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 536, in wrapper
    assert check_value_type(info.default), f'In funcion {name} default value of {info.name} is not a valid type, got {type(info.default)} expected {types_description()}'
AssertionError: In funcion qt.compile_resources default value of name is not a valid type, got <class 'NoneType'> expected str
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 138, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mcompile.py", line 324, in run
    cdata = coredata.load(options.wd)
  File "/usr/lib/python3.9/site-packages/mesonbuild/coredata.py", line 1030, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nicolas/Dokumente/devel/open-source/nheko/builddir/meson-private/coredata.dat'
```

Adding `name: 'res'` as an argument to compile_resources fixes that.

**Expected behavior**
I would have expected either meson to generate a name, since the name can be empty or it providing me with a readable error message.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?: native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Gentoo
* what Python version are you using e.g. 3.8.0: 3.9.0
* what `meson --version`: 60.2
* what `ninja --version` if it's a Ninja build: 1.10.2

**Comment by deepbluev7** [comment]
Thank you for the quick fix! <3
