### ISSUE TITLE
The exception with `meson wrap update jsoncpp`

### ISSUE THREAD

**Issue by H5117** [mesonbuild/meson#9760]
**Describe the bug**
The exception is raised with `meson wrap update jsoncpp`

**To Reproduce**
```bash
$ ls subprojects/
fmt.wrap  libarchive.wrap  openssl.wrap  yaml-cpp.wrap  zlib.wrap

$ meson wrap install jsoncpp
Installed jsoncpp version 1.9.5 revision 1

$ meson wrap update jsoncpp
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 138, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/wrap/wraptool.py", line 223, in run
    options.wrap_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/wrap/wraptool.py", line 142, in update
    (branch, revision, subdir, src_file, patch_file) = get_current_version(wrapfile)
  File "/usr/lib/python3.10/site-packages/mesonbuild/wrap/wraptool.py", line 126, in get_current_version
    patch_url = wrap_data['patch_url']
  File "/usr/lib/python3.10/configparser.py", line 1258, in __getitem__
    raise KeyError(key)
KeyError: 'patch_url'
```

**Expected behavior**
The exception should not happen.

**system parameters**
Native build
Arch Linux
Python 3.10.1
Meson 0.60.3
Ninja 1.10.2

**Comment by tristan957** [comment]
Is this still happening on latest Meson?

cc @eli-schwartz

**Comment by H5117** [comment]
Still something wrong:
```bash
$ meson wrap install jsoncpp
Installed jsoncpp version 1.9.5 revision 2
$ meson wrap update jsoncpp
Checking latest WrapDB version for jsoncpp...
  -> Could not determine current version, use --force to update any way
WARNING: Please check logs above as command failed in some subprojects which could have been left in conflict state: jsoncpp
```
Arch Linux
Python 3.10.9-1
Meson 1.0.1-1
Ninja 1.11.1-2

**Comment by xclaesse** [comment]
That's expected, meson does not remember which version of the wrap is installed, so it cannot know if it is up to date or not. --force will download latest version anyway. With wraps updated more recently, the version got added into the wrap file.
