### ISSUE TITLE
mpv Build issue

### ISSUE THREAD

**Issue by AcoUk** [mesonbuild/meson#9815]
**Describe the bug**
meson.build:18:0: ERROR: Unhandled python exception
    This is a Meson bug and should be reported!

**To Reproduce**
Build mpv

**Expected behavior**
a valid build as in v. 0.60.3

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* no
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* macOS Big Sur
* what Python version are you using e.g. 3.8.0
* 3.8
* what `meson --version`
* 0.61.0
* what `ninja --version` if it's a Ninja build
1.10.2

log
[meson-log.txt](https://github.com/mesonbuild/meson/files/7855579/meson-log.txt)

**Comment by eli-schwartz** [comment]
Can you also post the actual error message, in addition to merely posting the statement that the error message should be reported?

**Comment by LAbyOne** [comment]
all is into the attached build log no other specifications given.

**Comment by AcoUk** [comment]
All info i got are present in the attached log, no other specific notes given.

**Comment by eli-schwartz** [comment]
The attached log has a tremendous amount of detail on the compiler checks run etc. and so forth, but is missing the one thing important here, which is the python traceback.

**Comment by AcoUk** [comment]
i see, maybe this is the one?
[meson-Traceback.txt](https://github.com/mesonbuild/meson/files/7857095/meson-Traceback.txt)

**Comment by nirbheek** [comment]
```
Program python3 found: YES (/Volumes/FFmpeg-master//bin/python3)
Found pkg-config: /Volumes/FFmpeg-master//bin/pkg-config (0.29.2)
Run-time dependency libavutil found: YES 57.9.100
Run-time dependency libavcodec found: YES 59.13.100
Run-time dependency libavformat found: YES 59.9.101
Run-time dependency libswscale found: YES 6.1.100
Traceback (most recent call last):
...
  File "/Volumes/FFmpeg-master/lib/python3.8/site-packages/mesonbuild/dependencies/pkgconfig.py", line 115, in _call_pkgbin_real
    p, out, err = Popen_safe(cmd, env=env)
  File "/Volumes/FFmpeg-master/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1395, in Popen_safe
    o, e = p.communicate(write)
  File "/Volumes/FFmpeg-master/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Volumes/FFmpeg-master/lib/python3.8/subprocess.py", line 1904, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/Volumes/FFmpeg-master/lib/python3.8/subprocess.py", line 901, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 260: invalid continuation byte
```

Looks like there might be a corrupted pkgconfig file somewhere. The [next dependency() check after `libswscale` is `libavfilter`](https://github.com/mpv-player/mpv/blob/master/meson.build#L23). Can you paste the output of `pkg-config --libs --cflags libavfilter`?

**Comment by eli-schwartz** [comment]
@AcoUk yes, that's exactly what I was looking for. Thanks.

I'm not sure what the problem is but nirbheek is probably on to something. That call really shouldn't be able to fail. :/

**Comment by AcoUk** [comment]
@nirbheek 
here it is,
-I/Volumes/FFmpeg-master//include -L/Volumes/FFmpeg-master//lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/ffmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/\¬\†/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master/lib -L -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/ffmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/ffmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/FFmpeg-master//lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master/lib -L/Volumes/ffmpeg-master//lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master//lib -L/Volumes/ffmpeg-master/lib -L/Volumes/FFmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/ffmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/FFmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/FFmpeg-master//lib -L/Volumes/FFmpeg-master/lib -L/Volumes/FFmpeg-master//lib -lavfilter -framework OpenGL -lm -lrubberband -lstdc++ -lmysofa -lz -lm -lflite_cmu_time_awb -lflite_cmu_us_awb -lflite_cmu_us_kal -lflite_cmu_us_kal16 -lflite_cmu_us_rms -lflite_cmu_us_slt -lflite_usenglish -lflite_cmulex -lflite -lfribidi -lvmaf -lm -pthread -lass -lm -liconv -lfribidi -lfreetype -lbz2 -lpng16 -lz -lharfbuzz -lm -lvidstab -lzmq -lstdc++ -lsodium -lzimg -lstdc++ -framework CoreImage -framework AppKit -Wl,-framework,OpenCL -lfontconfig -lexpat -lfreetype -lpng -lexpat -lfreetype -lbz2 -lpng16 -lz -lharfbuzz -lm -lfreetype -lbz2 -lpng16 -lz -lharfbuzz -lm -lswscale -lm -lpostproc -lm -lavformat -lm -lbz2 -lmodplug -lstdc++ -lm -lbluray -framework CoreFoundation -framework DiskArbitration -lxml2 -lpthread -lz -liconv -lm -lz -lssl -lcrypto -lsrt -lc++ -lssl -lcrypto -lzmq -lstdc++ -lsodium -lavcodec -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -liconv -lm -llzma -ldav1d -lopencore-amrwb -lsnappy -lstdc++ -lz -framework AudioToolbox -laom -lm -lpthread -lfdk-aac -lgsm -lilbc -pthread -lmp3lame -lm -lopencore-amrnb -lopus -lrav1e -liconv -lSystem -lresolv -lc -lm -lshine -lspeex -ltheoraenc -ltheoradec -logg -ltwolame -lvorbis -lm -logg -lvorbisenc -lvorbis -lm -logg -lx264 -lpthread -lm -ldl -lx265 -lc++ -ldl -lxavs -pthread -lm -lxvidcore -lopenh264 -lstdc++ -pthread -lkvazaar -framework VideoToolbox -framework CoreFoundation -framework CoreMedia -framework CoreVideo -framework CoreServices -lswresample -lm -lsoxr -lavutil -pthread -lm -Wl,-framework,OpenCL -framework VideoToolbox -framework CoreFoundation -framework CoreMedia -framework CoreVideo -framework CoreServices

**Comment by nirbheek** [comment]
> `-L/Volumes/ffmpeg-master/\¬\†/lib`

That's your problem right there. The file has invalid unicode. Also why the heck does it have so many identical `-L` arguments?!

**Comment by nirbheek** [comment]
I guess maybe we should be using surrogateescape or something to decode unicode from untrusted files?

**Comment by AcoUk** [comment]
> > `-L/Volumes/ffmpeg-master/\¬\†/lib`
> 
> That's your problem right there. The file has invalid unicode. Also why the heck does it have so many identical `-L` arguments?!

it totally surprised me too, seeing all those repeated arguments, never noticed before, and frankly cannot understand why this is happening..
Curious thing is with v. 0.60.3 version the build had no issue..

**Comment by moi15moi** [comment]
I believe you got this problem because before this fix (https://github.com/pkgconf/pkgconf/pull/533), pkgconf was escaping each bytes which was breaking non ascii character.
With a recent version of pkgconf, you shouldnt be able to reproduce this issue.
