### ISSUE TITLE
Cross-compile with python as a dependency (Unhandled python exception)

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/meson#9842]
I want to cross-compile a meson project for Android. My project is in C++ with pybind11 python bindings, but I can't figure out how to include the python library.

My cross file looks like this:
```
[binaries]
c       = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang'
cpp     = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++'
ar      = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'
as      = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-as'
ranlib  = '/path-to-android-ndk/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib'
strip   = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip'
pkgconfig = ['pkg-config', '--env-only']

[properties]
sys_root = '/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot'
needs_exe_wrapper = false

[built-in options]
pkg_config_path = ['/path-to-android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/pkgconfig/']

[host_machine]
system = 'android'
cpu_family = 'arm'
cpu = 'aarch64'
endian = 'little'
```

The `pkg_config_path` is where I tried to include the python library. I can build successfully, but when I compile, then I get the error:
```
../subprojects/pybind11-2.6.0/include/pybind11/detail/common.h:122:10: fatal error: 'Python.h' file not found
```

I can also compile my project without pybind, and when I do it compiles successfully, but then the `meson test` fails with this lengthy `Unhandled python exception` error:
```
[0/1] Running all tests.
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/test/myproject_tests'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/test/myproject_tests'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/walkthrough.cpp'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/walkthrough2.cpp'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/examples/example2'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe...ormat error')>) at /home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py:1853>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/examples/example1'


Ok:                 0   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/meson-logs/testlog.txt
Traceback (most recent call last):
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 2011, in run
    return th.doit()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1688, in doit
    self.run_tests(runners)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1827, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1924, in _run_tests
    await complete_all(futures)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1194, in complete_all
    check_futures(done)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1184, in check_futures
    f.result()
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1855, in test_done
    f.result()
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1850, in run_test
    res = await test.run(self)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1394, in run
    await self._run_cmd(harness, cmd)
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1448, in _run_cmd
    p = await self._run_subprocess(cmd + extra_cmd,
  File "/home/djacobs/.local/lib/python3.9/site-packages/mesonbuild/mtest.py", line 1422, in _run_subprocess
    p = await asyncio.create_subprocess_exec(*args,
  File "/usr/lib64/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib64/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib64/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/djacobs/AndroidStudioProjects/MyProject/app/src/main/cpp/myproject/build/test/myproject_tests'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-test 
/home/djacobs/.local/bin/meson test --no-rebuild --print-errorlogs
```

I feel like it's unlikely this is an actual meson bug, and more likely because meson can't find python.

**Comment by danielcjacobs** [comment]
I believe this error is because I built for Android, but I'm trying to run the tests on my Fedora machine, so it fails when meson tries to call the tests.
