### ISSUE TITLE
"GCOV did not produce any data" when test program references source code in parent directory

### ISSUE THREAD

**Issue by yoursunny** [mesonbuild/meson#9844]
If the project defines a test `executable` in a subdirectory that references source code files in a parent directory, code coverage extraction does not work.

## To Reproduce

**/meson.build**

```meson
project('proj', 'cpp',
  default_options: [
    'warning_level=2',
    'cpp_std=c++11',
    'cpp_eh=none',
    'cpp_rtti=false'
  ])

subdir('unittest')
```

**/main.cpp**

```cpp
int main()
{
  int x = 1;
  --x;
  return x;
}
```

**/unittest/meson.build**

```meson
exe = executable('program',
  '../main.cpp'
)
test('program', exe)
```

**Command and Output**

```shell
ubuntu@ndndev:~/C$ meson build -Db_coverage=true
The Meson build system
Version: 0.61.1
Source dir: /home/ubuntu/C
Build dir: /home/ubuntu/C/build
Build type: native build
Project name: proj
Project version: undefined
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

proj undefined

  User defined options
    b_coverage: true

Found ninja-1.10.0 at /usr/bin/ninja
LLVM (http://llvm.org/):
  LLVM version 11.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
lcov: LCOV version 1.14
genhtml: LCOV version 1.14
ubuntu@ndndev:~/C$ ninja -C build test
ninja: Entering directory `build'
[2/3] Running all tests.
1/1 program        OK              0.00s


Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/ubuntu/C/build/meson-logs/testlog.txt
ubuntu@ndndev:~/C$ ninja -C build coverage
ninja: Entering directory `build'
[1/1] Generates coverage reports
FAILED: meson-coverage 
/usr/local/bin/meson --internal coverage /home/ubuntu/C /home/ubuntu/C/subprojects /home/ubuntu/C/build /home/ubuntu/C/build/meson-logs
LLVM (http://llvm.org/):
  LLVM version 11.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
lcov: LCOV version 1.14
genhtml: LCOV version 1.14
Capturing coverage data from /home/ubuntu/C/build
Found gcov version: 9.3.0
Using intermediate gcov format
Scanning /home/ubuntu/C/build for .gcno files ...
Found 1 graph files in /home/ubuntu/C/build
Processing .._main.cpp.gcno
geninfo: WARNING: GCOV did not produce any data for /home/ubuntu/C/build/unittest/program.p/.._main.cpp.gcno
Finished .info-file creation
Capturing coverage data from /home/ubuntu/C/build
Found gcov version: 9.3.0
Using intermediate gcov format
Scanning /home/ubuntu/C/build for .gcda files ...
Found 1 data files in /home/ubuntu/C/build
Processing .._main.cpp.gcda
geninfo: WARNING: GCOV did not produce any data for /home/ubuntu/C/build/unittest/program.p/.._main.cpp.gcda
Finished .info-file creation
lcov: ERROR: no valid records found in tracefile /home/ubuntu/C/build/meson-logs/coverage.info.initial
Combining tracefiles.
Reading tracefile /home/ubuntu/C/build/meson-logs/coverage.info.initial
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/mesonmain.py", line 252, in main
    return run(sys.argv[1:], launcher)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/mesonmain.py", line 241, in run
    return run_script_command(args[1], args[2:])
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/mesonmain.py", line 189, in run_script_command
    return module.run(script_args)
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/scripts/coverage.py", line 182, in run
    return coverage(options.outputs, options.source_root,
  File "/usr/local/lib/python3.8/dist-packages/mesonbuild/scripts/coverage.py", line 108, in coverage
    subprocess.check_call([lcov_exe,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lcov', '-a', '/home/ubuntu/C/build/meson-logs/coverage.info.initial', '-a', '/home/ubuntu/C/build/meson-logs/coverage.info.run', '--rc', 'lcov_branch_coverage=1', '-o', '/home/ubuntu/C/build/meson-logs/coverage.info.raw']' returned non-zero exit status 255.
ninja: build stopped: subcommand failed.
```

I have confirmed that `/home/ubuntu/C/build/unittest/program.p/.._main.cpp.gcno` and /home/ubuntu/C/build/unittest/program.p/.._main.cpp.gcda` files both exist.

## Expected behavior
Code coverage is extracted successfully, reporting 100% line coverage.

## System Parameters

* This is a native build.
* Ubuntu 20.04 amd64, running in a LXC container on Linux kernel 5.10
* Python 3.8.10
* Meson 0.61.1
* Ninja 1.10.0
* gcov (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* LCOV version 1.14

## Additional Information

The same input works correctly on my other machine with a different environment:

* Ubuntu 18.04 amd64, dedicated server
* Python 3.6.9
* Meson 0.61.1
* Ninja 1.10.2.git.kitware.jobserver-1
* gcov (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* LCOV version 1.13

On both machines, this issue does not occur if I move `/main.cpp` to `/unittest/main.cpp`.

**Comment by eli-schwartz** [comment]
This is a bug in lcov itself, see https://github.com/linux-test-project/lcov/issues/168 lcov uses a glob operator that ignores files beginning with a dot.

There's a fix in lcov now.
