### ISSUE TITLE
Can't build Meson Documentation

### ISSUE THREAD

**Issue by BioBox** [mesonbuild/meson#9873]
**Describe the bug**
I can't compile the meson documentation, though I followed the README as best I could.

**To Reproduce**
The `meson.build` file is unchanged from the github clone.

**Expected behavior**
Not getting an error.

**system parameters**
* Plain build
* Manjaro
* python 3.10.1
* meson 0.61.1
* ninja 1.10.2
* hotdoc version is 0.13.7 btw

```
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/hotdoc/run_hotdoc.py", line 294, in execute_command
    app.run()
  File "/usr/lib/python3.10/site-packages/hotdoc/run_hotdoc.py", line 107, in run
    self.project.setup()
  File "/usr/lib/python3.10/site-packages/hotdoc/core/project.py", line 183, in setup
    extension.setup()
  File "/home/daniel/downs/infobuilds/meson/docs/extensions/refman_links.py", line 94, in setup
    raw = Path(self._data_file).read_text(encoding='utf-8')
  File "/usr/lib/python3.10/pathlib.py", line 1132, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/daniel/downs/infobuilds/meson/docs/built_docs/refman_links.json'
while executing ['/usr/bin/hotdoc', 'run', '--conf-file', '/home/daniel/downs/infobuilds/meson/docs/built_docs/Meson documentation-doc.json', '--git-upload', '-vv']
FAILED: meson-upload 
/usr/bin/meson --internal exe --unpickle /home/daniel/downs/infobuilds/meson/docs/built_docs/meson-private/meson_exe_hotdoc_cf70f7c7c9f9f02d3b865ba2bd1f0998223a8a37.dat
ninja: build stopped: subcommand failed.
```

**Comment by eli-schwartz** [comment]
Why are you running `ninja upload`? That is only meant for, well, git cloning the mesonbuild.github.io repository and committing+pushing new contents.

`ninja` will build the docs by default, or `ninja Meson\ documentation-doc` will build just the hotdoc documentation without the (very rapidly finished) json/manpage exports.

**Comment by eli-schwartz** [comment]
Needs commit a038fa80f5a4f6954fe3c0b39c8602c78a7898a2 to actually build successfully on systems with python 3.10, though...

**Comment by eli-schwartz** [comment]
docs/README.md was wrong (since #4275), and I have changed that.
