### ISSUE TITLE
Meson has IndexError: list index out of range when CC='ccache'

### ISSUE THREAD

**Issue by CoderThomasB** [mesonbuild/meson#9933]
**Describe the bug**
When the CC environment variable is set to `ccache` meson will return an error even throw 'ccache'  is installed.
This is the error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/usr/lib/python3.10/site-packages/mesonbuild/msetup.py", line 207, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 307, in __init__
    self.parse_project()
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 118, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreterbase/decorators.py", line 573, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 1170, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 1299, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "/usr/lib/python3.10/site-packages/mesonbuild/interpreter/interpreter.py", line 1337, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine)
  File "/usr/lib/python3.10/site-packages/mesonbuild/compilers/detect.py", line 215, in detect_compiler_for
    comp = compiler_from_language(env, lang, for_machine)
  File "/usr/lib/python3.10/site-packages/mesonbuild/compilers/detect.py", line 212, in compiler_from_language
    return lang_map[lang](env, for_machine) if lang in lang_map else None
  File "/usr/lib/python3.10/site-packages/mesonbuild/compilers/detect.py", line 631, in detect_c_compiler
    return _detect_c_or_cpp_compiler(env, 'c', for_machine)
  File "/usr/lib/python3.10/site-packages/mesonbuild/compilers/detect.py", line 364, in _detect_c_or_cpp_compiler
    compiler_name = os.path.basename(compiler[0])
IndexError: list index out of range
```

**To Reproduce**
Run `export CC='ccache'` then run meson in the same terminal.

**Expected behavior**
Meson will tell the user to add a compiler to the CC variable. Eg `export CC='ccache gcc'` 

**system parameters**
* Arch OS
* Python 3.10.2
* meson 0.61.1
* ninja 1.10.2

**Comment by dcbaker** [comment]
We can fix the error, but ccache expects a compiler as a first argument, such as “ccache gcc”

**Comment by CoderThomasB** [comment]
> We can fix the error, but ccache expects a compiler as a first argument, such as “ccache gcc”

Ok, I have updated the issue with a new 'Expected behavior'
